name = "stackwise-indexer-worker"
main = "worker/index.js"
compatibility_date = "2026-07-24"

[triggers]
crons = ["0 */12 * * *"] # Runs automatically 2x daily (every 12 hours) on Cloudflare Edge

[[d1_databases]]
binding = "DB"
database_name = "stakdock-db"
database_id = "00000000-0000-0000-0000-000000000000"
