name = "stackwisefinds"
pages_build_output_dir = "dist"
compatibility_date = "2026-07-24"

[[d1_databases]]
binding = "DB"
database_name = "stakdock-db"
database_id = "c488f494-001c-4348-8b80-f15e12e2bba4"


