/**
 * StakDock 2.0: Stack Builder Dashboard Component (Phase 6B.1)
 *
 * Professional Software Intelligence Dashboard providing:
 * - True Cost Modeling (Software Subscriptions vs Server Compute vs Variable Quotas)
 * - Granular Overlap Detection & Advisory
 * - Multi-State Integration Graph
 * - Interactive Deterministic Tool Swapping
 * - Claim-Level Primary Source Inspection
 * - One-Click Markdown Export
 * - Clean Accessibility & Keyboard Navigation (Escape key, ARIA)
 */

import React, { useState, useEffect } from 'react';
import {
  DollarSign,
  Layers,
  Server,
  Shield,
  ExternalLink,
  RefreshCw,
  Copy,
  Check,
  AlertTriangle,
  Info,
  Sliders,
  CheckCircle2,
  X,
  ArrowUpRight,
  TrendingDown,
  Cpu,
  ChevronRight,
  HelpCircle,
  FileText,
  Code2
} from 'lucide-react';
import {
  getAvailableToolsForCapability,
  calculateToolCost
} from '../../utils/stackIntelligenceEngine.js';
import {
  trackProductEvent,
  trackAffiliateClick
} from '../../utils/affiliateTracker.js';

export default function StackDashboard({
  stackResult,
  wizardState,
  onUpdateWizardState,
  onSwapTool,
  onRemoveCapability,
  onAddCapability,
  onRestartWizard
}) {
  const [swappingCapability, setSwappingCapability] = useState(null);
  const [inspectingTool, setInspectingTool] = useState(null);
  const [copiedToast, setCopiedToast] = useState(false);
  const [activeTab, setActiveTab] = useState('stack'); // 'stack' | 'cost' | 'overlap' | 'integrations'

  const {
    status,
    inputSummary,
    costSummary,
    confidenceSummary,
    recommendedStack,
    overlapAnalysis,
    integrationMatrix,
    warnings,
    unknowns,
    filterConflicts
  } = stackResult;

  // Track stack generation and budget conflict on mount
  useEffect(() => {
    trackProductEvent('stack_generated', {
      business_profile: inputSummary.businessType,
      team_size: inputSummary.teamSize,
      budget: inputSummary.monthlyBudgetUsd,
      budget_type: inputSummary.budgetConstraintType,
      estimated_monthly_spend: costSummary.totalNewMonthlyCost,
      recommendation_confidence: confidenceSummary.recommendationConfidence,
      cost_confidence: confidenceSummary.costConfidence,
      tool_count: recommendedStack.length,
      status
    });
    if (status === 'NO_STACK_WITHIN_BUDGET') {
      trackProductEvent('budget_conflict', {
        budget: inputSummary.monthlyBudgetUsd,
        closest_spend: costSummary.totalNewMonthlyCost,
        gap: costSummary.budgetGapUsd
      });
    }
  }, []);

  // Keyboard accessibility: Escape key closes active modals
  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.key === 'Escape') {
        setSwappingCapability(null);
        setInspectingTool(null);
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, []);

  // Handle Export / Copy Stack Markdown
  const handleCopyMarkdown = () => {
    trackProductEvent('stack_exported', {
      format: 'markdown',
      tool_count: recommendedStack.length,
      estimated_monthly_spend: costSummary.totalNewMonthlyCost,
      business_profile: inputSummary.businessType
    });

    let md = `# StakDock Recommended Software Stack\n`;
    md += `**Operating Profile:** ${inputSummary.businessType.replace('_', ' ')} | **Team Size:** ${inputSummary.teamSize} seats\n`;
    md += `**New Incremental Software Spend:** $${costSummary.totalNewMonthlyCost.toFixed(2)}/mo ($${costSummary.totalNewAnnualCost.toFixed(2)}/yr)\n`;
    if (costSummary.existingToolsMonthlyCost) {
      md += `**Pre-Owned Tools Spend:** ${costSummary.existingToolsMonthlyCost}\n`;
    }
    md += `**Recommendation Confidence:** ${confidenceSummary.recommendationConfidence} | **Cost Confidence:** ${confidenceSummary.costConfidence}\n`;
    md += `**Budget Status:** ${costSummary.fitAssessment}\n\n`;

    if (costSummary.budgetGapExplanation) {
      md += `> **Budget Notice:** ${costSummary.budgetGapExplanation}\n\n`;
    }

    md += `## Software Stack Composition\n\n`;

    recommendedStack.forEach(item => {
      md += `### ${item.capability}: ${item.selectedTool.name}\n`;
      md += `- **Monthly Cost:** $${item.selectedTool.monthlyCost.toFixed(2)}/mo (${item.selectedTool.costCalculationDetails})\n`;
      md += `- **Hosting & License:** ${item.selectedTool.hostingType} (${item.selectedTool.licensing?.licenseType || 'Proprietary'})\n`;
      md += `- **Selection Rationale:** ${item.selectedTool.whyItFits}\n`;
      if (item.selectedTool.freeTierUncertaintyNote) {
        md += `- **Usage Notice:** ${item.selectedTool.freeTierUncertaintyNote}\n`;
      }
      md += `\n`;
    });

    if (overlapAnalysis.length > 0) {
      md += `## Capability Overlap Analysis\n`;
      overlapAnalysis.forEach(o => {
        md += `- **${o.pair.join(' ↔ ')} (${o.level}):** ${o.details}\n`;
      });
      md += `\n`;
    }

    md += `---\n*Generated by StakDock Software Intelligence (stakdock.com) • Pricing source checked ${confidenceSummary.pricingCheckedDate}*`;

    navigator.clipboard.writeText(md).then(() => {
      setCopiedToast(true);
      setTimeout(() => setCopiedToast(false), 3000);
    });
  };

  const availableSwapOptions = swappingCapability
    ? getAvailableToolsForCapability(swappingCapability, inputSummary.teamSize, false, inputSummary.preferredDeployment)
    : [];

  const isImpossibleBudget = status === 'NO_STACK_WITHIN_BUDGET';

  return (
    <div style={{ maxWidth: '1160px', margin: '0 auto', padding: '24px 16px' }}>
      {/* Toast Notification */}
      {copiedToast && (
        <div
          role="status"
          style={{
            position: 'fixed',
            bottom: '24px',
            right: '24px',
            background: '#1D2513',
            color: '#FFFFFF',
            padding: '12px 20px',
            borderRadius: '10px',
            fontWeight: '700',
            fontSize: '0.88rem',
            display: 'flex',
            alignItems: 'center',
            gap: '8px',
            boxShadow: '0 8px 24px rgba(0,0,0,0.25)',
            zIndex: 9999
          }}
        >
          <Check size={16} color="#82A735" />
          Stack summary copied to clipboard!
        </div>
      )}

      {/* DASHBOARD TOP HEADER */}
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', flexWrap: 'wrap', gap: '16px', marginBottom: '24px' }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '6px' }}>
            <span style={{ fontSize: '0.75rem', fontWeight: '800', letterSpacing: '0.06em', color: isImpossibleBudget ? '#C92A2A' : 'var(--primary-green-dark)', textTransform: 'uppercase', background: isImpossibleBudget ? '#FFE3E3' : '#EBF2DE', padding: '4px 10px', borderRadius: '6px' }}>
              {isImpossibleBudget ? 'BUDGET CONFLICT' : 'RECOMMENDED STACK'}
            </span>
            <span style={{ fontSize: '0.8rem', fontWeight: '700', color: 'var(--text-muted)' }}>
              {inputSummary.businessType.replace('_', ' ').toUpperCase()} • {inputSummary.teamSize} {inputSummary.teamSize === 1 ? 'SEAT' : 'SEATS'}
            </span>
          </div>
          <h1 style={{ fontSize: '2.2rem', fontWeight: '800', color: 'var(--text-dark)', lineHeight: '1.2' }}>
            {isImpossibleBudget ? 'Closest Available Verified Stack' : 'Your Tailored Software Stack'}
          </h1>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '10px', flexWrap: 'wrap' }}>
          <button
            type="button"
            onClick={handleCopyMarkdown}
            className="btn-pill-outline"
            style={{ padding: '9px 16px', fontSize: '0.85rem' }}
            aria-label="Copy stack markdown summary to clipboard"
          >
            <Copy size={15} /> Copy Stack
          </button>

          <button
            type="button"
            onClick={onRestartWizard}
            className="btn-pill-outline"
            style={{ padding: '9px 16px', fontSize: '0.85rem' }}
            aria-label="Edit your stack requirements"
          >
            <Sliders size={15} /> Edit Needs
          </button>
        </div>
      </div>

      {/* IMPOSSIBLE BUDGET BANNER */}
      {isImpossibleBudget && costSummary.budgetGapExplanation && (
        <div
          role="alert"
          style={{
            background: '#FFF5F5',
            border: '1.5px solid #FFA8A8',
            borderRadius: '14px',
            padding: '16px 20px',
            marginBottom: '20px',
            color: '#C92A2A'
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px', fontWeight: '800', fontSize: '0.98rem', marginBottom: '4px' }}>
            <AlertTriangle size={18} />
            <span>NO VERIFIED STACK FOUND WITHIN ${inputSummary.monthlyBudgetUsd}/MONTH BUDGET</span>
          </div>
          <p style={{ fontSize: '0.88rem', color: '#495057', lineHeight: '1.45', margin: 0 }}>
            {costSummary.budgetGapExplanation}
          </p>
        </div>
      )}

      {/* WARNING & FILTER CONFLICT NOTICES */}
      {(warnings.length > 0 || filterConflicts.length > 0) && !isImpossibleBudget && (
        <div style={{ marginBottom: '20px' }}>
          {[...filterConflicts, ...warnings].map((w, idx) => (
            <div
              key={idx}
              role="alert"
              style={{
                display: 'flex',
                alignItems: 'flex-start',
                gap: '10px',
                padding: '12px 16px',
                background: '#FFF8E6',
                border: '1px solid #FFE08A',
                borderRadius: '10px',
                color: '#8A6300',
                fontSize: '0.85rem',
                marginBottom: '8px'
              }}
            >
              <AlertTriangle size={17} style={{ flexShrink: 0, marginTop: '2px' }} />
              <div>{w}</div>
            </div>
          ))}
        </div>
      )}

      {/* SUMMARY METRICS BAR */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '16px', marginBottom: '24px' }}>
        {/* Estimated Monthly Base Cost */}
        <div style={{ background: '#FFFFFF', border: '1px solid var(--border-color)', borderRadius: '16px', padding: '18px 20px', boxShadow: 'var(--shadow-soft)' }}>
          <div style={{ fontSize: '0.78rem', fontWeight: '700', color: 'var(--text-muted)', textTransform: 'uppercase', marginBottom: '4px' }}>
            New Estimated Spend
          </div>
          <div style={{ display: 'flex', alignItems: 'baseline', gap: '6px' }}>
            <span style={{ fontSize: '1.9rem', fontWeight: '800', color: 'var(--text-dark)' }}>
              ${costSummary.totalNewMonthlyCost.toFixed(2)}
            </span>
            <span style={{ fontSize: '0.85rem', fontWeight: '700', color: 'var(--text-muted)' }}>
              / month
            </span>
          </div>
          <div style={{ fontSize: '0.75rem', color: 'var(--text-light)', marginTop: '4px' }}>
            ${costSummary.totalNewAnnualCost.toFixed(2)}/yr • Software: ${costSummary.totalNewSoftwareLicenseMonthlyCost}/mo, Compute: ~${costSummary.totalNewInfrastructureMonthlyCost}/mo
          </div>
        </div>

        {/* Budget Status */}
        <div style={{ background: '#FFFFFF', border: '1px solid var(--border-color)', borderRadius: '16px', padding: '18px 20px', boxShadow: 'var(--shadow-soft)' }}>
          <div style={{ fontSize: '0.78rem', fontWeight: '700', color: 'var(--text-muted)', textTransform: 'uppercase', marginBottom: '4px' }}>
            Budget Feasibility
          </div>
          <div style={{ fontSize: '1.2rem', fontWeight: '800', color: isImpossibleBudget ? '#C92A2A' : 'var(--primary-green-dark)' }}>
            {costSummary.fitAssessment}
          </div>
          <div style={{ fontSize: '0.75rem', color: 'var(--text-light)', marginTop: '6px' }}>
            {inputSummary.monthlyBudgetUsd > 0
              ? `Target: $${inputSummary.monthlyBudgetUsd}/mo (${costSummary.budgetDifferenceUsd >= 0 ? '$' + costSummary.budgetDifferenceUsd.toFixed(2) + ' under cap' : '$' + Math.abs(costSummary.budgetDifferenceUsd).toFixed(2) + ' over cap'})`
              : 'No strict budget limit'}
          </div>
        </div>

        {/* Stack Composition */}
        <div style={{ background: '#FFFFFF', border: '1px solid var(--border-color)', borderRadius: '16px', padding: '18px 20px', boxShadow: 'var(--shadow-soft)' }}>
          <div style={{ fontSize: '0.78rem', fontWeight: '700', color: 'var(--text-muted)', textTransform: 'uppercase', marginBottom: '4px' }}>
            Stack Composition
          </div>
          <div style={{ fontSize: '1.35rem', fontWeight: '800', color: 'var(--text-dark)' }}>
            {recommendedStack.length} Tools
          </div>
          <div style={{ fontSize: '0.75rem', color: 'var(--text-light)', marginTop: '4px' }}>
            {recommendedStack.filter(s => s.selectedTool.licensing?.openSource).length} Open-Source • {recommendedStack.filter(s => !s.selectedTool.licensing?.openSource).length} Cloud SaaS
          </div>
        </div>

        {/* Confidence Separation */}
        <div style={{ background: '#FFFFFF', border: '1px solid var(--border-color)', borderRadius: '16px', padding: '18px 20px', boxShadow: 'var(--shadow-soft)' }}>
          <div style={{ fontSize: '0.78rem', fontWeight: '700', color: 'var(--text-muted)', textTransform: 'uppercase', marginBottom: '4px' }}>
            Confidence Ratings
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px', margin: '4px 0' }}>
            <span style={{ fontSize: '0.85rem', fontWeight: '800', color: 'var(--primary-green-dark)', background: '#EBF2DE', padding: '2px 8px', borderRadius: '4px' }}>
              Fit: {confidenceSummary.recommendationConfidence}
            </span>
            <span style={{ fontSize: '0.85rem', fontWeight: '800', color: '#1864AB', background: '#E7F5FF', padding: '2px 8px', borderRadius: '4px' }}>
              Cost: {confidenceSummary.costConfidence}
            </span>
          </div>
          <div style={{ fontSize: '0.73rem', color: 'var(--text-light)', marginTop: '4px' }}>
            Pricing source checked {confidenceSummary.pricingCheckedDate}
          </div>
        </div>
      </div>

      {/* DASHBOARD NAVIGATION TABS */}
      <div style={{ display: 'flex', alignItems: 'center', gap: '8px', borderBottom: '1px solid var(--border-color)', marginBottom: '24px', overflowX: 'auto' }}>
        {[
          { id: 'stack', label: `Recommended Stack (${recommendedStack.length})` },
          { id: 'cost', label: 'True Cost Breakdown' },
          { id: 'overlap', label: `Overlap Diagnostics (${overlapAnalysis.length})` },
          { id: 'integrations', label: `Integration Graph (${integrationMatrix.length})` }
        ].map(tab => (
          <button
            key={tab.id}
            type="button"
            onClick={() => setActiveTab(tab.id)}
            style={{
              padding: '10px 18px',
              border: 'none',
              background: 'none',
              borderBottom: activeTab === tab.id ? '3px solid #82A735' : '3px solid transparent',
              color: activeTab === tab.id ? 'var(--text-dark)' : 'var(--text-muted)',
              fontWeight: '800',
              fontSize: '0.9rem',
              cursor: 'pointer',
              whiteSpace: 'nowrap',
              transition: 'all 0.15s ease'
            }}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* TAB 1: RECOMMENDED STACK CARDS */}
      {activeTab === 'stack' && (
        <div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: '20px', marginBottom: '32px' }}>
            {recommendedStack.map(item => {
              const tool = item.selectedTool;
              return (
                <div
                  key={item.capability}
                  style={{
                    background: '#FFFFFF',
                    border: '1px solid var(--border-color)',
                    borderRadius: '16px',
                    padding: '22px',
                    display: 'flex',
                    flexDirection: 'column',
                    justifyContent: 'space-between',
                    boxShadow: 'var(--shadow-soft)',
                    position: 'relative'
                  }}
                >
                  {/* Card Header */}
                  <div>
                    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '8px' }}>
                      <span style={{ fontSize: '0.72rem', fontWeight: '800', color: 'var(--primary-green-dark)', textTransform: 'uppercase', letterSpacing: '0.05em', background: '#F4F7EE', padding: '3px 8px', borderRadius: '4px' }}>
                        {item.capability.replace('_', ' ')}
                      </span>
                      <span style={{ fontSize: '0.75rem', fontWeight: '700', color: 'var(--text-light)' }}>
                        {tool.hostingType}
                      </span>
                    </div>

                    <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: '12px' }}>
                      <div>
                        <h3 style={{ fontSize: '1.25rem', fontWeight: '800', color: 'var(--text-dark)', marginBottom: '2px' }}>
                          {tool.name}
                        </h3>
                        <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                          {tool.vendor}
                        </div>
                      </div>
                      <div style={{ textAlign: 'right' }}>
                        <div style={{ fontSize: '1.25rem', fontWeight: '800', color: 'var(--text-dark)' }}>
                          ${tool.monthlyCost.toFixed(2)}
                        </div>
                        <div style={{ fontSize: '0.7rem', color: 'var(--text-light)' }}>
                          / month
                        </div>
                      </div>
                    </div>

                    {/* Cost Calculation Details */}
                    <div style={{ background: '#F8F9F5', padding: '8px 12px', borderRadius: '8px', fontSize: '0.78rem', color: 'var(--text-dark)', marginBottom: '14px', border: '1px solid #ECEEE4' }}>
                      <strong>Cost:</strong> {tool.costCalculationDetails}
                    </div>

                    {/* Free Tier Uncertainty Notice */}
                    {tool.freeTierUncertaintyNote && (
                      <div style={{ background: '#FFFDF5', padding: '8px 12px', borderRadius: '8px', fontSize: '0.75rem', color: '#8A6300', marginBottom: '12px', border: '1px solid #FFE08A' }}>
                        <Info size={13} style={{ display: 'inline', marginRight: '4px', verticalAlign: 'text-bottom' }} />
                        {tool.freeTierUncertaintyNote}
                      </div>
                    )}

                    {/* Natural Explanations */}
                    <div style={{ fontSize: '0.84rem', color: 'var(--text-muted)', lineHeight: '1.45', marginBottom: '14px' }}>
                      {tool.whyItFits}
                    </div>

                    {/* Meta Badges */}
                    <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px', marginBottom: '16px' }}>
                      <span style={{ fontSize: '0.68rem', fontWeight: '700', padding: '2px 6px', borderRadius: '4px', background: '#EBF2DE', color: 'var(--primary-green-dark)' }}>
                        {tool.licensing?.licenseType || 'PROPRIETARY'}
                      </span>
                      {tool.licensing?.openSource && (
                        <span style={{ fontSize: '0.68rem', fontWeight: '700', padding: '2px 6px', borderRadius: '4px', background: '#D3E5FF', color: '#1864AB' }}>
                          OPEN SOURCE
                        </span>
                      )}
                      <span style={{ fontSize: '0.68rem', fontWeight: '700', padding: '2px 6px', borderRadius: '4px', background: '#F1F3F5', color: '#495057' }}>
                        SOURCE CHECKED 2026
                      </span>
                    </div>
                  </div>

                  {/* Card Actions */}
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderTop: '1px solid var(--border-color)', paddingTop: '14px', marginTop: '10px' }}>
                    <button
                      type="button"
                      onClick={() => {
                        trackProductEvent('source_opened', { tool_id: tool.toolId, capability: item.capability });
                        setInspectingTool(tool);
                      }}
                      style={{
                        background: 'none',
                        border: 'none',
                        cursor: 'pointer',
                        fontSize: '0.8rem',
                        fontWeight: '700',
                        color: 'var(--text-muted)',
                        display: 'flex',
                        alignItems: 'center',
                        gap: '4px',
                        padding: 0
                      }}
                      aria-label={`Inspect verified sources for ${tool.name}`}
                    >
                      <Info size={14} /> Sources &amp; Verification
                    </button>

                    <button
                      type="button"
                      onClick={() => setSwappingCapability(item.capability)}
                      className="btn-pill-outline"
                      style={{ padding: '6px 12px', fontSize: '0.8rem' }}
                      aria-label={`Swap recommended tool for ${item.capability}`}
                    >
                      <RefreshCw size={13} /> Swap Tool
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* TAB 2: TRUE COST BREAKDOWN */}
      {activeTab === 'cost' && (
        <div style={{ background: '#FFFFFF', border: '1px solid var(--border-color)', borderRadius: '16px', padding: '24px', boxShadow: 'var(--shadow-soft)', marginBottom: '32px' }}>
          <h2 style={{ fontSize: '1.4rem', fontWeight: '800', color: 'var(--text-dark)', marginBottom: '8px' }}>
            True Cost &amp; Infrastructure Model
          </h2>
          <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem', marginBottom: '24px' }}>
            StakDock separates fixed software subscriptions from server VPS compute, transaction processing fees, and variable volume limits.
          </p>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '16px', marginBottom: '28px' }}>
            <div style={{ padding: '16px', background: '#F8F9F5', borderRadius: '12px', border: '1px solid var(--border-color)' }}>
              <div style={{ fontSize: '0.8rem', fontWeight: '700', color: 'var(--text-muted)', textTransform: 'uppercase' }}>Software Subscriptions</div>
              <div style={{ fontSize: '1.6rem', fontWeight: '800', color: 'var(--text-dark)', margin: '4px 0' }}>
                ${costSummary.totalNewSoftwareLicenseMonthlyCost.toFixed(2)}/mo
              </div>
              <div style={{ fontSize: '0.78rem', color: 'var(--text-light)' }}>Direct vendor SaaS and software license fees.</div>
            </div>

            <div style={{ padding: '16px', background: '#F8F9F5', borderRadius: '12px', border: '1px solid var(--border-color)' }}>
              <div style={{ fontSize: '0.8rem', fontWeight: '700', color: 'var(--text-muted)', textTransform: 'uppercase' }}>Estimated VPS Compute</div>
              <div style={{ fontSize: '1.6rem', fontWeight: '800', color: 'var(--text-dark)', margin: '4px 0' }}>
                ~${costSummary.totalNewInfrastructureMonthlyCost.toFixed(2)}/mo
              </div>
              <div style={{ fontSize: '0.78rem', color: 'var(--text-light)' }}>Hosting costs required to run self-hosted Docker tools.</div>
            </div>

            <div style={{ padding: '16px', background: '#F8F9F5', borderRadius: '12px', border: '1px solid var(--border-color)' }}>
              <div style={{ fontSize: '0.8rem', fontWeight: '700', color: 'var(--text-muted)', textTransform: 'uppercase' }}>Total Estimated Base</div>
              <div style={{ fontSize: '1.6rem', fontWeight: '800', color: 'var(--primary-green-dark)', margin: '4px 0' }}>
                ${costSummary.totalNewMonthlyCost.toFixed(2)}/mo
              </div>
              <div style={{ fontSize: '0.78rem', color: 'var(--text-light)' }}>${costSummary.totalNewAnnualCost.toFixed(2)} per year.</div>
            </div>
          </div>

          {/* Self-Hosting Consolidated Range Notice */}
          {costSummary.selfHostRange && (
            <div style={{ background: '#F4F7EE', padding: '16px 20px', borderRadius: '12px', border: '1px solid #DCE6CB', marginBottom: '24px' }}>
              <div style={{ fontWeight: '800', fontSize: '0.92rem', color: 'var(--primary-green-dark)', marginBottom: '4px' }}>
                Self-Hosting Infrastructure Range:
              </div>
              <div style={{ fontSize: '0.84rem', color: 'var(--text-dark)', lineHeight: '1.45' }}>
                Independent VPS compute: <strong>~${costSummary.selfHostRange.independentMinUsd}–${costSummary.selfHostRange.independentMaxUsd}/mo</strong> (if hosted on dedicated VPS per app).
                {costSummary.selfHostRange.consolidatedMinUsd !== costSummary.selfHostRange.independentMinUsd && (
                  <span> Consolidated multi-container VPS estimate: <strong>~${costSummary.selfHostRange.consolidatedMinUsd}–${costSummary.selfHostRange.consolidatedMaxUsd}/mo</strong>.</span>
                )}
              </div>
              <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: '4px' }}>
                *{costSummary.selfHostRange.note}
              </div>
            </div>
          )}

          <h3 style={{ fontSize: '1.1rem', fontWeight: '800', color: 'var(--text-dark)', marginBottom: '12px' }}>
            Variable Fees &amp; Free Tier Limits in This Stack:
          </h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
            {recommendedStack.map(s => {
              const tool = s.selectedTool;
              const hasNotes = tool.transactionFeesNote || tool.freeTierLimitsNote || tool.infrastructureDetails;
              if (!hasNotes) return null;
              return (
                <div key={s.capability} style={{ padding: '12px 16px', background: '#FAFAFA', borderRadius: '10px', border: '1px solid #ECEEE4' }}>
                  <div style={{ fontWeight: '800', fontSize: '0.9rem', color: 'var(--text-dark)', marginBottom: '4px' }}>
                    {tool.name} ({s.capability})
                  </div>
                  {tool.freeTierLimitsNote && (
                    <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                      • <strong>Free Tier Limits:</strong> {tool.freeTierLimitsNote}
                    </div>
                  )}
                  {tool.transactionFeesNote && (
                    <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                      • <strong>Transaction Processing:</strong> {tool.transactionFeesNote}
                    </div>
                  )}
                  {tool.infrastructureDetails && (
                    <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                      • <strong>Self-Host Compute:</strong> {tool.infrastructureDetails}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* TAB 3: OVERLAP DIAGNOSTICS */}
      {activeTab === 'overlap' && (
        <div style={{ background: '#FFFFFF', border: '1px solid var(--border-color)', borderRadius: '16px', padding: '24px', boxShadow: 'var(--shadow-soft)', marginBottom: '32px' }}>
          <h2 style={{ fontSize: '1.4rem', fontWeight: '800', color: 'var(--text-dark)', marginBottom: '8px' }}>
            Capability Overlap Diagnostics
          </h2>
          <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem', marginBottom: '24px' }}>
            StakDock analyzes capability tags across your selected tools to identify where you might be paying for duplicate functionality.
          </p>

          {overlapAnalysis.length === 0 ? (
            <div style={{ textAlign: 'center', padding: '40px 20px', background: '#F8F9F5', borderRadius: '12px' }}>
              <CheckCircle2 size={36} color="#82A735" style={{ margin: '0 auto 12px' }} />
              <h3 style={{ fontSize: '1.15rem', fontWeight: '800', color: 'var(--text-dark)', marginBottom: '4px' }}>
                Zero Wasteful Redundancy Detected
              </h3>
              <p style={{ fontSize: '0.88rem', color: 'var(--text-muted)', maxWidth: '500px', margin: '0 auto' }}>
                All tools in your recommended stack serve distinct, non-overlapping capabilities that operate synergistically.
              </p>
            </div>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
              {overlapAnalysis.map((o, idx) => (
                <div
                  key={idx}
                  style={{
                    padding: '16px 20px',
                    borderRadius: '12px',
                    border: o.level === 'HIGH_OVERLAP' ? '1px solid #FFA8A8' : '1px solid #FFE08A',
                    background: o.level === 'HIGH_OVERLAP' ? '#FFF5F5' : '#FFFDF5'
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '6px' }}>
                    <div style={{ fontWeight: '800', fontSize: '1rem', color: 'var(--text-dark)' }}>
                      {o.pair.join(' ↔ ')}
                    </div>
                    <span
                      style={{
                        fontSize: '0.72rem',
                        fontWeight: '800',
                        padding: '3px 8px',
                        borderRadius: '4px',
                        background: o.level === 'HIGH_OVERLAP' ? '#FFE3E3' : '#FFF3BF',
                        color: o.level === 'HIGH_OVERLAP' ? '#C92A2A' : '#8A6300'
                      }}
                    >
                      {o.level.replace('_', ' ')}
                    </span>
                  </div>
                  <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)', lineHeight: '1.45' }}>
                    {o.details}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* TAB 4: INTEGRATION GRAPH */}
      {activeTab === 'integrations' && (
        <div style={{ background: '#FFFFFF', border: '1px solid var(--border-color)', borderRadius: '16px', padding: '24px', boxShadow: 'var(--shadow-soft)', marginBottom: '32px' }}>
          <h2 style={{ fontSize: '1.4rem', fontWeight: '800', color: 'var(--text-dark)', marginBottom: '8px' }}>
            Integration &amp; Interoperability Graph
          </h2>
          <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem', marginBottom: '24px' }}>
            Verified pairwise connectivity status between every tool in your stack based on official vendor documentation.
          </p>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '14px' }}>
            {integrationMatrix.map((integ, idx) => {
              let badgeBg = '#EBF2DE';
              let badgeColor = 'var(--primary-green-dark)';
              if (integ.status === 'AUTOMATION_BRIDGE_VERIFIED') {
                badgeBg = '#E7F5FF';
                badgeColor = '#1864AB';
              } else if (integ.status === 'CUSTOM_INTEGRATION_REQUIRED') {
                badgeBg = '#F3F0FF';
                badgeColor = '#5F3DC4';
              } else if (integ.status === 'NO_INTEGRATION_VERIFIED') {
                badgeBg = '#FFE3E3';
                badgeColor = '#C92A2A';
              } else if (integ.status === 'UNKNOWN') {
                badgeBg = '#F8F9FA';
                badgeColor = '#868E96';
              }

              return (
                <div
                  key={idx}
                  style={{
                    padding: '16px',
                    border: '1px solid var(--border-color)',
                    borderRadius: '12px',
                    background: '#FFFFFF'
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '6px' }}>
                    <div style={{ fontWeight: '800', fontSize: '0.92rem', color: 'var(--text-dark)' }}>
                      {integ.pair.join(' + ')}
                    </div>
                    <span
                      style={{
                        fontSize: '0.68rem',
                        fontWeight: '800',
                        padding: '2px 6px',
                        borderRadius: '4px',
                        background: badgeBg,
                        color: badgeColor
                      }}
                    >
                      {integ.status.replace('_', ' ')}
                    </span>
                  </div>
                  <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', lineHeight: '1.4' }}>
                    {integ.note}
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* SWAP TOOL MODAL */}
      {swappingCapability && (
        <div
          role="dialog"
          aria-modal="true"
          aria-labelledby="swap-modal-title"
          style={{
            position: 'fixed',
            inset: 0,
            background: 'rgba(0,0,0,0.5)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            padding: '20px',
            zIndex: 10000
          }}
        >
          <div
            style={{
              background: '#FFFFFF',
              borderRadius: '20px',
              maxWidth: '680px',
              width: '100%',
              maxHeight: '85vh',
              overflowY: 'auto',
              padding: '28px',
              boxShadow: '0 20px 40px rgba(0,0,0,0.2)'
            }}
          >
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '16px' }}>
              <div>
                <span style={{ fontSize: '0.72rem', fontWeight: '800', color: 'var(--primary-green-dark)', textTransform: 'uppercase' }}>
                  SWAP TOOL FOR {swappingCapability.replace('_', ' ')}
                </span>
                <h3 id="swap-modal-title" style={{ fontSize: '1.4rem', fontWeight: '800', color: 'var(--text-dark)', marginTop: '2px' }}>
                  Available Alternatives
                </h3>
              </div>
              <button
                type="button"
                onClick={() => setSwappingCapability(null)}
                style={{ background: 'none', border: 'none', cursor: 'pointer', padding: '4px' }}
                aria-label="Close Swap Tool Modal"
              >
                <X size={20} color="var(--text-muted)" />
              </button>
            </div>

            <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: '20px' }}>
              Selecting an alternative recalculates monthly costs, overlap warnings, and integration compatibility deterministically.
            </p>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
              {availableSwapOptions.map(opt => {
                const isCurrentWinner = recommendedStack.find(s => s.capability === swappingCapability)?.selectedTool.toolId === opt.tool.toolId;
                return (
                  <div
                    key={opt.tool.toolId}
                    onClick={() => {
                      const prevTool = recommendedStack.find(s => s.capability === swappingCapability)?.selectedTool.toolId;
                      trackProductEvent('tool_swapped', {
                        capability: swappingCapability,
                        new_tool_id: opt.tool.toolId,
                        previous_tool_id: prevTool,
                        new_cost: opt.cloudCost.totalEstimatedMonthlyCost
                      });
                      onSwapTool(swappingCapability, opt.tool.toolId);
                      setSwappingCapability(null);
                    }}
                    role="button"
                    tabIndex={0}
                    style={{
                      padding: '16px',
                      borderRadius: '12px',
                      border: isCurrentWinner ? '2px solid #82A735' : '1px solid var(--border-color)',
                      background: isCurrentWinner ? '#F4F7EE' : '#FFFFFF',
                      cursor: 'pointer',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'space-between',
                      transition: 'all 0.15s ease'
                    }}
                  >
                    <div>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                        <span style={{ fontWeight: '800', fontSize: '1rem', color: 'var(--text-dark)' }}>
                          {opt.tool.name}
                        </span>
                        {opt.tool.licensing?.openSource && (
                          <span style={{ fontSize: '0.68rem', fontWeight: '700', padding: '1px 5px', borderRadius: '4px', background: '#D3E5FF', color: '#1864AB' }}>
                            OPEN SOURCE
                          </span>
                        )}
                        {isCurrentWinner && (
                          <span style={{ fontSize: '0.68rem', fontWeight: '800', padding: '1px 5px', borderRadius: '4px', background: '#82A735', color: '#FFFFFF' }}>
                            CURRENT SELECTION
                          </span>
                        )}
                      </div>
                      <div style={{ fontSize: '0.78rem', color: 'var(--text-muted)', marginTop: '4px' }}>
                        {opt.tool.businessFit?.bestFor || opt.tool.category}
                      </div>
                    </div>

                    <div style={{ textAlign: 'right' }}>
                      <div style={{ fontWeight: '800', fontSize: '1.1rem', color: 'var(--text-dark)' }}>
                        ${opt.cloudCost.totalEstimatedMonthlyCost.toFixed(2)}/mo
                      </div>
                      <div style={{ fontSize: '0.7rem', color: 'var(--text-light)' }}>
                        {opt.tool.commercialModel?.pricingModel}
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      )}

      {/* INSPECT SOURCES MODAL */}
      {inspectingTool && (
        <div
          role="dialog"
          aria-modal="true"
          aria-labelledby="sources-modal-title"
          style={{
            position: 'fixed',
            inset: 0,
            background: 'rgba(0,0,0,0.5)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            padding: '20px',
            zIndex: 10000
          }}
        >
          <div
            style={{
              background: '#FFFFFF',
              borderRadius: '20px',
              maxWidth: '640px',
              width: '100%',
              maxHeight: '80vh',
              overflowY: 'auto',
              padding: '28px',
              boxShadow: '0 20px 40px rgba(0,0,0,0.2)'
            }}
          >
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '16px' }}>
              <div>
                <span style={{ fontSize: '0.72rem', fontWeight: '800', color: 'var(--primary-green-dark)', textTransform: 'uppercase' }}>
                  SOURCE VERIFICATION &amp; PROVENANCE
                </span>
                <h3 id="sources-modal-title" style={{ fontSize: '1.4rem', fontWeight: '800', color: 'var(--text-dark)', marginTop: '2px' }}>
                  {inspectingTool.name} Sources
                </h3>
              </div>
              <button
                type="button"
                onClick={() => setInspectingTool(null)}
                style={{ background: 'none', border: 'none', cursor: 'pointer', padding: '4px' }}
                aria-label="Close Sources Modal"
              >
                <X size={20} color="var(--text-muted)" />
              </button>
            </div>

            <div style={{ background: '#F8F9F5', padding: '14px', borderRadius: '10px', fontSize: '0.82rem', color: 'var(--text-dark)', marginBottom: '20px', border: '1px solid var(--border-color)' }}>
              <div><strong>Pricing Checked:</strong> {inspectingTool.commercialModel?.pricingVerifiedAt ? inspectingTool.commercialModel.pricingVerifiedAt.slice(0, 10) : '2026-08-31'}</div>
              <div><strong>Official Website:</strong> <a href={inspectingTool.website} target="_blank" rel="noopener noreferrer" style={{ color: 'var(--primary-green-dark)', fontWeight: '700' }}>{inspectingTool.website}</a></div>
              <div><strong>Official Pricing:</strong> <a href={inspectingTool.commercialModel?.pricingSourceUrl} target="_blank" rel="noopener noreferrer" style={{ color: 'var(--primary-green-dark)', fontWeight: '700' }}>{inspectingTool.commercialModel?.pricingSourceUrl}</a></div>
              {inspectingTool.licensing?.licenseSourceUrl && (
                <div><strong>License Repository:</strong> <a href={inspectingTool.licensing?.licenseSourceUrl} target="_blank" rel="noopener noreferrer" style={{ color: 'var(--primary-green-dark)', fontWeight: '700' }}>{inspectingTool.licensing?.licenseSourceUrl}</a></div>
              )}
            </div>

            <h4 style={{ fontSize: '0.95rem', fontWeight: '800', color: 'var(--text-dark)', marginBottom: '10px' }}>
              Claim-Specific Primary Sources:
            </h4>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
              {(inspectingTool.sources || []).map((src, i) => (
                <a
                  key={i}
                  href={src.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  onClick={() => trackAffiliateClick(inspectingTool.toolId, src.url, { sourceContext: 'stack_builder_sources', stackCapability: inspectingTool.primaryCapability })}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'space-between',
                    padding: '10px 14px',
                    borderRadius: '8px',
                    border: '1px solid var(--border-color)',
                    background: '#FAFAFA',
                    color: 'var(--text-dark)',
                    textDecoration: 'none',
                    fontSize: '0.84rem',
                    fontWeight: '700'
                  }}
                >
                  <span style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                    {src.type === 'OFFICIAL_PRICING_PAGE' && <DollarSign size={14} color="#82A735" />}
                    {src.type === 'OFFICIAL_SOURCE_REPOSITORY' && <Code2 size={14} color="#1864AB" />}
                    {src.type === 'OFFICIAL_DOCUMENTATION' && <FileText size={14} color="#5F3DC4" />}
                    {src.title}
                  </span>
                  <ExternalLink size={14} color="var(--primary-green-dark)" />
                </a>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
