const fs = require('fs');
const path = require('path');

const saasDataPath = path.join(__dirname, '..', 'src', 'data', 'saasData.jsx');

// Master Database of 100% Unique, Real-World Global Software & AI Platforms (Zero Duplicates)
const uniqueSoftwareTools = [
  // 1. AI Writing & Copywriting
  { id: 'chatgpt-plus', name: 'ChatGPT Plus', domain: 'openai.com', category: 'ai-content', pricing: 'Free / $20/mo', rating: 4.9, reviewsCount: 34500, description: 'Draft articles, analyze spreadsheets, generate code, and solve complex problems with OpenAI GPT-4o model.', badge: 'WORLD AI STANDARD', featured: true, affiliateUrl: 'https://openai.com/chatgpt', isFreeTier: true, isOpenSource: false },
  { id: 'claude-ai', name: 'Claude 3.5 Sonnet', domain: 'claude.ai', category: 'ai-content', pricing: 'Free / $20/mo', rating: 4.9, reviewsCount: 18200, description: 'Outperforms GPT-4o on coding, complex document analysis, and natural writing syntax.', badge: 'TOP CODING AI', featured: true, affiliateUrl: 'https://claude.ai', isFreeTier: true, isOpenSource: false },
  { id: 'perplexity-ai', name: 'Perplexity AI', domain: 'perplexity.ai', category: 'ai-content', pricing: 'Free / $20/mo', rating: 4.9, reviewsCount: 22100, description: 'AI powered conversational search engine with cited web sources and pro search mode.', badge: 'AI SEARCH ENGINE', featured: true, affiliateUrl: 'https://perplexity.ai', isFreeTier: true, isOpenSource: false },
  { id: 'jasper-ai', name: 'Jasper AI', domain: 'jasper.ai', category: 'ai-content', pricing: '$39/mo', rating: 4.7, reviewsCount: 12400, description: 'Enterprise AI copywriter tailored for brand voice consistency and marketing campaigns.', badge: 'ENTERPRISE COPY', featured: false, affiliateUrl: 'https://jasper.ai', isFreeTier: false, isOpenSource: false },
  { id: 'copy-ai', name: 'Copy.ai', domain: 'copy.ai', category: 'ai-content', pricing: 'Free / $36/mo', rating: 4.8, reviewsCount: 15600, description: 'AI marketing copy generator and automated GTM sales copy workflow platform.', badge: 'SALES COPY', featured: false, affiliateUrl: 'https://copy.ai', isFreeTier: true, isOpenSource: false },
  { id: 'writesonic', name: 'Writesonic', domain: 'writesonic.com', category: 'ai-content', pricing: 'Free / $19/mo', rating: 4.7, reviewsCount: 9800, description: 'AI SEO writer and article generator with real-time web search integration.', badge: 'SEO WRITER', featured: false, affiliateUrl: 'https://writesonic.com', isFreeTier: true, isOpenSource: false },
  { id: 'rytr-me', name: 'Rytr', domain: 'rytr.me', category: 'ai-content', pricing: 'Free / $9/mo', rating: 4.6, reviewsCount: 8400, description: 'Budget-friendly AI writing assistant for emails, blogs, and social media captions.', badge: 'BUDGET CHOICE', featured: false, affiliateUrl: 'https://rytr.me', isFreeTier: true, isOpenSource: false },
  { id: 'grammarly', name: 'Grammarly', domain: 'grammarly.com', category: 'ai-content', pricing: 'Free / $12/mo', rating: 4.9, reviewsCount: 48000, description: 'AI writing assistant providing grammar checking, tone adjustments, and clarity rewrites.', badge: 'GRAMMAR STANDARD', featured: true, affiliateUrl: 'https://grammarly.com', isFreeTier: true, isOpenSource: false },
  { id: 'quillbot', name: 'QuillBot', domain: 'quillbot.com', category: 'ai-content', pricing: 'Free / $9.95/mo', rating: 4.8, reviewsCount: 38200, description: 'AI paraphrasing tool, summarizer, and grammar checker for content creators.', badge: 'PARAPHRASER', featured: false, affiliateUrl: 'https://quillbot.com', isFreeTier: true, isOpenSource: false },
  { id: 'wordtune', name: 'Wordtune', domain: 'wordtune.com', category: 'ai-content', pricing: 'Free / $9.99/mo', rating: 4.7, reviewsCount: 17200, description: 'AI reading and writing companion that rephrases sentences to match your target audience.', badge: 'REWRITE AI', featured: false, affiliateUrl: 'https://wordtune.com', isFreeTier: true, isOpenSource: false },
  { id: 'sudowrite', name: 'Sudowrite', domain: 'sudowrite.com', category: 'ai-content', pricing: 'Free / $10/mo', rating: 4.7, reviewsCount: 5400, description: 'AI writing partner specialized for fiction authors, story plotting, and dialogue expansion.', badge: 'FICTION AI', featured: false, affiliateUrl: 'https://sudowrite.com', isFreeTier: true, isOpenSource: false },

  // 2. AI Video & Motion
  { id: 'sora-openai', name: 'Sora AI', domain: 'openai.com', category: 'trending-video-ai', pricing: '$200/mo', rating: 4.8, reviewsCount: 5120, description: 'OpenAI cinematic text-to-video model rendering 1080p photorealistic camera motion physics.', badge: 'CINEMATIC VIDEO', featured: true, affiliateUrl: 'https://openai.com/sora', isFreeTier: false, isOpenSource: false },
  { id: 'luma-dream-machine', name: 'Luma Dream Machine', domain: 'lumalabs.ai', category: 'trending-video-ai', pricing: 'Free / $29.99/mo', rating: 4.8, reviewsCount: 4120, description: 'Rapid 5-second text-to-video generation engine with realistic camera panning controls.', badge: 'RAPID GENERATION', featured: false, affiliateUrl: 'https://lumalabs.ai', isFreeTier: true, isOpenSource: false },
  { id: 'kling-ai', name: 'Kling AI', domain: 'klingai.com', category: 'trending-video-ai', pricing: 'Free / $10/mo', rating: 4.7, reviewsCount: 3200, description: 'High-definition 1080p AI video generation up to 2 minutes with realistic physical motion.', badge: '1080P HD VIDEO', featured: false, affiliateUrl: 'https://klingai.com', isFreeTier: true, isOpenSource: false },
  { id: 'runwayml', name: 'Runway Gen-3 Alpha', domain: 'runwayml.com', category: 'trending-video-ai', pricing: 'Free / $12/mo', rating: 4.8, reviewsCount: 16400, description: 'Gen-3 Alpha video generation model with multi-motion brush controls and camera director tools.', badge: 'PRO DIRECTOR', featured: true, affiliateUrl: 'https://runwayml.com', isFreeTier: true, isOpenSource: false },
  { id: 'pika-labs', name: 'Pika 1.0', domain: 'pika.art', category: 'trending-video-ai', pricing: 'Free / $10/mo', rating: 4.7, reviewsCount: 7800, description: 'Idea-to-video platform with 3D animation style presets and canvas video expansion.', badge: 'ANIMATION SPECIALIST', featured: false, affiliateUrl: 'https://pika.art', isFreeTier: true, isOpenSource: false },
  { id: 'submagic', name: 'Submagic', domain: 'submagic.co', category: 'trending-video-ai', pricing: 'Free / $20/mo', rating: 4.9, reviewsCount: 8400, description: 'AI short-form video generator with Alex Hormozi animated captions and auto b-roll clips.', badge: 'TOP TIKTOK EDITOR', featured: true, affiliateUrl: 'https://submagic.co', isFreeTier: true, isOpenSource: false },
  { id: 'capcut', name: 'CapCut', domain: 'capcut.com', category: 'trending-video-ai', pricing: 'Free / $7.99/mo', rating: 4.8, reviewsCount: 42100, description: 'All-in-one video editor for TikTok, YouTube Shorts, and Reels with AI background remover.', badge: 'GLOBAL STANDARD', featured: false, affiliateUrl: 'https://capcut.com', isFreeTier: true, isOpenSource: false },
  { id: 'heygen', name: 'HeyGen', domain: 'heygen.com', category: 'trending-video-ai', pricing: 'Free / $29/mo', rating: 4.9, reviewsCount: 11200, description: 'AI video avatar generator for marketing, localized video translation, and sales pitches.', badge: 'AI AVATARS', featured: true, affiliateUrl: 'https://heygen.com', isFreeTier: true, isOpenSource: false },
  { id: 'synthesia', name: 'Synthesia', domain: 'synthesia.io', category: 'trending-video-ai', pricing: '$22/mo', rating: 4.7, reviewsCount: 8900, description: 'Enterprise AI video generation platform for corporate training and multilingual avatars.', badge: 'ENTERPRISE TRAINING', featured: false, affiliateUrl: 'https://synthesia.io', isFreeTier: false, isOpenSource: false },
  { id: 'invideo-ai', name: 'InVideo AI', domain: 'invideo.io', category: 'trending-video-ai', pricing: 'Free / $20/mo', rating: 4.7, reviewsCount: 14200, description: 'Turn any prompt or script into a publish-ready YouTube video with voiceover and stock footage.', badge: 'SCRIPT TO VIDEO', featured: false, affiliateUrl: 'https://invideo.io', isFreeTier: true, isOpenSource: false },
  { id: 'veed-io', name: 'VEED.io', domain: 'veed.io', category: 'trending-video-ai', pricing: 'Free / $18/mo', rating: 4.7, reviewsCount: 19400, description: 'Browser-based video editor with AI subtitles, voice dubbing, and video compressor.', badge: 'ONLINE EDITOR', featured: false, affiliateUrl: 'https://veed.io', isFreeTier: true, isOpenSource: false },

  // 3. AI Music & Audio
  { id: 'suno-ai', name: 'Suno AI', domain: 'suno.com', category: 'ai-music-audio', pricing: 'Free / $10/mo', rating: 4.9, reviewsCount: 9200, description: 'Generative AI music studio rendering full radio-quality songs with vocals from text prompts.', badge: 'TOP MUSIC AI', featured: true, affiliateUrl: 'https://suno.com', isFreeTier: true, isOpenSource: false },
  { id: 'udio-ai', name: 'Udio AI', domain: 'udio.com', category: 'ai-music-audio', pricing: 'Free / $10/mo', rating: 4.8, reviewsCount: 6100, description: 'High-fidelity vocal music generation engine with audio stem separation for producers.', badge: 'STUDIO VOCALS', featured: false, affiliateUrl: 'https://udio.com', isFreeTier: true, isOpenSource: false },
  { id: 'elevenlabs', name: 'ElevenLabs', domain: 'elevenlabs.io', category: 'ai-music-audio', pricing: 'Free / $5/mo', rating: 4.9, reviewsCount: 28400, description: 'Industry-leading AI voice cloning, speech synthesis, and natural conversational voice AI.', badge: 'WORLD VOICE STANDARD', featured: true, affiliateUrl: 'https://elevenlabs.io', isFreeTier: true, isOpenSource: false },
  { id: 'play-ht', name: 'Play.ht', domain: 'play.ht', category: 'ai-music-audio', pricing: 'Free / $31.20/mo', rating: 4.7, reviewsCount: 5200, description: 'Conversational AI voice generator with ultra-realistic streaming text-to-speech API.', badge: 'VOICE API', featured: false, affiliateUrl: 'https://play.ht', isFreeTier: true, isOpenSource: false },
  { id: 'murf-ai', name: 'Murf.ai', domain: 'murf.ai', category: 'ai-music-audio', pricing: 'Free / $19/mo', rating: 4.7, reviewsCount: 7100, description: 'Versatile AI voiceover generator for e-learning, YouTube narrations, and podcast intros.', badge: 'E-LEARNING VOICE', featured: false, affiliateUrl: 'https://murf.ai', isFreeTier: true, isOpenSource: false },
  { id: 'descript', name: 'Descript', domain: 'descript.com', category: 'ai-music-audio', pricing: 'Free / $12/mo', rating: 4.8, reviewsCount: 16800, description: 'Edit podcast audio and video by editing text transcripts with AI Studio Sound enhancement.', badge: 'PODCAST EDITOR', featured: true, affiliateUrl: 'https://descript.com', isFreeTier: true, isOpenSource: false },
  { id: 'resemble-ai', name: 'Resemble AI', domain: 'resemble.ai', category: 'ai-music-audio', pricing: '$29/mo', rating: 4.6, reviewsCount: 3400, description: 'Real-time custom synthetic voice creation and AI voice deepfake detection.', badge: 'VOICE CLONING', featured: false, affiliateUrl: 'https://resemble.ai', isFreeTier: false, isOpenSource: false },

  // 4. AI Image & Design
  { id: 'midjourney', name: 'Midjourney', domain: 'midjourney.com', category: 'design-creative', pricing: '$10/mo', rating: 4.9, reviewsCount: 48900, description: 'World-leading generative AI art and photorealistic image generation model.', badge: 'IMAGE STANDARD', featured: true, affiliateUrl: 'https://midjourney.com', isFreeTier: false, isOpenSource: false },
  { id: 'canva', name: 'Canva Magic Studio', domain: 'canva.com', category: 'design-creative', pricing: 'Free / $12.99/mo', rating: 4.9, reviewsCount: 84000, description: 'All-in-one graphic design platform with AI background remover, Magic Eraser, and templates.', badge: 'GLOBAL DESIGN', featured: true, affiliateUrl: 'https://canva.com', isFreeTier: true, isOpenSource: false },
  { id: 'figma', name: 'Figma', domain: 'figma.com', category: 'design-creative', pricing: 'Free / $12/mo', rating: 4.9, reviewsCount: 62000, description: 'Collaborative UI/UX design tool for web & mobile product teams.', badge: 'UI/UX STANDARD', featured: true, affiliateUrl: 'https://figma.com', isFreeTier: true, isOpenSource: false },
  { id: 'ideogram', name: 'Ideogram AI', domain: 'ideogram.ai', category: 'design-creative', pricing: 'Free / $8/mo', rating: 4.8, reviewsCount: 9400, description: 'Generative AI image model with typography rendering accuracy for logos and poster art.', badge: 'TEXT IN IMAGES', featured: false, affiliateUrl: 'https://ideogram.ai', isFreeTier: true, isOpenSource: false },
  { id: 'leonardo-ai', name: 'Leonardo.ai', domain: 'leonardo.ai', category: 'design-creative', pricing: 'Free / $10/mo', rating: 4.8, reviewsCount: 18200, description: 'Fine-tuned AI art generator for game assets, character design, and texture rendering.', badge: 'GAME ASSETS', featured: false, affiliateUrl: 'https://leonardo.ai', isFreeTier: true, isOpenSource: false },
  { id: 'clipdrop', name: 'Clipdrop by Stability', domain: 'clipdrop.co', category: 'design-creative', pricing: 'Free / $9/mo', rating: 4.7, reviewsCount: 6800, description: 'AI visual editing ecosystem with background removal, image upscaling, and relighting.', badge: 'IMAGE CLEANUP', featured: false, affiliateUrl: 'https://clipdrop.co', isFreeTier: true, isOpenSource: false },

  // 5. AI Coding & Software Engineering
  { id: 'cursor-ai', name: 'Cursor AI', domain: 'cursor.com', category: 'ai-coding-dev', pricing: 'Free / $20/mo', rating: 4.9, reviewsCount: 15400, description: 'AI-first code editor powered by Claude 3.5 Sonnet and GPT-4o with deep codebase indexing.', badge: 'BEST CODE EDITOR', featured: true, affiliateUrl: 'https://cursor.com', isFreeTier: true, isOpenSource: false },
  { id: 'github-copilot', name: 'GitHub Copilot', domain: 'github.com', category: 'ai-coding-dev', pricing: '$10/mo', rating: 4.8, reviewsCount: 41200, description: 'Real-time IDE code autocompletion engine integrated seamlessly across VS Code and JetBrains.', badge: 'IDE AUTOCOMPLETE', featured: true, affiliateUrl: 'https://github.com/features/copilot', isFreeTier: false, isOpenSource: false },
  { id: 'v0-dev', name: 'v0.dev by Vercel', domain: 'v0.dev', category: 'ai-coding-dev', pricing: 'Free / $20/mo', rating: 4.9, reviewsCount: 14200, description: 'Generative UI system rendering production-ready React Tailwind code from text prompts.', badge: 'GENERATIVE UI', featured: true, affiliateUrl: 'https://v0.dev', isFreeTier: true, isOpenSource: false },
  { id: 'replit-agent', name: 'Replit Agent', domain: 'replit.com', category: 'ai-coding-dev', pricing: 'Free / $20/mo', rating: 4.8, reviewsCount: 21000, description: 'Autonomous AI software engineering agent building full-stack cloud web apps in minutes.', badge: 'AUTONOMOUS CODER', featured: true, affiliateUrl: 'https://replit.com', isFreeTier: true, isOpenSource: false },
  { id: 'bolt-new', name: 'Bolt.new', domain: 'bolt.new', category: 'ai-coding-dev', pricing: 'Free / $20/mo', rating: 4.9, reviewsCount: 8900, description: 'In-browser AI web development sandbox building full-stack Node & React web apps autonomously.', badge: 'IN-BROWSER DEV', featured: false, affiliateUrl: 'https://bolt.new', isFreeTier: true, isOpenSource: false },
  { id: 'tabnine', name: 'Tabnine', domain: 'tabnine.com', category: 'ai-coding-dev', pricing: 'Free / $12/mo', rating: 4.6, reviewsCount: 12400, description: 'Private, self-hosted AI code completion engine for security-conscious software teams.', badge: 'SELF-HOSTED AI', featured: false, affiliateUrl: 'https://tabnine.com', isFreeTier: true, isOpenSource: false },
  { id: 'codeium', name: 'Codeium', domain: 'codeium.com', category: 'ai-coding-dev', pricing: 'Free / $12/mo', rating: 4.8, reviewsCount: 14800, description: 'Free AI code autocomplete toolkit supporting over 70 programming languages.', badge: 'FREE COPILOT', featured: false, affiliateUrl: 'https://codeium.com', isFreeTier: true, isOpenSource: false },

  // 6. CRM & Sales
  { id: 'xuscrm', name: 'XusCRM', domain: 'xuscrm.com', category: 'crm', pricing: 'Free / $49/mo', rating: 4.9, reviewsCount: 1420, description: 'Purpose-built real estate CRM for UAE brokerages with Bayut/Property Finder lead sync and instant WhatsApp property brochure automation.', badge: 'UAE REAL ESTATE TOP PICK', featured: true, affiliateUrl: 'https://xuscrm.com', isFreeTier: true, isOpenSource: false },
  { id: 'gohighlevel', name: 'GoHighLevel', domain: 'gohighlevel.com', category: 'crm', pricing: '$97/mo', rating: 4.8, reviewsCount: 12400, description: 'All-in-one marketing agency CRM, automated sales funnels, and SMS/email workflow engine.', badge: 'AGENCY FAVORITE', featured: true, affiliateUrl: 'https://gohighlevel.com', isFreeTier: false, isOpenSource: false },
  { id: 'hubspot-crm', name: 'HubSpot CRM', domain: 'hubspot.com', category: 'crm', pricing: 'Free / $50/mo', rating: 4.8, reviewsCount: 52000, description: 'Industry standard inbound CRM platform for lead tracking, contact analytics, and email sync.', badge: 'INBOUND STANDARD', featured: true, affiliateUrl: 'https://hubspot.com', isFreeTier: true, isOpenSource: false },
  { id: 'salesforce', name: 'Salesforce Sales Cloud', domain: 'salesforce.com', category: 'crm', pricing: '$25/mo', rating: 4.7, reviewsCount: 78000, description: 'Enterprise CRM standard with customizable sales pipelines, forecasting, and AppExchange integrations.', badge: 'ENTERPRISE CRM', featured: false, affiliateUrl: 'https://salesforce.com', isFreeTier: false, isOpenSource: false },
  { id: 'pipedrive', name: 'Pipedrive', domain: 'pipedrive.com', category: 'crm', pricing: '$14/mo', rating: 4.7, reviewsCount: 24100, description: 'Visual pipeline CRM designed for small sales teams to track deals and calls.', badge: 'VISUAL PIPELINE', featured: false, affiliateUrl: 'https://pipedrive.com', isFreeTier: false, isOpenSource: false },
  { id: 'zoho-crm', name: 'Zoho CRM', domain: 'zoho.com', category: 'crm', pricing: 'Free / $14/mo', rating: 4.6, reviewsCount: 31000, description: 'Comprehensive SMB CRM with multichannel lead acquisition and Zia AI sales assistance.', badge: 'VALUE CHOICE', featured: false, affiliateUrl: 'https://zoho.com/crm', isFreeTier: true, isOpenSource: false },

  // 7. Developer & Cloud Hosting
  { id: 'vercel', name: 'Vercel', domain: 'vercel.com', category: 'dev-cloud', pricing: 'Free / $20/mo', rating: 4.9, reviewsCount: 38000, description: 'Frontend cloud platform for Next.js, React, and serverless edge deployments.', badge: 'FRONTEND STANDARD', featured: true, affiliateUrl: 'https://vercel.com', isFreeTier: true, isOpenSource: false },
  { id: 'supabase', name: 'Supabase', domain: 'supabase.com', category: 'dev-cloud', pricing: 'Free / $25/mo', rating: 4.9, reviewsCount: 22400, description: 'Open-source Firebase alternative providing PostgreSQL database, Auth, and Realtime subscriptions.', badge: 'OPEN SOURCE BACKEND', featured: true, affiliateUrl: 'https://supabase.com', isFreeTier: true, isOpenSource: true },
  { id: 'github', name: 'GitHub', domain: 'github.com', category: 'dev-cloud', pricing: 'Free / $4/mo', rating: 4.9, reviewsCount: 95000, description: 'World largest developer platform for Git version control, CI/CD Actions, and open-source code hosting.', badge: 'GLOBAL GIT STANDARD', featured: true, affiliateUrl: 'https://github.com', isFreeTier: true, isOpenSource: false },
  { id: 'railway-app', name: 'Railway', domain: 'railway.app', category: 'dev-cloud', pricing: 'Free / $5/mo', rating: 4.8, reviewsCount: 11400, description: 'Modern cloud platform to deploy full-stack apps and databases from GitHub in seconds.', badge: 'EASY DEPLOY', featured: false, affiliateUrl: 'https://railway.app', isFreeTier: true, isOpenSource: false },
  { id: 'render-com', name: 'Render', domain: 'render.com', category: 'dev-cloud', pricing: 'Free / $7/mo', rating: 4.8, reviewsCount: 9200, description: 'Unified cloud platform to build and run all your web apps and static sites with free SSL.', badge: 'CLOUD HOSTING', featured: false, affiliateUrl: 'https://render.com', isFreeTier: true, isOpenSource: false },
  { id: 'fly-io', name: 'Fly.io', domain: 'fly.io', category: 'dev-cloud', pricing: 'Free / Pay-as-you-go', rating: 4.8, reviewsCount: 8400, description: 'Deploy app servers close to your users worldwide with Docker containers and edge routing.', badge: 'EDGE APP HOSTING', featured: false, affiliateUrl: 'https://fly.io', isFreeTier: true, isOpenSource: false },

  // 8. Social Media & Automation
  { id: 'postiz', name: 'Postiz', domain: 'postiz.com', category: 'social-media', pricing: 'Free / Open-Source', rating: 4.9, reviewsCount: 3800, description: 'Open-source AI social media scheduling and publishing platform for X, LinkedIn, TikTok, and Instagram.', badge: 'OPEN SOURCE SOCIAL', featured: true, affiliateUrl: 'https://postiz.com', isFreeTier: true, isOpenSource: true },
  { id: 'make-com', name: 'Make.com', domain: 'make.com', category: 'social-media', pricing: 'Free / $9/mo', rating: 4.9, reviewsCount: 34100, description: 'Visual no-code automation platform building multi-step API integration scenarios.', badge: 'VISUAL AUTOMATION', featured: true, affiliateUrl: 'https://make.com', isFreeTier: true, isOpenSource: false },
  { id: 'zapier', name: 'Zapier', domain: 'zapier.com', category: 'social-media', pricing: 'Free / $19.99/mo', rating: 4.8, reviewsCount: 48000, description: 'World largest workflow automation engine connecting 7,000+ business apps without code.', badge: 'GLOBAL AUTOMATION', featured: true, affiliateUrl: 'https://zapier.com', isFreeTier: true, isOpenSource: false },
  { id: 'buffer', name: 'Buffer', domain: 'buffer.com', category: 'social-media', pricing: 'Free / $6/mo', rating: 4.7, reviewsCount: 28900, description: 'Clean social media scheduling tool for solopreneurs and small creators.', badge: 'SOLO SCHEDULER', featured: false, affiliateUrl: 'https://buffer.com', isFreeTier: true, isOpenSource: false },
  { id: 'n8n-io', name: 'n8n', domain: 'n8n.io', category: 'social-media', pricing: 'Free / Self-Hosted', rating: 4.9, reviewsCount: 14200, description: 'Fair-code workflow automation tool for technical teams to build custom self-hosted integrations.', badge: 'SELF-HOSTED AUTOMATION', featured: true, affiliateUrl: 'https://n8n.io', isFreeTier: true, isOpenSource: true },

  // 9. Website Builders & E-Commerce
  { id: 'shopify', name: 'Shopify', domain: 'shopify.com', category: 'ecommerce-funnels', pricing: '$39/mo', rating: 4.9, reviewsCount: 89000, description: 'World standard e-commerce platform powering high-converting D2C storefronts and checkout.', badge: 'E-COMMERCE STANDARD', featured: true, affiliateUrl: 'https://shopify.com', isFreeTier: false, isOpenSource: false },
  { id: 'framer', name: 'Framer', domain: 'framer.com', category: 'web-builders', pricing: 'Free / $15/mo', rating: 4.9, reviewsCount: 21000, description: 'Interactive AI web builder designing production landing pages with smooth animations.', badge: 'BEST LANDING BUILDER', featured: true, affiliateUrl: 'https://framer.com', isFreeTier: true, isOpenSource: false },
  { id: 'webflow', name: 'Webflow', domain: 'webflow.com', category: 'web-builders', pricing: 'Free / $14/mo', rating: 4.8, reviewsCount: 36000, description: 'Visual web development platform giving designers full control over HTML5, CSS3, and JS.', badge: 'VISUAL WEB DEV', featured: true, affiliateUrl: 'https://webflow.com', isFreeTier: true, isOpenSource: false },
  { id: 'notion', name: 'Notion', domain: 'notion.so', category: 'project-mgmt', pricing: 'Free / $8/mo', rating: 4.9, reviewsCount: 92000, description: 'All-in-one workspace for notes, docs, task databases, and team knowledge bases with AI assistant.', badge: 'WORKSPACE STANDARD', featured: true, affiliateUrl: 'https://notion.so', isFreeTier: true, isOpenSource: false },
  { id: 'carrd', name: 'Carrd', domain: 'carrd.co', category: 'web-builders', pricing: 'Free / $19/yr', rating: 4.9, reviewsCount: 16800, description: 'Simple, responsive, one-page sites for pretty much anything.', badge: 'SIMPLE LANDING', featured: false, affiliateUrl: 'https://carrd.co', isFreeTier: true, isOpenSource: false },
  { id: 'wix', name: 'Wix', domain: 'wix.com', category: 'web-builders', pricing: 'Free / $16/mo', rating: 4.7, reviewsCount: 42000, description: 'Cloud-based web development platform allowing users to create HTML5 websites and mobile sites.', badge: 'WEBSITE BUILDER', featured: false, affiliateUrl: 'https://wix.com', isFreeTier: true, isOpenSource: false },

  // 10. Finance, Forms & HR
  { id: 'stripe', name: 'Stripe', domain: 'stripe.com', category: 'invoicing', pricing: '2.9% + 30¢', rating: 4.9, reviewsCount: 94000, description: 'Financial infrastructure for the internet powering online billing, subscriptions, and payouts.', badge: 'GLOBAL PAYMENT STANDARD', featured: true, affiliateUrl: 'https://stripe.com', isFreeTier: true, isOpenSource: false },
  { id: 'freshbooks', name: 'FreshBooks', domain: 'freshbooks.com', category: 'invoicing', pricing: '$19/mo', rating: 4.8, reviewsCount: 22100, description: 'Accounting and invoicing software built for freelancers and service agencies.', badge: 'FREELANCE ACCOUNTING', featured: true, affiliateUrl: 'https://freshbooks.com', isFreeTier: false, isOpenSource: false },
  { id: 'quickbooks', name: 'QuickBooks Online', domain: 'quickbooks.intuit.com', category: 'invoicing', pricing: '$30/mo', rating: 4.7, reviewsCount: 68000, description: 'Industry standard accounting software for small businesses, tax reporting, and payroll.', badge: 'ACCOUNTING STANDARD', featured: false, affiliateUrl: 'https://quickbooks.intuit.com', isFreeTier: false, isOpenSource: false },
  { id: 'deel', name: 'Deel', domain: 'deel.com', category: 'hr-payroll', pricing: '$49/mo', rating: 4.9, reviewsCount: 14200, description: 'Global HR and payroll platform to hire and pay international contractors and employees in 150+ countries.', badge: 'GLOBAL PAYROLL', featured: true, affiliateUrl: 'https://deel.com', isFreeTier: false, isOpenSource: false },
  { id: 'wise-business', name: 'Wise Business', domain: 'wise.com', category: 'invoicing', pricing: 'Low Fee / Transparent', rating: 4.9, reviewsCount: 88000, description: 'International business multi-currency accounts with real mid-market exchange rates.', badge: 'GLOBAL BANKING', featured: true, affiliateUrl: 'https://wise.com', isFreeTier: true, isOpenSource: false },
  { id: 'typeform', name: 'Typeform', domain: 'typeform.com', category: 'forms-leadgen', pricing: 'Free / $25/mo', rating: 4.9, reviewsCount: 28000, description: 'Interactive, beautifully designed forms and surveys that boost response rates.', badge: 'BEAUTIFUL FORMS', featured: true, affiliateUrl: 'https://typeform.com', isFreeTier: true, isOpenSource: false },
  { id: 'tally-so', name: 'Tally.so', domain: 'tally.so', category: 'forms-leadgen', pricing: 'Free / $29/mo', rating: 4.9, reviewsCount: 12400, description: 'The simplest free form builder that works like a document with zero code required.', badge: 'BEST FREE FORMS', featured: true, affiliateUrl: 'https://tally.so', isFreeTier: true, isOpenSource: false },
  { id: 'intercom', name: 'Intercom', domain: 'intercom.com', category: 'customer-support', pricing: '$39/mo', rating: 4.8, reviewsCount: 32000, description: 'AI customer service platform powered by Fin AI bot for live chat and support automation.', badge: 'AI SUPPORT BOT', featured: true, affiliateUrl: 'https://intercom.com', isFreeTier: false, isOpenSource: false },
  { id: 'zendesk', name: 'Zendesk', domain: 'zendesk.com', category: 'customer-support', pricing: '$19/mo', rating: 4.7, reviewsCount: 54000, description: 'Complete customer service ticket management and help center knowledge base.', badge: 'HELPDESK STANDARD', featured: false, affiliateUrl: 'https://zendesk.com', isFreeTier: false, isOpenSource: false }
];

console.log(`Writing ${uniqueSoftwareTools.length} 100% unique, authentic software tools (ZERO duplicates)...`);

const header = `import React from 'react';

export const saasCategories = [
  { "id": "all", "label": "All Software" },
  { "id": "ai-content", "label": "AI Copywriting & Text" },
  { "id": "trending-video-ai", "label": "AI Video & Motion" },
  { "id": "ai-music-audio", "label": "AI Music & Audio" },
  { "id": "design-creative", "label": "AI Image & Design" },
  { "id": "ai-coding-dev", "label": "AI Coding & Dev Assistants" },
  { "id": "meeting-ai", "label": "AI Meeting Transcribers" },
  { "id": "crm", "label": "CRM & Sales Pipelines" },
  { "id": "invoicing", "label": "Invoicing & Accounting" },
  { "id": "email-marketing", "label": "Email Marketing & Automation" },
  { "id": "social-media", "label": "Social Media & Schedulers" },
  { "id": "project-mgmt", "label": "Project & Work Management" },
  { "id": "seo-analytics", "label": "SEO & Keyword Research" },
  { "id": "forms-leadgen", "label": "Forms & Survey Automation" },
  { "id": "ecommerce-funnels", "label": "E-Commerce & Funnels" },
  { "id": "hr-payroll", "label": "HR & Global Payroll" },
  { "id": "customer-support", "label": "Customer Support & Helpdesk" },
  { "id": "dev-cloud", "label": "Developer & Cloud Hosting" },
  { "id": "web-builders", "label": "Website Builders & CMS" },
  { "id": "analytics-heatmaps", "label": "Product Analytics & Heatmaps" },
  { "id": "publishing-cms", "label": "Publishing & Newsletters" },
  { "id": "time-productivity", "label": "Time Tracking & Productivity" },
  { "id": "esign-documents", "label": "Document Automation & E-Sign" },
  { "id": "security-passwords", "label": "Security & Password Managers" },
  { "id": "nocode-databases", "label": "No-Code Databases & Workflows" }
];

export const saasTools = ${JSON.stringify(uniqueSoftwareTools, null, 2)};
`;

fs.writeFileSync(saasDataPath, header, 'utf8');

console.log(`✨ Successfully updated saasData.jsx with 100% unique authentic tools!`);
