const fs = require('fs');
const path = require('path');

const newTools = [
  {
    "id": "tableau",
    "name": "Tableau",
    "domain": "tableau.com",
    "category": "analytics-bi",
    "tagline": "Industry-leading visual analytics and interactive business intelligence platform",
    "description": "Tableau transforms raw data into intuitive, interactive dashboards and visual analytics. It is built for data analysts, business intelligence teams, and enterprise decision-makers.",
    "rating": 4.6,
    "reviewsCount": 3850,
    "pricing": "Free Trial",
    "websiteUrl": "https://tableau.com",
    "affiliateUrl": "https://tableau.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "14.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "power-bi",
    "name": "Microsoft Power BI",
    "domain": "powerbi.microsoft.com",
    "category": "analytics-bi",
    "tagline": "Scalable enterprise business intelligence and data visualization suite",
    "description": "Power BI connects disparate data sources to build interactive reports, real-time dashboards, and automated insights. It is designed for enterprise analysts, finance teams, and decision-makers integrated with Microsoft 365.",
    "rating": 4.7,
    "reviewsCount": 4200,
    "pricing": "Freemium",
    "websiteUrl": "https://powerbi.microsoft.com",
    "affiliateUrl": "https://powerbi.microsoft.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "28.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "mixpanel",
    "name": "Mixpanel",
    "domain": "mixpanel.com",
    "category": "analytics-bi",
    "tagline": "Self-serve product analytics to track user engagement and retention",
    "description": "Mixpanel helps product teams analyze user behavior, conversion funnels, and retention cohorts in real time. It is built for product managers, growth marketers, and SaaS founders.",
    "rating": 4.6,
    "reviewsCount": 1450,
    "pricing": "Freemium",
    "websiteUrl": "https://mixpanel.com",
    "affiliateUrl": "https://mixpanel.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "4.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "posthog",
    "name": "PostHog",
    "domain": "posthog.com",
    "category": "analytics-bi",
    "tagline": "The open-source product OS for analytics, session replays, and feature flags",
    "description": "PostHog combines product analytics, session recording, A/B testing, and feature flags into a single developer platform. It is engineered for software engineers, product managers, and open-source teams.",
    "rating": 4.8,
    "reviewsCount": 920,
    "pricing": "Freemium",
    "websiteUrl": "https://posthog.com",
    "affiliateUrl": "https://posthog.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "2.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "metabase",
    "name": "Metabase",
    "domain": "metabase.com",
    "category": "analytics-bi",
    "tagline": "The easy, open-source way to visualize data and build company dashboards",
    "description": "Metabase allows anyone on the team to ask questions and create visual charts without writing complex SQL. It is ideal for startups, developers, and non-technical team members exploring database records.",
    "rating": 4.7,
    "reviewsCount": 1100,
    "pricing": "Freemium",
    "websiteUrl": "https://metabase.com",
    "affiliateUrl": "https://metabase.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "looker-studio",
    "name": "Looker Studio (Google)",
    "domain": "lookerstudio.google.com",
    "category": "analytics-bi",
    "tagline": "Free visual report builder and data dashboard creator by Google",
    "description": "Looker Studio converts spreadsheet data, Google Analytics, and marketing metrics into customizable visual dashboards. It is tailored for digital marketers, small businesses, and media agencies.",
    "rating": 4.5,
    "reviewsCount": 2800,
    "pricing": "Free",
    "websiteUrl": "https://lookerstudio.google.com",
    "affiliateUrl": "https://lookerstudio.google.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "18.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "looker",
    "name": "Looker",
    "domain": "looker.com",
    "category": "analytics-bi",
    "tagline": "Enterprise data platform powered by LookML modeling and Google Cloud",
    "description": "Looker provides a unified data modeling layer and modern business intelligence suite built on top of cloud warehouses. It serves enterprise data teams, analytics engineers, and data-driven organizations.",
    "rating": 4.5,
    "reviewsCount": 1250,
    "pricing": "Paid",
    "websiteUrl": "https://looker.com",
    "affiliateUrl": "https://looker.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "amplitude",
    "name": "Amplitude",
    "domain": "amplitude.com",
    "category": "analytics-bi",
    "tagline": "Digital analytics platform to optimize product experiences and growth",
    "description": "Amplitude gives product and growth teams real-time visibility into user behavior, cross-platform journeys, and feature adoption. It is designed for digital product teams, mobile developers, and SaaS companies.",
    "rating": 4.6,
    "reviewsCount": 1650,
    "pricing": "Freemium",
    "websiteUrl": "https://amplitude.com",
    "affiliateUrl": "https://amplitude.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.9M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "google-analytics",
    "name": "Google Analytics (GA4)",
    "domain": "analytics.google.com",
    "category": "analytics-bi",
    "tagline": "The web standard for tracking digital traffic, events, and conversions",
    "description": "Google Analytics provides comprehensive web and mobile app measurement, tracking audience acquisition, user behavior, and revenue conversions. It is used by millions of website owners, marketers, and developers.",
    "rating": 4.5,
    "reviewsCount": 6100,
    "pricing": "Freemium",
    "websiteUrl": "https://analytics.google.com",
    "affiliateUrl": "https://analytics.google.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "65.0M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "plausible",
    "name": "Plausible Analytics",
    "domain": "plausible.io",
    "category": "analytics-bi",
    "tagline": "Lightweight, privacy-first open-source web analytics software",
    "description": "Plausible offers cookie-free, GDPR-compliant website analytics with a script footprint under 1KB. It is built for privacy-conscious developers, bloggers, and ethical business owners.",
    "rating": 4.9,
    "reviewsCount": 850,
    "pricing": "Paid",
    "websiteUrl": "https://plausible.io",
    "affiliateUrl": "https://plausible.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": false,
    "isOpenSource": true
  },
  {
    "id": "fathom-analytics",
    "name": "Fathom Analytics",
    "domain": "usefathom.com",
    "category": "analytics-bi",
    "tagline": "Simple, privacy-focused website analytics without cookie banners",
    "description": "Fathom Analytics provides simple website traffic insights while fully respecting visitor data privacy and compliance laws. It serves independent creators, agencies, and privacy-focused brands.",
    "rating": 4.8,
    "reviewsCount": 620,
    "pricing": "Paid",
    "websiteUrl": "https://usefathom.com",
    "affiliateUrl": "https://usefathom.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "850K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "matomo",
    "name": "Matomo",
    "domain": "matomo.org",
    "category": "analytics-bi",
    "tagline": "Powerful Google Analytics alternative that gives you full data ownership",
    "description": "Matomo delivers a complete web analytics suite that can be self-hosted on your own servers or run in the cloud. It is designed for government agencies, enterprises, and web teams requiring full data privacy control.",
    "rating": 4.7,
    "reviewsCount": 1150,
    "pricing": "Freemium",
    "websiteUrl": "https://matomo.org",
    "affiliateUrl": "https://matomo.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "thoughtspot",
    "name": "ThoughtSpot",
    "domain": "thoughtspot.com",
    "category": "analytics-bi",
    "tagline": "AI-powered search and natural language analytics platform",
    "description": "ThoughtSpot enables users to search company data using natural language queries and AI insights. It serves business analysts and enterprise decision-makers seeking immediate self-service data exploration.",
    "rating": 4.6,
    "reviewsCount": 510,
    "pricing": "Free Trial",
    "websiteUrl": "https://thoughtspot.com",
    "affiliateUrl": "https://thoughtspot.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "domo",
    "name": "Domo",
    "domain": "domo.com",
    "category": "analytics-bi",
    "tagline": "Cloud business management platform combining data integration and dashboards",
    "description": "Domo connects business data across systems, allowing leaders to create automated workflows, real-time alerts, and executive dashboards. It is built for enterprise executives and cross-functional teams.",
    "rating": 4.4,
    "reviewsCount": 890,
    "pricing": "Free Trial",
    "websiteUrl": "https://domo.com",
    "affiliateUrl": "https://domo.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "qlik-sense",
    "name": "Qlik Sense",
    "domain": "qlik.com",
    "category": "analytics-bi",
    "tagline": "Associative AI data analytics engine and business intelligence engine",
    "description": "Qlik Sense uses a unique associative indexing engine to let users explore hidden data relationships across all dimensions. It is engineered for enterprise business analysts and data operations.",
    "rating": 4.5,
    "reviewsCount": 1420,
    "pricing": "Free Trial",
    "websiteUrl": "https://qlik.com",
    "affiliateUrl": "https://qlik.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "sisense",
    "name": "Sisense",
    "domain": "sisense.com",
    "category": "analytics-bi",
    "tagline": "Embeddable analytics platform for software products and SaaS applications",
    "description": "Sisense enables product teams to embed white-labeled interactive dashboards and analytical features directly into customer-facing software. It is built for product managers and SaaS developers.",
    "rating": 4.4,
    "reviewsCount": 780,
    "pricing": "Free Trial",
    "websiteUrl": "https://sisense.com",
    "affiliateUrl": "https://sisense.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "580K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "apache-superset",
    "name": "Apache Superset",
    "domain": "superset.apache.org",
    "category": "analytics-bi",
    "tagline": "Modern enterprise open-source data exploration and visualization platform",
    "description": "Apache Superset provides an open-source, highly scalable data exploration workspace equipped with a rich SQL editor and visual chart options. It serves data engineers and open-source infrastructure teams.",
    "rating": 4.7,
    "reviewsCount": 810,
    "pricing": "Free",
    "websiteUrl": "https://superset.apache.org",
    "affiliateUrl": "https://superset.apache.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "690K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "redash",
    "name": "Redash",
    "domain": "redash.io",
    "category": "analytics-bi",
    "tagline": "Open-source SQL query editor, data visualizer, and dashboard builder",
    "description": "Redash connects to database sources to let teams write SQL, visualize query outputs, and collaborate on shared dashboards. It is tailored for developers, SQL power users, and data analysts.",
    "rating": 4.6,
    "reviewsCount": 420,
    "pricing": "Free",
    "websiteUrl": "https://redash.io",
    "affiliateUrl": "https://redash.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "310K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "mode-analytics",
    "name": "Mode (ThoughtSpot)",
    "domain": "mode.com",
    "category": "analytics-bi",
    "tagline": "Collaborative data science workspace combining SQL, Python, and R",
    "description": "Mode connects code-based data science workflows with business reporting by unifying SQL editors, Python/R notebooks, and interactive charts. It is engineered for data scientists and analytics leaders.",
    "rating": 4.6,
    "reviewsCount": 380,
    "pricing": "Free Trial",
    "websiteUrl": "https://mode.com",
    "affiliateUrl": "https://mode.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "450K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "hex-tech",
    "name": "Hex",
    "domain": "hex.tech",
    "category": "analytics-bi",
    "tagline": "The modern collaborative workspace for multi-modal data science and BI",
    "description": "Hex integrates SQL queries, Python code notebooks, drag-and-drop charts, and AI assist tools into interactive data apps. It serves data teams, research scientists, and analytics engineers.",
    "rating": 4.9,
    "reviewsCount": 310,
    "pricing": "Freemium",
    "websiteUrl": "https://hex.tech",
    "affiliateUrl": "https://hex.tech",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "520K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "deepnote",
    "name": "Deepnote",
    "domain": "deepnote.com",
    "category": "analytics-bi",
    "tagline": "Real-time collaborative data science notebook in the cloud",
    "description": "Deepnote provides a cloud-hosted Jupyter-compatible notebook equipped with SQL integration, multi-user collaboration, and reactive chart building. It is built for data science teams and research groups.",
    "rating": 4.8,
    "reviewsCount": 290,
    "pricing": "Freemium",
    "websiteUrl": "https://deepnote.com",
    "affiliateUrl": "https://deepnote.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "410K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "streamlit",
    "name": "Streamlit",
    "domain": "streamlit.io",
    "category": "analytics-bi",
    "tagline": "Turn Python scripts into interactive, shareable data apps in minutes",
    "description": "Streamlit allows Python developers to convert machine learning models and data scripts into functional web applications without writing frontend code. It is an industry favorite for data scientists and ML engineers.",
    "rating": 4.9,
    "reviewsCount": 1820,
    "pricing": "Free",
    "websiteUrl": "https://streamlit.io",
    "affiliateUrl": "https://streamlit.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "plotly-dash",
    "name": "Dash by Plotly",
    "domain": "plotly.com/dash",
    "category": "analytics-bi",
    "tagline": "Low-code Python framework for building custom web analytics applications",
    "description": "Dash enables data science teams to write production-ready analytical web apps using pure Python or R. It is tailored for enterprise data teams requiring custom visual dashboards.",
    "rating": 4.7,
    "reviewsCount": 650,
    "pricing": "Freemium",
    "websiteUrl": "https://plotly.com/dash",
    "affiliateUrl": "https://plotly.com/dash",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.9M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "hotjar",
    "name": "Hotjar",
    "domain": "hotjar.com",
    "category": "analytics-bi",
    "tagline": "Visual website heatmaps, session recordings, and user feedback tools",
    "description": "Hotjar captures visual click heatmaps, scroll maps, and session recordings to reveal how visitors interact with web pages. It serves UX researchers, digital marketers, and e-commerce managers.",
    "rating": 4.6,
    "reviewsCount": 3200,
    "pricing": "Freemium",
    "websiteUrl": "https://hotjar.com",
    "affiliateUrl": "https://hotjar.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "9.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "microsoft-clarity",
    "name": "Microsoft Clarity",
    "domain": "clarity.microsoft.com",
    "category": "analytics-bi",
    "tagline": "100% free visual website analytics, heatmaps, and session recordings",
    "description": "Microsoft Clarity provides completely free click heatmaps, rage-click tracking, and video session replays without traffic limits. It is designed for website owners, UX designers, and marketers.",
    "rating": 4.8,
    "reviewsCount": 1950,
    "pricing": "Free",
    "websiteUrl": "https://clarity.microsoft.com",
    "affiliateUrl": "https://clarity.microsoft.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "11.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "fullstory",
    "name": "FullStory",
    "domain": "fullstory.com",
    "category": "analytics-bi",
    "tagline": "Enterprise digital experience intelligence and session playback platform",
    "description": "FullStory combines high-definition session playback with automated frustration tracking and conversion analytics. It is built for enterprise product, engineering, and UX research teams.",
    "rating": 4.6,
    "reviewsCount": 1100,
    "pricing": "Free Trial",
    "websiteUrl": "https://fullstory.com",
    "affiliateUrl": "https://fullstory.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "contentsquare",
    "name": "Contentsquare",
    "domain": "contentsquare.com",
    "category": "analytics-bi",
    "tagline": "Enterprise digital experience analytics and customer journey mapping",
    "description": "Contentsquare provides zone-based heatmaps, customer intent analysis, and e-commerce merchandising analytics. It serves large enterprise brands optimizing web and mobile revenue funnels.",
    "rating": 4.5,
    "reviewsCount": 680,
    "pricing": "Paid",
    "websiteUrl": "https://contentsquare.com",
    "affiliateUrl": "https://contentsquare.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.5M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "crazy-egg",
    "name": "Crazy Egg",
    "domain": "crazyegg.com",
    "category": "analytics-bi",
    "tagline": "Website heatmaps, scroll maps, A/B testing, and user tracking tool",
    "description": "Crazy Egg visualizes user behavior through snapshot heatmaps and offers built-in A/B testing utilities to increase web conversions. It is built for small businesses, agencies, and conversion marketers.",
    "rating": 4.4,
    "reviewsCount": 850,
    "pricing": "Free Trial",
    "websiteUrl": "https://crazyegg.com",
    "affiliateUrl": "https://crazyegg.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "databox",
    "name": "Databox",
    "domain": "databox.com",
    "category": "analytics-bi",
    "tagline": "All-in-one business analytics dashboard connecting your favorite tools",
    "description": "Databox pulls marketing, sales, and operational metrics into unified mobile and TV dashboards automatically. It is built for agencies, executive teams, and growth marketers.",
    "rating": 4.7,
    "reviewsCount": 980,
    "pricing": "Freemium",
    "websiteUrl": "https://databox.com",
    "affiliateUrl": "https://databox.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "klipfolio",
    "name": "Klipfolio",
    "domain": "klipfolio.com",
    "category": "analytics-bi",
    "tagline": "Real-time metric tracking, custom dashboard builder, and business reporting",
    "description": "Klipfolio enables teams to construct custom real-time business dashboards and track core performance KPIs across channels. It serves growing businesses, agencies, and data analysts.",
    "rating": 4.5,
    "reviewsCount": 720,
    "pricing": "Freemium",
    "websiteUrl": "https://klipfolio.com",
    "affiliateUrl": "https://klipfolio.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "820K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "gecko-board",
    "name": "Geckoboard",
    "domain": "geckoboard.com",
    "category": "analytics-bi",
    "tagline": "Simple real-time KPI dashboards designed for team TV displays and office screens",
    "description": "Geckoboard makes it simple to stream live metric dashboards to office TV screens, Slack channels, and browser tabs. It is designed for customer support, sales, and operations leaders.",
    "rating": 4.7,
    "reviewsCount": 450,
    "pricing": "Free Trial",
    "websiteUrl": "https://geckoboard.com",
    "affiliateUrl": "https://geckoboard.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "510K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "gooddata",
    "name": "GoodData",
    "domain": "gooddata.com",
    "category": "analytics-bi",
    "tagline": "Composable cloud analytics and embeddable business intelligence platform",
    "description": "GoodData provides headless analytics infrastructure that embeds real-time dashboards and metrics into software applications. It is tailored for enterprise software vendors and product development teams.",
    "rating": 4.3,
    "reviewsCount": 320,
    "pricing": "Freemium",
    "websiteUrl": "https://gooddata.com",
    "affiliateUrl": "https://gooddata.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "290K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "yellowfin-bi",
    "name": "Yellowfin BI",
    "domain": "yellowfinbi.com",
    "category": "analytics-bi",
    "tagline": "Embedded analytics and automated data storytelling software",
    "description": "Yellowfin BI combines action-based dashboards, automated signals, and embedded reporting inside third-party web apps. It serves enterprise IT managers and software vendors.",
    "rating": 4.4,
    "reviewsCount": 240,
    "pricing": "Free Trial",
    "websiteUrl": "https://yellowfinbi.com",
    "affiliateUrl": "https://yellowfinbi.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "180K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "preset",
    "name": "Preset",
    "domain": "preset.io",
    "category": "analytics-bi",
    "tagline": "Fully managed cloud Apache Superset platform for modern data stacks",
    "description": "Preset offers hosted Apache Superset infrastructure, enabling teams to build SQL queries and visual dashboards with enterprise governance. It is built for data engineers and analytics teams.",
    "rating": 4.8,
    "reviewsCount": 190,
    "pricing": "Freemium",
    "websiteUrl": "https://preset.io",
    "affiliateUrl": "https://preset.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "240K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "lightdash",
    "name": "Lightdash",
    "domain": "lightdash.com",
    "category": "analytics-bi",
    "tagline": "Open-source BI platform natively integrated into your dbt semantic layer",
    "description": "Lightdash turns dbt project metrics into self-serve business intelligence dashboards automatically. It is built for analytics engineers and dbt power users.",
    "rating": 4.9,
    "reviewsCount": 160,
    "pricing": "Freemium",
    "websiteUrl": "https://lightdash.com",
    "affiliateUrl": "https://lightdash.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "190K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "cube-js",
    "name": "Cube",
    "domain": "cube.dev",
    "category": "analytics-bi",
    "tagline": "Universal semantic layer for cloud data warehouses and embedded analytics",
    "description": "Cube connects cloud databases like Snowflake and BigQuery to application frontends via a central semantic layer. It is built for software developers constructing analytical web tools.",
    "rating": 4.8,
    "reviewsCount": 340,
    "pricing": "Freemium",
    "websiteUrl": "https://cube.dev",
    "affiliateUrl": "https://cube.dev",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "380K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "heap-analytics",
    "name": "Heap (Contentsquare)",
    "domain": "heap.io",
    "category": "analytics-bi",
    "tagline": "Automated digital insights engine that captures every user web interaction",
    "description": "Heap automatically records every click, swipe, and pageview without manual event tagging setup. It serves product managers, growth teams, and UX researchers.",
    "rating": 4.5,
    "reviewsCount": 950,
    "pricing": "Freemium",
    "websiteUrl": "https://heap.io",
    "affiliateUrl": "https://heap.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "vwo",
    "name": "VWO (Visual Website Optimizer)",
    "domain": "vwo.com",
    "category": "analytics-bi",
    "tagline": "Enterprise web experimentation, A/B testing, and conversion optimization platform",
    "description": "VWO provides visual A/B testing, split URL testing, session recordings, and conversion funnel tracking. It is built for conversion rate optimization (CRO) managers and growth marketers.",
    "rating": 4.6,
    "reviewsCount": 1400,
    "pricing": "Freemium",
    "websiteUrl": "https://vwo.com",
    "affiliateUrl": "https://vwo.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "optimizely",
    "name": "Optimizely",
    "domain": "optimizely.com",
    "category": "analytics-bi",
    "tagline": "Digital experience platform for enterprise A/B testing and experimentation",
    "description": "Optimizely enables enterprise teams to run web split-tests, feature flags, and personalized web experiences. It serves enterprise digital product teams and marketing divisions.",
    "rating": 4.5,
    "reviewsCount": 1850,
    "pricing": "Paid",
    "websiteUrl": "https://optimizely.com",
    "affiliateUrl": "https://optimizely.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "chartmogul",
    "name": "ChartMogul",
    "domain": "chartmogul.com",
    "category": "analytics-bi",
    "tagline": "Subscription analytics and MRR tracking engine for SaaS businesses",
    "description": "ChartMogul calculates Monthly Recurring Revenue (MRR), churn rates, LTV, and subscriber metrics from billing engines automatically. It is engineered for SaaS founders and CFOs.",
    "rating": 4.8,
    "reviewsCount": 420,
    "pricing": "Freemium",
    "websiteUrl": "https://chartmogul.com",
    "affiliateUrl": "https://chartmogul.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "580K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "baremetrics",
    "name": "Baremetrics",
    "domain": "baremetrics.com",
    "category": "analytics-bi",
    "tagline": "Real-time SaaS financial analytics, metrics, and dunning tools",
    "description": "Baremetrics streams subscription revenue data, customer churn benchmarks, and automated dunning recovery tools. It serves B2B SaaS executives and subscription business leaders.",
    "rating": 4.7,
    "reviewsCount": 280,
    "pricing": "Free Trial",
    "websiteUrl": "https://baremetrics.com",
    "affiliateUrl": "https://baremetrics.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "340K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "profitwell",
    "name": "ProfitWell by Paddle",
    "domain": "paddle.com/profitwell",
    "category": "analytics-bi",
    "tagline": "100% free subscription financial metrics and churn reduction software",
    "description": "ProfitWell provides accurate subscription financial tracking and ARR metrics directly integrated into Stripe or Paddle. It is free for SaaS founders and subscription business operators.",
    "rating": 4.8,
    "reviewsCount": 610,
    "pricing": "Free",
    "websiteUrl": "https://paddle.com/profitwell",
    "affiliateUrl": "https://paddle.com/profitwell",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "supermetrics",
    "name": "Supermetrics",
    "domain": "supermetrics.com",
    "category": "analytics-bi",
    "tagline": "Automate marketing data transfer to Google Sheets, Looker, and BigQuery",
    "description": "Supermetrics aggregates marketing ad spend, social analytics, and SEO data into spreadsheets and BI databases automatically. It serves digital agencies, performance marketers, and growth teams.",
    "rating": 4.6,
    "reviewsCount": 1100,
    "pricing": "Free Trial",
    "websiteUrl": "https://supermetrics.com",
    "affiliateUrl": "https://supermetrics.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.9M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "funnel-io",
    "name": "Funnel",
    "domain": "funnel.io",
    "category": "analytics-bi",
    "tagline": "Automated marketing data hub for reporting, storage, and visualization",
    "description": "Funnel collects, cleanses, and maps marketing performance data across hundreds of channels into any BI endpoint. It is built for enterprise marketing divisions and digital agencies.",
    "rating": 4.7,
    "reviewsCount": 380,
    "pricing": "Free Trial",
    "websiteUrl": "https://funnel.io",
    "affiliateUrl": "https://funnel.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "trevor-io",
    "name": "Trevor.io",
    "domain": "trevor.io",
    "category": "analytics-bi",
    "tagline": "No-code SQL database query builder and team dashboard creator",
    "description": "Trevor.io empowers non-technical employees to query SQL databases and build visual reports without writing code. It is designed for operational teams and startup employees.",
    "rating": 4.8,
    "reviewsCount": 140,
    "pricing": "Freemium",
    "websiteUrl": "https://trevor.io",
    "affiliateUrl": "https://trevor.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "110K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "duckdb",
    "name": "DuckDB",
    "domain": "duckdb.org",
    "category": "analytics-bi",
    "tagline": "Fast, high-performance open-source in-process analytical SQL database",
    "description": "DuckDB is an embedded analytical SQL engine designed for rapid local data analysis and processing. It is engineered for data analysts, Python developers, and data science researchers.",
    "rating": 4.9,
    "reviewsCount": 920,
    "pricing": "Free",
    "websiteUrl": "https://duckdb.org",
    "affiliateUrl": "https://duckdb.org",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "clickhouse",
    "name": "ClickHouse",
    "domain": "clickhouse.com",
    "category": "analytics-bi",
    "tagline": "Ultra-fast open-source columnar database for real-time analytical reporting",
    "description": "ClickHouse provides real-time analytical query performance over billions of rows using columnar database storage. It is built for data infrastructure engineers and large-scale web applications.",
    "rating": 4.9,
    "reviewsCount": 1150,
    "pricing": "Freemium",
    "websiteUrl": "https://clickhouse.com",
    "affiliateUrl": "https://clickhouse.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "single-store",
    "name": "SingleStore",
    "domain": "singlestore.com",
    "category": "analytics-bi",
    "tagline": "Real-time unified transactional and analytical cloud database",
    "description": "SingleStore combines operational database processing with real-time analytical reporting in a single engine. It serves enterprise architects building fast analytics applications.",
    "rating": 4.6,
    "reviewsCount": 280,
    "pricing": "Free Trial",
    "websiteUrl": "https://singlestore.com",
    "affiliateUrl": "https://singlestore.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "420K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "gooddata-cloud",
    "name": "GoodData Cloud",
    "domain": "gooddata.com",
    "category": "analytics-bi",
    "tagline": "Cloud-native semantic layer and scalable analytics engine",
    "description": "GoodData delivers real-time business intelligence dashboards connected to cloud data warehouses via custom semantic models. It serves enterprise data leaders and application developers.",
    "rating": 4.4,
    "reviewsCount": 310,
    "pricing": "Freemium",
    "websiteUrl": "https://gooddata.com",
    "affiliateUrl": "https://gooddata.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "280K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "sigma-computing",
    "name": "Sigma Computing",
    "domain": "sigmacomputing.com",
    "category": "analytics-bi",
    "tagline": "Cloud-native spreadsheet-interface analytics for cloud data warehouses",
    "description": "Sigma provides a familiar spreadsheet interface that directly queries live cloud data warehouses like Snowflake in real time. It is built for business analysts and data operations teams.",
    "rating": 4.8,
    "reviewsCount": 240,
    "pricing": "Free Trial",
    "websiteUrl": "https://sigmacomputing.com",
    "affiliateUrl": "https://sigmacomputing.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "310K",
    "isFreeTier": false,
    "isOpenSource": false
  }
];

const saasDataPath = path.join(__dirname, '..', 'src', 'data', 'saasData.jsx');
let content = fs.readFileSync(saasDataPath, 'utf8');

const match = content.match(/export const staticSaasTools = (\[[\s\S]*?\n\]);/);
if (!match) {
  console.error('Could not find staticSaasTools in saasData.jsx');
  process.exit(1);
}

let existingTools = JSON.parse(match[1]);

const existingIds = new Set(existingTools.map(t => t.id.toLowerCase()));
const existingNames = new Set(existingTools.map(t => t.name.toLowerCase()));

let addedCount = 0;
let skippedCount = 0;

newTools.forEach(tool => {
  const normId = tool.id.toLowerCase();
  const normName = tool.name.toLowerCase();

  if (!existingIds.has(normId) && !existingNames.has(normName)) {
    existingTools.push(tool);
    existingIds.add(normId);
    existingNames.add(normName);
    addedCount++;
  } else {
    // Enrich existing tool without creating a duplicate
    const idx = existingTools.findIndex(t => t.id.toLowerCase() === normId || t.name.toLowerCase() === normName);
    if (idx !== -1) {
      existingTools[idx] = { ...existingTools[idx], category: tool.category, tagline: tool.tagline || existingTools[idx].tagline };
    }
    skippedCount++;
  }
});

const updatedArrayStr = JSON.stringify(existingTools, null, 2);
content = content.replace(/export const staticSaasTools = \[[\s\S]*?\n\];/, `export const staticSaasTools = ${updatedArrayStr};`);

fs.writeFileSync(saasDataPath, content, 'utf8');
console.log(`Ingestion Complete! Added: ${addedCount} brand new tools | Deduplicated: ${skippedCount} existing tools | Total static tools: ${existingTools.length}`);
