const fs = require('fs');
const path = require('path');

const selfHostedTools = [
  {
    "id": "coolify",
    "name": "Coolify",
    "domain": "coolify.io",
    "category": "open-source-self-hosted",
    "tagline": "An open-source, self-hosted Heroku and Netlify alternative for your VPS",
    "description": "Coolify converts bare-metal Linux servers and Virtual Private Servers into an automated application deployment platform. It is engineered for indie developers, software engineers, and privacy-first startups.",
    "rating": 4.9,
    "reviewsCount": 1420,
    "pricing": "Free",
    "websiteUrl": "https://coolify.io",
    "affiliateUrl": "https://coolify.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "caprover",
    "name": "CapRover",
    "domain": "caprover.com",
    "category": "open-source-self-hosted",
    "tagline": "Automated PaaS and deployment engine for Node.js, Python, PHP, and Docker apps",
    "description": "CapRover provides a self-hosted platform to deploy web applications, microservices, and databases with automated SSL and Nginx routing. It is built for developers wanting zero-overhead server management.",
    "rating": 4.8,
    "reviewsCount": 850,
    "pricing": "Free",
    "websiteUrl": "https://caprover.com",
    "affiliateUrl": "https://caprover.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "dokku",
    "name": "Dokku",
    "domain": "dokku.com",
    "category": "open-source-self-hosted",
    "tagline": "Docker-powered mini-Heroku platform for self-hosting on personal servers",
    "description": "Dokku is an ultra-lightweight PaaS that allows developers to push applications to their own VPS via simple Git commands. It is designed for developers seeking low-cost, self-hosted app deployments.",
    "rating": 4.7,
    "reviewsCount": 540,
    "pricing": "Free",
    "websiteUrl": "https://dokku.com",
    "affiliateUrl": "https://dokku.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "320K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "kamal-deploy",
    "name": "Kamal",
    "domain": "kamal-deploy.org",
    "category": "open-source-self-hosted",
    "tagline": "Deploy containerized apps anywhere from bare metal to cloud without heavy orchestrators",
    "description": "Kamal deploys web applications to servers via SSH using Docker containers with zero-downtime traffic switching. It is engineered for software developers and Rails teams seeking lightweight server deployment.",
    "rating": 4.9,
    "reviewsCount": 680,
    "pricing": "Free",
    "websiteUrl": "https://kamal-deploy.org",
    "affiliateUrl": "https://kamal-deploy.org",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "850K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "appflowy",
    "name": "AppFlowy",
    "domain": "appflowy.io",
    "category": "open-source-self-hosted",
    "tagline": "An open-source Notion alternative giving users total data control and privacy",
    "description": "AppFlowy offers customizable document editing, task boards, and relational tables built with Flutter and Rust for high performance. It serves knowledge workers, researchers, and privacy-first teams.",
    "rating": 4.8,
    "reviewsCount": 920,
    "pricing": "Free",
    "websiteUrl": "https://appflowy.io",
    "affiliateUrl": "https://appflowy.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "focalboard",
    "name": "Focalboard",
    "domain": "focalboard.com",
    "category": "open-source-self-hosted",
    "tagline": "Open-source, self-hosted project management tool and Trello alternative",
    "description": "Focalboard helps individuals and teams define tasks, track project status, and organize workflows in visual Kanban views. It is built for developers, project managers, and team leads.",
    "rating": 4.7,
    "reviewsCount": 750,
    "pricing": "Free",
    "websiteUrl": "https://focalboard.com",
    "affiliateUrl": "https://focalboard.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "920K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "taiga-io",
    "name": "Taiga",
    "domain": "taiga.io",
    "category": "open-source-self-hosted",
    "tagline": "Open-source agile project management platform for cross-functional software teams",
    "description": "Taiga offers intuitive Scrum and Kanban modules, issue tracking, epic roadmaps, and custom user stories. It is designed for agile developers, designers, and open-source project contributors.",
    "rating": 4.4,
    "reviewsCount": 310,
    "pricing": "Freemium",
    "websiteUrl": "https://taiga.io",
    "affiliateUrl": "https://taiga.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "380K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "plane-so",
    "name": "Plane",
    "domain": "plane.so",
    "category": "open-source-self-hosted",
    "tagline": "Open-source, AI-native issue tracking and project management platform",
    "description": "Plane offers cycles, epics, module tracking, and built-in docs with complete self-hosting and cloud options. It is built for engineering teams seeking an extensible open-source alternative to Jira.",
    "rating": 4.8,
    "reviewsCount": 650,
    "pricing": "Freemium",
    "websiteUrl": "https://plane.so",
    "affiliateUrl": "https://plane.so",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "vikunja",
    "name": "Vikunja",
    "domain": "vikunja.io",
    "category": "open-source-self-hosted",
    "tagline": "The open-source self-hosted to-do app to organize your tasks on any platform",
    "description": "Vikunja provides task lists, Gantt timelines, Kanban boards, and subtask relations with multi-user sharing capabilities. It is designed for productivity enthusiasts, freelancers, and small teams.",
    "rating": 4.9,
    "reviewsCount": 420,
    "pricing": "Free",
    "websiteUrl": "https://vikunja.io",
    "affiliateUrl": "https://vikunja.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "510K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "leantime",
    "name": "Leantime",
    "domain": "leantime.io",
    "category": "open-source-self-hosted",
    "tagline": "Open-source project management platform tailored for non-project managers and innovators",
    "description": "Leantime combines task management, strategy research boards, milestone tracking, and ADHD-friendly design principles. It is engineered for startup founders, product creators, and small teams.",
    "rating": 4.8,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://leantime.io",
    "affiliateUrl": "https://leantime.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "420K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "outline-wiki",
    "name": "Outline",
    "domain": "getoutline.com",
    "category": "open-source-self-hosted",
    "tagline": "Fast, real-time collaborative team knowledge base and open-source Confluence alternative",
    "description": "Outline provides Markdown editing, team permissions, document search, and real-time collaboration with clean modern typography. It is built for growing companies, software teams, and remote workforces.",
    "rating": 4.8,
    "reviewsCount": 780,
    "pricing": "Freemium",
    "websiteUrl": "https://getoutline.com",
    "affiliateUrl": "https://getoutline.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "wiki-js",
    "name": "Wiki.js",
    "domain": "js.wiki",
    "category": "open-source-self-hosted",
    "tagline": "Powerful, modern open-source wiki software running on Node.js",
    "description": "Wiki.js provides modular authentication, Git backend synchronization, built-in search, and customizable editor modes. It serves corporate IT departments, open-source communities, and developers.",
    "rating": 4.7,
    "reviewsCount": 1250,
    "pricing": "Free",
    "websiteUrl": "https://js.wiki",
    "affiliateUrl": "https://js.wiki",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.5M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "bookstack",
    "name": "BookStack",
    "domain": "bookstackapp.com",
    "category": "open-source-self-hosted",
    "tagline": "Simple, self-hosted platform for organizing information in book structures",
    "description": "BookStack structures documentation logically into Shelves, Books, Chapters, and Pages with visual WYSIWYG or Markdown editors. It is built for IT documentation, company SOPs, and user manuals.",
    "rating": 4.8,
    "reviewsCount": 1100,
    "pricing": "Free",
    "websiteUrl": "https://bookstackapp.com",
    "affiliateUrl": "https://bookstackapp.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "rustdesk",
    "name": "RustDesk",
    "domain": "rustdesk.com",
    "category": "open-source-self-hosted",
    "tagline": "The fast, open-source remote desktop software alternative to TeamViewer and AnyDesk",
    "description": "RustDesk provides full control over remote computer sessions without relying on third-party SaaS servers. It serves IT support technicians, remote workers, and system administrators requiring secure remote desktop access.",
    "rating": 4.9,
    "reviewsCount": 2100,
    "pricing": "Freemium",
    "websiteUrl": "https://rustdesk.com",
    "affiliateUrl": "https://rustdesk.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "3.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "meshcentral",
    "name": "MeshCentral",
    "domain": "meshcentral.com",
    "category": "open-source-self-hosted",
    "tagline": "Complete web-based remote management platform for computer asset management",
    "description": "MeshCentral enables remote terminal access, web desktop management, and file transfer across Windows, Mac, and Linux endpoints. It is tailored for IT administrators, MSPs, and system engineers.",
    "rating": 4.8,
    "reviewsCount": 680,
    "pricing": "Free",
    "websiteUrl": "https://meshcentral.com",
    "affiliateUrl": "https://meshcentral.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "apache-guacamole",
    "name": "Apache Guacamole",
    "domain": "guacamole.apache.org",
    "category": "open-source-self-hosted",
    "tagline": "Clientless remote desktop gateway supporting RDP, VNC, and SSH in browser",
    "description": "Apache Guacamole grants secure remote access to desktop environments directly inside web browsers without client software plugins. It serves enterprise IT teams, remote workers, and system admins.",
    "rating": 4.7,
    "reviewsCount": 1150,
    "pricing": "Free",
    "websiteUrl": "https://guacamole.apache.org",
    "affiliateUrl": "https://guacamole.apache.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "immich",
    "name": "Immich",
    "domain": "immich.app",
    "category": "open-source-self-hosted",
    "tagline": "High-performance self-hosted photo and video backup solution and Google Photos alternative",
    "description": "Immich delivers seamless mobile photo auto-backup, facial recognition, partner sharing, and geo-map search on personal servers. It is tailored for privacy-conscious families, photography enthusiasts, and home lab builders.",
    "rating": 4.9,
    "reviewsCount": 2100,
    "pricing": "Free",
    "websiteUrl": "https://immich.app",
    "affiliateUrl": "https://immich.app",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "2.9M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "photoprism",
    "name": "PhotoPrism",
    "domain": "photoprism.app",
    "category": "open-source-self-hosted",
    "tagline": "AI-powered web app for organizing and browsing personal photo collections",
    "description": "PhotoPrism uses machine learning to automatically tag, organize, and categorize personal photo libraries hosted on private servers. It serves photographers, digital archivists, and privacy enthusiasts.",
    "rating": 4.8,
    "reviewsCount": 1250,
    "pricing": "Freemium",
    "websiteUrl": "https://photoprism.app",
    "affiliateUrl": "https://photoprism.app",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.6M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "mealie",
    "name": "Mealie",
    "domain": "mealie.io",
    "category": "open-source-self-hosted",
    "tagline": "Self-hosted recipe manager and meal planner with automated web scraping",
    "description": "Mealie extracts recipe details automatically from websites, manages household grocery lists, and schedules weekly meal plans. It is built for home cooks, meal planners, and family households.",
    "rating": 4.9,
    "reviewsCount": 680,
    "pricing": "Free",
    "websiteUrl": "https://mealie.io",
    "affiliateUrl": "https://mealie.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "820K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "linkwarden",
    "name": "Linkwarden",
    "domain": "linkwarden.app",
    "category": "open-source-self-hosted",
    "tagline": "Self-hosted collaborative bookmark manager to collect, annotate, and preserve web links",
    "description": "Linkwarden saves web links, captures webpage screenshot archives, and generates PDF copies to protect against broken web links. It is designed for researchers, content collectors, and home lab teams.",
    "rating": 4.9,
    "reviewsCount": 540,
    "pricing": "Freemium",
    "websiteUrl": "https://linkwarden.app",
    "affiliateUrl": "https://linkwarden.app",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "wallabag",
    "name": "wallabag",
    "domain": "wallabag.org",
    "category": "open-source-self-hosted",
    "tagline": "Self-hostable application for saving web pages and reading them offline",
    "description": "wallabag extracts text content from articles to build a distraction-free, offline-readable library alternative to Pocket or Instapaper. It is built for avid readers and web article collectors.",
    "rating": 4.7,
    "reviewsCount": 480,
    "pricing": "Freemium",
    "websiteUrl": "https://wallabag.org",
    "affiliateUrl": "https://wallabag.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "520K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "shlink-url",
    "name": "Shlink",
    "domain": "shlink.io",
    "category": "open-source-self-hosted",
    "tagline": "Self-hosted open-source URL shortener with REST API and detailed analytics",
    "description": "Shlink generates custom branded short links, tracks click geolocations, and provides REST APIs for automated link creation. It is built for marketers, developers, and privacy-first webmasters.",
    "rating": 4.8,
    "reviewsCount": 380,
    "pricing": "Free",
    "websiteUrl": "https://shlink.io",
    "affiliateUrl": "https://shlink.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "kutt-it",
    "name": "Kutt",
    "domain": "kutt.it",
    "category": "open-source-self-hosted",
    "tagline": "Free and open-source modern URL shortener with custom domain support",
    "description": "Kutt provides custom link shortening, custom domain attachment, QR code generation, and click analytics dashboards. It serves content creators, digital marketers, and web developers.",
    "rating": 4.7,
    "reviewsCount": 510,
    "pricing": "Free",
    "websiteUrl": "https://kutt.it",
    "affiliateUrl": "https://kutt.it",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "750K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "activepieces",
    "name": "Activepieces",
    "domain": "activepieces.com",
    "category": "open-source-self-hosted",
    "tagline": "Open-source no-code business automation tool and Zapier alternative",
    "description": "Activepieces connects web apps and executes automated workflow steps with a clean drag-and-drop builder interface. It serves small businesses, operations teams, and self-hosted developers.",
    "rating": 4.8,
    "reviewsCount": 450,
    "pricing": "Freemium",
    "websiteUrl": "https://activepieces.com",
    "affiliateUrl": "https://activepieces.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "windmill-dev",
    "name": "Windmill",
    "domain": "windmill.dev",
    "category": "open-source-self-hosted",
    "tagline": "Open-source developer platform to turn scripts into workflows, UIs, and scheduled jobs",
    "description": "Windmill converts Python, TypeScript, Go, and SQL scripts into auto-generated internal tools, webhooks, and workflow pipelines. It is engineered for software developers and platform engineers.",
    "rating": 4.9,
    "reviewsCount": 580,
    "pricing": "Freemium",
    "websiteUrl": "https://windmill.dev",
    "affiliateUrl": "https://windmill.dev",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "850K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "huginn-agent",
    "name": "Huginn",
    "domain": "github.com",
    "category": "open-source-self-hosted",
    "tagline": "Open-source system for building automated online agents that perform tasks for you",
    "description": "Huginn acts as a private automated agent engine that scrapes web data, monitors events, and sends custom notifications. It serves power users, data scrapers, and automation enthusiasts.",
    "rating": 4.7,
    "reviewsCount": 1100,
    "pricing": "Free",
    "websiteUrl": "https://github.com/huginn/huginn",
    "affiliateUrl": "https://github.com/huginn/huginn",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "920K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "glance-dashboard",
    "name": "Glance",
    "domain": "github.com",
    "category": "open-source-self-hosted",
    "tagline": "A lightweight, customizable home feed dashboard for all your services and feeds",
    "description": "Glance consolidates RSS feeds, weather updates, bookmark links, and server status widgets into a single minimalist dashboard. It is tailored for home lab enthusiasts and privacy-focused users.",
    "rating": 4.9,
    "reviewsCount": 320,
    "pricing": "Free",
    "websiteUrl": "https://github.com/glanceapp/glance",
    "affiliateUrl": "https://github.com/glanceapp/glance",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "homarr-dashboard",
    "name": "Homarr",
    "domain": "homarr.dev",
    "category": "open-source-self-hosted",
    "tagline": "Sleek, modern dashboard for managing your self-hosted services and homelab",
    "description": "Homarr integrates live Docker stats, media server controls, and service bookmark tiles into an elegant web portal interface. It serves home lab managers and self-hosting enthusiasts.",
    "rating": 4.9,
    "reviewsCount": 680,
    "pricing": "Free",
    "websiteUrl": "https://homarr.dev",
    "affiliateUrl": "https://homarr.dev",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "950K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "dashy-dashboard",
    "name": "Dashy",
    "domain": "dashy.to",
    "category": "open-source-self-hosted",
    "tagline": "The ultimate open-source, feature-rich dashboard for your home server",
    "description": "Dashy offers customizable layout themes, real-time widget monitoring, multi-page support, and auto-status checking. It is engineered for home lab managers and power users organizing homelab apps.",
    "rating": 4.8,
    "reviewsCount": 850,
    "pricing": "Free",
    "websiteUrl": "https://dashy.to",
    "affiliateUrl": "https://dashy.to",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "820K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "flame-dashboard",
    "name": "Flame",
    "domain": "github.com",
    "category": "open-source-self-hosted",
    "tagline": "Minimalist self-hosted startpage for your server with Docker integration",
    "description": "Flame automatically discovers running Docker containers to populate application launchers alongside custom bookmark categories. It serves home lab builders wanting a lightweight startpage.",
    "rating": 4.7,
    "reviewsCount": 510,
    "pricing": "Free",
    "websiteUrl": "https://github.com/pawelmalak/flame",
    "affiliateUrl": "https://github.com/pawelmalak/flame",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "uptime-kuma",
    "name": "Uptime Kuma",
    "domain": "uptime.kuma.pet",
    "category": "open-source-self-hosted",
    "tagline": "Fancy, self-hosted monitoring tool for HTTP, TCP, and ping uptime status",
    "description": "Uptime Kuma monitors server responsiveness, tracks SSL certificate expiration, and publishes customizable status pages with instant multi-channel alert notifications. It serves homelab managers and IT admins.",
    "rating": 4.9,
    "reviewsCount": 2100,
    "pricing": "Free",
    "websiteUrl": "https://uptime.kuma.pet",
    "affiliateUrl": "https://uptime.kuma.pet",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "statping-ng",
    "name": "Statping-ng",
    "domain": "github.com",
    "category": "open-source-self-hosted",
    "tagline": "An updated open-source status page and monitoring server for web applications",
    "description": "Statping-ng tracks service response times, alerts teams via webhooks, and displays public status dashboards during service incidents. It is built for IT admins, developers, and webmasters.",
    "rating": 4.6,
    "reviewsCount": 380,
    "pricing": "Free",
    "websiteUrl": "https://github.com/statping-ng/statping-ng",
    "affiliateUrl": "https://github.com/statping-ng/statping-ng",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "310K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "gatus-monitoring",
    "name": "Gatus",
    "domain": "gatus.io",
    "category": "open-source-self-hosted",
    "tagline": "Developer-oriented health dashboard and automated service status monitor",
    "description": "Gatus evaluates service health conditions using custom HTTP, ICMP, and DNS assertions declared in lightweight YAML configs. It serves DevOps engineers and cloud infrastructure operators.",
    "rating": 4.9,
    "reviewsCount": 420,
    "pricing": "Free",
    "websiteUrl": "https://gatus.io",
    "affiliateUrl": "https://gatus.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "450K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "change-detection",
    "name": "changedetection.io",
    "domain": "changedetection.io",
    "category": "open-source-self-hosted",
    "tagline": "Open-source web page change monitoring and notification service",
    "description": "changedetection.io tracks text updates, price adjustments, and PDF changes on target web pages, alerting users via Slack, Discord, or email. It serves price trackers, researchers, and developers.",
    "rating": 4.8,
    "reviewsCount": 510,
    "pricing": "Freemium",
    "websiteUrl": "https://changedetection.io",
    "affiliateUrl": "https://changedetection.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "750K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "gotify-server",
    "name": "Gotify",
    "domain": "gotify.net",
    "category": "open-source-self-hosted",
    "tagline": "Simple self-hosted push notification server for sending real-time messages to devices",
    "description": "Gotify receives push notifications via REST API and dispatches real-time alerts to Android devices and web clients. It is built for home lab managers and developers wanting self-hosted alerts.",
    "rating": 4.8,
    "reviewsCount": 620,
    "pricing": "Free",
    "websiteUrl": "https://gotify.net",
    "affiliateUrl": "https://gotify.net",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "580K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "apprise-notify",
    "name": "Apprise",
    "domain": "github.com",
    "category": "open-source-self-hosted",
    "tagline": "Universal push notification library and server supporting 80+ messaging services",
    "description": "Apprise provides a single unified notification endpoint to send alerts across Telegram, Discord, Email, SMS, and custom webhooks. It serves software developers and home lab automation leads.",
    "rating": 4.9,
    "reviewsCount": 850,
    "pricing": "Free",
    "websiteUrl": "https://github.com/caronc/apprise",
    "affiliateUrl": "https://github.com/caronc/apprise",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "820K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "ntfy-sh",
    "name": "ntfy",
    "domain": "ntfy.sh",
    "category": "open-source-self-hosted",
    "tagline": "Send push notifications to your phone or desktop via simple HTTP requests",
    "description": "ntfy dispatches instant mobile and desktop push alerts from scripts, servers, or webhooks using simple PUT/POST HTTP payloads. It serves system engineers, developers, and home lab builders.",
    "rating": 4.9,
    "reviewsCount": 980,
    "pricing": "Freemium",
    "websiteUrl": "https://ntfy.sh",
    "affiliateUrl": "https://ntfy.sh",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "calibre-web",
    "name": "Calibre-Web",
    "domain": "github.com",
    "category": "open-source-self-hosted",
    "tagline": "Web interface for browsing, reading, and downloading eBooks from Calibre databases",
    "description": "Calibre-Web provides a clean web interface to access ebook collections, send books to Kindle devices, and manage user reading permissions. It serves avid readers and digital book collectors.",
    "rating": 4.8,
    "reviewsCount": 1100,
    "pricing": "Free",
    "websiteUrl": "https://github.com/janarez/calibre-web",
    "affiliateUrl": "https://github.com/janarez/calibre-web",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "audiobookshelf",
    "name": "Audiobookshelf",
    "domain": "audiobookshelf.org",
    "category": "open-source-self-hosted",
    "tagline": "Self-hosted audiobook and podcast server with mobile streaming apps",
    "description": "Audiobookshelf manages personal audiobook and podcast media libraries, syncing listening progress across desktop and mobile devices. It is tailored for audiobook listeners and podcast collectors.",
    "rating": 4.9,
    "reviewsCount": 890,
    "pricing": "Free",
    "websiteUrl": "https://audiobookshelf.org",
    "affiliateUrl": "https://audiobookshelf.org",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "jellyfin",
    "name": "Jellyfin",
    "domain": "jellyfin.org",
    "category": "open-source-self-hosted",
    "tagline": "The free software media system for organizing, managing, and streaming personal media",
    "description": "Jellyfin streams personal movies, TV shows, music, and live TV to any client device with zero tracking, paywalls, or central servers. It is built for home media enthusiasts and open-source advocates.",
    "rating": 4.9,
    "reviewsCount": 3100,
    "pricing": "Free",
    "websiteUrl": "https://jellyfin.org",
    "affiliateUrl": "https://jellyfin.org",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "4.5M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "navidrome",
    "name": "Navidrome",
    "domain": "navidrome.org",
    "category": "open-source-self-hosted",
    "tagline": "Modern, open-source music server and streamer compatible with Subsonic clients",
    "description": "Navidrome indexes large digital music libraries to stream high-quality audio to desktop browsers and third-party mobile apps. It serves audiophiles and music library collectors.",
    "rating": 4.9,
    "reviewsCount": 750,
    "pricing": "Free",
    "websiteUrl": "https://navidrome.org",
    "affiliateUrl": "https://navidrome.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "820K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "kavita-reader",
    "name": "Kavita",
    "domain": "kavitareader.com",
    "category": "open-source-self-hosted",
    "tagline": "Fast, feature-rich self-hosted digital library for manga, comics, and eBooks",
    "description": "Kavita indexes digital manga, comic archives (CBZ/CBR), and EPUB files into a responsive, customizable web reader. It is engineered for comic collectors and manga enthusiasts.",
    "rating": 4.9,
    "reviewsCount": 620,
    "pricing": "Free",
    "websiteUrl": "https://kavitareader.com",
    "affiliateUrl": "https://kavitareader.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "780K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "komga-media",
    "name": "Komga",
    "domain": "komga.org",
    "category": "open-source-self-hosted",
    "tagline": "Media server for your comics, manga, webtoons, and digital books",
    "description": "Komga organizes digital comic archives and webtoons with built-in web reading interfaces and OPDS client compatibility. It serves comic collectors, manga readers, and digital archivists.",
    "rating": 4.8,
    "reviewsCount": 540,
    "pricing": "Free",
    "websiteUrl": "https://komga.org",
    "affiliateUrl": "https://komga.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "650K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "firefly-iii",
    "name": "Firefly III",
    "domain": "firefly-iii.org",
    "category": "open-source-self-hosted",
    "tagline": "Free and open-source personal finance manager to track budgets and expenses",
    "description": "Firefly III tracks bank accounts, recurring bills, budget targets, and financial reports while keeping financial data strictly private. It is built for budget-conscious individuals and self-hosters.",
    "rating": 4.8,
    "reviewsCount": 920,
    "pricing": "Free",
    "websiteUrl": "https://firefly-iii.org",
    "affiliateUrl": "https://firefly-iii.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "950K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "actual-budget",
    "name": "Actual Budget",
    "domain": "actualbudget.org",
    "category": "open-source-self-hosted",
    "tagline": "Super fast, privacy-focused open-source personal finance app using envelope budgeting",
    "description": "Actual Budget provides zero-based envelope budgeting, automated bank sync extensions, and local-first data encryption. It serves individuals and families taking control of personal finances.",
    "rating": 4.9,
    "reviewsCount": 850,
    "pricing": "Free",
    "websiteUrl": "https://actualbudget.org",
    "affiliateUrl": "https://actualbudget.org",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "open-webui",
    "name": "Open WebUI",
    "domain": "openwebui.com",
    "category": "open-source-self-hosted",
    "tagline": "User-friendly, self-hosted AI interface for Ollama and OpenAI-compatible APIs",
    "description": "Open WebUI provides a ChatGPT-like web dashboard equipped with RAG document uploading, model switching, multi-user access, and web search integration. It serves local AI enthusiasts and privacy-focused teams.",
    "rating": 4.9,
    "reviewsCount": 1820,
    "pricing": "Free",
    "websiteUrl": "https://openwebui.com",
    "affiliateUrl": "https://openwebui.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "3.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "localai-engine",
    "name": "LocalAI",
    "domain": "localai.io",
    "category": "open-source-self-hosted",
    "tagline": "Free, open-source local OpenAI-compatible REST API for LLMs, audio, and images",
    "description": "LocalAI acts as a drop-in local replacement for OpenAI APIs, executing text generation, speech-to-text, and image generation on consumer hardware. It serves software developers and local AI builders.",
    "rating": 4.8,
    "reviewsCount": 1150,
    "pricing": "Free",
    "websiteUrl": "https://localai.io",
    "affiliateUrl": "https://localai.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.6M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "ollama-ai",
    "name": "Ollama",
    "domain": "ollama.com",
    "category": "open-source-self-hosted",
    "tagline": "Get up and running with large language models locally on your hardware",
    "description": "Ollama bundles open-source LLMs like Llama, Mistral, and Gemma into local executable runtimes with OpenAI-compatible REST APIs. It is engineered for software developers, AI researchers, and privacy advocates.",
    "rating": 4.9,
    "reviewsCount": 3100,
    "pricing": "Free",
    "websiteUrl": "https://ollama.com",
    "affiliateUrl": "https://ollama.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "6.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "jan-ai",
    "name": "Jan",
    "domain": "jan.ai",
    "category": "open-source-self-hosted",
    "tagline": "Rethinking local AI - an open-source, privacy-first desktop alternative to ChatGPT",
    "description": "Jan downloads and executes open-source large language models locally on consumer computers with complete offline data privacy. It is tailored for developers, researchers, and privacy-conscious users.",
    "rating": 4.9,
    "reviewsCount": 1250,
    "pricing": "Free",
    "websiteUrl": "https://jan.ai",
    "affiliateUrl": "https://jan.ai",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "microbin-paste",
    "name": "MicroBin",
    "domain": "microbin.eu",
    "category": "open-source-self-hosted",
    "tagline": "Super tiny, self-hosted, encrypted pastebin and file-sharing web application",
    "description": "MicroBin allows users to paste text code snippets and upload temporary files with client-side encryption and custom expiration limits. It serves developers, sysadmins, and privacy purists.",
    "rating": 4.8,
    "reviewsCount": 290,
    "pricing": "Free",
    "websiteUrl": "https://microbin.eu",
    "affiliateUrl": "https://microbin.eu",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "340K",
    "isFreeTier": true,
    "isOpenSource": true
  }
];

const targetPath = path.join(__dirname, '../src/data/saasData.jsx');
let content = fs.readFileSync(targetPath, 'utf8');

// Ensure saasCategories has open-source-self-hosted
if (!content.includes('"open-source-self-hosted"')) {
  console.log('Adding open-source-self-hosted category to saasCategories...');
  content = content.replace(
    '  { "id": "devops-infrastructure", "label": "DevOps & Cloud Infrastructure" }',
    '  { "id": "devops-infrastructure", "label": "DevOps & Cloud Infrastructure" },\n  { "id": "open-source-self-hosted", "label": "Open-Source & Self-Hosted" }'
  );
}

// Build existing domains set
const existingDomains = new Set();
const existingNames = new Set();
const domainMatches = content.matchAll(/"domain":\s*"([^"]+)"/g);
for (const match of domainMatches) {
  existingDomains.add(match[1].toLowerCase());
}
const nameMatches = content.matchAll(/"name":\s*"([^"]+)"/g);
for (const match of nameMatches) {
  existingNames.add(match[1].toLowerCase());
}

console.log(`Initial DB has ${existingDomains.size} domains and ${existingNames.size} tool names.`);

const defaultFeatures = [
  "Privacy & Self-Hosted Data",
  "Zero Vendor Lock-In",
  "Community Driven",
  "Automated Deployment"
];

const newToolsToInsert = [];
for (const tool of selfHostedTools) {
  const normDomain = tool.domain.toLowerCase();
  const normName = tool.name.toLowerCase();

  // If domain is github.com, check by name instead of domain alone
  const isDuplicate = normDomain !== 'github.com'
    ? (existingDomains.has(normDomain) || existingNames.has(normName))
    : existingNames.has(normName);

  if (isDuplicate) {
    console.log(`[SKIP DUPLICATE] ${tool.name} (${tool.domain})`);
    continue;
  }

  tool.features = defaultFeatures;
  newToolsToInsert.push(tool);
  if (normDomain !== 'github.com') existingDomains.add(normDomain);
  existingNames.add(normName);
}

console.log(`Found ${newToolsToInsert.length} NEW Self-Hosted tools to insert. Skipped ${selfHostedTools.length - newToolsToInsert.length} duplicates.`);

if (newToolsToInsert.length > 0) {
  const formattedTools = newToolsToInsert.map(t => JSON.stringify(t, null, 4)).join(',\n');
  const insertionMarker = 'export const staticSaasTools = [\n';
  content = content.replace(insertionMarker, insertionMarker + formattedTools + ',\n');
  fs.writeFileSync(targetPath, content, 'utf8');
  console.log(`Successfully ingested ${newToolsToInsert.length} new Self-Hosted tools into src/data/saasData.jsx!`);
} else {
  console.log('No new tools to insert.');
}
