const fs = require('fs');
const path = require('path');

const newTools = [
  {
    "id": "quickbooks",
    "name": "QuickBooks Online",
    "domain": "quickbooks.intuit.com",
    "category": "invoicing",
    "tagline": "Industry-standard cloud accounting and invoicing software for small businesses",
    "description": "QuickBooks Online handles invoicing, expense tracking, payroll, and financial reporting in one unified dashboard. It is designed for small business owners, accountants, and growing startups.",
    "rating": 4.7,
    "reviewsCount": 3850,
    "pricing": "Paid",
    "websiteUrl": "https://quickbooks.intuit.com",
    "affiliateUrl": "https://quickbooks.intuit.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "18.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "xero",
    "name": "Xero",
    "domain": "xero.com",
    "category": "invoicing",
    "tagline": "Beautiful cloud accounting software for small businesses and bookkeepers",
    "description": "Xero streamlines daily financial management with automated bank reconciliation, online invoicing, and expense claims. It is tailored for small businesses, accountants, and bookkeepers worldwide.",
    "rating": 4.6,
    "reviewsCount": 2410,
    "pricing": "Paid",
    "websiteUrl": "https://xero.com",
    "affiliateUrl": "https://xero.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "9.5M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "freshbooks",
    "name": "FreshBooks",
    "domain": "freshbooks.com",
    "category": "invoicing",
    "tagline": "Invoicing and accounting software built for freelancers and service SMBs",
    "description": "FreshBooks simplifies client invoicing, billable hour tracking, and project expense management. It is built specifically for freelancers, agencies, and service-based small businesses.",
    "rating": 4.5,
    "reviewsCount": 1820,
    "pricing": "Paid",
    "websiteUrl": "https://freshbooks.com",
    "affiliateUrl": "https://freshbooks.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "3.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "wave",
    "name": "Wave",
    "domain": "waveapps.com",
    "category": "invoicing",
    "tagline": "Free accounting and invoicing software for solopreneurs and small teams",
    "description": "Wave offers zero-cost invoicing, accounting, and receipt tracking with optional pay-per-use payment processing. It is ideal for freelancers, consultants, and micro-business owners.",
    "rating": 4.4,
    "reviewsCount": 1290,
    "pricing": "Freemium",
    "websiteUrl": "https://waveapps.com",
    "affiliateUrl": "https://waveapps.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "zoho-books",
    "name": "Zoho Books",
    "domain": "zoho.com/books",
    "category": "invoicing",
    "tagline": "Smart, end-to-end cloud accounting software for growing businesses",
    "description": "Zoho Books manages recurring billing, inventory tracking, VAT/tax compliance, and client portals seamlessly. It is designed for small to mid-sized businesses seeking an integrated financial suite.",
    "rating": 4.6,
    "reviewsCount": 1150,
    "pricing": "Freemium",
    "websiteUrl": "https://zoho.com/books",
    "affiliateUrl": "https://zoho.com/books",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "5.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "stripe-billing",
    "name": "Stripe Billing",
    "domain": "stripe.com/billing",
    "category": "invoicing",
    "tagline": "Flexible subscription billing and automated global invoicing infrastructure",
    "description": "Stripe Billing automates recurring subscriptions, metered usage pricing, dunning management, and global tax calculation via API. It is tailored for SaaS companies, e-commerce platforms, and digital businesses.",
    "rating": 4.8,
    "reviewsCount": 1950,
    "pricing": "Paid",
    "websiteUrl": "https://stripe.com/billing",
    "affiliateUrl": "https://stripe.com/billing",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "28.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "chargebee",
    "name": "Chargebee",
    "domain": "chargebee.com",
    "category": "invoicing",
    "tagline": "Subscription management and recurring billing platform for SaaS",
    "description": "Chargebee automates subscriber lifecycles, recurring invoices, proration, and revenue recognition across global gateways. It is built for B2B and B2C subscription businesses scaling their revenue operations.",
    "rating": 4.7,
    "reviewsCount": 680,
    "pricing": "Freemium",
    "websiteUrl": "https://chargebee.com",
    "affiliateUrl": "https://chargebee.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "recurly",
    "name": "Recurly",
    "domain": "recurly.com",
    "category": "invoicing",
    "tagline": "Enterprise subscription billing and recurring payment engine",
    "description": "Recurly provides automated subscription management, intelligent payment recovery, and multi-currency invoicing. It is optimized for high-growth subscription brands looking to minimize churn.",
    "rating": 4.5,
    "reviewsCount": 320,
    "pricing": "Paid",
    "websiteUrl": "https://recurly.com",
    "affiliateUrl": "https://recurly.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "splitwise",
    "name": "Splitwise",
    "domain": "splitwise.com",
    "category": "invoicing",
    "tagline": "The easy way to share expenses and settle balances with friends and roommates",
    "description": "Splitwise tracks shared household bills, group travel costs, and shared expenses while calculating net balances automatically. It is designed for roommates, travelers, and social groups managing group costs.",
    "rating": 4.8,
    "reviewsCount": 4200,
    "pricing": "Freemium",
    "websiteUrl": "https://splitwise.com",
    "affiliateUrl": "https://splitwise.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "12.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "expensify",
    "name": "Expensify",
    "domain": "expensify.com",
    "category": "invoicing",
    "tagline": "Automated receipt scanning and corporate expense management platform",
    "description": "Expensify automates receipt capture, expense approvals, employee reimbursements, and corporate card tracking. It serves individual business travelers as well as enterprise financial teams.",
    "rating": 4.5,
    "reviewsCount": 1540,
    "pricing": "Freemium",
    "websiteUrl": "https://expensify.com",
    "affiliateUrl": "https://expensify.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "ramp",
    "name": "Ramp",
    "domain": "ramp.com",
    "category": "invoicing",
    "tagline": "Corporate cards, spend management, and automated accounts payable",
    "description": "Ramp combines corporate credit cards with AI receipt matching, automated vendor bill pay, and real-time spend controls. It is built for modern finance teams seeking automated expense control.",
    "rating": 4.8,
    "reviewsCount": 980,
    "pricing": "Free",
    "websiteUrl": "https://ramp.com",
    "affiliateUrl": "https://ramp.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "3.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "brex",
    "name": "Brex",
    "domain": "brex.com",
    "category": "invoicing",
    "tagline": "AI corporate cards, global spend management, and bill pay engine",
    "description": "Brex offers high-limit corporate cards, automated global bill payments, expense tracking, and travel booking in one platform. It is designed for venture-backed startups and scaling enterprises.",
    "rating": 4.7,
    "reviewsCount": 850,
    "pricing": "Freemium",
    "websiteUrl": "https://brex.com",
    "affiliateUrl": "https://brex.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "bill-com",
    "name": "Bill",
    "domain": "bill.com",
    "category": "invoicing",
    "tagline": "Automated accounts payable and accounts receivable management software",
    "description": "Bill automates vendor payment approvals, digital ACH transfers, and electronic customer invoicing. It is built for small to mid-sized businesses automating back-office financial workflows.",
    "rating": 4.4,
    "reviewsCount": 1120,
    "pricing": "Paid",
    "websiteUrl": "https://bill.com",
    "affiliateUrl": "https://bill.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "6.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "melio",
    "name": "Melio",
    "domain": "meliopayments.com",
    "category": "invoicing",
    "tagline": "Simple accounts payable tool for small businesses to pay bills online",
    "description": "Melio enables small businesses to pay vendor bills via bank transfer or credit card with automated accounting sync. It is tailored for small business owners optimizing cash flow management.",
    "rating": 4.6,
    "reviewsCount": 740,
    "pricing": "Freemium",
    "websiteUrl": "https://meliopayments.com",
    "affiliateUrl": "https://meliopayments.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "invoice-ninja",
    "name": "Invoice Ninja",
    "domain": "invoiceninja.com",
    "category": "invoicing",
    "tagline": "Open-source invoicing, expense tracking, and time management suite",
    "description": "Invoice Ninja provides open-source invoice creation, vendor payment tracking, client portals, and proposal generation. It is designed for freelancers and small businesses requiring self-hosted or cloud billing.",
    "rating": 4.7,
    "reviewsCount": 490,
    "pricing": "Freemium",
    "websiteUrl": "https://invoiceninja.com",
    "affiliateUrl": "https://invoiceninja.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "510K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "zoho-invoice",
    "name": "Zoho Invoice",
    "domain": "zoho.com/invoice",
    "category": "invoicing",
    "tagline": "100% free online invoicing software for small businesses and freelancers",
    "description": "Zoho Invoice allows users to generate professional invoices, track billable time, send automated payment reminders, and accept online payments. It is completely free for small businesses and freelancers.",
    "rating": 4.7,
    "reviewsCount": 890,
    "pricing": "Free",
    "websiteUrl": "https://zoho.com/invoice",
    "affiliateUrl": "https://zoho.com/invoice",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "bonsai",
    "name": "Bonsai",
    "domain": "hellobonsai.com",
    "category": "invoicing",
    "tagline": "All-in-one business management, invoicing, and contract tool for agencies",
    "description": "Bonsai combines client contracts, proposals, time tracking, custom invoicing, and simple tax accounting into a single interface. It is built for agencies, consultants, and independent freelancers.",
    "rating": 4.6,
    "reviewsCount": 620,
    "pricing": "Paid",
    "websiteUrl": "https://hellobonsai.com",
    "affiliateUrl": "https://hellobonsai.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "square-invoicing",
    "name": "Square Invoicing",
    "domain": "squareup.com/invoices",
    "category": "invoicing",
    "tagline": "Send digital estimates and invoices with integrated payment processing",
    "description": "Square Invoicing lets businesses send customized digital estimates and invoices directly to clients for credit card or ACH payment. It is optimized for retail, service contractors, and mobile vendors.",
    "rating": 4.6,
    "reviewsCount": 1410,
    "pricing": "Freemium",
    "websiteUrl": "https://squareup.com/invoices",
    "affiliateUrl": "https://squareup.com/invoices",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "14.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "invoicely",
    "name": "Invoicely",
    "domain": "invoicely.com",
    "category": "invoicing",
    "tagline": "Free online invoicing for freelancers and small business owners",
    "description": "Invoicely enables instant multi-currency invoice creation, billable time tracking, and customer payment processing. It is designed for freelancers and small teams seeking uncomplicated billing software.",
    "rating": 4.4,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://invoicely.com",
    "affiliateUrl": "https://invoicely.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "420K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "sage-intacct",
    "name": "Sage Intacct",
    "domain": "sage.com",
    "category": "invoicing",
    "tagline": "Enterprise cloud financial management and ERP accounting software",
    "description": "Sage Intacct delivers advanced multi-entity accounting, general ledger automation, accounts payable, and revenue recognition. It is built for growing mid-market and enterprise financial departments.",
    "rating": 4.5,
    "reviewsCount": 1100,
    "pricing": "Paid",
    "websiteUrl": "https://sage.com",
    "affiliateUrl": "https://sage.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "netsuite",
    "name": "Oracle NetSuite ERP",
    "domain": "netsuite.com",
    "category": "invoicing",
    "tagline": "Comprehensive cloud ERP platform for enterprise financial operations",
    "description": "Oracle NetSuite unifies enterprise accounting, order management, subscription billing, and inventory control into a single cloud system. It is engineered for global mid-market and enterprise companies.",
    "rating": 4.4,
    "reviewsCount": 2150,
    "pricing": "Paid",
    "websiteUrl": "https://netsuite.com",
    "affiliateUrl": "https://netsuite.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "7.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "tipalti",
    "name": "Tipalti",
    "domain": "tipalti.com",
    "category": "invoicing",
    "tagline": "Global payables automation and supplier invoice processing software",
    "description": "Tipalti automates international supplier payouts, tax form collection, 2-way/3-way PO matching, and global payment reconciliation. It serves high-volume digital platforms, marketplaces, and global enterprises.",
    "rating": 4.6,
    "reviewsCount": 410,
    "pricing": "Paid",
    "websiteUrl": "https://tipalti.com",
    "affiliateUrl": "https://tipalti.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "pleo",
    "name": "Pleo",
    "domain": "pleo.io",
    "category": "invoicing",
    "tagline": "Smart business cards and automated expense management solution",
    "description": "Pleo issues physical and virtual corporate cards paired with automated receipt scanning, invoice payments, and accounting sync. It is tailored for European small-to-medium businesses streamlining spending.",
    "rating": 4.7,
    "reviewsCount": 590,
    "pricing": "Paid",
    "websiteUrl": "https://pleo.io",
    "affiliateUrl": "https://pleo.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "820K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "payhawk",
    "name": "Payhawk",
    "domain": "payhawk.com",
    "category": "invoicing",
    "tagline": "All-in-one company card, spend management, and invoice payable engine",
    "description": "Payhawk consolidates corporate visa cards, automated subscription management, vendor invoice processing, and ERP accounting sync. It is designed for international finance teams managing multi-currency spend.",
    "rating": 4.8,
    "reviewsCount": 310,
    "pricing": "Paid",
    "websiteUrl": "https://payhawk.com",
    "affiliateUrl": "https://payhawk.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "390K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "maxio",
    "name": "Maxio",
    "domain": "maxio.com",
    "category": "invoicing",
    "tagline": "Financial operations, subscription billing, and revenue recognition for SaaS",
    "description": "Maxio combines complex B2B subscription management with automated ASC 606 revenue recognition and SaaS financial metrics. It is built specifically for B2B SaaS leadership and finance teams.",
    "rating": 4.5,
    "reviewsCount": 240,
    "pricing": "Paid",
    "websiteUrl": "https://maxio.com",
    "affiliateUrl": "https://maxio.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "290K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "orb",
    "name": "Orb",
    "domain": "withorb.com",
    "category": "invoicing",
    "tagline": "Composable usage-based billing and rating engine for modern software",
    "description": "Orb handles high-volume usage metering, real-time consumption pricing, custom enterprise contract billing, and automated invoicing. It serves engineering-led AI, cloud, and API infrastructure companies.",
    "rating": 4.8,
    "reviewsCount": 110,
    "pricing": "Paid",
    "websiteUrl": "https://withorb.com",
    "affiliateUrl": "https://withorb.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "150K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "lago",
    "name": "Lago",
    "domain": "getlago.com",
    "category": "invoicing",
    "tagline": "Open-source metering and usage-based billing infrastructure",
    "description": "Lago offers an open-source architecture for meter rating, usage-based pricing, hybrid subscriptions, and automated invoicing. It is designed for developers building custom in-house billing systems.",
    "rating": 4.7,
    "reviewsCount": 190,
    "pricing": "Freemium",
    "websiteUrl": "https://getlago.com",
    "affiliateUrl": "https://getlago.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "180K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "metronome",
    "name": "Metronome",
    "domain": "metronome.com",
    "category": "invoicing",
    "tagline": "Usage-based billing platform designed for high-growth AI and tech products",
    "description": "Metronome processes real-time usage data streams to power dynamic usage-based pricing models, credit systems, and invoices. It is engineered for fast-scaling AI, data, and developer tool platforms.",
    "rating": 4.8,
    "reviewsCount": 95,
    "pricing": "Paid",
    "websiteUrl": "https://metronome.com",
    "affiliateUrl": "https://metronome.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "120K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "quaderno",
    "name": "Quaderno",
    "domain": "quaderno.io",
    "category": "invoicing",
    "tagline": "Automated sales tax, VAT, and GST calculation and invoicing engine",
    "description": "Quaderno calculates international digital sales taxes in real time, issues compliant tax receipts, and generates global tax filing reports. It is built for e-commerce, SaaS, and digital product sellers globally.",
    "rating": 4.6,
    "reviewsCount": 180,
    "pricing": "Paid",
    "websiteUrl": "https://quaderno.io",
    "affiliateUrl": "https://quaderno.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "160K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "taxjar",
    "name": "TaxJar",
    "domain": "taxjar.com",
    "category": "invoicing",
    "tagline": "Automated US sales tax compliance, calculation, and reporting software",
    "description": "TaxJar provides real-time sales tax calculation at checkout, economic nexus tracking, and automated multi-state tax filing. It is designed for US e-commerce merchants and digital storefronts.",
    "rating": 4.5,
    "reviewsCount": 620,
    "pricing": "Paid",
    "websiteUrl": "https://taxjar.com",
    "affiliateUrl": "https://taxjar.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "950K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "anrok",
    "name": "Anrok",
    "domain": "anrok.com",
    "category": "invoicing",
    "tagline": "Global sales tax and VAT compliance engine built specifically for SaaS",
    "description": "Anrok connects with modern subscription billing stacks to track global tax nexus thresholds, calculate local taxes, and manage filings. It is built tailored for SaaS CFOs and finance teams.",
    "rating": 4.9,
    "reviewsCount": 85,
    "pricing": "Paid",
    "websiteUrl": "https://anrok.com",
    "affiliateUrl": "https://anrok.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "110K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "freeagent",
    "name": "FreeAgent",
    "domain": "freeagent.com",
    "category": "invoicing",
    "tagline": "Online accounting software for UK contractors, freelancers, and small businesses",
    "description": "FreeAgent manages self-assessment tax calculations, MTD VAT filing, professional invoicing, and live bank feed reconciliation. It is tailored for UK-based small business owners and freelancers.",
    "rating": 4.7,
    "reviewsCount": 810,
    "pricing": "Paid",
    "websiteUrl": "https://freeagent.com",
    "affiliateUrl": "https://freeagent.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.3M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "kashflow",
    "name": "KashFlow",
    "domain": "kashflow.com",
    "category": "invoicing",
    "tagline": "Simple UK-tailored cloud accounting and online invoicing software",
    "description": "KashFlow simplifies UK VAT submission, professional invoice generation, expense tracking, and payroll processing. It is built for small UK sole traders, contractors, and small businesses.",
    "rating": 4.3,
    "reviewsCount": 290,
    "pricing": "Paid",
    "websiteUrl": "https://kashflow.com",
    "affiliateUrl": "https://kashflow.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "310K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "harvest",
    "name": "Harvest",
    "domain": "getharvest.com",
    "category": "invoicing",
    "tagline": "Time tracking, project cost accounting, and online invoicing platform",
    "description": "Harvest converts tracked project hours and expense records directly into detailed, payable client invoices. It is built for agencies, design studios, and professional consulting teams.",
    "rating": 4.6,
    "reviewsCount": 1280,
    "pricing": "Freemium",
    "websiteUrl": "https://getharvest.com",
    "affiliateUrl": "https://getharvest.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "toggl-track",
    "name": "Toggl Track",
    "domain": "toggl.com/track",
    "category": "invoicing",
    "tagline": "Time tracking software with integrated billable hour reporting and client invoicing",
    "description": "Toggl Track logs billable project hours across devices and generates detailed client time summaries for easy invoicing. It is popular among freelancers, remote teams, and creative agencies.",
    "rating": 4.7,
    "reviewsCount": 2100,
    "pricing": "Freemium",
    "websiteUrl": "https://toggl.com/track",
    "affiliateUrl": "https://toggl.com/track",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.6M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "invoice-simple",
    "name": "Invoice Simple",
    "domain": "invoicesimple.com",
    "category": "invoicing",
    "tagline": "Quick invoice maker app for contractors and small business owners",
    "description": "Invoice Simple provides a mobile-first invoice generator to send client estimates and receipts directly from job sites. It is tailored for field contractors, trade professionals, and local service providers.",
    "rating": 4.6,
    "reviewsCount": 890,
    "pricing": "Freemium",
    "websiteUrl": "https://invoicesimple.com",
    "affiliateUrl": "https://invoicesimple.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "hiveage",
    "name": "Hiveage",
    "domain": "hiveage.com",
    "category": "invoicing",
    "tagline": "Fast, cloud-based online invoicing and billing for small businesses",
    "description": "Hiveage delivers custom invoice creation, recurring billing, team time tracking, and multi-currency reporting. It is designed for freelancers and small businesses needing clean online payment billing.",
    "rating": 4.4,
    "reviewsCount": 160,
    "pricing": "Freemium",
    "websiteUrl": "https://hiveage.com",
    "affiliateUrl": "https://hiveage.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "140K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "plooto",
    "name": "Plooto",
    "domain": "plooto.com",
    "category": "invoicing",
    "tagline": "Automated B2B payments and accounts payable/receivable platform",
    "description": "Plooto automates domestic and international ACH transfers, approval workflows, and two-way accounting sync. It is designed for small to mid-sized businesses streamlining vendor payments.",
    "rating": 4.5,
    "reviewsCount": 210,
    "pricing": "Paid",
    "websiteUrl": "https://plooto.com",
    "affiliateUrl": "https://plooto.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "280K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "avidxchange",
    "name": "AvidXchange",
    "domain": "avidxchange.com",
    "category": "invoicing",
    "tagline": "Accounts payable automation and electronic payment software",
    "description": "AvidXchange digitizes paper invoice processing, approval routing, and electronic vendor payments for mid-market operational teams. It serves real estate, construction, financial, and healthcare industries.",
    "rating": 4.3,
    "reviewsCount": 310,
    "pricing": "Paid",
    "websiteUrl": "https://avidxchange.com",
    "affiliateUrl": "https://avidxchange.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "610K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "vic-ai",
    "name": "Vic.ai",
    "domain": "vic.ai",
    "category": "invoicing",
    "tagline": "Autonomous AI accounts payable and invoice processing software",
    "description": "Vic.ai uses computer vision and deep learning to ingest, code, and approve high-volume enterprise vendor invoices automatically. It is engineered for enterprise CFOs and accounting service firms.",
    "rating": 4.8,
    "reviewsCount": 75,
    "pricing": "Paid",
    "websiteUrl": "https://vic.ai",
    "affiliateUrl": "https://vic.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "90K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "rossum",
    "name": "Rossum",
    "domain": "rossum.ai",
    "category": "invoicing",
    "tagline": "AI document processing engine for transactional invoices and POs",
    "description": "Rossum extracts, validates, and routes data automatically from complex, unstructured invoices directly into enterprise ERPs. It serves global logistics, manufacturing, and enterprise accounting divisions.",
    "rating": 4.6,
    "reviewsCount": 140,
    "pricing": "Paid",
    "websiteUrl": "https://rossum.ai",
    "affiliateUrl": "https://rossum.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "210K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "docuclipper",
    "name": "DocuClipper",
    "domain": "docuclipper.com",
    "category": "invoicing",
    "tagline": "OCR bank statement converter and automatic invoice data extractor",
    "description": "DocuClipper extracts data accurately from PDF invoices, receipts, and bank statements into Excel or accounting software. It is built for bookkeepers, accountants, and financial auditors.",
    "rating": 4.7,
    "reviewsCount": 110,
    "pricing": "Paid",
    "websiteUrl": "https://docuclipper.com",
    "affiliateUrl": "https://docuclipper.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "130K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "precoro",
    "name": "Precoro",
    "domain": "precoro.com",
    "category": "invoicing",
    "tagline": "Procurement software and automated purchase order management system",
    "description": "Precoro eliminates manual purchase ordering, speeds up 3-way invoice matching, and enforces corporate purchasing budgets. It is designed for mid-sized business operations and purchasing departments.",
    "rating": 4.8,
    "reviewsCount": 230,
    "pricing": "Paid",
    "websiteUrl": "https://precoro.com",
    "affiliateUrl": "https://precoro.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "240K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "ziphq",
    "name": "Zip",
    "domain": "ziphq.com",
    "category": "invoicing",
    "tagline": "Intake-to-pay procurement and AI invoice processing platform",
    "description": "Zip centralizes corporate procurement intake, vendor approvals, contract tracking, and automated bill payment processing. It is engineered for enterprise organizations looking to control indirect spend.",
    "rating": 4.8,
    "reviewsCount": 180,
    "pricing": "Paid",
    "websiteUrl": "https://ziphq.com",
    "affiliateUrl": "https://ziphq.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "310K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "order-co",
    "name": "Order.co",
    "domain": "order.co",
    "category": "invoicing",
    "tagline": "Procurement and accounts payable automation software",
    "description": "Order.co simplifies vendor purchasing, enforces spend guidelines, and consolidates hundreds of monthly supply invoices into a single bill. It is tailored for multi-location businesses and corporate operations.",
    "rating": 4.6,
    "reviewsCount": 150,
    "pricing": "Paid",
    "websiteUrl": "https://order.co",
    "affiliateUrl": "https://order.co",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "190K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "billomat",
    "name": "Billomat",
    "domain": "billomat.com",
    "category": "invoicing",
    "tagline": "Web-based invoicing software and bookkeeping application for European businesses",
    "description": "Billomat automates online invoice creation, estimate generation, dunning workflows, and banking synchronization. It is built specifically for European freelancers, startups, and small businesses.",
    "rating": 4.4,
    "reviewsCount": 130,
    "pricing": "Paid",
    "websiteUrl": "https://billomat.com",
    "affiliateUrl": "https://billomat.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "180K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "younium",
    "name": "Younium",
    "domain": "younium.com",
    "category": "invoicing",
    "tagline": "B2B subscription management and contract hub for growing SaaS companies",
    "description": "Younium manages complex B2B subscription contracts, price revisions, recurring invoices, and SaaS metric tracking. It serves B2B software companies with multi-year custom enterprise contracts.",
    "rating": 4.6,
    "reviewsCount": 95,
    "pricing": "Paid",
    "websiteUrl": "https://younium.com",
    "affiliateUrl": "https://younium.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "85K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "tricount",
    "name": "Tricount",
    "domain": "tricount.com",
    "category": "invoicing",
    "tagline": "Simple group expense sharing app for trips, events, and household bills",
    "description": "Tricount tracks group expenses on mobile devices, organizing shared costs and calculating optimal balance settlements. It is popular among group travelers, event organizers, and roommates.",
    "rating": 4.7,
    "reviewsCount": 2800,
    "pricing": "Freemium",
    "websiteUrl": "https://tricount.com",
    "affiliateUrl": "https://tricount.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.9M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "outseta",
    "name": "Outseta",
    "domain": "outseta.com",
    "category": "invoicing",
    "tagline": "All-in-one membership management, CRM, and subscription billing software",
    "description": "Outseta integrates subscription billing, gated content authentication, lightweight CRM, and automated email invoicing into one platform. It is engineered for bootstrapped startups and creator membership sites.",
    "rating": 4.8,
    "reviewsCount": 110,
    "pricing": "Paid",
    "websiteUrl": "https://outseta.com",
    "affiliateUrl": "https://outseta.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "140K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "spendflo",
    "name": "Spendflo",
    "domain": "spendflo.com",
    "category": "invoicing",
    "tagline": "SaaS buying, contract management, and software spend optimization",
    "description": "Spendflo tracks corporate software licenses, automates vendor renewals, monitors usage, and negotiates SaaS invoices. It is designed for modern finance and IT ops leaders looking to optimize software costs.",
    "rating": 4.7,
    "reviewsCount": 120,
    "pricing": "Paid",
    "websiteUrl": "https://spendflo.com",
    "affiliateUrl": "https://spendflo.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "160K",
    "isFreeTier": false,
    "isOpenSource": false
  }
];

const saasDataPath = path.join(__dirname, '..', 'src', 'data', 'saasData.jsx');
let content = fs.readFileSync(saasDataPath, 'utf8');

const match = content.match(/export const staticSaasTools = (\[[\s\S]*?\n\]);/);
if (!match) {
  console.error('Could not find staticSaasTools in saasData.jsx');
  process.exit(1);
}

let existingTools = JSON.parse(match[1]);

const existingIds = new Set(existingTools.map(t => t.id));
let addedCount = 0;

newTools.forEach(tool => {
  if (!existingIds.has(tool.id)) {
    existingTools.push(tool);
    existingIds.add(tool.id);
    addedCount++;
  } else {
    // Update existing tool with richer data
    const idx = existingTools.findIndex(t => t.id === tool.id);
    if (idx !== -1) {
      existingTools[idx] = { ...existingTools[idx], ...tool };
    }
  }
});

const updatedArrayStr = JSON.stringify(existingTools, null, 2);
content = content.replace(/export const staticSaasTools = \[[\s\S]*?\n\];/, `export const staticSaasTools = ${updatedArrayStr};`);

fs.writeFileSync(saasDataPath, content, 'utf8');
console.log(`Successfully ingested ${addedCount} new Invoicing & Accounting tools. Total static tools: ${existingTools.length}`);
