const fs = require('fs');
const path = require('path');

const newTools = [
  {
    "id": "1password",
    "name": "1Password",
    "domain": "1password.com",
    "category": "security-passwords",
    "tagline": "Password manager and digital vault for individuals, families, and businesses",
    "description": "1Password securely stores passwords, credit cards, and sensitive notes behind end-to-end encryption. It is built for teams and individuals seeking seamless credential sharing and strong access security.",
    "rating": 4.8,
    "reviewsCount": 3200,
    "pricing": "Paid",
    "websiteUrl": "https://1password.com",
    "affiliateUrl": "https://1password.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "14.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "bitwarden",
    "name": "Bitwarden",
    "domain": "bitwarden.com",
    "category": "security-passwords",
    "tagline": "Open-source password manager for personal and enterprise credential security",
    "description": "Bitwarden provides zero-knowledge password management across all devices with self-hosting options. It is designed for privacy-focused individuals, developers, and security teams.",
    "rating": 4.9,
    "reviewsCount": 4100,
    "pricing": "Freemium",
    "websiteUrl": "https://bitwarden.com",
    "affiliateUrl": "https://bitwarden.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "11.5M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "dashlane",
    "name": "Dashlane",
    "domain": "dashlane.com",
    "category": "security-passwords",
    "tagline": "Password manager and digital identity protection suite",
    "description": "Dashlane simplifies login security with automatic password generation, dark web monitoring, and integrated VPN access. It is ideal for personal users and businesses wanting effortless security management.",
    "rating": 4.6,
    "reviewsCount": 2100,
    "pricing": "Freemium",
    "websiteUrl": "https://dashlane.com",
    "affiliateUrl": "https://dashlane.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "lastpass",
    "name": "LastPass",
    "domain": "lastpass.com",
    "category": "security-passwords",
    "tagline": "Password management and vault storage across web and mobile",
    "description": "LastPass saves login credentials, generates strong passwords, and auto-fills web forms across all major platforms. It serves personal users and corporate IT departments managing user permissions.",
    "rating": 4.3,
    "reviewsCount": 2850,
    "pricing": "Freemium",
    "websiteUrl": "https://lastpass.com",
    "affiliateUrl": "https://lastpass.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "9.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "keeper",
    "name": "Keeper Password Manager",
    "domain": "keepersecurity.com",
    "category": "security-passwords",
    "tagline": "Cybersecurity and zero-trust password management for enterprises and individuals",
    "description": "Keeper delivers zero-knowledge encryption to safeguard passwords, secrets, and confidential files. It is engineered for enterprise IT teams requiring strict compliance and granular access controls.",
    "rating": 4.7,
    "reviewsCount": 1450,
    "pricing": "Freemium",
    "websiteUrl": "https://keepersecurity.com",
    "affiliateUrl": "https://keepersecurity.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.9M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "proton-pass",
    "name": "Proton Pass",
    "domain": "proton.me/pass",
    "category": "security-passwords",
    "tagline": "Open-source, encrypted password manager with email hide-my-alias protection",
    "description": "Proton Pass encrypts credentials, credit cards, and notes while generating email aliases to prevent tracking. It is tailored for privacy advocates and existing users of the Swiss Proton ecosystem.",
    "rating": 4.8,
    "reviewsCount": 1100,
    "pricing": "Freemium",
    "websiteUrl": "https://proton.me/pass",
    "affiliateUrl": "https://proton.me/pass",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "15.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "nordpass",
    "name": "NordPass",
    "domain": "nordpass.com",
    "category": "security-passwords",
    "tagline": "Intuitive, XChaCha20-encrypted password manager powered by Nord Security",
    "description": "NordPass simplifies secure credential saving with biometric unlocking, passkey support, and breach scanning. It serves individuals, small businesses, and enterprise teams seeking high-grade encryption.",
    "rating": 4.7,
    "reviewsCount": 1320,
    "pricing": "Freemium",
    "websiteUrl": "https://nordpass.com",
    "affiliateUrl": "https://nordpass.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "auth0",
    "name": "Auth0 by Okta",
    "domain": "auth0.com",
    "category": "security-passwords",
    "tagline": "Adaptable developer platform for authentication, authorization, and SSO",
    "description": "Auth0 provides developers with pre-built authentication services, user management, single sign-on, and multi-factor auth APIs. It is engineered for web and mobile application developers.",
    "rating": 4.7,
    "reviewsCount": 1950,
    "pricing": "Freemium",
    "websiteUrl": "https://auth0.com",
    "affiliateUrl": "https://auth0.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "6.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "okta",
    "name": "Okta",
    "domain": "okta.com",
    "category": "security-passwords",
    "tagline": "Enterprise identity management, single sign-on, and zero-trust security",
    "description": "Okta secures employee and customer access through cloud single sign-on, adaptive MFA, and lifecycle management. It is built for enterprise IT leaders managing corporate digital identities.",
    "rating": 4.6,
    "reviewsCount": 2700,
    "pricing": "Free Trial",
    "websiteUrl": "https://okta.com",
    "affiliateUrl": "https://okta.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "18.5M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "clerk",
    "name": "Clerk",
    "domain": "clerk.com",
    "category": "security-passwords",
    "tagline": "Complete user management and authentication suite for React and Next.js",
    "description": "Clerk provides pre-built UI components for user sign-ups, sign-ins, profile management, and passkey authentication. It is designed for modern frontend developers building web applications fast.",
    "rating": 4.9,
    "reviewsCount": 850,
    "pricing": "Freemium",
    "websiteUrl": "https://clerk.com",
    "affiliateUrl": "https://clerk.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "duo-security",
    "name": "Duo Security by Cisco",
    "domain": "duo.com",
    "category": "security-passwords",
    "tagline": "Multi-factor authentication and secure access verification",
    "description": "Duo verifies user identity and device health through seamless push notifications before granting network access. It is built for corporate IT admins implementing zero-trust security frameworks.",
    "rating": 4.7,
    "reviewsCount": 1820,
    "pricing": "Free Trial",
    "websiteUrl": "https://duo.com",
    "affiliateUrl": "https://duo.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.6M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "authy",
    "name": "Twilio Authy",
    "domain": "authy.com",
    "category": "security-passwords",
    "tagline": "Multi-device 2FA authenticator app for secure two-step verification",
    "description": "Authy generates secure two-factor authentication tokens with encrypted multi-device sync and cloud backup capabilities. It serves consumer accounts and security-conscious individuals.",
    "rating": 4.6,
    "reviewsCount": 1250,
    "pricing": "Free",
    "websiteUrl": "https://authy.com",
    "affiliateUrl": "https://authy.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "yubico",
    "name": "Yubico YubiKey",
    "domain": "yubico.com",
    "category": "security-passwords",
    "tagline": "Hardware authentication keys for unphishable two-factor authentication",
    "description": "Yubico manufactures physical USB/NFC keys implementing FIDO2 and WebAuthn standards for hardware-bound login defense. It is tailored for enterprises, developers, and high-risk targets.",
    "rating": 4.9,
    "reviewsCount": 3100,
    "pricing": "Paid",
    "websiteUrl": "https://yubico.com",
    "affiliateUrl": "https://yubico.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "3.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "mullvad-vpn",
    "name": "Mullvad VPN",
    "domain": "mullvad.net",
    "category": "security-passwords",
    "tagline": "Account-less, privacy-first VPN service with verifiable open-source apps",
    "description": "Mullvad VPN requires no personal details or email addresses to register, ensuring absolute online anonymity. It is engineered for privacy enthusiasts demanding transparent, audit-proven encryption.",
    "rating": 4.9,
    "reviewsCount": 2900,
    "pricing": "Paid",
    "websiteUrl": "https://mullvad.net",
    "affiliateUrl": "https://mullvad.net",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "4.1M",
    "isFreeTier": false,
    "isOpenSource": true
  },
  {
    "id": "proton-vpn",
    "name": "Proton VPN",
    "domain": "protonvpn.com",
    "category": "security-passwords",
    "tagline": "Swiss-based encrypted VPN with strict no-logs policy and free tier",
    "description": "Proton VPN routes web traffic through encrypted tunnels with Secure Core architecture to defend against network surveillance. It is designed for individuals prioritizing online privacy and data protection.",
    "rating": 4.8,
    "reviewsCount": 3800,
    "pricing": "Freemium",
    "websiteUrl": "https://protonvpn.com",
    "affiliateUrl": "https://protonvpn.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "12.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "nordvpn",
    "name": "NordVPN",
    "domain": "nordvpn.com",
    "category": "security-passwords",
    "tagline": "Fast, high-security private network and threat protection software",
    "description": "NordVPN offers high-speed encrypted internet connectivity alongside malware blocking and ad-filtering features. It serves general consumers and remote workers securing public Wi-Fi access.",
    "rating": 4.7,
    "reviewsCount": 8900,
    "pricing": "Paid",
    "websiteUrl": "https://nordvpn.com",
    "affiliateUrl": "https://nordvpn.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "28.5M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "tailscale",
    "name": "Tailscale",
    "domain": "tailscale.com",
    "category": "security-passwords",
    "tagline": "Zero-config mesh VPN built on WireGuard for secure private networks",
    "description": "Tailscale connects computers, servers, and cloud infrastructure directly together into an encrypted private mesh network. It is built for software developers, home lab creators, and IT operations.",
    "rating": 4.9,
    "reviewsCount": 1420,
    "pricing": "Freemium",
    "websiteUrl": "https://tailscale.com",
    "affiliateUrl": "https://tailscale.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "3.9M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "wireguard",
    "name": "WireGuard",
    "domain": "wireguard.com",
    "category": "security-passwords",
    "tagline": "Extremely simple, high-speed, and modern open-source VPN protocol",
    "description": "WireGuard uses state-of-the-art cryptography to deliver faster, leaner, and more secure VPN tunnels than IPsec or OpenVPN. It serves network engineers, developers, and privacy projects.",
    "rating": 4.9,
    "reviewsCount": 1150,
    "pricing": "Free",
    "websiteUrl": "https://wireguard.com",
    "affiliateUrl": "https://wireguard.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.6M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "keepassxc",
    "name": "KeePassXC",
    "domain": "keepassxc.org",
    "category": "security-passwords",
    "tagline": "Cross-platform open-source offline password manager database",
    "description": "KeePassXC stores credentials locally in AES-256 encrypted database files without relying on cloud services. It is engineered for security purists and offline desktop users.",
    "rating": 4.8,
    "reviewsCount": 1680,
    "pricing": "Free",
    "websiteUrl": "https://keepassxc.org",
    "affiliateUrl": "https://keepassxc.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "passbolt",
    "name": "Passbolt",
    "domain": "passbolt.com",
    "category": "security-passwords",
    "tagline": "Open-source, GPG-based password manager built for agile tech teams",
    "description": "Passbolt enables software teams to securely share, organize, and audit credential access using OpenPGP encryption. It is tailored for DevOps engineers and security-focused organizations.",
    "rating": 4.7,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://passbolt.com",
    "affiliateUrl": "https://passbolt.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "320K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "hashicorp-vault",
    "name": "HashiCorp Vault",
    "domain": "vaultproject.io",
    "category": "security-passwords",
    "tagline": "Enterprise secret management, API encryption, and access control framework",
    "description": "HashiCorp Vault secures, stores, and tightly controls access to tokens, passwords, certificates, and API keys across cloud infrastructure. It is built for DevOps engineers and cloud security architects.",
    "rating": 4.8,
    "reviewsCount": 1250,
    "pricing": "Freemium",
    "websiteUrl": "https://vaultproject.io",
    "affiliateUrl": "https://vaultproject.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.9M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "doppler",
    "name": "Doppler",
    "domain": "doppler.com",
    "category": "security-passwords",
    "tagline": "Centralized secret management platform for environment variables and API keys",
    "description": "Doppler syncs environment variables and API keys across development, staging, and production hosting environments. It is designed for software developers eliminating raw .env file sharing.",
    "rating": 4.9,
    "reviewsCount": 420,
    "pricing": "Freemium",
    "websiteUrl": "https://doppler.com",
    "affiliateUrl": "https://doppler.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "infisical",
    "name": "Infisical",
    "domain": "infisical.com",
    "category": "security-passwords",
    "tagline": "Open-source secret management platform for sync, auth, and environment keys",
    "description": "Infisical lets teams manage application secrets, API keys, and certificates securely across cloud providers. It serves engineering teams seeking open-source HashiCorp Vault alternatives.",
    "rating": 4.9,
    "reviewsCount": 310,
    "pricing": "Freemium",
    "websiteUrl": "https://infisical.com",
    "affiliateUrl": "https://infisical.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "390K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "keycloak",
    "name": "Keycloak",
    "domain": "keycloak.org",
    "category": "security-passwords",
    "tagline": "Open-source identity and access management system for modern web apps",
    "description": "Keycloak adds single sign-on, identity brokering, and user management capabilities with OpenID Connect support. It is designed for enterprise software architects requiring self-hosted IAM.",
    "rating": 4.7,
    "reviewsCount": 980,
    "pricing": "Free",
    "websiteUrl": "https://keycloak.org",
    "affiliateUrl": "https://keycloak.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.5M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "zitadel",
    "name": "ZITADEL",
    "domain": "zitadel.com",
    "category": "security-passwords",
    "tagline": "Open-source cloud-native identity management and passkey platform",
    "description": "ZITADEL provides passwordless authentication, multi-tenancy, and role-based access control APIs for software products. It serves developers building B2B SaaS apps requiring turnkey identity.",
    "rating": 4.8,
    "reviewsCount": 240,
    "pricing": "Freemium",
    "websiteUrl": "https://zitadel.com",
    "affiliateUrl": "https://zitadel.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "310K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "supertokens",
    "name": "SuperTokens",
    "domain": "supertokens.com",
    "category": "security-passwords",
    "tagline": "Open-source authentication solution alternative to Auth0 and Firebase Auth",
    "description": "SuperTokens provides pre-built signup flows, session management, and social logins that run within your infrastructure. It is engineered for developers wanting full control over auth data.",
    "rating": 4.8,
    "reviewsCount": 310,
    "pricing": "Freemium",
    "websiteUrl": "https://supertokens.com",
    "affiliateUrl": "https://supertokens.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "280K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "stytch",
    "name": "Stytch",
    "domain": "stytch.com",
    "category": "security-passwords",
    "tagline": "Developer-first passwordless authentication and fraud prevention platform",
    "description": "Stytch offers APIs and SDKs for magic links, passkeys, biometrics, and multi-factor auth integrations. It is built for product engineers modernizing application user onboarding.",
    "rating": 4.7,
    "reviewsCount": 190,
    "pricing": "Freemium",
    "websiteUrl": "https://stytch.com",
    "affiliateUrl": "https://stytch.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "240K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "passage-1password",
    "name": "Passage by 1Password",
    "domain": "passage.1password.com",
    "category": "security-passwords",
    "tagline": "Passkey-first authentication infrastructure for web and mobile developers",
    "description": "Passage replaces traditional passwords with native device biometrics like Touch ID and Face ID. It is built for developers wanting to embed WebAuthn passkey logins into applications.",
    "rating": 4.7,
    "reviewsCount": 140,
    "pricing": "Freemium",
    "websiteUrl": "https://passage.1password.com",
    "affiliateUrl": "https://passage.1password.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "180K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "descope",
    "name": "Descope",
    "domain": "descope.com",
    "category": "security-passwords",
    "tagline": "No-code customer authentication and user journey orchestration platform",
    "description": "Descope provides visual drag-and-drop workflows for user registration, passkey authentication, and SSO implementation. It serves product managers and developers streamlining security journeys.",
    "rating": 4.9,
    "reviewsCount": 160,
    "pricing": "Freemium",
    "websiteUrl": "https://descope.com",
    "affiliateUrl": "https://descope.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "220K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "expressvpn",
    "name": "ExpressVPN",
    "domain": "expressvpn.com",
    "category": "security-passwords",
    "tagline": "High-speed, encrypted private network for secure global internet access",
    "description": "ExpressVPN encrypts web traffic using modern Lightway protocols across thousands of global servers. It is built for non-technical consumers seeking fast streaming and safe public web access.",
    "rating": 4.6,
    "reviewsCount": 7800,
    "pricing": "Paid",
    "websiteUrl": "https://expressvpn.com",
    "affiliateUrl": "https://expressvpn.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "16.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "cloudflare-zero-trust",
    "name": "Cloudflare Zero Trust",
    "domain": "cloudflare.com/zero-trust",
    "category": "security-passwords",
    "tagline": "Zero-trust network access, secure web gateway, and DNS filtering",
    "description": "Cloudflare Zero Trust replaces legacy enterprise VPNs by verifying every request to internal applications. It is tailored for IT security administrators protecting distributed workforce teams.",
    "rating": 4.8,
    "reviewsCount": 1650,
    "pricing": "Freemium",
    "websiteUrl": "https://cloudflare.com/zero-trust",
    "affiliateUrl": "https://cloudflare.com/zero-trust",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "42.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "pomerium",
    "name": "Pomerium",
    "domain": "pomerium.com",
    "category": "security-passwords",
    "tagline": "Open-source identity-aware access proxy for zero-trust network access",
    "description": "Pomerium authenticates incoming requests to internal services based on user identity and context rules. It serves DevOps engineers replacing perimeter VPN setups with modern access proxies.",
    "rating": 4.7,
    "reviewsCount": 210,
    "pricing": "Freemium",
    "websiteUrl": "https://pomerium.com",
    "affiliateUrl": "https://pomerium.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "140K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "teleport",
    "name": "Teleport",
    "domain": "goteleport.com",
    "category": "security-passwords",
    "tagline": "Open-source identity-native infrastructure access platform",
    "description": "Teleport provides consolidated zero-trust access to SSH servers, Kubernetes clusters, databases, and web apps. It is engineered for infrastructure engineers securing multi-cloud operations.",
    "rating": 4.8,
    "reviewsCount": 540,
    "pricing": "Freemium",
    "websiteUrl": "https://goteleport.com",
    "affiliateUrl": "https://goteleport.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "580K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "boundary-hashicorp",
    "name": "HashiCorp Boundary",
    "domain": "boundaryproject.io",
    "category": "security-passwords",
    "tagline": "Identity-based infrastructure access management for privileged users",
    "description": "Boundary enables fine-grained privileged access to hosts and services without exposing underlying networks. It serves enterprise security operators managing dynamic developer credentials.",
    "rating": 4.6,
    "reviewsCount": 280,
    "pricing": "Freemium",
    "websiteUrl": "https://boundaryproject.io",
    "affiliateUrl": "https://boundaryproject.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "210K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "openvpn",
    "name": "OpenVPN",
    "domain": "openvpn.net",
    "category": "security-passwords",
    "tagline": "Full-featured open-source SSL VPN software for secure remote connectivity",
    "description": "OpenVPN creates encrypted point-to-point site connections to secure remote workforce data transmission. It is an industry mainstay for network admins and IT infrastructure teams.",
    "rating": 4.5,
    "reviewsCount": 2300,
    "pricing": "Freemium",
    "websiteUrl": "https://openvpn.net",
    "affiliateUrl": "https://openvpn.net",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "pivpn",
    "name": "PiVPN",
    "domain": "pivpn.io",
    "category": "security-passwords",
    "tagline": "Lightweight open-source script to turn a Raspberry Pi into a WireGuard VPN",
    "description": "PiVPN simplifies configuring a dedicated WireGuard or OpenVPN server on low-power devices. It is popular among home lab builders and self-hosters securing local network access.",
    "rating": 4.9,
    "reviewsCount": 680,
    "pricing": "Free",
    "websiteUrl": "https://pivpn.io",
    "affiliateUrl": "https://pivpn.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "310K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "netmaker",
    "name": "Netmaker",
    "domain": "netmaker.io",
    "category": "security-passwords",
    "tagline": "Automated open-source WireGuard virtual networking software",
    "description": "Netmaker automates creating fast, multi-cloud WireGuard mesh networks across distributed servers and devices. It is built for DevOps engineers connecting cloud infrastructure directly.",
    "rating": 4.7,
    "reviewsCount": 190,
    "pricing": "Freemium",
    "websiteUrl": "https://netmaker.io",
    "affiliateUrl": "https://netmaker.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "150K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "shadowsocks",
    "name": "Shadowsocks",
    "domain": "shadowsocks.org",
    "category": "security-passwords",
    "tagline": "Open-source secure SOCKS5 proxy designed to bypass internet censorship",
    "description": "Shadowsocks encrypts internet traffic to look like standard HTTPS connections, bypassing strict firewall filtering. It serves privacy seekers navigating heavily restricted networks.",
    "rating": 4.8,
    "reviewsCount": 1400,
    "pricing": "Free",
    "websiteUrl": "https://shadowsocks.org",
    "affiliateUrl": "https://shadowsocks.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "890K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "privoxy",
    "name": "Privoxy",
    "domain": "privoxy.org",
    "category": "security-passwords",
    "tagline": "Non-caching web proxy with advanced privacy filtering and ad blocking",
    "description": "Privoxy filters web page data, removes ads, and modifies HTTP headers to protect user privacy online. It is designed for privacy advocates configuring customized web browser proxies.",
    "rating": 4.5,
    "reviewsCount": 310,
    "pricing": "Free",
    "websiteUrl": "https://privoxy.org",
    "affiliateUrl": "https://privoxy.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "240K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "roboform",
    "name": "RoboForm",
    "domain": "roboform.com",
    "category": "security-passwords",
    "tagline": "Automated web form filler and password vault software",
    "description": "RoboForm specializes in one-click complex web form filling, password generation, and secure vault storage. It serves personal users and businesses looking to accelerate manual form entry.",
    "rating": 4.5,
    "reviewsCount": 1100,
    "pricing": "Freemium",
    "websiteUrl": "https://roboform.com",
    "affiliateUrl": "https://roboform.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "enpass",
    "name": "Enpass",
    "domain": "enpass.io",
    "category": "security-passwords",
    "tagline": "Offline-first password manager with user-selected cloud backup sync",
    "description": "Enpass stores encrypted password vaults locally or syncs them using personal cloud drives like iCloud or WebDAV. It is built for security-conscious users avoiding centralized vendor cloud storage.",
    "rating": 4.6,
    "reviewsCount": 620,
    "pricing": "Freemium",
    "websiteUrl": "https://enpass.io",
    "affiliateUrl": "https://enpass.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "510K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "cyberghost-vpn",
    "name": "CyberGhost VPN",
    "domain": "cyberghostvpn.com",
    "category": "security-passwords",
    "tagline": "User-friendly privacy VPN with dedicated servers for streaming and gaming",
    "description": "CyberGhost hides IP addresses and encrypts online traffic with pre-configured profile connections. It is targeted at everyday internet users securing public Wi-Fi or accessing global media.",
    "rating": 4.4,
    "reviewsCount": 4200,
    "pricing": "Paid",
    "websiteUrl": "https://cyberghostvpn.com",
    "affiliateUrl": "https://cyberghostvpn.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "5.6M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "surfshark",
    "name": "Surfshark",
    "domain": "surfshark.com",
    "category": "security-passwords",
    "tagline": "All-in-one privacy suite offering unlimited device VPN connections",
    "description": "Surfshark provides encrypted web browsing, ad blocking, and identity leak alerts across unlimited household devices. It serves privacy-conscious families and multi-device owners.",
    "rating": 4.6,
    "reviewsCount": 5100,
    "pricing": "Paid",
    "websiteUrl": "https://surfshark.com",
    "affiliateUrl": "https://surfshark.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "11.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "windscribe",
    "name": "Windscribe",
    "domain": "windscribe.com",
    "category": "security-passwords",
    "tagline": "VPN and desktop ad-blocker defending online privacy with generous free data",
    "description": "Windscribe blocks ads, trackers, and network snooping while spoofing geographic locations securely. It is popular among students and casual users taking advantage of high free bandwidth tiers.",
    "rating": 4.6,
    "reviewsCount": 2300,
    "pricing": "Freemium",
    "websiteUrl": "https://windscribe.com",
    "affiliateUrl": "https://windscribe.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "authenticator-app",
    "name": "Microsoft Authenticator",
    "domain": "microsoft.com/security/mobile-authenticator-app",
    "category": "security-passwords",
    "tagline": "Secure two-factor authentication and passwordless phone sign-in app",
    "description": "Microsoft Authenticator approves login pushes, generates 2FA codes, and enables passwordless account access. It is optimized for enterprise employees and personal Microsoft account holders.",
    "rating": 4.7,
    "reviewsCount": 6100,
    "pricing": "Free",
    "websiteUrl": "https://microsoft.com/security/mobile-authenticator-app",
    "affiliateUrl": "https://microsoft.com/security/mobile-authenticator-app",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "22.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "google-authenticator",
    "name": "Google Authenticator",
    "domain": "google.com",
    "category": "security-passwords",
    "tagline": "Lightweight time-based one-time password (TOTP) generator",
    "description": "Google Authenticator generates 6-digit TOTP verification codes for two-step verification across online accounts. It is built for everyday users adding two-factor security layers.",
    "rating": 4.5,
    "reviewsCount": 8200,
    "pricing": "Free",
    "websiteUrl": "https://google.com",
    "affiliateUrl": "https://google.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "85.0M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "spherical-cyberark",
    "name": "CyberArk Privilege Cloud",
    "domain": "cyberark.com",
    "category": "security-passwords",
    "tagline": "Privileged access management and enterprise identity defense",
    "description": "CyberArk protects, controls, and monitors privileged human and machine credentials across enterprise environments. It serves enterprise CISOs and IT compliance directors.",
    "rating": 4.6,
    "reviewsCount": 890,
    "pricing": "Paid",
    "websiteUrl": "https://cyberark.com",
    "affiliateUrl": "https://cyberark.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "ping-identity",
    "name": "Ping Identity",
    "domain": "pingidentity.com",
    "category": "security-passwords",
    "tagline": "Enterprise orchestration, single sign-on, and smart identity management",
    "description": "Ping Identity coordinates zero-trust authentication, multi-factor verification, and identity governance for workforce users. It is built for Global 2000 enterprise security architects.",
    "rating": 4.5,
    "reviewsCount": 940,
    "pricing": "Free Trial",
    "websiteUrl": "https://pingidentity.com",
    "affiliateUrl": "https://pingidentity.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.6M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "beyondtrust",
    "name": "BeyondTrust Privileged Access",
    "domain": "beyondtrust.com",
    "category": "security-passwords",
    "tagline": "Privileged remote access, password vaulting, and threat protection",
    "description": "BeyondTrust secures admin credentials, restricts excessive user privileges, and audits remote support sessions. It is engineered for enterprise IT risk and compliance teams.",
    "rating": 4.5,
    "reviewsCount": 780,
    "pricing": "Paid",
    "websiteUrl": "https://beyondtrust.com",
    "affiliateUrl": "https://beyondtrust.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "920K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "buttercup",
    "name": "Buttercup",
    "domain": "buttercup.pw",
    "category": "security-passwords",
    "tagline": "Free, open-source NodeJS-powered password manager for desktop and mobile",
    "description": "Buttercup stores encrypted credentials in custom vault files hosted locally or on personal cloud drives. It serves privacy enthusiasts wanting open-source desktop and mobile password management.",
    "rating": 4.6,
    "reviewsCount": 180,
    "pricing": "Free",
    "websiteUrl": "https://buttercup.pw",
    "affiliateUrl": "https://buttercup.pw",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "95K",
    "isFreeTier": true,
    "isOpenSource": true
  }
];

const saasDataPath = path.join(__dirname, '..', 'src', 'data', 'saasData.jsx');
let content = fs.readFileSync(saasDataPath, 'utf8');

const match = content.match(/export const staticSaasTools = (\[[\s\S]*?\n\]);/);
if (!match) {
  console.error('Could not find staticSaasTools in saasData.jsx');
  process.exit(1);
}

let existingTools = JSON.parse(match[1]);

const existingIds = new Set(existingTools.map(t => t.id.toLowerCase()));
const existingNames = new Set(existingTools.map(t => t.name.toLowerCase()));

let addedCount = 0;
let skippedCount = 0;

newTools.forEach(tool => {
  const normId = tool.id.toLowerCase();
  const normName = tool.name.toLowerCase();

  if (!existingIds.has(normId) && !existingNames.has(normName)) {
    existingTools.push(tool);
    existingIds.add(normId);
    existingNames.add(normName);
    addedCount++;
  } else {
    // Enrich existing tool without creating a duplicate
    const idx = existingTools.findIndex(t => t.id.toLowerCase() === normId || t.name.toLowerCase() === normName);
    if (idx !== -1) {
      existingTools[idx] = { ...existingTools[idx], category: tool.category, tagline: tool.tagline || existingTools[idx].tagline };
    }
    skippedCount++;
  }
});

const updatedArrayStr = JSON.stringify(existingTools, null, 2);
content = content.replace(/export const staticSaasTools = \[[\s\S]*?\n\];/, `export const staticSaasTools = ${updatedArrayStr};`);

fs.writeFileSync(saasDataPath, content, 'utf8');
console.log(`Ingestion Complete! Added: ${addedCount} brand new tools | Deduplicated: ${skippedCount} existing tools | Total static tools: ${existingTools.length}`);
