const fs = require('fs');
const path = require('path');

const newTools = [
  {
    "id": "crowdstrike-falcon",
    "name": "CrowdStrike Falcon",
    "domain": "crowdstrike.com",
    "category": "security-identity",
    "tagline": "AI-native cloud unified endpoint, identity, and threat protection platform",
    "description": "CrowdStrike Falcon unifies endpoint detection and response (EDR), identity threat detection (ITDR), and cloud workload defense into a single lightweight agent. It is engineered for enterprise security operations centers (SOC) stopping breaches in real time.",
    "rating": 4.8,
    "reviewsCount": 2450,
    "pricing": "Free Trial",
    "websiteUrl": "https://crowdstrike.com",
    "affiliateUrl": "https://crowdstrike.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "4.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "twingate",
    "name": "Twingate",
    "domain": "twingate.com",
    "category": "security-identity",
    "tagline": "Modern Zero Trust Network Access (ZTNA) platform replacing business VPNs",
    "description": "Twingate provides least-privilege network access to private resources across cloud, on-premise, and multi-cloud environments without exposing IP addresses. It is built for IT admins and DevOps teams securing distributed workforces.",
    "rating": 4.9,
    "reviewsCount": 680,
    "pricing": "Freemium",
    "websiteUrl": "https://twingate.com",
    "affiliateUrl": "https://twingate.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "wiz-cloud",
    "name": "Wiz",
    "domain": "wiz.io",
    "category": "security-identity",
    "tagline": "Agentless cloud security posture management and identity exposure graph",
    "description": "Wiz scans cloud infrastructure agentlessly to map risk graphs across misconfigurations, vulnerabilities, and overly permissive IAM roles. It serves cloud security architects and DevOps leads across AWS, Azure, and GCP.",
    "rating": 4.9,
    "reviewsCount": 850,
    "pricing": "Free Trial",
    "websiteUrl": "https://wiz.io",
    "affiliateUrl": "https://wiz.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "2.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "snyk-sec",
    "name": "Snyk",
    "domain": "snyk.io",
    "category": "security-identity",
    "tagline": "Developer-first application security platform for code, dependencies, and containers",
    "description": "Snyk scans code repositories, open-source dependencies, and container images directly inside developer IDEs and CI/CD pipelines. It is engineered for software developers and DevSecOps teams.",
    "rating": 4.7,
    "reviewsCount": 1820,
    "pricing": "Freemium",
    "websiteUrl": "https://snyk.io",
    "affiliateUrl": "https://snyk.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "3.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "tailscale-ztna",
    "name": "Tailscale",
    "domain": "tailscale.com",
    "category": "security-identity",
    "tagline": "Zero-config mesh WireGuard VPN providing identity-aware private access",
    "description": "Tailscale builds encrypted peer-to-peer mesh networks authenticated via your team's existing Identity Provider (SSO). It serves developers, homelabs, and IT teams connecting infrastructure securely.",
    "rating": 4.9,
    "reviewsCount": 1420,
    "pricing": "Freemium",
    "websiteUrl": "https://tailscale.com",
    "affiliateUrl": "https://tailscale.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "3.9M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "zscaler-private-access",
    "name": "Zscaler",
    "domain": "zscaler.com",
    "category": "security-identity",
    "tagline": "Enterprise cloud security platform delivering Zero Trust Exchange and ZTNA",
    "description": "Zscaler securely connects users directly to applications without placing them on the corporate network, eliminating lateral threat movement. It is tailored for global enterprise CISOs and IT directors.",
    "rating": 4.6,
    "reviewsCount": 1950,
    "pricing": "Paid",
    "websiteUrl": "https://zscaler.com",
    "affiliateUrl": "https://zscaler.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "5.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "smallstep",
    "name": "Smallstep",
    "domain": "smallstep.com",
    "category": "security-identity",
    "tagline": "Automated internal Public Key Infrastructure (PKI) and X.509 certificate management",
    "description": "Smallstep automates TLS certificate issuing, SSH key rotation, and device identity verification across DevOps pipelines. It serves infrastructure security leads, SREs, and DevOps engineers.",
    "rating": 4.8,
    "reviewsCount": 310,
    "pricing": "Freemium",
    "websiteUrl": "https://smallstep.com",
    "affiliateUrl": "https://smallstep.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "sentinelone",
    "name": "SentinelOne Singularity",
    "domain": "sentinelone.com",
    "category": "security-identity",
    "tagline": "Autonomous AI-powered endpoint, identity, and cloud runtime defense",
    "description": "SentinelOne combines endpoint protection (EPP), EDR, and identity security with automated machine-speed incident response. It is built for enterprise SOC teams and managed security providers.",
    "rating": 4.7,
    "reviewsCount": 2100,
    "pricing": "Free Trial",
    "websiteUrl": "https://sentinelone.com",
    "affiliateUrl": "https://sentinelone.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "jumpcloud",
    "name": "JumpCloud",
    "domain": "jumpcloud.com",
    "category": "security-identity",
    "tagline": "Cloud directory platform unifying identity, device management, and SSO",
    "description": "JumpCloud replaces legacy Active Directory by combining cloud IAM, device management (MDM), and passwordless authentication. It serves IT admins managing heterogeneous OS fleets across remote teams.",
    "rating": 4.6,
    "reviewsCount": 1650,
    "pricing": "Freemium",
    "websiteUrl": "https://jumpcloud.com",
    "affiliateUrl": "https://jumpcloud.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "strongdm",
    "name": "strongDM",
    "domain": "strongdm.com",
    "category": "security-identity",
    "tagline": "Zero Trust infrastructure access platform managing databases, SSH, and Kubernetes",
    "description": "strongDM manages privileged access to infrastructure nodes while auditing every database query and terminal command. It is engineered for DevOps leads, SREs, and compliance officers.",
    "rating": 4.8,
    "reviewsCount": 290,
    "pricing": "Free Trial",
    "websiteUrl": "https://strongdm.com",
    "affiliateUrl": "https://strongdm.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "340K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "keeper-secrets-manager",
    "name": "Keeper Secrets Manager",
    "domain": "keepersecurity.com/secrets-manager.html",
    "category": "security-identity",
    "tagline": "Zero-knowledge, zero-trust cloud secret management for API keys and CI/CD",
    "description": "Keeper Secrets Manager secures API keys, database credentials, and certificates across cloud infrastructure without hardcoded tokens. It is tailored for enterprise IT and DevOps engineering teams.",
    "rating": 4.7,
    "reviewsCount": 420,
    "pricing": "Free Trial",
    "websiteUrl": "https://keepersecurity.com/secrets-manager.html",
    "affiliateUrl": "https://keepersecurity.com/secrets-manager.html",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.9M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "perimeter81",
    "name": "Perimeter 81 (Check Point)",
    "domain": "perimeter81.com",
    "category": "security-identity",
    "tagline": "Converged Network as a Service (SSE) delivering Zero Trust network protection",
    "description": "Perimeter 81 unifies cloud firewalls, Zero Trust Network Access, and secure web gateways into a cloud-native console. It serves IT managers replacing hardware firewalls and legacy VPNs.",
    "rating": 4.6,
    "reviewsCount": 890,
    "pricing": "Paid",
    "websiteUrl": "https://perimeter81.com",
    "affiliateUrl": "https://perimeter81.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "pomerium-proxy",
    "name": "Pomerium",
    "domain": "pomerium.com",
    "category": "security-identity",
    "tagline": "Open-source identity-aware access proxy for zero-trust application enforcement",
    "description": "Pomerium validates identity and context rules on incoming HTTP/HTTPS traffic to internal applications in real time. It is built for DevOps engineers replacing legacy perimeter networks.",
    "rating": 4.7,
    "reviewsCount": 210,
    "pricing": "Freemium",
    "websiteUrl": "https://pomerium.com",
    "affiliateUrl": "https://pomerium.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "140K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "teleport-access",
    "name": "Teleport",
    "domain": "goteleport.com",
    "category": "security-identity",
    "tagline": "Open-source identity-native infrastructure access platform for SSH and K8s",
    "description": "Teleport eliminates static SSH keys and passwords by providing certificate-based access to servers, Kubernetes, and web apps. It is designed for infrastructure engineers and SREs.",
    "rating": 4.8,
    "reviewsCount": 540,
    "pricing": "Freemium",
    "websiteUrl": "https://goteleport.com",
    "affiliateUrl": "https://goteleport.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "580K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "doppler-secrets",
    "name": "Doppler",
    "domain": "doppler.com",
    "category": "security-identity",
    "tagline": "Universal secret ops platform for centralizing API keys and environment variables",
    "description": "Doppler synchronizes secrets and environment variables securely across local dev, GitHub Actions, Vercel, and AWS. It serves modern developers and DevOps engineers ending .env file sprawl.",
    "rating": 4.9,
    "reviewsCount": 420,
    "pricing": "Freemium",
    "websiteUrl": "https://doppler.com",
    "affiliateUrl": "https://doppler.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "infisical-secrets",
    "name": "Infisical",
    "domain": "infisical.com",
    "category": "security-identity",
    "tagline": "Open-source secret management platform for syncing environment variables and certificates",
    "description": "Infisical provides end-to-end encrypted secret storage with native CLI, SDKs, and Kubernetes operator integrations. It is engineered for software developers and cloud engineers seeking open-source Vault alternatives.",
    "rating": 4.9,
    "reviewsCount": 310,
    "pricing": "Freemium",
    "websiteUrl": "https://infisical.com",
    "affiliateUrl": "https://infisical.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "390K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "keycloak-iam",
    "name": "Keycloak",
    "domain": "keycloak.org",
    "category": "security-identity",
    "tagline": "Open-source identity and access management system with OAuth2 and SAML",
    "description": "Keycloak offers self-hosted single sign-on, social login brokers, and LDAP user synchronization for custom web applications. It serves software architects and open-source advocates.",
    "rating": 4.7,
    "reviewsCount": 980,
    "pricing": "Free",
    "websiteUrl": "https://keycloak.org",
    "affiliateUrl": "https://keycloak.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.5M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "passbolt-vault",
    "name": "Passbolt",
    "domain": "passbolt.com",
    "category": "security-identity",
    "tagline": "Open-source GPG-based password manager engineered for agile software teams",
    "description": "Passbolt allows technical teams to store, share, and audit credential access using OpenPGP encryption standards. It is tailored for DevOps engineers, sysadmins, and security-minded organizations.",
    "rating": 4.7,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://passbolt.com",
    "affiliateUrl": "https://passbolt.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "320K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "zitadel-id",
    "name": "ZITADEL",
    "domain": "zitadel.com",
    "category": "security-identity",
    "tagline": "Open-source cloud-native identity platform with turnkey passkeys and multi-tenancy",
    "description": "ZITADEL provides passwordless logins, audit logs, and B2B SaaS organization management through clean REST APIs. It is built for developers constructing multi-tenant SaaS products.",
    "rating": 4.8,
    "reviewsCount": 240,
    "pricing": "Freemium",
    "websiteUrl": "https://zitadel.com",
    "affiliateUrl": "https://zitadel.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "310K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "descope-auth",
    "name": "Descope",
    "domain": "descope.com",
    "category": "security-identity",
    "tagline": "No-code user journey orchestration and drag-and-drop authentication platform",
    "description": "Descope provides visual workflows for embedding passkeys, MFA, and SSO into web applications with zero code complexity. It serves product managers and software engineers modernizing app sign-ups.",
    "rating": 4.9,
    "reviewsCount": 160,
    "pricing": "Freemium",
    "websiteUrl": "https://descope.com",
    "affiliateUrl": "https://descope.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "220K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "supertokens-auth",
    "name": "SuperTokens",
    "domain": "supertokens.com",
    "category": "security-identity",
    "tagline": "Open-source developer authentication alternative to Auth0 and Firebase",
    "description": "SuperTokens offers self-hostable user session management, social sign-ins, and passwordless authentication widgets. It is built for developers demanding total control over user credential data.",
    "rating": 4.8,
    "reviewsCount": 310,
    "pricing": "Freemium",
    "websiteUrl": "https://supertokens.com",
    "affiliateUrl": "https://supertokens.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "280K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "stytch-auth",
    "name": "Stytch",
    "domain": "stytch.com",
    "category": "security-identity",
    "tagline": "Developer-first API suite for passkeys, magic links, and fraud prevention",
    "description": "Stytch delivers flexible SDKs to build passwordless authentication flows and device fingerprinting into modern apps. It is tailored for product development teams improving user conversion.",
    "rating": 4.7,
    "reviewsCount": 190,
    "pricing": "Freemium",
    "websiteUrl": "https://stytch.com",
    "affiliateUrl": "https://stytch.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "240K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "authentik-idp",
    "name": "authentik",
    "domain": "goauthentik.io",
    "category": "security-identity",
    "tagline": "Open-source Identity Provider focused on versatile SSO and application proxies",
    "description": "authentik provides self-hosted single sign-on, WebAuthn MFA, and LDAP integration across private web apps. It serves homelab managers and corporate IT administrators.",
    "rating": 4.9,
    "reviewsCount": 620,
    "pricing": "Free",
    "websiteUrl": "https://goauthentik.io",
    "affiliateUrl": "https://goauthentik.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "850K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "authelia-auth",
    "name": "Authelia",
    "domain": "authelia.com",
    "category": "security-identity",
    "tagline": "Lightweight open-source 2FA and single sign-on authentication portal",
    "description": "Authelia acts as a reverse proxy authentication portal adding multi-factor protection to internal server applications. It is engineered for self-hosters securing private server endpoints.",
    "rating": 4.8,
    "reviewsCount": 540,
    "pricing": "Free",
    "websiteUrl": "https://authelia.com",
    "affiliateUrl": "https://authelia.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "yubico-keys",
    "name": "Yubico YubiKey",
    "domain": "yubico.com",
    "category": "security-identity",
    "tagline": "Hardware authentication keys delivering unphishable FIDO2 security",
    "description": "Yubico manufactures physical security keys providing hardware-backed WebAuthn authentication against credential theft. It serves enterprise IT staff, software developers, and high-risk targets.",
    "rating": 4.9,
    "reviewsCount": 3100,
    "pricing": "Paid",
    "websiteUrl": "https://yubico.com",
    "affiliateUrl": "https://yubico.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "mullvad-privacy",
    "name": "Mullvad VPN",
    "domain": "mullvad.net",
    "category": "security-identity",
    "tagline": "Account-less, privacy-first VPN with audited open-source desktop clients",
    "description": "Mullvad VPN requires no personal details to register, maintaining complete online user anonymity over WireGuard tunnels. It is engineered for privacy purists and security researchers.",
    "rating": 4.9,
    "reviewsCount": 2900,
    "pricing": "Paid",
    "websiteUrl": "https://mullvad.net",
    "affiliateUrl": "https://mullvad.net",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.1M",
    "isFreeTier": false,
    "isOpenSource": true
  },
  {
    "id": "varonis-data",
    "name": "Varonis",
    "domain": "varonis.com",
    "category": "security-identity",
    "tagline": "Automated data security posture management and identity access governance",
    "description": "Varonis continuously maps sensitive data permissions and detects anomalous insider threats across cloud stores. It serves enterprise CISOs and data governance directors.",
    "rating": 4.6,
    "reviewsCount": 680,
    "pricing": "Paid",
    "websiteUrl": "https://varonis.com",
    "affiliateUrl": "https://varonis.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "ping-identity-suite",
    "name": "Ping Identity",
    "domain": "pingidentity.com",
    "category": "security-identity",
    "tagline": "Enterprise identity orchestration, intelligent single sign-on, and MFA",
    "description": "Ping Identity orchestrates zero-trust access, customer identity (CIAM), and multi-factor authentication for Global 2000 firms. It is built for enterprise security leads.",
    "rating": 4.5,
    "reviewsCount": 940,
    "pricing": "Free Trial",
    "websiteUrl": "https://pingidentity.com",
    "affiliateUrl": "https://pingidentity.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.6M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "beyondtrust-pam",
    "name": "BeyondTrust Privileged Access",
    "domain": "beyondtrust.com",
    "category": "security-identity",
    "tagline": "Privileged access management, credential vaulting, and remote session auditing",
    "description": "BeyondTrust secures admin passwords, limits excessive user permissions, and records remote maintenance sessions. It is engineered for enterprise IT risk and compliance auditors.",
    "rating": 4.5,
    "reviewsCount": 780,
    "pricing": "Paid",
    "websiteUrl": "https://beyondtrust.com",
    "affiliateUrl": "https://beyondtrust.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "920K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "cyberark-cloud",
    "name": "CyberArk Privilege Cloud",
    "domain": "cyberark.com",
    "category": "security-identity",
    "tagline": "Enterprise privileged account management and machine identity defense",
    "description": "CyberArk protects and audits high-risk administrative credentials across on-premise and multi-cloud environments. It is built for corporate CISOs and IAM architects.",
    "rating": 4.6,
    "reviewsCount": 890,
    "pricing": "Paid",
    "websiteUrl": "https://cyberark.com",
    "affiliateUrl": "https://cyberark.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "semperis-directory",
    "name": "Semperis",
    "domain": "semperis.com",
    "category": "security-identity",
    "tagline": "Identity-driven cyber resilience and automated Active Directory recovery",
    "description": "Semperis detects Active Directory misconfigurations and provides automated rollback during active ransomware attacks. It serves enterprise IT security teams maintaining AD infrastructure.",
    "rating": 4.8,
    "reviewsCount": 180,
    "pricing": "Paid",
    "websiteUrl": "https://semperis.com",
    "affiliateUrl": "https://semperis.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "210K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "sailpoint-identity",
    "name": "SailPoint Identity Security",
    "domain": "sailpoint.com",
    "category": "security-identity",
    "tagline": "AI-driven enterprise identity governance and lifecycle management",
    "description": "SailPoint automates employee access provisioning, role certifications, and compliance tracking across enterprise applications. It serves enterprise IAM directors and compliance auditors.",
    "rating": 4.4,
    "reviewsCount": 850,
    "pricing": "Paid",
    "websiteUrl": "https://sailpoint.com",
    "affiliateUrl": "https://sailpoint.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "saviynt-governance",
    "name": "Saviynt",
    "domain": "saviynt.com",
    "category": "security-identity",
    "tagline": "Cloud-native identity governance and privileged access management (IGAM)",
    "description": "Saviynt unifies user lifecycle management, cloud PAM, and application risk analytics into a single platform. It is built for enterprise risk management officers.",
    "rating": 4.5,
    "reviewsCount": 320,
    "pricing": "Paid",
    "websiteUrl": "https://saviynt.com",
    "affiliateUrl": "https://saviynt.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "bitwarden-enterprise",
    "name": "Bitwarden Secrets Manager",
    "domain": "bitwarden.com/products/secrets-manager",
    "category": "security-identity",
    "tagline": "Open-source developer secret management for API keys and tokens",
    "description": "Bitwarden Secrets Manager centralizes machine credentials, environment variables, and API keys across dev teams. It is built for open-source teams and software engineers.",
    "rating": 4.8,
    "reviewsCount": 510,
    "pricing": "Freemium",
    "websiteUrl": "https://bitwarden.com/products/secrets-manager",
    "affiliateUrl": "https://bitwarden.com/products/secrets-manager",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "11.5M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "tailscale-funnel",
    "name": "Tailscale SSH",
    "domain": "tailscale.com/use-cases/ssh",
    "category": "security-identity",
    "tagline": "Zero-trust SSH access management using OpenID Connect authentication",
    "description": "Tailscale SSH authenticates server terminal sessions via user Identity Providers without managing static SSH keys. It is built for DevOps engineers and SREs.",
    "rating": 4.9,
    "reviewsCount": 420,
    "pricing": "Freemium",
    "websiteUrl": "https://tailscale.com/use-cases/ssh",
    "affiliateUrl": "https://tailscale.com/use-cases/ssh",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.9M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "boundary-access",
    "name": "HashiCorp Boundary",
    "domain": "boundaryproject.io",
    "category": "security-identity",
    "tagline": "Identity-based infrastructure access management for privileged endpoints",
    "description": "Boundary grants dynamic access to target hosts and databases based on user identity without exposing private networks. It serves enterprise DevOps leads and security administrators.",
    "rating": 4.6,
    "reviewsCount": 280,
    "pricing": "Freemium",
    "websiteUrl": "https://boundaryproject.io",
    "affiliateUrl": "https://boundaryproject.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "210K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "axonius-asset",
    "name": "Axonius",
    "domain": "axonius.com",
    "category": "security-identity",
    "tagline": "Cybersecurity asset management and SaaS management platform",
    "description": "Axonius correlates asset inventories across devices, users, and cloud instances to surface security coverage gaps. It is engineered for enterprise CISOs and IT asset leads.",
    "rating": 4.7,
    "reviewsCount": 310,
    "pricing": "Paid",
    "websiteUrl": "https://axonius.com",
    "affiliateUrl": "https://axonius.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "420K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "runpanther-siem",
    "name": "Panther",
    "domain": "panther.com",
    "category": "security-identity",
    "tagline": "Cloud-native SIEM and security analytics powered by Python and Snowflake",
    "description": "Panther detects security threats in real time by analyzing high-volume log data using Python detection code. It serves security engineers and modern SOC teams.",
    "rating": 4.8,
    "reviewsCount": 190,
    "pricing": "Paid",
    "websiteUrl": "https://panther.com",
    "affiliateUrl": "https://panther.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "280K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "orca-security",
    "name": "Orca Security",
    "domain": "orca.security",
    "category": "security-identity",
    "tagline": "Agentless cloud security platform providing 100% deep visibility",
    "description": "Orca Security scans cloud workloads without agents to identify malware, misconfigurations, and vulnerable secrets. It is built for enterprise cloud security engineers.",
    "rating": 4.8,
    "reviewsCount": 380,
    "pricing": "Free Trial",
    "websiteUrl": "https://orca.security",
    "affiliateUrl": "https://orca.security",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "580K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "lacework-cloud",
    "name": "Lacework",
    "domain": "lacework.com",
    "category": "security-identity",
    "tagline": "Data-driven cloud security platform for threat detection and posture management",
    "description": "Lacework analyzes cloud activity changes automatically to surface unusual behavioral anomalies across containers and IAM. It serves cloud-native enterprise security operations.",
    "rating": 4.5,
    "reviewsCount": 410,
    "pricing": "Paid",
    "websiteUrl": "https://lacework.com",
    "affiliateUrl": "https://lacework.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "noname-security",
    "name": "Noname Security",
    "domain": "nonamesecurity.com",
    "category": "security-identity",
    "tagline": "Complete API security platform for discovery, testing, and posture defense",
    "description": "Noname Security detects rogue APIs, identifies misconfigured authentication, and blocks runtime API attacks. It is designed for enterprise AppSec and API architects.",
    "rating": 4.8,
    "reviewsCount": 160,
    "pricing": "Paid",
    "websiteUrl": "https://nonamesecurity.com",
    "affiliateUrl": "https://nonamesecurity.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "240K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "salt-security",
    "name": "Salt Security",
    "domain": "salt.security",
    "category": "security-identity",
    "tagline": "API security platform using big data AI to block API business logic attacks",
    "description": "Salt Security monitors API traffic to discover hidden endpoints and prevent unauthorized data exfiltration. It serves enterprise AppSec leads and software engineering teams.",
    "rating": 4.7,
    "reviewsCount": 210,
    "pricing": "Paid",
    "websiteUrl": "https://salt.security",
    "affiliateUrl": "https://salt.security",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "310K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "wiz-ciem",
    "name": "Wiz CIEM",
    "domain": "wiz.io/solutions/ciem",
    "category": "security-identity",
    "tagline": "Cloud Infrastructure Entitlement Management for rightsizing cloud IAM permissions",
    "description": "Wiz CIEM analyzes cloud permissions automatically to enforce least-privilege policies across multi-cloud accounts. It is built for cloud security teams and IAM administrators.",
    "rating": 4.9,
    "reviewsCount": 310,
    "pricing": "Free Trial",
    "websiteUrl": "https://wiz.io/solutions/ciem",
    "affiliateUrl": "https://wiz.io/solutions/ciem",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "gitguardian-secrets",
    "name": "GitGuardian",
    "domain": "gitguardian.com",
    "category": "security-identity",
    "tagline": "Automated secret detection engine preventing API key leaks in code repositories",
    "description": "GitGuardian scans commit histories and developer repositories in real time to catch leaked API keys and tokens. It serves DevSecOps teams and software engineering leads.",
    "rating": 4.8,
    "reviewsCount": 490,
    "pricing": "Freemium",
    "websiteUrl": "https://gitguardian.com",
    "affiliateUrl": "https://gitguardian.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "820K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "trufflehog-sec",
    "name": "TruffleHog",
    "domain": "trufflesecurity.com",
    "category": "security-identity",
    "tagline": "Open-source secret scanner detecting valid API keys and passwords across code",
    "description": "TruffleHog searches commit logs, Git branches, and S3 buckets to locate active credentials and verify validity. It is built for open-source developers and security engineers.",
    "rating": 4.9,
    "reviewsCount": 680,
    "pricing": "Freemium",
    "websiteUrl": "https://trufflesecurity.com",
    "affiliateUrl": "https://trufflesecurity.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "580K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "cyberhaven-data",
    "name": "Cyberhaven",
    "domain": "cyberhaven.com",
    "category": "security-identity",
    "tagline": "Data Lineage and Data Loss Prevention (DLP) platform for shadow AI risks",
    "description": "Cyberhaven tracks file lineage across endpoints and web apps to prevent employees from pasting sensitive data into public LLMs. It serves corporate CISOs and data security managers.",
    "rating": 4.8,
    "reviewsCount": 140,
    "pricing": "Paid",
    "websiteUrl": "https://cyberhaven.com",
    "affiliateUrl": "https://cyberhaven.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "180K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "openziti-mesh",
    "name": "OpenZiti",
    "domain": "openziti.io",
    "category": "security-identity",
    "tagline": "Open-source programmable zero-trust network mesh for application software",
    "description": "OpenZiti embeds zero-trust connectivity directly into software application code without requiring external VPN clients. It is engineered for software developers and networking architects.",
    "rating": 4.8,
    "reviewsCount": 210,
    "pricing": "Free",
    "websiteUrl": "https://openziti.io",
    "affiliateUrl": "https://openziti.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "240K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "netmaker-mesh",
    "name": "Netmaker",
    "domain": "netmaker.io",
    "category": "security-identity",
    "tagline": "Automated open-source WireGuard virtual networking and ZTNA engine",
    "description": "Netmaker automates fast, multi-cloud WireGuard virtual networks across distributed servers and cloud instances. It serves DevOps engineers connecting private cloud networks.",
    "rating": 4.7,
    "reviewsCount": 190,
    "pricing": "Freemium",
    "websiteUrl": "https://netmaker.io",
    "affiliateUrl": "https://netmaker.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "150K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "buttercup-vault",
    "name": "Buttercup",
    "domain": "buttercup.pw",
    "category": "security-identity",
    "tagline": "Free, open-source NodeJS-powered offline password vault for desktop and mobile",
    "description": "Buttercup stores encrypted credentials in local vault files or syncs them securely via personal WebDAV and cloud drives. It serves privacy enthusiasts wanting open-source credential security.",
    "rating": 4.6,
    "reviewsCount": 180,
    "pricing": "Free",
    "websiteUrl": "https://buttercup.pw",
    "affiliateUrl": "https://buttercup.pw",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "95K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "passage-passkeys",
    "name": "Passage by 1Password",
    "domain": "passage.1password.com",
    "category": "security-identity",
    "tagline": "Passkey-first authentication infrastructure for web and mobile developers",
    "description": "Passage replaces standard password logins with native WebAuthn device biometrics like Touch ID and Face ID. It is engineered for developers embedding passkey authentication into web apps.",
    "rating": 4.7,
    "reviewsCount": 140,
    "pricing": "Freemium",
    "websiteUrl": "https://passage.1password.com",
    "affiliateUrl": "https://passage.1password.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "180K",
    "isFreeTier": true,
    "isOpenSource": false
  }
];

const saasDataPath = path.join(__dirname, '..', 'src', 'data', 'saasData.jsx');
let content = fs.readFileSync(saasDataPath, 'utf8');

const match = content.match(/export const staticSaasTools = (\[[\s\S]*?\n\]);/);
if (!match) {
  console.error('Could not find staticSaasTools in saasData.jsx');
  process.exit(1);
}

let existingTools = JSON.parse(match[1]);

const existingIds = new Set(existingTools.map(t => t.id.toLowerCase()));
const existingNames = new Set(existingTools.map(t => t.name.toLowerCase()));

let addedCount = 0;
let skippedCount = 0;

newTools.forEach(tool => {
  const normId = tool.id.toLowerCase();
  const normName = tool.name.toLowerCase();

  if (!existingIds.has(normId) && !existingNames.has(normName)) {
    existingTools.push(tool);
    existingIds.add(normId);
    existingNames.add(normName);
    addedCount++;
  } else {
    // Enrich existing tool without creating a duplicate
    const idx = existingTools.findIndex(t => t.id.toLowerCase() === normId || t.name.toLowerCase() === normName);
    if (idx !== -1) {
      existingTools[idx] = { ...existingTools[idx], category: tool.category, tagline: tool.tagline || existingTools[idx].tagline };
    }
    skippedCount++;
  }
});

const updatedArrayStr = JSON.stringify(existingTools, null, 2);
content = content.replace(/export const staticSaasTools = \[[\s\S]*?\n\];/, `export const staticSaasTools = ${updatedArrayStr};`);

fs.writeFileSync(saasDataPath, content, 'utf8');
console.log(`Ingestion Complete! Added: ${addedCount} brand new tools | Deduplicated: ${skippedCount} existing tools | Total static tools: ${existingTools.length}`);
