const fs = require('fs');
const path = require('path');

const newTools = [
  {
    "id": "kong-gateway",
    "name": "Kong Gateway",
    "domain": "konghq.com",
    "category": "api-management",
    "tagline": "Cloud-native, high-performance API gateway and microservices management platform",
    "description": "Kong Gateway manages API traffic, load balancing, authentication, and rate-limiting for microservice architectures. It serves enterprise software architects, platform engineers, and cloud infrastructure leads.",
    "rating": 4.8,
    "reviewsCount": 2100,
    "pricing": "Freemium",
    "websiteUrl": "https://konghq.com",
    "affiliateUrl": "https://konghq.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "4.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "tyk-io",
    "name": "Tyk",
    "domain": "tyk.io",
    "category": "api-management",
    "tagline": "Open-source enterprise API gateway, management platform, and developer portal",
    "description": "Tyk delivers lightweight API routing, quota management, detailed analytics, and developer portal generation with zero dependencies. It is built for DevOps engineers, software architects, and enterprise platform leads.",
    "rating": 4.7,
    "reviewsCount": 850,
    "pricing": "Freemium",
    "websiteUrl": "https://tyk.io",
    "affiliateUrl": "https://tyk.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "svix-webhooks",
    "name": "Svix",
    "domain": "svix.com",
    "category": "api-management",
    "tagline": "Enterprise webhook-as-a-service infrastructure for sending and managing webhooks",
    "description": "Svix handles webhook sending, automatic retries, security signatures, and developer management portals via simple APIs. It serves SaaS developers, product engineering teams, and API platforms.",
    "rating": 4.9,
    "reviewsCount": 310,
    "pricing": "Freemium",
    "websiteUrl": "https://svix.com",
    "affiliateUrl": "https://svix.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "krakend",
    "name": "KrakenD",
    "domain": "krakend.io",
    "category": "api-management",
    "tagline": "Ultra-performance, stateless open-source API gateway written in Go",
    "description": "KrakenD transforms, aggregates, and filters API requests at high throughput without requiring a centralized database state. It is built for backend developers and microservice architects prioritizing raw execution speed.",
    "rating": 4.8,
    "reviewsCount": 650,
    "pricing": "Freemium",
    "websiteUrl": "https://krakend.io",
    "affiliateUrl": "https://krakend.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "850K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "hasura",
    "name": "Hasura",
    "domain": "hasura.io",
    "category": "api-management",
    "tagline": "Instant GraphQL and REST API engine over databases with built-in authorization",
    "description": "Hasura auto-generates real-time GraphQL and REST API endpoints directly over existing SQL databases with row-level security. It is engineered for full-stack developers and backend software teams.",
    "rating": 4.8,
    "reviewsCount": 1820,
    "pricing": "Freemium",
    "websiteUrl": "https://hasura.io",
    "affiliateUrl": "https://hasura.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "2.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "mulesoft-anypoint",
    "name": "MuleSoft Anypoint Platform",
    "domain": "mulesoft.com",
    "category": "api-management",
    "tagline": "Enterprise API management, integration, and lifecycle orchestration engine",
    "description": "Anypoint Platform manages enterprise API design, deployment, security governance, and system integration workflows. It is built for enterprise integration architects and corporate IT operations.",
    "rating": 4.4,
    "reviewsCount": 2400,
    "pricing": "Free Trial",
    "websiteUrl": "https://mulesoft.com",
    "affiliateUrl": "https://mulesoft.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "6.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "apigee-google",
    "name": "Google Cloud Apigee",
    "domain": "cloud.google.com/apigee",
    "category": "api-management",
    "tagline": "Enterprise API management platform for security, analytics, and monetization",
    "description": "Apigee enables enterprises to design, secure, deploy, monitor, and monetize APIs across multi-cloud infrastructure. It serves enterprise cloud architects and corporate API program managers.",
    "rating": 4.5,
    "reviewsCount": 1950,
    "pricing": "Paid",
    "websiteUrl": "https://cloud.google.com/apigee",
    "affiliateUrl": "https://cloud.google.com/apigee",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "42.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "aws-api-gateway",
    "name": "Amazon API Gateway",
    "domain": "aws.amazon.com/api-gateway",
    "category": "api-management",
    "tagline": "Fully managed service to create, publish, secure, and monitor APIs at scale",
    "description": "Amazon API Gateway handles traffic management, CORS support, authorization, and throttling for serverless Lambda backends. It is built for AWS cloud architects and backend engineers.",
    "rating": 4.6,
    "reviewsCount": 3100,
    "pricing": "Freemium",
    "websiteUrl": "https://aws.amazon.com/api-gateway",
    "affiliateUrl": "https://aws.amazon.com/api-gateway",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "68.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "traefik-hub",
    "name": "Traefik Hub",
    "domain": "traefik.io/traefik-hub",
    "category": "api-management",
    "tagline": "Cloud-native API management and API gateway for Kubernetes and Docker",
    "description": "Traefik Hub publishes, secures, and tracks microservice APIs automatically across Kubernetes clusters. It serves DevOps engineers and cloud-native platform architects.",
    "rating": 4.8,
    "reviewsCount": 890,
    "pricing": "Freemium",
    "websiteUrl": "https://traefik.io/traefik-hub",
    "affiliateUrl": "https://traefik.io/traefik-hub",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "apollo-graphql",
    "name": "Apollo GraphOS",
    "domain": "apollographql.com",
    "category": "api-management",
    "tagline": "The platform for building, managing, and unifying a supergraph API",
    "description": "Apollo GraphOS coordinates GraphQL schema composition, query routing, and federated subgraphs into a unified endpoint. It serves frontend developers and enterprise GraphQL architects.",
    "rating": 4.8,
    "reviewsCount": 1650,
    "pricing": "Freemium",
    "websiteUrl": "https://apollographql.com",
    "affiliateUrl": "https://apollographql.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "gravitee-io",
    "name": "Gravitee.io",
    "domain": "gravitee.io",
    "category": "api-management",
    "tagline": "Flexible event-native API management and API security platform",
    "description": "Gravitee manages REST, GraphQL, and event-driven APIs (Kafka, WebSockets) with real-time policy controls and threat blocking. It serves enterprise integration leads and AppSec teams.",
    "rating": 4.7,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://gravitee.io",
    "affiliateUrl": "https://gravitee.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "wso2-api-manager",
    "name": "WSO2 API Manager",
    "domain": "wso2.com/api-management",
    "category": "api-management",
    "tagline": "Full-lifecycle open-source API management and integration platform",
    "description": "WSO2 API Manager controls API design, monetization, rate limiting, microgateway routing, and developer portals. It is engineered for enterprise IT organizations and middleware developers.",
    "rating": 4.5,
    "reviewsCount": 920,
    "pricing": "Freemium",
    "websiteUrl": "https://wso2.com/api-management",
    "affiliateUrl": "https://wso2.com/api-management",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "standard-webhooks",
    "name": "Hookdeck",
    "domain": "hookdeck.com",
    "category": "api-management",
    "tagline": "Event gateway infrastructure for receiving, queuing, and routing webhooks safely",
    "description": "Hookdeck acts as an asynchronous queue between webhook senders and receiving application servers to prevent dropped events. It serves software developers and backend integration leads.",
    "rating": 4.9,
    "reviewsCount": 240,
    "pricing": "Freemium",
    "websiteUrl": "https://hookdeck.com",
    "affiliateUrl": "https://hookdeck.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "380K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "convoy-webhooks",
    "name": "Convoy",
    "domain": "getconvoy.io",
    "category": "api-management",
    "tagline": "High-performance open-source webhook gateway for ingesting and dispatching webhooks",
    "description": "Convoy manages incoming and outgoing webhook delivery with rate-limiting, event filtering, and delivery logs. It is designed for developers building webhook-first platforms and microservices.",
    "rating": 4.8,
    "reviewsCount": 180,
    "pricing": "Freemium",
    "websiteUrl": "https://getconvoy.io",
    "affiliateUrl": "https://getconvoy.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "240K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "treblle-observability",
    "name": "Treblle",
    "domain": "treblle.com",
    "category": "api-management",
    "tagline": "API observability, real-time monitoring, auto-documentation, and security insights",
    "description": "Treblle provides instant API logging, payload inspection, security scoring, and auto-generated API docs via single-line SDKs. It serves backend engineers and engineering managers.",
    "rating": 4.9,
    "reviewsCount": 340,
    "pricing": "Freemium",
    "websiteUrl": "https://treblle.com",
    "affiliateUrl": "https://treblle.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "420K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "resurface-io",
    "name": "Resurface",
    "domain": "resurface.io",
    "category": "api-management",
    "tagline": "API-first data capture and API observability database for security and QA",
    "description": "Resurface captures full API request and response payloads locally without sampling to debug failures and catch security threats. It is tailored for AppSec leads and QA engineers.",
    "rating": 4.7,
    "reviewsCount": 110,
    "pricing": "Freemium",
    "websiteUrl": "https://resurface.io",
    "affiliateUrl": "https://resurface.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "120K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "moesif-api",
    "name": "Moesif",
    "domain": "moesif.com",
    "category": "api-management",
    "tagline": "API analytics, usage-based billing monetization, and observability platform",
    "description": "Moesif tracks individual API usage metrics, calculates consumption billing tiers, and detects user-level API errors. It serves SaaS product managers, API product leads, and growth teams.",
    "rating": 4.8,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://moesif.com",
    "affiliateUrl": "https://moesif.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "510K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "rapidapi-enterprise",
    "name": "Rapid",
    "domain": "rapidapi.com",
    "category": "api-management",
    "tagline": "The world's largest API marketplace and enterprise internal API hub",
    "description": "Rapid provides a central platform to discover, connect to, and manage public and private internal enterprise APIs. It serves software engineers, API providers, and enterprise IT leads.",
    "rating": 4.5,
    "reviewsCount": 2100,
    "pricing": "Freemium",
    "websiteUrl": "https://rapidapi.com",
    "affiliateUrl": "https://rapidapi.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "12.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "gloo-gateway",
    "name": "Gloo Gateway (Solo.io)",
    "domain": "solo.io/products/gloo",
    "category": "api-management",
    "tagline": "Kubernetes-native Envoy-powered API gateway and service mesh control plane",
    "description": "Gloo Gateway orchestrates microservice traffic, gRPC routing, and GraphQL APIs built natively on top of Envoy Proxy. It serves cloud-native infrastructure engineers and Kubernetes architects.",
    "rating": 4.8,
    "reviewsCount": 290,
    "pricing": "Freemium",
    "websiteUrl": "https://solo.io/products/gloo",
    "affiliateUrl": "https://solo.io/products/gloo",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "320K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "apisix-apache",
    "name": "Apache APISIX",
    "domain": "apisix.apache.org",
    "category": "api-management",
    "tagline": "Dynamic, real-time, high-performance open-source cloud-native API gateway",
    "description": "Apache APISIX routes HTTP, gRPC, and MQTT traffic with dynamic plugin reloading and ultra-low latency execution. It serves backend system engineers and microservice platform operators.",
    "rating": 4.8,
    "reviewsCount": 620,
    "pricing": "Free",
    "websiteUrl": "https://apisix.apache.org",
    "affiliateUrl": "https://apisix.apache.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "580K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "benthos-redpanda",
    "name": "Redpanda Connect (Benthos)",
    "domain": "redpanda.com/redpanda-connect",
    "category": "api-management",
    "tagline": "High-performance stream processor connecting APIs, webhooks, and data queues",
    "description": "Redpanda Connect transforms and routes streaming event data between webhooks, REST APIs, Kafka, and cloud databases. It is tailored for data engineers and event-driven architects.",
    "rating": 4.9,
    "reviewsCount": 420,
    "pricing": "Free",
    "websiteUrl": "https://redpanda.com/redpanda-connect",
    "affiliateUrl": "https://redpanda.com/redpanda-connect",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "650K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "wundergraph",
    "name": "WunderGraph",
    "domain": "wundergraph.com",
    "category": "api-management",
    "tagline": "Declarative API composition framework merging REST, GraphQL, and databases into one schema",
    "description": "WunderGraph stitches databases, microservices, and third-party APIs into a secure, type-safe API gateway interface. It serves full-stack software engineers and API developers.",
    "rating": 4.9,
    "reviewsCount": 210,
    "pricing": "Freemium",
    "websiteUrl": "https://wundergraph.com",
    "affiliateUrl": "https://wundergraph.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "280K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "tailcall-graphql",
    "name": "Tailcall",
    "domain": "tailcall.run",
    "category": "api-management",
    "tagline": "High-performance Rust-based GraphQL gateway for composing REST and gRPC microservices",
    "description": "Tailcall optimizes GraphQL query execution by transforming declarative configurations into JIT-compiled API execution graphs. It is built for backend systems engineers and API platform leads.",
    "rating": 4.9,
    "reviewsCount": 140,
    "pricing": "Free",
    "websiteUrl": "https://tailcall.run",
    "affiliateUrl": "https://tailcall.run",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "150K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "stepzen-ibm",
    "name": "StepZen (IBM)",
    "domain": "ibm.com/products/stepzen",
    "category": "api-management",
    "tagline": "Declarative GraphQL engine to aggregate multi-source backend data fast",
    "description": "StepZen compiles REST endpoints, databases, and microservices into a unified GraphQL API schema using declarative code configs. It serves backend software developers and data teams.",
    "rating": 4.7,
    "reviewsCount": 180,
    "pricing": "Freemium",
    "websiteUrl": "https://ibm.com/products/stepzen",
    "affiliateUrl": "https://ibm.com/products/stepzen",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "18.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "graphql-mesh",
    "name": "GraphQL Mesh",
    "domain": "the-guild.dev/graphql/mesh",
    "category": "api-management",
    "tagline": "Open-source framework to query OpenAPI, gRPC, and SOAP endpoints using GraphQL",
    "description": "GraphQL Mesh converts non-GraphQL backend services into unified executable GraphQL schemas without changing backend code. It is engineered for frontend leads and API integration architects.",
    "rating": 4.8,
    "reviewsCount": 380,
    "pricing": "Free",
    "websiteUrl": "https://the-guild.dev/graphql/mesh",
    "affiliateUrl": "https://the-guild.dev/graphql/mesh",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "graphql-hive",
    "name": "GraphQL Hive",
    "domain": "graphql-hive.com",
    "category": "api-management",
    "tagline": "Open-source GraphQL schema registry, analytics, and breaking change monitoring platform",
    "description": "GraphQL Hive prevents breaking schema deployments and tracks field-level usage analytics across GraphQL federations. It serves frontend and backend teams maintaining shared GraphQL APIs.",
    "rating": 4.9,
    "reviewsCount": 190,
    "pricing": "Freemium",
    "websiteUrl": "https://graphql-hive.com",
    "affiliateUrl": "https://graphql-hive.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "210K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "azure-api-mgmt",
    "name": "Azure API Management",
    "domain": "azure.microsoft.com/products/api-management",
    "category": "api-management",
    "tagline": "Hybrid multi-cloud API management platform for securing and analyzing enterprise APIs",
    "description": "Azure API Management provides enterprise gateways, developer portals, JWT validation, and rate limiting natively in Microsoft Azure. It is built for enterprise cloud operations and solution architects.",
    "rating": 4.5,
    "reviewsCount": 1820,
    "pricing": "Freemium",
    "websiteUrl": "https://azure.microsoft.com/products/api-management",
    "affiliateUrl": "https://azure.microsoft.com/products/api-management",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "38.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "starlight-api",
    "name": "Speakeasy",
    "domain": "speakeasy.com",
    "category": "api-management",
    "tagline": "Automated SDK generation, OpenAPI linter, and type-safe API client builder",
    "description": "Speakeasy generates production-grade idiomatic client SDKs and Terraform providers directly from OpenAPI specifications. It serves API product engineering teams and SaaS platform leads.",
    "rating": 4.9,
    "reviewsCount": 160,
    "pricing": "Freemium",
    "websiteUrl": "https://speakeasy.com",
    "affiliateUrl": "https://speakeasy.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "280K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "libib-fern",
    "name": "Fern",
    "domain": "buildwithfern.com",
    "category": "api-management",
    "tagline": "Open-source tool to generate client SDKs, API documentation, and Postman collections",
    "description": "Fern turns API definitions into published SDKs in TypeScript, Python, Go, and Java alongside developer portals. It is engineered for API engineers scaling external developer platforms.",
    "rating": 4.9,
    "reviewsCount": 210,
    "pricing": "Freemium",
    "websiteUrl": "https://buildwithfern.com",
    "affiliateUrl": "https://buildwithfern.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "310K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "bump-sh",
    "name": "Bump.sh",
    "domain": "bump.sh",
    "category": "api-management",
    "tagline": "Automated API change tracking, interactive documentation, and diff detection",
    "description": "Bump.sh tracks OpenAPI and AsyncAPI schema changes on pull requests to render human-readable diff reports automatically. It serves technical writers, API architects, and frontend developers.",
    "rating": 4.8,
    "reviewsCount": 140,
    "pricing": "Freemium",
    "websiteUrl": "https://bump.sh",
    "affiliateUrl": "https://bump.sh",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "180K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "zuplo-gateway",
    "name": "Zuplo",
    "domain": "zuplo.com",
    "category": "api-management",
    "tagline": "Edge-deployed API gateway with git-driven workflows and key management",
    "description": "Zuplo deploys API gateways to edge networks in seconds with programmatic API key management, rate limiting, and OpenAPI docs. It serves Jamstack developers and modern SaaS engineering leads.",
    "rating": 4.9,
    "reviewsCount": 180,
    "pricing": "Freemium",
    "websiteUrl": "https://zuplo.com",
    "affiliateUrl": "https://zuplo.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "240K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "unkey-dev",
    "name": "Unkey",
    "domain": "unkey.com",
    "category": "api-management",
    "tagline": "Open-source fast API key management and rate-limiting infrastructure for developers",
    "description": "Unkey handles global API key creation, verification, revocation, and per-user rate-limiting at edge speed. It is engineered for SaaS developers monetizing custom APIs.",
    "rating": 4.9,
    "reviewsCount": 210,
    "pricing": "Freemium",
    "websiteUrl": "https://unkey.com",
    "affiliateUrl": "https://unkey.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "320K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "webhooks-site",
    "name": "Webhook.site",
    "domain": "webhook.site",
    "category": "api-management",
    "tagline": "Instant online HTTP request inspection and custom webhook testing endpoint",
    "description": "Webhook.site provides disposable, instant HTTP endpoints to inspect incoming webhook payloads, headers, and execution scripts. It is a daily utility for developers and QA engineers.",
    "rating": 4.9,
    "reviewsCount": 1420,
    "pricing": "Freemium",
    "websiteUrl": "https://webhook.site",
    "affiliateUrl": "https://webhook.site",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "requestbin-pipedream",
    "name": "RequestBin (Pipedream)",
    "domain": "requestbin.com",
    "category": "api-management",
    "tagline": "Inspect HTTP requests and build serverless webhook processing workflows",
    "description": "RequestBin captures HTTP requests and allows developers to write Node.js or Python code to process payloads in real time. It serves backend developers and webhook integration engineers.",
    "rating": 4.8,
    "reviewsCount": 850,
    "pricing": "Freemium",
    "websiteUrl": "https://requestbin.com",
    "affiliateUrl": "https://requestbin.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "sentry-api-mon",
    "name": "Sentry API Monitoring",
    "domain": "sentry.io/for/api-monitoring",
    "category": "api-management",
    "tagline": "API error tracking, performance tracing, and slow request identification",
    "description": "Sentry pinpoints failing API endpoints, broken response status codes, and slow database queries across distributed calls. It is built for backend developers and SREs.",
    "rating": 4.8,
    "reviewsCount": 2400,
    "pricing": "Freemium",
    "websiteUrl": "https://sentry.io/for/api-monitoring",
    "affiliateUrl": "https://sentry.io/for/api-monitoring",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "6.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "optic-openapi",
    "name": "Optic",
    "domain": "useoptic.com",
    "category": "api-management",
    "tagline": "Open-source Git-like version control and breaking change detection for OpenAPI",
    "description": "Optic catches breaking API changes in CI pipelines by comparing actual endpoint behavior against OpenAPI definitions. It serves AppSec leads, backend engineers, and technical leads.",
    "rating": 4.8,
    "reviewsCount": 310,
    "pricing": "Free",
    "websiteUrl": "https://useoptic.com",
    "affiliateUrl": "https://useoptic.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "240K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "schemathesis-api",
    "name": "Schemathesis",
    "domain": "schemathesis.io",
    "category": "api-management",
    "tagline": "Open-source property-based API testing tool derived from OpenAPI specifications",
    "description": "Schemathesis automatically generates edge-case test payloads from OpenAPI definitions to uncover server crashes and spec violations. It is built for QA leads and backend developers.",
    "rating": 4.9,
    "reviewsCount": 180,
    "pricing": "Free",
    "websiteUrl": "https://schemathesis.io",
    "affiliateUrl": "https://schemathesis.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "190K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "prism-stoplight",
    "name": "Stoplight Prism",
    "domain": "stoplight.io/open-source/prism",
    "category": "api-management",
    "tagline": "Open-source HTTP mock server powered by OpenAPI schemas",
    "description": "Prism generates realistic mock API servers directly from OpenAPI documents to enable parallel frontend and backend development. It serves frontend engineers and API product leads.",
    "rating": 4.8,
    "reviewsCount": 510,
    "pricing": "Free",
    "websiteUrl": "https://stoplight.io/open-source/prism",
    "affiliateUrl": "https://stoplight.io/open-source/prism",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "850K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "spectral-stoplight",
    "name": "Stoplight Spectral",
    "domain": "stoplight.io/open-source/spectral",
    "category": "api-management",
    "tagline": "Flexible open-source JSON and YAML linter for API descriptions and OpenAPI files",
    "description": "Spectral enforces enterprise API style guides, naming standards, and security rules across OpenAPI schemas in CI pipelines. It is engineered for API architects and governance leads.",
    "rating": 4.9,
    "reviewsCount": 420,
    "pricing": "Free",
    "websiteUrl": "https://stoplight.io/open-source/spectral",
    "affiliateUrl": "https://stoplight.io/open-source/spectral",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "850K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "microiks-envoy",
    "name": "Envoy Proxy",
    "domain": "envoyproxy.io",
    "category": "api-management",
    "tagline": "High-performance open-source edge and service proxy designed for cloud-native architectures",
    "description": "Envoy Proxy handles service discovery, mTLS security, rate limiting, and observability routing across modern cloud microservices. It is a foundational component for SREs and platform engineers.",
    "rating": 4.8,
    "reviewsCount": 2800,
    "pricing": "Free",
    "websiteUrl": "https://envoyproxy.io",
    "affiliateUrl": "https://envoyproxy.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.9M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "benthos-gateway",
    "name": "Benthos",
    "domain": "benthos.dev",
    "category": "api-management",
    "tagline": "Fancy, resilient stream processor connecting APIs, webhooks, and message queues",
    "description": "Benthos parses, maps, and enriches API traffic payloads moving between HTTP endpoints and message brokers reliably. It is designed for backend engineers and data pipeline developers.",
    "rating": 4.9,
    "reviewsCount": 310,
    "pricing": "Free",
    "websiteUrl": "https://benthos.dev",
    "affiliateUrl": "https://benthos.dev",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "340K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "apito-io",
    "name": "Apito",
    "domain": "apito.io",
    "category": "api-management",
    "tagline": "Instant REST and GraphQL API builder with visual database modeling",
    "description": "Apito converts visual data models into production-ready GraphQL and REST API endpoints with authentication out of the box. It serves full-stack developers and indie hackers.",
    "rating": 4.7,
    "reviewsCount": 120,
    "pricing": "Freemium",
    "websiteUrl": "https://apito.io",
    "affiliateUrl": "https://apito.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "90K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "gravitee-cockpit",
    "name": "Gravitee API Designer",
    "domain": "gravitee.io/products/api-designer",
    "category": "api-management",
    "tagline": "Visual design-first platform for constructing REST and event-driven API specs",
    "description": "Gravitee API Designer provides visual mind-map interfaces to model OpenAPI and AsyncAPI specs before code implementation. It serves API architects and enterprise product teams.",
    "rating": 4.7,
    "reviewsCount": 160,
    "pricing": "Freemium",
    "websiteUrl": "https://gravitee.io/products/api-designer",
    "affiliateUrl": "https://gravitee.io/products/api-designer",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "portman-api",
    "name": "Portman",
    "domain": "github.com/apideck-libraries/portman",
    "category": "api-management",
    "tagline": "Open-source CLI to automatically convert OpenAPI specs into Postman test suites",
    "description": "Portman generates comprehensive API test suites and contract validations directly from OpenAPI definition files. It serves QA engineers, API developers, and CI pipeline leads.",
    "rating": 4.8,
    "reviewsCount": 210,
    "pricing": "Free",
    "websiteUrl": "https://github.com/apideck-libraries/portman",
    "affiliateUrl": "https://github.com/apideck-libraries/portman",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "180K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "read-me-docs",
    "name": "ReadMe",
    "domain": "readme.com",
    "category": "api-management",
    "tagline": "Interactive developer hub platform transforming OpenAPI specs into API portals",
    "description": "ReadMe turns static API references into interactive, testable developer portals with live API key metrics. It serves API product teams, SaaS founders, and technical writers.",
    "rating": 4.7,
    "reviewsCount": 680,
    "pricing": "Paid",
    "websiteUrl": "https://readme.com",
    "affiliateUrl": "https://readme.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "superface-ai",
    "name": "Superface",
    "domain": "superface.ai",
    "category": "api-management",
    "tagline": "Universal API integration layer providing self-healing API calls for AI agents",
    "description": "Superface maps API schemas dynamically, allowing autonomous AI agents and apps to execute API integrations reliably without breaking changes. It serves AI developers and platform engineers.",
    "rating": 4.8,
    "reviewsCount": 140,
    "pricing": "Freemium",
    "websiteUrl": "https://superface.ai",
    "affiliateUrl": "https://superface.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "160K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "mocklab-wiremock",
    "name": "WireMock Cloud (formerly MockLab)",
    "domain": "wiremock.io",
    "category": "api-management",
    "tagline": "Hosted API mocking platform for simulating microservices and third-party APIs",
    "description": "WireMock Cloud hosts collaborative API stubs and chaos testing simulations to unblock parallel frontend and backend engineering. It serves QA teams and software developers.",
    "rating": 4.8,
    "reviewsCount": 320,
    "pricing": "Freemium",
    "websiteUrl": "https://wiremock.io",
    "affiliateUrl": "https://wiremock.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "420K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "starlark-yarp",
    "name": "YARP (Reverse Proxy)",
    "domain": "microsoft.github.io/reverse-proxy",
    "category": "api-management",
    "tagline": "High-performance customizable reverse proxy toolkit built on .NET infrastructure",
    "description": "YARP enables .NET developers to build tailored API gateway routing, load balancing, and health check logic using C#. It is engineered specifically for enterprise .NET engineering teams.",
    "rating": 4.9,
    "reviewsCount": 510,
    "pricing": "Free",
    "websiteUrl": "https://microsoft.github.io/reverse-proxy",
    "affiliateUrl": "https://microsoft.github.io/reverse-proxy",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "webhookdeck-api",
    "name": "Svix Play",
    "domain": "play.svix.com",
    "category": "api-management",
    "tagline": "Free online developer tool to test, debug, and inspect incoming webhook payloads",
    "description": "Svix Play provides instant disposable HTTP endpoints to inspect raw webhook headers, payloads, and JSON data structures. It serves software developers testing webhook integrations.",
    "rating": 4.9,
    "reviewsCount": 180,
    "pricing": "Free",
    "websiteUrl": "https://play.svix.com",
    "affiliateUrl": "https://play.svix.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "mockingbird-api",
    "name": "Mocki",
    "domain": "mocki.io",
    "category": "api-management",
    "tagline": "Simple tool to design and host mock REST APIs with custom JSON responses",
    "description": "Mocki creates instant cloud-hosted REST endpoints with dynamic status codes and CORS configurations for rapid frontend prototyping. It serves web developers and mobile app engineers.",
    "rating": 4.7,
    "reviewsCount": 150,
    "pricing": "Freemium",
    "websiteUrl": "https://mocki.io",
    "affiliateUrl": "https://mocki.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "180K",
    "isFreeTier": true,
    "isOpenSource": false
  }
];

const saasDataPath = path.join(__dirname, '..', 'src', 'data', 'saasData.jsx');
let content = fs.readFileSync(saasDataPath, 'utf8');

const match = content.match(/export const staticSaasTools = (\[[\s\S]*?\n\]);/);
if (!match) {
  console.error('Could not find staticSaasTools in saasData.jsx');
  process.exit(1);
}

let existingTools = JSON.parse(match[1]);

const existingIds = new Set(existingTools.map(t => t.id.toLowerCase()));
const existingNames = new Set(existingTools.map(t => t.name.toLowerCase()));

let addedCount = 0;
let skippedCount = 0;

newTools.forEach(tool => {
  const normId = tool.id.toLowerCase();
  const normName = tool.name.toLowerCase();

  if (!existingIds.has(normId) && !existingNames.has(normName)) {
    existingTools.push(tool);
    existingIds.add(normId);
    existingNames.add(normName);
    addedCount++;
  } else {
    // Enrich existing tool without creating a duplicate
    const idx = existingTools.findIndex(t => t.id.toLowerCase() === normId || t.name.toLowerCase() === normName);
    if (idx !== -1) {
      existingTools[idx] = { ...existingTools[idx], category: tool.category, tagline: tool.tagline || existingTools[idx].tagline };
    }
    skippedCount++;
  }
});

const updatedArrayStr = JSON.stringify(existingTools, null, 2);
content = content.replace(/export const staticSaasTools = \[[\s\S]*?\n\];/, `export const staticSaasTools = ${updatedArrayStr};`);

fs.writeFileSync(saasDataPath, content, 'utf8');
console.log(`Ingestion Complete! Added: ${addedCount} brand new tools | Deduplicated: ${skippedCount} existing tools | Total static tools: ${existingTools.length}`);
