const fs = require('fs');
const path = require('path');

const newTools = [
  {
    "id": "docusign",
    "name": "DocuSign",
    "domain": "docusign.com",
    "category": "esign-documents",
    "tagline": "The global standard for legally binding electronic signatures and agreement workflows",
    "description": "DocuSign allows individuals and enterprises to sign, send, and manage digital documents securely from any device. It is designed for sales teams, legal departments, and businesses automating compliance workflows.",
    "rating": 4.7,
    "reviewsCount": 5100,
    "pricing": "Paid",
    "websiteUrl": "https://docusign.com",
    "affiliateUrl": "https://docusign.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "24.5M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "adobe-acrobat-sign",
    "name": "Adobe Acrobat Sign",
    "domain": "acrobat.adobe.com",
    "category": "esign-documents",
    "tagline": "Enterprise electronic signature solution integrated into Adobe Creative and Document Cloud",
    "description": "Adobe Acrobat Sign enables teams to collect legally compliant e-signatures, automate document approval routes, and track audit trails. It serves enterprise businesses, HR divisions, and legal operations.",
    "rating": 4.6,
    "reviewsCount": 3800,
    "pricing": "Paid",
    "websiteUrl": "https://acrobat.adobe.com",
    "affiliateUrl": "https://acrobat.adobe.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "38.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "dropbox-sign",
    "name": "Dropbox Sign (formerly HelloSign)",
    "domain": "sign.dropbox.com",
    "category": "esign-documents",
    "tagline": "User-friendly electronic signatures built natively into the Dropbox ecosystem",
    "description": "Dropbox Sign provides clean document signing, template management, and developer-friendly eSignature APIs. It is ideal for small-to-medium businesses, freelancers, and software developers.",
    "rating": 4.7,
    "reviewsCount": 2150,
    "pricing": "Freemium",
    "websiteUrl": "https://sign.dropbox.com",
    "affiliateUrl": "https://sign.dropbox.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "12.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "pandadoc",
    "name": "PandaDoc",
    "domain": "pandadoc.com",
    "category": "esign-documents",
    "tagline": "All-in-one document automation, proposal creation, and e-signature software",
    "description": "PandaDoc allows sales teams to build, send, track, and electronically sign proposals, quotes, and contracts. It includes CRM integrations, CPQ features, and interactive payment collection blocks.",
    "rating": 4.7,
    "reviewsCount": 2900,
    "pricing": "Freemium",
    "websiteUrl": "https://pandadoc.com",
    "affiliateUrl": "https://pandadoc.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "6.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "documenso",
    "name": "Documenso",
    "domain": "documenso.com",
    "category": "esign-documents",
    "tagline": "The open-source alternative to DocuSign built for modern web stacks",
    "description": "Documenso provides an open-source, self-hostable document signing platform with full API access and custom domain support. It is engineered for privacy-first organizations, developers, and tech companies.",
    "rating": 4.8,
    "reviewsCount": 420,
    "pricing": "Freemium",
    "websiteUrl": "https://documenso.com",
    "affiliateUrl": "https://documenso.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "280K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "signwell",
    "name": "SignWell",
    "domain": "signwell.com",
    "category": "esign-documents",
    "tagline": "Affordable, legally binding electronic signatures and document tracking software",
    "description": "SignWell offers legally compliant e-signatures, automated signing reminders, and reusable document templates. It is tailored for small businesses, agencies, and consultants looking for cost-effective e-signatures.",
    "rating": 4.8,
    "reviewsCount": 850,
    "pricing": "Freemium",
    "websiteUrl": "https://signwell.com",
    "affiliateUrl": "https://signwell.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "signnow",
    "name": "signNow by airSlate",
    "domain": "signnow.com",
    "category": "esign-documents",
    "tagline": "Enterprise eSignature solution and document workflow automation engine",
    "description": "signNow provides secure electronic signature capabilities, complex multi-signer routing, and automated document generation. It serves medium-to-large businesses seeking scalable agreement management.",
    "rating": 4.6,
    "reviewsCount": 1650,
    "pricing": "Free Trial",
    "websiteUrl": "https://signnow.com",
    "affiliateUrl": "https://signnow.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.9M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "proposify",
    "name": "Proposify",
    "domain": "proposify.com",
    "category": "esign-documents",
    "tagline": "Proposal software for sales teams to build, track, and close agreements",
    "description": "Proposify gives sales reps control over brand-consistent sales proposals, contract templates, and electronic signatures. It is built for agencies, software sales teams, and B2B services.",
    "rating": 4.5,
    "reviewsCount": 1100,
    "pricing": "Free Trial",
    "websiteUrl": "https://proposify.com",
    "affiliateUrl": "https://proposify.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "getaccept",
    "name": "GetAccept",
    "domain": "getaccept.com",
    "category": "esign-documents",
    "tagline": "Digital sales room platform combining video, proposals, and eSignatures",
    "description": "GetAccept combines proposal creation, personalized sales videos, live buyer chat, and legally binding eSignatures into interactive digital sales rooms. It is engineered for B2B sales teams.",
    "rating": 4.6,
    "reviewsCount": 780,
    "pricing": "Freemium",
    "websiteUrl": "https://getaccept.com",
    "affiliateUrl": "https://getaccept.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "850K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "ironclad",
    "name": "Ironclad",
    "domain": "ironcladapp.com",
    "category": "esign-documents",
    "tagline": "Enterprise contract lifecycle management (CLM) and digital contracting platform",
    "description": "Ironclad automates contract creation, redlining, approval workflows, and repository tracking using AI. It is designed for enterprise legal teams, procurement divisions, and corporate operations.",
    "rating": 4.7,
    "reviewsCount": 920,
    "pricing": "Paid",
    "websiteUrl": "https://ironcladapp.com",
    "affiliateUrl": "https://ironcladapp.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "conga-sign",
    "name": "Conga Sign",
    "domain": "conga.com",
    "category": "esign-documents",
    "tagline": "Enterprise revenue lifecycle and integrated eSignature software for Salesforce",
    "description": "Conga Sign automates document generation and electronic signature execution directly inside Salesforce records. It serves enterprise revenue teams, legal operations, and contract administrators.",
    "rating": 4.4,
    "reviewsCount": 650,
    "pricing": "Paid",
    "websiteUrl": "https://conga.com",
    "affiliateUrl": "https://conga.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "920K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "formstack-documents",
    "name": "Formstack Documents",
    "domain": "formstack.com/products/documents",
    "category": "esign-documents",
    "tagline": "Automated document generation and template workflow software",
    "description": "Formstack Documents automatically populates custom PDF, Word, and Excel files using web form or CRM data sources. It is built for businesses streamlining paperwork and compliance generation.",
    "rating": 4.5,
    "reviewsCount": 540,
    "pricing": "Paid",
    "websiteUrl": "https://formstack.com/products/documents",
    "affiliateUrl": "https://formstack.com/products/documents",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.9M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "bold-sign",
    "name": "BoldSign",
    "domain": "boldsign.com",
    "category": "esign-documents",
    "tagline": "Enterprise-grade electronic signature software and developer API platform",
    "description": "BoldSign delivers legally compliant digital signature collection with custom branding, cloud storage sync, and REST APIs. It serves growing businesses and software engineers embedding signatures.",
    "rating": 4.8,
    "reviewsCount": 310,
    "pricing": "Freemium",
    "websiteUrl": "https://boldsign.com",
    "affiliateUrl": "https://boldsign.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "410K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "signaturely",
    "name": "Signaturely",
    "domain": "signaturely.com",
    "category": "esign-documents",
    "tagline": "Simple online eSignature software for online document signing",
    "description": "Signaturely helps users upload documents, place signature fields, and request legally binding signatures in minutes. It is built for solopreneurs, small business owners, and remote teams.",
    "rating": 4.7,
    "reviewsCount": 490,
    "pricing": "Freemium",
    "websiteUrl": "https://signaturely.com",
    "affiliateUrl": "https://signaturely.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "docupilot",
    "name": "Docupilot",
    "domain": "docupilot.app",
    "category": "esign-documents",
    "tagline": "Flexible document automation platform for generating PDFs and contracts",
    "description": "Docupilot automatically converts template documents into personalized PDFs and Word documents using data from Airtable or Zapier. It serves non-coders and operations managers automating paperwork.",
    "rating": 4.8,
    "reviewsCount": 210,
    "pricing": "Free Trial",
    "websiteUrl": "https://docupilot.app",
    "affiliateUrl": "https://docupilot.app",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "190K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "pdf-monkey",
    "name": "PDFMonkey",
    "domain": "pdfmonkey.io",
    "category": "esign-documents",
    "tagline": "Developer-friendly HTML to PDF document generation service",
    "description": "PDFMonkey allows developers to design PDF templates using HTML and CSS, rendering documents dynamically via API requests. It is engineered for web application developers automing PDF exports.",
    "rating": 4.8,
    "reviewsCount": 180,
    "pricing": "Freemium",
    "websiteUrl": "https://pdfmonkey.io",
    "affiliateUrl": "https://pdfmonkey.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "240K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "anvil",
    "name": "Anvil",
    "domain": "useanvil.com",
    "category": "esign-documents",
    "tagline": "APIs for PDF generation, web forms, and developer electronic signatures",
    "description": "Anvil provides APIs to convert paperwork into web forms, generate PDFs programmatically, and collect digital signatures. It is built for engineering teams modernizing legacy paper workflows.",
    "rating": 4.9,
    "reviewsCount": 160,
    "pricing": "Freemium",
    "websiteUrl": "https://useanvil.com",
    "affiliateUrl": "https://useanvil.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "150K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "eversign",
    "name": "Eversign",
    "domain": "eversign.com",
    "category": "esign-documents",
    "tagline": "Secure digital signature software for businesses and developers",
    "description": "Eversign provides legally binding electronic signatures, document templates, and REST APIs for automated signing. It serves freelancers, small businesses, and enterprise teams requiring cloud signing.",
    "rating": 4.6,
    "reviewsCount": 620,
    "pricing": "Freemium",
    "websiteUrl": "https://eversign.com",
    "affiliateUrl": "https://eversign.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "890K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "smallpdf",
    "name": "Smallpdf",
    "domain": "smallpdf.com",
    "category": "esign-documents",
    "tagline": "All-in-one web PDF editor, converter, compressor, and eSign tool",
    "description": "Smallpdf provides online tools to edit, convert, compress, merge, and electronically sign PDF files directly in browser. It is popular among students, office workers, and general web users.",
    "rating": 4.7,
    "reviewsCount": 4200,
    "pricing": "Freemium",
    "websiteUrl": "https://smallpdf.com",
    "affiliateUrl": "https://smallpdf.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "42.0M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "ilovepdf",
    "name": "iLovePDF",
    "domain": "ilovepdf.com",
    "category": "esign-documents",
    "tagline": "Every online PDF management tool needed in one place",
    "description": "iLovePDF offers suite utilities for merging, splitting, compressing, converting, and digitally signing PDF documents online. It serves millions of casual, academic, and professional users daily.",
    "rating": 4.8,
    "reviewsCount": 6100,
    "pricing": "Freemium",
    "websiteUrl": "https://ilovepdf.com",
    "affiliateUrl": "https://ilovepdf.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "85.0M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "pdf24",
    "name": "PDF24 Creator",
    "domain": "pdf24.org",
    "category": "esign-documents",
    "tagline": "100% free offline and online PDF tools and document editor",
    "description": "PDF24 provides completely free desktop and web utilities to organize, convert, sign, and protect PDF files without restrictions. It is ideal for budget-conscious users and enterprise IT deployment.",
    "rating": 4.8,
    "reviewsCount": 3100,
    "pricing": "Free",
    "websiteUrl": "https://pdf24.org",
    "affiliateUrl": "https://pdf24.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "21.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "sodapdf",
    "name": "Soda PDF",
    "domain": "sodapdf.com",
    "category": "esign-documents",
    "tagline": "Comprehensive PDF editor, converter, and digital signature suite",
    "description": "Soda PDF allows users to edit text, insert images, extract pages, and request electronic signatures on desktop and web. It is built for business professionals needing full PDF authoring control.",
    "rating": 4.4,
    "reviewsCount": 1450,
    "pricing": "Freemium",
    "websiteUrl": "https://sodapdf.com",
    "affiliateUrl": "https://sodapdf.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "5.6M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "pdf-element",
    "name": "Wondershare PDFelement",
    "domain": "pdf.wondershare.com",
    "category": "esign-documents",
    "tagline": "All-in-one PDF editing, OCR scanning, and eSigning software",
    "description": "PDFelement provides desktop and mobile editing, form creation, optical character recognition (OCR), and secure e-signatures. It serves individual professionals, educators, and enterprise teams.",
    "rating": 4.5,
    "reviewsCount": 2100,
    "pricing": "Free Trial",
    "websiteUrl": "https://pdf.wondershare.com",
    "affiliateUrl": "https://pdf.wondershare.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "8.9M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "foxit-pdf-editor",
    "name": "Foxit PDF Editor",
    "domain": "foxit.com",
    "category": "esign-documents",
    "tagline": "Fast, affordable enterprise PDF creation, editing, and eSign suite",
    "description": "Foxit PDF Editor delivers robust document editing, security redaction, form building, and integrated Foxit eSign. It is an established Adobe Acrobat alternative for enterprise IT environments.",
    "rating": 4.6,
    "reviewsCount": 2800,
    "pricing": "Free Trial",
    "websiteUrl": "https://foxit.com",
    "affiliateUrl": "https://foxit.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "6.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "nitro-sign",
    "name": "Nitro PDF & Sign",
    "domain": "gonitro.com",
    "category": "esign-documents",
    "tagline": "Enterprise PDF editing, document conversion, and eSignature solution",
    "description": "Nitro provides high-volume PDF editing tools combined with unlimited electronic signatures and document analytics. It is engineered for corporate teams reducing paper usage across organizations.",
    "rating": 4.5,
    "reviewsCount": 1900,
    "pricing": "Free Trial",
    "websiteUrl": "https://gonitro.com",
    "affiliateUrl": "https://gonitro.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "airslate",
    "name": "airSlate",
    "domain": "airslate.com",
    "category": "esign-documents",
    "tagline": "No-code business process automation, document generation, and eSignatures",
    "description": "airSlate combines contract generation, web forms, automated routing bots, and eSignatures into complete no-code workflows. It serves operations leaders automating end-to-end documentation.",
    "rating": 4.6,
    "reviewsCount": 890,
    "pricing": "Free Trial",
    "websiteUrl": "https://airslate.com",
    "affiliateUrl": "https://airslate.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.7M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "conga-composer",
    "name": "Conga Composer",
    "domain": "conga.com/products/conga-composer",
    "category": "esign-documents",
    "tagline": "Automated document generation for Salesforce records and data objects",
    "description": "Conga Composer generates customized quotes, contracts, and proposals automatically using data inside Salesforce. It is designed for revenue operations professionals managing sales agreements.",
    "rating": 4.4,
    "reviewsCount": 720,
    "pricing": "Paid",
    "websiteUrl": "https://conga.com/products/conga-composer",
    "affiliateUrl": "https://conga.com/products/conga-composer",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "820K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "nintex-drawloop",
    "name": "Nintex DocGen",
    "domain": "nintex.com",
    "category": "esign-documents",
    "tagline": "Automated document creation software for enterprise workflows",
    "description": "Nintex DocGen simplifies creating complex document templates and publishing PDFs directly within CRM and ERP workflows. It is built for enterprise operations teams managing compliance files.",
    "rating": 4.5,
    "reviewsCount": 480,
    "pricing": "Paid",
    "websiteUrl": "https://nintex.com",
    "affiliateUrl": "https://nintex.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "650K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "contractbook",
    "name": "Contractbook",
    "domain": "contractbook.com",
    "category": "esign-documents",
    "tagline": "Data-driven contract lifecycle management platform for modern SMBs",
    "description": "Contractbook allows businesses to draft, approve, sign, and store legal contracts on a single automated platform. It is built for growing companies, HR teams, and legal operations.",
    "rating": 4.7,
    "reviewsCount": 380,
    "pricing": "Paid",
    "websiteUrl": "https://contractbook.com",
    "affiliateUrl": "https://contractbook.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "340K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "juro",
    "name": "Juro",
    "domain": "juro.com",
    "category": "esign-documents",
    "tagline": "AI-enabled contract automation platform for fast-scaling companies",
    "description": "Juro enables legal and commercial teams to create, negotiate, sign, and manage contracts in a unified browser interface. It is optimized for scaling tech companies and legal operations.",
    "rating": 4.8,
    "reviewsCount": 410,
    "pricing": "Paid",
    "websiteUrl": "https://juro.com",
    "affiliateUrl": "https://juro.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "420K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "oneflow",
    "name": "Oneflow",
    "domain": "oneflow.com",
    "category": "esign-documents",
    "tagline": "Truly digital contract software with live editing and eSignatures",
    "description": "Oneflow replaces static PDFs with dynamic, browser-native digital contracts allowing live collaborative editing before signing. It serves modern sales, HR, and procurement departments.",
    "rating": 4.7,
    "reviewsCount": 320,
    "pricing": "Paid",
    "websiteUrl": "https://oneflow.com",
    "affiliateUrl": "https://oneflow.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "380K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "spotdraft",
    "name": "SpotDraft",
    "domain": "spotdraft.com",
    "category": "esign-documents",
    "tagline": "AI-driven contract management and legal automation workspace",
    "description": "SpotDraft accelerates contract drafting, redlining, approval routing, and tracking using automated AI insights. It is engineered for corporate in-house legal counsel and revenue teams.",
    "rating": 4.8,
    "reviewsCount": 290,
    "pricing": "Paid",
    "websiteUrl": "https://spotdraft.com",
    "affiliateUrl": "https://spotdraft.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "290K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "agiloft",
    "name": "Agiloft",
    "domain": "agiloft.com",
    "category": "esign-documents",
    "tagline": "Flexible, no-code enterprise contract lifecycle management software",
    "description": "Agiloft provides a configurable contract management platform tailored for complex procurement, sales, and legal workflows. It serves enterprise procurement leaders and legal departments.",
    "rating": 4.6,
    "reviewsCount": 510,
    "pricing": "Paid",
    "websiteUrl": "https://agiloft.com",
    "affiliateUrl": "https://agiloft.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "230K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "signable",
    "name": "Signable",
    "domain": "signable.co.uk",
    "category": "esign-documents",
    "tagline": "Straightforward electronic signature software for UK and European businesses",
    "description": "Signable simplifies sending contracts, agreements, and waivers for legally binding online electronic signatures. It is built for UK and European small businesses seeking Pay-As-You-Go signing.",
    "rating": 4.7,
    "reviewsCount": 450,
    "pricing": "Freemium",
    "websiteUrl": "https://signable.co.uk",
    "affiliateUrl": "https://signable.co.uk",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "510K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "yousign",
    "name": "Yousign",
    "domain": "yousign.com",
    "category": "esign-documents",
    "tagline": "eIDAS-compliant European electronic signature platform",
    "description": "Yousign delivers legally binding eIDAS-compliant digital signatures, document workflows, and developer APIs. It is tailored specifically for European SMBs, legal firms, and software companies.",
    "rating": 4.6,
    "reviewsCount": 680,
    "pricing": "Free Trial",
    "websiteUrl": "https://yousign.com",
    "affiliateUrl": "https://yousign.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "pdf-co",
    "name": "PDF.co",
    "domain": "pdf.co",
    "category": "esign-documents",
    "tagline": "API platform for PDF generation, data extraction, and document conversion",
    "description": "PDF.co provides REST APIs for automated PDF editing, form filling, OCR scanning, barcode reading, and digital signatures. It is built for developers and Zapier power users.",
    "rating": 4.8,
    "reviewsCount": 240,
    "pricing": "Freemium",
    "websiteUrl": "https://pdf.co",
    "affiliateUrl": "https://pdf.co",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "320K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "carbone-io",
    "name": "Carbone",
    "domain": "carbone.io",
    "category": "esign-documents",
    "tagline": "Open-source fast document generator using JSON data and templates",
    "description": "Carbone injects JSON data into LibreOffice templates to render PDF, DOCX, XLSX, and ODT documents programmatically. It is engineered for developers seeking fast server-side document generation.",
    "rating": 4.9,
    "reviewsCount": 170,
    "pricing": "Freemium",
    "websiteUrl": "https://carbone.io",
    "affiliateUrl": "https://carbone.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "180K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "craft-my-pdf",
    "name": "CraftMyPDF",
    "domain": "craftmypdf.com",
    "category": "esign-documents",
    "tagline": "Drag-and-drop PDF template builder and API generation engine",
    "description": "CraftMyPDF allows non-coders to visually design PDF templates and render them automatically via REST API or Zapier. It serves no-code builders and startups producing automated invoices and contracts.",
    "rating": 4.8,
    "reviewsCount": 130,
    "pricing": "Freemium",
    "websiteUrl": "https://craftmypdf.com",
    "affiliateUrl": "https://craftmypdf.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "140K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "plumsail-documents",
    "name": "Plumsail Documents",
    "domain": "plumsail.com/documents",
    "category": "esign-documents",
    "tagline": "Document generation and delivery platform for Microsoft 365 and web",
    "description": "Plumsail Documents creates PDF, Word, and Excel files automatically from templates triggered by Power Automate or web forms. It is tailored for Microsoft 365 enterprise environment users.",
    "rating": 4.6,
    "reviewsCount": 190,
    "pricing": "Free Trial",
    "websiteUrl": "https://plumsail.com/documents",
    "affiliateUrl": "https://plumsail.com/documents",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "210K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "gotenberg",
    "name": "Gotenberg",
    "domain": "gotenberg.dev",
    "category": "esign-documents",
    "tagline": "Open-source Docker-powered API for converting HTML, Markdown, and Office docs to PDF",
    "description": "Gotenberg is an open-source Docker microservice that converts web pages, Office documents, and Markdown files to PDF using Chromium and LibreOffice. It is built for backend software engineers.",
    "rating": 4.9,
    "reviewsCount": 280,
    "pricing": "Free",
    "websiteUrl": "https://gotenberg.dev",
    "affiliateUrl": "https://gotenberg.dev",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "160K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "stirling-pdf",
    "name": "Stirling-PDF",
    "domain": "stirlingtools.com",
    "category": "esign-documents",
    "tagline": "Robust, locally hosted open-source web-based PDF manipulation tool",
    "description": "Stirling-PDF provides a powerful self-hosted web interface to split, merge, convert, edit, and sign PDF files without cloud third parties. It is built for privacy-focused developers and IT admins.",
    "rating": 4.9,
    "reviewsCount": 510,
    "pricing": "Free",
    "websiteUrl": "https://stirlingtools.com",
    "affiliateUrl": "https://stirlingtools.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "480K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "revv-so",
    "name": "Revv",
    "domain": "revv.so",
    "category": "esign-documents",
    "tagline": "Document automation, business contract templates, and electronic signatures",
    "description": "Revv provides vetted legal contract templates, interactive document review, and legally binding eSignatures in one workspace. It serves freelancers, consultants, and SMB founders.",
    "rating": 4.6,
    "reviewsCount": 220,
    "pricing": "Freemium",
    "websiteUrl": "https://revv.so",
    "affiliateUrl": "https://revv.so",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "150K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "digisigner",
    "name": "DigiSigner",
    "domain": "digisigner.com",
    "category": "esign-documents",
    "tagline": "Fast, simple, and affordable online electronic signature service",
    "description": "DigiSigner lets users quickly upload, sign, and send documents for legally binding electronic signatures online. It is designed for small business owners, landlords, and independent workers.",
    "rating": 4.5,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://digisigner.com",
    "affiliateUrl": "https://digisigner.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "420K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "docsketch",
    "name": "Docsketch",
    "domain": "docsketch.com",
    "category": "esign-documents",
    "tagline": "Legally binding eSignatures and online document approval tool",
    "description": "Docsketch offers intuitive document signing, approval tracking, and reusable template links for quick client sign-offs. It serves freelancers, agency owners, and sales professionals.",
    "rating": 4.6,
    "reviewsCount": 310,
    "pricing": "Freemium",
    "websiteUrl": "https://docsketch.com",
    "affiliateUrl": "https://docsketch.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "290K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "pdf-escape",
    "name": "PDFescape",
    "domain": "pdfescape.com",
    "category": "esign-documents",
    "tagline": "Free online PDF reader, editor, form filler, and form designer",
    "description": "PDFescape enables users to edit PDF documents, fill out forms, insert annotations, and design custom PDF forms in browser. It serves individual web users needing fast PDF edits.",
    "rating": 4.3,
    "reviewsCount": 1850,
    "pricing": "Freemium",
    "websiteUrl": "https://pdfescape.com",
    "affiliateUrl": "https://pdfescape.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "pdf-gear",
    "name": "PDFgear",
    "domain": "pdfgear.com",
    "category": "esign-documents",
    "tagline": "Completely free PDF editor with integrated AI copilot reading assistant",
    "description": "PDFgear offers free desktop and mobile PDF editing, page extraction, conversion, and AI document chat capabilities. It is built for students, researchers, and office workers seeking free PDF tools.",
    "rating": 4.9,
    "reviewsCount": 1200,
    "pricing": "Free",
    "websiteUrl": "https://pdfgear.com",
    "affiliateUrl": "https://pdfgear.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "3.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "open-sign",
    "name": "OpenSign",
    "domain": "opensignlabs.com",
    "category": "esign-documents",
    "tagline": "Free open-source document signing software platform for developers",
    "description": "OpenSign provides an open-source eSignature platform featuring document creation, signing fields, REST APIs, and custom deployment options. It serves developers and privacy-first teams.",
    "rating": 4.8,
    "reviewsCount": 190,
    "pricing": "Freemium",
    "websiteUrl": "https://opensignlabs.com",
    "affiliateUrl": "https://opensignlabs.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "120K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "foxit-esign",
    "name": "Foxit eSign",
    "domain": "foxit.com/esign",
    "category": "esign-documents",
    "tagline": "Legally binding eSignature service integrated into Foxit Document Cloud",
    "description": "Foxit eSign enables users to prepare, send, track, and manage e-signatures securely across desktop and mobile devices. It serves business teams using Foxit PDF Editor.",
    "rating": 4.6,
    "reviewsCount": 420,
    "pricing": "Paid",
    "websiteUrl": "https://foxit.com/esign",
    "affiliateUrl": "https://foxit.com/esign",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "pdf-filler",
    "name": "pdfFiller by airSlate",
    "domain": "pdffiller.com",
    "category": "esign-documents",
    "tagline": "Comprehensive cloud PDF editor, form builder, and eSignature manager",
    "description": "pdfFiller transforms static documents into editable, signable online PDF forms directly within any web browser. It serves small-to-medium business operations, legal admins, and educators.",
    "rating": 4.5,
    "reviewsCount": 3400,
    "pricing": "Paid",
    "websiteUrl": "https://pdffiller.com",
    "affiliateUrl": "https://pdffiller.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "11.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "dochub",
    "name": "DocHub",
    "domain": "dochub.com",
    "category": "esign-documents",
    "tagline": "Online PDF editor and document signing tool integrated with Google Workspace",
    "description": "DocHub allows users to edit PDF text, annotate documents, construct web forms, and collect electronic signatures natively in Google Drive. It is widely used by schools, freelancers, and SMBs.",
    "rating": 4.6,
    "reviewsCount": 2100,
    "pricing": "Freemium",
    "websiteUrl": "https://dochub.com",
    "affiliateUrl": "https://dochub.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "8.2M",
    "isFreeTier": true,
    "isOpenSource": false
  }
];

const saasDataPath = path.join(__dirname, '..', 'src', 'data', 'saasData.jsx');
let content = fs.readFileSync(saasDataPath, 'utf8');

const match = content.match(/export const staticSaasTools = (\[[\s\S]*?\n\]);/);
if (!match) {
  console.error('Could not find staticSaasTools in saasData.jsx');
  process.exit(1);
}

let existingTools = JSON.parse(match[1]);

const existingIds = new Set(existingTools.map(t => t.id.toLowerCase()));
const existingNames = new Set(existingTools.map(t => t.name.toLowerCase()));

let addedCount = 0;
let skippedCount = 0;

newTools.forEach(tool => {
  const normId = tool.id.toLowerCase();
  const normName = tool.name.toLowerCase();

  if (!existingIds.has(normId) && !existingNames.has(normName)) {
    existingTools.push(tool);
    existingIds.add(normId);
    existingNames.add(normName);
    addedCount++;
  } else {
    // Enrich existing tool without creating a duplicate
    const idx = existingTools.findIndex(t => t.id.toLowerCase() === normId || t.name.toLowerCase() === normName);
    if (idx !== -1) {
      existingTools[idx] = { ...existingTools[idx], category: tool.category, tagline: tool.tagline || existingTools[idx].tagline };
    }
    skippedCount++;
  }
});

const updatedArrayStr = JSON.stringify(existingTools, null, 2);
content = content.replace(/export const staticSaasTools = \[[\s\S]*?\n\];/, `export const staticSaasTools = ${updatedArrayStr};`);

fs.writeFileSync(saasDataPath, content, 'utf8');
console.log(`Ingestion Complete! Added: ${addedCount} brand new tools | Deduplicated: ${skippedCount} existing tools | Total static tools: ${existingTools.length}`);
