const fs = require('fs');
const path = require('path');

const newTools = [
  {
    "id": "suno",
    "name": "Suno",
    "domain": "suno.com",
    "category": "ai-music-audio",
    "tagline": "Generative AI music engine turning text prompts into full studio tracks",
    "description": "Suno generates complete songs with realistic vocals, multi-instrumental arrangements, and custom lyrics from simple text descriptions. It allows content creators, songwriters, and hobbyists to compose full-length tracks across any genre without requiring prior musical experience.",
    "rating": 4.8,
    "reviewsCount": 1450,
    "pricing": "Freemium",
    "websiteUrl": "https://suno.com",
    "affiliateUrl": "https://suno.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "18.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "udio",
    "name": "Udio",
    "domain": "udio.com",
    "category": "ai-music-audio",
    "tagline": "High-fidelity AI song generation and musical arrangement platform",
    "description": "Udio produces high-fidelity tracks across genres with granular control over lyrics, audio extensions, and musical style tags. It is designed for music producers, video creators, and songwriters seeking professional-grade audio synthesis.",
    "rating": 4.7,
    "reviewsCount": 920,
    "pricing": "Freemium",
    "websiteUrl": "https://udio.com",
    "affiliateUrl": "https://udio.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "9.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "elevenlabs",
    "name": "ElevenLabs",
    "domain": "elevenlabs.io",
    "category": "ai-music-audio",
    "tagline": "Hyper-realistic AI voice generator, voice cloning, and text-to-speech studio",
    "description": "ElevenLabs delivers emotionally expressive speech synthesis, real-time voice cloning, and AI sound effect generation in dozens of languages. It is widely adopted by audiobook publishers, video game studios, and content creators.",
    "rating": 4.9,
    "reviewsCount": 2400,
    "pricing": "Freemium",
    "websiteUrl": "https://elevenlabs.io",
    "affiliateUrl": "https://elevenlabs.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "22.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "descript",
    "name": "Descript",
    "domain": "descript.com",
    "category": "ai-music-audio",
    "tagline": "Text-based audio and video editor with voice cloning and studio cleanup",
    "description": "Descript automatically transcribes spoken audio, letting users edit recorded tracks simply by editing text transcripts. It features automatic filler-word removal, AI noise reduction, and personalized voice synthesis.",
    "rating": 4.8,
    "reviewsCount": 1650,
    "pricing": "Freemium",
    "websiteUrl": "https://descript.com",
    "affiliateUrl": "https://descript.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "6.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "whisper-openai",
    "name": "Whisper by OpenAI",
    "domain": "github.com/openai/whisper",
    "category": "ai-music-audio",
    "tagline": "Open-source automatic speech recognition and multi-lingual transcription model",
    "description": "Whisper is an open-source neural network trained on vast speech datasets for accurate multilingual speech recognition, translation, and language identification. It is the core speech-to-text engine powering modern audio application pipelines.",
    "rating": 4.9,
    "reviewsCount": 3100,
    "pricing": "Free",
    "websiteUrl": "https://github.com/openai/whisper",
    "affiliateUrl": "https://github.com/openai/whisper",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "4.5M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "soundraw",
    "name": "Soundraw",
    "domain": "soundraw.io",
    "category": "ai-music-audio",
    "tagline": "Customizable AI background music generator for content creators",
    "description": "Soundraw allows creators to generate royalty-free background music and customize intro length, chorus timing, and tempo. It serves YouTubers, podcasters, and filmmakers needing tailored soundtracks.",
    "rating": 4.6,
    "reviewsCount": 510,
    "pricing": "Freemium",
    "websiteUrl": "https://soundraw.io",
    "affiliateUrl": "https://soundraw.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "lalal-ai",
    "name": "LALAL.AI",
    "domain": "lalal.ai",
    "category": "ai-music-audio",
    "tagline": "High-precision AI vocal remover and music stem splitter",
    "description": "LALAL.AI utilizes neural network algorithms to extract vocal tracks, drums, bass, guitar, and piano from mixed audio files. It is built for DJs, music producers, and audio engineers needing clean stem isolation.",
    "rating": 4.8,
    "reviewsCount": 780,
    "pricing": "Freemium",
    "websiteUrl": "https://lalal.ai",
    "affiliateUrl": "https://lalal.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "play-ht",
    "name": "PlayHT",
    "domain": "play.ht",
    "category": "ai-music-audio",
    "tagline": "Conversational AI voice synthesis and real-time voice cloning platform",
    "description": "PlayHT generates ultra-realistic text-to-speech audio and real-time voice clones for narrative media and conversational AI agents. It serves enterprise platforms, e-learning creators, and podcasters.",
    "rating": 4.6,
    "reviewsCount": 620,
    "pricing": "Freemium",
    "websiteUrl": "https://play.ht",
    "affiliateUrl": "https://play.ht",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "murf-ai",
    "name": "Murf AI",
    "domain": "murf.ai",
    "category": "ai-music-audio",
    "tagline": "Versatile AI voiceover studio for presentations and video narration",
    "description": "Murf AI converts plain text into natural-sounding voiceovers for e-learning modules, corporate presentations, and advertising clips. It features precise timing controls, pitch adjustments, and background track layering.",
    "rating": 4.7,
    "reviewsCount": 890,
    "pricing": "Freemium",
    "websiteUrl": "https://murf.ai",
    "affiliateUrl": "https://murf.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "krisp",
    "name": "Krisp",
    "domain": "krisp.ai",
    "category": "ai-music-audio",
    "tagline": "AI noise cancellation, accent localization, and real-time call cleanup",
    "description": "Krisp runs locally on desktop hardware to eliminate background voices, room echo, and noise during live online calls. It is designed for call center agents, remote professionals, and podcasters.",
    "rating": 4.8,
    "reviewsCount": 1120,
    "pricing": "Freemium",
    "websiteUrl": "https://krisp.ai",
    "affiliateUrl": "https://krisp.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "adobe-podcast",
    "name": "Adobe Podcast",
    "domain": "podcast.adobe.com",
    "category": "ai-music-audio",
    "tagline": "AI-powered web audio recording, speech enhancement, and transcript editing",
    "description": "Adobe Podcast offers AI speech enhancement tools that eliminate background noise and optimize mic frequencies to match studio quality. It provides browser-based multi-track recording and transcript-based editing.",
    "rating": 4.7,
    "reviewsCount": 950,
    "pricing": "Freemium",
    "websiteUrl": "https://podcast.adobe.com",
    "affiliateUrl": "https://podcast.adobe.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "moises-ai",
    "name": "Moises.ai",
    "domain": "moises.ai",
    "category": "ai-music-audio",
    "tagline": "The ultimate AI app for musicians, stem isolation, and practice tools",
    "description": "Moises allows musicians to isolate instruments, detect track key and tempo, and slow down audio without pitch distortion. Its mobile and desktop apps assist band practice, vocal training, and music education.",
    "rating": 4.8,
    "reviewsCount": 2100,
    "pricing": "Freemium",
    "websiteUrl": "https://moises.ai",
    "affiliateUrl": "https://moises.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "mubert",
    "name": "Mubert",
    "domain": "mubert.com",
    "category": "ai-music-audio",
    "tagline": "Real-time AI generative audio for content creators, apps, and streams",
    "description": "Mubert generates real-time streaming AI soundtracks for video channels, podcasts, and mobile applications. It offers a REST API for software developers alongside a web studio interface for content creators.",
    "rating": 4.5,
    "reviewsCount": 420,
    "pricing": "Freemium",
    "websiteUrl": "https://mubert.com",
    "affiliateUrl": "https://mubert.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "boomy",
    "name": "Boomy",
    "domain": "boomy.com",
    "category": "ai-music-audio",
    "tagline": "Create original songs in seconds and publish to streaming networks",
    "description": "Boomy enables users with no musical training to generate complete songs using generative algorithms in seconds. Users can release their AI tracks directly to streaming platforms like Spotify and Apple Music.",
    "rating": 4.4,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://boomy.com",
    "affiliateUrl": "https://boomy.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "850K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "speechify",
    "name": "Speechify",
    "domain": "speechify.com",
    "category": "ai-music-audio",
    "tagline": "AI text-to-speech reader for web pages, PDFs, and ebooks",
    "description": "Speechify reads written text out loud using fluid AI voice engines across desktop and mobile devices. It is widely used by dyslexic readers, students, and professionals to consume documents faster.",
    "rating": 4.8,
    "reviewsCount": 1850,
    "pricing": "Freemium",
    "websiteUrl": "https://speechify.com",
    "affiliateUrl": "https://speechify.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "8.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "kits-ai",
    "name": "Kits AI",
    "domain": "kits.ai",
    "category": "ai-music-audio",
    "tagline": "AI voice platform designed for vocal conversion and music production",
    "description": "Kits AI provides royalty-free AI voice models, vocal conversion engines, and custom model training for music producers. It enables artists to generate studio-grade vocal takes without hiring session singers.",
    "rating": 4.7,
    "reviewsCount": 490,
    "pricing": "Freemium",
    "websiteUrl": "https://kits.ai",
    "affiliateUrl": "https://kits.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.3M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "aiva",
    "name": "AIVA",
    "domain": "aiva.ai",
    "category": "ai-music-audio",
    "tagline": "AI soundtrack composer for films, video games, and commercials",
    "description": "AIVA composes classical, cinematic, and electronic music scores based on predefined style profiles. It provides full MIDI and audio export options for music directors, game developers, and media composers.",
    "rating": 4.6,
    "reviewsCount": 350,
    "pricing": "Freemium",
    "websiteUrl": "https://aiva.ai",
    "affiliateUrl": "https://aiva.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "landr",
    "name": "LANDR",
    "domain": "landr.com",
    "category": "ai-music-audio",
    "tagline": "Automated AI music mastering, distribution, and plugin suite",
    "description": "LANDR provides automated AI music mastering that analyzes audio tracks and applies custom EQ and dynamic compression. It also offers digital music distribution, plugins, and sample libraries for independent artists.",
    "rating": 4.7,
    "reviewsCount": 1100,
    "pricing": "Freemium",
    "websiteUrl": "https://landr.com",
    "affiliateUrl": "https://landr.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "stable-audio",
    "name": "Stable Audio",
    "domain": "stableaudio.com",
    "category": "ai-music-audio",
    "tagline": "Generative AI music and sound effect creator by Stability AI",
    "description": "Stable Audio produces high-quality multi-track audio and sound effects from text descriptions. Built on audio diffusion models, it generates royalty-free sound clips for media designers and music producers.",
    "rating": 4.7,
    "reviewsCount": 720,
    "pricing": "Freemium",
    "websiteUrl": "https://stableaudio.com",
    "affiliateUrl": "https://stableaudio.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "izotope-ozone",
    "name": "iZotope Ozone",
    "domain": "izotope.com",
    "category": "ai-music-audio",
    "tagline": "Industry-standard AI-assisted audio mastering plugin suite",
    "description": "iZotope Ozone utilizes an intelligent Master Assistant engine to suggest optimal EQ profiles, dynamic balance, and commercial loudness targets. It is an industry standard across recording studios worldwide.",
    "rating": 4.9,
    "reviewsCount": 1350,
    "pricing": "Paid",
    "websiteUrl": "https://izotope.com",
    "affiliateUrl": "https://izotope.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.7M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "rvc-beta",
    "name": "Retrieval-based Voice Conversion (RVC)",
    "domain": "github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI",
    "category": "ai-music-audio",
    "tagline": "Fast, open-source real-time voice conversion framework",
    "description": "RVC is an open-source web UI framework that trains custom voice models rapidly with minimal audio data. It supports real-time singing and speaking voice transformations locally on desktop GPUs.",
    "rating": 4.8,
    "reviewsCount": 980,
    "pricing": "Free",
    "websiteUrl": "https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI",
    "affiliateUrl": "https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "deepgram",
    "name": "Deepgram",
    "domain": "deepgram.com",
    "category": "ai-music-audio",
    "tagline": "Ultra-fast speech-to-text API for real-time meeting transcription and voice AI",
    "description": "Deepgram delivers low-latency speech-to-text APIs with high accuracy and speaker diarization. It is engineered for developers building AI voice agents, live captioning, and conversational intelligence tools.",
    "rating": 4.8,
    "reviewsCount": 410,
    "pricing": "Freemium",
    "websiteUrl": "https://deepgram.com",
    "affiliateUrl": "https://deepgram.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "950K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "assembly-ai",
    "name": "AssemblyAI",
    "domain": "assemblyai.com",
    "category": "ai-music-audio",
    "tagline": "Production-ready Speech AI models for transcription and audio intelligence",
    "description": "AssemblyAI provides APIs for speech-to-text, speaker identification, sentiment detection, and automated topic summarization. It is tailored for software engineering teams processing high-volume voice data.",
    "rating": 4.8,
    "reviewsCount": 540,
    "pricing": "Freemium",
    "websiteUrl": "https://assemblyai.com",
    "affiliateUrl": "https://assemblyai.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "gladia",
    "name": "Gladia",
    "domain": "gladia.io",
    "category": "ai-music-audio",
    "tagline": "Real-time speech-to-text and audio intelligence engine API",
    "description": "Gladia delivers ultra-fast multi-lingual transcription, speaker separation, and real-time audio translation APIs. It is built for meeting platform developers, call analytics software, and live translators.",
    "rating": 4.7,
    "reviewsCount": 210,
    "pricing": "Freemium",
    "websiteUrl": "https://gladia.io",
    "affiliateUrl": "https://gladia.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "320K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "sonix-ai",
    "name": "Sonix",
    "domain": "sonix.ai",
    "category": "ai-music-audio",
    "tagline": "Automated audio transcription, translation, and speech-to-text platform",
    "description": "Sonix uses speech recognition models to transcribe audio files, generate video captions, and translate transcripts across 40+ languages. It serves journalists, podcasters, and media production companies.",
    "rating": 4.7,
    "reviewsCount": 610,
    "pricing": "Free Trial",
    "websiteUrl": "https://sonix.ai",
    "affiliateUrl": "https://sonix.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "notta-ai",
    "name": "Notta",
    "domain": "notta.ai",
    "category": "ai-music-audio",
    "tagline": "Voice-to-text AI transcription and live meeting notes platform",
    "description": "Notta converts live web meetings, voice memos, and audio files into searchable text transcripts with automated summaries. It is designed for researchers, executive assistants, and sales reps.",
    "rating": 4.7,
    "reviewsCount": 780,
    "pricing": "Freemium",
    "websiteUrl": "https://notta.ai",
    "affiliateUrl": "https://notta.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.9M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "cleanvoice-ai",
    "name": "Cleanvoice AI",
    "domain": "cleanvoice.ai",
    "category": "ai-music-audio",
    "tagline": "Automated podcast editing tool removing filler words, stutters, and dead air",
    "description": "Cleanvoice AI automatically detects and removes hesitation sounds, lip smacks, stuttering, and awkward pauses from recorded tracks. It saves podcast editors hours of manual cutting.",
    "rating": 4.7,
    "reviewsCount": 320,
    "pricing": "Free Trial",
    "websiteUrl": "https://cleanvoice.ai",
    "affiliateUrl": "https://cleanvoice.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "420K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "auphonic",
    "name": "Auphonic",
    "domain": "auphonic.com",
    "category": "ai-music-audio",
    "tagline": "Automated AI audio mastering and volume leveling tool for podcasters",
    "description": "Auphonic handles loudness normalization, background noise reduction, and automatic levelling for spoken audio files. It is an industry staple for podcasters, radio broadcasters, and audiobook producers.",
    "rating": 4.7,
    "reviewsCount": 390,
    "pricing": "Freemium",
    "websiteUrl": "https://auphonic.com",
    "affiliateUrl": "https://auphonic.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "voicemod",
    "name": "Voicemod",
    "domain": "voicemod.net",
    "category": "ai-music-audio",
    "tagline": "Real-time AI voice modifier and soundboard for desktop communication",
    "description": "Voicemod modifies live mic input with custom AI voice filters, pitch shifts, and soundboard effects. It integrates into Discord, OBS, Twitch, and multiplayer desktop games.",
    "rating": 4.7,
    "reviewsCount": 1250,
    "pricing": "Freemium",
    "websiteUrl": "https://voicemod.net",
    "affiliateUrl": "https://voicemod.net",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "6.7M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "voice-ai",
    "name": "Voice.ai",
    "domain": "voice.ai",
    "category": "ai-music-audio",
    "tagline": "Real-time voice changing software powered by deep learning models",
    "description": "Voice.ai transforms spoken input in real time using custom user-trained voice profiles. Gamers, streamers, and VTubers use it to alter their voice identity during live broadcasts.",
    "rating": 4.4,
    "reviewsCount": 540,
    "pricing": "Freemium",
    "websiteUrl": "https://voice.ai",
    "affiliateUrl": "https://voice.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.9M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "lovo-ai",
    "name": "Lovo.ai",
    "domain": "lovo.ai",
    "category": "ai-music-audio",
    "tagline": "AI voice generator and text-to-speech video studio platform",
    "description": "Lovo.ai generates expressive AI voiceovers with emotional controls and fine-tuned pitch adjustments for marketing collateral. Its Genny studio pairs voice synthesis directly with video editing.",
    "rating": 4.6,
    "reviewsCount": 480,
    "pricing": "Freemium",
    "websiteUrl": "https://lovo.ai",
    "affiliateUrl": "https://lovo.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "respeecher",
    "name": "Respeecher",
    "domain": "respeecher.com",
    "category": "ai-music-audio",
    "tagline": "Hollywood-grade AI voice cloning for film, TV, and game production",
    "description": "Respeecher allows voice actors to sound like specific historical figures or younger versions of themselves using high-precision cloning. It is utilized by major film studios and AAA game developers.",
    "rating": 4.8,
    "reviewsCount": 190,
    "pricing": "Paid",
    "websiteUrl": "https://respeecher.com",
    "affiliateUrl": "https://respeecher.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "180K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "beatoven-ai",
    "name": "Beatoven.ai",
    "domain": "beatoven.ai",
    "category": "ai-music-audio",
    "tagline": "Royalty-free mood-based background music composer for video creators",
    "description": "Beatoven.ai uses AI composition techniques to build mood-based background soundtracks for digital content. It helps creators adapt song structures to match video cuts and emotional shifts.",
    "rating": 4.5,
    "reviewsCount": 260,
    "pricing": "Freemium",
    "websiteUrl": "https://beatoven.ai",
    "affiliateUrl": "https://beatoven.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "510K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "soundful",
    "name": "Soundful",
    "domain": "soundful.com",
    "category": "ai-music-audio",
    "tagline": "AI royalty-free background music generator for streaming and brands",
    "description": "Soundful generates unique royalty-free background tracks for videos, live streams, and podcasts. Users can adjust BPM, scale key, and instrument layers to customize song outputs.",
    "rating": 4.6,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://soundful.com",
    "affiliateUrl": "https://soundful.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "820K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "musicfy",
    "name": "Musicfy",
    "domain": "musicfy.lol",
    "category": "ai-music-audio",
    "tagline": "Create custom AI voice models and transform vocal tracks instantly",
    "description": "Musicfy enables users to clone voices or select pre-trained AI vocalists to render sung tracks from audio or text inputs. It features text-to-music generation alongside stem extraction.",
    "rating": 4.5,
    "reviewsCount": 340,
    "pricing": "Freemium",
    "websiteUrl": "https://musicfy.lol",
    "affiliateUrl": "https://musicfy.lol",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "950K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "vocal-remover",
    "name": "VocalRemover.media",
    "domain": "vocalremover.media",
    "category": "ai-music-audio",
    "tagline": "Free browser-based AI vocal remover and karaoke track converter",
    "description": "VocalRemover isolates singing voices from backing music directly in web browsers using AI algorithms. It includes bonus utilities like pitch transposition, BPM estimation, and audio trimming.",
    "rating": 4.6,
    "reviewsCount": 810,
    "pricing": "Free",
    "websiteUrl": "https://vocalremover.media",
    "affiliateUrl": "https://vocalremover.media",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "5.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "ripx-daw",
    "name": "RipX DAW",
    "domain": "hit-shaper.com",
    "category": "ai-music-audio",
    "tagline": "AI-powered stem separation DAW for audio editing and remixing",
    "description": "RipX separates mixed audio files into fully editable notes, vocal melodies, and instrument stems inside a visual DAW interface. It empowers music producers and remixers to isolate and manipulate audio elements.",
    "rating": 4.6,
    "reviewsCount": 210,
    "pricing": "Free Trial",
    "websiteUrl": "https://hit-shaper.com",
    "affiliateUrl": "https://hit-shaper.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "230K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "audiocraft",
    "name": "AudioCraft (Meta)",
    "domain": "github.com/facebookresearch/audiocraft",
    "category": "ai-music-audio",
    "tagline": "Meta's open-source generative AI framework for music and sound synthesis",
    "description": "AudioCraft is an open-source generative library containing PyTorch models like MusicGen and AudioGen for text-to-music generation. It enables developers and audio researchers to run sound generation locally.",
    "rating": 4.8,
    "reviewsCount": 620,
    "pricing": "Free",
    "websiteUrl": "https://github.com/facebookresearch/audiocraft",
    "affiliateUrl": "https://github.com/facebookresearch/audiocraft",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "wavtool",
    "name": "WavTool",
    "domain": "wavtool.com",
    "category": "ai-music-audio",
    "tagline": "Browser-based DAW with integrated AI assistant for music production",
    "description": "WavTool is a complete web-based digital audio workstation equipped with an integrated AI assistant named Conductor. It helps producers generate MIDI melodies, synthesize instruments, and edit audio tracks.",
    "rating": 4.6,
    "reviewsCount": 280,
    "pricing": "Freemium",
    "websiteUrl": "https://wavtool.com",
    "affiliateUrl": "https://wavtool.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "340K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "podcastle",
    "name": "Podcastle",
    "domain": "podcastle.ai",
    "category": "ai-music-audio",
    "tagline": "All-in-one AI recording, editing, and voice cloning platform for podcasters",
    "description": "Podcastle provides multi-track remote recording, automated voice cloning, and AI speech enhancement in a clean browser studio. It serves podcasters, educators, and audio storytellers.",
    "rating": 4.8,
    "reviewsCount": 740,
    "pricing": "Freemium",
    "websiteUrl": "https://podcastle.ai",
    "affiliateUrl": "https://podcastle.ai",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "2.7M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "voicemaker",
    "name": "Voicemaker",
    "domain": "voicemaker.in",
    "category": "ai-music-audio",
    "tagline": "Web-based AI text-to-speech converter supporting granular SSML controls",
    "description": "Voicemaker generates natural MP3 speech files from text with SSML tags, pitch modulation, and speed adjustments. It is popular for advertisement voiceovers, YouTube videos, and audiobooks.",
    "rating": 4.5,
    "reviewsCount": 490,
    "pricing": "Freemium",
    "websiteUrl": "https://voicemaker.in",
    "affiliateUrl": "https://voicemaker.in",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "audiostrip",
    "name": "AudioStrip",
    "domain": "audiostrip.com",
    "category": "ai-music-audio",
    "tagline": "Fast online AI vocal isolation and instrumental stem extractor",
    "description": "AudioStrip allows music producers to separate vocals from backing tracks quickly using deep learning models. It provides clean stem exports for bootlegs, mashups, and rehearsal tracks.",
    "rating": 4.5,
    "reviewsCount": 310,
    "pricing": "Freemium",
    "websiteUrl": "https://audiostrip.com",
    "affiliateUrl": "https://audiostrip.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "580K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "rask-ai",
    "name": "Rask AI",
    "domain": "rask.ai",
    "category": "ai-music-audio",
    "tagline": "AI audio dubbing, voice cloning, and multi-speaker video translation",
    "description": "Rask AI translates spoken video and audio into 130+ languages while matching the original speaker's vocal tone and rhythm. It is built for content creators, global educators, and marketing agencies.",
    "rating": 4.7,
    "reviewsCount": 680,
    "pricing": "Paid",
    "websiteUrl": "https://rask.ai",
    "affiliateUrl": "https://rask.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "trint",
    "name": "Trint",
    "domain": "trint.com",
    "category": "ai-music-audio",
    "tagline": "AI speech-to-text platform designed for newsrooms and media storytellers",
    "description": "Trint converts recorded speech into editable, searchable text, enabling journalists and video producers to craft soundbites quickly. It features multi-user collaborative editing and team approval workflows.",
    "rating": 4.5,
    "reviewsCount": 510,
    "pricing": "Paid",
    "websiteUrl": "https://trint.com",
    "affiliateUrl": "https://trint.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "890K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "happy-scribe",
    "name": "Happy Scribe",
    "domain": "happyscribe.com",
    "category": "ai-music-audio",
    "tagline": "Audio transcription and subtitle generator platform",
    "description": "Happy Scribe combines fast machine AI transcription with optional human proofreading for interviews and video captions. It serves academics, journalists, and video production teams.",
    "rating": 4.6,
    "reviewsCount": 850,
    "pricing": "Freemium",
    "websiteUrl": "https://happyscribe.com",
    "affiliateUrl": "https://happyscribe.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "emastered",
    "name": "eMastered",
    "domain": "emastered.com",
    "category": "ai-music-audio",
    "tagline": "Instant online AI audio mastering engine created by Grammy-winning engineers",
    "description": "eMastered leverages machine learning to master audio tracks automatically in a web browser within seconds. Producers can upload reference tracks to achieve target commercial loudness and frequency balance.",
    "rating": 4.5,
    "reviewsCount": 450,
    "pricing": "Free Trial",
    "websiteUrl": "https://emastered.com",
    "affiliateUrl": "https://emastered.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "650K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "so-vits-svc",
    "name": "So-VITS-SVC",
    "domain": "github.com/svc-develop-team/so-vits-svc",
    "category": "ai-music-audio",
    "tagline": "Open-source singing voice conversion neural network framework",
    "description": "So-VITS-SVC is an open-source deep learning framework designed to convert singing voice audio into target trained vocal timbres. It is popular across music research communities and specialized audio development.",
    "rating": 4.7,
    "reviewsCount": 520,
    "pricing": "Free",
    "websiteUrl": "https://github.com/svc-develop-team/so-vits-svc",
    "affiliateUrl": "https://github.com/svc-develop-team/so-vits-svc",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "820K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "matchering",
    "name": "Matchering",
    "domain": "github.com/sergree/matchering",
    "category": "ai-music-audio",
    "tagline": "Open-source reference-based AI audio mastering container",
    "description": "Matchering is an open-source audio processing framework that matches a target track's tone and RMS balance to a reference file. It provides automated mastering for independent developers and audio engineers.",
    "rating": 4.7,
    "reviewsCount": 240,
    "pricing": "Free",
    "websiteUrl": "https://github.com/sergree/matchering",
    "affiliateUrl": "https://github.com/sergree/matchering",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "190K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "audiobox-meta",
    "name": "Audiobox (Meta)",
    "domain": "audiobox.metademolab.com",
    "category": "ai-music-audio",
    "tagline": "Meta's generative AI model for custom audio synthesis and voice prompts",
    "description": "Audiobox generates custom voice clips, sound effects, and musical textures using combined text and voice inputs. It advances research in multi-modal generative audio creation.",
    "rating": 4.8,
    "reviewsCount": 420,
    "pricing": "Free",
    "websiteUrl": "https://audiobox.metademolab.com",
    "affiliateUrl": "https://audiobox.metademolab.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "voicefixer",
    "name": "VoiceFixer",
    "domain": "github.com/haoheliu/voicefixer",
    "category": "ai-music-audio",
    "tagline": "Open-source neural network for restoring degraded speech audio",
    "description": "VoiceFixer is an open-source deep learning framework that restores corrupted, clipped, or low-quality speech audio files. It recovers missing frequency bands and suppresses background noise automatically.",
    "rating": 4.6,
    "reviewsCount": 170,
    "pricing": "Free",
    "websiteUrl": "https://github.com/haoheliu/voicefixer",
    "affiliateUrl": "https://github.com/haoheliu/voicefixer",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "110K",
    "isFreeTier": true,
    "isOpenSource": true
  }
];

const saasDataPath = path.join(__dirname, '..', 'src', 'data', 'saasData.jsx');
let content = fs.readFileSync(saasDataPath, 'utf8');

const match = content.match(/export const staticSaasTools = (\[[\s\S]*?\n\]);/);
if (!match) {
  console.error('Could not find staticSaasTools in saasData.jsx');
  process.exit(1);
}

let existingTools = JSON.parse(match[1]);

const existingIds = new Set(existingTools.map(t => t.id.toLowerCase()));
const existingNames = new Set(existingTools.map(t => t.name.toLowerCase()));

let addedCount = 0;
let skippedCount = 0;

newTools.forEach(tool => {
  const normId = tool.id.toLowerCase();
  const normName = tool.name.toLowerCase();

  if (!existingIds.has(normId) && !existingNames.has(normName)) {
    existingTools.push(tool);
    existingIds.add(normId);
    existingNames.add(normName);
    addedCount++;
  } else {
    // Enrich existing tool without creating a duplicate
    const idx = existingTools.findIndex(t => t.id.toLowerCase() === normId || t.name.toLowerCase() === normName);
    if (idx !== -1) {
      existingTools[idx] = { ...existingTools[idx], category: tool.category, tagline: tool.tagline || existingTools[idx].tagline };
    }
    skippedCount++;
  }
});

const updatedArrayStr = JSON.stringify(existingTools, null, 2);
content = content.replace(/export const staticSaasTools = \[[\s\S]*?\n\];/, `export const staticSaasTools = ${updatedArrayStr};`);

fs.writeFileSync(saasDataPath, content, 'utf8');
console.log(`Ingestion Complete! Added: ${addedCount} brand new tools | Deduplicated: ${skippedCount} existing tools | Total static tools: ${existingTools.length}`);
