const fs = require('fs');
const path = require('path');

const inputTools = [
  {
    "id": "clickhouse",
    "name": "ClickHouse",
    "domain": "clickhouse.com",
    "category": "db-vector-search",
    "tagline": "Ultra-fast open-source columnar database for real-time analytics and vector search",
    "description": "ClickHouse delivers real-time analytical query performance over billions of rows using columnar database storage and vector indexes. It is built for data platform engineers, security leads, and high-scale SaaS developers.",
    "rating": 4.9,
    "reviewsCount": 1150,
    "pricing": "Freemium",
    "websiteUrl": "https://clickhouse.com",
    "affiliateUrl": "https://clickhouse.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "duckdb",
    "name": "DuckDB",
    "domain": "duckdb.org",
    "category": "db-vector-search",
    "tagline": "High-performance open-source embedded analytical SQL database engine",
    "description": "DuckDB is an in-process analytical database designed for rapid local data analysis, vector operations, and zero-overhead execution. It is engineered for data analysts, Python developers, and data science researchers.",
    "rating": 4.9,
    "reviewsCount": 920,
    "pricing": "Free",
    "websiteUrl": "https://duckdb.org",
    "affiliateUrl": "https://duckdb.org",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "lancedb",
    "name": "LanceDB",
    "domain": "lancedb.com",
    "category": "db-vector-search",
    "tagline": "Developer-friendly, open-source embedded vector database for multi-modal AI",
    "description": "LanceDB stores vectors, images, and tabular data on disk using the high-performance Lance columnar format with zero server infrastructure setup. It serves AI developers, local-first applications, and data science teams.",
    "rating": 4.9,
    "reviewsCount": 420,
    "pricing": "Free",
    "websiteUrl": "https://lancedb.com",
    "affiliateUrl": "https://lancedb.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "vespa",
    "name": "Vespa",
    "domain": "vespa.ai",
    "category": "db-vector-search",
    "tagline": "Open-source big data engine for real-time vector search, tensor computing, and RAG",
    "description": "Vespa handles low-latency vector similarity search, structured filtering, and machine-learned ranking over billions of items simultaneously. It is engineered for enterprise AI architects, search engineers, and recommendation engines.",
    "rating": 4.8,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://vespa.ai",
    "affiliateUrl": "https://vespa.ai",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "480K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "singlestore",
    "name": "SingleStore",
    "domain": "singlestore.com",
    "category": "db-vector-search",
    "tagline": "Unified real-time cloud database combining transactions, analytics, and vector search",
    "description": "SingleStore processes high-throughput OLTP transactions, analytical JOIN queries, and vector embeddings in a single ultra-fast engine. It is built for enterprise architects scaling real-time AI and analytics applications.",
    "rating": 4.6,
    "reviewsCount": 280,
    "pricing": "Free Trial",
    "websiteUrl": "https://singlestore.com",
    "affiliateUrl": "https://singlestore.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "420K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "dragonfly",
    "name": "Dragonfly",
    "domain": "dragonflydb.io",
    "category": "db-vector-search",
    "tagline": "Ultra-fast in-memory data store providing a modern replacement for Redis",
    "description": "Dragonfly uses a multi-threaded, shared-nothing architecture to deliver 25x higher throughput than traditional in-memory stores. It serves backend software leads, DevOps engineers, and high-concurrency web platforms.",
    "rating": 4.9,
    "reviewsCount": 510,
    "pricing": "Freemium",
    "websiteUrl": "https://dragonflydb.io",
    "affiliateUrl": "https://dragonflydb.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "580K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "valkey",
    "name": "Valkey",
    "domain": "valkey.io",
    "category": "db-vector-search",
    "tagline": "High-performance open-source in-memory key-value data structure store",
    "description": "Valkey is a community-driven open-source in-memory cache and database backed by major cloud foundations. It serves system engineers and software developers requiring reliable, low-latency caching infrastructure.",
    "rating": 4.8,
    "reviewsCount": 320,
    "pricing": "Free",
    "websiteUrl": "https://valkey.io",
    "affiliateUrl": "https://valkey.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "390K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "surrealdb",
    "name": "SurrealDB",
    "domain": "surrealdb.com",
    "category": "db-vector-search",
    "tagline": "Ultimate multi-model cloud database for document, graph, key-value, and vector queries",
    "description": "SurrealDB simplifies application backends by unifying relational, document, graph, and vector search capabilities into a single Rust-powered engine. It is designed for full-stack developers and modern SaaS creators.",
    "rating": 4.8,
    "reviewsCount": 890,
    "pricing": "Freemium",
    "websiteUrl": "https://surrealdb.com",
    "affiliateUrl": "https://surrealdb.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "faunadb",
    "name": "Fauna",
    "domain": "fauna.com",
    "category": "db-vector-search",
    "tagline": "Flexible, developer-friendly serverless database with document and relational capabilities",
    "description": "Fauna offers a strongly consistent, distributed document-relational database delivered as a zero-ops serverless GraphQL API. It is tailored for full-stack web and mobile developers seeking instant scaling.",
    "rating": 4.7,
    "reviewsCount": 650,
    "pricing": "Freemium",
    "websiteUrl": "https://fauna.com",
    "affiliateUrl": "https://fauna.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "820K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "scylladb",
    "name": "ScyllaDB",
    "domain": "scylladb.com",
    "category": "db-vector-search",
    "tagline": "Monster-throughput C++ NoSQL database fully compatible with Apache Cassandra",
    "description": "ScyllaDB delivers ultra-low p99 latency and high-throughput NoSQL operations by leveraging an asynchronous, shard-per-core architecture. It serves enterprise infrastructure architects and high-scale backend engineers.",
    "rating": 4.8,
    "reviewsCount": 780,
    "pricing": "Freemium",
    "websiteUrl": "https://scylladb.com",
    "affiliateUrl": "https://scylladb.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "950K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "timescaledb",
    "name": "TimescaleDB",
    "domain": "timescale.com",
    "category": "db-vector-search",
    "tagline": "Open-source PostgreSQL powered up for time-series, analytics, and vector search",
    "description": "Timescale converts Postgres into a high-speed time-series and vector database using hypertables and automated compression. It is built for backend developers, IoT engineers, and financial software developers.",
    "rating": 4.8,
    "reviewsCount": 1100,
    "pricing": "Freemium",
    "websiteUrl": "https://timescale.com",
    "affiliateUrl": "https://timescale.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.6M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "opensearch",
    "name": "OpenSearch",
    "domain": "opensearch.org",
    "category": "db-vector-search",
    "tagline": "Open-source search, analytics, and vector retrieval suite for enterprise scale",
    "description": "OpenSearch combines full-text keyword search, k-NN vector search, and log analytics inside a scalable distributed cluster. It is built for DevOps engineers, search developers, and enterprise architects.",
    "rating": 4.7,
    "reviewsCount": 1850,
    "pricing": "Free",
    "websiteUrl": "https://opensearch.org",
    "affiliateUrl": "https://opensearch.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "meilisearch",
    "name": "Meilisearch",
    "domain": "meilisearch.com",
    "category": "db-vector-search",
    "tagline": "Lightning-fast, open-source search engine providing typo-tolerant instant search",
    "description": "Meilisearch delivers blazingly fast full-text search and vector hybrid search capabilities out of the box with zero complex configuration. It serves web developers, e-commerce storefronts, and app creators.",
    "rating": 4.9,
    "reviewsCount": 1420,
    "pricing": "Freemium",
    "websiteUrl": "https://meilisearch.com",
    "affiliateUrl": "https://meilisearch.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.9M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "typesense",
    "name": "Typesense",
    "domain": "typesense.org",
    "category": "db-vector-search",
    "tagline": "Open-source, in-memory search engine optimized for developer experience and fast retrieval",
    "description": "Typesense provides typo-tolerant full-text and vector search with sub-50ms response times written in C++. It is built for frontend engineers and e-commerce platforms wanting an easy Algolia alternative.",
    "rating": 4.9,
    "reviewsCount": 980,
    "pricing": "Freemium",
    "websiteUrl": "https://typesense.org",
    "affiliateUrl": "https://typesense.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "elasticsearch",
    "name": "Elasticsearch",
    "domain": "elastic.co",
    "category": "db-vector-search",
    "tagline": "Distributed search and analytics engine with dense and sparse vector capabilities",
    "description": "Elasticsearch executes hybrid search combining BM25 full-text matching with dense vector ANN search across enterprise data. It serves enterprise search teams, AppSec analysts, and platform leads.",
    "rating": 4.6,
    "reviewsCount": 6100,
    "pricing": "Freemium",
    "websiteUrl": "https://elastic.co",
    "affiliateUrl": "https://elastic.co",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "18.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "memgraph",
    "name": "Memgraph",
    "domain": "memgraph.com",
    "category": "db-vector-search",
    "tagline": "Open-source in-memory graph database with Cypher query support and streaming analytics",
    "description": "Memgraph executes graph queries over streaming data streams with real-time performance and full Cypher query compatibility. It is built for data engineers, fraud detection analysts, and network graph leads.",
    "rating": 4.8,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://memgraph.com",
    "affiliateUrl": "https://memgraph.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "arangodb",
    "name": "ArangoDB",
    "domain": "arangodb.com",
    "category": "db-vector-search",
    "tagline": "Native multi-model database combining graph, document, and search indexes in one engine",
    "description": "ArangoDB unifies document records, graph relations, and full-text search with a single query language (AQL). It serves software developers and system architects consolidating multi-database sprawl.",
    "rating": 4.6,
    "reviewsCount": 650,
    "pricing": "Freemium",
    "websiteUrl": "https://arangodb.com",
    "affiliateUrl": "https://arangodb.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "780K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "tigergraph",
    "name": "TigerGraph",
    "domain": "tigergraph.com",
    "category": "db-vector-search",
    "tagline": "Enterprise distributed graph database built for deep link analytics and AI",
    "description": "TigerGraph analyzes multi-hop relationship patterns across billions of connected entities using parallel graph processing. It serves enterprise data science teams, banking fraud leads, and supply chain analysts.",
    "rating": 4.5,
    "reviewsCount": 310,
    "pricing": "Freemium",
    "websiteUrl": "https://tigergraph.com",
    "affiliateUrl": "https://tigergraph.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "380K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "couchbase",
    "name": "Couchbase",
    "domain": "couchbase.com",
    "category": "db-vector-search",
    "tagline": "Distributed NoSQL cloud database combining key-value memory speed with JSON document search",
    "description": "Couchbase delivers high-performance memory-first caching, SQL-for-JSON querying, and mobile peer-to-peer sync. It serves enterprise application developers and mobile software engineers.",
    "rating": 4.4,
    "reviewsCount": 850,
    "pricing": "Free Trial",
    "websiteUrl": "https://couchbase.com",
    "affiliateUrl": "https://couchbase.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": false,
    "isOpenSource": true
  },
  {
    "id": "influxdb",
    "name": "InfluxDB",
    "domain": "influxdata.com",
    "category": "db-vector-search",
    "tagline": "Purpose-built time-series database engine for IoT, metrics, and real-time events",
    "description": "InfluxDB ingests millions of time-stamped metrics per second to provide real-time operational monitoring and analytics. It is engineered for DevOps engineers, IoT developers, and platform SREs.",
    "rating": 4.6,
    "reviewsCount": 1820,
    "pricing": "Freemium",
    "websiteUrl": "https://influxdata.com",
    "affiliateUrl": "https://influxdata.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "questdb",
    "name": "QuestDB",
    "domain": "questdb.io",
    "category": "db-vector-search",
    "tagline": "Ultra-fast open-source SQL time-series database engine for high-frequency data",
    "description": "QuestDB uses SIMD instruction optimizations and column-oriented storage to process millions of time-series SQL writes per second. It serves fintech engineers, market data leads, and IoT developers.",
    "rating": 4.9,
    "reviewsCount": 420,
    "pricing": "Free",
    "websiteUrl": "https://questdb.io",
    "affiliateUrl": "https://questdb.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "520K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "turbopuffer",
    "name": "Turbopuffer",
    "domain": "turbopuffer.com",
    "category": "db-vector-search",
    "tagline": "Serverless, low-cost vector database architecture built on cloud object storage",
    "description": "Turbopuffer decouples vector search compute from object storage to offer high-scale vector retrieval at minimal cost. It is designed for multi-tenant AI applications, SaaS platforms, and LLM developers.",
    "rating": 4.8,
    "reviewsCount": 180,
    "pricing": "Paid",
    "websiteUrl": "https://turbopuffer.com",
    "affiliateUrl": "https://turbopuffer.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "240K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "marqo",
    "name": "Marqo",
    "domain": "marqo.ai",
    "category": "db-vector-search",
    "tagline": "Open-source vector search engine with built-in multi-modal embedding generation",
    "description": "Marqo handles embedding generation, vector storage, and hybrid search natively across text and visual media in a single platform. It serves e-commerce search engineers and multi-modal AI teams.",
    "rating": 4.9,
    "reviewsCount": 210,
    "pricing": "Freemium",
    "websiteUrl": "https://marqo.ai",
    "affiliateUrl": "https://marqo.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "310K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "upstash",
    "name": "Upstash",
    "domain": "upstash.com",
    "category": "db-vector-search",
    "tagline": "Serverless database platform for Redis, Kafka, and Vector search with HTTP APIs",
    "description": "Upstash provides serverless Redis and Vector databases with per-request pricing and HTTP REST SDKs for edge runtime frameworks. It is built for Next.js, Vercel, and serverless web application developers.",
    "rating": 4.9,
    "reviewsCount": 620,
    "pricing": "Freemium",
    "websiteUrl": "https://upstash.com",
    "affiliateUrl": "https://upstash.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "850K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "turso",
    "name": "Turso",
    "domain": "turso.tech",
    "category": "db-vector-search",
    "tagline": "Edge-replicated, serverless SQLite-compatible database platform powered by libSQL",
    "description": "Turso replicates SQLite database instances near end users worldwide while adding native vector search extensions. It serves web developers building low-latency distributed edge applications.",
    "rating": 4.8,
    "reviewsCount": 420,
    "pricing": "Freemium",
    "websiteUrl": "https://turso.tech",
    "affiliateUrl": "https://turso.tech",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "480K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "convex",
    "name": "Convex",
    "domain": "convex.dev",
    "category": "db-vector-search",
    "tagline": "The reactive backend platform combining database, serverless functions, and vector search",
    "description": "Convex pairs real-time reactive database subscriptions with backend typescript functions and vector index searching. It is engineered for full-stack React and Next.js software developers.",
    "rating": 4.9,
    "reviewsCount": 540,
    "pricing": "Freemium",
    "websiteUrl": "https://convex.dev",
    "affiliateUrl": "https://convex.dev",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "yugabyte-db",
    "name": "YugabyteDB",
    "domain": "yugabyte.com",
    "category": "db-vector-search",
    "tagline": "High-performance open-source distributed SQL database compatible with PostgreSQL",
    "description": "YugabyteDB delivers multi-region horizontal scaling and fault tolerance while preserving native Postgres SQL compatibility. It is built for enterprise cloud leads and mission-critical SaaS applications.",
    "rating": 4.7,
    "reviewsCount": 620,
    "pricing": "Freemium",
    "websiteUrl": "https://yugabyte.com",
    "affiliateUrl": "https://yugabyte.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "780K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "tidb-pingcap",
    "name": "TiDB",
    "domain": "pingcap.com",
    "category": "db-vector-search",
    "tagline": "Open-source distributed HTAP database compatible with MySQL and vector search",
    "description": "TiDB handles real-time transactional and analytical workloads in a single horizontally scalable database engine. It serves enterprise database leads and high-growth e-commerce platforms.",
    "rating": 4.7,
    "reviewsCount": 850,
    "pricing": "Freemium",
    "websiteUrl": "https://pingcap.com",
    "affiliateUrl": "https://pingcap.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "cockroachdb",
    "name": "CockroachDB",
    "domain": "cockroachlabs.com",
    "category": "db-vector-search",
    "tagline": "Cloud-native distributed SQL database with multi-region resilience and serializable ACID",
    "description": "CockroachDB guarantees transactional consistency across geographic regions with survivor-level fault tolerance. It is engineered for enterprise architects, financial systems, and global SaaS products.",
    "rating": 4.7,
    "reviewsCount": 890,
    "pricing": "Freemium",
    "websiteUrl": "https://cockroachlabs.com",
    "affiliateUrl": "https://cockroachlabs.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "dgraph",
    "name": "Dgraph",
    "domain": "dgraph.io",
    "category": "db-vector-search",
    "tagline": "Open-source distributed GraphQL database built natively for graph applications",
    "description": "Dgraph provides low-latency graph queries over distributed nodes with GraphQL as its native query language. It is designed for software developers building social networks, recommendations, and knowledge graphs.",
    "rating": 4.5,
    "reviewsCount": 480,
    "pricing": "Freemium",
    "websiteUrl": "https://dgraph.io",
    "affiliateUrl": "https://dgraph.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "420K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "gel-edgedb",
    "name": "Gel (formerly EdgeDB)",
    "domain": "geldata.com",
    "category": "db-vector-search",
    "tagline": "Graph-relational database built on PostgreSQL with strict schema safety and EdgeQL",
    "description": "Gel redefines relational databases by replacing traditional SQL with an object-oriented graph-relational query model. It is built for TypeScript and Python developers wanting modern database developer experience.",
    "rating": 4.9,
    "reviewsCount": 380,
    "pricing": "Free",
    "websiteUrl": "https://geldata.com",
    "affiliateUrl": "https://geldata.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "580K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "janusgraph",
    "name": "JanusGraph",
    "domain": "janusgraph.org",
    "category": "db-vector-search",
    "tagline": "Open-source distributed graph database supporting Gremlin and massive scaling",
    "description": "JanusGraph stores billions of graph vertices and edges across Cassandra, HBase, or BerkeleyDB backends. It is built for enterprise data engineering teams processing massive connectivity networks.",
    "rating": 4.4,
    "reviewsCount": 310,
    "pricing": "Free",
    "websiteUrl": "https://janusgraph.org",
    "affiliateUrl": "https://janusgraph.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "290K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "terminusdb",
    "name": "TerminusDB",
    "domain": "terminusdb.com",
    "category": "db-vector-search",
    "tagline": "Open-source graph database with Git-like revision control and versioning",
    "description": "TerminusDB adds branch, merge, pull, and push data-versioning capabilities to knowledge graphs and document stores. It serves data engineers, knowledge managers, and collaborative data teams.",
    "rating": 4.7,
    "reviewsCount": 210,
    "pricing": "Free",
    "websiteUrl": "https://terminusdb.com",
    "affiliateUrl": "https://terminusdb.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "240K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "rocksdb",
    "name": "RocksDB",
    "domain": "rocksdb.org",
    "category": "db-vector-search",
    "tagline": "High-performance embedded persistent key-value store optimized for fast storage",
    "description": "RocksDB provides low-latency embedded key-value storage utilizing Log-Structured Merge (LSM) trees on fast NVMe drives. It is an industry-standard storage engine underlying major databases.",
    "rating": 4.9,
    "reviewsCount": 1100,
    "pricing": "Free",
    "websiteUrl": "https://rocksdb.org",
    "affiliateUrl": "https://rocksdb.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "850K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "aerospike",
    "name": "Aerospike",
    "domain": "aerospike.com",
    "category": "db-vector-search",
    "tagline": "Real-time, sub-millisecond NoSQL and vector database for multi-terabyte workloads",
    "description": "Aerospike uses hybrid memory and flash storage optimizations to deliver predictable low latency at massive scale. It serves enterprise banking, adtech, and real-time transaction applications.",
    "rating": 4.5,
    "reviewsCount": 420,
    "pricing": "Free Trial",
    "websiteUrl": "https://aerospike.com",
    "affiliateUrl": "https://aerospike.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": false,
    "isOpenSource": true
  },
  {
    "id": "cassandra",
    "name": "Apache Cassandra",
    "domain": "cassandra.apache.org",
    "category": "db-vector-search",
    "tagline": "Open-source distributed NoSQL database with vector search and masterless resilience",
    "description": "Cassandra offers linear scalability and fault tolerance across data centers alongside vector indexing capabilities. It is designed for enterprise infrastructure engineers and high-volume backend platforms.",
    "rating": 4.5,
    "reviewsCount": 2400,
    "pricing": "Free",
    "websiteUrl": "https://cassandra.apache.org",
    "affiliateUrl": "https://cassandra.apache.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "astradb",
    "name": "DataStax Astra DB",
    "domain": "datastax.com/products/datastax-astra",
    "category": "db-vector-search",
    "tagline": "Vector-first cloud database service powered by Apache Cassandra",
    "description": "Astra DB provides a fully managed, serverless vector database built on Cassandra for building GenAI and RAG applications. It serves AI developers, enterprise cloud architects, and software teams.",
    "rating": 4.7,
    "reviewsCount": 680,
    "pricing": "Freemium",
    "websiteUrl": "https://datastax.com/products/datastax-astra",
    "affiliateUrl": "https://datastax.com/products/datastax-astra",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "zilliz-cloud",
    "name": "Zilliz Cloud",
    "domain": "zilliz.com",
    "category": "db-vector-search",
    "tagline": "Fully managed enterprise cloud vector database platform powered by Milvus",
    "description": "Zilliz Cloud delivers auto-scaling, billion-scale vector similarity search infrastructure with zero cluster maintenance. It serves enterprise AI development teams, recommendation systems, and search leads.",
    "rating": 4.8,
    "reviewsCount": 450,
    "pricing": "Freemium",
    "websiteUrl": "https://zilliz.com",
    "affiliateUrl": "https://zilliz.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "850K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "keydb",
    "name": "KeyDB",
    "domain": "docs.keydb.dev",
    "category": "db-vector-search",
    "tagline": "High-performance multi-threaded fork of Redis built for speed and memory efficiency",
    "description": "KeyDB accelerates in-memory operations using true multi-threading, active replication, and FLASH disk offloading. It serves backend engineers and system leads requiring high-throughput caching.",
    "rating": 4.8,
    "reviewsCount": 380,
    "pricing": "Free",
    "websiteUrl": "https://docs.keydb.dev",
    "affiliateUrl": "https://docs.keydb.dev",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "320K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "kuzu-db",
    "name": "Kùzu",
    "domain": "kuzudb.com",
    "category": "db-vector-search",
    "tagline": "Embeddable open-source property graph database engine built for speed",
    "description": "Kùzu provides in-process, disk-based graph database storage optimized for graph algorithms and vector queries without server setup. It is engineered for data scientists and software developers.",
    "rating": 4.9,
    "reviewsCount": 160,
    "pricing": "Free",
    "websiteUrl": "https://kuzudb.com",
    "affiliateUrl": "https://kuzudb.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "180K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "greptimedb",
    "name": "GreptimeDB",
    "domain": "greptime.com",
    "category": "db-vector-search",
    "tagline": "Open-source cloud-native time-series database with unified metric and log processing",
    "description": "GreptimeDB handles time-series metrics, logs, and analytical events using SQL and PromQL in a single Rust engine. It serves DevOps engineers, observability leads, and IoT developers.",
    "rating": 4.8,
    "reviewsCount": 190,
    "pricing": "Freemium",
    "websiteUrl": "https://greptime.com",
    "affiliateUrl": "https://greptime.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "210K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "victoriametrics",
    "name": "VictoriaMetrics",
    "domain": "victoriametrics.com",
    "category": "db-vector-search",
    "tagline": "Fast, cost-effective open-source time series database and Prometheus monitoring solution",
    "description": "VictoriaMetrics provides high-throughput metric ingestion and long-term time-series storage with small RAM footprints. It is engineered for system administrators, DevOps leads, and SREs.",
    "rating": 4.9,
    "reviewsCount": 820,
    "pricing": "Freemium",
    "websiteUrl": "https://victoriametrics.com",
    "affiliateUrl": "https://victoriametrics.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "950K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "cratedb",
    "name": "CrateDB",
    "domain": "crate.io",
    "category": "db-vector-search",
    "tagline": "Distributed SQL database engineered for real-time multi-model time-series and vector analytics",
    "description": "CrateDB combines SQL query interfaces with distributed document and vector indexing for high-volume IoT and AI data. It serves industrial IoT engineers, data architects, and analysts.",
    "rating": 4.6,
    "reviewsCount": 240,
    "pricing": "Freemium",
    "websiteUrl": "https://crate.io",
    "affiliateUrl": "https://crate.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "310K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "faiss-fb",
    "name": "FAISS (Meta)",
    "domain": "github.com/facebookresearch/faiss",
    "category": "db-vector-search",
    "tagline": "Open-source library for efficient similarity search and clustering of dense vectors",
    "description": "FAISS provides GPU-accelerated C++ vector indexing algorithms to perform ultra-fast nearest neighbor searches over massive vector sets. It is a foundational library for machine learning researchers and AI engineers.",
    "rating": 4.9,
    "reviewsCount": 2800,
    "pricing": "Free",
    "websiteUrl": "https://github.com/facebookresearch/faiss",
    "affiliateUrl": "https://github.com/facebookresearch/faiss",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "pgvector-ext",
    "name": "pgvector",
    "domain": "github.com/pgvector/pgvector",
    "category": "db-vector-search",
    "tagline": "Open-source vector similarity search extension for PostgreSQL",
    "description": "pgvector adds HNSW and IVFFlat vector indexing directly to existing PostgreSQL databases, allowing combined SQL and vector queries. It serves application developers extending Postgres for AI workloads.",
    "rating": 4.9,
    "reviewsCount": 3200,
    "pricing": "Free",
    "websiteUrl": "https://github.com/pgvector/pgvector",
    "affiliateUrl": "https://github.com/pgvector/pgvector",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "foundationdb",
    "name": "FoundationDB",
    "domain": "apple.github.io/foundationdb",
    "category": "db-vector-search",
    "tagline": "Open-source distributed transactional key-value store powering cloud foundations",
    "description": "FoundationDB provides ACID transactions and horizontal scaling in a low-level key-value core designed to underlie higher-level databases. It serves cloud infrastructure engineers and distributed systems developers.",
    "rating": 4.8,
    "reviewsCount": 420,
    "pricing": "Free",
    "websiteUrl": "https://apple.github.io/foundationdb",
    "affiliateUrl": "https://apple.github.io/foundationdb",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "tikv-cncf",
    "name": "TiKV",
    "domain": "tikv.org",
    "category": "db-vector-search",
    "tagline": "CNCF open-source distributed transactional key-value database",
    "description": "TiKV delivers ACID-compliant distributed key-value storage using the Raft consensus protocol for high-concurrency systems. It is engineered for cloud infrastructure developers and database architects.",
    "rating": 4.8,
    "reviewsCount": 380,
    "pricing": "Free",
    "websiteUrl": "https://tikv.org",
    "affiliateUrl": "https://tikv.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "390K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "garnet-ms",
    "name": "Garnet (Microsoft)",
    "domain": "microsoft.github.io/garnet",
    "category": "db-vector-search",
    "tagline": "Remote cache-store from Microsoft Research offering extreme throughput and low latency",
    "description": "Garnet delivers high-speed in-memory key-value caching using C# .NET thread scaling while maintaining Redis protocol compatibility. It is built for backend systems engineers and high-performance server architects.",
    "rating": 4.9,
    "reviewsCount": 510,
    "pricing": "Free",
    "websiteUrl": "https://microsoft.github.io/garnet",
    "affiliateUrl": "https://microsoft.github.io/garnet",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "quickwit",
    "name": "Quickwit",
    "domain": "quickwit.io",
    "category": "db-vector-search",
    "tagline": "Cloud-native, sub-second search engine for logs and traces built directly on object storage",
    "description": "Quickwit indexes high-volume log data and vector records straight into S3-compatible cloud storage for cost-efficient search. It is built for DevOps engineers, FinOps leads, and platform architects.",
    "rating": 4.9,
    "reviewsCount": 310,
    "pricing": "Free",
    "websiteUrl": "https://quickwit.io",
    "affiliateUrl": "https://quickwit.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "380K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "tantivy-engine",
    "name": "Tantivy",
    "domain": "github.com/quickwit-oss/tantivy",
    "category": "db-vector-search",
    "tagline": "Full-text search engine library written in Rust as a fast alternative to Lucene",
    "description": "Tantivy provides a low-level, high-performance C++ and Rust search indexing library for embedding custom search engines. It serves system developers, search software leads, and database creators.",
    "rating": 4.9,
    "reviewsCount": 480,
    "pricing": "Free",
    "websiteUrl": "https://github.com/quickwit-oss/tantivy",
    "affiliateUrl": "https://github.com/quickwit-oss/tantivy",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "420K",
    "isFreeTier": true,
    "isOpenSource": true
  }
];

function generateSlug(name) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

async function main() {
  const saasDataPath = path.join(__dirname, '../src/data/saasData.jsx');
  let fileContent = fs.readFileSync(saasDataPath, 'utf8');

  const existingDomains = new Set();
  const existingNames = new Set();

  const domainMatches = fileContent.matchAll(/"domain":\s*"([^"]+)"/g);
  for (const m of domainMatches) existingDomains.add(m[1].toLowerCase());

  const nameMatches = fileContent.matchAll(/"name":\s*"([^"]+)"/g);
  for (const m of nameMatches) existingNames.add(m[1].toLowerCase());

  console.log(`Initial DB has ${existingDomains.size} domains and ${existingNames.size} tool names.`);

  const newToolsToAdd = [];
  let skippedDuplicates = 0;

  for (const tool of inputTools) {
    const cleanDomain = tool.domain.toLowerCase().trim();
    const cleanName = tool.name.toLowerCase().trim();

    if (existingDomains.has(cleanDomain) || existingNames.has(cleanName)) {
      console.log(`[SKIP DUPLICATE] ${tool.name} (${tool.domain})`);
      skippedDuplicates++;
      continue;
    }

    const toolId = tool.id || generateSlug(tool.name);
    const newToolObj = {
      id: toolId,
      name: tool.name,
      domain: tool.domain,
      category: tool.category || "db-vector-search",
      tagline: tool.tagline,
      description: tool.description,
      rating: tool.rating || 4.8,
      reviewsCount: tool.reviewsCount || 500,
      pricing: tool.pricing || 'Freemium',
      websiteUrl: tool.websiteUrl || `https://${tool.domain}`,
      affiliateUrl: tool.affiliateUrl || `https://${tool.domain}`,
      badge: tool.badge || "Verified Tool",
      featured: Boolean(tool.featured),
      monthlyVisits: tool.monthlyVisits || "500K",
      isFreeTier: Boolean(tool.isFreeTier),
      isOpenSource: Boolean(tool.isOpenSource),
      features: [
        "High Performance Storage",
        "Vector & SQL Queries",
        "Horizontal Scalability",
        "Cloud Native Deployment"
      ]
    };

    newToolsToAdd.push(newToolObj);
    existingDomains.add(cleanDomain);
    existingNames.add(cleanName);
  }

  console.log(`Found ${newToolsToAdd.length} NEW Database tools to insert. Skipped ${skippedDuplicates} duplicates.`);

  if (newToolsToAdd.length === 0) {
    console.log("No new tools to insert!");
    return;
  }

  const formattedJsonEntries = newToolsToAdd.map(t => JSON.stringify(t, null, 4)).join(',\n');
  const targetInsertionPoint = `export const staticSaasTools = [`;
  
  fileContent = fileContent.replace(targetInsertionPoint, `${targetInsertionPoint}\n${formattedJsonEntries},`);

  fs.writeFileSync(saasDataPath, fileContent, 'utf8');
  console.log(`Successfully ingested ${newToolsToAdd.length} new Database tools into src/data/saasData.jsx!`);
}

main().catch(console.error);
