const fs = require('fs');
const path = require('path');

const newTools = [
  {
    "id": "crossplane",
    "name": "Crossplane",
    "domain": "crossplane.io",
    "category": "devops-infrastructure",
    "tagline": "Open-source framework to build custom control planes and provision cloud infrastructure",
    "description": "Crossplane transforms Kubernetes into a universal control plane to manage cloud resources, services, and databases using declarative custom APIs. It is built for platform engineering teams creating self-service developer infrastructure platforms.",
    "rating": 4.9,
    "reviewsCount": 620,
    "pricing": "Free",
    "websiteUrl": "https://crossplane.io",
    "affiliateUrl": "https://crossplane.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "680K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "dagger-engine",
    "name": "Dagger",
    "domain": "dagger.io",
    "category": "devops-infrastructure",
    "tagline": "Programmable CI/CD engine to write pipelines as code using real programming languages",
    "description": "Dagger allows developers to replace complex CI/CD YAML configurations with type-safe Go, Python, or TypeScript code executing inside container runtimes. It serves software engineers and DevOps teams building portable, locally testable pipelines.",
    "rating": 4.9,
    "reviewsCount": 850,
    "pricing": "Freemium",
    "websiteUrl": "https://dagger.io",
    "affiliateUrl": "https://dagger.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "spinnaker-cd",
    "name": "Spinnaker",
    "domain": "spinnaker.io",
    "category": "devops-infrastructure",
    "tagline": "Open-source multi-cloud continuous delivery platform for high-velocity software releases",
    "description": "Spinnaker automates complex application deployment pipelines, automated canary analyses, and multi-region rollouts across AWS, GCP, and Kubernetes. It is designed for enterprise release managers and cloud infrastructure engineers.",
    "rating": 4.5,
    "reviewsCount": 1100,
    "pricing": "Free",
    "websiteUrl": "https://spinnaker.io",
    "affiliateUrl": "https://spinnaker.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "850K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "flux-cd",
    "name": "Flux",
    "domain": "fluxcd.io",
    "category": "devops-infrastructure",
    "tagline": "GitOps operator for Kubernetes keeping cluster configurations automatically in sync",
    "description": "Flux monitors Git repositories and OCI registries to automatically reconcile desired Kubernetes states with active cluster deployments. It serves cloud-native developers, platform engineers, and SRE teams enforcing GitOps practices.",
    "rating": 4.8,
    "reviewsCount": 1250,
    "pricing": "Free",
    "websiteUrl": "https://fluxcd.io",
    "affiliateUrl": "https://fluxcd.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "hashicorp-nomad",
    "name": "HashiCorp Nomad",
    "domain": "nomadproject.io",
    "category": "devops-infrastructure",
    "tagline": "Flexible workload orchestrator to deploy containerized and legacy applications effortlessly",
    "description": "Nomad schedules containers, non-containerized binaries, and batch jobs across Linux, Windows, and multi-cloud environments. It is tailored for operations teams seeking a lightweight, simple alternative to Kubernetes.",
    "rating": 4.7,
    "reviewsCount": 1420,
    "pricing": "Freemium",
    "websiteUrl": "https://nomadproject.io",
    "affiliateUrl": "https://nomadproject.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.9M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "opentofu",
    "name": "OpenTofu",
    "domain": "opentofu.org",
    "category": "devops-infrastructure",
    "tagline": "Open-source community-driven fork of Terraform for Infrastructure as Code",
    "description": "OpenTofu provides a truly open, MPL-licensed Infrastructure as Code engine compatible with existing HCL configurations and provider ecosystems. It serves cloud engineers, platform architects, and DevOps leads requiring open IaC tooling.",
    "rating": 4.9,
    "reviewsCount": 1150,
    "pricing": "Free",
    "websiteUrl": "https://opentofu.org",
    "affiliateUrl": "https://opentofu.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.6M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "open-feature",
    "name": "OpenFeature",
    "domain": "openfeature.dev",
    "category": "devops-infrastructure",
    "tagline": "Vendor-agnostic open-source standard for feature flag management and progressive delivery",
    "description": "OpenFeature provides standardized SDKs and unified APIs to decouple application code from underlying feature flag management vendors. It serves software developers and release engineers implementing trunk-based development.",
    "rating": 4.8,
    "reviewsCount": 240,
    "pricing": "Free",
    "websiteUrl": "https://openfeature.dev",
    "affiliateUrl": "https://openfeature.dev",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "280K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "launchdarkly",
    "name": "LaunchDarkly",
    "domain": "launchdarkly.com",
    "category": "devops-infrastructure",
    "tagline": "Enterprise feature management and targeted release control platform",
    "description": "LaunchDarkly gives software teams real-time control over feature rollouts, canary deployments, kill-switches, and user segment targeting. It serves product engineering teams and DevOps architects reducing release risk.",
    "rating": 4.6,
    "reviewsCount": 1820,
    "pricing": "Free Trial",
    "websiteUrl": "https://launchdarkly.com",
    "affiliateUrl": "https://launchdarkly.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "growthbook",
    "name": "GrowthBook",
    "domain": "growthbook.io",
    "category": "devops-infrastructure",
    "tagline": "Open-source feature flagging and A/B testing platform built for data-driven engineering",
    "description": "GrowthBook combines customizable feature flag controls with native data warehouse analysis without exposing user data to third parties. It is built for developers, growth marketers, and data engineers.",
    "rating": 4.9,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://growthbook.io",
    "affiliateUrl": "https://growthbook.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "flagsmith",
    "name": "Flagsmith",
    "domain": "flagsmith.com",
    "category": "devops-infrastructure",
    "tagline": "Open-source feature flag and remote configuration engine for web and mobile",
    "description": "Flagsmith enables software developers to toggle features, manage remote application configurations, and run A/B experiments locally or in cloud. It serves software teams migrating toward continuous delivery.",
    "rating": 4.8,
    "reviewsCount": 420,
    "pricing": "Freemium",
    "websiteUrl": "https://flagsmith.com",
    "affiliateUrl": "https://flagsmith.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "520K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "unleash-flags",
    "name": "Unleash",
    "domain": "getunleash.io",
    "category": "devops-infrastructure",
    "tagline": "Enterprise open-source feature management platform prioritizing security and privacy",
    "description": "Unleash evaluates feature flags locally inside application servers to protect sensitive user data while providing instant feature switches. It serves enterprise DevSecOps teams and software engineering leads.",
    "rating": 4.8,
    "reviewsCount": 620,
    "pricing": "Freemium",
    "websiteUrl": "https://getunleash.io",
    "affiliateUrl": "https://getunleash.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "820K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "k3s-rancher",
    "name": "K3s",
    "domain": "k3s.io",
    "category": "devops-infrastructure",
    "tagline": "Lightweight, fully compliant Kubernetes distribution built for IoT and Edge computing",
    "description": "K3s packages Kubernetes into a single binary under 100MB with reduced resource requirements for resource-constrained server nodes. It is ideal for edge deployments, ARM devices, and development environments.",
    "rating": 4.9,
    "reviewsCount": 2100,
    "pricing": "Free",
    "websiteUrl": "https://k3s.io",
    "affiliateUrl": "https://k3s.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "rancher-desktop",
    "name": "Rancher Desktop",
    "domain": "rancherdesktop.io",
    "category": "devops-infrastructure",
    "tagline": "Open-source desktop container management and local Kubernetes app for Mac and Windows",
    "description": "Rancher Desktop provides container management, nerdctl/Docker CLI support, and local Kubernetes cluster creation on developer machines. It is engineered for software engineers, DevOps testers, and platform engineers.",
    "rating": 4.7,
    "reviewsCount": 980,
    "pricing": "Free",
    "websiteUrl": "https://rancherdesktop.io",
    "affiliateUrl": "https://rancherdesktop.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "talos-linux",
    "name": "Talos Linux",
    "domain": "talos.dev",
    "category": "devops-infrastructure",
    "tagline": "Immutable, minimalist, and API-driven Linux distribution built exclusively for Kubernetes",
    "description": "Talos Linux eliminates SSH, systemd, and traditional shell environments, managing OS components strictly via gRPC declarative APIs. It is engineered for security-conscious cloud infrastructure architects and SREs.",
    "rating": 4.9,
    "reviewsCount": 480,
    "pricing": "Free",
    "websiteUrl": "https://talos.dev",
    "affiliateUrl": "https://talos.dev",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "kusionstack",
    "name": "KusionStack",
    "domain": "kusionstack.io",
    "category": "devops-infrastructure",
    "tagline": "Intent-driven platform engineering framework for orchestrating modern cloud infrastructure",
    "description": "KusionStack translates high-level application intent code into concrete cloud infrastructure manifests across Kubernetes and multi-cloud providers. It serves enterprise platform engineering divisions and DevOps teams.",
    "rating": 4.8,
    "reviewsCount": 180,
    "pricing": "Free",
    "websiteUrl": "https://kusionstack.io",
    "affiliateUrl": "https://kusionstack.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "150K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "backstage-spotify",
    "name": "Backstage",
    "domain": "backstage.io",
    "category": "devops-infrastructure",
    "tagline": "Open-source developer portal platform created by Spotify for platform engineering",
    "description": "Backstage unifies microservice software catalogs, software templates, technical documentation, and CI tooling into a single developer portal. It is built for enterprise platform engineers scaling developer experience.",
    "rating": 4.8,
    "reviewsCount": 1450,
    "pricing": "Free",
    "websiteUrl": "https://backstage.io",
    "affiliateUrl": "https://backstage.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "port-devportal",
    "name": "Port",
    "domain": "getport.io",
    "category": "devops-infrastructure",
    "tagline": "No-code developer portal and internal developer platform for platform teams",
    "description": "Port consolidates cloud asset catalogs, developer self-service actions, and software scorecard standards without complex frontend code. It is tailored for DevOps managers and platform engineering teams.",
    "rating": 4.9,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://getport.io",
    "affiliateUrl": "https://getport.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "580K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "cortex-io",
    "name": "Cortex",
    "domain": "cortex.io",
    "category": "devops-infrastructure",
    "tagline": "Internal developer portal for microservice governance and engineering scorecards",
    "description": "Cortex maps microservice ownership, enforces production readiness scorecards, and tracks security compliance across cloud infrastructure. It serves engineering leaders, CISOs, and platform engineering teams.",
    "rating": 4.8,
    "reviewsCount": 310,
    "pricing": "Free Trial",
    "websiteUrl": "https://cortex.io",
    "affiliateUrl": "https://cortex.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "420K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "opslevel",
    "name": "OpsLevel",
    "domain": "opslevel.com",
    "category": "devops-infrastructure",
    "tagline": "Developer portal helping engineering teams tame microservice complexity",
    "description": "OpsLevel maintains centralized service catalogs, enforces technical standards, and drives self-service infrastructure actions. It serves engineering managers, SREs, and platform teams in scaling SaaS companies.",
    "rating": 4.8,
    "reviewsCount": 240,
    "pricing": "Free Trial",
    "websiteUrl": "https://opslevel.com",
    "affiliateUrl": "https://opslevel.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "310K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "atlantis-iac",
    "name": "Atlantis",
    "domain": "runatlantis.io",
    "category": "devops-infrastructure",
    "tagline": "Open-source Terraform pull request automation tool for GitOps workflows",
    "description": "Atlantis executes Terraform plan and apply commands directly within GitHub, GitLab, and Bitbucket pull request comments. It is built for DevOps engineers automating IaC peer reviews and deployment safety.",
    "rating": 4.9,
    "reviewsCount": 820,
    "pricing": "Free",
    "websiteUrl": "https://runatlantis.io",
    "affiliateUrl": "https://runatlantis.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "950K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "terragrunt",
    "name": "Terragrunt",
    "domain": "terragrunt.gruntwork.io",
    "category": "devops-infrastructure",
    "tagline": "Thin wrapper for Terraform providing DRY code configurations and multi-module execution",
    "description": "Terragrunt eliminates code duplication across environment directories and orchestrates execution across multiple Terraform modules simultaneously. It serves cloud infrastructure engineers and DevOps leads.",
    "rating": 4.8,
    "reviewsCount": 1100,
    "pricing": "Free",
    "websiteUrl": "https://terragrunt.gruntwork.io",
    "affiliateUrl": "https://terragrunt.gruntwork.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "infracost",
    "name": "Infracost",
    "domain": "infracost.io",
    "category": "devops-infrastructure",
    "tagline": "Cloud cost estimates for Terraform in pull requests before deployment",
    "description": "Infracost parses Infrastructure as Code pull requests to display exact monthly cloud cost changes directly inside code reviews. It is engineered for DevOps engineers, FinOps leads, and engineering managers.",
    "rating": 4.9,
    "reviewsCount": 650,
    "pricing": "Freemium",
    "websiteUrl": "https://infracost.io",
    "affiliateUrl": "https://infracost.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "780K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "scalr-iac",
    "name": "Scalr",
    "domain": "scalr.com",
    "category": "devops-infrastructure",
    "tagline": "Infrastructure as Code management platform built for Terraform and OpenTofu",
    "description": "Scalr manages IaC state files, policy-as-code guardrails, RBAC, and cost controls across organizational cloud environments. It serves enterprise cloud architects and platform engineering teams.",
    "rating": 4.7,
    "reviewsCount": 320,
    "pricing": "Freemium",
    "websiteUrl": "https://scalr.com",
    "affiliateUrl": "https://scalr.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "380K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "spacelift-iac",
    "name": "Spacelift",
    "domain": "spacelift.io",
    "category": "devops-infrastructure",
    "tagline": "Sophisticated CI/CD platform for Infrastructure as Code management and orchestration",
    "description": "Spacelift orchestrates Terraform, OpenTofu, Pulumi, CloudFormation, and Ansible workflows with custom policy-as-code rules. It is engineered for enterprise platform engineering and DevOps teams.",
    "rating": 4.8,
    "reviewsCount": 510,
    "pricing": "Free Trial",
    "websiteUrl": "https://spacelift.io",
    "affiliateUrl": "https://spacelift.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "env0-iac",
    "name": "env0",
    "domain": "env0.com",
    "category": "devops-infrastructure",
    "tagline": "Automated cloud environment management and IaC orchestration platform",
    "description": "env0 provides self-service ephemeral cloud environments, state management, budget controls, and TTL policies for IaC tools. It serves DevOps engineers and platform leaders managing cloud spend.",
    "rating": 4.8,
    "reviewsCount": 290,
    "pricing": "Freemium",
    "websiteUrl": "https://env0.com",
    "affiliateUrl": "https://env0.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "340K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "packer-hashicorp",
    "name": "HashiCorp Packer",
    "domain": "packer.io",
    "category": "devops-infrastructure",
    "tagline": "Automated open-source tool for building identical machine images across multi-cloud platforms",
    "description": "Packer bakes golden machine images, AMIs, and VM templates from declarative configuration files across cloud providers. It is a standard tool for cloud security operations and infrastructure teams.",
    "rating": 4.8,
    "reviewsCount": 1820,
    "pricing": "Free",
    "websiteUrl": "https://packer.io",
    "affiliateUrl": "https://packer.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "vagrant-hashicorp",
    "name": "HashiCorp Vagrant",
    "domain": "vagrantup.com",
    "category": "devops-infrastructure",
    "tagline": "Tool for building and managing portable, reproducible development environments",
    "description": "Vagrant configures lightweight, repeatable virtual machine environments across hypervisors using simple configuration scripts. It serves software developers and QA engineers creating consistent local dev environments.",
    "rating": 4.5,
    "reviewsCount": 2400,
    "pricing": "Free",
    "websiteUrl": "https://vagrantup.com",
    "affiliateUrl": "https://vagrantup.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "waypoint-hashicorp",
    "name": "HashiCorp Waypoint",
    "domain": "waypointproject.io",
    "category": "devops-infrastructure",
    "tagline": "Consistent developer workflow to build, deploy, and release application code across platforms",
    "description": "Waypoint abstracts deployment mechanics, allowing developers to push applications to Kubernetes, EC2, or Cloud Run via a single config file. It is built for platform engineering teams simplifying app delivery.",
    "rating": 4.6,
    "reviewsCount": 380,
    "pricing": "Free",
    "websiteUrl": "https://waypointproject.io",
    "affiliateUrl": "https://waypointproject.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "320K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "tekton-cd",
    "name": "Tekton",
    "domain": "tekton.dev",
    "category": "devops-infrastructure",
    "tagline": "Cloud-native open-source framework for creating serverless CI/CD execution systems on Kubernetes",
    "description": "Tekton provides Kubernetes Custom Resource Definitions (CRDs) to execute modular, scalable CI/CD pipelines natively in container clusters. It serves platform developers building custom internal CI/CD infrastructure.",
    "rating": 4.7,
    "reviewsCount": 750,
    "pricing": "Free",
    "websiteUrl": "https://tekton.dev",
    "affiliateUrl": "https://tekton.dev",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "820K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "buildkite-cicd",
    "name": "Buildkite",
    "domain": "buildkite.com",
    "category": "devops-infrastructure",
    "tagline": "Hybrid CI/CD platform combining cloud pipeline controls with self-hosted private runners",
    "description": "Buildkite separates pipeline orchestration from build execution, running agent workloads safely inside user private clouds. It serves security-conscious enterprise engineering teams and DevOps architects.",
    "rating": 4.8,
    "reviewsCount": 680,
    "pricing": "Freemium",
    "websiteUrl": "https://buildkite.com",
    "affiliateUrl": "https://buildkite.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "950K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "teamcity-jetbrains",
    "name": "TeamCity",
    "domain": "jetbrains.com/teamcity",
    "category": "devops-infrastructure",
    "tagline": "Powerful, out-of-the-box build management and continuous integration server",
    "description": "TeamCity provides comprehensive CI build pipelines, intelligent test impact analysis, and deep JetBrains IDE integrations. It is engineered for professional software development teams and enterprise engineering leads.",
    "rating": 4.6,
    "reviewsCount": 1820,
    "pricing": "Freemium",
    "websiteUrl": "https://jetbrains.com/teamcity",
    "affiliateUrl": "https://jetbrains.com/teamcity",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "drone-ci",
    "name": "Drone (Harness)",
    "domain": "drone.io",
    "category": "devops-infrastructure",
    "tagline": "Self-service, container-native continuous integration engine built on Docker",
    "description": "Drone executes every pipeline step inside isolated Docker containers using clean, simple YAML configuration files. It is designed for software developers and DevOps teams wanting fast, lightweight self-hosted CI.",
    "rating": 4.7,
    "reviewsCount": 920,
    "pricing": "Freemium",
    "websiteUrl": "https://drone.io",
    "affiliateUrl": "https://drone.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "harness-io",
    "name": "Harness",
    "domain": "harness.io",
    "category": "devops-infrastructure",
    "tagline": "End-to-end AI-driven software delivery and developer platform",
    "description": "Harness automates code builds, continuous deployments, cloud cost management, feature flags, and chaos engineering modules. It is engineered for enterprise DevOps organizations scaling delivery platform operations.",
    "rating": 4.6,
    "reviewsCount": 850,
    "pricing": "Freemium",
    "websiteUrl": "https://harness.io",
    "affiliateUrl": "https://harness.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "octopus-deploy",
    "name": "Octopus Deploy",
    "domain": "octopus.com",
    "category": "devops-infrastructure",
    "tagline": "Automated deployment and release management platform for multi-cloud environments",
    "description": "Octopus Deploy handles complex continuous deployment pipelines, environment configuration variables, and release approvals. It serves enterprise DevOps teams, release engineers, and system administrators.",
    "rating": 4.8,
    "reviewsCount": 1650,
    "pricing": "Freemium",
    "websiteUrl": "https://octopus.com",
    "affiliateUrl": "https://octopus.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "codefresh-gitops",
    "name": "Codefresh",
    "domain": "codefresh.io",
    "category": "devops-infrastructure",
    "tagline": "Enterprise GitOps platform built on Argo CD for Kubernetes continuous delivery",
    "description": "Codefresh unifies Argo workflows, pipeline dashboards, image security scanning, and deployment tracking for Kubernetes. It serves enterprise DevSecOps teams scaling cloud-native GitOps delivery.",
    "rating": 4.7,
    "reviewsCount": 420,
    "pricing": "Freemium",
    "websiteUrl": "https://codefresh.io",
    "affiliateUrl": "https://codefresh.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "510K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "werf-io",
    "name": "werf",
    "domain": "werf.io",
    "category": "devops-infrastructure",
    "tagline": "Open-source CLI tool glueing Git, Docker, and Helm into seamless Kubernetes CI/CD",
    "description": "werf builds container images, cleans container registries, and deploys application releases directly into Kubernetes. It is built for DevOps engineers streamlining container delivery pipelines.",
    "rating": 4.8,
    "reviewsCount": 310,
    "pricing": "Free",
    "websiteUrl": "https://werf.io",
    "affiliateUrl": "https://werf.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "380K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "tilt-dev",
    "name": "Tilt",
    "domain": "tilt.dev",
    "category": "devops-infrastructure",
    "tagline": "Local Kubernetes development environment tool offering instant multi-service feedback loops",
    "description": "Tilt monitors local code changes, rebuilds container images, and syncs updates to local Kubernetes clusters instantly. It serves microservice developers and cloud-native software engineers.",
    "rating": 4.8,
    "reviewsCount": 540,
    "pricing": "Free",
    "websiteUrl": "https://tilt.dev",
    "affiliateUrl": "https://tilt.dev",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "skaffold-dev",
    "name": "Skaffold",
    "domain": "skaffold.dev",
    "category": "devops-infrastructure",
    "tagline": "Google-backed open-source command-line tool facilitating continuous development on Kubernetes",
    "description": "Skaffold handles local building, pushing, and deploying workflows for Kubernetes applications as code changes occur. It is engineered for cloud developers and Kubernetes application maintainers.",
    "rating": 4.7,
    "reviewsCount": 890,
    "pricing": "Free",
    "websiteUrl": "https://skaffold.dev",
    "affiliateUrl": "https://skaffold.dev",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "850K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "telepresence-datawire",
    "name": "Telepresence",
    "domain": "telepresence.io",
    "category": "devops-infrastructure",
    "tagline": "Fast local development tool for Kubernetes microservices without cluster deployment",
    "description": "Telepresence proxies remote Kubernetes cluster traffic directly to a local development machine for instant debugging. It is built for microservice software engineers and cloud developers.",
    "rating": 4.8,
    "reviewsCount": 420,
    "pricing": "Freemium",
    "websiteUrl": "https://telepresence.io",
    "affiliateUrl": "https://telepresence.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "kustomize-io",
    "name": "Kustomize",
    "domain": "kustomize.io",
    "category": "devops-infrastructure",
    "tagline": "Template-free customization of Kubernetes YAML manifests natively built into kubectl",
    "description": "Kustomize introduces overlay structures to customize raw Kubernetes manifests across environments without template engines. It is an industry standard for Kubernetes configuration managers.",
    "rating": 4.8,
    "reviewsCount": 1650,
    "pricing": "Free",
    "websiteUrl": "https://kustomize.io",
    "affiliateUrl": "https://kustomize.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "carvel-dev",
    "name": "Carvel",
    "domain": "carvel.dev",
    "category": "devops-infrastructure",
    "tagline": "Suite of single-purpose, composable open-source tools for Kubernetes application building",
    "description": "Carvel provides modular command-line tools (ytt, kbld, kapp) to template, build, and deploy Kubernetes applications reliably. It serves Kubernetes platform engineers and DevOps architects.",
    "rating": 4.8,
    "reviewsCount": 210,
    "pricing": "Free",
    "websiteUrl": "https://carvel.dev",
    "affiliateUrl": "https://carvel.dev",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "240K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "external-secrets",
    "name": "External Secrets Operator",
    "domain": "external-secrets.io",
    "category": "devops-infrastructure",
    "tagline": "Kubernetes operator integrating external secret management systems into native secrets",
    "description": "External Secrets Operator syncs secrets securely from AWS Secrets Manager, HashiCorp Vault, or GCP into native Kubernetes Secrets. It is built for DevSecOps leads and Kubernetes administrators.",
    "rating": 4.9,
    "reviewsCount": 680,
    "pricing": "Free",
    "websiteUrl": "https://external-secrets.io",
    "affiliateUrl": "https://external-secrets.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "850K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "cert-manager",
    "name": "cert-manager",
    "domain": "cert-manager.io",
    "category": "devops-infrastructure",
    "tagline": "Automated TLS certificate management and issuance operator for Kubernetes",
    "description": "cert-manager automates requesting, renewing, and configuring TLS certificates from Let's Encrypt and private PKIs inside Kubernetes. It is an essential component for cloud-native security leads.",
    "rating": 4.9,
    "reviewsCount": 1950,
    "pricing": "Free",
    "websiteUrl": "https://cert-manager.io",
    "affiliateUrl": "https://cert-manager.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "velero-io",
    "name": "Velero",
    "domain": "velero.io",
    "category": "devops-infrastructure",
    "tagline": "Open-source backup, disaster recovery, and migration tool for Kubernetes clusters",
    "description": "Velero backs up Kubernetes cluster resources and persistent volumes safely to S3-compatible cloud storage buckets. It is designed for SREs, cluster administrators, and disaster recovery leads.",
    "rating": 4.9,
    "reviewsCount": 1150,
    "pricing": "Free",
    "websiteUrl": "https://velero.io",
    "affiliateUrl": "https://velero.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "kyverno-io",
    "name": "Kyverno",
    "domain": "kyverno.io",
    "category": "devops-infrastructure",
    "tagline": "Kubernetes-native policy management engine for validation, mutation, and generation",
    "description": "Kyverno manages cluster policy enforcement as native Kubernetes resources without requiring custom OPA Rego programming language skills. It serves Kubernetes security teams and platform engineers.",
    "rating": 4.9,
    "reviewsCount": 540,
    "pricing": "Free",
    "websiteUrl": "https://kyverno.io",
    "affiliateUrl": "https://kyverno.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "open-policy-agent",
    "name": "Open Policy Agent (OPA)",
    "domain": "openpolicyagent.org",
    "category": "devops-infrastructure",
    "tagline": "Open-source general-purpose policy engine for unified cloud-native compliance",
    "description": "OPA decouples policy decisions from application logic using Rego code across microservices, Kubernetes, and CI/CD pipelines. It is built for security architects, DevSecOps leads, and platform teams.",
    "rating": 4.8,
    "reviewsCount": 1250,
    "pricing": "Free",
    "websiteUrl": "https://openpolicyagent.org",
    "affiliateUrl": "https://openpolicyagent.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.5M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "keda-sh",
    "name": "KEDA",
    "domain": "keda.sh",
    "category": "devops-infrastructure",
    "tagline": "Kubernetes Event-driven Autoscaling component for scaling workloads based on event metrics",
    "description": "KEDA drives Kubernetes pod autoscaling based on incoming queue depth, message streams, or custom metrics down to zero pods. It serves backend cloud developers and event-driven architecture leads.",
    "rating": 4.9,
    "reviewsCount": 850,
    "pricing": "Free",
    "websiteUrl": "https://keda.sh",
    "affiliateUrl": "https://keda.sh",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "950K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "vcluster-loft",
    "name": "vcluster (Loft)",
    "domain": "vcluster.com",
    "category": "devops-infrastructure",
    "tagline": "Create fully functional virtual Kubernetes clusters inside a namespace of a host cluster",
    "description": "vcluster spins up lightweight virtual Kubernetes clusters to provide isolated tenant environments at a fraction of standard cluster costs. It is built for platform engineering teams scaling dev environments.",
    "rating": 4.9,
    "reviewsCount": 620,
    "pricing": "Free",
    "websiteUrl": "https://vcluster.com",
    "affiliateUrl": "https://vcluster.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "780K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "testkube-io",
    "name": "Testkube",
    "domain": "testkube.io",
    "category": "devops-infrastructure",
    "tagline": "Native Kubernetes-native test execution and orchestration framework for GitOps",
    "description": "Testkube executes, schedules, and visualizes automated tests natively inside Kubernetes clusters via custom resource definitions. It serves QA engineers and DevOps teams embedding tests in GitOps.",
    "rating": 4.8,
    "reviewsCount": 240,
    "pricing": "Freemium",
    "websiteUrl": "https://testkube.io",
    "affiliateUrl": "https://testkube.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "310K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "chaos-mesh",
    "name": "Chaos Mesh",
    "domain": "chaos-mesh.org",
    "category": "devops-infrastructure",
    "tagline": "Open-source cloud-native chaos engineering platform orchestrating fault injections in Kubernetes",
    "description": "Chaos Mesh injects network latency, pod failures, kernel errors, and stress scenarios into Kubernetes applications to prove system fault tolerance. It is built for SREs and reliability engineers.",
    "rating": 4.8,
    "reviewsCount": 480,
    "pricing": "Free",
    "websiteUrl": "https://chaos-mesh.org",
    "affiliateUrl": "https://chaos-mesh.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "520K",
    "isFreeTier": true,
    "isOpenSource": true
  }
];

const saasDataPath = path.join(__dirname, '..', 'src', 'data', 'saasData.jsx');
let content = fs.readFileSync(saasDataPath, 'utf8');

const match = content.match(/export const staticSaasTools = (\[[\s\S]*?\n\]);/);
if (!match) {
  console.error('Could not find staticSaasTools in saasData.jsx');
  process.exit(1);
}

let existingTools = JSON.parse(match[1]);

const existingIds = new Set(existingTools.map(t => t.id.toLowerCase()));
const existingNames = new Set(existingTools.map(t => t.name.toLowerCase()));

let addedCount = 0;
let skippedCount = 0;

newTools.forEach(tool => {
  const normId = tool.id.toLowerCase();
  const normName = tool.name.toLowerCase();

  if (!existingIds.has(normId) && !existingNames.has(normName)) {
    existingTools.push(tool);
    existingIds.add(normId);
    existingNames.add(normName);
    addedCount++;
  } else {
    // Enrich existing tool without creating a duplicate
    const idx = existingTools.findIndex(t => t.id.toLowerCase() === normId || t.name.toLowerCase() === normName);
    if (idx !== -1) {
      existingTools[idx] = { ...existingTools[idx], category: tool.category, tagline: tool.tagline || existingTools[idx].tagline };
    }
    skippedCount++;
  }
});

const updatedArrayStr = JSON.stringify(existingTools, null, 2);
content = content.replace(/export const staticSaasTools = \[[\s\S]*?\n\];/, `export const staticSaasTools = ${updatedArrayStr};`);

fs.writeFileSync(saasDataPath, content, 'utf8');
console.log(`Ingestion Complete! Added: ${addedCount} brand new tools | Deduplicated: ${skippedCount} existing tools | Total static tools: ${existingTools.length}`);
