const fs = require('fs');
const path = require('path');

const newTools = [
  {
    "id": "notion",
    "name": "Notion",
    "domain": "notion.so",
    "category": "productivity-tools",
    "tagline": "Connected workspace for notes, tasks, databases, and wikis",
    "description": "Notion unifies note-taking, project tracking, and document collaboration into a customizable block-based workspace. It is designed for individuals, remote teams, and growing startups.",
    "rating": 4.8,
    "reviewsCount": 4200,
    "pricing": "Freemium",
    "websiteUrl": "https://notion.so",
    "affiliateUrl": "https://notion.so",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "142M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "todoist",
    "name": "Todoist",
    "domain": "todoist.com",
    "category": "productivity-tools",
    "tagline": "Intuitive task manager and daily planner for personal and team productivity",
    "description": "Todoist helps users organize, schedule, and prioritize daily tasks using natural language recognition and recurring due dates. It serves individuals and teams striving for daily task clarity.",
    "rating": 4.8,
    "reviewsCount": 3100,
    "pricing": "Freemium",
    "websiteUrl": "https://todoist.com",
    "affiliateUrl": "https://todoist.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "28.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "obsidian",
    "name": "Obsidian",
    "domain": "obsidian.md",
    "category": "productivity-tools",
    "tagline": "Sharpen your thinking with a private, extensible Markdown knowledge base",
    "description": "Obsidian stores notes as plain Markdown files locally on your device with bidirectional linking. It is built for researchers, writers, and knowledge workers building a personal second brain.",
    "rating": 4.9,
    "reviewsCount": 2800,
    "pricing": "Freemium",
    "websiteUrl": "https://obsidian.md",
    "affiliateUrl": "https://obsidian.md",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "11.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "toggl-track",
    "name": "Toggl Track",
    "domain": "toggl.com/track",
    "category": "productivity-tools",
    "tagline": "Effortless time tracking and billable hour reporting for freelancers and teams",
    "description": "Toggl Track monitors time spent across tasks and projects with one-click timers and visual reporting. It is designed for freelancers, agencies, and remote workers optimizing time allocation.",
    "rating": 4.7,
    "reviewsCount": 2100,
    "pricing": "Freemium",
    "websiteUrl": "https://toggl.com/track",
    "affiliateUrl": "https://toggl.com/track",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.6M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "ticktick",
    "name": "TickTick",
    "domain": "ticktick.com",
    "category": "productivity-tools",
    "tagline": "All-in-one task manager, habit tracker, and Pomodoro timer",
    "description": "TickTick combines to-do lists, calendar integration, habit tracking, and Pomodoro focus timers in one app. It is tailored for individuals seeking comprehensive personal organization.",
    "rating": 4.8,
    "reviewsCount": 1850,
    "pricing": "Freemium",
    "websiteUrl": "https://ticktick.com",
    "affiliateUrl": "https://ticktick.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "5.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "evernote",
    "name": "Evernote",
    "domain": "evernote.com",
    "category": "productivity-tools",
    "tagline": "Capture notes, web clippings, and documents across all devices",
    "description": "Evernote helps users save text notes, web articles, scanned documents, and audio recordings in a searchable notebook system. It is built for professionals and students capturing information on the go.",
    "rating": 4.4,
    "reviewsCount": 3800,
    "pricing": "Freemium",
    "websiteUrl": "https://evernote.com",
    "affiliateUrl": "https://evernote.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "18.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "clockify",
    "name": "Clockify",
    "domain": "clockify.me",
    "category": "productivity-tools",
    "tagline": "Free time tracker and timesheet app for teams of all sizes",
    "description": "Clockify logs project hours, billable rates, and employee timesheets through desktop and browser timers. It serves freelancers, agencies, and enterprises monitoring workforce productivity.",
    "rating": 4.7,
    "reviewsCount": 2400,
    "pricing": "Freemium",
    "websiteUrl": "https://clockify.me",
    "affiliateUrl": "https://clockify.me",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "12.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "rescetime",
    "name": "RescueTime",
    "domain": "rescuetime.com",
    "category": "productivity-tools",
    "tagline": "Automated time tracking and focus coaching software for digital habits",
    "description": "RescueTime runs quietly in the background to analyze app usage, website visits, and digital distractions. It is designed for knowledge workers seeking deep work optimization.",
    "rating": 4.5,
    "reviewsCount": 920,
    "pricing": "Free Trial",
    "websiteUrl": "https://rescuetime.com",
    "affiliateUrl": "https://rescuetime.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "raycast",
    "name": "Raycast",
    "domain": "raycast.com",
    "category": "productivity-tools",
    "tagline": "Blazingly fast, extensible Mac launcher and productivity assistant",
    "description": "Raycast controls your Mac tools, manages windows, runs custom scripts, and invokes AI extensions via a single command bar. It is tailored for developers, designers, and power Mac users.",
    "rating": 4.9,
    "reviewsCount": 1100,
    "pricing": "Freemium",
    "websiteUrl": "https://raycast.com",
    "affiliateUrl": "https://raycast.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "2.9M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "alfred",
    "name": "Alfred",
    "domain": "alfredapp.com",
    "category": "productivity-tools",
    "tagline": "Award-winning macOS launcher for productivity hotkeys and custom workflows",
    "description": "Alfred boosts Mac productivity with custom keyboard shortcuts, clipboard history, file searching, and workflow automation. It is engineered for macOS power users streamlining repetitive system tasks.",
    "rating": 4.8,
    "reviewsCount": 1450,
    "pricing": "Freemium",
    "websiteUrl": "https://alfredapp.com",
    "affiliateUrl": "https://alfredapp.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "freedom",
    "name": "Freedom",
    "domain": "freedom.to",
    "category": "productivity-tools",
    "tagline": "Block distracting websites and apps across all your devices simultaneously",
    "description": "Freedom schedules digital block sessions to restrict access to addictive social media, news, and games across mobile and desktop. It serves students and professionals building focus habits.",
    "rating": 4.7,
    "reviewsCount": 850,
    "pricing": "Free Trial",
    "websiteUrl": "https://freedom.to",
    "affiliateUrl": "https://freedom.to",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "brain-fm",
    "name": "Brain.fm",
    "domain": "brain.fm",
    "category": "productivity-tools",
    "tagline": "Functional music backed by neuroscience to improve focus and sleep",
    "description": "Brain.fm generates scientifically designed auditory neural-phase locking music to enhance focus, relaxation, and deep work. It is built for students, programmers, and professionals seeking sustained concentration.",
    "rating": 4.8,
    "reviewsCount": 1300,
    "pricing": "Free Trial",
    "websiteUrl": "https://brain.fm",
    "affiliateUrl": "https://brain.fm",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "endel",
    "name": "Endel",
    "domain": "endel.io",
    "category": "productivity-tools",
    "tagline": "AI-powered personalized soundscapes tailored to your environment and heart rate",
    "description": "Endel creates real-time adaptive soundscapes tuned to weather, location, and circadian rhythms to support focus and relaxation. It serves individuals looking to reduce stress and increase deep work capacity.",
    "rating": 4.7,
    "reviewsCount": 980,
    "pricing": "Free Trial",
    "websiteUrl": "https://endel.io",
    "affiliateUrl": "https://endel.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "mem-ai",
    "name": "Mem",
    "domain": "mem.ai",
    "category": "productivity-tools",
    "tagline": "Self-organizing workspace powered by artificial intelligence",
    "description": "Mem automatically tags, connects, and surfaces relevant notes and ideas using AI without manual folder organization. It is designed for busy professionals and writers managing large knowledge stores.",
    "rating": 4.5,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://mem.ai",
    "affiliateUrl": "https://mem.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "logseq",
    "name": "Logseq",
    "domain": "logseq.com",
    "category": "productivity-tools",
    "tagline": "Privacy-first, open-source outliner knowledge base and task manager",
    "description": "Logseq provides a local-first outliner notebook with block-level bidirectional linking and PDF annotation. It serves privacy-conscious researchers, developers, and knowledge workers.",
    "rating": 4.8,
    "reviewsCount": 890,
    "pricing": "Free",
    "websiteUrl": "https://logseq.com",
    "affiliateUrl": "https://logseq.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.5M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "roam-research",
    "name": "Roam Research",
    "domain": "roamresearch.com",
    "category": "productivity-tools",
    "tagline": "A note-taking tool for networked thought and associative brainstorming",
    "description": "Roam Research uses graph database structures and bi-directional links to connect complex thoughts and notes effortlessly. It is engineered for academic researchers, writers, and strategic thinkers.",
    "rating": 4.6,
    "reviewsCount": 1120,
    "pricing": "Paid",
    "websiteUrl": "https://roamresearch.com",
    "affiliateUrl": "https://roamresearch.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.9M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "reflect-app",
    "name": "Reflect",
    "domain": "reflect.app",
    "category": "productivity-tools",
    "tagline": "End-to-end encrypted note-taking app with built-in AI assistant and calendar sync",
    "description": "Reflect offers ultra-fast encrypted note-taking paired with instant AI transcription, web clipping, and calendar meeting integration. It serves executives and founders managing daily agendas.",
    "rating": 4.9,
    "reviewsCount": 420,
    "pricing": "Paid",
    "websiteUrl": "https://reflect.app",
    "affiliateUrl": "https://reflect.app",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "580K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "craft-do",
    "name": "Craft",
    "domain": "craft.do",
    "category": "productivity-tools",
    "tagline": "Visually stunning document editor and digital publication builder",
    "description": "Craft enables users to structure beautiful documents, notes, and visual wikis across Mac, iOS, and web. It is built for designers, creative writers, and team leaders producing polished shareable docs.",
    "rating": 4.8,
    "reviewsCount": 740,
    "pricing": "Freemium",
    "websiteUrl": "https://craft.do",
    "affiliateUrl": "https://craft.do",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.3M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "any-do",
    "name": "Any.do",
    "domain": "any.do",
    "category": "productivity-tools",
    "tagline": "Task management, daily planner, and calendar integration in one space",
    "description": "Any.do consolidates daily to-do lists, smart reminders, and calendar events into an uncluttered mobile and desktop view. It serves personal planners and small teams coordinating daily schedules.",
    "rating": 4.5,
    "reviewsCount": 2100,
    "pricing": "Freemium",
    "websiteUrl": "https://any.do",
    "affiliateUrl": "https://any.do",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "things3",
    "name": "Things 3",
    "domain": "culturedcode.com/things",
    "category": "productivity-tools",
    "tagline": "Elegantly designed personal task manager built exclusively for Apple devices",
    "description": "Things 3 organizes personal goals, daily checklists, and multi-step projects inside a beautifully crafted Apple-native UI. It is built exclusively for Mac, iPad, iPhone, and Apple Watch users.",
    "rating": 4.9,
    "reviewsCount": 1650,
    "pricing": "Paid",
    "websiteUrl": "https://culturedcode.com/things",
    "affiliateUrl": "https://culturedcode.com/things",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "omnifocus",
    "name": "OmniFocus",
    "domain": "omnigroup.com/omnifocus",
    "category": "productivity-tools",
    "tagline": "Powerful GTD-based task management for complex personal and professional workflows",
    "description": "OmniFocus applies Getting Things Done (GTD) principles with deep perspective filtering, context tags, and project deferrals. It serves power users managing high-volume complex task workloads.",
    "rating": 4.6,
    "reviewsCount": 820,
    "pricing": "Paid",
    "websiteUrl": "https://omnigroup.com/omnifocus",
    "affiliateUrl": "https://omnigroup.com/omnifocus",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "sunsama",
    "name": "Sunsama",
    "domain": "sunsama.com",
    "category": "productivity-tools",
    "tagline": "The digital daily planner that pulls tasks from all your work apps into your calendar",
    "description": "Sunsama consolidates tasks from Notion, Trello, Asana, and Gmail into a unified time-blocked daily schedule. It is engineered for knowledge workers seeking realistic workload management.",
    "rating": 4.8,
    "reviewsCount": 610,
    "pricing": "Free Trial",
    "websiteUrl": "https://sunsama.com",
    "affiliateUrl": "https://sunsama.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "akiflow",
    "name": "Akiflow",
    "domain": "akiflow.com",
    "category": "productivity-tools",
    "tagline": "Consolidate all your tasks and calendars into a single time-blocking desktop app",
    "description": "Akiflow aggregates tasks from Slack, Gmail, ClickUp, and Jira into a centralized command center for rapid time-blocking. It serves busy executives and operators maximizing daily calendar efficiency.",
    "rating": 4.8,
    "reviewsCount": 490,
    "pricing": "Free Trial",
    "websiteUrl": "https://akiflow.com",
    "affiliateUrl": "https://akiflow.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "820K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "motion",
    "name": "Motion",
    "domain": "usemotion.com",
    "category": "productivity-tools",
    "tagline": "AI calendar and task manager that automatically plans your day",
    "description": "Motion uses artificial intelligence to automatically schedule tasks, meetings, and project deadlines directly on your calendar. It is built for professionals and teams looking to automate schedule planning.",
    "rating": 4.6,
    "reviewsCount": 1250,
    "pricing": "Free Trial",
    "websiteUrl": "https://usemotion.com",
    "affiliateUrl": "https://usemotion.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "3.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "fantastical",
    "name": "Fantastical by Flexibits",
    "domain": "flexibits.com/fantastical",
    "category": "productivity-tools",
    "tagline": "Award-winning calendar and task app with natural language parsing",
    "description": "Fantastical parses natural language inputs to schedule events, manage video calls, and display weather forecasts seamlessly. It serves Apple and Windows power users seeking premium calendar control.",
    "rating": 4.8,
    "reviewsCount": 1890,
    "pricing": "Freemium",
    "websiteUrl": "https://flexibits.com/fantastical",
    "affiliateUrl": "https://flexibits.com/fantastical",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "cron-calendar",
    "name": "Notion Calendar (formerly Cron)",
    "domain": "calendar.notion.so",
    "category": "productivity-tools",
    "tagline": "Modern, beautifully designed calendar for professionals and Notion users",
    "description": "Notion Calendar provides time zone scheduling, clean keyboard navigation, and deep integration with Notion documents and tasks. It is tailored for remote teams and modern digital workers.",
    "rating": 4.9,
    "reviewsCount": 950,
    "pricing": "Free",
    "websiteUrl": "https://calendar.notion.so",
    "affiliateUrl": "https://calendar.notion.so",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "morgen",
    "name": "Morgen",
    "domain": "morgen.so",
    "category": "productivity-tools",
    "tagline": "Unified calendar, task manager, and scheduling link platform",
    "description": "Morgen aggregates multiple calendar accounts, to-do managers, and personalized booking links into one desktop interface. It serves freelancers, consultants, and remote workers.",
    "rating": 4.8,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://morgen.so",
    "affiliateUrl": "https://morgen.so",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "focus-at-will",
    "name": "Focus@Will",
    "domain": "focusatwill.com",
    "category": "productivity-tools",
    "tagline": "Neuroscience-based music library optimized to extend focus duration",
    "description": "Focus@Will offers specialized instrumental music channels tailored to individual brain types to prevent distraction. It is designed for students, writers, and programmers working long hours.",
    "rating": 4.5,
    "reviewsCount": 540,
    "pricing": "Free Trial",
    "websiteUrl": "https://focusatwill.com",
    "affiliateUrl": "https://focusatwill.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "410K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "cold-turkey",
    "name": "Cold Turkey",
    "domain": "getcoldturkey.com",
    "category": "productivity-tools",
    "tagline": "The toughest website and application blocker on the internet",
    "description": "Cold Turkey enforces strict distraction-blocking by locking selected desktop apps, websites, or the entire computer during focus windows. It serves students and professionals needing unbreakable focus boundaries.",
    "rating": 4.9,
    "reviewsCount": 810,
    "pricing": "Freemium",
    "websiteUrl": "https://getcoldturkey.com",
    "affiliateUrl": "https://getcoldturkey.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "890K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "forest-app",
    "name": "Forest",
    "domain": "forestapp.cc",
    "category": "productivity-tools",
    "tagline": "Gamified focus timer that helps you put down your phone and plant real trees",
    "description": "Forest turns focus sessions into a virtual tree-growing game, encouraging users to stay off their phones to build a lush forest. It is popular among students and digital habit improvers.",
    "rating": 4.8,
    "reviewsCount": 3100,
    "pricing": "Paid",
    "websiteUrl": "https://forestapp.cc",
    "affiliateUrl": "https://forestapp.cc",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "focusmate",
    "name": "Focusmate",
    "domain": "focusmate.com",
    "category": "productivity-tools",
    "tagline": "Virtual co-working sessions for accountability and deep work concentration",
    "description": "Focusmate pairs users with live accountability partners worldwide for timed 25, 50, or 75-minute silent work video sessions. It serves freelancers, remote workers, and ADHD individuals building focus routines.",
    "rating": 4.9,
    "reviewsCount": 1420,
    "pricing": "Freemium",
    "websiteUrl": "https://focusmate.com",
    "affiliateUrl": "https://focusmate.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "session-app",
    "name": "Session",
    "domain": "stayinsession.org",
    "category": "productivity-tools",
    "tagline": "Pomodoro focus timer with analytics and website blocking for Apple platforms",
    "description": "Session combines Pomodoro focus tracking, website blocking, intention setting, and detailed focus analytics on iOS and macOS. It is built for Apple users seeking mindful productivity routines.",
    "rating": 4.8,
    "reviewsCount": 410,
    "pricing": "Freemium",
    "websiteUrl": "https://stayinsession.org",
    "affiliateUrl": "https://stayinsession.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "210K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "pomo-focus",
    "name": "Pomofocus",
    "domain": "pomofocus.io",
    "category": "productivity-tools",
    "tagline": "Clean, customizable browser-based Pomodoro timer with task management",
    "description": "Pomofocus provides a lightweight online timer that breaks work sessions into 25-minute focus intervals and breaks. It is free and widely used by students and casual desktop workers.",
    "rating": 4.7,
    "reviewsCount": 1650,
    "pricing": "Free",
    "websiteUrl": "https://pomofocus.io",
    "affiliateUrl": "https://pomofocus.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "9.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "textexpander",
    "name": "TextExpander",
    "domain": "textexpander.com",
    "category": "productivity-tools",
    "tagline": "Type faster and eliminate repetitive typing with custom text shortcuts",
    "description": "TextExpander replaces short custom keyboard abbreviations with full email templates, code snippets, and standard text blocks. It is engineered for customer support, sales reps, and writers.",
    "rating": 4.6,
    "reviewsCount": 1100,
    "pricing": "Paid",
    "websiteUrl": "https://textexpander.com",
    "affiliateUrl": "https://textexpander.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "espanso",
    "name": "Espanso",
    "domain": "espanso.org",
    "category": "productivity-tools",
    "tagline": "Cross-platform, open-source text expander powered by Rust",
    "description": "Espanso offers fast, system-wide text expansion and custom script triggers configured via clean YAML files. It serves developers, privacy purists, and command-line enthusiasts.",
    "rating": 4.9,
    "reviewsCount": 520,
    "pricing": "Free",
    "websiteUrl": "https://espanso.org",
    "affiliateUrl": "https://espanso.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "clean-shot-x",
    "name": "CleanShot X",
    "domain": "cleanshot.com",
    "category": "productivity-tools",
    "tagline": "The ultimate screen capture and recording tool for macOS",
    "description": "CleanShot X provides screenshot editing, scrolling captures, quick annotations, and cloud link sharing on Mac. It is widely considered an indispensable utility for designers, writers, and developers.",
    "rating": 4.9,
    "reviewsCount": 1820,
    "pricing": "Paid",
    "websiteUrl": "https://cleanshot.com",
    "affiliateUrl": "https://cleanshot.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.6M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "snagit",
    "name": "TechSmith Snagit",
    "domain": "techsmith.com/screen-capture.html",
    "category": "productivity-tools",
    "tagline": "Screen capture and visual documentation software for team tutorials",
    "description": "Snagit captures screenshots and screen video recordings, adding visual callouts, step numbers, and graphic edits. It is built for corporate trainers, technical writers, and support documentation creators.",
    "rating": 4.7,
    "reviewsCount": 2400,
    "pricing": "Paid",
    "websiteUrl": "https://techsmith.com/screen-capture.html",
    "affiliateUrl": "https://techsmith.com/screen-capture.html",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "shottr",
    "name": "Shottr",
    "domain": "shottr.cc",
    "category": "productivity-tools",
    "tagline": "Blazingly fast, lightweight screenshot measurement and annotation app for Mac",
    "description": "Shottr provides instant Mac pixel-measuring, text recognition (OCR), color picking, and screenshot annotations. It serves UI/UX designers, frontend engineers, and digital creators.",
    "rating": 4.9,
    "reviewsCount": 680,
    "pricing": "Freemium",
    "websiteUrl": "https://shottr.cc",
    "affiliateUrl": "https://shottr.cc",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "510K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "readwise",
    "name": "Readwise",
    "domain": "readwise.io",
    "category": "productivity-tools",
    "tagline": "Consolidate and review your digital highlights from Kindle, web, and articles",
    "description": "Readwise gathers highlights from Kindle, web articles, podcasts, and Twitter, resurfacing them via daily spaced-repetition emails. It is designed for lifelong learners and readers building a knowledge system.",
    "rating": 4.9,
    "reviewsCount": 1150,
    "pricing": "Paid",
    "websiteUrl": "https://readwise.io",
    "affiliateUrl": "https://readwise.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "2.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "readwise-reader",
    "name": "Readwise Reader",
    "domain": "readwise.io/read",
    "category": "productivity-tools",
    "tagline": "The power-user read-it-later app built for articles, newsletters, PDFs, and EPUBs",
    "description": "Reader offers text-to-speech, web highlight syncing, ghost-reader AI summaries, and RSS feeds in an intuitive reader UI. It serves heavy researchers, academics, and digital readers.",
    "rating": 4.9,
    "reviewsCount": 890,
    "pricing": "Paid",
    "websiteUrl": "https://readwise.io/read",
    "affiliateUrl": "https://readwise.io/read",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "pocket",
    "name": "Mozilla Pocket",
    "domain": "getpocket.com",
    "category": "productivity-tools",
    "tagline": "Save articles, videos, and stories from across the web to read offline",
    "description": "Pocket lets users bookmark web content across devices to read later in a clean, distraction-free reader interface. It is built for casual readers capturing web content on mobile and desktop.",
    "rating": 4.5,
    "reviewsCount": 2900,
    "pricing": "Freemium",
    "websiteUrl": "https://getpocket.com",
    "affiliateUrl": "https://getpocket.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "14.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "instapaper",
    "name": "Instapaper",
    "domain": "instapaper.com",
    "category": "productivity-tools",
    "tagline": "A simple tool for saving web pages to read later on iOS, Android, and Kindle",
    "description": "Instapaper extracts clean text from articles for distraction-free reading, highlighting, and offline sync across devices. It serves long-form article readers and Kindle enthusiasts.",
    "rating": 4.6,
    "reviewsCount": 1100,
    "pricing": "Freemium",
    "websiteUrl": "https://instapaper.com",
    "affiliateUrl": "https://instapaper.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "wallabag",
    "name": "Wallabag",
    "domain": "wallabag.org",
    "category": "productivity-tools",
    "tagline": "Self-hostable, open-source read-it-later web article archiver",
    "description": "Wallabag extracts and saves web articles to your personal server, providing offline reading, tagging, and RSS feeds. It serves open-source advocates wanting total data privacy over saved links.",
    "rating": 4.7,
    "reviewsCount": 310,
    "pricing": "Free",
    "websiteUrl": "https://wallabag.org",
    "affiliateUrl": "https://wallabag.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "240K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "habitica",
    "name": "Habitica",
    "domain": "habitica.com",
    "category": "productivity-tools",
    "tagline": "Gamify your life by turning tasks and habits into an RPG role-playing game",
    "description": "Habitica treats daily habits, to-do lists, and chores like monsters to defeat, awarding XP, gold, and gear upon task completion. It serves gamers and students seeking gamified habit motivation.",
    "rating": 4.6,
    "reviewsCount": 2100,
    "pricing": "Freemium",
    "websiteUrl": "https://habitica.com",
    "affiliateUrl": "https://habitica.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "streaks-app",
    "name": "Streaks",
    "domain": "streaksapp.com",
    "category": "productivity-tools",
    "tagline": "The Apple Design Award-winning habit tracking app",
    "description": "Streaks tracks good habits and routine completion, encouraging daily momentum with customizable targets and Apple Health integration. It serves iOS users building healthy daily routines.",
    "rating": 4.8,
    "reviewsCount": 1420,
    "pricing": "Paid",
    "websiteUrl": "https://streaksapp.com",
    "affiliateUrl": "https://streaksapp.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "820K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "paste-app",
    "name": "Paste",
    "domain": "pasteapp.io",
    "category": "productivity-tools",
    "tagline": "Smart clipboard manager for Mac and iOS with unlimited search history",
    "description": "Paste saves everything you copy on Mac or iPhone, allowing quick search and organization of text clips, images, and links. It is designed for creators, developers, and writers copying content daily.",
    "rating": 4.8,
    "reviewsCount": 980,
    "pricing": "Paid",
    "websiteUrl": "https://pasteapp.io",
    "affiliateUrl": "https://pasteapp.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "950K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "maccy",
    "name": "Maccy",
    "domain": "maccy.app",
    "category": "productivity-tools",
    "tagline": "Lightweight, open-source clipboard manager for macOS",
    "description": "Maccy keeps a searchable history of everything you copy to your clipboard without unnecessary UI bloat or tracking. It is engineered for Mac power users preferring minimal open-source utilities.",
    "rating": 4.9,
    "reviewsCount": 620,
    "pricing": "Free",
    "websiteUrl": "https://maccy.app",
    "affiliateUrl": "https://maccy.app",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "380K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "magnet-mac",
    "name": "Magnet",
    "domain": "magnet.crowdcafe.com",
    "category": "productivity-tools",
    "tagline": "Intuitive window manager for macOS with keyboard shortcuts and snap zones",
    "description": "Magnet arranges Mac application windows into split screens and side-by-side quadrants using simple drag zones or hotkeys. It serves multi-taskers organizing crowded Mac desktop displays.",
    "rating": 4.8,
    "reviewsCount": 3800,
    "pricing": "Paid",
    "websiteUrl": "https://magnet.crowdcafe.com",
    "affiliateUrl": "https://magnet.crowdcafe.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "rectangle-mac",
    "name": "Rectangle",
    "domain": "rectangleapp.com",
    "category": "productivity-tools",
    "tagline": "Free, open-source macOS window management app using keyboard shortcuts",
    "description": "Rectangle snaps desktop windows into clean screen partitions via hotkeys and mouse drags without consuming system resources. It is popular among Mac power users seeking free, open-source window snapping.",
    "rating": 4.9,
    "reviewsCount": 2100,
    "pricing": "Free",
    "websiteUrl": "https://rectangleapp.com",
    "affiliateUrl": "https://rectangleapp.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "centered-app",
    "name": "Centered",
    "domain": "centered.app",
    "category": "productivity-tools",
    "tagline": "AI focus coach, task manager, and flow-state music player for deep work",
    "description": "Centered combines task time-boxing, ambient focus tracks, and an AI coach that gently nudges you back to work when you drift off-task. It is tailored for remote workers looking to build focus discipline.",
    "rating": 4.7,
    "reviewsCount": 340,
    "pricing": "Freemium",
    "websiteUrl": "https://centered.app",
    "affiliateUrl": "https://centered.app",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "280K",
    "isFreeTier": true,
    "isOpenSource": false
  }
];

const saasDataPath = path.join(__dirname, '..', 'src', 'data', 'saasData.jsx');
let content = fs.readFileSync(saasDataPath, 'utf8');

const match = content.match(/export const staticSaasTools = (\[[\s\S]*?\n\]);/);
if (!match) {
  console.error('Could not find staticSaasTools in saasData.jsx');
  process.exit(1);
}

let existingTools = JSON.parse(match[1]);

const existingIds = new Set(existingTools.map(t => t.id.toLowerCase()));
const existingNames = new Set(existingTools.map(t => t.name.toLowerCase()));

let addedCount = 0;
let skippedCount = 0;

newTools.forEach(tool => {
  const normId = tool.id.toLowerCase();
  const normName = tool.name.toLowerCase();

  if (!existingIds.has(normId) && !existingNames.has(normName)) {
    existingTools.push(tool);
    existingIds.add(normId);
    existingNames.add(normName);
    addedCount++;
  } else {
    // Enrich existing tool without creating a duplicate
    const idx = existingTools.findIndex(t => t.id.toLowerCase() === normId || t.name.toLowerCase() === normName);
    if (idx !== -1) {
      existingTools[idx] = { ...existingTools[idx], category: tool.category, tagline: tool.tagline || existingTools[idx].tagline };
    }
    skippedCount++;
  }
});

const updatedArrayStr = JSON.stringify(existingTools, null, 2);
content = content.replace(/export const staticSaasTools = \[[\s\S]*?\n\];/, `export const staticSaasTools = ${updatedArrayStr};`);

fs.writeFileSync(saasDataPath, content, 'utf8');
console.log(`Ingestion Complete! Added: ${addedCount} brand new tools | Deduplicated: ${skippedCount} existing tools | Total static tools: ${existingTools.length}`);
