const fs = require('fs');
const path = require('path');

const newTools = [
  {
    "id": "airtable",
    "name": "Airtable",
    "domain": "airtable.com",
    "category": "nocode-databases",
    "tagline": "The low-code platform for building collaborative relational database apps",
    "description": "Airtable combines the simplicity of a spreadsheet with the relational data power of a database. It is designed for marketing teams, project managers, and operations leaders looking to create custom workflows.",
    "rating": 4.8,
    "reviewsCount": 2450,
    "pricing": "Freemium",
    "websiteUrl": "https://airtable.com",
    "affiliateUrl": "https://airtable.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "16.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "notion",
    "name": "Notion",
    "domain": "notion.so",
    "category": "nocode-databases",
    "tagline": "Connected workspace for docs, relational databases, wikis, and tasks",
    "description": "Notion allows users to organize knowledge, projects, and custom databases inside a unified block-based editor. It serves solopreneurs, startups, and remote teams building tailored work operating systems.",
    "rating": 4.8,
    "reviewsCount": 4200,
    "pricing": "Freemium",
    "websiteUrl": "https://notion.so",
    "affiliateUrl": "https://notion.so",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "142M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "zapier",
    "name": "Zapier",
    "domain": "zapier.com",
    "category": "nocode-databases",
    "tagline": "Automate workflows across thousands of web applications effortlessly",
    "description": "Zapier connects web apps via trigger-and-action workflows called Zaps without writing a single line of code. It is designed for businesses of all sizes looking to automate repetitive tasks.",
    "rating": 4.7,
    "reviewsCount": 3100,
    "pricing": "Freemium",
    "websiteUrl": "https://zapier.com",
    "affiliateUrl": "https://zapier.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "24.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "make",
    "name": "Make",
    "domain": "make.com",
    "category": "nocode-databases",
    "tagline": "Visual automation platform to design, build, and automate complex workflows",
    "description": "Make provides an interactive drag-and-drop canvas to build visual data pipelines and app integrations. It is ideal for power users, developers, and automation agencies seeking advanced multi-step logic.",
    "rating": 4.8,
    "reviewsCount": 1850,
    "pricing": "Freemium",
    "websiteUrl": "https://make.com",
    "affiliateUrl": "https://make.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "9.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "n8n",
    "name": "n8n",
    "domain": "n8n.io",
    "category": "nocode-databases",
    "tagline": "Fair-code node-based workflow automation platform for tech teams",
    "description": "n8n offers a flexible workflow editor that can be hosted on-premise or used in the cloud to connect internal APIs. It is built for developers and technical teams prioritizing data privacy and custom code nodes.",
    "rating": 4.8,
    "reviewsCount": 940,
    "pricing": "Freemium",
    "websiteUrl": "https://n8n.io",
    "affiliateUrl": "https://n8n.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "3.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "bubble",
    "name": "Bubble",
    "domain": "bubble.io",
    "category": "nocode-databases",
    "tagline": "Full-stack no-code web application platform for building complex products",
    "description": "Bubble enables non-technical founders to design responsive interfaces, structure databases, and program complex business logic. It is optimized for startups launching full-featured SaaS web applications.",
    "rating": 4.6,
    "reviewsCount": 1420,
    "pricing": "Freemium",
    "websiteUrl": "https://bubble.io",
    "affiliateUrl": "https://bubble.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "3.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "softr",
    "name": "Softr",
    "domain": "softr.io",
    "category": "nocode-databases",
    "tagline": "Turn Airtable and Google Sheets into powerful client portals and web apps",
    "description": "Softr allows users to create membership portals, internal tools, and directories directly on top of database sources. It is popular among non-coders and agencies building fast web applications.",
    "rating": 4.8,
    "reviewsCount": 520,
    "pricing": "Freemium",
    "websiteUrl": "https://softr.io",
    "affiliateUrl": "https://softr.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "glide",
    "name": "Glide",
    "domain": "glideapps.com",
    "category": "nocode-databases",
    "tagline": "Create mobile apps and internal business tools from spreadsheets and databases",
    "description": "Glide converts data from Google Sheets, Airtable, or SQL databases into intuitive mobile and desktop applications. It is tailored for operations teams requiring internal workflow tools.",
    "rating": 4.7,
    "reviewsCount": 680,
    "pricing": "Freemium",
    "websiteUrl": "https://glideapps.com",
    "affiliateUrl": "https://glideapps.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.9M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "supabase",
    "name": "Supabase",
    "domain": "supabase.com",
    "category": "nocode-databases",
    "tagline": "The open-source Firebase alternative providing real-time Postgres backends",
    "description": "Supabase provides developers with an instant Postgres database, authentication, row-level security, and auto-generated APIs. It serves engineers building scalable mobile and web applications.",
    "rating": 4.9,
    "reviewsCount": 1890,
    "pricing": "Freemium",
    "websiteUrl": "https://supabase.com",
    "affiliateUrl": "https://supabase.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "5.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "xano",
    "name": "Xano",
    "domain": "xano.com",
    "category": "nocode-databases",
    "tagline": "The scalable no-code backend engine for web and mobile apps",
    "description": "Xano gives users a flexible Postgres database, business logic builder, and REST API generator without writing code. It is designed for no-code developers seeking enterprise-grade backend infrastructure.",
    "rating": 4.8,
    "reviewsCount": 310,
    "pricing": "Freemium",
    "websiteUrl": "https://xano.com",
    "affiliateUrl": "https://xano.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "retool",
    "name": "Retool",
    "domain": "retool.com",
    "category": "nocode-databases",
    "tagline": "Fast development platform to build custom internal tools and admin panels",
    "description": "Retool connects pre-built visual UI components to databases, APIs, and business logic quickly. It is engineered for software developers building internal dashboards and operational tools.",
    "rating": 4.7,
    "reviewsCount": 820,
    "pricing": "Freemium",
    "websiteUrl": "https://retool.com",
    "affiliateUrl": "https://retool.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "appsmith",
    "name": "Appsmith",
    "domain": "appsmith.com",
    "category": "nocode-databases",
    "tagline": "Open-source low-code framework to build internal admin applications",
    "description": "Appsmith allows engineering teams to drag and drop UI components to connect with databases and REST APIs. It is ideal for developers building secure internal tools on self-hosted servers.",
    "rating": 4.7,
    "reviewsCount": 490,
    "pricing": "Freemium",
    "websiteUrl": "https://appsmith.com",
    "affiliateUrl": "https://appsmith.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "850K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "flutterflow",
    "name": "FlutterFlow",
    "domain": "flutterflow.io",
    "category": "nocode-databases",
    "tagline": "Build native cross-platform mobile and web applications visually",
    "description": "FlutterFlow enables users to build native Flutter apps visually, structure Firebase/Supabase backends, and export clean Dart code. It serves mobile app creators, designers, and software agencies.",
    "rating": 4.7,
    "reviewsCount": 980,
    "pricing": "Freemium",
    "websiteUrl": "https://flutterflow.io",
    "affiliateUrl": "https://flutterflow.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "adalo",
    "name": "Adalo",
    "domain": "adalo.com",
    "category": "nocode-databases",
    "tagline": "Design and publish native iOS, Android, and web applications without code",
    "description": "Adalo provides a drag-and-drop user interface to construct database-driven mobile apps with dynamic layouts. It is built for entrepreneurs and small businesses launching custom mobile products.",
    "rating": 4.4,
    "reviewsCount": 430,
    "pricing": "Freemium",
    "websiteUrl": "https://adalo.com",
    "affiliateUrl": "https://adalo.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "690K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "nocodb",
    "name": "NocoDB",
    "domain": "nocodb.com",
    "category": "nocode-databases",
    "tagline": "Open-source Airtable alternative turning any database into a smart spreadsheet",
    "description": "NocoDB transforms existing MySQL, PostgreSQL, or SQLite databases into visual spreadsheet interfaces with API generation. It is targeted at privacy-conscious developers and open-source teams.",
    "rating": 4.8,
    "reviewsCount": 710,
    "pricing": "Freemium",
    "websiteUrl": "https://nocodb.com",
    "affiliateUrl": "https://nocodb.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "520K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "baserow",
    "name": "Baserow",
    "domain": "baserow.io",
    "category": "nocode-databases",
    "tagline": "Open-source no-code database and application builder",
    "description": "Baserow offers an open-source database platform allowing users to create relational structures and modular web interfaces. It is designed for businesses needing self-hosted data control.",
    "rating": 4.7,
    "reviewsCount": 340,
    "pricing": "Freemium",
    "websiteUrl": "https://baserow.io",
    "affiliateUrl": "https://baserow.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "380K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "coda",
    "name": "Coda",
    "domain": "coda.io",
    "category": "nocode-databases",
    "tagline": "All-in-one collaborative doc that brings words, data, and workflows together",
    "description": "Coda blends document writing with powerful relational tables, automation packs, and interactive buttons. It serves modern product management and operations teams organizing complex project data.",
    "rating": 4.7,
    "reviewsCount": 1150,
    "pricing": "Freemium",
    "websiteUrl": "https://coda.io",
    "affiliateUrl": "https://coda.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "smartsuite",
    "name": "SmartSuite",
    "domain": "smartsuite.com",
    "category": "nocode-databases",
    "tagline": "Work management platform for managing workflows, projects, and business data",
    "description": "SmartSuite combines project management capabilities with structured database record management. It is built for growing businesses looking to centralize operations and team workflows.",
    "rating": 4.8,
    "reviewsCount": 290,
    "pricing": "Freemium",
    "websiteUrl": "https://smartsuite.com",
    "affiliateUrl": "https://smartsuite.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "450K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "fibery",
    "name": "Fibery",
    "domain": "fibery.io",
    "category": "nocode-databases",
    "tagline": "Connected workspace to build custom work management systems and wikis",
    "description": "Fibery allows users to connect custom relational databases, product roadmaps, and document wikis together. It is designed for product development teams and tech startups looking for deep customization.",
    "rating": 4.8,
    "reviewsCount": 210,
    "pricing": "Freemium",
    "websiteUrl": "https://fibery.io",
    "affiliateUrl": "https://fibery.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "290K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "fillout",
    "name": "Fillout",
    "domain": "fillout.com",
    "category": "nocode-databases",
    "tagline": "Advanced form builder native to Airtable, Notion, and SQL databases",
    "description": "Fillout lets creators build multi-step forms, user portals, and surveys that directly read and update external databases. It is tailored for modern teams collecting structured data.",
    "rating": 4.9,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://fillout.com",
    "affiliateUrl": "https://fillout.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "780K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "tally",
    "name": "Tally",
    "domain": "tally.so",
    "category": "nocode-databases",
    "tagline": "Simple Notion-like form builder with unlimited responses",
    "description": "Tally uses a document-style slash-command editor to quickly construct custom forms and surveys. It is built for creators, startups, and marketers requiring clean form automation.",
    "rating": 4.9,
    "reviewsCount": 610,
    "pricing": "Freemium",
    "websiteUrl": "https://tally.so",
    "affiliateUrl": "https://tally.so",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "workato",
    "name": "Workato",
    "domain": "workato.com",
    "category": "nocode-databases",
    "tagline": "Enterprise-grade integration and workflow automation platform",
    "description": "Workato automates complex enterprise workflows and data syncs across SaaS applications and databases. It serves enterprise IT, security, and business operations divisions.",
    "rating": 4.7,
    "reviewsCount": 480,
    "pricing": "Paid",
    "websiteUrl": "https://workato.com",
    "affiliateUrl": "https://workato.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "tray-io",
    "name": "Tray.io",
    "domain": "tray.io",
    "category": "nocode-databases",
    "tagline": "AI-powered enterprise integration and workflow automation engine",
    "description": "Tray.io provides a visual integration platform to orchestrate complex data flows between core enterprise systems. It is engineered for enterprise IT teams and revenue operations managers.",
    "rating": 4.5,
    "reviewsCount": 310,
    "pricing": "Paid",
    "websiteUrl": "https://tray.io",
    "affiliateUrl": "https://tray.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "520K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "activepieces",
    "name": "Activepieces",
    "domain": "activepieces.com",
    "category": "nocode-databases",
    "tagline": "Open-source Zapier alternative for workflow automation and AI agents",
    "description": "Activepieces provides an open-source workflow automation builder with community piece integrations and local hosting support. It is built for developers and privacy-first teams.",
    "rating": 4.8,
    "reviewsCount": 180,
    "pricing": "Freemium",
    "websiteUrl": "https://activepieces.com",
    "affiliateUrl": "https://activepieces.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "240K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "pipedream",
    "name": "Pipedream",
    "domain": "pipedream.com",
    "category": "nocode-databases",
    "tagline": "Integration platform for developers to build event-driven workflows",
    "description": "Pipedream combines low-code visual triggers with custom Node.js and Python code execution. It serves software engineers seeking fast API integration without managing infrastructure.",
    "rating": 4.8,
    "reviewsCount": 540,
    "pricing": "Freemium",
    "websiteUrl": "https://pipedream.com",
    "affiliateUrl": "https://pipedream.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.3M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "pocketbase",
    "name": "PocketBase",
    "domain": "pocketbase.io",
    "category": "nocode-databases",
    "tagline": "Open-source single file backend consisting of embedded SQLite database",
    "description": "PocketBase packages an embedded SQLite database, user authentication, file storage, and real-time subscriptions into a single binary. It is ideal for developers building small-to-medium web applications.",
    "rating": 4.9,
    "reviewsCount": 620,
    "pricing": "Free",
    "websiteUrl": "https://pocketbase.io",
    "affiliateUrl": "https://pocketbase.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "680K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "appsheet",
    "name": "Google AppSheet",
    "domain": "about.appsheet.com",
    "category": "nocode-databases",
    "tagline": "Google Cloud's no-code platform to build custom web and mobile apps",
    "description": "AppSheet allows users to convert Google Workspace sheets, Excel files, and cloud databases into functional mobile applications. It is tailored for enterprise productivity and field operations.",
    "rating": 4.5,
    "reviewsCount": 980,
    "pricing": "Freemium",
    "websiteUrl": "https://about.appsheet.com",
    "affiliateUrl": "https://about.appsheet.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "microsoft-power-apps",
    "name": "Microsoft Power Apps",
    "domain": "powerapps.microsoft.com",
    "category": "nocode-databases",
    "tagline": "Build professional-grade enterprise applications quickly with low code",
    "description": "Power Apps enables corporate employees to construct custom business applications connected to Microsoft 365 and Dataverse. It is designed for enterprise digital transformation and business analyst workflows.",
    "rating": 4.5,
    "reviewsCount": 1650,
    "pricing": "Paid",
    "websiteUrl": "https://powerapps.microsoft.com",
    "affiliateUrl": "https://powerapps.microsoft.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "5.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "microsoft-power-automate",
    "name": "Microsoft Power Automate",
    "domain": "powerautomate.microsoft.com",
    "category": "nocode-databases",
    "tagline": "Streamline repetitive tasks and business processes with automated workflows",
    "description": "Power Automate automates workflows between enterprise cloud services, desktop legacy software, and Microsoft applications. It serves corporate teams optimizing operational tasks.",
    "rating": 4.6,
    "reviewsCount": 1890,
    "pricing": "Paid",
    "websiteUrl": "https://powerautomate.microsoft.com",
    "affiliateUrl": "https://powerautomate.microsoft.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "6.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "directus",
    "name": "Directus",
    "domain": "directus.io",
    "category": "nocode-databases",
    "tagline": "Open-source data platform wrapping any SQL database with dynamic APIs and app",
    "description": "Directus overlays existing SQL databases with a real-time admin app and automatic REST/GraphQL APIs. It is engineered for developers and content managers seeking control over native database schemas.",
    "rating": 4.8,
    "reviewsCount": 410,
    "pricing": "Freemium",
    "websiteUrl": "https://directus.io",
    "affiliateUrl": "https://directus.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "490K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "strapi",
    "name": "Strapi",
    "domain": "strapi.io",
    "category": "nocode-databases",
    "tagline": "Leading open-source headless CMS for customizable content APIs",
    "description": "Strapi empowers developers to define custom content schemas and manage database content via automatically generated APIs. It serves software teams building modern Jamstack web applications.",
    "rating": 4.7,
    "reviewsCount": 1240,
    "pricing": "Freemium",
    "websiteUrl": "https://strapi.io",
    "affiliateUrl": "https://strapi.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "sanity",
    "name": "Sanity",
    "domain": "sanity.io",
    "category": "nocode-databases",
    "tagline": "Composable content platform with real-time collaborative database studio",
    "description": "Sanity treats content as structured data, providing an open-source React editing studio connected to a scalable backend. It is built for digital agencies and product teams publishing multi-channel media.",
    "rating": 4.8,
    "reviewsCount": 780,
    "pricing": "Freemium",
    "websiteUrl": "https://sanity.io",
    "affiliateUrl": "https://sanity.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "stacker",
    "name": "Stacker",
    "domain": "stackerhq.com",
    "category": "nocode-databases",
    "tagline": "Build custom portals and internal tools powered by your business data",
    "description": "Stacker transforms data from Airtable, Google Sheets, or SQL databases into polished customer portals and internal tools. It is designed for businesses needing secure granular access permissions.",
    "rating": 4.6,
    "reviewsCount": 170,
    "pricing": "Paid",
    "websiteUrl": "https://stackerhq.com",
    "affiliateUrl": "https://stackerhq.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "210K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "noloco",
    "name": "Noloco",
    "domain": "noloco.io",
    "category": "nocode-databases",
    "tagline": "No-code app builder for client portals and internal tools from your data",
    "description": "Noloco auto-generates responsive web apps connected to Airtable, Postgres, or Google Sheets with customizable user roles. It is tailored for agencies, real estate managers, and SMB operations.",
    "rating": 4.9,
    "reviewsCount": 130,
    "pricing": "Paid",
    "websiteUrl": "https://noloco.io",
    "affiliateUrl": "https://noloco.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "160K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "rowy",
    "name": "Rowy",
    "domain": "rowy.io",
    "category": "nocode-databases",
    "tagline": "Low-code database platform for Google Cloud Firestore in a spreadsheet UI",
    "description": "Rowy provides a visual spreadsheet interface to manage GCP Firestore data and build Cloud Functions in code. It serves developers looking for fast backend data management.",
    "rating": 4.8,
    "reviewsCount": 150,
    "pricing": "Freemium",
    "websiteUrl": "https://rowy.io",
    "affiliateUrl": "https://rowy.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "120K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "app-builder-weweb",
    "name": "WeWeb",
    "domain": "weweb.io",
    "category": "nocode-databases",
    "tagline": "Build visual frontends on top of any database and API backend",
    "description": "WeWeb allows creators to design visual web applications while connecting to backends like Supabase, Xano, or REST APIs. It is optimized for agencies building secure, hosted web applications.",
    "rating": 4.8,
    "reviewsCount": 240,
    "pricing": "Freemium",
    "websiteUrl": "https://weweb.io",
    "affiliateUrl": "https://weweb.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "310K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "toddle",
    "name": "toddle",
    "domain": "toddle.dev",
    "category": "nocode-databases",
    "tagline": "The visual web application builder for building production-grade software",
    "description": "toddle offers a visual editor built around modern web standards, component trees, and state management. It is designed for founders and product teams scaling web applications without code lock-in.",
    "rating": 4.9,
    "reviewsCount": 110,
    "pricing": "Freemium",
    "websiteUrl": "https://toddle.dev",
    "affiliateUrl": "https://toddle.dev",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "140K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "plasmic",
    "name": "Plasmic",
    "domain": "plasmic.app",
    "category": "nocode-databases",
    "tagline": "Visual page builder and CMS platform that integrates into codebase stacks",
    "description": "Plasmic enables designers to build visual interfaces that integrate directly into React, Next.js, and custom codebases. It serves engineering teams delegating web UI creation to marketing.",
    "rating": 4.7,
    "reviewsCount": 290,
    "pricing": "Freemium",
    "websiteUrl": "https://plasmic.app",
    "affiliateUrl": "https://plasmic.app",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "280K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "budibase",
    "name": "Budibase",
    "domain": "budibase.com",
    "category": "nocode-databases",
    "tagline": "Open-source low-code platform for building internal apps and forms",
    "description": "Budibase allows developers to quickly generate internal applications, forms, and admin panels on top of existing databases. It is optimized for enterprise teams focusing on self-hosting and security.",
    "rating": 4.8,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://budibase.com",
    "affiliateUrl": "https://budibase.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "410K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "tooljet",
    "name": "ToolJet",
    "domain": "tooljet.com",
    "category": "nocode-databases",
    "tagline": "Open-source low-code framework to build internal tools and automations",
    "description": "ToolJet connects to databases, cloud storage, and APIs to assemble internal business applications. It is tailored for developers seeking an extensible, open-source internal tool engine.",
    "rating": 4.7,
    "reviewsCount": 320,
    "pricing": "Freemium",
    "websiteUrl": "https://tooljet.com",
    "affiliateUrl": "https://tooljet.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "350K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "illadysk",
    "name": "ILLA Cloud",
    "domain": "illacloud.com",
    "category": "nocode-databases",
    "tagline": "Low-code open-source platform for building internal tools and AI agents",
    "description": "ILLA Cloud combines low-code application building with custom AI agent workflows and database integrations. It serves developers seeking to automate business logic alongside visual UI elements.",
    "rating": 4.7,
    "reviewsCount": 190,
    "pricing": "Freemium",
    "websiteUrl": "https://illacloud.com",
    "affiliateUrl": "https://illacloud.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "220K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "appgyver-composer",
    "name": "SAP Build Apps",
    "domain": "sap.com",
    "category": "nocode-databases",
    "tagline": "Professional no-code app development platform for enterprise systems",
    "description": "SAP Build Apps (formerly AppGyver) allows users to construct web and mobile applications visually with enterprise connectors. It serves corporate teams extending SAP enterprise software workflows.",
    "rating": 4.4,
    "reviewsCount": 410,
    "pricing": "Free Trial",
    "websiteUrl": "https://sap.com",
    "affiliateUrl": "https://sap.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "8.9M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "superblocks",
    "name": "Superblocks",
    "domain": "superblocks.com",
    "category": "nocode-databases",
    "tagline": "Enterprise programmable platform to build internal tools and workflows fast",
    "description": "Superblocks provides developers with a visual IDE to build internal apps, background jobs, and scheduled workflows. It is built for enterprise engineering organizations scaling internal tool building.",
    "rating": 4.9,
    "reviewsCount": 140,
    "pricing": "Paid",
    "websiteUrl": "https://superblocks.com",
    "affiliateUrl": "https://superblocks.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "180K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "steedos",
    "name": "Steedos",
    "domain": "steedos.com",
    "category": "nocode-databases",
    "tagline": "Open-source low-code enterprise application architecture platform",
    "description": "Steedos offers an open-source alternative to Salesforce for building enterprise CRM, ERP, and internal management tools. It is designed for IT architects requiring customizable data schemas.",
    "rating": 4.6,
    "reviewsCount": 95,
    "pricing": "Freemium",
    "websiteUrl": "https://steedos.com",
    "affiliateUrl": "https://steedos.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "90K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "backendless",
    "name": "Backendless",
    "domain": "backendless.com",
    "category": "nocode-databases",
    "tagline": "Visual app development platform combining UI builder and backend engine",
    "description": "Backendless offers visual database management, real-time messaging, user management, and visual API logic builders. It is engineered for developers and visual builders deploying web and mobile products.",
    "rating": 4.5,
    "reviewsCount": 260,
    "pricing": "Freemium",
    "websiteUrl": "https://backendless.com",
    "affiliateUrl": "https://backendless.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "210K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "zenaton",
    "name": "Zenaton",
    "domain": "zenaton.com",
    "category": "nocode-databases",
    "tagline": "Workflow engine for developers to run asynchronous background tasks",
    "description": "Zenaton helps software developers build, monitor, and execute event-driven workflows and background tasks. It serves technical leads handling complex serverless automation logic.",
    "rating": 4.6,
    "reviewsCount": 110,
    "pricing": "Freemium",
    "websiteUrl": "https://zenaton.com",
    "affiliateUrl": "https://zenaton.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "80K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "draftbit",
    "name": "Draftbit",
    "domain": "draftbit.com",
    "category": "nocode-databases",
    "tagline": "Visual mobile app builder that outputs native React Native source code",
    "description": "Draftbit allows creators to build mobile apps visually while maintaining full access to underlying React Native code. It is designed for developers and product designers requiring source-code ownership.",
    "rating": 4.6,
    "reviewsCount": 170,
    "pricing": "Paid",
    "websiteUrl": "https://draftbit.com",
    "affiliateUrl": "https://draftbit.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "130K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "kuika",
    "name": "Kuika",
    "domain": "kuika.com",
    "category": "nocode-databases",
    "tagline": "Low-code application platform for enterprise mobile and web development",
    "description": "Kuika enables business analysts and developers to construct cross-platform enterprise applications with visual data binding. It serves enterprise organizations accelerating custom internal software releases.",
    "rating": 4.5,
    "reviewsCount": 85,
    "pricing": "Paid",
    "websiteUrl": "https://kuika.com",
    "affiliateUrl": "https://kuika.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "60K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "kintone",
    "name": "Kintone",
    "domain": "kintone.com",
    "category": "nocode-databases",
    "tagline": "No-code enterprise workspace for team collaboration, databases, and workflows",
    "description": "Kintone allows non-technical business users to build custom database apps, track workflows, and manage team communication. It is optimized for enterprise business management and operations teams.",
    "rating": 4.6,
    "reviewsCount": 450,
    "pricing": "Paid",
    "websiteUrl": "https://kintone.com",
    "affiliateUrl": "https://kintone.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "fastgen",
    "name": "Fastgen",
    "domain": "fastgen.com",
    "category": "nocode-databases",
    "tagline": "Low-code backend builder for creating APIs, workflows, and database logic",
    "description": "Fastgen provides a visual platform to construct serverless backends, connect database tables, and deploy APIs fast. It serves startup developers and no-code builders needing scalable app logic.",
    "rating": 4.8,
    "reviewsCount": 120,
    "pricing": "Freemium",
    "websiteUrl": "https://fastgen.com",
    "affiliateUrl": "https://fastgen.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "110K",
    "isFreeTier": true,
    "isOpenSource": false
  }
];

const saasDataPath = path.join(__dirname, '..', 'src', 'data', 'saasData.jsx');
let content = fs.readFileSync(saasDataPath, 'utf8');

const match = content.match(/export const staticSaasTools = (\[[\s\S]*?\n\]);/);
if (!match) {
  console.error('Could not find staticSaasTools in saasData.jsx');
  process.exit(1);
}

let existingTools = JSON.parse(match[1]);

const existingIds = new Set(existingTools.map(t => t.id.toLowerCase()));
const existingNames = new Set(existingTools.map(t => t.name.toLowerCase()));

let addedCount = 0;
let skippedCount = 0;

newTools.forEach(tool => {
  const normId = tool.id.toLowerCase();
  const normName = tool.name.toLowerCase();

  if (!existingIds.has(normId) && !existingNames.has(normName)) {
    existingTools.push(tool);
    existingIds.add(normId);
    existingNames.add(normName);
    addedCount++;
  } else {
    // Enrich existing tool without creating a duplicate
    const idx = existingTools.findIndex(t => t.id.toLowerCase() === normId || t.name.toLowerCase() === normName);
    if (idx !== -1) {
      existingTools[idx] = { ...existingTools[idx], category: tool.category, tagline: tool.tagline || existingTools[idx].tagline };
    }
    skippedCount++;
  }
});

const updatedArrayStr = JSON.stringify(existingTools, null, 2);
content = content.replace(/export const staticSaasTools = \[[\s\S]*?\n\];/, `export const staticSaasTools = ${updatedArrayStr};`);

fs.writeFileSync(saasDataPath, content, 'utf8');
console.log(`Ingestion Complete! Added: ${addedCount} brand new tools | Deduplicated: ${skippedCount} existing tools | Total static tools: ${existingTools.length}`);
