const fs = require('fs');
const path = require('path');

const newTools = [
  {
    "id": "midjourney",
    "name": "Midjourney",
    "domain": "midjourney.com",
    "category": "ai-image-video",
    "tagline": "State-of-the-art artistic and photorealistic AI image generation",
    "description": "Midjourney generates highly detailed artwork, photorealistic images, and conceptual visual assets from text prompts. It serves digital artists, graphic designers, and creative directors worldwide.",
    "rating": 4.9,
    "reviewsCount": 3800,
    "pricing": "Paid",
    "websiteUrl": "https://midjourney.com",
    "affiliateUrl": "https://midjourney.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "24.5M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "runway",
    "name": "Runway",
    "domain": "runwayml.com",
    "category": "ai-image-video",
    "tagline": "Generative AI video generation and creative editing suite",
    "description": "Runway provides text-to-video and image-to-video generation with motion brush and camera controls. It is built for filmmakers, video editors, and visual content creators.",
    "rating": 4.8,
    "reviewsCount": 2100,
    "pricing": "Freemium",
    "websiteUrl": "https://runwayml.com",
    "affiliateUrl": "https://runwayml.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "12.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "pika",
    "name": "Pika",
    "domain": "pika.art",
    "category": "ai-image-video",
    "tagline": "Idea-to-video platform for dynamic animations and video effects",
    "description": "Pika generates and edits animated video clips from text prompts or still images with precise motion modification. It serves animators, social media creators, and digital marketers.",
    "rating": 4.7,
    "reviewsCount": 1250,
    "pricing": "Freemium",
    "websiteUrl": "https://pika.art",
    "affiliateUrl": "https://pika.art",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "8.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "luma-dream-machine",
    "name": "Luma Dream Machine",
    "domain": "lumalabs.ai",
    "category": "ai-image-video",
    "tagline": "High-fidelity cinematic AI video generator and 3D scene capture",
    "description": "Luma Dream Machine converts text prompts and static images into fluid, realistic cinematic video clips. It is designed for creative storytellers, visual artists, and game developers.",
    "rating": 4.8,
    "reviewsCount": 940,
    "pricing": "Freemium",
    "websiteUrl": "https://lumalabs.ai",
    "affiliateUrl": "https://lumalabs.ai",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "9.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "synthesia",
    "name": "Synthesia",
    "domain": "synthesia.io",
    "category": "ai-image-video",
    "tagline": "AI avatar video generator for corporate training and presentations",
    "description": "Synthesia turns text scripts into studio-quality videos featuring realistic digital avatars speaking in 140+ languages. It is tailored for L&D professionals, corporate trainers, and educators.",
    "rating": 4.7,
    "reviewsCount": 1850,
    "pricing": "Paid",
    "websiteUrl": "https://synthesia.io",
    "affiliateUrl": "https://synthesia.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "6.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "heygen",
    "name": "HeyGen",
    "domain": "heygen.com",
    "category": "ai-image-video",
    "tagline": "AI video generation and multi-language lip-sync video translation",
    "description": "HeyGen creates personalized avatar videos and translates existing video dialogue with lip-sync matching across multiple languages. It serves marketing agencies, sales reps, and content creators.",
    "rating": 4.8,
    "reviewsCount": 1620,
    "pricing": "Freemium",
    "websiteUrl": "https://heygen.com",
    "affiliateUrl": "https://heygen.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "11.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "leonardo-ai",
    "name": "Leonardo.Ai",
    "domain": "leonardo.ai",
    "category": "ai-image-video",
    "tagline": "Generative AI asset suite for game production and concept art",
    "description": "Leonardo.Ai offers fine-tuned generative models for character assets, game design, texture mapping, and concept visuals. It is built for game developers, illustrators, and digital artists.",
    "rating": 4.8,
    "reviewsCount": 2400,
    "pricing": "Freemium",
    "websiteUrl": "https://leonardo.ai",
    "affiliateUrl": "https://leonardo.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "14.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "ideogram",
    "name": "Ideogram",
    "domain": "ideogram.ai",
    "category": "ai-image-video",
    "tagline": "AI image generator with precise text rendering and graphic typography",
    "description": "Ideogram excels at generating legible typography and clean text inside AI-generated logos, poster art, and graphic designs. It serves graphic designers, brand strategists, and apparel creators.",
    "rating": 4.8,
    "reviewsCount": 1150,
    "pricing": "Freemium",
    "websiteUrl": "https://ideogram.ai",
    "affiliateUrl": "https://ideogram.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "10.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "recraft",
    "name": "Recraft",
    "domain": "recraft.ai",
    "category": "ai-image-video",
    "tagline": "AI design canvas for generating raster, SVG vector art, and 3D graphics",
    "description": "Recraft provides an infinite canvas enabling designers to generate scalable vector illustrations, 3D assets, and branded graphic sets. It is engineered for UI/UX designers and brand illustrators.",
    "rating": 4.9,
    "reviewsCount": 850,
    "pricing": "Freemium",
    "websiteUrl": "https://recraft.ai",
    "affiliateUrl": "https://recraft.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.9M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "d-id",
    "name": "D-ID",
    "domain": "d-id.com",
    "category": "ai-image-video",
    "tagline": "Generative AI photo animation and digital human agent platform",
    "description": "D-ID transforms still portrait photos into speaking digital avatar videos using uploaded audio files or text-to-speech engines. It serves customer service teams, educators, and video creators.",
    "rating": 4.6,
    "reviewsCount": 1320,
    "pricing": "Freemium",
    "websiteUrl": "https://d-id.com",
    "affiliateUrl": "https://d-id.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "invideo-ai",
    "name": "InVideo AI",
    "domain": "invideo.io",
    "category": "ai-image-video",
    "tagline": "Prompt-to-video generator with script, voiceover, and stock footage",
    "description": "InVideo AI converts text prompts into fully edited videos complete with scripted voiceovers, media selection, and subtitles. It is designed for social media marketers, YouTubers, and agencies.",
    "rating": 4.6,
    "reviewsCount": 2850,
    "pricing": "Freemium",
    "websiteUrl": "https://invideo.io",
    "affiliateUrl": "https://invideo.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "8.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "kling-ai",
    "name": "Kling AI",
    "domain": "klingai.com",
    "category": "ai-image-video",
    "tagline": "Advanced generative AI video engine for realistic long-clip synthesis",
    "description": "Kling AI generates extended, high-resolution video sequences from prompts with high physical accuracy and character consistency. It is built for visual artists, filmmakers, and digital studios.",
    "rating": 4.8,
    "reviewsCount": 720,
    "pricing": "Freemium",
    "websiteUrl": "https://klingai.com",
    "affiliateUrl": "https://klingai.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "6.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "krea-ai",
    "name": "Krea AI",
    "domain": "krea.ai",
    "category": "ai-image-video",
    "tagline": "Real-time interactive AI image generation, upscaling, and pattern design",
    "description": "Krea AI outputs real-time visual generations as you draw on canvas, offering high-resolution upscaling and pattern synthesis. It serves concept artists, designers, and visual strategists.",
    "rating": 4.8,
    "reviewsCount": 980,
    "pricing": "Freemium",
    "websiteUrl": "https://krea.ai",
    "affiliateUrl": "https://krea.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "5.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "magnific-ai",
    "name": "Magnific AI",
    "domain": "magnific.ai",
    "category": "ai-image-video",
    "tagline": "Ultra-high resolution AI image upscaler and detail enhancement engine",
    "description": "Magnific AI enhances and upscales low-resolution imagery into hyper-detailed 8K visuals using controlled generative hallucination. It is used by photographers, digital artists, and print designers.",
    "rating": 4.9,
    "reviewsCount": 610,
    "pricing": "Paid",
    "websiteUrl": "https://magnific.ai",
    "affiliateUrl": "https://magnific.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "opus-pro",
    "name": "OpusClip",
    "domain": "opus.pro",
    "category": "ai-image-video",
    "tagline": "AI video clipping tool converting long recordings into viral shorts",
    "description": "OpusClip analyzes long-form videos to extract, reframe, score, and caption short vertical clips for TikTok and Reels. It is tailored for podcasters, YouTubers, and content marketers.",
    "rating": 4.7,
    "reviewsCount": 1950,
    "pricing": "Freemium",
    "websiteUrl": "https://opus.pro",
    "affiliateUrl": "https://opus.pro",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "7.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "captions-ai",
    "name": "Captions",
    "domain": "captions.ai",
    "category": "ai-image-video",
    "tagline": "AI studio for talking-head video editing, subtitling, and eye contact alignment",
    "description": "Captions automates word-by-word animated subtitles, AI dubbing, background noise suppression, and eye-tracking correction. It serves mobile creators, educators, and social media influencers.",
    "rating": 4.8,
    "reviewsCount": 1410,
    "pricing": "Paid",
    "websiteUrl": "https://captions.ai",
    "affiliateUrl": "https://captions.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "kaiber-ai",
    "name": "Kaiber",
    "domain": "kaiber.ai",
    "category": "ai-image-video",
    "tagline": "AI creative studio for stylized animation and music video visualizers",
    "description": "Kaiber transforms existing footage or text prompts into stylized, artistic animations and music visualizers. It is popular among musicians, video directors, and visual artists.",
    "rating": 4.6,
    "reviewsCount": 890,
    "pricing": "Paid",
    "websiteUrl": "https://kaiber.ai",
    "affiliateUrl": "https://kaiber.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "viggle-ai",
    "name": "Viggle",
    "domain": "viggle.ai",
    "category": "ai-image-video",
    "tagline": "Controllable character animation and physics movement generator",
    "description": "Viggle allows creators to animate custom character imagery using existing motion reference clips with realistic body movement physics. It is built for meme creators, animators, and social video creators.",
    "rating": 4.7,
    "reviewsCount": 650,
    "pricing": "Freemium",
    "websiteUrl": "https://viggle.ai",
    "affiliateUrl": "https://viggle.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "photoroom",
    "name": "Photoroom",
    "domain": "photoroom.com",
    "category": "ai-image-video",
    "tagline": "AI product photo editing, background removal, and studio photographer",
    "description": "Photoroom removes photo backgrounds instantly and replaces them with AI-generated studio scenes. It is tailored for e-commerce sellers, resellers, and digital product marketers.",
    "rating": 4.8,
    "reviewsCount": 3100,
    "pricing": "Freemium",
    "websiteUrl": "https://photoroom.com",
    "affiliateUrl": "https://photoroom.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "18.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "adobe-firefly",
    "name": "Adobe Firefly",
    "domain": "firefly.adobe.com",
    "category": "ai-image-video",
    "tagline": "Commercially safe generative AI models integrated into Adobe Creative Cloud",
    "description": "Adobe Firefly generates royalty-free imagery, vector graphics, and text effects trained on licensed Adobe Stock content. It serves professional graphic designers, agencies, and enterprise creatives.",
    "rating": 4.7,
    "reviewsCount": 2900,
    "pricing": "Freemium",
    "websiteUrl": "https://firefly.adobe.com",
    "affiliateUrl": "https://firefly.adobe.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "16.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "submagic-co",
    "name": "Submagic",
    "domain": "submagic.co",
    "category": "ai-image-video",
    "tagline": "AI captions, b-roll generation, and sound effects for short videos",
    "description": "Submagic enhances short videos with trend-aligned captions, auto-inserted stock B-roll, and sound effects. It is designed for TikTokers, Instagram Reels creators, and performance marketers.",
    "rating": 4.7,
    "reviewsCount": 820,
    "pricing": "Paid",
    "websiteUrl": "https://submagic.co",
    "affiliateUrl": "https://submagic.co",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "colossyan",
    "name": "Colossyan",
    "domain": "colossyan.com",
    "category": "ai-image-video",
    "tagline": "AI video creator for workplace learning and corporate training",
    "description": "Colossyan transforms PDF documents and presentations into interactive training videos hosted by synthetic human avatars. It serves corporate L&D teams and HR training specialists.",
    "rating": 4.7,
    "reviewsCount": 540,
    "pricing": "Paid",
    "websiteUrl": "https://colossyan.com",
    "affiliateUrl": "https://colossyan.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "fliki",
    "name": "Fliki",
    "domain": "fliki.ai",
    "category": "ai-image-video",
    "tagline": "Text-to-video and text-to-speech creator powered by realistic AI voices",
    "description": "Fliki converts blog posts, scripts, and tweets into narrated video content using stock media libraries and voice synthesis. It is built for content marketers, bloggers, and podcasters.",
    "rating": 4.6,
    "reviewsCount": 1820,
    "pricing": "Freemium",
    "websiteUrl": "https://fliki.ai",
    "affiliateUrl": "https://fliki.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "pictory-ai",
    "name": "Pictory",
    "domain": "pictory.ai",
    "category": "ai-image-video",
    "tagline": "Automated short-form video creation from long-form text content",
    "description": "Pictory extracts key highlights from long webinars and turns articles or scripts into branded video summaries. It is designed for digital marketers, course creators, and agency owners.",
    "rating": 4.5,
    "reviewsCount": 1450,
    "pricing": "Paid",
    "websiteUrl": "https://pictory.ai",
    "affiliateUrl": "https://pictory.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.9M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "elai-io",
    "name": "Elai.io",
    "domain": "elai.io",
    "category": "ai-image-video",
    "tagline": "Build presenter-led AI videos from plain text or website URLs",
    "description": "Elai.io allows users to produce presenter-led video training modules featuring custom human avatars from simple script inputs. It serves corporate trainers, e-learning creators, and HR teams.",
    "rating": 4.6,
    "reviewsCount": 480,
    "pricing": "Freemium",
    "websiteUrl": "https://elai.io",
    "affiliateUrl": "https://elai.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "850K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "deepbrain-ai",
    "name": "DeepBrain AI",
    "domain": "deepbrain.io",
    "category": "ai-image-video",
    "tagline": "Photorealistic AI human avatars for video generation and broadcasts",
    "description": "DeepBrain AI produces conversational human avatar models suitable for news broadcasts, training videos, and virtual kiosks. It is tailored for media enterprises and corporate communications.",
    "rating": 4.5,
    "reviewsCount": 380,
    "pricing": "Paid",
    "websiteUrl": "https://deepbrain.io",
    "affiliateUrl": "https://deepbrain.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "920K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "hour-one",
    "name": "Hour One",
    "domain": "hourone.ai",
    "category": "ai-image-video",
    "tagline": "AI video generator converting text into video presentations",
    "description": "Hour One automates professional video production for e-learning, customer support, and internal news using virtual hosts. It is built for enterprise training and communications divisions.",
    "rating": 4.5,
    "reviewsCount": 310,
    "pricing": "Freemium",
    "websiteUrl": "https://hourone.ai",
    "affiliateUrl": "https://hourone.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "610K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "getmunch",
    "name": "Munch",
    "domain": "getmunch.com",
    "category": "ai-image-video",
    "tagline": "AI clip extraction and content repurposing for social video marketing",
    "description": "Munch extracts trending snippets from long-form video content based on social analytics data and auto-crops for vertical feeds. It serves media buyers, agencies, and content strategists.",
    "rating": 4.7,
    "reviewsCount": 780,
    "pricing": "Paid",
    "websiteUrl": "https://getmunch.com",
    "affiliateUrl": "https://getmunch.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "klap-app",
    "name": "Klap",
    "domain": "klap.app",
    "category": "ai-image-video",
    "tagline": "Turn long YouTube videos into viral TikToks and Shorts in 1 click",
    "description": "Klap uses AI to detect captivating video moments, apply dynamic face reframing, and render auto-captions for short-form clips. It serves social media managers and video creators.",
    "rating": 4.7,
    "reviewsCount": 610,
    "pricing": "Freemium",
    "websiteUrl": "https://klap.app",
    "affiliateUrl": "https://klap.app",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "vizard-ai",
    "name": "Vizard",
    "domain": "vizard.ai",
    "category": "ai-image-video",
    "tagline": "AI video editor that turns long recordings into short clips",
    "description": "Vizard automatically splits webinars, podcasts, and Zoom calls into social-ready video clips with custom layout templates. It is designed for remote teams, podcasters, and marketers.",
    "rating": 4.6,
    "reviewsCount": 520,
    "pricing": "Freemium",
    "websiteUrl": "https://vizard.ai",
    "affiliateUrl": "https://vizard.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "vidyo-ai",
    "name": "Vidyo.ai",
    "domain": "vidyo.ai",
    "category": "ai-image-video",
    "tagline": "Content repurposing platform for podcasters and video creators",
    "description": "Vidyo.ai converts long-form podcasts and interviews into short, caption-enriched videos optimized for Instagram, Shorts, and TikTok. It serves content creators and social media teams.",
    "rating": 4.5,
    "reviewsCount": 1100,
    "pricing": "Freemium",
    "websiteUrl": "https://vidyo.ai",
    "affiliateUrl": "https://vidyo.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "tavus",
    "name": "Tavus",
    "domain": "tavus.io",
    "category": "ai-image-video",
    "tagline": "Programmatic personalized video generation API for sales and product ops",
    "description": "Tavus clones your voice and face to generate thousands of personalized sales outreach videos automatically via API. It is engineered for enterprise sales teams and growth marketers.",
    "rating": 4.8,
    "reviewsCount": 240,
    "pricing": "Paid",
    "websiteUrl": "https://tavus.io",
    "affiliateUrl": "https://tavus.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "450K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "bhuman-ai",
    "name": "BHuman",
    "domain": "bhuman.ai",
    "category": "ai-image-video",
    "tagline": "Personalized video messaging at scale with AI voice and video cloning",
    "description": "BHuman records one base video and automatically adjusts spoken variables to deliver personalized video messages to prospective leads. It serves sales reps, e-commerce stores, and recruiters.",
    "rating": 4.5,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://bhuman.ai",
    "affiliateUrl": "https://bhuman.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "380K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "domoai-app",
    "name": "DomoAI",
    "domain": "domoai.app",
    "category": "ai-image-video",
    "tagline": "Transform real footage into anime and stylized animations",
    "description": "DomoAI converts live-action footage into consistent anime, 3D render, or comic book visual styles. It serves video editors, animators, and digital visual creators.",
    "rating": 4.7,
    "reviewsCount": 510,
    "pricing": "Freemium",
    "websiteUrl": "https://domoai.app",
    "affiliateUrl": "https://domoai.app",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.9M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "pixverse-ai",
    "name": "PixVerse",
    "domain": "pixverse.ai",
    "category": "ai-image-video",
    "tagline": "Generative AI video platform for high-resolution motion clips",
    "description": "PixVerse converts text prompts and still imagery into expressive video scenes with customized visual style filters. It is built for creative artists, animators, and digital marketers.",
    "rating": 4.6,
    "reviewsCount": 420,
    "pricing": "Freemium",
    "websiteUrl": "https://pixverse.ai",
    "affiliateUrl": "https://pixverse.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "ltx-studio",
    "name": "LTX Studio",
    "domain": "ltx.studio",
    "category": "ai-image-video",
    "tagline": "AI-driven filmmaking and visual storyboard production platform",
    "description": "LTX Studio provides multi-shot control over script development, character consistency, shot angles, and scene editing for filmmakers. It serves movie directors, animators, and ad creators.",
    "rating": 4.8,
    "reviewsCount": 350,
    "pricing": "Freemium",
    "websiteUrl": "https://ltx.studio",
    "affiliateUrl": "https://ltx.studio",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "steve-ai",
    "name": "Steve.ai",
    "domain": "steve.ai",
    "category": "ai-image-video",
    "tagline": "AI video maker for live-action and 2D animated explainer videos",
    "description": "Steve.ai converts text scripts into 2D animation or live-action stock videos using automated asset matching. It is tailored for content creators, HR teams, and educators.",
    "rating": 4.4,
    "reviewsCount": 890,
    "pricing": "Freemium",
    "websiteUrl": "https://steve.ai",
    "affiliateUrl": "https://steve.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "lumen5",
    "name": "Lumen5",
    "domain": "lumen5.com",
    "category": "ai-image-video",
    "tagline": "Turns blog posts and articles into video ad collateral",
    "description": "Lumen5 matches written text with relevant video clips, overlay typography, and music to assemble video ads. It serves content marketers, brand teams, and social media managers.",
    "rating": 4.5,
    "reviewsCount": 1650,
    "pricing": "Freemium",
    "websiteUrl": "https://lumen5.com",
    "affiliateUrl": "https://lumen5.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "artbreeder",
    "name": "Artbreeder",
    "domain": "artbreeder.com",
    "category": "ai-image-video",
    "tagline": "Collaborative image blending and character gene creation platform",
    "description": "Artbreeder combines and mutates image characteristics to create unique portraits, landscapes, and anime art concepts. It is designed for creative artists, fantasy authors, and game designers.",
    "rating": 4.6,
    "reviewsCount": 1200,
    "pricing": "Freemium",
    "websiteUrl": "https://artbreeder.com",
    "affiliateUrl": "https://artbreeder.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.9M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "seaart-ai",
    "name": "SeaArt",
    "domain": "seaart.ai",
    "category": "ai-image-video",
    "tagline": "AI creative tool for image rendering, ControlNet, and portrait art",
    "description": "SeaArt provides an AI art generator equipped with ControlNet parameters, image-to-image styling, and photo restoration. It serves digital artists, illustrators, and anime designers.",
    "rating": 4.7,
    "reviewsCount": 910,
    "pricing": "Freemium",
    "websiteUrl": "https://seaart.ai",
    "affiliateUrl": "https://seaart.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "5.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "civitai",
    "name": "Civitai",
    "domain": "civitai.com",
    "category": "ai-image-video",
    "tagline": "The open-source AI model media repository and prompt generation hub",
    "description": "Civitai serves as an open platform for sharing custom AI image generation models, LoRAs, visual style presets, and prompt ideas. It is built for open-source AI artists and model trainers.",
    "rating": 4.9,
    "reviewsCount": 3100,
    "pricing": "Freemium",
    "websiteUrl": "https://civitai.com",
    "affiliateUrl": "https://civitai.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "28.5M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "patterned-ai",
    "name": "Patterned AI",
    "domain": "patterned.ai",
    "category": "ai-image-video",
    "tagline": "AI seamless pattern generator for print and web graphics",
    "description": "Patterned AI generates seamless, royalty-free background graphics for surface prints, packaging design, and web backgrounds. It serves textile designers, brand managers, and artists.",
    "rating": 4.6,
    "reviewsCount": 180,
    "pricing": "Freemium",
    "websiteUrl": "https://patterned.ai",
    "affiliateUrl": "https://patterned.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "180K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "lets-enhance",
    "name": "Let's Enhance",
    "domain": "letsenhance.io",
    "category": "ai-image-video",
    "tagline": "Automated AI image upscale and quality enhancement software",
    "description": "Let's Enhance fixes pixelation, increases image resolution up to 16x, and adjusts color balance for print and web. It serves e-commerce managers, photographers, and graphic designers.",
    "rating": 4.6,
    "reviewsCount": 1100,
    "pricing": "Freemium",
    "websiteUrl": "https://letsenhance.io",
    "affiliateUrl": "https://letsenhance.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "topaz-gigapixel",
    "name": "Topaz Gigapixel AI",
    "domain": "topazlabs.com/gigapixel-ai",
    "category": "ai-image-video",
    "tagline": "Desktop AI image upscaler and detail restorer for high-res printing",
    "description": "Topaz Gigapixel AI recovers fine details and textures in low-resolution photos up to 600% enlargement. It is engineered for professional photographers, printmakers, and digital archivists.",
    "rating": 4.8,
    "reviewsCount": 1650,
    "pricing": "Paid",
    "websiteUrl": "https://topazlabs.com/gigapixel-ai",
    "affiliateUrl": "https://topazlabs.com/gigapixel-ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "pebblely",
    "name": "Pebblely",
    "domain": "pebblely.com",
    "category": "ai-image-video",
    "tagline": "AI product photography generator for e-commerce brands",
    "description": "Pebblely transforms simple product photos into professional studio-shot promotional visuals in seconds. It serves e-commerce store owners, social media managers, and ad agencies.",
    "rating": 4.7,
    "reviewsCount": 420,
    "pricing": "Freemium",
    "websiteUrl": "https://pebblely.com",
    "affiliateUrl": "https://pebblely.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "950K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "flair-ai",
    "name": "Flair AI",
    "domain": "flair.ai",
    "category": "ai-image-video",
    "tagline": "AI design tool for branded content and product photography",
    "description": "Flair AI provides a drag-and-drop canvas for composing product shoots with custom 3D props and realistic lighting. It is built for DTC brands, creative directors, and ad designers.",
    "rating": 4.8,
    "reviewsCount": 510,
    "pricing": "Freemium",
    "websiteUrl": "https://flair.ai",
    "affiliateUrl": "https://flair.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "mokker-ai",
    "name": "Mokker AI",
    "domain": "mokker.ai",
    "category": "ai-image-video",
    "tagline": "Instant background generator for product photo catalogs",
    "description": "Mokker AI replaces plain product photo backgrounds with realistic lifestyle environments suitable for digital marketing. It serves e-commerce catalog managers and social advertisers.",
    "rating": 4.6,
    "reviewsCount": 310,
    "pricing": "Freemium",
    "websiteUrl": "https://mokker.ai",
    "affiliateUrl": "https://mokker.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "meshy-ai",
    "name": "Meshy",
    "domain": "meshy.ai",
    "category": "ai-image-video",
    "tagline": "Text and image to 3D model generator for game developers and designers",
    "description": "Meshy converts text descriptions or 2D images into textured 3D meshes in minutes. It serves game developers, 3D artists, and AR/VR content creators.",
    "rating": 4.7,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://meshy.ai",
    "affiliateUrl": "https://meshy.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "820K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "clipdrop-uncrop",
    "name": "Clipdrop Uncrop",
    "domain": "clipdrop.co/uncrop",
    "category": "ai-image-video",
    "tagline": "AI aspect ratio expander and image outpainting tool",
    "description": "Clipdrop Uncrop expands the canvas boundaries of photos using AI to fill in background details seamlessly. It is tailored for graphic designers, web editors, and digital marketers.",
    "rating": 4.7,
    "reviewsCount": 890,
    "pricing": "Freemium",
    "websiteUrl": "https://clipdrop.co/uncrop",
    "affiliateUrl": "https://clipdrop.co/uncrop",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "wondershare-virbo",
    "name": "Wondershare Virbo",
    "domain": "virbo.wondershare.com",
    "category": "ai-image-video",
    "tagline": "AI avatar video creator for global marketing and e-commerce",
    "description": "Wondershare Virbo offers 300+ realistic avatars and multi-language translation tools to generate video ads quickly. It serves global e-commerce sellers and social media marketers.",
    "rating": 4.5,
    "reviewsCount": 620,
    "pricing": "Freemium",
    "websiteUrl": "https://virbo.wondershare.com",
    "affiliateUrl": "https://virbo.wondershare.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": false
  }
];

const saasDataPath = path.join(__dirname, '..', 'src', 'data', 'saasData.jsx');
let content = fs.readFileSync(saasDataPath, 'utf8');

const match = content.match(/export const staticSaasTools = (\[[\s\S]*?\n\]);/);
if (!match) {
  console.error('Could not find staticSaasTools in saasData.jsx');
  process.exit(1);
}

let existingTools = JSON.parse(match[1]);

const existingIds = new Set(existingTools.map(t => t.id.toLowerCase()));
const existingNames = new Set(existingTools.map(t => t.name.toLowerCase()));

let addedCount = 0;
let skippedCount = 0;

newTools.forEach(tool => {
  const normId = tool.id.toLowerCase();
  const normName = tool.name.toLowerCase();

  if (!existingIds.has(normId) && !existingNames.has(normName)) {
    existingTools.push(tool);
    existingIds.add(normId);
    existingNames.add(normName);
    addedCount++;
  } else {
    // Enrich existing tool without creating a duplicate
    const idx = existingTools.findIndex(t => t.id.toLowerCase() === normId || t.name.toLowerCase() === normName);
    if (idx !== -1) {
      existingTools[idx] = { ...existingTools[idx], category: tool.category, tagline: tool.tagline || existingTools[idx].tagline };
    }
    skippedCount++;
  }
});

const updatedArrayStr = JSON.stringify(existingTools, null, 2);
content = content.replace(/export const staticSaasTools = \[[\s\S]*?\n\];/, `export const staticSaasTools = ${updatedArrayStr};`);

fs.writeFileSync(saasDataPath, content, 'utf8');
console.log(`Ingestion Complete! Added: ${addedCount} brand new tools | Deduplicated: ${skippedCount} existing tools | Total static tools: ${existingTools.length}`);
