const fs = require('fs');
const path = require('path');

const newTools = [
  {
    "id": "dagster",
    "name": "Dagster",
    "domain": "dagster.io",
    "category": "bi-data-analytics",
    "tagline": "Declarative, asset-based orchestrator for building, testing, and observing data pipelines",
    "description": "Dagster orchestrates data assets through a software-defined asset paradigm rather than traditional task DAGs. It serves data engineers and analytics leads building testable, observed data pipelines.",
    "rating": 4.9,
    "reviewsCount": 1150,
    "pricing": "Freemium",
    "websiteUrl": "https://dagster.io",
    "affiliateUrl": "https://dagster.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "apache-airflow",
    "name": "Apache Airflow",
    "domain": "airflow.apache.org",
    "category": "bi-data-analytics",
    "tagline": "Open-source programmatic workflow orchestration engine for complex data pipelines",
    "description": "Apache Airflow allows engineers to author, schedule, and monitor data workflows as Directed Acyclic Graphs (DAGs) in Python. It is an industry standard for data engineers and platform architects.",
    "rating": 4.6,
    "reviewsCount": 4200,
    "pricing": "Free",
    "websiteUrl": "https://airflow.apache.org",
    "affiliateUrl": "https://airflow.apache.org",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "3.5M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "prefect",
    "name": "Prefect",
    "domain": "prefect.io",
    "category": "bi-data-analytics",
    "tagline": "Modern workflow orchestration engine built for Python-native data pipelines",
    "description": "Prefect turns any Python function into a tracked, resilient step in a distributed data pipeline with automatic retries and state tracking. It serves data scientists and data engineers.",
    "rating": 4.8,
    "reviewsCount": 980,
    "pricing": "Freemium",
    "websiteUrl": "https://prefect.io",
    "affiliateUrl": "https://prefect.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "mage-ai",
    "name": "Mage",
    "domain": "mage.ai",
    "category": "bi-data-analytics",
    "tagline": "Hybrid notebook-style data pipeline engine and open-source Airflow alternative",
    "description": "Mage streamlines building ETL/ELT pipelines using interactive code blocks written in Python, SQL, or R. It is built for data developers seeking fast local feedback loops and modular pipeline creation.",
    "rating": 4.9,
    "reviewsCount": 850,
    "pricing": "Freemium",
    "websiteUrl": "https://mage.ai",
    "affiliateUrl": "https://mage.ai",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "950K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "atlan",
    "name": "Atlan",
    "domain": "atlan.com",
    "category": "bi-data-analytics",
    "tagline": "Active metadata platform, automated data catalog, and data governance engine",
    "description": "Atlan centralizes data lineage, data discovery, and automated access governance across cloud data warehouses. It is engineered for enterprise data leaders, data stewards, and analytics managers.",
    "rating": 4.8,
    "reviewsCount": 620,
    "pricing": "Paid",
    "websiteUrl": "https://atlan.com",
    "affiliateUrl": "https://atlan.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "monte-carlo-data",
    "name": "Monte Carlo Data",
    "domain": "montecarlodata.com",
    "category": "bi-data-analytics",
    "tagline": "End-to-end data observability and automated data downtime prevention platform",
    "description": "Monte Carlo applies machine learning to detect data anomalies, schema breakages, and stale pipelines across the data stack automatically. It is built for enterprise data engineers and SRE leads.",
    "rating": 4.8,
    "reviewsCount": 420,
    "pricing": "Paid",
    "websiteUrl": "https://montecarlodata.com",
    "affiliateUrl": "https://montecarlodata.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "680K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "alation",
    "name": "Alation",
    "domain": "alation.com",
    "category": "bi-data-analytics",
    "tagline": "Enterprise data catalog, data governance, and data intelligence platform",
    "description": "Alation provides automated data discovery, behavioral metadata analysis, and policy enforcement across enterprise data assets. It serves enterprise data stewards, compliance leads, and analysts.",
    "rating": 4.5,
    "reviewsCount": 780,
    "pricing": "Paid",
    "websiteUrl": "https://alation.com",
    "affiliateUrl": "https://alation.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "collibra",
    "name": "Collibra",
    "domain": "collibra.com",
    "category": "bi-data-analytics",
    "tagline": "Enterprise data intelligence, data governance, and privacy compliance platform",
    "description": "Collibra unifies data catalogs, policy enforcement, data quality checks, and lineage tracking for regulated industries. It is engineered for Global 2000 Chief Data Officers and compliance executives.",
    "rating": 4.3,
    "reviewsCount": 890,
    "pricing": "Paid",
    "websiteUrl": "https://collibra.com",
    "affiliateUrl": "https://collibra.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.5M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "martez-openmetadata",
    "name": "OpenMetadata",
    "domain": "open-metadata.org",
    "category": "bi-data-analytics",
    "tagline": "Open-source data catalog, automated end-to-end lineage, and governance platform",
    "description": "OpenMetadata uses a standardized metadata schema to deliver data discovery, field-level lineage, and data quality tests. It serves open-source data platform engineers and data architects.",
    "rating": 4.9,
    "reviewsCount": 380,
    "pricing": "Free",
    "websiteUrl": "https://open-metadata.org",
    "affiliateUrl": "https://open-metadata.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "520K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "soda-data",
    "name": "Soda",
    "domain": "soda.io",
    "category": "bi-data-analytics",
    "tagline": "Open-source data quality testing framework and automated monitoring platform",
    "description": "Soda runs SodaCL data quality contracts natively in CI/CD pipelines and data warehouses to stop bad data propagation. It is designed for analytics engineers and data quality teams.",
    "rating": 4.8,
    "reviewsCount": 310,
    "pricing": "Freemium",
    "websiteUrl": "https://soda.io",
    "affiliateUrl": "https://soda.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "380K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "great-expectations",
    "name": "Great Expectations",
    "domain": "greatexpectations.io",
    "category": "bi-data-analytics",
    "tagline": "Leading open-source Python library for data validation, documentation, and profiling",
    "description": "Great Expectations helps data teams eliminate bad data through declarative assertion tests and automated data documentation. It is an industry standard for data engineers and pipeline builders.",
    "rating": 4.8,
    "reviewsCount": 1250,
    "pricing": "Free",
    "websiteUrl": "https://greatexpectations.io",
    "affiliateUrl": "https://greatexpectations.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "elementary-data",
    "name": "Elementary",
    "domain": "elementary-data.com",
    "category": "bi-data-analytics",
    "tagline": "Open-source dbt-native data observability and monitoring framework",
    "description": "Elementary tracks dbt test failures, schema changes, and data freshness anomalies inside Slack and web dashboards natively. It is built specifically for analytics engineers using dbt.",
    "rating": 4.9,
    "reviewsCount": 420,
    "pricing": "Freemium",
    "websiteUrl": "https://elementary-data.com",
    "affiliateUrl": "https://elementary-data.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "acceldata",
    "name": "Acceldata",
    "domain": "acceldata.io",
    "category": "bi-data-analytics",
    "tagline": "Enterprise data observability platform across data pipelines, compute, and quality",
    "description": "Acceldata monitors data pipelines, optimizes cloud data compute costs, and validates data reliability across multi-cloud stacks. It serves enterprise data platform operators and FinOps leads.",
    "rating": 4.6,
    "reviewsCount": 210,
    "pricing": "Paid",
    "websiteUrl": "https://acceldata.io",
    "affiliateUrl": "https://acceldata.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "280K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "astronomer-io",
    "name": "Astronomer (Astro)",
    "domain": "astronomer.io",
    "category": "bi-data-analytics",
    "tagline": "Managed cloud platform for running Apache Airflow at enterprise scale",
    "description": "Astronomer provides managed Apache Airflow infrastructure with auto-scaling, enhanced security, and developer CLI tools. It is engineered for enterprise data platform engineering teams.",
    "rating": 4.8,
    "reviewsCount": 340,
    "pricing": "Free Trial",
    "websiteUrl": "https://astronomer.io",
    "affiliateUrl": "https://astronomer.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "kestra-io",
    "name": "Kestra",
    "domain": "kestra.io",
    "category": "bi-data-analytics",
    "tagline": "Open-source language-agnostic data orchestrator declarative via YAML",
    "description": "Kestra builds and executes data pipelines as declarative YAML configurations with an intuitive web-based interface. It serves software developers, data engineers, and IT automation leads.",
    "rating": 4.9,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://kestra.io",
    "affiliateUrl": "https://kestra.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "580K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "meltano",
    "name": "Meltano",
    "domain": "meltano.com",
    "category": "bi-data-analytics",
    "tagline": "Open-source CLI-first DataOps platform built on Singer taps and targets",
    "description": "Meltano applies software engineering best practices like Git version control and CI/CD to ELT data pipelines. It is built for analytics engineers and developer-centric data teams.",
    "rating": 4.7,
    "reviewsCount": 290,
    "pricing": "Free",
    "websiteUrl": "https://meltano.com",
    "affiliateUrl": "https://meltano.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "240K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "portable-io",
    "name": "Portable",
    "domain": "portable.io",
    "category": "bi-data-analytics",
    "tagline": "Cloud ETL solution specializing in hard-to-find long-tail SaaS integrations",
    "description": "Portable builds custom cloud data connectors to extract data from niche SaaS applications into modern warehouses. It serves data teams blocked by un-supported SaaS API integrations.",
    "rating": 4.9,
    "reviewsCount": 180,
    "pricing": "Freemium",
    "websiteUrl": "https://portable.io",
    "affiliateUrl": "https://portable.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "190K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "hevo-data",
    "name": "Hevo Data",
    "domain": "hevodata.com",
    "category": "bi-data-analytics",
    "tagline": "No-code automated real-time ELT pipeline platform for modern warehouses",
    "description": "Hevo Data streams data automatically from 150+ sources into cloud data warehouses with zero code maintenance. It is designed for growing businesses and non-technical analytics teams.",
    "rating": 4.7,
    "reviewsCount": 680,
    "pricing": "Freemium",
    "websiteUrl": "https://hevodata.com",
    "affiliateUrl": "https://hevodata.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "estuary-flow",
    "name": "Estuary Flow",
    "domain": "estuary.dev",
    "category": "bi-data-analytics",
    "tagline": "Real-time streaming data integration platform built on open-source Gazette",
    "description": "Estuary Flow provides low-latency CDC (change data capture) and real-time streaming pipelines into cloud databases. It is engineered for backend developers and streaming data engineers.",
    "rating": 4.8,
    "reviewsCount": 210,
    "pricing": "Freemium",
    "websiteUrl": "https://estuary.dev",
    "affiliateUrl": "https://estuary.dev",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "310K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "census-reverse-etl",
    "name": "Census",
    "domain": "getcensus.com",
    "category": "bi-data-analytics",
    "tagline": "Leading Reverse ETL platform syncing warehouse analytics directly into operational SaaS tools",
    "description": "Census syncs customer data records directly from cloud warehouses into Salesforce, Hubspot, and Zendesk automatically. It serves growth teams, revenue operations, and analytics engineers.",
    "rating": 4.8,
    "reviewsCount": 420,
    "pricing": "Freemium",
    "websiteUrl": "https://getcensus.com",
    "affiliateUrl": "https://getcensus.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "hightouch",
    "name": "Hightouch",
    "domain": "hightouch.com",
    "category": "bi-data-analytics",
    "tagline": "Composable Customer Data Platform (CDP) powered by Reverse ETL",
    "description": "Hightouch syncs warehouse analytics models directly to sales, marketing, and ad platforms without engineering code. It is tailored for digital marketers, RevOps leads, and analytics teams.",
    "rating": 4.8,
    "reviewsCount": 510,
    "pricing": "Freemium",
    "websiteUrl": "https://hightouch.com",
    "affiliateUrl": "https://hightouch.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "850K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "rudderstack",
    "name": "RudderStack",
    "domain": "rudderstack.com",
    "category": "bi-data-analytics",
    "tagline": "Developer-first, open-source customer data pipeline infrastructure alternative to Segment",
    "description": "RudderStack collects, transforms, and routes customer event data natively into private cloud warehouses and destination tools. It is built for privacy-conscious developers and data engineers.",
    "rating": 4.7,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://rudderstack.com",
    "affiliateUrl": "https://rudderstack.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "580K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "jitsu-cdp",
    "name": "Jitsu",
    "domain": "jitsu.com",
    "category": "bi-data-analytics",
    "tagline": "Open-source data ingestion engine and event collection platform",
    "description": "Jitsu captures real-time web and mobile app event streams, streaming data directly into PostgreSQL, ClickHouse, or BigQuery. It serves developers seeking self-hosted event ingestion.",
    "rating": 4.8,
    "reviewsCount": 190,
    "pricing": "Freemium",
    "websiteUrl": "https://jitsu.com",
    "affiliateUrl": "https://jitsu.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "210K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "cubewise-cube",
    "name": "Cube (Cube Cloud)",
    "domain": "cube.dev",
    "category": "bi-data-analytics",
    "tagline": "Universal semantic layer for cloud data warehouses and analytics applications",
    "description": "Cube organizes database metrics, access security, and caching into a centralized semantic API layer for BI tools and web apps. It is engineered for data architects and software developers.",
    "rating": 4.8,
    "reviewsCount": 340,
    "pricing": "Freemium",
    "websiteUrl": "https://cube.dev",
    "affiliateUrl": "https://cube.dev",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "380K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "gooddata-semantic",
    "name": "GoodData",
    "domain": "gooddata.com",
    "category": "bi-data-analytics",
    "tagline": "Composable analytics platform and headless semantic layer for cloud warehouses",
    "description": "GoodData provides centralized metric definitions, multi-tenant analytics, and embedded visual dashboards across cloud databases. It serves enterprise product managers and data leads.",
    "rating": 4.4,
    "reviewsCount": 310,
    "pricing": "Freemium",
    "websiteUrl": "https://gooddata.com",
    "affiliateUrl": "https://gooddata.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "280K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "duckdb-analytics",
    "name": "DuckDB",
    "domain": "duckdb.org",
    "category": "bi-data-analytics",
    "tagline": "Ultra-fast open-source in-process analytical SQL database engine",
    "description": "DuckDB provides high-performance analytical processing locally inside Python, R, or browser runtimes without complex server clusters. It is built for data analysts and data science researchers.",
    "rating": 4.9,
    "reviewsCount": 920,
    "pricing": "Free",
    "websiteUrl": "https://duckdb.org",
    "affiliateUrl": "https://duckdb.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "clickhouse-cloud",
    "name": "ClickHouse Cloud",
    "domain": "clickhouse.com",
    "category": "bi-data-analytics",
    "tagline": "Fully managed cloud columnar database for real-time analytical reporting at scale",
    "description": "ClickHouse Cloud delivers lightning-fast SQL queries over petabytes of event logs and analytical datasets. It serves data platform engineers, security leads, and high-scale SaaS developers.",
    "rating": 4.9,
    "reviewsCount": 1150,
    "pricing": "Freemium",
    "websiteUrl": "https://clickhouse.com",
    "affiliateUrl": "https://clickhouse.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "starburst-trino",
    "name": "Starburst (Trino)",
    "domain": "starburst.io",
    "category": "bi-data-analytics",
    "tagline": "Enterprise distributed SQL query engine powered by open-source Trino",
    "description": "Starburst queries massive datasets across object storage, relational databases, and data lakes simultaneously without data movement. It is tailored for enterprise data architects and analysts.",
    "rating": 4.6,
    "reviewsCount": 280,
    "pricing": "Free Trial",
    "websiteUrl": "https://starburst.io",
    "affiliateUrl": "https://starburst.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "420K",
    "isFreeTier": false,
    "isOpenSource": true
  },
  {
    "id": "dremio",
    "name": "Dremio",
    "domain": "dremio.com",
    "category": "bi-data-analytics",
    "tagline": "Easy, automated lakehouse management platform and SQL engine for cloud storage",
    "description": "Dremio provides self-service SQL analytics directly on Apache Iceberg data lakes without needing data warehouse copy migrations. It serves enterprise data platform leads and analysts.",
    "rating": 4.6,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://dremio.com",
    "affiliateUrl": "https://dremio.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "apache-pinot",
    "name": "Apache Pinot",
    "domain": "pinot.apache.org",
    "category": "bi-data-analytics",
    "tagline": "Distributed OLAP datastore designed for real-time user-facing analytics",
    "description": "Apache Pinot executes sub-second analytical queries over streaming data events to power live, consumer-facing application features. It serves real-time platform engineers and data architects.",
    "rating": 4.8,
    "reviewsCount": 310,
    "pricing": "Free",
    "websiteUrl": "https://pinot.apache.org",
    "affiliateUrl": "https://pinot.apache.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "380K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "apache-druid",
    "name": "Apache Druid",
    "domain": "druid.apache.org",
    "category": "bi-data-analytics",
    "tagline": "Real-time analytics database designed for high-concurrency event stream queries",
    "description": "Apache Druid combines column-oriented storage, real-time ingestion, and distributed indexing to power interactive operational analytics. It is built for data platform leads and backend architects.",
    "rating": 4.7,
    "reviewsCount": 420,
    "pricing": "Free",
    "websiteUrl": "https://druid.apache.org",
    "affiliateUrl": "https://druid.apache.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "onehouse-ai",
    "name": "Onehouse",
    "domain": "onehouse.ai",
    "category": "bi-data-analytics",
    "tagline": "Fully managed open data lakehouse platform powered by Apache Hudi",
    "description": "Onehouse ingests streaming data events into open lakehouse table formats like Apache Hudi, Iceberg, and Delta Lake automatically. It serves cloud data architects and data infrastructure leads.",
    "rating": 4.9,
    "reviewsCount": 110,
    "pricing": "Free Trial",
    "websiteUrl": "https://onehouse.ai",
    "affiliateUrl": "https://onehouse.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "120K",
    "isFreeTier": false,
    "isOpenSource": true
  },
  {
    "id": "tobiko-sqlmesh",
    "name": "SQLMesh",
    "domain": "sqlmesh.com",
    "category": "bi-data-analytics",
    "tagline": "Open-source data transformation framework focused on virtual data environments and correctness",
    "description": "SQLMesh enables analytics teams to run isolated virtual data environments and stateful SQL transformations with instant column lineage. It serves analytics engineers and data team leads.",
    "rating": 4.9,
    "reviewsCount": 160,
    "pricing": "Freemium",
    "websiteUrl": "https://sqlmesh.com",
    "affiliateUrl": "https://sqlmesh.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "210K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "sqlglot-toby",
    "name": "SQLGlot",
    "domain": "github.com/tobymao/sqlglot",
    "category": "bi-data-analytics",
    "tagline": "No-dependency Python SQL parser, transpiler, and optimizer supporting 20+ dialects",
    "description": "SQLGlot parses complex SQL queries, validates syntax structures, and transpiles queries across SQL dialects seamlessly. It is an essential open-source utility for analytics engineers and data tool builders.",
    "rating": 4.9,
    "reviewsCount": 540,
    "pricing": "Free",
    "websiteUrl": "https://github.com/tobymao/sqlglot",
    "affiliateUrl": "https://github.com/tobymao/sqlglot",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "rill-data",
    "name": "Rill",
    "domain": "rilldata.com",
    "category": "bi-data-analytics",
    "tagline": "Ultra-fast code-first operational BI dashboarding tool powered by DuckDB",
    "description": "Rill combines DuckDB performance with code-first YAML configurations to build fast visual analytics dashboards from local files or S3. It is designed for analytics engineers and data scientists.",
    "rating": 4.9,
    "reviewsCount": 180,
    "pricing": "Freemium",
    "websiteUrl": "https://rilldata.com",
    "affiliateUrl": "https://rilldata.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "240K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "evidence-dev",
    "name": "Evidence",
    "domain": "evidence.dev",
    "category": "bi-data-analytics",
    "tagline": "Open-source business intelligence as code using Markdown and SQL queries",
    "description": "Evidence converts Markdown files and embedded SQL statements into fast, version-controlled web data reports. It serves analytics engineers and developers building data products as code.",
    "rating": 4.9,
    "reviewsCount": 210,
    "pricing": "Freemium",
    "websiteUrl": "https://evidence.dev",
    "affiliateUrl": "https://evidence.dev",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "280K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "lightdash-bi",
    "name": "Lightdash",
    "domain": "lightdash.com",
    "category": "bi-data-analytics",
    "tagline": "Open-source self-serve BI platform natively connected to your dbt semantic layer",
    "description": "Lightdash turns dbt project metrics and schema definitions into visual, self-serve business intelligence dashboards automatically. It serves analytics engineers and dbt power users.",
    "rating": 4.9,
    "reviewsCount": 160,
    "pricing": "Freemium",
    "websiteUrl": "https://lightdash.com",
    "affiliateUrl": "https://lightdash.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "190K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "preset-superset",
    "name": "Preset",
    "domain": "preset.io",
    "category": "bi-data-analytics",
    "tagline": "Managed cloud Apache Superset platform for visual enterprise analytics",
    "description": "Preset offers hosted Apache Superset infrastructure, enabling teams to build SQL queries and visual dashboards with enterprise governance. It is built for data engineers and analytics teams.",
    "rating": 4.8,
    "reviewsCount": 190,
    "pricing": "Freemium",
    "websiteUrl": "https://preset.io",
    "affiliateUrl": "https://preset.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "240K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "sigma-computing-bi",
    "name": "Sigma Computing",
    "domain": "sigmacomputing.com",
    "category": "bi-data-analytics",
    "tagline": "Cloud-native spreadsheet interface querying cloud data warehouses directly",
    "description": "Sigma provides a familiar spreadsheet interface that directly queries live cloud data warehouses like Snowflake in real time. It is built for business analysts and data operations teams.",
    "rating": 4.8,
    "reviewsCount": 240,
    "pricing": "Free Trial",
    "websiteUrl": "https://sigmacomputing.com",
    "affiliateUrl": "https://sigmacomputing.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "310K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "thoughtspot-analytics",
    "name": "ThoughtSpot",
    "domain": "thoughtspot.com",
    "category": "bi-data-analytics",
    "tagline": "AI-powered natural language analytics and business intelligence platform",
    "description": "ThoughtSpot enables business users to search cloud data using natural language queries and dynamic AI charts. It serves corporate decision-makers and enterprise business analysts.",
    "rating": 4.6,
    "reviewsCount": 510,
    "pricing": "Free Trial",
    "websiteUrl": "https://thoughtspot.com",
    "affiliateUrl": "https://thoughtspot.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "domo-platform",
    "name": "Domo",
    "domain": "domo.com",
    "category": "bi-data-analytics",
    "tagline": "Cloud business management platform combining data pipelines, ETL, and dashboards",
    "description": "Domo integrates hundreds of data sources, automates ETL jobs, and generates executive dashboards on mobile and desktop. It is designed for enterprise executives and cross-functional teams.",
    "rating": 4.4,
    "reviewsCount": 890,
    "pricing": "Free Trial",
    "websiteUrl": "https://domo.com",
    "affiliateUrl": "https://domo.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "databox-dashboards",
    "name": "Databox",
    "domain": "databox.com",
    "category": "bi-data-analytics",
    "tagline": "All-in-one business analytics dashboard connecting your favorite tools",
    "description": "Databox aggregates marketing, sales, and financial KPIs into clean visual dashboards automatically. It serves digital agencies, executive teams, and performance marketers.",
    "rating": 4.7,
    "reviewsCount": 980,
    "pricing": "Freemium",
    "websiteUrl": "https://databox.com",
    "affiliateUrl": "https://databox.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "klipfolio-metrics",
    "name": "Klipfolio",
    "domain": "klipfolio.com",
    "category": "bi-data-analytics",
    "tagline": "Real-time KPI tracking, metric monitoring, and business reporting dashboard",
    "description": "Klipfolio connects data sources to build custom business performance dashboards and track key metrics. It is tailored for growing businesses, digital agencies, and data leads.",
    "rating": 4.5,
    "reviewsCount": 720,
    "pricing": "Freemium",
    "websiteUrl": "https://klipfolio.com",
    "affiliateUrl": "https://klipfolio.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "820K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "mode-analytics-hub",
    "name": "Mode",
    "domain": "mode.com",
    "category": "bi-data-analytics",
    "tagline": "Collaborative data workspace uniting SQL queries, Python notebooks, and visual charts",
    "description": "Mode connects SQL query editors, Python/R code notebooks, and self-serve visual dashboards in one platform. It is engineered for data science teams and enterprise analytics leads.",
    "rating": 4.6,
    "reviewsCount": 380,
    "pricing": "Free Trial",
    "websiteUrl": "https://mode.com",
    "affiliateUrl": "https://mode.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "450K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "hex-data-app",
    "name": "Hex",
    "domain": "hex.tech",
    "category": "bi-data-analytics",
    "tagline": "Collaborative data workspace for SQL, Python, and interactive data apps",
    "description": "Hex integrates SQL query blocks, Python code, drag-and-drop charts, and AI assistance into shareable data applications. It serves data science teams, research analysts, and analytics engineers.",
    "rating": 4.9,
    "reviewsCount": 310,
    "pricing": "Freemium",
    "websiteUrl": "https://hex.tech",
    "affiliateUrl": "https://hex.tech",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "520K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "deepnote-data",
    "name": "Deepnote",
    "domain": "deepnote.com",
    "category": "bi-data-analytics",
    "tagline": "Real-time collaborative data science and SQL notebook in the cloud",
    "description": "Deepnote provides cloud-hosted Jupyter-compatible notebooks with native SQL support, team editing, and chart creation. It is engineered for data science teams, researchers, and educators.",
    "rating": 4.8,
    "reviewsCount": 290,
    "pricing": "Freemium",
    "websiteUrl": "https://deepnote.com",
    "affiliateUrl": "https://deepnote.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "410K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "supermetrics-data",
    "name": "Supermetrics",
    "domain": "supermetrics.com",
    "category": "bi-data-analytics",
    "tagline": "Automate marketing data transfers to Google Sheets, BigQuery, and cloud warehouses",
    "description": "Supermetrics consolidates advertising spend, social metrics, and SEO performance data into cloud databases automatically. It serves performance marketers, growth teams, and digital agencies.",
    "rating": 4.6,
    "reviewsCount": 1100,
    "pricing": "Free Trial",
    "websiteUrl": "https://supermetrics.com",
    "affiliateUrl": "https://supermetrics.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.9M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "funnel-io-marketing",
    "name": "Funnel",
    "domain": "funnel.io",
    "category": "bi-data-analytics",
    "tagline": "Automated marketing data hub for reporting, storage, and analytics pipelines",
    "description": "Funnel collects, cleanses, and maps multi-channel marketing performance data into cloud warehouses automatically. It serves enterprise marketing divisions, digital agencies, and growth leads.",
    "rating": 4.7,
    "reviewsCount": 380,
    "pricing": "Free Trial",
    "websiteUrl": "https://funnel.io",
    "affiliateUrl": "https://funnel.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "trevor-io-sql",
    "name": "Trevor.io",
    "domain": "trevor.io",
    "category": "bi-data-analytics",
    "tagline": "No-code SQL database query builder and visual reporting tool",
    "description": "Trevor.io empowers non-technical employees to query SQL databases and build visual reports without writing code. It is designed for operational teams and startup employees.",
    "rating": 4.8,
    "reviewsCount": 140,
    "pricing": "Freemium",
    "websiteUrl": "https://trevor.io",
    "affiliateUrl": "https://trevor.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "110K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "redash-sql",
    "name": "Redash",
    "domain": "redash.io",
    "category": "bi-data-analytics",
    "tagline": "Open-source SQL query editor, data visualizer, and dashboard platform",
    "description": "Redash connects to database sources to let teams write SQL, visualize query outputs, and collaborate on shared dashboards. It is tailored for developers, SQL power users, and data analysts.",
    "rating": 4.6,
    "reviewsCount": 420,
    "pricing": "Free",
    "websiteUrl": "https://redash.io",
    "affiliateUrl": "https://redash.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "310K",
    "isFreeTier": true,
    "isOpenSource": true
  }
];

const saasDataPath = path.join(__dirname, '..', 'src', 'data', 'saasData.jsx');
let content = fs.readFileSync(saasDataPath, 'utf8');

const match = content.match(/export const staticSaasTools = (\[[\s\S]*?\n\]);/);
if (!match) {
  console.error('Could not find staticSaasTools in saasData.jsx');
  process.exit(1);
}

let existingTools = JSON.parse(match[1]);

const existingIds = new Set(existingTools.map(t => t.id.toLowerCase()));
const existingNames = new Set(existingTools.map(t => t.name.toLowerCase()));

let addedCount = 0;
let skippedCount = 0;

newTools.forEach(tool => {
  const normId = tool.id.toLowerCase();
  const normName = tool.name.toLowerCase();

  if (!existingIds.has(normId) && !existingNames.has(normName)) {
    existingTools.push(tool);
    existingIds.add(normId);
    existingNames.add(normName);
    addedCount++;
  } else {
    // Enrich existing tool without creating a duplicate
    const idx = existingTools.findIndex(t => t.id.toLowerCase() === normId || t.name.toLowerCase() === normName);
    if (idx !== -1) {
      existingTools[idx] = { ...existingTools[idx], category: tool.category, tagline: tool.tagline || existingTools[idx].tagline };
    }
    skippedCount++;
  }
});

const updatedArrayStr = JSON.stringify(existingTools, null, 2);
content = content.replace(/export const staticSaasTools = \[[\s\S]*?\n\];/, `export const staticSaasTools = ${updatedArrayStr};`);

fs.writeFileSync(saasDataPath, content, 'utf8');
console.log(`Ingestion Complete! Added: ${addedCount} brand new tools | Deduplicated: ${skippedCount} existing tools | Total static tools: ${existingTools.length}`);
