const fs = require('fs');
const path = require('path');

const newTools = [
  {
    "id": "playwright",
    "name": "Playwright",
    "domain": "playwright.dev",
    "category": "testing-qa",
    "tagline": "Fast, cross-browser end-to-end automation library for modern web apps",
    "description": "Playwright enables reliable cross-browser automation across Chromium, Firefox, and WebKit with automatic waiting and trace viewing. It is built for frontend engineers and QA automation teams scaling modern E2E test suites.",
    "rating": 4.9,
    "reviewsCount": 2400,
    "pricing": "Free",
    "websiteUrl": "https://playwright.dev",
    "affiliateUrl": "https://playwright.dev",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "4.5M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "cypress",
    "name": "Cypress",
    "domain": "cypress.io",
    "category": "testing-qa",
    "tagline": "Developer-friendly frontend testing framework for fast E2E and component tests",
    "description": "Cypress runs tests inside real browser execution loops with time-travel debugging and automated DOM snapshots. It serves web developers and QA specialists building reactive web applications.",
    "rating": 4.8,
    "reviewsCount": 3800,
    "pricing": "Freemium",
    "websiteUrl": "https://cypress.io",
    "affiliateUrl": "https://cypress.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "6.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "grafana-k6",
    "name": "Grafana k6",
    "domain": "k6.io",
    "category": "testing-qa",
    "tagline": "Developer-centric load testing tool built for performance and reliability engineering",
    "description": "k6 executes developer-friendly load tests scripted in JavaScript to test API throughput and peak traffic limits. It is tailored for SREs, performance engineers, and backend teams in CI/CD pipelines.",
    "rating": 4.8,
    "reviewsCount": 1420,
    "pricing": "Freemium",
    "websiteUrl": "https://k6.io",
    "affiliateUrl": "https://k6.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "2.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "applitools",
    "name": "Applitools Eyes",
    "domain": "applitools.com",
    "category": "testing-qa",
    "tagline": "AI-augmented visual UI testing and cross-browser visual validation platform",
    "description": "Applitools uses Visual AI to catch UI regressions, layout bugs, and visual defects across browsers and screen resolutions. It serves enterprise QA teams and frontend engineers upholding design system integrity.",
    "rating": 4.8,
    "reviewsCount": 510,
    "pricing": "Free Trial",
    "websiteUrl": "https://applitools.com",
    "affiliateUrl": "https://applitools.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "850K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "selenium",
    "name": "Selenium",
    "domain": "selenium.dev",
    "category": "testing-qa",
    "tagline": "Open-source browser automation framework powering web application testing globally",
    "description": "Selenium provides W3C-standard browser automation drivers across multiple programming languages and OS environments. It is an industry foundation for enterprise QA engineers and automation architects.",
    "rating": 4.5,
    "reviewsCount": 6200,
    "pricing": "Free",
    "websiteUrl": "https://selenium.dev",
    "affiliateUrl": "https://selenium.dev",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "5.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "appium",
    "name": "Appium",
    "domain": "appium.io",
    "category": "testing-qa",
    "tagline": "Open-source cross-platform mobile automation framework for iOS and Android apps",
    "description": "Appium automates native, hybrid, and mobile web applications using the WebDriver protocol without modifying app source code. It is designed for mobile QA engineers and mobile app developers.",
    "rating": 4.6,
    "reviewsCount": 1850,
    "pricing": "Free",
    "websiteUrl": "https://appium.io",
    "affiliateUrl": "https://appium.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "browserstack",
    "name": "BrowserStack",
    "domain": "browserstack.com",
    "category": "testing-qa",
    "tagline": "Real device cloud platform for cross-browser and mobile application testing",
    "description": "BrowserStack grants instant cloud access to 3,000+ real mobile devices and desktop browser instances for live and automated testing. It serves enterprise engineering leads, QA teams, and web developers.",
    "rating": 4.6,
    "reviewsCount": 3100,
    "pricing": "Free Trial",
    "websiteUrl": "https://browserstack.com",
    "affiliateUrl": "https://browserstack.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "9.5M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "sauce-labs",
    "name": "Sauce Labs",
    "domain": "saucelabs.com",
    "category": "testing-qa",
    "tagline": "Unified cloud-based test platform for web and mobile app quality assurance",
    "description": "Sauce Labs executes automated web and mobile test scripts across cloud device farms, offering error analytics and visual testing. It serves enterprise DevSecOps teams and QA leaders.",
    "rating": 4.4,
    "reviewsCount": 1250,
    "pricing": "Free Trial",
    "websiteUrl": "https://saucelabs.com",
    "affiliateUrl": "https://saucelabs.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "lambdatest",
    "name": "LambdaTest",
    "domain": "lambdatest.com",
    "category": "testing-qa",
    "tagline": "AI-powered test execution cloud for ultra-fast cross-browser and mobile grid testing",
    "description": "LambdaTest runs automated Selenium, Playwright, and Cypress test suites across a distributed cloud grid with Smart UI comparison tools. It is built for fast-scaling engineering and QA teams.",
    "rating": 4.7,
    "reviewsCount": 1650,
    "pricing": "Freemium",
    "websiteUrl": "https://lambdatest.com",
    "affiliateUrl": "https://lambdatest.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "artillery-io",
    "name": "Artillery",
    "domain": "artillery.io",
    "category": "testing-qa",
    "tagline": "Cloud-scale load and stress testing framework for APIs, WebSockets, and microservices",
    "description": "Artillery runs high-throughput serverless load tests across cloud infrastructure using Node.js and YAML test definitions. It serves backend architects, SREs, and DevOps performance engineers.",
    "rating": 4.8,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://artillery.io",
    "affiliateUrl": "https://artillery.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "locust-io",
    "name": "Locust",
    "domain": "locust.io",
    "category": "testing-qa",
    "tagline": "Open-source, Python-based distributed user load testing framework",
    "description": "Locust lets performance engineers define concurrent user behaviors in plain Python code and monitor load scenarios in real-time web UI dashboards. It serves backend developers and SREs.",
    "rating": 4.8,
    "reviewsCount": 920,
    "pricing": "Free",
    "websiteUrl": "https://locust.io",
    "affiliateUrl": "https://locust.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "850K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "gatling",
    "name": "Gatling",
    "domain": "gatling.io",
    "category": "testing-qa",
    "tagline": "High-performance load testing tool built for web application stress testing",
    "description": "Gatling simulates heavy user traffic against web servers using Java, Kotlin, or Scala domain-specific DSL scripts with detailed HTML reporting. It is engineered for enterprise performance engineers.",
    "rating": 4.7,
    "reviewsCount": 780,
    "pricing": "Freemium",
    "websiteUrl": "https://gatling.io",
    "affiliateUrl": "https://gatling.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "apache-jmeter",
    "name": "Apache JMeter",
    "domain": "jmeter.apache.org",
    "category": "testing-qa",
    "tagline": "Open-source Java application designed to load test functional behavior and measure performance",
    "description": "Apache JMeter simulates heavy loads on servers, networks, and databases to test endurance and analyze overall application performance under stress. It is a classic tool for performance testers.",
    "rating": 4.3,
    "reviewsCount": 3800,
    "pricing": "Free",
    "websiteUrl": "https://jmeter.apache.org",
    "affiliateUrl": "https://jmeter.apache.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "allure-report",
    "name": "Allure Report",
    "domain": "allurereport.org",
    "category": "testing-qa",
    "tagline": "Open-source multi-language test reporting tool providing clear visual analytics",
    "description": "Allure transforms raw test execution logs from JUnit, PyTest, and Jest into interactive visual HTML reports with step timelines and attachments. It is built for QA automation engineers.",
    "rating": 4.9,
    "reviewsCount": 650,
    "pricing": "Free",
    "websiteUrl": "https://allurereport.org",
    "affiliateUrl": "https://allurereport.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "780K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "testrail",
    "name": "TestRail",
    "domain": "testrail.com",
    "category": "testing-qa",
    "tagline": "Comprehensive web-based test case management software for QA and development teams",
    "description": "TestRail organizes manual and automated test cases, tracks test execution runs, and provides real-time coverage reports. It serves QA managers, software testers, and engineering directors.",
    "rating": 4.5,
    "reviewsCount": 1820,
    "pricing": "Free Trial",
    "websiteUrl": "https://testrail.com",
    "affiliateUrl": "https://testrail.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.9M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "qase-io",
    "name": "Qase",
    "domain": "qase.io",
    "category": "testing-qa",
    "tagline": "Modern cloud test management workspace unifying manual and automated testing",
    "description": "Qase centralizes test plans, captures execution logs, and links automated CI/CD test results directly to Jira and GitHub. It serves fast-moving engineering teams and QA leads.",
    "rating": 4.8,
    "reviewsCount": 420,
    "pricing": "Freemium",
    "websiteUrl": "https://qase.io",
    "affiliateUrl": "https://qase.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "xray-jira",
    "name": "Xray Test Management",
    "domain": "getxray.app",
    "category": "testing-qa",
    "tagline": "Native quality assurance and test management app built directly inside Jira",
    "description": "Xray integrates test specification, execution tracking, and coverage metrics directly into native Jira issue workflows. It is built specifically for agile teams using Atlassian software.",
    "rating": 4.6,
    "reviewsCount": 890,
    "pricing": "Free Trial",
    "websiteUrl": "https://getxray.app",
    "affiliateUrl": "https://getxray.app",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "zephyr-scale",
    "name": "Zephyr Scale (SmartBear)",
    "domain": "smartbear.com/test-management/zephyr-scale",
    "category": "testing-qa",
    "tagline": "Scalable enterprise test management solution natively integrated into Jira",
    "description": "Zephyr Scale tracks complex test case hierarchies, version histories, and execution metrics directly within Jira projects. It is engineered for large-scale enterprise QA organizations.",
    "rating": 4.5,
    "reviewsCount": 1100,
    "pricing": "Free Trial",
    "websiteUrl": "https://smartbear.com/test-management/zephyr-scale",
    "affiliateUrl": "https://smartbear.com/test-management/zephyr-scale",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "testim-io",
    "name": "Tricentis Testim",
    "domain": "testim.io",
    "category": "testing-qa",
    "tagline": "AI-powered codeless test automation for web and mobile applications",
    "description": "Testim uses machine learning locator algorithms to create self-healing web and mobile tests with minimal maintenance overhead. It is built for QA leads, agile developers, and release leads.",
    "rating": 4.7,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://testim.io",
    "affiliateUrl": "https://testim.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "450K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "mabl-qa",
    "name": "mabl",
    "domain": "mabl.com",
    "category": "testing-qa",
    "tagline": "Low-code test automation platform integrating visual, API, and performance checks",
    "description": "mabl combines automated functional UI checks, visual regressions, and accessibility testing into CI/CD development pipelines. It serves agile software teams and quality engineers.",
    "rating": 4.6,
    "reviewsCount": 310,
    "pricing": "Free Trial",
    "websiteUrl": "https://mabl.com",
    "affiliateUrl": "https://mabl.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "380K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "katalon-studio",
    "name": "Katalon Platform",
    "domain": "katalon.com",
    "category": "testing-qa",
    "tagline": "All-in-one AI-augmented test automation platform for web, API, mobile, and desktop",
    "description": "Katalon integrates test generation, execution engines, and central reporting for cross-platform software suites. It is tailored for QA teams scaling automated end-to-end testing.",
    "rating": 4.5,
    "reviewsCount": 2100,
    "pricing": "Freemium",
    "websiteUrl": "https://katalon.com",
    "affiliateUrl": "https://katalon.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "robot-framework",
    "name": "Robot Framework",
    "domain": "robotframework.org",
    "category": "testing-qa",
    "tagline": "Generic open-source Python automation framework for acceptance testing and RPA",
    "description": "Robot Framework uses keyword-driven tabular syntax to execute automated acceptance tests and robotic process automation routines. It is built for open-source testers and Python engineers.",
    "rating": 4.7,
    "reviewsCount": 980,
    "pricing": "Free",
    "websiteUrl": "https://robotframework.org",
    "affiliateUrl": "https://robotframework.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "820K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "webdriver-io",
    "name": "WebdriverIO",
    "domain": "webdriver.io",
    "category": "testing-qa",
    "tagline": "Next-gen browser and mobile automation test framework for Node.js",
    "description": "WebdriverIO provides flexible end-to-end automation over the WebDriver and Chrome DevTools protocols for Node.js apps. It serves frontend developers and JavaScript QA engineers.",
    "rating": 4.8,
    "reviewsCount": 750,
    "pricing": "Free",
    "websiteUrl": "https://webdriver.io",
    "affiliateUrl": "https://webdriver.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "950K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "percy-browserstack",
    "name": "Percy by BrowserStack",
    "domain": "percy.io",
    "category": "testing-qa",
    "tagline": "All-in-one visual testing and automated review platform for web UI components",
    "description": "Percy captures pixel-by-pixel UI snapshots on pull requests to highlight unintended CSS and layout regressions visually. It serves design system engineers and frontend web developers.",
    "rating": 4.7,
    "reviewsCount": 480,
    "pricing": "Freemium",
    "websiteUrl": "https://percy.io",
    "affiliateUrl": "https://percy.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "rest-assured",
    "name": "REST Assured",
    "domain": "rest-assured.io",
    "category": "testing-qa",
    "tagline": "Java domain-specific language for easy, expressive testing of REST services",
    "description": "REST Assured simplifies testing and validating HTTP REST endpoints using BDD-style given-when-then Java code structures. It is engineered for Java backend developers and automation leads.",
    "rating": 4.8,
    "reviewsCount": 890,
    "pricing": "Free",
    "websiteUrl": "https://rest-assured.io",
    "affiliateUrl": "https://rest-assured.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "510K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "karate-labs",
    "name": "Karate Labs",
    "domain": "karatelabs.io",
    "category": "testing-qa",
    "tagline": "Open-source unified framework for API automation, performance testing, and UI mocks",
    "description": "Karate combines API test execution, mock server setup, and load testing into a single Cucumber-like DSL syntax. It serves full-stack software engineers and backend API developers.",
    "rating": 4.8,
    "reviewsCount": 540,
    "pricing": "Freemium",
    "websiteUrl": "https://karatelabs.io",
    "affiliateUrl": "https://karatelabs.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "420K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "pact-io",
    "name": "Pact",
    "domain": "pact.io",
    "category": "testing-qa",
    "tagline": "Fast, safe code-first contract testing framework for HTTP and messaging APIs",
    "description": "Pact enables consumer-driven contract testing to verify API integration agreements between microservices without end-to-end setup. It is built for microservice architects and developers.",
    "rating": 4.8,
    "reviewsCount": 380,
    "pricing": "Free",
    "websiteUrl": "https://pact.io",
    "affiliateUrl": "https://pact.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "340K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "pactflow-io",
    "name": "PactFlow",
    "domain": "pactflow.io",
    "category": "testing-qa",
    "tagline": "Enterprise contract testing platform for scalable microservice deployments",
    "description": "PactFlow provides centralized contract verification dashboards and deployment safety checks for distributed software APIs. It serves enterprise engineering leads and DevOps leads.",
    "rating": 4.9,
    "reviewsCount": 180,
    "pricing": "Freemium",
    "websiteUrl": "https://pactflow.io",
    "affiliateUrl": "https://pactflow.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "210K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "playwright-ct",
    "name": "Playwright Component Testing",
    "domain": "playwright.dev/docs/test-components",
    "category": "testing-qa",
    "tagline": "Fast, isolated component testing for React, Vue, Svelte, and Solid components",
    "description": "Playwright Component Testing renders UI components inside real browser instances to verify interactions natively. It serves frontend developers building design libraries and UI components.",
    "rating": 4.9,
    "reviewsCount": 310,
    "pricing": "Free",
    "websiteUrl": "https://playwright.dev/docs/test-components",
    "affiliateUrl": "https://playwright.dev/docs/test-components",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.5M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "storybook-test",
    "name": "Storybook",
    "domain": "storybook.js.org",
    "category": "testing-qa",
    "tagline": "Frontend workshop for building UI components and running automated visual checks",
    "description": "Storybook isolates UI component development while enabling interaction testing, accessibility checks, and snapshot validations. It is an industry standard for frontend developers and UI leads.",
    "rating": 4.9,
    "reviewsCount": 2800,
    "pricing": "Free",
    "websiteUrl": "https://storybook.js.org",
    "affiliateUrl": "https://storybook.js.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "axe-deque",
    "name": "axe DevTools (Deque)",
    "domain": "deque.com/axe",
    "category": "testing-qa",
    "tagline": "Automated digital accessibility (WCAG) testing engine for web and mobile",
    "description": "axe DevTools automatically catches up to 80% of digital accessibility defects during development and test execution. It serves frontend developers, accessibility auditors, and QA teams.",
    "rating": 4.8,
    "reviewsCount": 620,
    "pricing": "Freemium",
    "websiteUrl": "https://deque.com/axe",
    "affiliateUrl": "https://deque.com/axe",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "580K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "pa11y-org",
    "name": "Pa11y",
    "domain": "pa11y.org",
    "category": "testing-qa",
    "tagline": "Free open-source command-line accessibility testing tool for web pages",
    "description": "Pa11y runs automated web accessibility audits against URLs via command line or CI/CD pipelines. It is engineered for open-source developers and web accessibility advocates.",
    "rating": 4.7,
    "reviewsCount": 240,
    "pricing": "Free",
    "websiteUrl": "https://pa11y.org",
    "affiliateUrl": "https://pa11y.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "180K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "jest-js",
    "name": "Jest",
    "domain": "jestjs.io",
    "category": "testing-qa",
    "tagline": "Delightful JavaScript testing framework with a focus on simplicity",
    "description": "Jest provides instant zero-configuration unit and snapshot testing for JavaScript and TypeScript codebases. It is built for frontend and Node.js developers testing React, Vue, and backend modules.",
    "rating": 4.8,
    "reviewsCount": 3400,
    "pricing": "Free",
    "websiteUrl": "https://jestjs.io",
    "affiliateUrl": "https://jestjs.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "vitest-dev",
    "name": "Vitest",
    "domain": "vitest.dev",
    "category": "testing-qa",
    "tagline": "Next-generation Vite-native unit test framework with lightning-fast execution",
    "description": "Vitest leverages Vite's transformation pipeline to run unit and integration tests with instant HMR re-runs. It serves modern web developers building React, Vue, and Svelte applications.",
    "rating": 4.9,
    "reviewsCount": 980,
    "pricing": "Free",
    "websiteUrl": "https://vitest.dev",
    "affiliateUrl": "https://vitest.dev",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "pytest-org",
    "name": "pytest",
    "domain": "docs.pytest.org",
    "category": "testing-qa",
    "tagline": "Mature, feature-rich Python testing framework for simple unit and complex functional tests",
    "description": "pytest simplifies writing small Python test scripts while scaling to support complex integration suites via fixture dependency injection. It is the gold standard for Python developers and QA leads.",
    "rating": 4.9,
    "reviewsCount": 2900,
    "pricing": "Free",
    "websiteUrl": "https://docs.pytest.org",
    "affiliateUrl": "https://docs.pytest.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "testing-library",
    "name": "Testing Library",
    "domain": "testing-library.com",
    "category": "testing-qa",
    "tagline": "Simple and complete testing utilities that encourage good DOM testing practices",
    "description": "Testing Library evaluates web components based on actual user interactions rather than implementation details. It is tailored for DOM, React, and Angular component developers.",
    "rating": 4.9,
    "reviewsCount": 1650,
    "pricing": "Free",
    "websiteUrl": "https://testing-library.com",
    "affiliateUrl": "https://testing-library.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "sonar-sonarqube",
    "name": "SonarQube (Sonar)",
    "domain": "sonarsource.com/products/sonarqube",
    "category": "testing-qa",
    "tagline": "Automatic code quality inspection and static security analysis (SAST) platform",
    "description": "SonarQube continuously inspects codebases across 30+ languages to detect code smells, bugs, and security vulnerabilities. It serves DevSecOps engineering leads and software quality architects.",
    "rating": 4.6,
    "reviewsCount": 2400,
    "pricing": "Freemium",
    "websiteUrl": "https://sonarsource.com/products/sonarqube",
    "affiliateUrl": "https://sonarsource.com/products/sonarqube",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "coveralls-io",
    "name": "Coveralls",
    "domain": "coveralls.io",
    "category": "testing-qa",
    "tagline": "Code coverage history tracking and pull request status checks for developers",
    "description": "Coveralls ingests test coverage reports from CI builds to monitor line coverage trends and block untested code merges. It serves open-source maintainers and engineering teams.",
    "rating": 4.6,
    "reviewsCount": 420,
    "pricing": "Freemium",
    "websiteUrl": "https://coveralls.io",
    "affiliateUrl": "https://coveralls.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "codecov-io",
    "name": "Codecov (Sentry)",
    "domain": "about.codecov.io",
    "category": "testing-qa",
    "tagline": "Actionable code coverage insight and automated pull request comments",
    "description": "Codecov visualizes test coverage metrics directly within pull requests, highlighting untested code changes automatically. It is engineered for software development teams and open-source projects.",
    "rating": 4.7,
    "reviewsCount": 680,
    "pricing": "Freemium",
    "websiteUrl": "https://about.codecov.io",
    "affiliateUrl": "https://about.codecov.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "testsigma",
    "name": "Testsigma",
    "domain": "testsigma.com",
    "category": "testing-qa",
    "tagline": "No-code AI-driven test automation platform for web, mobile, and API testing",
    "description": "Testsigma allows QA teams to author automated tests in plain natural language without writing code scripts. It serves agile teams, non-technical testers, and QA leads.",
    "rating": 4.7,
    "reviewsCount": 310,
    "pricing": "Freemium",
    "websiteUrl": "https://testsigma.com",
    "affiliateUrl": "https://testsigma.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "repeato-app",
    "name": "Repeato",
    "domain": "repeato.app",
    "category": "testing-qa",
    "tagline": "No-code computer-vision based test automation for mobile iOS and Android apps",
    "description": "Repeato uses computer vision and neural networks to record and execute mobile UI tests in minutes. It serves mobile app creators, indie developers, and non-technical QA testers.",
    "rating": 4.8,
    "reviewsCount": 110,
    "pricing": "Freemium",
    "websiteUrl": "https://repeato.app",
    "affiliateUrl": "https://repeato.app",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "90K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "maestro-mobile",
    "name": "Maestro (MobileDev)",
    "domain": "maestro.mobiledev.pro",
    "category": "testing-qa",
    "tagline": "Easiest open-source mobile UI testing framework for iOS and Android",
    "description": "Maestro allows developers to define multi-step mobile UI flows in declarative YAML files that tolerate slow animations and delays. It is built for Flutter, React Native, and native mobile engineers.",
    "rating": 4.9,
    "reviewsCount": 520,
    "pricing": "Free",
    "websiteUrl": "https://maestro.mobiledev.pro",
    "affiliateUrl": "https://maestro.mobiledev.pro",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "detox-wix",
    "name": "Detox (Wix)",
    "domain": "wix.github.io/Detox",
    "category": "testing-qa",
    "tagline": "Gray-box end-to-end testing and automation framework for React Native apps",
    "description": "Detox runs deterministic E2E mobile tests by synchronizing with React Native async operations to eliminate test flakiness. It serves mobile app developers and React Native engineers.",
    "rating": 4.6,
    "reviewsCount": 420,
    "pricing": "Free",
    "websiteUrl": "https://wix.github.io/Detox",
    "affiliateUrl": "https://wix.github.io/Detox",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "280K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "ghost-inspector",
    "name": "Ghost Inspector",
    "domain": "ghostinspector.com",
    "category": "testing-qa",
    "tagline": "No-code website monitoring and browser automated UI testing service",
    "description": "Ghost Inspector records browser interactions, schedules recurring site checks, and alerts teams when UI flows break. It serves digital agencies, non-technical site admins, and QA leads.",
    "rating": 4.7,
    "reviewsCount": 340,
    "pricing": "Free Trial",
    "websiteUrl": "https://ghostinspector.com",
    "affiliateUrl": "https://ghostinspector.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "310K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "checkly-hq",
    "name": "Checkly",
    "domain": "checklyhq.com",
    "category": "testing-qa",
    "tagline": "Synthetic monitoring and E2E testing platform powered by Playwright code",
    "description": "Checkly monitors API endpoints and web user flows continuously using JavaScript and Playwright scripts. It serves SREs, frontend engineers, and DevOps operations.",
    "rating": 4.8,
    "reviewsCount": 290,
    "pricing": "Freemium",
    "websiteUrl": "https://checklyhq.com",
    "affiliateUrl": "https://checklyhq.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "380K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "wiremock-net",
    "name": "WireMock",
    "domain": "wiremock.org",
    "category": "testing-qa",
    "tagline": "Flexible open-source tool for mocking HTTP APIs and simulating edge failure modes",
    "description": "WireMock spins up mock HTTP servers to simulate third-party API dependencies, latency, and fault conditions during testing. It serves backend software developers and QA automation engineers.",
    "rating": 4.8,
    "reviewsCount": 850,
    "pricing": "Free",
    "websiteUrl": "https://wiremock.org",
    "affiliateUrl": "https://wiremock.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "720K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "mockoon-app",
    "name": "Mockoon",
    "domain": "mockoon.com",
    "category": "testing-qa",
    "tagline": "The easiest, fast open-source tool to create local mock REST APIs in seconds",
    "description": "Mockoon provides a desktop GUI for building custom mock REST APIs without remote servers or cloud accounts. It serves frontend developers and mobile app engineers needing offline API stubs.",
    "rating": 4.9,
    "reviewsCount": 420,
    "pricing": "Free",
    "websiteUrl": "https://mockoon.com",
    "affiliateUrl": "https://mockoon.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "testcontaines-org",
    "name": "Testcontainers",
    "domain": "testcontainers.com",
    "category": "testing-qa",
    "tagline": "Lightweight throwaway instances of databases, message brokers, and web browsers in code",
    "description": "Testcontainers provisions real Docker instances of databases and services directly within unit test code setups. It is engineered for backend developers writing integration tests in Java, Go, and Python.",
    "rating": 4.9,
    "reviewsCount": 1150,
    "pricing": "Free",
    "websiteUrl": "https://testcontainers.com",
    "affiliateUrl": "https://testcontainers.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "bugasura-io",
    "name": "Bugasura",
    "domain": "bugasura.io",
    "category": "testing-qa",
    "tagline": "AI-powered modern bug tracking and visual defect reporting software for SaaS",
    "description": "Bugasura captures annotated screenshots, screen recordings, and console logs to streamline bug reporting and resolution. It serves QA testers, product managers, and software developers.",
    "rating": 4.7,
    "reviewsCount": 190,
    "pricing": "Freemium",
    "websiteUrl": "https://bugasura.io",
    "affiliateUrl": "https://bugasura.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "210K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "testrigor-com",
    "name": "testRigor",
    "domain": "testrigor.com",
    "category": "testing-qa",
    "tagline": "Generative AI autonomous end-to-end test automation tool written in plain English",
    "description": "testRigor converts plain-English test descriptions into executable end-to-end tests across web, mobile, and API interfaces. It serves manual QA testers, business analysts, and QA leads.",
    "rating": 4.8,
    "reviewsCount": 280,
    "pricing": "Freemium",
    "websiteUrl": "https://testrigor.com",
    "affiliateUrl": "https://testrigor.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "340K",
    "isFreeTier": true,
    "isOpenSource": false
  }
];

const saasDataPath = path.join(__dirname, '..', 'src', 'data', 'saasData.jsx');
let content = fs.readFileSync(saasDataPath, 'utf8');

const match = content.match(/export const staticSaasTools = (\[[\s\S]*?\n\]);/);
if (!match) {
  console.error('Could not find staticSaasTools in saasData.jsx');
  process.exit(1);
}

let existingTools = JSON.parse(match[1]);

const existingIds = new Set(existingTools.map(t => t.id.toLowerCase()));
const existingNames = new Set(existingTools.map(t => t.name.toLowerCase()));

let addedCount = 0;
let skippedCount = 0;

newTools.forEach(tool => {
  const normId = tool.id.toLowerCase();
  const normName = tool.name.toLowerCase();

  if (!existingIds.has(normId) && !existingNames.has(normName)) {
    existingTools.push(tool);
    existingIds.add(normId);
    existingNames.add(normName);
    addedCount++;
  } else {
    // Enrich existing tool without creating a duplicate
    const idx = existingTools.findIndex(t => t.id.toLowerCase() === normId || t.name.toLowerCase() === normName);
    if (idx !== -1) {
      existingTools[idx] = { ...existingTools[idx], category: tool.category, tagline: tool.tagline || existingTools[idx].tagline };
    }
    skippedCount++;
  }
});

const updatedArrayStr = JSON.stringify(existingTools, null, 2);
content = content.replace(/export const staticSaasTools = \[[\s\S]*?\n\];/, `export const staticSaasTools = ${updatedArrayStr};`);

fs.writeFileSync(saasDataPath, content, 'utf8');
console.log(`Ingestion Complete! Added: ${addedCount} brand new tools | Deduplicated: ${skippedCount} existing tools | Total static tools: ${existingTools.length}`);
