const fs = require('fs');
const path = require('path');

const newTools = [
  {
    "id": "rippling",
    "name": "Rippling",
    "domain": "rippling.com",
    "category": "hr-payroll",
    "tagline": "Unified platform to manage global payroll, HR, IT, and spend",
    "description": "Rippling brings together global payroll, employee benefits, device management, and app access into a single system of record. It is designed for growing businesses and modern workforce operations.",
    "rating": 4.8,
    "reviewsCount": 2850,
    "pricing": "Paid",
    "websiteUrl": "https://rippling.com",
    "affiliateUrl": "https://rippling.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "8.5M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "deel",
    "name": "Deel",
    "domain": "deel.com",
    "category": "hr-payroll",
    "tagline": "Global HR and payroll platform for international hiring and compliance",
    "description": "Deel enables companies to hire, pay, and manage remote contractors and full-time employees in over 150 countries compliant with local laws. It is built for remote-first teams and global organizations.",
    "rating": 4.8,
    "reviewsCount": 3400,
    "pricing": "Paid",
    "websiteUrl": "https://deel.com",
    "affiliateUrl": "https://deel.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "12.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "gusto",
    "name": "Gusto",
    "domain": "gusto.com",
    "category": "hr-payroll",
    "tagline": "All-in-one payroll, benefits, and HR platform for growing small businesses",
    "description": "Gusto automates payroll processing, tax filings, health insurance administration, and employee onboarding. It is tailored specifically for small business owners and HR managers.",
    "rating": 4.7,
    "reviewsCount": 4200,
    "pricing": "Paid",
    "websiteUrl": "https://gusto.com",
    "affiliateUrl": "https://gusto.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "14.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "bamboohr",
    "name": "BambooHR",
    "domain": "bamboohr.com",
    "category": "hr-payroll",
    "tagline": "Complete HR software suite for employee data, payroll, and applicant tracking",
    "description": "BambooHR centralizes employee records, time tracking, performance management, and hiring workflows. It serves growing small to medium-sized businesses modernizing HR admin.",
    "rating": 4.6,
    "reviewsCount": 2100,
    "pricing": "Free Trial",
    "websiteUrl": "https://bamboohr.com",
    "affiliateUrl": "https://bamboohr.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "6.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "remote-com",
    "name": "Remote",
    "domain": "remote.com",
    "category": "hr-payroll",
    "tagline": "Employer of record and global payroll platform for international teams",
    "description": "Remote simplifies paying contractors and full-time employees globally through native Employer of Record (EOR) entities. It is built for companies expanding global talent acquisition without compliance risk.",
    "rating": 4.7,
    "reviewsCount": 1150,
    "pricing": "Paid",
    "websiteUrl": "https://remote.com",
    "affiliateUrl": "https://remote.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.9M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "greenhouse",
    "name": "Greenhouse",
    "domain": "greenhouse.com",
    "category": "hr-payroll",
    "tagline": "Leading applicant tracking system and structured hiring software",
    "description": "Greenhouse helps talent acquisition teams optimize recruitment pipelines, score candidate interviews, and promote structured hiring. It is engineered for fast-scaling startups and enterprise companies.",
    "rating": 4.6,
    "reviewsCount": 1820,
    "pricing": "Paid",
    "websiteUrl": "https://greenhouse.com",
    "affiliateUrl": "https://greenhouse.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "9.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "lever",
    "name": "Lever",
    "domain": "lever.co",
    "category": "hr-payroll",
    "tagline": "Complete talent acquisition suite combining ATS and candidate CRM",
    "description": "Lever unifies candidate sourcing, applicant tracking, and recruitment analytics into a single collaborative platform. It serves talent teams scaling their candidate sourcing and talent relationships.",
    "rating": 4.5,
    "reviewsCount": 1420,
    "pricing": "Paid",
    "websiteUrl": "https://lever.co",
    "affiliateUrl": "https://lever.co",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "workday",
    "name": "Workday",
    "domain": "workday.com",
    "category": "hr-payroll",
    "tagline": "Enterprise cloud platform for human capital management and financial planning",
    "description": "Workday delivers global HR management, workforce planning, talent analytics, and enterprise payroll capabilities. It is designed for large enterprise organizations managing complex global workforces.",
    "rating": 4.4,
    "reviewsCount": 3100,
    "pricing": "Paid",
    "websiteUrl": "https://workday.com",
    "affiliateUrl": "https://workday.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "48.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "paylocity",
    "name": "Paylocity",
    "domain": "paylocity.com",
    "category": "hr-payroll",
    "tagline": "Cloud HR and payroll software delivering employee engagement and admin tools",
    "description": "Paylocity combines payroll automation, time tracking, talent management, and employee communication portals. It is tailored for mid-market HR departments automating workforce management.",
    "rating": 4.5,
    "reviewsCount": 2600,
    "pricing": "Paid",
    "websiteUrl": "https://paylocity.com",
    "affiliateUrl": "https://paylocity.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "18.5M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "paycom",
    "name": "Paycom",
    "domain": "paycom.com",
    "category": "hr-payroll",
    "tagline": "Comprehensive HR and self-directed employee payroll software",
    "description": "Paycom offers single-software architecture for payroll, talent acquisition, timekeeping, and HR management. It features Beti, allowing employees to manage and approve their own payroll prior to payout.",
    "rating": 4.3,
    "reviewsCount": 1950,
    "pricing": "Paid",
    "websiteUrl": "https://paycom.com",
    "affiliateUrl": "https://paycom.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "15.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "adp-run",
    "name": "ADP RUN",
    "domain": "adp.com",
    "category": "hr-payroll",
    "tagline": "Reliable small business payroll and HR compliance platform",
    "description": "ADP RUN provides automated tax filing, direct deposit, employee onboarding, and HR compliance support. It is built for small business owners looking for established payroll reliability.",
    "rating": 4.5,
    "reviewsCount": 3800,
    "pricing": "Paid",
    "websiteUrl": "https://adp.com",
    "affiliateUrl": "https://adp.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "32.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "oyster-hr",
    "name": "Oyster",
    "domain": "oysterhr.com",
    "category": "hr-payroll",
    "tagline": "Global employment platform for hiring, paying, and caring for distributed teams",
    "description": "Oyster automates cross-border employment, compliant contractor management, global benefits, and multi-currency payroll. It serves growing companies expanding global hiring operations.",
    "rating": 4.7,
    "reviewsCount": 820,
    "pricing": "Paid",
    "websiteUrl": "https://oysterhr.com",
    "affiliateUrl": "https://oysterhr.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "papaya-global",
    "name": "Papaya Global",
    "domain": "papayaglobal.com",
    "category": "hr-payroll",
    "tagline": "Global payroll and workforce management platform powered by fintech infrastructure",
    "description": "Papaya Global unifies global payroll, Employer of Record services, and contractor payments across 160+ countries. It is built for enterprise organizations modernizing multi-country payroll.",
    "rating": 4.6,
    "reviewsCount": 650,
    "pricing": "Paid",
    "websiteUrl": "https://papayaglobal.com",
    "affiliateUrl": "https://papayaglobal.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "personio",
    "name": "Personio",
    "domain": "personio.com",
    "category": "hr-payroll",
    "tagline": "The all-in-one HR software for European small and medium-sized enterprises",
    "description": "Personio digitizes core HR processes, applicant tracking, attendance management, and payroll approvals. It is engineered specifically for European SMBs managing workforce compliance.",
    "rating": 4.6,
    "reviewsCount": 1250,
    "pricing": "Free Trial",
    "websiteUrl": "https://personio.com",
    "affiliateUrl": "https://personio.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.5M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "workable",
    "name": "Workable",
    "domain": "workable.com",
    "category": "hr-payroll",
    "tagline": "All-in-one recruiting and HR software for candidate sourcing and hiring",
    "description": "Workable combines AI candidate sourcing, job board syndication, candidate tracking, and employee onboarding. It serves companies looking to streamline hiring workflows and talent acquisition.",
    "rating": 4.6,
    "reviewsCount": 1400,
    "pricing": "Free Trial",
    "websiteUrl": "https://workable.com",
    "affiliateUrl": "https://workable.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "5.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "ashby",
    "name": "Ashby",
    "domain": "ashbyhq.com",
    "category": "hr-payroll",
    "tagline": "All-in-one recruiting platform combining ATS, sourcing, and talent analytics",
    "description": "Ashby consolidates candidate sourcing, scheduling automation, applicant tracking, and recruitment reporting into an ultra-fast platform. It is built for high-growth tech startups and scale-ups.",
    "rating": 4.9,
    "reviewsCount": 510,
    "pricing": "Paid",
    "websiteUrl": "https://ashbyhq.com",
    "affiliateUrl": "https://ashbyhq.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "breezy-hr",
    "name": "Breezy HR",
    "domain": "breezy.hr",
    "category": "hr-payroll",
    "tagline": "Simple applicant tracking system and recruiting software for modern teams",
    "description": "Breezy HR streamlines hiring with visual candidate pipelines, automated messaging, interview scheduling, and background checks. It offers a free tier ideal for small teams making occasional hires.",
    "rating": 4.5,
    "reviewsCount": 1100,
    "pricing": "Freemium",
    "websiteUrl": "https://breezy.hr",
    "affiliateUrl": "https://breezy.hr",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.9M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "jazzhr",
    "name": "JazzHR",
    "domain": "jazzhr.com",
    "category": "hr-payroll",
    "tagline": "Powerful, user-friendly recruitment software tailored for growing businesses",
    "description": "JazzHR replaces spreadsheet hiring with job board posting, resume screening, collaborative candidate evaluation, and offer letters. It serves growing SMBs looking for affordable recruitment tools.",
    "rating": 4.4,
    "reviewsCount": 980,
    "pricing": "Paid",
    "websiteUrl": "https://jazzhr.com",
    "affiliateUrl": "https://jazzhr.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "recruitee",
    "name": "Recruitee by Tellent",
    "domain": "recruitee.com",
    "category": "hr-payroll",
    "tagline": "Collaborative applicant tracking system and talent acquisition platform",
    "description": "Recruitee empowers internal hiring teams to design careers pages, automate candidate workflows, and evaluate applicants collaboratively. It is built for small to mid-sized businesses.",
    "rating": 4.6,
    "reviewsCount": 750,
    "pricing": "Free Trial",
    "websiteUrl": "https://recruitee.com",
    "affiliateUrl": "https://recruitee.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "zoho-recruit",
    "name": "Zoho Recruit",
    "domain": "zoho.com/recruit",
    "category": "hr-payroll",
    "tagline": "Cloud-based applicant tracking system for staffing agencies and HR teams",
    "description": "Zoho Recruit provides candidate sourcing, resume parsing, interview scheduling, and job board publishing. It serves both internal corporate recruiters and commercial staffing agencies.",
    "rating": 4.5,
    "reviewsCount": 890,
    "pricing": "Freemium",
    "websiteUrl": "https://zoho.com/recruit",
    "affiliateUrl": "https://zoho.com/recruit",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "zoho-people",
    "name": "Zoho People",
    "domain": "zoho.com/people",
    "category": "hr-payroll",
    "tagline": "Cloud HR management software for employee onboarding, leave, and performance",
    "description": "Zoho People centralizes core HR databases, leave tracking, time logs, and performance appraisals into one system. It is tailored for small to mid-sized businesses seeking modular HR admin.",
    "rating": 4.4,
    "reviewsCount": 1100,
    "pricing": "Freemium",
    "websiteUrl": "https://zoho.com/people",
    "affiliateUrl": "https://zoho.com/people",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "zenefits",
    "name": "TriNet Zenefits",
    "domain": "zenefits.com",
    "category": "hr-payroll",
    "tagline": "Intuitive HR, benefits administration, and payroll platform for SMBs",
    "description": "Zenefits streamlines core HR administrative tasks, benefits enrollments, time tracking, and automated payroll sync. It serves small and mid-sized businesses looking to simplify employee admin.",
    "rating": 4.2,
    "reviewsCount": 1600,
    "pricing": "Paid",
    "websiteUrl": "https://zenefits.com",
    "affiliateUrl": "https://zenefits.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "justworks",
    "name": "Justworks",
    "domain": "justworks.com",
    "category": "hr-payroll",
    "tagline": "PEO platform simplifying payroll, HR, benefits, and compliance for small business",
    "description": "Justworks operates as a Professional Employer Organization (PEO), pooling businesses to offer enterprise-level health benefits, automated payroll, and HR compliance support. It is built for growing SMBs.",
    "rating": 4.7,
    "reviewsCount": 920,
    "pricing": "Paid",
    "websiteUrl": "https://justworks.com",
    "affiliateUrl": "https://justworks.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.9M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "multiplier",
    "name": "Multiplier",
    "domain": "usemultiplier.com",
    "category": "hr-payroll",
    "tagline": "Global employment platform for hiring, managing, and paying international talent",
    "description": "Multiplier helps companies employ global contractors and full-time workers seamlessly with local legal compliance, benefits, and payroll. It serves startups and enterprises expanding global teams.",
    "rating": 4.8,
    "reviewsCount": 420,
    "pricing": "Paid",
    "websiteUrl": "https://usemultiplier.com",
    "affiliateUrl": "https://usemultiplier.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "lano",
    "name": "Lano",
    "domain": "lano.io",
    "category": "hr-payroll",
    "tagline": "Global payroll consolidation and contractor management platform",
    "description": "Lano integrates existing global payroll providers into a unified dashboard while managing contractor compliance and invoicing. It is engineered for mid-market and enterprise international operations.",
    "rating": 4.6,
    "reviewsCount": 210,
    "pricing": "Paid",
    "websiteUrl": "https://lano.io",
    "affiliateUrl": "https://lano.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "280K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "plane-hr",
    "name": "Plane (formerly Pilot)",
    "domain": "plane.com",
    "category": "hr-payroll",
    "tagline": "Global payroll and contractor payment platform for international teams",
    "description": "Plane handles international payroll, contractor payouts, and health benefits across 240+ countries without markup fees. It is built specifically for remote-first tech startups and growing companies.",
    "rating": 4.8,
    "reviewsCount": 310,
    "pricing": "Paid",
    "websiteUrl": "https://plane.com",
    "affiliateUrl": "https://plane.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "340K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "factorial",
    "name": "Factorial",
    "domain": "factorialhr.com",
    "category": "hr-payroll",
    "tagline": "All-in-one HR software for time management, talent, and payroll processing",
    "description": "Factorial automates leave tracking, time clocking, performance reviews, document management, and payroll reports. It is tailored for small and medium-sized organizations modernizing office administration.",
    "rating": 4.5,
    "reviewsCount": 810,
    "pricing": "Free Trial",
    "websiteUrl": "https://factorialhr.com",
    "affiliateUrl": "https://factorialhr.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "charlie-hr",
    "name": "CharlieHR",
    "domain": "charliehr.com",
    "category": "hr-payroll",
    "tagline": "Effortless HR software and advisor support for UK small businesses",
    "description": "CharlieHR automates UK holiday tracking, onboarding flows, performance reviews, and compliance documents. It is designed specifically for small UK businesses, startups, and creative agencies.",
    "rating": 4.7,
    "reviewsCount": 380,
    "pricing": "Free Trial",
    "websiteUrl": "https://charliehr.com",
    "affiliateUrl": "https://charliehr.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "290K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "hibob",
    "name": "Bob (hiBob)",
    "domain": "hibob.com",
    "category": "hr-payroll",
    "tagline": "Modern HR platform built to drive engagement, culture, and workforce growth",
    "description": "Bob delivers core HR administration alongside company culture tools, performance management, and workforce analytics. It is built for fast-scaling mid-sized and global tech companies.",
    "rating": 4.6,
    "reviewsCount": 950,
    "pricing": "Paid",
    "websiteUrl": "https://hibob.com",
    "affiliateUrl": "https://hibob.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "lattice",
    "name": "Lattice",
    "domain": "lattice.com",
    "category": "hr-payroll",
    "tagline": "Performance management, OKR tracking, and employee engagement platform",
    "description": "Lattice connects 1-on-1s, performance reviews, employee engagement surveys, and career growth tracks into a single HR suite. It serves people-first tech companies and scaling startups.",
    "rating": 4.7,
    "reviewsCount": 1350,
    "pricing": "Paid",
    "websiteUrl": "https://lattice.com",
    "affiliateUrl": "https://lattice.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "15five",
    "name": "15Five",
    "domain": "15five.com",
    "category": "hr-payroll",
    "tagline": "Performance management platform for employee engagement and leadership development",
    "description": "15Five combines weekly employee check-ins, 360 performance reviews, OKR tracking, and manager training tools. It is engineered for HR leaders fostering workplace culture and manager growth.",
    "rating": 4.6,
    "reviewsCount": 1100,
    "pricing": "Paid",
    "websiteUrl": "https://15five.com",
    "affiliateUrl": "https://15five.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "culture-amp",
    "name": "Culture Amp",
    "domain": "cultureamp.com",
    "category": "hr-payroll",
    "tagline": "Employee experience platform for employee engagement and performance management",
    "description": "Culture Amp collects employee feedback, conducts engagement surveys, and tracks performance metrics backed by people analytics. It serves mid-market and enterprise HR leadership.",
    "rating": 4.6,
    "reviewsCount": 1200,
    "pricing": "Paid",
    "websiteUrl": "https://cultureamp.com",
    "affiliateUrl": "https://cultureamp.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.9M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "smartrecruiters",
    "name": "SmartRecruiters",
    "domain": "smartrecruiters.com",
    "category": "hr-payroll",
    "tagline": "Enterprise talent acquisition suite and applicant tracking software",
    "description": "SmartRecruiters offers global recruitment management, automated candidate scoring, interview scheduling, and offer management. It is designed for high-volume enterprise talent acquisition teams.",
    "rating": 4.4,
    "reviewsCount": 1150,
    "pricing": "Paid",
    "websiteUrl": "https://smartrecruiters.com",
    "affiliateUrl": "https://smartrecruiters.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "clearcompany",
    "name": "ClearCompany",
    "domain": "clearcompany.com",
    "category": "hr-payroll",
    "tagline": "Talent management software combining recruiting, onboarding, and performance",
    "description": "ClearCompany unifies candidate sourcing, applicant tracking, paperless onboarding, and goal tracking into a single system. It serves small to enterprise businesses streamlining talent management.",
    "rating": 4.5,
    "reviewsCount": 890,
    "pricing": "Paid",
    "websiteUrl": "https://clearcompany.com",
    "affiliateUrl": "https://clearcompany.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "teamtailor",
    "name": "Teamtailor",
    "domain": "teamtailor.com",
    "category": "hr-payroll",
    "tagline": "Employer branding and applicant tracking software built for modern recruitment",
    "description": "Teamtailor enables companies to build career sites easily while managing candidate pipelines and recruitment marketing. It serves growing companies focusing on employer brand and candidate experience.",
    "rating": 4.7,
    "reviewsCount": 910,
    "pricing": "Free Trial",
    "websiteUrl": "https://teamtailor.com",
    "affiliateUrl": "https://teamtailor.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "pinpoint",
    "name": "Pinpoint",
    "domain": "pinpointhq.com",
    "category": "hr-payroll",
    "tagline": "Applicant tracking system designed for in-house talent acquisition teams",
    "description": "Pinpoint provides candidate sourcing, blind recruitment controls, interview scheduling, and paperless onboarding workflows. It is engineered for in-house HR and talent acquisition departments.",
    "rating": 4.8,
    "reviewsCount": 290,
    "pricing": "Paid",
    "websiteUrl": "https://pinpointhq.com",
    "affiliateUrl": "https://pinpointhq.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "380K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "manatal",
    "name": "Manatal",
    "domain": "manatal.com",
    "category": "hr-payroll",
    "tagline": "AI-powered recruitment software and applicant tracking system",
    "description": "Manatal utilizes AI candidate matching, social media profile enrichment, and job board posting to accelerate hiring. It serves recruitment agencies and internal HR teams worldwide.",
    "rating": 4.7,
    "reviewsCount": 450,
    "pricing": "Free Trial",
    "websiteUrl": "https://manatal.com",
    "affiliateUrl": "https://manatal.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "950K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "orangehrm",
    "name": "OrangeHRM",
    "domain": "orangehrm.com",
    "category": "hr-payroll",
    "tagline": "Open-source and cloud HR management software for businesses worldwide",
    "description": "OrangeHRM delivers modular human resource management covering employee records, leave management, time tracking, and recruitment. It provides both free open-source and enterprise cloud deployment.",
    "rating": 4.3,
    "reviewsCount": 620,
    "pricing": "Freemium",
    "websiteUrl": "https://orangehrm.com",
    "affiliateUrl": "https://orangehrm.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "780K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "connecteam",
    "name": "Connecteam",
    "domain": "connecteam.com",
    "category": "hr-payroll",
    "tagline": "All-in-one workforce management app for deskless and mobile employees",
    "description": "Connecteam provides employee scheduling, GPS time tracking, mobile training, digital checklists, and internal chat. It is engineered for non-desk, retail, construction, and field service teams.",
    "rating": 4.8,
    "reviewsCount": 1650,
    "pricing": "Freemium",
    "websiteUrl": "https://connecteam.com",
    "affiliateUrl": "https://connecteam.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "deputy",
    "name": "Deputy",
    "domain": "deputy.com",
    "category": "hr-payroll",
    "tagline": "Employee scheduling, time tracking, and shift management software",
    "description": "Deputy simplifies shift scheduling, facial-recognition time clocking, labor compliance, and team communication. It serves healthcare, hospitality, retail, and shift-based businesses.",
    "rating": 4.6,
    "reviewsCount": 1250,
    "pricing": "Free Trial",
    "websiteUrl": "https://deputy.com",
    "affiliateUrl": "https://deputy.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "when-i-work",
    "name": "When I Work",
    "domain": "wheniwork.com",
    "category": "hr-payroll",
    "tagline": "Employee scheduling and time tracking app for hourly workforces",
    "description": "When I Work enables quick team shift scheduling, mobile clock-ins, shift swapping, and payroll exporting. It is built for small-to-medium businesses with hourly employees.",
    "rating": 4.5,
    "reviewsCount": 1100,
    "pricing": "Free Trial",
    "websiteUrl": "https://wheniwork.com",
    "affiliateUrl": "https://wheniwork.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "7shifts",
    "name": "7shifts",
    "domain": "7shifts.com",
    "category": "hr-payroll",
    "tagline": "Team management and shift scheduling software built for restaurants",
    "description": "7shifts optimizes restaurant labor scheduling, tip pooling, time tracking, and team messaging. It is engineered specifically for restaurant managers, bars, and food service operations.",
    "rating": 4.7,
    "reviewsCount": 980,
    "pricing": "Freemium",
    "websiteUrl": "https://7shifts.com",
    "affiliateUrl": "https://7shifts.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "homebase",
    "name": "Homebase",
    "domain": "joinhomebase.com",
    "category": "hr-payroll",
    "tagline": "Everything local small businesses need to manage hourly workers",
    "description": "Homebase provides shift scheduling, time clocking, payroll processing, and HR compliance support in one place. It offers a generous free tier for single-location small businesses.",
    "rating": 4.6,
    "reviewsCount": 1850,
    "pricing": "Freemium",
    "websiteUrl": "https://joinhomebase.com",
    "affiliateUrl": "https://joinhomebase.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "pento",
    "name": "Pento",
    "domain": "pento.io",
    "category": "hr-payroll",
    "tagline": "Automated real-time payroll software for modern finance and HR teams",
    "description": "Pento eliminates traditional outsourced payroll bureaus by automating calculations, tax filings, and bank payouts directly. It serves modern UK and European tech companies.",
    "rating": 4.8,
    "reviewsCount": 210,
    "pricing": "Paid",
    "websiteUrl": "https://pento.io",
    "affiliateUrl": "https://pento.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "240K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "check-hq",
    "name": "Check",
    "domain": "checkhq.com",
    "category": "hr-payroll",
    "tagline": "Payroll infrastructure API to build embedded payroll into any app",
    "description": "Check provides API infrastructure that enables SaaS platforms to embed custom payroll products directly into their applications. It is engineered for software developers and vertical SaaS founders.",
    "rating": 4.9,
    "reviewsCount": 95,
    "pricing": "Paid",
    "websiteUrl": "https://checkhq.com",
    "affiliateUrl": "https://checkhq.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "150K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "zeal-payroll",
    "name": "Zeal",
    "domain": "zeal.com",
    "category": "hr-payroll",
    "tagline": "Embedded payroll API infrastructure for platforms and staffing tech",
    "description": "Zeal enables software platforms to build native, compliant payroll workflows for W-2 employees and 1099 contractors. It serves developers and technology platforms offering financial tools.",
    "rating": 4.8,
    "reviewsCount": 80,
    "pricing": "Paid",
    "websiteUrl": "https://zeal.com",
    "affiliateUrl": "https://zeal.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "110K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "jobvite",
    "name": "Jobvite",
    "domain": "jobvite.com",
    "category": "hr-payroll",
    "tagline": "Comprehensive talent acquisition suite for candidate engagement and hiring",
    "description": "Jobvite combines applicant tracking, recruitment marketing, applicant screening, and employee referral management. It serves mid-market and enterprise talent acquisition teams.",
    "rating": 4.2,
    "reviewsCount": 1150,
    "pricing": "Paid",
    "websiteUrl": "https://jobvite.com",
    "affiliateUrl": "https://jobvite.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "trinet",
    "name": "TriNet",
    "domain": "trinet.com",
    "category": "hr-payroll",
    "tagline": "Full-service PEO solution providing industry-tailored HR, payroll, and benefits",
    "description": "TriNet offers comprehensive PEO services delivering enterprise benefits, payroll processing, risk mitigation, and HR consulting. It is tailored for industry-specific small to medium-sized businesses.",
    "rating": 4.3,
    "reviewsCount": 1400,
    "pricing": "Paid",
    "websiteUrl": "https://trinet.com",
    "affiliateUrl": "https://trinet.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.9M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "bonusly",
    "name": "Bonusly",
    "domain": "bonus.ly",
    "category": "hr-payroll",
    "tagline": "Fun, interactive peer-to-peer recognition and employee rewards platform",
    "description": "Bonusly enables team members to recognize peers with small micro-bonuses that can be redeemed for gift cards or donations. It is designed to boost employee retention and workplace engagement.",
    "rating": 4.8,
    "reviewsCount": 2100,
    "pricing": "Paid",
    "websiteUrl": "https://bonus.ly",
    "affiliateUrl": "https://bonus.ly",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.6M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "fond-rewards",
    "name": "Fond by Rewards Network",
    "domain": "fond.co",
    "category": "hr-payroll",
    "tagline": "Employee recognition and corporate perks platform for company culture",
    "description": "Fond consolidates peer recognition, corporate discount perks, and employee milestone awards into one portal. It serves enterprise HR teams looking to build employee appreciation programs.",
    "rating": 4.6,
    "reviewsCount": 420,
    "pricing": "Paid",
    "websiteUrl": "https://fond.co",
    "affiliateUrl": "https://fond.co",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "310K",
    "isFreeTier": false,
    "isOpenSource": false
  }
];

const saasDataPath = path.join(__dirname, '..', 'src', 'data', 'saasData.jsx');
let content = fs.readFileSync(saasDataPath, 'utf8');

const match = content.match(/export const staticSaasTools = (\[[\s\S]*?\n\]);/);
if (!match) {
  console.error('Could not find staticSaasTools in saasData.jsx');
  process.exit(1);
}

let existingTools = JSON.parse(match[1]);

const existingIds = new Set(existingTools.map(t => t.id.toLowerCase()));
const existingNames = new Set(existingTools.map(t => t.name.toLowerCase()));

let addedCount = 0;
let skippedCount = 0;

newTools.forEach(tool => {
  const normId = tool.id.toLowerCase();
  const normName = tool.name.toLowerCase();

  if (!existingIds.has(normId) && !existingNames.has(normName)) {
    existingTools.push(tool);
    existingIds.add(normId);
    existingNames.add(normName);
    addedCount++;
  } else {
    // Enrich existing tool without creating a duplicate
    const idx = existingTools.findIndex(t => t.id.toLowerCase() === normId || t.name.toLowerCase() === normName);
    if (idx !== -1) {
      existingTools[idx] = { ...existingTools[idx], category: tool.category, tagline: tool.tagline || existingTools[idx].tagline };
    }
    skippedCount++;
  }
});

const updatedArrayStr = JSON.stringify(existingTools, null, 2);
content = content.replace(/export const staticSaasTools = \[[\s\S]*?\n\];/, `export const staticSaasTools = ${updatedArrayStr};`);

fs.writeFileSync(saasDataPath, content, 'utf8');
console.log(`Ingestion Complete! Added: ${addedCount} brand new tools | Deduplicated: ${skippedCount} existing tools | Total static tools: ${existingTools.length}`);
