const fs = require('fs');
const path = require('path');

const newTools = [
  {
    "id": "suno",
    "name": "Suno",
    "domain": "suno.com",
    "category": "ai-music-audio",
    "tagline": "Generative AI music platform turning text prompts into full songs",
    "description": "Suno allows users to create full-length songs complete with vocals, instrumentation, and lyrics using simple text prompts. It is designed for creators, musicians, and hobbyists looking to produce high-quality original tracks instantly.",
    "rating": 4.8,
    "reviewsCount": 1250,
    "pricing": "Freemium",
    "websiteUrl": "https://suno.com",
    "affiliateUrl": "https://suno.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "18.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "udio",
    "name": "Udio",
    "domain": "udio.com",
    "category": "ai-music-audio",
    "tagline": "Advanced AI music generation engine with high-fidelity control",
    "description": "Udio produces high-fidelity music tracks across diverse genres with nuanced control over arrangement and lyrics. It serves music producers and content creators seeking professional-grade audio generation.",
    "rating": 4.7,
    "reviewsCount": 890,
    "pricing": "Freemium",
    "websiteUrl": "https://udio.com",
    "affiliateUrl": "https://udio.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "9.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "elevenlabs",
    "name": "ElevenLabs",
    "domain": "elevenlabs.io",
    "category": "ai-music-audio",
    "tagline": "Realistic AI voice generator, text-to-speech, and sound effect studio",
    "description": "ElevenLabs offers hyper-realistic AI voice synthesis, voice cloning, and text-to-speech capabilities in dozens of languages. It is widely used by developers, audio creators, and video editors worldwide.",
    "rating": 4.9,
    "reviewsCount": 2100,
    "pricing": "Freemium",
    "websiteUrl": "https://elevenlabs.io",
    "affiliateUrl": "https://elevenlabs.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "22.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "soundraw",
    "name": "Soundraw",
    "domain": "soundraw.io",
    "category": "ai-music-audio",
    "tagline": "AI music generator for creators with customizable arrangements",
    "description": "Soundraw enables creators to generate royalty-free background music and customize intro length, chorus position, and tempo. It is tailored for YouTubers, podcasters, and video producers.",
    "rating": 4.6,
    "reviewsCount": 420,
    "pricing": "Freemium",
    "websiteUrl": "https://soundraw.io",
    "affiliateUrl": "https://soundraw.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "mubert",
    "name": "Mubert",
    "domain": "mubert.com",
    "category": "ai-music-audio",
    "tagline": "Real-time AI generative audio for content creators and apps",
    "description": "Mubert generates real-time streaming AI soundtracks for videos, podcasts, and mobile apps. It offers an extensive API for developers alongside a direct studio interface for video creators.",
    "rating": 4.5,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://mubert.com",
    "affiliateUrl": "https://mubert.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "boomy",
    "name": "Boomy",
    "domain": "boomy.com",
    "category": "ai-music-audio",
    "tagline": "Create original songs in seconds and publish to streaming platforms",
    "description": "Boomy allows users with no musical background to create complete songs using AI algorithms in seconds. Users can release their creations directly to streaming services like Spotify and Apple Music.",
    "rating": 4.4,
    "reviewsCount": 310,
    "pricing": "Freemium",
    "websiteUrl": "https://boomy.com",
    "affiliateUrl": "https://boomy.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "850K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "lalal-ai",
    "name": "LALAL.AI",
    "domain": "lalal.ai",
    "category": "ai-music-audio",
    "tagline": "High-precision AI vocal remover and music stem splitter",
    "description": "LALAL.AI uses neural networks to extract vocals, drums, bass, guitar, and piano from any audio or video file. It is built for DJs, music producers, and audio engineers seeking clean stem isolation.",
    "rating": 4.8,
    "reviewsCount": 650,
    "pricing": "Freemium",
    "websiteUrl": "https://lalal.ai",
    "affiliateUrl": "https://lalal.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "play-ht",
    "name": "PlayHT",
    "domain": "play.ht",
    "category": "ai-music-audio",
    "tagline": "Conversational AI voice generator and low-latency voice cloning",
    "description": "PlayHT generates ultra-realistic text-to-speech audio and real-time voice clones for narrative content and interactive AI agents. It serves e-learning creators, podcasters, and enterprise applications.",
    "rating": 4.6,
    "reviewsCount": 510,
    "pricing": "Freemium",
    "websiteUrl": "https://play.ht",
    "affiliateUrl": "https://play.ht",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "murf-ai",
    "name": "Murf AI",
    "domain": "murf.ai",
    "category": "ai-music-audio",
    "tagline": "Versatile AI voiceover studio for presentations and video creators",
    "description": "Murf AI converts text into natural-sounding voiceovers for e-learning videos, corporate presentations, and marketing ads. It includes precise timing adjustments, pitch controls, and background music overlays.",
    "rating": 4.7,
    "reviewsCount": 780,
    "pricing": "Freemium",
    "websiteUrl": "https://murf.ai",
    "affiliateUrl": "https://murf.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "descript",
    "name": "Descript",
    "domain": "descript.com",
    "category": "ai-music-audio",
    "tagline": "Text-based video and audio editing with voice cloning and cleanup",
    "description": "Descript transcribes audio and video files so users can edit media simply by editing the text transcript. It features AI filler word removal, audio enhancement, and custom voice regeneration.",
    "rating": 4.8,
    "reviewsCount": 1400,
    "pricing": "Freemium",
    "websiteUrl": "https://descript.com",
    "affiliateUrl": "https://descript.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "6.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "krisp",
    "name": "Krisp",
    "domain": "krisp.ai",
    "category": "ai-music-audio",
    "tagline": "AI noise cancellation and background voice suppression app",
    "description": "Krisp runs locally on desktop devices to mute background noise and echo during live calls in real time. It is designed for remote professionals, call centers, and podcasters wanting pristine audio.",
    "rating": 4.8,
    "reviewsCount": 950,
    "pricing": "Freemium",
    "websiteUrl": "https://krisp.ai",
    "affiliateUrl": "https://krisp.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "adobe-podcast",
    "name": "Adobe Podcast",
    "domain": "podcast.adobe.com",
    "category": "ai-music-audio",
    "tagline": "AI-powered web audio recording, editing, and speech enhancement",
    "description": "Adobe Podcast offers AI speech enhancement tools that eliminate background noise and optimize mic frequencies to sound like a studio setup. It provides browser-based recording and transcript-based editing.",
    "rating": 4.7,
    "reviewsCount": 830,
    "pricing": "Freemium",
    "websiteUrl": "https://podcast.adobe.com",
    "affiliateUrl": "https://podcast.adobe.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "aiva",
    "name": "AIVA",
    "domain": "aiva.ai",
    "category": "ai-music-audio",
    "tagline": "AI soundtrack composer for films, video games, and commercials",
    "description": "AIVA composes original classical, cinematic, and electronic music scores based on predefined style profiles. It provides full MIDI and audio export options for music directors and game developers.",
    "rating": 4.6,
    "reviewsCount": 290,
    "pricing": "Freemium",
    "websiteUrl": "https://aiva.ai",
    "affiliateUrl": "https://aiva.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "beatoven-ai",
    "name": "Beatoven.ai",
    "domain": "beatoven.ai",
    "category": "ai-music-audio",
    "tagline": "Royalty-free mood-based background music generator for video and podcasts",
    "description": "Beatoven.ai uses advanced AI music generation techniques to compose unique mood-based background tracks. It helps content creators tailor audio tracks to fit specific scene moods and durations.",
    "rating": 4.5,
    "reviewsCount": 210,
    "pricing": "Freemium",
    "websiteUrl": "https://beatoven.ai",
    "affiliateUrl": "https://beatoven.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "510K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "voice-ai",
    "name": "Voice.ai",
    "domain": "voice.ai",
    "category": "ai-music-audio",
    "tagline": "Real-time AI voice changer for gaming, streaming, and content creation",
    "description": "Voice.ai provides a real-time voice changer engine powered by deep learning algorithms. Gamers, streamers, and VTubers use it to transform their voice live during online calls or gaming sessions.",
    "rating": 4.4,
    "reviewsCount": 480,
    "pricing": "Freemium",
    "websiteUrl": "https://voice.ai",
    "affiliateUrl": "https://voice.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.9M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "speechify",
    "name": "Speechify",
    "domain": "speechify.com",
    "category": "ai-music-audio",
    "tagline": "AI text-to-speech reader for web pages, PDFs, and books",
    "description": "Speechify reads written text out loud using natural, fluid AI voice engines across desktop and mobile devices. It is widely used by Dyslexic readers, students, and professionals to consume content faster.",
    "rating": 4.8,
    "reviewsCount": 1650,
    "pricing": "Freemium",
    "websiteUrl": "https://speechify.com",
    "affiliateUrl": "https://speechify.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "8.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "voicemod",
    "name": "Voicemod",
    "domain": "voicemod.net",
    "category": "ai-music-audio",
    "tagline": "Real-time AI voice modifier and soundboard for desktop applications",
    "description": "Voicemod modifies live voice input with custom AI voice filters, pitch modulation, and built-in sound effects. It integrates into Discord, OBS, Twitch, and major online multiplayer games.",
    "rating": 4.7,
    "reviewsCount": 1100,
    "pricing": "Freemium",
    "websiteUrl": "https://voicemod.net",
    "affiliateUrl": "https://voicemod.net",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "6.7M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "auphonic",
    "name": "Auphonic",
    "domain": "auphonic.com",
    "category": "ai-music-audio",
    "tagline": "Automated AI audio mastering and leveling tool for podcasters",
    "description": "Auphonic uses AI algorithms to handle loudness normalization, noise reduction, and automatic levelling for spoken audio. It is an industry favorite for podcasters, broadcasters, and radio producers.",
    "rating": 4.7,
    "reviewsCount": 340,
    "pricing": "Freemium",
    "websiteUrl": "https://auphonic.com",
    "affiliateUrl": "https://auphonic.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "ripx-daw",
    "name": "RipX DAW",
    "domain": "hit-shaper.com",
    "category": "ai-music-audio",
    "tagline": "AI-powered stem separation DAW for audio editing and remixing",
    "description": "RipX separates mixed audio files into fully editable notes, vocals, and instrument stems inside a visual DAW. It empowers remixers, educators, and producers to manipulate existing audio tracks.",
    "rating": 4.6,
    "reviewsCount": 190,
    "pricing": "Free Trial",
    "websiteUrl": "https://hit-shaper.com",
    "affiliateUrl": "https://hit-shaper.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "230K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "lovo-ai",
    "name": "Lovo.ai",
    "domain": "lovo.ai",
    "category": "ai-music-audio",
    "tagline": "Award-winning AI voice generator and text-to-speech platform",
    "description": "Lovo.ai delivers realistic AI voiceovers with emotional depth and fine-tuned pitch controls for marketing and video content. It features Genny, an all-in-one AI voiceover and video creation tool.",
    "rating": 4.6,
    "reviewsCount": 430,
    "pricing": "Freemium",
    "websiteUrl": "https://lovo.ai",
    "affiliateUrl": "https://lovo.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "respeecher",
    "name": "Respeecher",
    "domain": "respeecher.com",
    "category": "ai-music-audio",
    "tagline": "Hollywood-grade AI voice cloning for film, TV, and game development",
    "description": "Respeecher allows voice actors to sound like another person, historical figure, or younger version of themselves using advanced AI cloning. It is utilized in major film studios and game projects.",
    "rating": 4.8,
    "reviewsCount": 160,
    "pricing": "Paid",
    "websiteUrl": "https://respeecher.com",
    "affiliateUrl": "https://respeecher.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "180K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "splitter-ai",
    "name": "Splitter.ai",
    "domain": "splitter.ai",
    "category": "ai-music-audio",
    "tagline": "AI audio stem isolation and vocal extraction engine",
    "description": "Splitter.ai uses machine learning models to split songs into individual tracks like drums, vocals, bass, and piano. It is heavily relied upon by music producers, sample diggers, and audio technicians.",
    "rating": 4.5,
    "reviewsCount": 270,
    "pricing": "Freemium",
    "websiteUrl": "https://splitter.ai",
    "affiliateUrl": "https://splitter.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "690K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "soundful",
    "name": "Soundful",
    "domain": "soundful.com",
    "category": "ai-music-audio",
    "tagline": "AI royalty-free background music generator for producers and brands",
    "description": "Soundful uses AI to instantly generate royalty-free background tracks for videos, streams, and podcasts. Users can adjust BPM, key, and instrument layers to customize tracks.",
    "rating": 4.6,
    "reviewsCount": 330,
    "pricing": "Freemium",
    "websiteUrl": "https://soundful.com",
    "affiliateUrl": "https://soundful.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "820K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "landr",
    "name": "LANDR",
    "domain": "landr.com",
    "category": "ai-music-audio",
    "tagline": "AI automated music mastering, distribution, and plugin suite",
    "description": "LANDR provides automated AI music mastering that instantly analyzes tracks and applies custom EQ and compression. It also offers digital music distribution, plugins, and sample libraries for musicians.",
    "rating": 4.7,
    "reviewsCount": 920,
    "pricing": "Freemium",
    "websiteUrl": "https://landr.com",
    "affiliateUrl": "https://landr.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "ecrett-music",
    "name": "Ecrett Music",
    "domain": "ecrettmusic.com",
    "category": "ai-music-audio",
    "tagline": "Intuitive AI music composer for video creators and game developers",
    "description": "Ecrett Music allows creators to generate custom soundtracks based on scene mood and video category. Its intuitive interface lets users quickly rearrange instrument structures and track lengths.",
    "rating": 4.4,
    "reviewsCount": 180,
    "pricing": "Paid",
    "websiteUrl": "https://ecrettmusic.com",
    "affiliateUrl": "https://ecrettmusic.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "210K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "cyanite-ai",
    "name": "Cyanite.ai",
    "domain": "cyanite.ai",
    "category": "ai-music-audio",
    "tagline": "AI music tagging, mood analysis, and audio search engine",
    "description": "Cyanite.ai automatically analyzes and tags large music catalogs with key metadata like mood, genre, and instrumentation. It helps music publishers and sync agencies search audio libraries efficiently.",
    "rating": 4.6,
    "reviewsCount": 140,
    "pricing": "Free Trial",
    "websiteUrl": "https://cyanite.ai",
    "affiliateUrl": "https://cyanite.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "120K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "emastered",
    "name": "eMastered",
    "domain": "emastered.com",
    "category": "ai-music-audio",
    "tagline": "Instant online AI audio mastering built by Grammy-winning engineers",
    "description": "eMastered leverages machine learning to master audio tracks automatically in a web browser within seconds. Producers can upload reference tracks to achieve professional commercial loudness and balance.",
    "rating": 4.5,
    "reviewsCount": 410,
    "pricing": "Free Trial",
    "websiteUrl": "https://emastered.com",
    "affiliateUrl": "https://emastered.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "650K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "audiocraft",
    "name": "AudioCraft (Meta)",
    "domain": "github.com/facebookresearch/audiocraft",
    "category": "ai-music-audio",
    "tagline": "Open-source generative AI framework for music and audio research",
    "description": "AudioCraft is an open-source generative audio library created by Meta containing models like MusicGen and AudioGen. It enables developers and researchers to generate high-quality audio locally.",
    "rating": 4.8,
    "reviewsCount": 560,
    "pricing": "Free",
    "websiteUrl": "https://github.com/facebookresearch/audiocraft",
    "affiliateUrl": "https://github.com/facebookresearch/audiocraft",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "musicfy",
    "name": "Musicfy",
    "domain": "musicfy.lol",
    "category": "ai-music-audio",
    "tagline": "Create custom AI voice models and transform vocals instantly",
    "description": "Musicfy allows users to clone their own voice or select AI voice models to sing any song or text input. It features AI text-to-music capabilities and stem separation features.",
    "rating": 4.5,
    "reviewsCount": 310,
    "pricing": "Freemium",
    "websiteUrl": "https://musicfy.lol",
    "affiliateUrl": "https://musicfy.lol",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "950K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "kits-ai",
    "name": "Kits AI",
    "domain": "kits.ai",
    "category": "ai-music-audio",
    "tagline": "AI voice platform designed specifically for music creators and producers",
    "description": "Kits AI provides royalty-free AI voice models, vocal conversion tools, and custom voice model training for musicians. It empowers producers to generate professional studio vocal takes instantly.",
    "rating": 4.7,
    "reviewsCount": 390,
    "pricing": "Freemium",
    "websiteUrl": "https://kits.ai",
    "affiliateUrl": "https://kits.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.3M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "vocal-remover",
    "name": "VocalRemover.media",
    "domain": "vocalremover.media",
    "category": "ai-music-audio",
    "tagline": "Free browser-based AI vocal remover and karaoke track creator",
    "description": "VocalRemover uses AI algorithms to separate voice tracks from musical instruments directly in web browsers. It includes extra utilities like pitch shifters, BPM finders, and audio joiners.",
    "rating": 4.6,
    "reviewsCount": 720,
    "pricing": "Free",
    "websiteUrl": "https://vocalremover.media",
    "affiliateUrl": "https://vocalremover.media",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "5.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "moises-ai",
    "name": "Moises.ai",
    "domain": "moises.ai",
    "category": "ai-music-audio",
    "tagline": "The ultimate AI app for practicing musicians and stem separation",
    "description": "Moises allows musicians to isolate instruments, detect key and tempo, and slow down tracks for practice. Its mobile and desktop apps assist music students, band practice, and vocal rehearsal.",
    "rating": 4.8,
    "reviewsCount": 1850,
    "pricing": "Freemium",
    "websiteUrl": "https://moises.ai",
    "affiliateUrl": "https://moises.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "revocalize-ai",
    "name": "Revocalize AI",
    "domain": "revocalize.ai",
    "category": "ai-music-audio",
    "tagline": "AI vocal synthesis, voice transformation, and pitch tuning engine",
    "description": "Revocalize AI transforms existing vocal tracks into custom studio-grade voice models without pitch artifacting. It helps sound designers and record labels adjust vocal tracks dynamically.",
    "rating": 4.5,
    "reviewsCount": 170,
    "pricing": "Freemium",
    "websiteUrl": "https://revocalize.ai",
    "affiliateUrl": "https://revocalize.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "260K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "izotope-ozone",
    "name": "iZotope Ozone",
    "domain": "izotope.com",
    "category": "ai-music-audio",
    "tagline": "Industry-leading AI-assisted audio mastering plugin suite",
    "description": "iZotope Ozone utilizes intelligent Master Assistant AI to suggest optimal EQ, dynamic control, and loudness targets for tracks. It is an industry standard across professional recording studios.",
    "rating": 4.9,
    "reviewsCount": 1120,
    "pricing": "Paid",
    "websiteUrl": "https://izotope.com",
    "affiliateUrl": "https://izotope.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.7M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "so-vits-svc",
    "name": "So-VITS-SVC",
    "domain": "github.com/svc-develop-team/so-vits-svc",
    "category": "ai-music-audio",
    "tagline": "Open-source singing voice conversion neural network framework",
    "description": "So-VITS-SVC is an open-source deep learning framework designed to convert singing voice audio into target trained voices. It is widely used in music research communities and specialized audio development.",
    "rating": 4.7,
    "reviewsCount": 490,
    "pricing": "Free",
    "websiteUrl": "https://github.com/svc-develop-team/so-vits-svc",
    "affiliateUrl": "https://github.com/svc-develop-team/so-vits-svc",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "820K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "rvc-beta",
    "name": "Retrieval-based Voice Conversion (RVC)",
    "domain": "github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI",
    "category": "ai-music-audio",
    "tagline": "Fast, open-source real-time voice conversion framework",
    "description": "RVC is an open-source web UI framework that trains voice models rapidly with minimal audio data. It supports real-time singing and speaking voice transformations locally on desktop GPUs.",
    "rating": 4.8,
    "reviewsCount": 890,
    "pricing": "Free",
    "websiteUrl": "https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI",
    "affiliateUrl": "https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "sonix-ai",
    "name": "Sonix",
    "domain": "sonix.ai",
    "category": "ai-music-audio",
    "tagline": "Automated audio transcription, translation, and speech-to-text platform",
    "description": "Sonix uses machine learning to transcribe audio files, generate captions, and translate transcripts in over 40 languages. It serves journalists, podcasters, and media production companies.",
    "rating": 4.7,
    "reviewsCount": 540,
    "pricing": "Free Trial",
    "websiteUrl": "https://sonix.ai",
    "affiliateUrl": "https://sonix.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "wavtool",
    "name": "WavTool",
    "domain": "wavtool.com",
    "category": "ai-music-audio",
    "tagline": "Browser-based DAW featuring built-in AI assistant for music production",
    "description": "WavTool is a complete web-based digital audio workstation equipped with an integrated AI assistant named Conductor. It helps producers generate MIDI melodies, synthesize instruments, and edit audio.",
    "rating": 4.6,
    "reviewsCount": 230,
    "pricing": "Freemium",
    "websiteUrl": "https://wavtool.com",
    "affiliateUrl": "https://wavtool.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "340K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "stable-audio",
    "name": "Stable Audio",
    "domain": "stableaudio.com",
    "category": "ai-music-audio",
    "tagline": "Generative AI music and sound effects generator by Stability AI",
    "description": "Stable Audio produces high-quality multi-track audio and sound effects from text descriptions. Built on diffusion models, it provides royalty-free audio for sound designers and music creators.",
    "rating": 4.7,
    "reviewsCount": 610,
    "pricing": "Freemium",
    "websiteUrl": "https://stableaudio.com",
    "affiliateUrl": "https://stableaudio.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "soundtrap-storytellers",
    "name": "Soundtrap by Spotify",
    "domain": "soundtrap.com",
    "category": "ai-music-audio",
    "tagline": "Collaborative online studio with smart transcription and vocal tools",
    "description": "Soundtrap provides a cloud-based recording studio equipped with smart voice cleanup, auto-tune, and interactive podcast transcription. It enables real-time collaboration for musicians and podcasters.",
    "rating": 4.6,
    "reviewsCount": 880,
    "pricing": "Freemium",
    "websiteUrl": "https://soundtrap.com",
    "affiliateUrl": "https://soundtrap.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "aimi-fm",
    "name": "Aimi.fm",
    "domain": "aimi.fm",
    "category": "ai-music-audio",
    "tagline": "Continuous generative AI music playback and interactive listening",
    "description": "Aimi.fm generates continuous, non-repeating ambient and electronic music streams powered by AI. Listeners can interact with music elements in real time to alter beat dynamics and mood intensity.",
    "rating": 4.5,
    "reviewsCount": 130,
    "pricing": "Freemium",
    "websiteUrl": "https://aimi.fm",
    "affiliateUrl": "https://aimi.fm",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "150K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "sound-search-audiostrip",
    "name": "AudioStrip",
    "domain": "audiostrip.com",
    "category": "ai-music-audio",
    "tagline": "Fast online AI vocal isolation and instrumental separation",
    "description": "AudioStrip allows music producers to quickly separate vocals from instrumental backing tracks using deep learning. It offers clean stem exports for bootlegs, remixes, and practice tracks.",
    "rating": 4.5,
    "reviewsCount": 260,
    "pricing": "Freemium",
    "websiteUrl": "https://audiostrip.com",
    "affiliateUrl": "https://audiostrip.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "580K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "matchering",
    "name": "Matchering",
    "domain": "github.com/sergree/matchering",
    "category": "ai-music-audio",
    "tagline": "Open-source reference-based AI audio mastering container",
    "description": "Matchering is an open-source audio processing framework that matches the target track's tone and RMS balance to a reference file. It provides automated mastering for independent audio developers.",
    "rating": 4.7,
    "reviewsCount": 210,
    "pricing": "Free",
    "websiteUrl": "https://github.com/sergree/matchering",
    "affiliateUrl": "https://github.com/sergree/matchering",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "190K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "deepdub-ai",
    "name": "Deepdub",
    "domain": "deepdub.ai",
    "category": "ai-music-audio",
    "tagline": "AI-powered entertainment dubbing, voice translation, and localization",
    "description": "Deepdub localizes film, TV, and gaming content across global languages using expressively cloned AI voices. It preserves original actor dynamics while matching regional dubbing standards.",
    "rating": 4.6,
    "reviewsCount": 110,
    "pricing": "Paid",
    "websiteUrl": "https://deepdub.ai",
    "affiliateUrl": "https://deepdub.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "140K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "audiobox-meta",
    "name": "Audiobox (Meta)",
    "domain": "audiobox.metademolab.com",
    "category": "ai-music-audio",
    "tagline": "Meta's generative AI model for custom audio synthesis and voice prompts",
    "description": "Audiobox generates custom voice clips, sound effects, and musical textures using combined text and voice prompts. It pushes research boundaries in multi-modal generative audio creation.",
    "rating": 4.8,
    "reviewsCount": 380,
    "pricing": "Free",
    "websiteUrl": "https://audiobox.metademolab.com",
    "affiliateUrl": "https://audiobox.metademolab.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "voicefixer",
    "name": "VoiceFixer",
    "domain": "github.com/haoheliu/voicefixer",
    "category": "ai-music-audio",
    "tagline": "Open-source neural network for restoring degraded speech audio",
    "description": "VoiceFixer is an open-source deep learning tool that restores corrupted, clipped, or low-quality speech audio files. It recovers missing frequency bands and suppresses background noise automatically.",
    "rating": 4.6,
    "reviewsCount": 150,
    "pricing": "Free",
    "websiteUrl": "https://github.com/haoheliu/voicefixer",
    "affiliateUrl": "https://github.com/haoheliu/voicefixer",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "110K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "neutone",
    "name": "Neutone",
    "domain": "neutone.space",
    "category": "ai-music-audio",
    "tagline": "Real-time AI audio processing VST plugin for sound designers",
    "description": "Neutone bridges neural network models with traditional digital audio workstations via a custom VST plugin. Sound designers can run real-time generative audio transformation models during production.",
    "rating": 4.7,
    "reviewsCount": 180,
    "pricing": "Free",
    "websiteUrl": "https://neutone.space",
    "affiliateUrl": "https://neutone.space",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "95K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "voicemaker-in",
    "name": "Voicemaker",
    "domain": "voicemaker.in",
    "category": "ai-music-audio",
    "tagline": "Web-based AI text-to-speech converter supporting SSML controls",
    "description": "Voicemaker generates natural voiceover MP3 files from text with detailed SSML tags, pitch, speed, and emphasis adjustments. It is popular for commercial advertisement voiceovers and YouTube videos.",
    "rating": 4.5,
    "reviewsCount": 420,
    "pricing": "Freemium",
    "websiteUrl": "https://voicemaker.in",
    "affiliateUrl": "https://voicemaker.in",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "cleanvoice-ai",
    "name": "Cleanvoice AI",
    "domain": "cleanvoice.ai",
    "category": "ai-music-audio",
    "tagline": "Automated podcast audio editing tool that removes filler words and mouth sounds",
    "description": "Cleanvoice AI automatically detects and removes stuttering, filler words, hesitation sounds, and dead air from podcast recordings. It saves editors hours of manual audio cutting.",
    "rating": 4.7,
    "reviewsCount": 290,
    "pricing": "Free Trial",
    "websiteUrl": "https://cleanvoice.ai",
    "affiliateUrl": "https://cleanvoice.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "420K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "podcastle",
    "name": "Podcastle",
    "domain": "podcastle.ai",
    "category": "ai-music-audio",
    "tagline": "All-in-one AI audio recording, editing, and voice cloning platform",
    "description": "Podcastle provides studio-quality remote multi-track recording, automated voice cloning, and AI speech enhancement. It serves podcasters, educators, and storytellers seeking simplified audio creation.",
    "rating": 4.8,
    "reviewsCount": 670,
    "pricing": "Freemium",
    "websiteUrl": "https://podcastle.ai",
    "affiliateUrl": "https://podcastle.ai",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "2.7M",
    "isFreeTier": true,
    "isOpenSource": false
  }
];

const saasDataPath = path.join(__dirname, '..', 'src', 'data', 'saasData.jsx');
let content = fs.readFileSync(saasDataPath, 'utf8');

const match = content.match(/export const staticSaasTools = (\[[\s\S]*?\n\]);/);
if (!match) {
  console.error('Could not find staticSaasTools in saasData.jsx');
  process.exit(1);
}

let existingTools = JSON.parse(match[1]);

const existingIds = new Set(existingTools.map(t => t.id));
let addedCount = 0;

newTools.forEach(tool => {
  if (!existingIds.has(tool.id)) {
    existingTools.push(tool);
    existingIds.add(tool.id);
    addedCount++;
  } else {
    // Update existing tool with richer data
    const idx = existingTools.findIndex(t => t.id === tool.id);
    if (idx !== -1) {
      existingTools[idx] = { ...existingTools[idx], ...tool };
    }
  }
});

const updatedArrayStr = JSON.stringify(existingTools, null, 2);
content = content.replace(/export const staticSaasTools = \[[\s\S]*?\n\];/, `export const staticSaasTools = ${updatedArrayStr};`);

fs.writeFileSync(saasDataPath, content, 'utf8');
console.log(`Successfully ingested ${addedCount} new AI Music & Audio tools. Total static tools: ${existingTools.length}`);
