const fs = require('fs');
const path = require('path');

const newTools = [
  {
    "id": "nextcloud",
    "name": "Nextcloud",
    "domain": "nextcloud.com",
    "category": "open-source-self-hosted",
    "tagline": "The self-hosted productivity platform and open-source Google Workspace alternative",
    "description": "Nextcloud provides encrypted file storage, calendar scheduling, contacts sync, and collaborative office suite capabilities on private servers. It serves privacy-minded individuals, educational institutions, and enterprise organizations.",
    "rating": 4.8,
    "reviewsCount": 3800,
    "pricing": "Free",
    "websiteUrl": "https://nextcloud.com",
    "affiliateUrl": "https://nextcloud.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "12.5M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "vaultwarden",
    "name": "Vaultwarden",
    "domain": "github.com/dani-garcia/vaultwarden",
    "category": "open-source-self-hosted",
    "tagline": "Lightweight open-source Bitwarden server implementation written in Rust",
    "description": "Vaultwarden delivers full Bitwarden API compatibility and encrypted vault features while running efficiently on low-resource hardware like Raspberry Pis. It is built for self-hosters and home lab administrators seeking low-overhead password security.",
    "rating": 4.9,
    "reviewsCount": 2400,
    "pricing": "Free",
    "websiteUrl": "https://github.com/dani-garcia/vaultwarden",
    "affiliateUrl": "https://github.com/dani-garcia/vaultwarden",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "3.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "immich",
    "name": "Immich",
    "domain": "immich.app",
    "category": "open-source-self-hosted",
    "tagline": "High-performance self-hosted photo and video backup solution and Google Photos alternative",
    "description": "Immich delivers seamless mobile photo auto-backup, facial recognition, partner sharing, and geo-map search on personal servers. It is tailored for privacy-conscious families, photography enthusiasts, and home lab builders.",
    "rating": 4.9,
    "reviewsCount": 2100,
    "pricing": "Free",
    "websiteUrl": "https://immich.app",
    "affiliateUrl": "https://immich.app",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "2.9M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "coolify",
    "name": "Coolify",
    "domain": "coolify.io",
    "category": "open-source-self-hosted",
    "tagline": "An open-source, self-hosted Heroku and Netlify alternative for your servers",
    "description": "Coolify converts bare-metal Linux servers and Virtual Private Servers into an automated application deployment platform. It is engineered for indie developers, software engineers, and privacy-first startups.",
    "rating": 4.9,
    "reviewsCount": 1420,
    "pricing": "Free",
    "websiteUrl": "https://coolify.io",
    "affiliateUrl": "https://coolify.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "jellyfin",
    "name": "Jellyfin",
    "domain": "jellyfin.org",
    "category": "open-source-self-hosted",
    "tagline": "The free software media system for organizing, managing, and streaming personal media",
    "description": "Jellyfin streams personal movies, TV shows, music, and live TV to any client device with zero tracking, paywalls, or central servers. It is built for home media enthusiasts and open-source advocates.",
    "rating": 4.9,
    "reviewsCount": 3100,
    "pricing": "Free",
    "websiteUrl": "https://jellyfin.org",
    "affiliateUrl": "https://jellyfin.org",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "4.5M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "paperless-ngx",
    "name": "Paperless-ngx",
    "domain": "docs.paperless-ngx.com",
    "category": "open-source-self-hosted",
    "tagline": "Community-supported open-source document management system for paperless homes",
    "description": "Paperless-ngx scans, indexes, and performs OCR text extraction on physical documents to build a searchable digital archive. It serves digital archivists, small business operators, and home office managers.",
    "rating": 4.9,
    "reviewsCount": 1850,
    "pricing": "Free",
    "websiteUrl": "https://docs.paperless-ngx.com",
    "affiliateUrl": "https://docs.paperless-ngx.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "n8n",
    "name": "n8n",
    "domain": "n8n.io",
    "category": "open-source-self-hosted",
    "tagline": "Fair-code workflow automation platform and open-source Zapier alternative",
    "description": "n8n enables users to build multi-step workflow automations connecting hundreds of web services and internal APIs visually. It is tailored for developers, IT managers, and privacy-conscious agencies.",
    "rating": 4.8,
    "reviewsCount": 1650,
    "pricing": "Freemium",
    "websiteUrl": "https://n8n.io",
    "affiliateUrl": "https://n8n.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "3.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "appflowy",
    "name": "AppFlowy",
    "domain": "appflowy.io",
    "category": "open-source-self-hosted",
    "tagline": "An open-source Notion alternative giving users total data control and privacy",
    "description": "AppFlowy offers customizable document editing, task boards, and relational tables built with Flutter and Rust for high performance. It serves knowledge workers, researchers, and privacy-first teams.",
    "rating": 4.8,
    "reviewsCount": 920,
    "pricing": "Free",
    "websiteUrl": "https://appflowy.io",
    "affiliateUrl": "https://appflowy.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "nocodb",
    "name": "NocoDB",
    "domain": "nocodb.com",
    "category": "open-source-self-hosted",
    "tagline": "Open-source no-code database infrastructure converting SQL databases into Airtable interfaces",
    "description": "NocoDB turns PostgreSQL, MySQL, and SQLite databases into collaborative smart spreadsheets with REST/GraphQL APIs and automation webhooks. It is built for software developers, data teams, and operations managers.",
    "rating": 4.9,
    "reviewsCount": 1150,
    "pricing": "Freemium",
    "websiteUrl": "https://nocodb.com",
    "affiliateUrl": "https://nocodb.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.6M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "gitea",
    "name": "Gitea",
    "domain": "about.gitea.com",
    "category": "open-source-self-hosted",
    "tagline": "Painless, lightweight self-hosted Git service and GitHub alternative",
    "description": "Gitea delivers code hosting, pull request reviews, issue tracking, and CI/CD runner support with minimal system CPU memory consumption. It is engineered for solo developers, remote software teams, and home labs.",
    "rating": 4.7,
    "reviewsCount": 1450,
    "pricing": "Free",
    "websiteUrl": "https://about.gitea.com",
    "affiliateUrl": "https://about.gitea.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "plausible-analytics",
    "name": "Plausible Analytics",
    "domain": "plausible.io",
    "category": "open-source-self-hosted",
    "tagline": "Lightweight, privacy-first, open-source web analytics alternative to Google Analytics",
    "description": "Plausible provides cookie-free, GDPR-compliant site traffic reporting with a lightweight tracking script under 1KB. It serves ethical business owners, bloggers, and privacy-conscious webmasters.",
    "rating": 4.9,
    "reviewsCount": 850,
    "pricing": "Freemium",
    "websiteUrl": "https://plausible.io",
    "affiliateUrl": "https://plausible.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "umami",
    "name": "Umami",
    "domain": "umami.is",
    "category": "open-source-self-hosted",
    "tagline": "Simple, fast, privacy-focused open-source web analytics platform",
    "description": "Umami tracks pageviews, referrer sources, device specs, and custom event goals without collecting personal data or using tracking cookies. It is designed for web developers and privacy-focused site owners.",
    "rating": 4.9,
    "reviewsCount": 680,
    "pricing": "Freemium",
    "websiteUrl": "https://umami.is",
    "affiliateUrl": "https://umami.is",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "950K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "home-assistant",
    "name": "Home Assistant",
    "domain": "home-assistant.io",
    "category": "open-source-self-hosted",
    "tagline": "Open-source home automation prioritizing local control and privacy",
    "description": "Home Assistant integrates thousands of smart devices locally across Zigbee, Z-Wave, Matter, and Wi-Fi networks without cloud dependencies. It is built for smart home enthusiasts and IoT privacy advocates.",
    "rating": 4.9,
    "reviewsCount": 5200,
    "pricing": "Free",
    "websiteUrl": "https://home-assistant.io",
    "affiliateUrl": "https://home-assistant.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "8.9M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "ollama",
    "name": "Ollama",
    "domain": "ollama.com",
    "category": "open-source-self-hosted",
    "tagline": "Get up and running with large language models locally on your hardware",
    "description": "Ollama bundles open-source LLMs like Llama, Mistral, and Gemma into local executable runtimes with OpenAI-compatible REST APIs. It is engineered for software developers, AI researchers, and privacy advocates.",
    "rating": 4.9,
    "reviewsCount": 3100,
    "pricing": "Free",
    "websiteUrl": "https://ollama.com",
    "affiliateUrl": "https://ollama.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "6.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "open-webui",
    "name": "Open WebUI",
    "domain": "openwebui.com",
    "category": "open-source-self-hosted",
    "tagline": "User-friendly, self-hosted AI interface for Ollama and OpenAI-compatible APIs",
    "description": "Open WebUI provides a ChatGPT-like web dashboard equipped with RAG document uploading, model switching, multi-user access, and web search integration. It serves local AI enthusiasts and privacy-focused teams.",
    "rating": 4.9,
    "reviewsCount": 1820,
    "pricing": "Free",
    "websiteUrl": "https://openwebui.com",
    "affiliateUrl": "https://openwebui.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "3.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "outline-wiki",
    "name": "Outline",
    "domain": "getoutline.com",
    "category": "open-source-self-hosted",
    "tagline": "Fast, real-time collaborative team knowledge base and open-source Confluence alternative",
    "description": "Outline provides Markdown editing, team permissions, document search, and real-time collaboration with clean modern typography. It is built for growing companies, software teams, and remote workforces.",
    "rating": 4.8,
    "reviewsCount": 780,
    "pricing": "Freemium",
    "websiteUrl": "https://getoutline.com",
    "affiliateUrl": "https://getoutline.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "affine",
    "name": "AFFiNE",
    "domain": "affine.pro",
    "category": "open-source-self-hosted",
    "tagline": "Next-gen open-source knowledge base merging docs, whiteboards, and canvas spaces",
    "description": "AFFiNE unifies block-based text editing, infinite visual whiteboards, and relational database views into a single local-first workspace. It serves creative thinkers, researchers, and project planners.",
    "rating": 4.8,
    "reviewsCount": 650,
    "pricing": "Freemium",
    "websiteUrl": "https://affine.pro",
    "affiliateUrl": "https://affine.pro",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "980K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "syncthing",
    "name": "Syncthing",
    "domain": "syncthing.net",
    "category": "open-source-self-hosted",
    "tagline": "Continuous peer-to-peer encrypted file synchronization tool",
    "description": "Syncthing syncs files directly between computers, smartphones, and servers over local networks and internet connections without central cloud storage. It serves privacy enthusiasts managing personal backups.",
    "rating": 4.9,
    "reviewsCount": 2900,
    "pricing": "Free",
    "websiteUrl": "https://syncthing.net",
    "affiliateUrl": "https://syncthing.net",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "docmost",
    "name": "Docmost",
    "domain": "docmost.com",
    "category": "open-source-self-hosted",
    "tagline": "Open-source collaborative wiki and documentation software for teams",
    "description": "Docmost provides real-time multi-user document editing, space hierarchy organization, page permissions, and diagramming tools. It is engineered for technical teams and corporate knowledge bases.",
    "rating": 4.9,
    "reviewsCount": 420,
    "pricing": "Free",
    "websiteUrl": "https://docmost.com",
    "affiliateUrl": "https://docmost.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "bookstack",
    "name": "BookStack",
    "domain": "bookstackapp.com",
    "category": "open-source-self-hosted",
    "tagline": "Simple, self-hosted platform for organizing and storing information in book structures",
    "description": "BookStack structures documentation logically into Shelves, Books, Chapters, and Pages with visual WYSIWYG or Markdown editors. It is built for IT documentation, company SOPs, and user manuals.",
    "rating": 4.8,
    "reviewsCount": 1100,
    "pricing": "Free",
    "websiteUrl": "https://bookstackapp.com",
    "affiliateUrl": "https://bookstackapp.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "wiki-js",
    "name": "Wiki.js",
    "domain": "js.wiki",
    "category": "open-source-self-hosted",
    "tagline": "Powerful, modern open-source wiki software running on Node.js",
    "description": "Wiki.js provides modular authentication, Git backend synchronization, built-in search, and customizable editor modes. It serves corporate IT departments, open-source communities, and developers.",
    "rating": 4.7,
    "reviewsCount": 1250,
    "pricing": "Free",
    "websiteUrl": "https://js.wiki",
    "affiliateUrl": "https://js.wiki",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.5M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "ghost",
    "name": "Ghost",
    "domain": "ghost.org",
    "category": "open-source-self-hosted",
    "tagline": "Independent open-source publishing platform for blogs, newsletters, and memberships",
    "description": "Ghost provides professional publishing tools, email newsletter distribution, and paid subscription paywalls without platform transaction cuts. It is designed for independent writers, journalists, and media publishers.",
    "rating": 4.8,
    "reviewsCount": 2400,
    "pricing": "Freemium",
    "websiteUrl": "https://ghost.org",
    "affiliateUrl": "https://ghost.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "strapi",
    "name": "Strapi",
    "domain": "strapi.io",
    "category": "open-source-self-hosted",
    "tagline": "Leading open-source headless CMS built with Node.js and TypeScript",
    "description": "Strapi enables developers to build custom content structures and consume them via auto-generated REST or GraphQL APIs. It serves software developers, frontend leads, and digital product teams.",
    "rating": 4.7,
    "reviewsCount": 1950,
    "pricing": "Freemium",
    "websiteUrl": "https://strapi.io",
    "affiliateUrl": "https://strapi.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "directus",
    "name": "Directus",
    "domain": "directus.io",
    "category": "open-source-self-hosted",
    "tagline": "Open-source data platform connecting SQL databases with instant APIs and admin apps",
    "description": "Directus layers an intuitive admin dashboard and dynamic REST/GraphQL APIs directly over existing relational databases. It serves backend software engineers, database admins, and app developers.",
    "rating": 4.8,
    "reviewsCount": 890,
    "pricing": "Freemium",
    "websiteUrl": "https://directus.io",
    "affiliateUrl": "https://directus.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "minio",
    "name": "MinIO",
    "domain": "min.io",
    "category": "open-source-self-hosted",
    "tagline": "High-performance Kubernetes-native open-source object storage compatible with Amazon S3",
    "description": "MinIO delivers enterprise-grade S3-compatible cloud object storage for structured and unstructured data workloads. It is engineered for cloud infrastructure architects, DevOps leads, and enterprise IT teams.",
    "rating": 4.8,
    "reviewsCount": 1650,
    "pricing": "Freemium",
    "websiteUrl": "https://min.io",
    "affiliateUrl": "https://min.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "metabase",
    "name": "Metabase",
    "domain": "metabase.com",
    "category": "open-source-self-hosted",
    "tagline": "The easy, open-source way to visualize data and build company dashboards",
    "description": "Metabase allows non-technical team members to query databases visually and generate interactive BI charts without complex SQL. It serves startups, product managers, and data analysts.",
    "rating": 4.7,
    "reviewsCount": 1100,
    "pricing": "Freemium",
    "websiteUrl": "https://metabase.com",
    "affiliateUrl": "https://metabase.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "apache-superset",
    "name": "Apache Superset",
    "domain": "superset.apache.org",
    "category": "open-source-self-hosted",
    "tagline": "Modern enterprise open-source data exploration and visualization platform",
    "description": "Apache Superset provides an open-source, highly scalable data exploration workspace equipped with a rich SQL editor and visual chart options. It serves data engineers and open-source infrastructure teams.",
    "rating": 4.7,
    "reviewsCount": 810,
    "pricing": "Free",
    "websiteUrl": "https://superset.apache.org",
    "affiliateUrl": "https://superset.apache.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "690K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "posthog",
    "name": "PostHog",
    "domain": "posthog.com",
    "category": "open-source-self-hosted",
    "tagline": "The open-source product OS for analytics, session replays, and feature flags",
    "description": "PostHog combines product analytics, session recording, A/B testing, and feature flags into a single developer platform. It is engineered for software engineers, product managers, and open-source teams.",
    "rating": 4.8,
    "reviewsCount": 920,
    "pricing": "Freemium",
    "websiteUrl": "https://posthog.com",
    "affiliateUrl": "https://posthog.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "matomo",
    "name": "Matomo",
    "domain": "matomo.org",
    "category": "open-source-self-hosted",
    "tagline": "Powerful Google Analytics alternative that gives you full data ownership",
    "description": "Matomo delivers a complete web analytics suite that can be self-hosted on your own servers or run in the cloud. It is designed for government agencies, enterprises, and web teams requiring full data privacy control.",
    "rating": 4.7,
    "reviewsCount": 1150,
    "pricing": "Freemium",
    "websiteUrl": "https://matomo.org",
    "affiliateUrl": "https://matomo.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "linkwarden",
    "name": "Linkwarden",
    "domain": "linkwarden.app",
    "category": "open-source-self-hosted",
    "tagline": "Self-hosted collaborative bookmark manager to collect, annotate, and preserve web links",
    "description": "Linkwarden saves web links, captures webpage screenshot archives, and generates PDF copies to protect against broken web links. It is designed for researchers, content collectors, and home lab teams.",
    "rating": 4.9,
    "reviewsCount": 540,
    "pricing": "Freemium",
    "websiteUrl": "https://linkwarden.app",
    "affiliateUrl": "https://linkwarden.app",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "linkding",
    "name": "linkding",
    "domain": "github.com/sissbruecker/linkding",
    "category": "open-source-self-hosted",
    "tagline": "Minimal bookmark management tool designed for speed and low resource usage",
    "description": "linkding provides lightweight bookmark saving, tagging, auto-archiving to Internet Archive, and browser extension integrations. It serves self-hosters running lightweight apps on Raspberry Pi hardware.",
    "rating": 4.8,
    "reviewsCount": 420,
    "pricing": "Free",
    "websiteUrl": "https://github.com/sissbruecker/linkding",
    "affiliateUrl": "https://github.com/sissbruecker/linkding",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "mealie",
    "name": "Mealie",
    "domain": "mealie.io",
    "category": "open-source-self-hosted",
    "tagline": "Self-hosted recipe manager and meal planner with automated web scraping",
    "description": "Mealie extracts recipe details automatically from websites, manages household grocery lists, and schedules weekly meal plans. It is built for home cooks, meal planners, and family households.",
    "rating": 4.9,
    "reviewsCount": 680,
    "pricing": "Free",
    "websiteUrl": "https://mealie.io",
    "affiliateUrl": "https://mealie.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "820K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "hoarder-karakeep",
    "name": "Karakeep (formerly Hoarder)",
    "domain": "github.com/hoarder-app/hoarder",
    "category": "open-source-self-hosted",
    "tagline": "AI-powered bookmarking and content archive app for data collectors",
    "description": "Karakeep automatically archives web pages, uses local AI models for auto-tagging, and performs OCR text extraction on saved screenshots. It serves digital hoarders, researchers, and self-hosters.",
    "rating": 4.9,
    "reviewsCount": 380,
    "pricing": "Free",
    "websiteUrl": "https://github.com/hoarder-app/hoarder",
    "affiliateUrl": "https://github.com/hoarder-app/hoarder",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "510K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "change-detection",
    "name": "changedetection.io",
    "domain": "changedetection.io",
    "category": "open-source-self-hosted",
    "tagline": "Open-source web page change monitoring and notification service",
    "description": "changedetection.io tracks text updates, price adjustments, and PDF changes on target web pages, alerting users via Slack, Discord, or email. It serves price trackers, researchers, and developers.",
    "rating": 4.8,
    "reviewsCount": 510,
    "pricing": "Freemium",
    "websiteUrl": "https://changedetection.io",
    "affiliateUrl": "https://changedetection.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "750K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "uptime-kuma",
    "name": "Uptime Kuma",
    "domain": "uptime.kuma.pet",
    "category": "open-source-self-hosted",
    "tagline": "Fancy, self-hosted monitoring tool for HTTP, TCP, and ping uptime status",
    "description": "Uptime Kuma monitors server responsiveness, tracks SSL certificate expiration, and publishes customizable status pages with instant multi-channel alert notifications. It serves homelab managers and IT admins.",
    "rating": 4.9,
    "reviewsCount": 2100,
    "pricing": "Free",
    "websiteUrl": "https://uptime.kuma.pet",
    "affiliateUrl": "https://uptime.kuma.pet",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "beszel",
    "name": "Beszel",
    "domain": "beszel.dev",
    "category": "open-source-self-hosted",
    "tagline": "Lightweight self-hosted server monitoring hub with Docker stats and alert notifications",
    "description": "Beszel tracks CPU, memory, network I/O, disk usage, and container metrics across servers with a minimal memory footprint. It is engineered for homelab enthusiasts, sysadmins, and VPS operators.",
    "rating": 4.9,
    "reviewsCount": 290,
    "pricing": "Free",
    "websiteUrl": "https://beszel.dev",
    "affiliateUrl": "https://beszel.dev",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "380K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "portainer",
    "name": "Portainer",
    "domain": "portainer.io",
    "category": "open-source-self-hosted",
    "tagline": "Lightweight management UI for Docker, Swarm, and Kubernetes environments",
    "description": "Portainer simplifies container management with an intuitive graphical dashboard for deploying and monitoring Docker containers. It is tailored for home lab managers, developers, and DevOps teams.",
    "rating": 4.8,
    "reviewsCount": 1250,
    "pricing": "Freemium",
    "websiteUrl": "https://portainer.io",
    "affiliateUrl": "https://portainer.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "netdata",
    "name": "Netdata",
    "domain": "netdata.cloud",
    "category": "open-source-self-hosted",
    "tagline": "Real-time infrastructure monitoring and troubleshooting engine for servers and containers",
    "description": "Netdata captures high-resolution system performance metrics per second across CPU, RAM, disk, and network interfaces. It is built for DevOps engineers, sysadmins, and homelab managers.",
    "rating": 4.8,
    "reviewsCount": 1100,
    "pricing": "Freemium",
    "websiteUrl": "https://netdata.cloud",
    "affiliateUrl": "https://netdata.cloud",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "authentik",
    "name": "authentik",
    "domain": "goauthentik.io",
    "category": "open-source-self-hosted",
    "tagline": "Open-source Identity Provider focused on flexibility and versatile SSO integration",
    "description": "authentik provides single sign-on (SSO), OAuth2, SAML, and WebAuthn multi-factor authentication across self-hosted web applications. It serves homelab sysadmins and enterprise security leads.",
    "rating": 4.9,
    "reviewsCount": 620,
    "pricing": "Free",
    "websiteUrl": "https://goauthentik.io",
    "affiliateUrl": "https://goauthentik.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "850K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "authelia",
    "name": "Authelia",
    "domain": "authelia.com",
    "category": "open-source-self-hosted",
    "tagline": "Open-source authentication and authorization server providing 2FA security",
    "description": "Authelia acts as a reverse proxy authentication portal adding two-factor authentication and single sign-on protection to web services. It is designed for self-hosters securing internal server endpoints.",
    "rating": 4.8,
    "reviewsCount": 540,
    "pricing": "Free",
    "websiteUrl": "https://authelia.com",
    "affiliateUrl": "https://authelia.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "keycloak",
    "name": "Keycloak",
    "domain": "keycloak.org",
    "category": "open-source-self-hosted",
    "tagline": "Open-source identity and access management system for modern web apps",
    "description": "Keycloak adds single sign-on, identity brokering, and user management capabilities with OpenID Connect support. It is designed for enterprise software architects requiring self-hosted IAM.",
    "rating": 4.7,
    "reviewsCount": 980,
    "pricing": "Free",
    "websiteUrl": "https://keycloak.org",
    "affiliateUrl": "https://keycloak.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.5M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "pi-hole",
    "name": "Pi-hole",
    "domain": "pi-hole.net",
    "category": "open-source-self-hosted",
    "tagline": "Network-wide sinkhole for blocking ads and trackers without client software",
    "description": "Pi-hole acts as a local DNS server that filters out advertising and tracking domains for all devices connected to a home network. It is an essential self-hosted security tool for home labs.",
    "rating": 4.9,
    "reviewsCount": 3800,
    "pricing": "Free",
    "websiteUrl": "https://pi-hole.net",
    "affiliateUrl": "https://pi-hole.net",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "3.5M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "adguard-home",
    "name": "AdGuard Home",
    "domain": "adguard.com/adguard-home.html",
    "category": "open-source-self-hosted",
    "tagline": "Network-wide software for blocking ads, tracking, and managing network DNS",
    "description": "AdGuard Home routes network DNS requests locally to block ads, enforce parental controls, and encrypt DNS over HTTPS/TLS. It serves home network administrators and self-hosted security builds.",
    "rating": 4.9,
    "reviewsCount": 1950,
    "pricing": "Free",
    "websiteUrl": "https://adguard.com/adguard-home.html",
    "affiliateUrl": "https://adguard.com/adguard-home.html",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "freshrss",
    "name": "FreshRSS",
    "domain": "freshrss.org",
    "category": "open-source-self-hosted",
    "tagline": "Free, self-hostable RSS aggregator and web feed reader",
    "description": "FreshRSS aggregates web feeds, podcasts, and YouTube channels with fast filtering, OPML exports, and mobile app API support. It is built for news junkies and information collectors.",
    "rating": 4.8,
    "reviewsCount": 620,
    "pricing": "Free",
    "websiteUrl": "https://freshrss.org",
    "affiliateUrl": "https://freshrss.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "780K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "wallabag",
    "name": "wallabag",
    "domain": "wallabag.org",
    "category": "open-source-self-hosted",
    "tagline": "Self-hostable application for saving web pages and reading them offline",
    "description": "wallabag extracts text content from articles to build a distraction-free, offline-readable library alternative to Pocket or Instapaper. It is built for avid readers and web article collectors.",
    "rating": 4.7,
    "reviewsCount": 480,
    "pricing": "Freemium",
    "websiteUrl": "https://wallabag.org",
    "affiliateUrl": "https://wallabag.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "520K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "mattermost",
    "name": "Mattermost",
    "domain": "mattermost.com",
    "category": "open-source-self-hosted",
    "tagline": "Open-source, self-hostable secure team messaging and developer collaboration platform",
    "description": "Mattermost provides encrypted channel-based chat, audio calls, and incident management with full self-hosted data ownership. It is engineered for technical DevOps, defense, and security-sensitive organizations.",
    "rating": 4.6,
    "reviewsCount": 920,
    "pricing": "Freemium",
    "websiteUrl": "https://mattermost.com",
    "affiliateUrl": "https://mattermost.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "chatwoot",
    "name": "Chatwoot",
    "domain": "chatwoot.com",
    "category": "open-source-self-hosted",
    "tagline": "Open-source customer engagement platform and privacy-first omnichannel inbox",
    "description": "Chatwoot offers a self-hostable customer communication workspace unifying website live chat, WhatsApp, email, and social messaging. It is built for privacy-focused teams and software developers.",
    "rating": 4.7,
    "reviewsCount": 480,
    "pricing": "Freemium",
    "websiteUrl": "https://chatwoot.com",
    "affiliateUrl": "https://chatwoot.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "380K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "freescout",
    "name": "FreeScout",
    "domain": "freescout.net",
    "category": "open-source-self-hosted",
    "tagline": "Open-source self-hosted help desk and shared email inbox software",
    "description": "FreeScout is a lightweight, self-hosted PHP alternative to Help Scout and Zendesk, giving companies 100% privacy control over support data. It serves developers and privacy-first organizations.",
    "rating": 4.8,
    "reviewsCount": 380,
    "pricing": "Free",
    "websiteUrl": "https://freescout.net",
    "affiliateUrl": "https://freescout.net",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "240K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "homepage-gethomepage",
    "name": "Homepage",
    "domain": "gethomepage.dev",
    "category": "open-source-self-hosted",
    "tagline": "Modern, highly customizable application dashboard for homelabs and self-hosted services",
    "description": "Homepage aggregates links, live service status widgets, Docker metrics, and search engines into a clean dashboard interface. It is engineered for homelab enthusiasts organizing self-hosted infrastructure.",
    "rating": 4.9,
    "reviewsCount": 850,
    "pricing": "Free",
    "websiteUrl": "https://gethomepage.dev",
    "affiliateUrl": "https://gethomepage.dev",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "trilium-notes",
    "name": "Trilium Notes",
    "domain": "github.com/zadam/trilium",
    "category": "open-source-self-hosted",
    "tagline": "Hierarchical note-taking application focused on building large personal knowledge bases",
    "description": "Trilium Notes manages structured personal knowledge trees, mind maps, encrypted notes, and auto-versioning without cloud lock-in. It is tailored for researchers, programmers, and heavy note-takers.",
    "rating": 4.8,
    "reviewsCount": 720,
    "pricing": "Free",
    "websiteUrl": "https://github.com/zadam/trilium",
    "affiliateUrl": "https://github.com/zadam/trilium",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "650K",
    "isFreeTier": true,
    "isOpenSource": true
  }
];

const saasDataPath = path.join(__dirname, '..', 'src', 'data', 'saasData.jsx');
let content = fs.readFileSync(saasDataPath, 'utf8');

const match = content.match(/export const staticSaasTools = (\[[\s\S]*?\n\]);/);
if (!match) {
  console.error('Could not find staticSaasTools in saasData.jsx');
  process.exit(1);
}

let existingTools = JSON.parse(match[1]);

const existingIds = new Set(existingTools.map(t => t.id.toLowerCase()));
const existingNames = new Set(existingTools.map(t => t.name.toLowerCase()));

let addedCount = 0;
let skippedCount = 0;

newTools.forEach(tool => {
  const normId = tool.id.toLowerCase();
  const normName = tool.name.toLowerCase();

  if (!existingIds.has(normId) && !existingNames.has(normName)) {
    existingTools.push(tool);
    existingIds.add(normId);
    existingNames.add(normName);
    addedCount++;
  } else {
    // Enrich existing tool without creating a duplicate
    const idx = existingTools.findIndex(t => t.id.toLowerCase() === normId || t.name.toLowerCase() === normName);
    if (idx !== -1) {
      existingTools[idx] = { ...existingTools[idx], category: tool.category, tagline: tool.tagline || existingTools[idx].tagline };
    }
    skippedCount++;
  }
});

const updatedArrayStr = JSON.stringify(existingTools, null, 2);
content = content.replace(/export const staticSaasTools = \[[\s\S]*?\n\];/, `export const staticSaasTools = ${updatedArrayStr};`);

fs.writeFileSync(saasDataPath, content, 'utf8');
console.log(`Ingestion Complete! Added: ${addedCount} brand new tools | Deduplicated: ${skippedCount} existing tools | Total static tools: ${existingTools.length}`);
