const fs = require('fs');
const path = require('path');

const newTools = [
  {
    "id": "quickbooks-online",
    "name": "QuickBooks Online",
    "domain": "quickbooks.intuit.com",
    "category": "finance-accounting",
    "tagline": "Industry-standard cloud accounting and financial management software",
    "description": "QuickBooks Online tracks income, expenses, tax obligations, and financial reports in one centralized platform. It is built for small businesses, accountants, and growing startups looking to streamline bookkeeping.",
    "rating": 4.7,
    "reviewsCount": 4200,
    "pricing": "Paid",
    "websiteUrl": "https://quickbooks.intuit.com",
    "affiliateUrl": "https://quickbooks.intuit.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "18.5M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "xero",
    "name": "Xero",
    "domain": "xero.com",
    "category": "finance-accounting",
    "tagline": "Powerful cloud accounting software for small businesses and bookkeepers",
    "description": "Xero simplifies daily bookkeeping with automated bank reconciliations, invoicing, and expense claims. It serves small business owners, bookkeepers, and accounting practices worldwide.",
    "rating": 4.6,
    "reviewsCount": 2800,
    "pricing": "Paid",
    "websiteUrl": "https://xero.com",
    "affiliateUrl": "https://xero.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "9.5M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "freshbooks",
    "name": "FreshBooks",
    "domain": "freshbooks.com",
    "category": "finance-accounting",
    "tagline": "Invoicing and simple accounting built for service businesses and freelancers",
    "description": "FreshBooks makes it easy to manage client invoicing, time tracking, expense receipts, and basic financial reports. It is built specifically for freelancers, consultants, and service-based small businesses.",
    "rating": 4.5,
    "reviewsCount": 1950,
    "pricing": "Paid",
    "websiteUrl": "https://freshbooks.com",
    "affiliateUrl": "https://freshbooks.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "3.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "wave-accounting",
    "name": "Wave Accounting",
    "domain": "waveapps.com",
    "category": "finance-accounting",
    "tagline": "Free cloud accounting and invoicing software for solopreneurs",
    "description": "Wave provides zero-cost bookkeeping, invoice generation, and expense tracking with no monthly recurring fees. It is ideal for freelancers, sole proprietors, and micro-business owners.",
    "rating": 4.4,
    "reviewsCount": 1420,
    "pricing": "Freemium",
    "websiteUrl": "https://waveapps.com",
    "affiliateUrl": "https://waveapps.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "zoho-books",
    "name": "Zoho Books",
    "domain": "zoho.com/books",
    "category": "finance-accounting",
    "tagline": "Smart, end-to-end cloud accounting platform for growing businesses",
    "description": "Zoho Books automates accounting workflows, inventory tracking, VAT/sales tax compliance, and client portals. It is tailored for growing small and mid-sized businesses seeking an affordable financial engine.",
    "rating": 4.6,
    "reviewsCount": 1250,
    "pricing": "Freemium",
    "websiteUrl": "https://zoho.com/books",
    "affiliateUrl": "https://zoho.com/books",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "5.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "oracle-netsuite",
    "name": "Oracle NetSuite ERP",
    "domain": "netsuite.com",
    "category": "finance-accounting",
    "tagline": "Comprehensive enterprise ERP for global accounting and multi-entity finance",
    "description": "NetSuite consolidates enterprise general ledgers, revenue recognition, inventory, and global tax compliance into one cloud platform. It is engineered for mid-market and enterprise organizations.",
    "rating": 4.4,
    "reviewsCount": 2400,
    "pricing": "Paid",
    "websiteUrl": "https://netsuite.com",
    "affiliateUrl": "https://netsuite.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "7.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "sage-intacct",
    "name": "Sage Intacct",
    "domain": "sage.com",
    "category": "finance-accounting",
    "tagline": "Cloud financial management software designed for CFOs and finance leaders",
    "description": "Sage Intacct delivers advanced multi-entity consolidation, accounts payable automation, and dimensional general ledger reporting. It serves mid-sized companies and growing corporate finance divisions.",
    "rating": 4.5,
    "reviewsCount": 1150,
    "pricing": "Paid",
    "websiteUrl": "https://sage.com",
    "affiliateUrl": "https://sage.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "expensify",
    "name": "Expensify",
    "domain": "expensify.com",
    "category": "finance-accounting",
    "tagline": "Automated receipt scanning, corporate card management, and expense tracking",
    "description": "Expensify uses SmartScan technology to capture receipts, automate expense approvals, and sync reimbursements with accounting software. It is designed for employees, managers, and finance admins.",
    "rating": 4.5,
    "reviewsCount": 1650,
    "pricing": "Freemium",
    "websiteUrl": "https://expensify.com",
    "affiliateUrl": "https://expensify.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "2.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "ramp-spend",
    "name": "Ramp",
    "domain": "ramp.com",
    "category": "finance-accounting",
    "tagline": "Corporate cards, automated expense management, and vendor bill pay",
    "description": "Ramp unifies corporate cards, automated receipt matching, travel management, and accounts payable into one platform. It is built for modern finance teams seeking real-time spend control.",
    "rating": 4.8,
    "reviewsCount": 1100,
    "pricing": "Free",
    "websiteUrl": "https://ramp.com",
    "affiliateUrl": "https://ramp.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "3.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "brex-finance",
    "name": "Brex",
    "domain": "brex.com",
    "category": "finance-accounting",
    "tagline": "AI corporate cards, global expense tracking, and automated spend controls",
    "description": "Brex offers corporate cards paired with real-time spend management, receipt capture, and automated ERP integrations. It is built for scaling tech startups and enterprise organizations.",
    "rating": 4.7,
    "reviewsCount": 920,
    "pricing": "Freemium",
    "websiteUrl": "https://brex.com",
    "affiliateUrl": "https://brex.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "sap-concur",
    "name": "SAP Concur",
    "domain": "concur.com",
    "category": "finance-accounting",
    "tagline": "Enterprise travel, expense reporting, and invoice management automation",
    "description": "SAP Concur automates travel booking, employee expense submissions, and vendor invoice processing across global enterprises. It serves corporate compliance teams and enterprise CFOs.",
    "rating": 4.3,
    "reviewsCount": 3800,
    "pricing": "Free Trial",
    "websiteUrl": "https://concur.com",
    "affiliateUrl": "https://concur.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "12.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "zoho-expense",
    "name": "Zoho Expense",
    "domain": "zoho.com/expense",
    "category": "finance-accounting",
    "tagline": "Automated business expense tracking and corporate travel policy enforcement",
    "description": "Zoho Expense simplifies receipt scanning, multi-stage approval routing, corporate card feeds, and reimbursement processing. It is designed for small-to-enterprise businesses managing employee spending.",
    "rating": 4.6,
    "reviewsCount": 850,
    "pricing": "Freemium",
    "websiteUrl": "https://zoho.com/expense",
    "affiliateUrl": "https://zoho.com/expense",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "avalara",
    "name": "Avalara",
    "domain": "avalara.com",
    "category": "finance-accounting",
    "tagline": "Automated sales tax calculation, VAT compliance, and tax filing software",
    "description": "Avalara calculates sales tax, VAT, and GST in real time across e-commerce checkouts and handles automated tax filing. It serves online retailers, marketplaces, and multi-state businesses.",
    "rating": 4.4,
    "reviewsCount": 1280,
    "pricing": "Paid",
    "websiteUrl": "https://avalara.com",
    "affiliateUrl": "https://avalara.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "dext-prepare",
    "name": "Dext Prepare",
    "domain": "dext.com",
    "category": "finance-accounting",
    "tagline": "OCR document extraction and automated receipt bookkeeping software",
    "description": "Dext Prepare automatically extracts line-item data from paper receipts, invoices, and supplier bills into cloud accounting platforms. It is engineered for accountants, bookkeepers, and small businesses.",
    "rating": 4.7,
    "reviewsCount": 1100,
    "pricing": "Paid",
    "websiteUrl": "https://dext.com",
    "affiliateUrl": "https://dext.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "turbotax-business",
    "name": "TurboTax Business",
    "domain": "turbotax.intuit.com",
    "category": "finance-accounting",
    "tagline": "Guided tax preparation and filing software for small business entities",
    "description": "TurboTax guides business owners through S-Corp, Partnership, C-Corp, and LLC tax return filings with audit defense support. It is built for small business owners and self-employed professionals.",
    "rating": 4.6,
    "reviewsCount": 5100,
    "pricing": "Paid",
    "websiteUrl": "https://turbotax.intuit.com",
    "affiliateUrl": "https://turbotax.intuit.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "24.5M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "freeagent",
    "name": "FreeAgent",
    "domain": "freeagent.com",
    "category": "finance-accounting",
    "tagline": "Online accounting software for freelancers, contractors, and small businesses",
    "description": "FreeAgent manages self-assessment estimates, UK VAT submissions, project invoicing, and bank reconciliation. It is tailored for UK-based sole traders, contractors, and small business owners.",
    "rating": 4.7,
    "reviewsCount": 890,
    "pricing": "Paid",
    "websiteUrl": "https://freeagent.com",
    "affiliateUrl": "https://freeagent.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.3M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "stampli-ap",
    "name": "Stampli",
    "domain": "stampli.com",
    "category": "finance-accounting",
    "tagline": "AI-powered accounts payable automation and invoice processing platform",
    "description": "Stampli streamlines invoice approval workflows, 3-way PO matching, and corporate card management around existing ERP systems. It is designed for corporate AP and finance teams.",
    "rating": 4.8,
    "reviewsCount": 520,
    "pricing": "Paid",
    "websiteUrl": "https://stampli.com",
    "affiliateUrl": "https://stampli.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "a2x-accounting",
    "name": "A2X",
    "domain": "a2xaccounting.com",
    "category": "finance-accounting",
    "tagline": "Automated e-commerce accounting sync for Amazon, Shopify, and eBay",
    "description": "A2X summarizes e-commerce payout data, COGS, and sales tax automatically into QuickBooks and Xero. It is built for e-commerce sellers, Amazon merchants, and specialized accountants.",
    "rating": 4.9,
    "reviewsCount": 380,
    "pricing": "Paid",
    "websiteUrl": "https://a2xaccounting.com",
    "affiliateUrl": "https://a2xaccounting.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "320K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "rydoo",
    "name": "Rydoo",
    "domain": "rydoo.com",
    "category": "finance-accounting",
    "tagline": "Smart expense management software for modern corporate travel and claims",
    "description": "Rydoo digitizes receipt capture, enforces corporate expense policies automatically, and simplifies global employee reimbursements. It serves mid-market and enterprise international organizations.",
    "rating": 4.6,
    "reviewsCount": 340,
    "pricing": "Paid",
    "websiteUrl": "https://rydoo.com",
    "affiliateUrl": "https://rydoo.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "410K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "airbase-spend",
    "name": "Airbase (Paylocity)",
    "domain": "airbase.com",
    "category": "finance-accounting",
    "tagline": "Procure-to-pay spend management platform with AP automation and corporate cards",
    "description": "Airbase combines accounts payable automation, corporate card issuance, and employee expense reimbursements. It is built for mid-market CFOs and finance teams consolidating spending tools.",
    "rating": 4.7,
    "reviewsCount": 420,
    "pricing": "Paid",
    "websiteUrl": "https://airbase.com",
    "affiliateUrl": "https://airbase.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "290K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "taxjar-tax",
    "name": "TaxJar",
    "domain": "taxjar.com",
    "category": "finance-accounting",
    "tagline": "Automated sales tax compliance, nexus tracking, and filing platform",
    "description": "TaxJar automates US sales tax calculation across e-commerce checkouts, tracks economic nexus limits, and handles auto-filing. It serves e-commerce brands and multi-channel merchants.",
    "rating": 4.5,
    "reviewsCount": 680,
    "pricing": "Paid",
    "websiteUrl": "https://taxjar.com",
    "affiliateUrl": "https://taxjar.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "950K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "gnucash",
    "name": "GnuCash",
    "domain": "gnucash.org",
    "category": "finance-accounting",
    "tagline": "Free, open-source double-entry personal and small business accounting software",
    "description": "GnuCash provides double-entry accounting, bank account tracking, stock portfolio management, and financial reporting locally. It is designed for open-source advocates and budget-conscious bookkeepers.",
    "rating": 4.5,
    "reviewsCount": 490,
    "pricing": "Free",
    "websiteUrl": "https://gnucash.org",
    "affiliateUrl": "https://gnucash.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "akaunting",
    "name": "Akaunting",
    "domain": "akaunting.com",
    "category": "finance-accounting",
    "tagline": "Free, open-source online accounting software for small businesses and freelancers",
    "description": "Akaunting offers modular cloud bookkeeping, invoice generation, bill tracking, and financial reporting. It provides both self-hosted open-source software and managed cloud plans for small business owners.",
    "rating": 4.6,
    "reviewsCount": 310,
    "pricing": "Freemium",
    "websiteUrl": "https://akaunting.com",
    "affiliateUrl": "https://akaunting.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "380K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "pleo-spend",
    "name": "Pleo",
    "domain": "pleo.io",
    "category": "finance-accounting",
    "tagline": "Smart business cards and automated European expense management platform",
    "description": "Pleo pairs physical and virtual corporate cards with receipt scanning, invoice payments, and accounting system sync. It is engineered for European SMBs automating employee spend.",
    "rating": 4.7,
    "reviewsCount": 650,
    "pricing": "Paid",
    "websiteUrl": "https://pleo.io",
    "affiliateUrl": "https://pleo.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "820K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "payhawk-finance",
    "name": "Payhawk",
    "domain": "payhawk.com",
    "category": "finance-accounting",
    "tagline": "All-in-one corporate cards, spend management, and accounts payable software",
    "description": "Payhawk consolidates credit card issuance, subscription tracking, vendor invoice approvals, and multi-currency ERP sync. It serves international finance departments managing multi-entity spending.",
    "rating": 4.8,
    "reviewsCount": 380,
    "pricing": "Paid",
    "websiteUrl": "https://payhawk.com",
    "affiliateUrl": "https://payhawk.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "390K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "sage-50",
    "name": "Sage 50 Accounting",
    "domain": "sage.com/en-us/products/sage-50-cloud",
    "category": "finance-accounting",
    "tagline": "Desktop business accounting software with cloud connectivity and inventory",
    "description": "Sage 50 combines desktop security with cloud connectivity, advanced inventory management, and audit tracking. It is built for established small-to-midsize product and manufacturing companies.",
    "rating": 4.3,
    "reviewsCount": 1820,
    "pricing": "Paid",
    "websiteUrl": "https://sage.com/en-us/products/sage-50-cloud",
    "affiliateUrl": "https://sage.com/en-us/products/sage-50-cloud",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "divvy-bill-com",
    "name": "BILL Spend & Expense (formerly Divvy)",
    "domain": "bill.com/product/spend-and-expense",
    "category": "finance-accounting",
    "tagline": "Free corporate card and expense management software backed by BILL",
    "description": "BILL Spend & Expense combines credit lines with real-time budget enforcement and automated receipt capture. It serves small to mid-sized business teams looking for free spend management software.",
    "rating": 4.6,
    "reviewsCount": 2100,
    "pricing": "Free",
    "websiteUrl": "https://bill.com/product/spend-and-expense",
    "affiliateUrl": "https://bill.com/product/spend-and-expense",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "6.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "anrok-tax",
    "name": "Anrok",
    "domain": "anrok.com",
    "category": "finance-accounting",
    "tagline": "Global sales tax and VAT compliance engine built specifically for SaaS",
    "description": "Anrok monitors global tax nexus thresholds, calculates real-time SaaS sales taxes, and manages automated tax filings. It is built specifically for SaaS CFOs and finance operations.",
    "rating": 4.9,
    "reviewsCount": 110,
    "pricing": "Paid",
    "websiteUrl": "https://anrok.com",
    "affiliateUrl": "https://anrok.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "110K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "quaderno-accounting",
    "name": "Quaderno",
    "domain": "quaderno.io",
    "category": "finance-accounting",
    "tagline": "Automated sales tax, VAT, and GST calculation and receipt software",
    "description": "Quaderno calculates international digital sales taxes in real time, issues compliant receipts, and generates tax reports. It serves e-commerce merchants, digital creators, and SaaS businesses.",
    "rating": 4.6,
    "reviewsCount": 210,
    "pricing": "Paid",
    "websiteUrl": "https://quaderno.io",
    "affiliateUrl": "https://quaderno.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "160K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "kashflow",
    "name": "KashFlow",
    "domain": "kashflow.com",
    "category": "finance-accounting",
    "tagline": "Straightforward UK cloud accounting and online invoicing software",
    "description": "KashFlow simplifies UK Making Tax Digital (MTD) VAT filing, client invoicing, and expense reporting. It is tailored for UK sole traders, contractors, and small business operators.",
    "rating": 4.2,
    "reviewsCount": 310,
    "pricing": "Paid",
    "websiteUrl": "https://kashflow.com",
    "affiliateUrl": "https://kashflow.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "310K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "accountsiq",
    "name": "AccountsIQ",
    "domain": "accountsiq.com",
    "category": "finance-accounting",
    "tagline": "Cloud accounting software for multi-entity consolidation and medium businesses",
    "description": "AccountsIQ simplifies multi-currency consolidation, automated intercompany transactions, and financial reporting. It is engineered for growth-stage companies, franchises, and multi-entity groups.",
    "rating": 4.6,
    "reviewsCount": 180,
    "pricing": "Paid",
    "websiteUrl": "https://accountsiq.com",
    "affiliateUrl": "https://accountsiq.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "140K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "vic-ai",
    "name": "Vic.ai",
    "domain": "vic.ai",
    "category": "finance-accounting",
    "tagline": "Autonomous AI accounts payable and invoice processing software",
    "description": "Vic.ai uses computer vision and machine learning to ingest, code, and approve high-volume enterprise invoices automatically. It serves enterprise CFOs, accounting practices, and finance leads.",
    "rating": 4.8,
    "reviewsCount": 95,
    "pricing": "Paid",
    "websiteUrl": "https://vic.ai",
    "affiliateUrl": "https://vic.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "90K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "rossum-ap",
    "name": "Rossum",
    "domain": "rossum.ai",
    "category": "finance-accounting",
    "tagline": "AI document processing engine for transactional invoices and POs",
    "description": "Rossum extracts, validates, and routes data automatically from complex, unstructured invoices into enterprise ERPs. It serves global logistics, manufacturing, and enterprise accounting teams.",
    "rating": 4.6,
    "reviewsCount": 160,
    "pricing": "Paid",
    "websiteUrl": "https://rossum.ai",
    "affiliateUrl": "https://rossum.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "210K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "docuclipper",
    "name": "DocuClipper",
    "domain": "docuclipper.com",
    "category": "finance-accounting",
    "tagline": "OCR bank statement converter and automatic invoice data extractor",
    "description": "DocuClipper extracts transaction data accurately from PDF bank statements, receipts, and invoices into Excel or accounting software. It is built for bookkeepers, accountants, and auditors.",
    "rating": 4.7,
    "reviewsCount": 120,
    "pricing": "Paid",
    "websiteUrl": "https://docuclipper.com",
    "affiliateUrl": "https://docuclipper.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "130K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "precoro-ap",
    "name": "Precoro",
    "domain": "precoro.com",
    "category": "finance-accounting",
    "tagline": "Procurement software and automated purchase order management system",
    "description": "Precoro eliminates manual purchase ordering, speeds up 3-way invoice matching, and enforces corporate purchasing budgets. It is designed for mid-sized business operations and procurement teams.",
    "rating": 4.8,
    "reviewsCount": 240,
    "pricing": "Paid",
    "websiteUrl": "https://precoro.com",
    "affiliateUrl": "https://precoro.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "240K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "avidxchange-ap",
    "name": "AvidXchange",
    "domain": "avidxchange.com",
    "category": "finance-accounting",
    "tagline": "Enterprise accounts payable automation and electronic payment software",
    "description": "AvidXchange digitizes paper invoice processing, approval routing, and electronic vendor payments for mid-market finance teams. It serves real estate, construction, and healthcare industries.",
    "rating": 4.3,
    "reviewsCount": 340,
    "pricing": "Paid",
    "websiteUrl": "https://avidxchange.com",
    "affiliateUrl": "https://avidxchange.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "610K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "plooto-payments",
    "name": "Plooto",
    "domain": "plooto.com",
    "category": "finance-accounting",
    "tagline": "Automated B2B payments and accounts payable/receivable software",
    "description": "Plooto automates domestic and international ACH transfers, approval workflows, and two-way accounting sync. It is designed for small to mid-sized businesses streamlining vendor payments.",
    "rating": 4.5,
    "reviewsCount": 220,
    "pricing": "Paid",
    "websiteUrl": "https://plooto.com",
    "affiliateUrl": "https://plooto.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "280K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "saasant-transactions",
    "name": "SaasAnt Transactions",
    "domain": "saasant.com",
    "category": "finance-accounting",
    "tagline": "Bulk transaction import, export, and data automation for QuickBooks",
    "description": "SaasAnt enables accounting teams to bulk import, export, and modify bank files or sales data inside QuickBooks automatically. It serves accountants, bookkeepers, and e-commerce managers.",
    "rating": 4.8,
    "reviewsCount": 290,
    "pricing": "Paid",
    "websiteUrl": "https://saasant.com",
    "affiliateUrl": "https://saasant.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "180K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "refrens-accounting",
    "name": "Refrens",
    "domain": "refrens.com",
    "category": "finance-accounting",
    "tagline": "AI-powered finance, invoicing, inventory, and accounting platform",
    "description": "Refrens centralizes invoicing, GST compliance, expense tracking, and vendor management on a unified ledger. It is built for freelancers, agencies, and small businesses in emerging markets.",
    "rating": 4.9,
    "reviewsCount": 260,
    "pricing": "Freemium",
    "websiteUrl": "https://refrens.com",
    "affiliateUrl": "https://refrens.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "890K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "webexpenses",
    "name": "Webexpenses",
    "domain": "webexpenses.com",
    "category": "finance-accounting",
    "tagline": "Automated employee expense management and receipt scanning software",
    "description": "Webexpenses provides digital tools for receipt tracking, claim submissions, automated approvals, and ERP integration. It serves mid-market and enterprise organizations looking to enforce spend compliance.",
    "rating": 4.4,
    "reviewsCount": 390,
    "pricing": "Paid",
    "websiteUrl": "https://webexpenses.com",
    "affiliateUrl": "https://webexpenses.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "210K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "bokio-accounting",
    "name": "Bokio",
    "domain": "bokio.co.uk",
    "category": "finance-accounting",
    "tagline": "Smart, automated bookkeeping and VAT filing software for micro-businesses",
    "description": "Bokio automates everyday bookkeeping, bank reconciliations, VAT submissions, and invoice management. It is built specifically for sole traders, small business owners, and freelancers.",
    "rating": 4.5,
    "reviewsCount": 280,
    "pricing": "Freemium",
    "websiteUrl": "https://bokio.co.uk",
    "affiliateUrl": "https://bokio.co.uk",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "320K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "brightpay-payroll",
    "name": "BrightPay",
    "domain": "brightpay.co.uk",
    "category": "finance-accounting",
    "tagline": "Desktop and cloud payroll software for accounting firms and SMBs",
    "description": "BrightPay automates batch payroll processing, auto-enrolment pensions, payslip distribution, and HMRC reporting. It is designed for UK accountants, bookkeepers, and payroll bureaus.",
    "rating": 4.9,
    "reviewsCount": 380,
    "pricing": "Paid",
    "websiteUrl": "https://brightpay.co.uk",
    "affiliateUrl": "https://brightpay.co.uk",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "450K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "silverfin-working-papers",
    "name": "Silverfin",
    "domain": "silverfin.com",
    "category": "finance-accounting",
    "tagline": "Cloud platform for automated working papers and financial compliance",
    "description": "Silverfin standardizes accounting firm compliance, real-time working papers, and client financial reporting. It is engineered for modern accounting firms and advisory practices.",
    "rating": 4.7,
    "reviewsCount": 140,
    "pricing": "Paid",
    "websiteUrl": "https://silverfin.com",
    "affiliateUrl": "https://silverfin.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "180K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "revrec-chargebee",
    "name": "Chargebee RevRec",
    "domain": "chargebee.com/revrec",
    "category": "finance-accounting",
    "tagline": "Automated ASC 606 and IFRS 15 revenue recognition software for SaaS",
    "description": "Chargebee RevRec automates complex deferred revenue schedules, contract modifications, and compliance reporting. It serves SaaS finance leaders and subscription business CFOs.",
    "rating": 4.8,
    "reviewsCount": 120,
    "pricing": "Paid",
    "websiteUrl": "https://chargebee.com/revrec",
    "affiliateUrl": "https://chargebee.com/revrec",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "billomat-accounting",
    "name": "Billomat",
    "domain": "billomat.com",
    "category": "finance-accounting",
    "tagline": "Web-based bookkeeping and invoicing software for European businesses",
    "description": "Billomat automates online invoice creation, dunning workflows, bank feed sync, and expense management. It is built for European freelancers, startups, and small business owners.",
    "rating": 4.4,
    "reviewsCount": 140,
    "pricing": "Paid",
    "websiteUrl": "https://billomat.com",
    "affiliateUrl": "https://billomat.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "180K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "myob-business",
    "name": "MYOB Business",
    "domain": "myob.com",
    "category": "finance-accounting",
    "tagline": "Cloud accounting, payroll, and tax software for ANZ small businesses",
    "description": "MYOB manages Single Touch Payroll, GST tracking, inventory, and automated bank reconciliations. It is built specifically for Australian and New Zealand small businesses and accountants.",
    "rating": 4.2,
    "reviewsCount": 1650,
    "pricing": "Paid",
    "websiteUrl": "https://myob.com",
    "affiliateUrl": "https://myob.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "reckon-one",
    "name": "Reckon One",
    "domain": "reckon.com",
    "category": "finance-accounting",
    "tagline": "Modular cloud accounting and Single Touch Payroll software",
    "description": "Reckon One provides budget-friendly modular bookkeeping, invoicing, expense tracking, and payroll processing. It serves Australian freelancers, contractors, and small business owners.",
    "rating": 4.3,
    "reviewsCount": 420,
    "pricing": "Paid",
    "websiteUrl": "https://reckon.com",
    "affiliateUrl": "https://reckon.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "clear-books",
    "name": "Clear Books",
    "domain": "clearbooks.co.uk",
    "category": "finance-accounting",
    "tagline": "Easy UK small business accounting and Making Tax Digital software",
    "description": "Clear Books handles UK MTD VAT returns, CIS tax calculations, client invoicing, and dividend processing. It is built for UK small businesses, sole traders, and accountants.",
    "rating": 4.5,
    "reviewsCount": 380,
    "pricing": "Free Trial",
    "websiteUrl": "https://clearbooks.co.uk",
    "affiliateUrl": "https://clearbooks.co.uk",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "210K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "bright-manager",
    "name": "Bright Manager (AccountancyManager)",
    "domain": "brightsg.com/en-gb/products/bright-manager",
    "category": "finance-accounting",
    "tagline": "Onboarding, task automation, and practice management for accountants",
    "description": "Bright Manager automates client onboarding, AML checks, task scheduling, and document collection for accounting practices. It is built for UK and Irish accountants and bookkeepers.",
    "rating": 4.8,
    "reviewsCount": 350,
    "pricing": "Free Trial",
    "websiteUrl": "https://brightsg.com/en-gb/products/bright-manager",
    "affiliateUrl": "https://brightsg.com/en-gb/products/bright-manager",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "280K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "inflo-audit",
    "name": "Inflo",
    "domain": "inflosoftware.com",
    "category": "finance-accounting",
    "tagline": "Data analytics, working papers, and automation platform for audit firms",
    "description": "Inflo automates client data extraction, audit sample testing, and quality review workflows. It is engineered specifically for modern CPA and chartered audit practices.",
    "rating": 4.7,
    "reviewsCount": 110,
    "pricing": "Paid",
    "websiteUrl": "https://inflosoftware.com",
    "affiliateUrl": "https://inflosoftware.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "120K",
    "isFreeTier": false,
    "isOpenSource": false
  }
];

const saasDataPath = path.join(__dirname, '..', 'src', 'data', 'saasData.jsx');
let content = fs.readFileSync(saasDataPath, 'utf8');

const match = content.match(/export const staticSaasTools = (\[[\s\S]*?\n\]);/);
if (!match) {
  console.error('Could not find staticSaasTools in saasData.jsx');
  process.exit(1);
}

let existingTools = JSON.parse(match[1]);

const existingIds = new Set(existingTools.map(t => t.id.toLowerCase()));
const existingNames = new Set(existingTools.map(t => t.name.toLowerCase()));

let addedCount = 0;
let skippedCount = 0;

newTools.forEach(tool => {
  const normId = tool.id.toLowerCase();
  const normName = tool.name.toLowerCase();

  if (!existingIds.has(normId) && !existingNames.has(normName)) {
    existingTools.push(tool);
    existingIds.add(normId);
    existingNames.add(normName);
    addedCount++;
  } else {
    // Enrich existing tool without creating a duplicate
    const idx = existingTools.findIndex(t => t.id.toLowerCase() === normId || t.name.toLowerCase() === normName);
    if (idx !== -1) {
      existingTools[idx] = { ...existingTools[idx], category: tool.category, tagline: tool.tagline || existingTools[idx].tagline };
    }
    skippedCount++;
  }
});

const updatedArrayStr = JSON.stringify(existingTools, null, 2);
content = content.replace(/export const staticSaasTools = \[[\s\S]*?\n\];/, `export const staticSaasTools = ${updatedArrayStr};`);

fs.writeFileSync(saasDataPath, content, 'utf8');
console.log(`Ingestion Complete! Added: ${addedCount} brand new tools | Deduplicated: ${skippedCount} existing tools | Total static tools: ${existingTools.length}`);
