const fs = require('fs');
const path = require('path');

const newTools = [
  {
    "id": "shopify",
    "name": "Shopify",
    "domain": "shopify.com",
    "category": "ecommerce-platforms",
    "tagline": "The world's leading omni-channel e-commerce and storefront platform",
    "description": "Shopify enables businesses to build, customize, and scale online stores with integrated payment processing and inventory management. It serves independent entrepreneurs, direct-to-consumer brands, and global retail enterprises.",
    "rating": 4.8,
    "reviewsCount": 8500,
    "pricing": "Free Trial",
    "websiteUrl": "https://shopify.com",
    "affiliateUrl": "https://shopify.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "68.5M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "woocommerce",
    "name": "WooCommerce",
    "domain": "woocommerce.com",
    "category": "ecommerce-platforms",
    "tagline": "The premier open-source e-commerce plugin for WordPress websites",
    "description": "WooCommerce turns WordPress sites into fully functional digital storefronts with complete code customization and extension options. It is engineered for web developers, agencies, and WordPress site owners.",
    "rating": 4.6,
    "reviewsCount": 6200,
    "pricing": "Free",
    "websiteUrl": "https://woocommerce.com",
    "affiliateUrl": "https://woocommerce.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "12.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "bigcommerce",
    "name": "BigCommerce",
    "domain": "bigcommerce.com",
    "category": "ecommerce-platforms",
    "tagline": "Flexible Open SaaS e-commerce platform built for fast-scaling brands and B2B",
    "description": "BigCommerce offers native multi-storefront management, multi-channel marketplace sync, and robust headless APIs without transaction fees. It is built for fast-scaling mid-market businesses, B2B merchants, and enterprise brands.",
    "rating": 4.5,
    "reviewsCount": 2400,
    "pricing": "Free Trial",
    "websiteUrl": "https://bigcommerce.com",
    "affiliateUrl": "https://bigcommerce.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "4.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "wix-ecommerce",
    "name": "Wix Ecommerce",
    "domain": "wix.com/ecommerce/website",
    "category": "ecommerce-platforms",
    "tagline": "Drag-and-drop website builder with integrated online store and retail management",
    "description": "Wix Ecommerce allows merchants to create visually striking storefronts with flexible design tools, secure checkout, and order management. It is tailored for small business owners, boutique creators, and visual brands.",
    "rating": 4.6,
    "reviewsCount": 4800,
    "pricing": "Freemium",
    "websiteUrl": "https://wix.com/ecommerce/website",
    "affiliateUrl": "https://wix.com/ecommerce/website",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "42.0M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "squarespace-commerce",
    "name": "Squarespace Commerce",
    "domain": "squarespace.com/ecommerce-website",
    "category": "ecommerce-platforms",
    "tagline": "Aesthetic storefront builder for creative entrepreneurs, artists, and lifestyle brands",
    "description": "Squarespace Commerce combines high-end website design templates with built-in product catalogs, appointments, and subscription selling. It serves artists, designers, boutique retailers, and content creators.",
    "rating": 4.7,
    "reviewsCount": 3900,
    "pricing": "Free Trial",
    "websiteUrl": "https://squarespace.com/ecommerce-website",
    "affiliateUrl": "https://squarespace.com/ecommerce-website",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "32.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "adobe-commerce",
    "name": "Adobe Commerce (formerly Magento)",
    "domain": "business.adobe.com/products/magento/magento-commerce.html",
    "category": "ecommerce-platforms",
    "tagline": "Enterprise-grade, highly customizable open-source e-commerce platform",
    "description": "Adobe Commerce provides high-performance merchandise catalog management, multi-site architecture, and deep ERP integration capabilities. It is engineered for enterprise B2C and B2B global brands with specialized development resources.",
    "rating": 4.3,
    "reviewsCount": 3100,
    "pricing": "Paid",
    "websiteUrl": "https://business.adobe.com/products/magento/magento-commerce.html",
    "affiliateUrl": "https://business.adobe.com/products/magento/magento-commerce.html",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "18.5M",
    "isFreeTier": false,
    "isOpenSource": true
  },
  {
    "id": "ecwid",
    "name": "Ecwid by Lightspeed",
    "domain": "ecwid.com",
    "category": "ecommerce-platforms",
    "tagline": "Embeddable shopping cart widget for existing websites and social channels",
    "description": "Ecwid allows merchants to instantly add online shopping cart functionality onto existing websites, blogs, or social media pages. It serves small business owners wanting to sell online without rebuilding their site.",
    "rating": 4.7,
    "reviewsCount": 2800,
    "pricing": "Freemium",
    "websiteUrl": "https://ecwid.com",
    "affiliateUrl": "https://ecwid.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "salesforce-commerce-cloud",
    "name": "Salesforce Commerce Cloud",
    "domain": "salesforce.com/products/commerce-cloud/overview",
    "category": "ecommerce-platforms",
    "tagline": "AI-powered enterprise e-commerce platform integrated into Salesforce CRM",
    "description": "Salesforce Commerce Cloud unites online storefronts, order management, and personalized AI shopping experiences with core CRM records. It is engineered for Global 2000 enterprises and enterprise B2B/B2C retailers.",
    "rating": 4.3,
    "reviewsCount": 1850,
    "pricing": "Paid",
    "websiteUrl": "https://salesforce.com/products/commerce-cloud/overview",
    "affiliateUrl": "https://salesforce.com/products/commerce-cloud/overview",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "24.5M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "square-online",
    "name": "Square Online",
    "domain": "squareup.com/online-store",
    "category": "ecommerce-platforms",
    "tagline": "Free online store builder synced directly with Square POS hardware",
    "description": "Square Online creates digital storefronts that sync inventory, sales, and customer records in real time with brick-and-mortar Square POS systems. It is built for local retail shops, restaurants, and hybrid sellers.",
    "rating": 4.6,
    "reviewsCount": 3200,
    "pricing": "Freemium",
    "websiteUrl": "https://squareup.com/online-store",
    "affiliateUrl": "https://squareup.com/online-store",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "14.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "commercetools",
    "name": "commercetools",
    "domain": "commercetools.com",
    "category": "ecommerce-platforms",
    "tagline": "Pioneer in composable, headless MACH e-commerce architecture",
    "description": "commercetools provides a cloud-native, API-first headless commerce engine allowing enterprises to build custom frontend shopping touchpoints. It is designed for enterprise software architects and digital product teams.",
    "rating": 4.7,
    "reviewsCount": 320,
    "pricing": "Paid",
    "websiteUrl": "https://commercetools.com",
    "affiliateUrl": "https://commercetools.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "580K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "medusa-js",
    "name": "Medusa",
    "domain": "medusajs.com",
    "category": "ecommerce-platforms",
    "tagline": "Open-source Node.js headless commerce framework for developers",
    "description": "Medusa offers a developer-first, open-source backend alternative to Shopify with modular building blocks and complete code autonomy. It serves software engineers and technical teams constructing custom commerce apps.",
    "rating": 4.9,
    "reviewsCount": 680,
    "pricing": "Free",
    "websiteUrl": "https://medusajs.com",
    "affiliateUrl": "https://medusajs.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "920K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "elastic-path",
    "name": "Elastic Path",
    "domain": "elasticpath.com",
    "category": "ecommerce-platforms",
    "tagline": "Composable commerce engine for enterprise multi-brand digital experiences",
    "description": "Elastic Path provides microservices-based, headless e-commerce components to orchestrate complex catalogs and checkout experiences. It serves enterprise brands, manufacturers, and multi-channel retailers.",
    "rating": 4.5,
    "reviewsCount": 190,
    "pricing": "Paid",
    "websiteUrl": "https://elasticpath.com",
    "affiliateUrl": "https://elasticpath.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "210K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "prestashop",
    "name": "PrestaShop",
    "domain": "prestashop.com",
    "category": "ecommerce-platforms",
    "tagline": "Customizable open-source e-commerce platform widely used across Europe",
    "description": "PrestaShop provides a self-hosted e-commerce core accompanied by a rich add-on marketplace for themes and regional payment modules. It is popular among European small-to-medium retailers and web developers.",
    "rating": 4.3,
    "reviewsCount": 2100,
    "pricing": "Free",
    "websiteUrl": "https://prestashop.com",
    "affiliateUrl": "https://prestashop.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "opencart",
    "name": "OpenCart",
    "domain": "opencart.com",
    "category": "ecommerce-platforms",
    "tagline": "Free, open-source PHP online store management platform",
    "description": "OpenCart offers a lightweight, self-hosted PHP e-commerce framework with built-in multi-store support and simple admin dashboards. It is tailored for developers and merchants seeking cost-effective self-hosting.",
    "rating": 4.4,
    "reviewsCount": 1650,
    "pricing": "Free",
    "websiteUrl": "https://opencart.com",
    "affiliateUrl": "https://opencart.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.9M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "shift4shop",
    "name": "Shift4Shop",
    "domain": "shift4shop.com",
    "category": "ecommerce-platforms",
    "tagline": "Feature-rich turn-key e-commerce builder with free hosting using Shift4 processing",
    "description": "Shift4Shop provides an all-in-one hosted online store platform with enterprise features included for free when using Shift4 payment processing. It serves US-based online merchants and growing stores.",
    "rating": 4.2,
    "reviewsCount": 1100,
    "pricing": "Freemium",
    "websiteUrl": "https://shift4shop.com",
    "affiliateUrl": "https://shift4shop.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "volusion",
    "name": "Volusion",
    "domain": "volusion.com",
    "category": "ecommerce-platforms",
    "tagline": "Established cloud e-commerce platform for inventory-focused online sellers",
    "description": "Volusion delivers site building tools, integrated merchant processing, stock inventory tracking, and CRM management. It is designed for small and mid-sized product-focused e-commerce businesses.",
    "rating": 4.1,
    "reviewsCount": 1250,
    "pricing": "Free Trial",
    "websiteUrl": "https://volusion.com",
    "affiliateUrl": "https://volusion.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "850K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "gumroad",
    "name": "Gumroad",
    "domain": "gumroad.com",
    "category": "ecommerce-platforms",
    "tagline": "Simple digital product e-commerce storefront for creators and indie makers",
    "description": "Gumroad allows creators, authors, and developers to sell ebooks, software licenses, memberships, and digital assets instantly. It serves solo creators, artists, and digital product sellers.",
    "rating": 4.6,
    "reviewsCount": 2900,
    "pricing": "Freemium",
    "websiteUrl": "https://gumroad.com",
    "affiliateUrl": "https://gumroad.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "18.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "lemon-squeezy",
    "name": "Lemon Squeezy (Stripe)",
    "domain": "lemonsqueezy.com",
    "category": "ecommerce-platforms",
    "tagline": "All-in-one Merchant of Record platform for digital products and SaaS",
    "description": "Lemon Squeezy handles global sales tax compliance, digital product delivery, license key generation, and subscription billing automatically. It is built for SaaS founders, software developers, and digital creators.",
    "rating": 4.8,
    "reviewsCount": 850,
    "pricing": "Paid",
    "websiteUrl": "https://lemonsqueezy.com",
    "affiliateUrl": "https://lemonsqueezy.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "3.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "payhip",
    "name": "Payhip",
    "domain": "payhip.com",
    "category": "ecommerce-platforms",
    "tagline": "Simple e-commerce platform to sell digital downloads, courses, and physical items",
    "description": "Payhip allows creators to embed buy buttons or host custom storefronts to sell digital downloads, online courses, and physical products. It serves independent creators, educators, and authors.",
    "rating": 4.7,
    "reviewsCount": 1100,
    "pricing": "Freemium",
    "websiteUrl": "https://payhip.com",
    "affiliateUrl": "https://payhip.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "sellfy",
    "name": "Sellfy",
    "domain": "sellfy.com",
    "category": "ecommerce-platforms",
    "tagline": "E-commerce platform for digital creators, print-on-demand, and physical merch",
    "description": "Sellfy combines digital product hosting, built-in print-on-demand merch fulfillment, and simple checkout storefronts in minutes. It is built for YouTubers, designers, and social media creators.",
    "rating": 4.6,
    "reviewsCount": 820,
    "pricing": "Free Trial",
    "websiteUrl": "https://sellfy.com",
    "affiliateUrl": "https://sellfy.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "big-cartel",
    "name": "Big Cartel",
    "domain": "bigcartel.com",
    "category": "ecommerce-platforms",
    "tagline": "Simple online store platform built specifically for artists and makers",
    "description": "Big Cartel provides uncomplicated, affordable storefront hosting tailored for independent artists, clothing designers, and handicraft makers. It serves creative makers managing small product inventories.",
    "rating": 4.5,
    "reviewsCount": 1450,
    "pricing": "Freemium",
    "websiteUrl": "https://bigcartel.com",
    "affiliateUrl": "https://bigcartel.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "webflow-ecommerce",
    "name": "Webflow Ecommerce",
    "domain": "webflow.com/ecommerce",
    "category": "ecommerce-platforms",
    "tagline": "Visual design-first e-commerce builder for custom branded shopping experiences",
    "description": "Webflow Ecommerce grants complete visual design control over product pages, cart layouts, and checkout flows without code. It is engineered for web designers, creative agencies, and visual brands.",
    "rating": 4.6,
    "reviewsCount": 2100,
    "pricing": "Free Trial",
    "websiteUrl": "https://webflow.com/ecommerce",
    "affiliateUrl": "https://webflow.com/ecommerce",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "12.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "shoify-plus",
    "name": "Shopify Plus",
    "domain": "shopify.com/plus",
    "category": "ecommerce-platforms",
    "tagline": "Enterprise cloud e-commerce platform for high-volume global brands",
    "description": "Shopify Plus delivers dedicated enterprise checkout customization, localized multi-region expansion, and automated B2B features. It serves high-growth brands and Fortune 500 enterprise retailers.",
    "rating": 4.8,
    "reviewsCount": 1250,
    "pricing": "Paid",
    "websiteUrl": "https://shopify.com/plus",
    "affiliateUrl": "https://shopify.com/plus",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "68.5M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "spryker",
    "name": "Spryker",
    "domain": "spryker.com",
    "category": "ecommerce-platforms",
    "tagline": "Modular, composable e-commerce platform for enterprise B2B and marketplaces",
    "description": "Spryker provides API-first, headless commerce capabilities tailored for complex B2B business logic, IoT commerce, and multi-vendor marketplaces. It serves enterprise IT architects and digital directors.",
    "rating": 4.7,
    "reviewsCount": 180,
    "pricing": "Paid",
    "websiteUrl": "https://spryker.com",
    "affiliateUrl": "https://spryker.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "320K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "kibo-commerce",
    "name": "Kibo Commerce",
    "domain": "kibocommerce.com",
    "category": "ecommerce-platforms",
    "tagline": "Unified composable e-commerce, order management, and personalization platform",
    "description": "Kibo combines headless e-commerce, enterprise order management (DOM), and AI personalization on a single cloud platform. It serves mid-market and enterprise multi-channel retailers.",
    "rating": 4.4,
    "reviewsCount": 210,
    "pricing": "Paid",
    "websiteUrl": "https://kibocommerce.com",
    "affiliateUrl": "https://kibocommerce.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "240K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "vtex",
    "name": "VTEX",
    "domain": "vtex.com",
    "category": "ecommerce-platforms",
    "tagline": "Composable enterprise e-commerce platform with native marketplace and OMS",
    "description": "VTEX provides fully integrated headless commerce, native marketplace architecture, and distributed order management. It is designed for enterprise global retailers and consumer brands.",
    "rating": 4.5,
    "reviewsCount": 420,
    "pricing": "Paid",
    "websiteUrl": "https://vtex.com",
    "affiliateUrl": "https://vtex.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "orocrm-orocommerce",
    "name": "OroCommerce",
    "domain": "oroinc.com/b2b-ecommerce",
    "category": "ecommerce-platforms",
    "tagline": "Open-source e-commerce platform engineered specifically for B2B manufacturers and distributors",
    "description": "OroCommerce provides complex corporate account structures, custom buyer price books, CPQ workflows, and built-in CRM. It is engineered specifically for B2B manufacturers, wholesalers, and distributors.",
    "rating": 4.6,
    "reviewsCount": 160,
    "pricing": "Freemium",
    "websiteUrl": "https://oroinc.com/b2b-ecommerce",
    "affiliateUrl": "https://oroinc.com/b2b-ecommerce",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "180K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "nopcommerce",
    "name": "nopCommerce",
    "domain": "nopcommerce.com",
    "category": "ecommerce-platforms",
    "tagline": "Leading open-source .NET e-commerce platform for businesses worldwide",
    "description": "nopCommerce offers a free, ASP.NET Core open-source shopping cart with multi-store and multi-vendor marketplace capabilities out of the box. It serves .NET developers and mid-sized enterprises.",
    "rating": 4.6,
    "reviewsCount": 540,
    "pricing": "Free",
    "websiteUrl": "https://nopcommerce.com",
    "affiliateUrl": "https://nopcommerce.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "sylius",
    "name": "Sylius",
    "domain": "sylius.com",
    "category": "ecommerce-platforms",
    "tagline": "Open-source PHP framework for tailored e-commerce applications built on Symfony",
    "description": "Sylius provides a clean, highly testable PHP e-commerce framework for developers building completely custom shopping experiences. It is tailored for software engineers and digital agencies.",
    "rating": 4.8,
    "reviewsCount": 240,
    "pricing": "Free",
    "websiteUrl": "https://sylius.com",
    "affiliateUrl": "https://sylius.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "280K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "vendure",
    "name": "Vendure",
    "domain": "vendure.io",
    "category": "ecommerce-platforms",
    "tagline": "Open-source TypeScript headless e-commerce framework built on Node.js and GraphQL",
    "description": "Vendure delivers a modern TypeScript headless commerce framework with GraphQL APIs and flexible plugin extensions. It is engineered for modern web developers building custom digital stores.",
    "rating": 4.9,
    "reviewsCount": 190,
    "pricing": "Free",
    "websiteUrl": "https://vendure.io",
    "affiliateUrl": "https://vendure.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "150K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "bagisto",
    "name": "Bagisto",
    "domain": "bagisto.com",
    "category": "ecommerce-platforms",
    "tagline": "Open-source Laravel e-commerce framework and multi-vendor marketplace builder",
    "description": "Bagisto provides a flexible open-source e-commerce framework built on Laravel, featuring native multi-inventory and marketplace capabilities. It serves PHP developers and growing online businesses.",
    "rating": 4.7,
    "reviewsCount": 310,
    "pricing": "Free",
    "websiteUrl": "https://bagisto.com",
    "affiliateUrl": "https://bagisto.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "380K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "zoho-commerce",
    "name": "Zoho Commerce",
    "domain": "zoho.com/commerce",
    "category": "ecommerce-platforms",
    "tagline": "Integrated online store builder connected directly to the Zoho business ecosystem",
    "description": "Zoho Commerce combines site building, inventory tracking, order processing, and automated marketing in a single ecosystem. It is designed for businesses utilizing Zoho CRM and Zoho Books.",
    "rating": 4.4,
    "reviewsCount": 450,
    "pricing": "Free Trial",
    "websiteUrl": "https://zoho.com/commerce",
    "affiliateUrl": "https://zoho.com/commerce",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "weebly-ecommerce",
    "name": "Weebly (by Square)",
    "domain": "weebly.com/ecommerce-website",
    "category": "ecommerce-platforms",
    "tagline": "Simple, beginner-friendly online store builder backed by Square payments",
    "description": "Weebly provides drag-and-drop website creation paired with straightforward e-commerce selling powered by Square. It serves small business beginners, local merchants, and side-hustle sellers.",
    "rating": 4.3,
    "reviewsCount": 2100,
    "pricing": "Freemium",
    "websiteUrl": "https://weebly.com/ecommerce-website",
    "affiliateUrl": "https://weebly.com/ecommerce-website",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "6.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "cartflows",
    "name": "CartFlows",
    "domain": "cartflows.com",
    "category": "ecommerce-platforms",
    "tagline": "Sales funnel builder and high-converting checkout plugin for WooCommerce",
    "description": "CartFlows replaces standard WooCommerce checkout pages with custom sales funnels, order bumps, and one-click upsells. It is built for WordPress site owners seeking higher e-commerce conversion rates.",
    "rating": 4.8,
    "reviewsCount": 620,
    "pricing": "Free Trial",
    "websiteUrl": "https://cartflows.com",
    "affiliateUrl": "https://cartflows.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "surecart",
    "name": "SureCart",
    "domain": "surecart.com",
    "category": "ecommerce-platforms",
    "tagline": "Modern headless e-commerce and subscription platform for WordPress",
    "description": "SureCart offers a lightweight, modern platform for handling physical, digital, and subscription sales directly inside WordPress. It is designed for course creators, service providers, and WordPress site owners.",
    "rating": 4.9,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://surecart.com",
    "affiliateUrl": "https://surecart.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "350K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "thrivecart",
    "name": "Thrivecart",
    "domain": "thrivecart.com",
    "category": "ecommerce-platforms",
    "tagline": "High-converting shopping cart and funnel builder for digital products and courses",
    "description": "ThriveCart specializes in hosted checkout pages, sales funnels, course hosting (Learn), and affiliate management. It serves course creators, digital product sellers, and marketing strategists.",
    "rating": 4.8,
    "reviewsCount": 1150,
    "pricing": "Paid",
    "websiteUrl": "https://thrivecart.com",
    "affiliateUrl": "https://thrivecart.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.9M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "samcart",
    "name": "SamCart",
    "domain": "samcart.com",
    "category": "ecommerce-platforms",
    "tagline": "Direct-to-consumer checkout platform built to maximize customer order value",
    "description": "SamCart provides direct product checkout templates, dynamic add-ons, digital course delivery, and subscription tools. It is built for online creators, educators, and direct-response marketers.",
    "rating": 4.5,
    "reviewsCount": 1420,
    "pricing": "Free Trial",
    "websiteUrl": "https://samcart.com",
    "affiliateUrl": "https://samcart.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "cart66",
    "name": "Cart66",
    "domain": "cart66.com",
    "category": "ecommerce-platforms",
    "tagline": "Secure cloud-hosted checkout and e-commerce plugin for WordPress",
    "description": "Cart66 handles PCI-compliant checkout security, digital product delivery, and recurring subscriptions on WordPress without complex setup. It serves small businesses and independent web masters.",
    "rating": 4.2,
    "reviewsCount": 140,
    "pricing": "Free Trial",
    "websiteUrl": "https://cart66.com",
    "affiliateUrl": "https://cart66.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "90K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "easy-digital-downloads",
    "name": "Easy Digital Downloads (EDD)",
    "domain": "easydigitaldownloads.com",
    "category": "ecommerce-platforms",
    "tagline": "WordPress e-commerce plugin specialized for selling digital products and software",
    "description": "Easy Digital Downloads simplifies selling software, PDFs, graphics, and digital media natively inside WordPress. It is engineered specifically for software developers, authors, and digital creators.",
    "rating": 4.7,
    "reviewsCount": 890,
    "pricing": "Freemium",
    "websiteUrl": "https://easydigitaldownloads.com",
    "affiliateUrl": "https://easydigitaldownloads.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "memberpress",
    "name": "MemberPress",
    "domain": "memberpress.com",
    "category": "ecommerce-platforms",
    "tagline": "All-in-one WordPress membership, digital course, and paywall e-commerce plugin",
    "description": "MemberPress restricts content access, manages recurring subscription payments, and delivers online courses on WordPress. It is built for online educators, publishers, and membership site owners.",
    "rating": 4.8,
    "reviewsCount": 1100,
    "pricing": "Paid",
    "websiteUrl": "https://memberpress.com",
    "affiliateUrl": "https://memberpress.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "sellfi",
    "name": "Shopaccino",
    "domain": "shopaccino.com",
    "category": "ecommerce-platforms",
    "tagline": "Cloud e-commerce platform for launching custom retail websites and mobile apps",
    "description": "Shopaccino provides online store creation tools paired with native iOS and Android mobile shopping app builders. It serves growing retail brands and physical stores expanding online.",
    "rating": 4.6,
    "reviewsCount": 120,
    "pricing": "Free Trial",
    "websiteUrl": "https://shopaccino.com",
    "affiliateUrl": "https://shopaccino.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "110K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "jumpseller",
    "name": "Jumpseller",
    "domain": "jumpseller.com",
    "category": "ecommerce-platforms",
    "tagline": "Global e-commerce platform with strong regional payment support across Latin America",
    "description": "Jumpseller enables small business merchants to build online stores with integrated multi-language and localized payment gateways. It is popular among Latin American and European online sellers.",
    "rating": 4.6,
    "reviewsCount": 380,
    "pricing": "Free Trial",
    "websiteUrl": "https://jumpseller.com",
    "affiliateUrl": "https://jumpseller.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "shopline",
    "name": "SHOPLINE",
    "domain": "shopline.com",
    "category": "ecommerce-platforms",
    "tagline": "Global smart commerce enabler for cross-border e-commerce and retail",
    "description": "SHOPLINE provides hosted storefronts, social commerce tools, live-stream shopping, and cross-border payment integration. It serves direct-to-consumer merchants expanding across international markets.",
    "rating": 4.6,
    "reviewsCount": 510,
    "pricing": "Free Trial",
    "websiteUrl": "https://shopline.com",
    "affiliateUrl": "https://shopline.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.6M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "branchbob",
    "name": "branchbob",
    "domain": "branchbob.com",
    "category": "ecommerce-platforms",
    "tagline": "Free cloud e-commerce platform for building online stores with no monthly platform fee",
    "description": "branchbob allows merchants to set up online stores quickly without monthly subscription fees or transaction cut markups. It serves small business beginners and budget-conscious retailers.",
    "rating": 4.5,
    "reviewsCount": 210,
    "pricing": "Free",
    "websiteUrl": "https://branchbob.com",
    "affiliateUrl": "https://branchbob.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "190K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "shopware",
    "name": "Shopware",
    "domain": "shopware.com",
    "category": "ecommerce-platforms",
    "tagline": "Leading European open-source e-commerce platform for B2C and B2B brands",
    "description": "Shopware offers a flexible, open-source e-commerce architecture with visual story building and advanced B2B capabilities. It is heavily utilized by European enterprises, retailers, and agencies.",
    "rating": 4.6,
    "reviewsCount": 620,
    "pricing": "Freemium",
    "websiteUrl": "https://shopware.com",
    "affiliateUrl": "https://shopware.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "strikingly-store",
    "name": "Strikingly",
    "domain": "strikingly.com",
    "category": "ecommerce-platforms",
    "tagline": "Simple single-page website builder with built-in simple online store",
    "description": "Strikingly enables users to construct single-page websites and instantly attach simple e-commerce checkout sections. It serves freelancers, event organizers, and micro-product sellers.",
    "rating": 4.4,
    "reviewsCount": 980,
    "pricing": "Freemium",
    "websiteUrl": "https://strikingly.com",
    "affiliateUrl": "https://strikingly.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "dokan-cloud",
    "name": "Dokan Cloud",
    "domain": "dokan.co",
    "category": "ecommerce-platforms",
    "tagline": "Multi-vendor marketplace builder to launch online marketplace portals",
    "description": "Dokan Cloud provides all necessary infrastructure to launch custom multi-vendor e-commerce marketplaces with individual seller dashboards. It serves marketplace entrepreneurs and business operators.",
    "rating": 4.7,
    "reviewsCount": 820,
    "pricing": "Free Trial",
    "websiteUrl": "https://dokan.co",
    "affiliateUrl": "https://dokan.co",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "520K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "cart2cart",
    "name": "Cart2Cart",
    "domain": "shopping-cart-migration.com",
    "category": "ecommerce-platforms",
    "tagline": "Automated e-commerce migration service between shopping cart platforms",
    "description": "Cart2Cart migrates products, customers, order histories, and SEO redirects seamlessly between 85+ e-commerce platforms. It serves online merchants and agency leads executing platform migrations.",
    "rating": 4.8,
    "reviewsCount": 750,
    "pricing": "Free Trial",
    "websiteUrl": "https://shopping-cart-migration.com",
    "affiliateUrl": "https://shopping-cart-migration.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "380K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "shoppimo-shopizer",
    "name": "Shopizer",
    "domain": "shopizer.com",
    "category": "ecommerce-platforms",
    "tagline": "Open-source Java e-commerce software and headless REST API engine",
    "description": "Shopizer delivers an open-source Java e-commerce backend providing REST APIs for web and mobile retail applications. It is engineered for Java developers and enterprise software architects.",
    "rating": 4.5,
    "reviewsCount": 110,
    "pricing": "Free",
    "websiteUrl": "https://shopizer.com",
    "affiliateUrl": "https://shopizer.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "85K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "swell-is",
    "name": "Swell",
    "domain": "swell.is",
    "category": "ecommerce-platforms",
    "tagline": "Customizable headless e-commerce platform for modern brands and agencies",
    "description": "Swell provides flexible API-first headless commerce infrastructure with native support for subscription billing and custom models. It serves software developers, agencies, and innovative online brands.",
    "rating": 4.7,
    "reviewsCount": 210,
    "pricing": "Freemium",
    "websiteUrl": "https://swell.is",
    "affiliateUrl": "https://swell.is",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "240K",
    "isFreeTier": true,
    "isOpenSource": false
  }
];

const saasDataPath = path.join(__dirname, '..', 'src', 'data', 'saasData.jsx');
let content = fs.readFileSync(saasDataPath, 'utf8');

const match = content.match(/export const staticSaasTools = (\[[\s\S]*?\n\]);/);
if (!match) {
  console.error('Could not find staticSaasTools in saasData.jsx');
  process.exit(1);
}

let existingTools = JSON.parse(match[1]);

const existingIds = new Set(existingTools.map(t => t.id.toLowerCase()));
const existingNames = new Set(existingTools.map(t => t.name.toLowerCase()));

let addedCount = 0;
let skippedCount = 0;

newTools.forEach(tool => {
  const normId = tool.id.toLowerCase();
  const normName = tool.name.toLowerCase();

  if (!existingIds.has(normId) && !existingNames.has(normName)) {
    existingTools.push(tool);
    existingIds.add(normId);
    existingNames.add(normName);
    addedCount++;
  } else {
    // Enrich existing tool without creating a duplicate
    const idx = existingTools.findIndex(t => t.id.toLowerCase() === normId || t.name.toLowerCase() === normName);
    if (idx !== -1) {
      existingTools[idx] = { ...existingTools[idx], category: tool.category, tagline: tool.tagline || existingTools[idx].tagline };
    }
    skippedCount++;
  }
});

const updatedArrayStr = JSON.stringify(existingTools, null, 2);
content = content.replace(/export const staticSaasTools = \[[\s\S]*?\n\];/, `export const staticSaasTools = ${updatedArrayStr};`);

fs.writeFileSync(saasDataPath, content, 'utf8');
console.log(`Ingestion Complete! Added: ${addedCount} brand new tools | Deduplicated: ${skippedCount} existing tools | Total static tools: ${existingTools.length}`);
