const fs = require('fs');
const path = require('path');

const newTools = [
  {
    "id": "typeform",
    "name": "Typeform",
    "domain": "typeform.com",
    "category": "forms-surveys",
    "tagline": "Conversational online form builder designed to engage respondents one question at a time",
    "description": "Typeform turns standard forms and surveys into interactive conversational experiences with dynamic conditional logic. It is built for marketers, product teams, and businesses aiming to increase completion rates.",
    "rating": 4.7,
    "reviewsCount": 3800,
    "pricing": "Freemium",
    "websiteUrl": "https://typeform.com",
    "affiliateUrl": "https://typeform.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "18.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "jotform",
    "name": "Jotform",
    "domain": "jotform.com",
    "category": "forms-surveys",
    "tagline": "Powerful online form builder with payment processing, widgets, and e-signatures",
    "description": "Jotform offers thousands of customizable form templates, conditional logic rules, payment gateway integrations, and PDF report builders. It serves small businesses, healthcare organizations, and non-profits collecting data.",
    "rating": 4.7,
    "reviewsCount": 4200,
    "pricing": "Freemium",
    "websiteUrl": "https://jotform.com",
    "affiliateUrl": "https://jotform.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "22.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "tally",
    "name": "Tally",
    "domain": "tally.so",
    "category": "forms-surveys",
    "tagline": "Simple Notion-like form builder with unlimited forms and responses",
    "description": "Tally uses a document-style slash-command interface to construct clean, customizable web forms and surveys in seconds. It is designed for creators, startups, and product managers collecting structured user feedback.",
    "rating": 4.9,
    "reviewsCount": 1150,
    "pricing": "Freemium",
    "websiteUrl": "https://tally.so",
    "affiliateUrl": "https://tally.so",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "3.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "fillout",
    "name": "Fillout",
    "domain": "fillout.com",
    "category": "forms-surveys",
    "tagline": "Advanced form builder native to Airtable, Notion, and SQL databases",
    "description": "Fillout allows creators to build multi-step forms, user login portals, and surveys that directly read and update external databases. It is tailored for modern operations and product teams collecting database records.",
    "rating": 4.9,
    "reviewsCount": 850,
    "pricing": "Freemium",
    "websiteUrl": "https://fillout.com",
    "affiliateUrl": "https://fillout.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "google-forms",
    "name": "Google Forms",
    "domain": "forms.google.com",
    "category": "forms-surveys",
    "tagline": "Free, easy-to-use web form and quiz builder integrated with Google Sheets",
    "description": "Google Forms creates straightforward web forms, quick surveys, and self-grading quizzes that sync results directly to spreadsheets. It is used worldwide by educators, individuals, and businesses for basic data collection.",
    "rating": 4.6,
    "reviewsCount": 6500,
    "pricing": "Free",
    "websiteUrl": "https://forms.google.com",
    "affiliateUrl": "https://forms.google.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "85.0M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "surveymonkey",
    "name": "SurveyMonkey",
    "domain": "surveymonkey.com",
    "category": "forms-surveys",
    "tagline": "Enterprise survey platform for market research, CSAT, and employee feedback",
    "description": "SurveyMonkey delivers robust survey logic, audience panel sourcing, statistical reporting, and enterprise governance tools. It is engineered for market researchers, enterprise HR teams, and customer experience managers.",
    "rating": 4.5,
    "reviewsCount": 5400,
    "pricing": "Freemium",
    "websiteUrl": "https://surveymonkey.com",
    "affiliateUrl": "https://surveymonkey.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "28.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "formstack",
    "name": "Formstack Forms",
    "domain": "formstack.com",
    "category": "forms-surveys",
    "tagline": "HIPAA-compliant online form builder and automated document workflow engine",
    "description": "Formstack Forms enables secure data collection with strict HIPAA/GDPR compliance, custom approval routing, and digital document generation. it is built for healthcare providers, financial institutions, and enterprise teams.",
    "rating": 4.5,
    "reviewsCount": 1100,
    "pricing": "Free Trial",
    "websiteUrl": "https://formstack.com",
    "affiliateUrl": "https://formstack.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "paperform",
    "name": "Paperform",
    "domain": "paperform.co",
    "category": "forms-surveys",
    "tagline": "Versatile digital form and landing page builder with built-in payments and booking",
    "description": "Paperform combines doc-style editing, custom media insertion, payment collection, and calendar appointment scheduling into standalone forms. It serves small businesses, agencies, and independent creators.",
    "rating": 4.8,
    "reviewsCount": 620,
    "pricing": "Free Trial",
    "websiteUrl": "https://paperform.co",
    "affiliateUrl": "https://paperform.co",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "feathery",
    "name": "Feathery",
    "domain": "feathery.io",
    "category": "forms-surveys",
    "tagline": "Developer-grade form builder for complex user onboarding and product flows",
    "description": "Feathery provides granular layout styling, custom JavaScript extensions, and deep API integrations to construct complex product onboarding forms. It is engineered for product managers, growth teams, and software engineers.",
    "rating": 4.9,
    "reviewsCount": 210,
    "pricing": "Freemium",
    "websiteUrl": "https://feathery.io",
    "affiliateUrl": "https://feathery.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "320K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "qualtrics",
    "name": "Qualtrics XM",
    "domain": "qualtrics.com",
    "category": "forms-surveys",
    "tagline": "Enterprise experience management platform for deep market and customer research",
    "description": "Qualtrics provides advanced statistical analysis, predictive text analytics, and automated experience workflows across customer and employee touchpoints. It is designed for Global 2000 enterprises and academic researchers.",
    "rating": 4.5,
    "reviewsCount": 2800,
    "pricing": "Free Trial",
    "websiteUrl": "https://qualtrics.com",
    "affiliateUrl": "https://qualtrics.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "14.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "formbricks",
    "name": "Formbricks",
    "domain": "formbricks.com",
    "category": "forms-surveys",
    "tagline": "Open-source in-app user survey and micro-feedback platform for SaaS",
    "description": "Formbricks allows product teams to trigger targeted micro-surveys natively inside web and mobile applications based on user actions. It serves open-source developers, SaaS product leads, and UX researchers.",
    "rating": 4.9,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://formbricks.com",
    "affiliateUrl": "https://formbricks.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "formspree",
    "name": "Formspree",
    "domain": "formspree.io",
    "category": "forms-surveys",
    "tagline": "Form backend infrastructure and API for static site developers",
    "description": "Formspree handles backend submission processing, spam filtering, and email notifications for custom HTML and Jamstack forms without server code. It is tailored for web developers and frontend engineers.",
    "rating": 4.7,
    "reviewsCount": 920,
    "pricing": "Freemium",
    "websiteUrl": "https://formspree.io",
    "affiliateUrl": "https://formspree.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "web3forms",
    "name": "Web3Forms",
    "domain": "web3forms.com",
    "category": "forms-surveys",
    "tagline": "Contact form backend API without server code or access keys",
    "description": "Web3Forms routes static HTML contact form submissions directly to developer inboxes using access keys without backend infrastructure. It serves Jamstack developers and static site owners.",
    "rating": 4.8,
    "reviewsCount": 310,
    "pricing": "Freemium",
    "websiteUrl": "https://web3forms.com",
    "affiliateUrl": "https://web3forms.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "380K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "wufoo",
    "name": "Wufoo by SurveyMonkey",
    "domain": "wufoo.com",
    "category": "forms-surveys",
    "tagline": "Cloud-based form builder for creating web forms, payment forms, and surveys",
    "description": "Wufoo allows users to build drag-and-drop online forms, accept payments, and generate automated database reports. It is built for small business teams, event organizers, and administrative leads.",
    "rating": 4.4,
    "reviewsCount": 1250,
    "pricing": "Freemium",
    "websiteUrl": "https://wufoo.com",
    "affiliateUrl": "https://wufoo.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.9M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "zoho-forms",
    "name": "Zoho Forms",
    "domain": "zoho.com/forms",
    "category": "forms-surveys",
    "tagline": "Online form builder with workflow automation and deep Zoho CRM integration",
    "description": "Zoho Forms collects data via web and mobile forms, triggering automated email notifications, task assignments, and CRM record updates. It is optimized for businesses operating in the Zoho ecosystem.",
    "rating": 4.6,
    "reviewsCount": 1650,
    "pricing": "Freemium",
    "websiteUrl": "https://zoho.com/forms",
    "affiliateUrl": "https://zoho.com/forms",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "cognito-forms",
    "name": "Cognito Forms",
    "domain": "cognitoforms.com",
    "category": "forms-surveys",
    "tagline": "Advanced online form builder featuring custom calculations and conditional logic",
    "description": "Cognito Forms specializes in complex conditional logic, field calculations, multi-page forms, and integrated payment processing. It serves small businesses, educational institutions, and healthcare providers.",
    "rating": 4.7,
    "reviewsCount": 980,
    "pricing": "Freemium",
    "websiteUrl": "https://cognitoforms.com",
    "affiliateUrl": "https://cognitoforms.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.9M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "123formbuilder",
    "name": "123FormBuilder",
    "domain": "123formbuilder.com",
    "category": "forms-surveys",
    "tagline": "Drag-and-drop online form builder with deep Salesforce integration",
    "description": "123FormBuilder creates web forms and surveys that auto-populate and sync records directly with Salesforce and other CRMs. It is tailored for enterprise sales operations, non-profits, and corporate HR.",
    "rating": 4.5,
    "reviewsCount": 780,
    "pricing": "Freemium",
    "websiteUrl": "https://123formbuilder.com",
    "affiliateUrl": "https://123formbuilder.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "100ms-surveys-tripetto",
    "name": "Tripetto",
    "domain": "tripetto.com",
    "category": "forms-surveys",
    "tagline": "Conversational form builder plugin and web app with visual logic flowcharts",
    "description": "Tripetto uses a visual flowchart canvas to design conversational forms, quizzes, and surveys with advanced logic branches. It provides both a WordPress plugin and a standalone web application.",
    "rating": 4.8,
    "reviewsCount": 320,
    "pricing": "Freemium",
    "websiteUrl": "https://tripetto.com",
    "affiliateUrl": "https://tripetto.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "380K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "microsoft-forms",
    "name": "Microsoft Forms",
    "domain": "forms.office.com",
    "category": "forms-surveys",
    "tagline": "Simple survey, quiz, and poll creation tool integrated into Microsoft 365",
    "description": "Microsoft Forms enables users to create surveys, quizzes, and internal polls with automated real-time charts and Excel data exporting. It is built for Microsoft 365 enterprise users, educators, and administrative teams.",
    "rating": 4.5,
    "reviewsCount": 3100,
    "pricing": "Freemium",
    "websiteUrl": "https://forms.office.com",
    "affiliateUrl": "https://forms.office.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "42.0M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "survey-sparrow",
    "name": "SurveySparrow",
    "domain": "surveysparrow.com",
    "category": "forms-surveys",
    "tagline": "Omnichannel customer experience and conversational survey software",
    "description": "SurveySparrow transforms static surveys into chat-like experiences across web, executive dashboards, offline kiosks, and email. It is engineered for customer success teams, HR managers, and market researchers.",
    "rating": 4.5,
    "reviewsCount": 1420,
    "pricing": "Free Trial",
    "websiteUrl": "https://surveysparrow.com",
    "affiliateUrl": "https://surveysparrow.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.9M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "get-feedback",
    "name": "GetFeedback by SurveyMonkey",
    "domain": "getfeedback.com",
    "category": "forms-surveys",
    "tagline": "Agile customer experience feedback platform built for Salesforce users",
    "description": "GetFeedback collects real-time customer feedback across email, web, and mobile channels, mapping responses directly into Salesforce objects. It serves customer experience (CX) and support leaders.",
    "rating": 4.5,
    "reviewsCount": 420,
    "pricing": "Paid",
    "websiteUrl": "https://getfeedback.com",
    "affiliateUrl": "https://getfeedback.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "survicate",
    "name": "Survicate",
    "domain": "survicate.com",
    "category": "forms-surveys",
    "tagline": "Continuous customer feedback software for web, mobile apps, and email",
    "description": "Survicate runs targeted web popups, mobile app micro-surveys, and email CSAT/NPS evaluations to capture customer sentiment continuously. It serves product managers, growth marketers, and customer success leads.",
    "rating": 4.7,
    "reviewsCount": 510,
    "pricing": "Freemium",
    "websiteUrl": "https://survicate.com",
    "affiliateUrl": "https://survicate.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "850K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "usabilla-contentsquare",
    "name": "Contentsquare VOC (formerly Usabilla)",
    "domain": "contentsquare.com/voice-of-customer",
    "category": "forms-surveys",
    "tagline": "Voice of customer feedback buttons and visual website feedback tools",
    "description": "Contentsquare VOC allows website visitors to submit instant visual feedback, report bugs, and rate site experiences. It is engineered for enterprise e-commerce managers and digital product teams.",
    "rating": 4.4,
    "reviewsCount": 380,
    "pricing": "Paid",
    "websiteUrl": "https://contentsquare.com/voice-of-customer",
    "affiliateUrl": "https://contentsquare.com/voice-of-customer",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.5M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "wootric-inmoment",
    "name": "Wootric by InMoment",
    "domain": "wootric.com",
    "category": "forms-surveys",
    "tagline": "In-app NPS, CSAT, and CES micro-surveys for SaaS and digital products",
    "description": "Wootric measures Net Promoter Score (NPS), CSAT, and Customer Effort Score (CES) directly inside web apps, mobile apps, and email. It is tailored for SaaS product leads and customer success managers.",
    "rating": 4.6,
    "reviewsCount": 290,
    "pricing": "Free Trial",
    "websiteUrl": "https://wootric.com",
    "affiliateUrl": "https://wootric.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "340K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "delighted-qualitrics",
    "name": "Delighted by Qualtrics",
    "domain": "delighted.com",
    "category": "forms-surveys",
    "tagline": "Turnkey customer feedback platform for gathering NPS, CSAT, and CES fast",
    "description": "Delighted enables brands to send multi-channel NPS, CSAT, and product feedback surveys via email, web, SMS, or link in minutes. It serves fast-growing e-commerce brands and customer-centric SMBs.",
    "rating": 4.7,
    "reviewsCount": 680,
    "pricing": "Freemium",
    "websiteUrl": "https://delighted.com",
    "affiliateUrl": "https://delighted.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "920K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "refiner-io",
    "name": "Refiner",
    "domain": "refiner.io",
    "category": "forms-surveys",
    "tagline": "User feedback and survey platform built specifically for SaaS products",
    "description": "Refiner triggers highly targeted in-app surveys to specific user segments based on behavioral data and product usage. It serves SaaS product managers, growth hackers, and UX researchers.",
    "rating": 4.8,
    "reviewsCount": 190,
    "pricing": "Free Trial",
    "websiteUrl": "https://refiner.io",
    "affiliateUrl": "https://refiner.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "210K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "hotjar-surveys",
    "name": "Hotjar Surveys",
    "domain": "hotjar.com/our-product/surveys",
    "category": "forms-surveys",
    "tagline": "On-site website feedback widgets and exit-intent survey popups",
    "description": "Hotjar Surveys launches targeted exit-intent survey popups and embedded feedback widgets linked directly to user session recordings. It is built for UX designers, CRO specialists, and digital marketers.",
    "rating": 4.6,
    "reviewsCount": 3200,
    "pricing": "Freemium",
    "websiteUrl": "https://hotjar.com/our-product/surveys",
    "affiliateUrl": "https://hotjar.com/our-product/surveys",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "9.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "gravity-forms",
    "name": "Gravity Forms",
    "domain": "gravityforms.com",
    "category": "forms-surveys",
    "tagline": "The premier drag-and-drop form building plugin for WordPress websites",
    "description": "Gravity Forms provides advanced form fields, multi-page layouts, quiz add-ons, and payment integrations natively inside WordPress. It is the go-to form solution for WordPress developers and web agencies.",
    "rating": 4.7,
    "reviewsCount": 2400,
    "pricing": "Paid",
    "websiteUrl": "https://gravityforms.com",
    "affiliateUrl": "https://gravityforms.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "wpforms",
    "name": "WPForms",
    "domain": "wpforms.com",
    "category": "forms-surveys",
    "tagline": "User-friendly drag-and-drop WordPress form builder plugin for beginners",
    "description": "WPForms makes creating contact forms, survey polls, subscription forms, and payment checkouts simple for WordPress users. It is designed for small business owners, bloggers, and non-technical site admins.",
    "rating": 4.8,
    "reviewsCount": 3800,
    "pricing": "Freemium",
    "websiteUrl": "https://wpforms.com",
    "affiliateUrl": "https://wpforms.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "ninja-forms",
    "name": "Ninja Forms",
    "domain": "ninjaforms.com",
    "category": "forms-surveys",
    "tagline": "Flexible, developer-friendly WordPress form builder with modular add-ons",
    "description": "Ninja Forms offers an intuitive drag-and-drop form builder interface backed by extensive developer hooks and customizable add-ons. It serves WordPress site owners, freelancers, and agency developers.",
    "rating": 4.5,
    "reviewsCount": 1850,
    "pricing": "Freemium",
    "websiteUrl": "https://ninjaforms.com",
    "affiliateUrl": "https://ninjaforms.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.6M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "formidable-forms",
    "name": "Formidable Forms",
    "domain": "formidableforms.com",
    "category": "forms-surveys",
    "tagline": "Advanced WordPress form builder plugin with data views and web app building",
    "description": "Formidable Forms goes beyond basic forms by turning user submission data into front-end directories, listings, and web applications on WordPress. It is engineered for advanced WordPress developers and agency teams.",
    "rating": 4.8,
    "reviewsCount": 920,
    "pricing": "Freemium",
    "websiteUrl": "https://formidableforms.com",
    "affiliateUrl": "https://formidableforms.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "fluent-forms",
    "name": "Fluent Forms",
    "domain": "fluentforms.com",
    "category": "forms-surveys",
    "tagline": "Lightweight, fast drag-and-drop WordPress form plugin",
    "description": "Fluent Forms delivers fast form rendering, conversational form modes, conditional logic, and built-in calculations for WordPress. It is built for budget-conscious site owners seeking fast page load speeds.",
    "rating": 4.9,
    "reviewsCount": 750,
    "pricing": "Freemium",
    "websiteUrl": "https://fluentforms.com",
    "affiliateUrl": "https://fluentforms.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "820K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "ohmyform",
    "name": "OhMyForm",
    "domain": "ohmyform.com",
    "category": "forms-surveys",
    "tagline": "Open-source self-hostable alternative to Typeform and Google Forms",
    "description": "OhMyForm enables developers to deploy and host open-source conversational web forms and surveys on their own servers. It serves privacy advocates, open-source developers, and self-hosting enthusiasts.",
    "rating": 4.6,
    "reviewsCount": 180,
    "pricing": "Free",
    "websiteUrl": "https://ohmyform.com",
    "affiliateUrl": "https://ohmyform.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "140K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "lime-survey",
    "name": "LimeSurvey",
    "domain": "limesurvey.org",
    "category": "forms-surveys",
    "tagline": "Leading open-source online survey tool for statistical research",
    "description": "LimeSurvey provides open-source survey creation, complex branching logic, token-based respondent management, and statistical data exporting. It is widely used by universities, academic researchers, and government agencies.",
    "rating": 4.5,
    "reviewsCount": 1100,
    "pricing": "Freemium",
    "websiteUrl": "https://limesurvey.org",
    "affiliateUrl": "https://limesurvey.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "alchemer",
    "name": "Alchemer (formerly SurveyGizmo)",
    "domain": "alchemer.com",
    "category": "forms-surveys",
    "tagline": "Flexible enterprise survey and customer feedback collection platform",
    "description": "Alchemer provides custom survey building, automated action workflows, and CRM data integration to turn feedback into business action. It serves enterprise customer research and operations teams.",
    "rating": 4.4,
    "reviewsCount": 1250,
    "pricing": "Free Trial",
    "websiteUrl": "https://alchemer.com",
    "affiliateUrl": "https://alchemer.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.6M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "proprofs-survey-maker",
    "name": "ProProfs Survey Maker",
    "domain": "proprofs.com/survey",
    "category": "forms-surveys",
    "tagline": "Simple online survey maker for quizzes, polls, and customer feedback",
    "description": "ProProfs Survey Maker allows users to build scored quizzes, NPS evaluations, and web feedback widgets quickly with pre-made templates. It is designed for educators, marketers, and small business leads.",
    "rating": 4.5,
    "reviewsCount": 450,
    "pricing": "Freemium",
    "websiteUrl": "https://proprofs.com/survey",
    "affiliateUrl": "https://proprofs.com/survey",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "kform-kform-io",
    "name": "Kidoju / Formsite",
    "domain": "formsite.com",
    "category": "forms-surveys",
    "tagline": "Secure online form builder with encrypting, payments, and PDF generation",
    "description": "Formsite specializes in secure form processing, PCI payment integration, encrypted fields, and automated PDF document generation. It serves corporate compliance teams, schools, and event hosts.",
    "rating": 4.6,
    "reviewsCount": 620,
    "pricing": "Free Trial",
    "websiteUrl": "https://formsite.com",
    "affiliateUrl": "https://formsite.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "user-testing",
    "name": "UserTesting",
    "domain": "usertesting.com",
    "category": "forms-surveys",
    "tagline": "Human insight platform for video feedback and usability testing",
    "description": "UserTesting connects product teams with real human testers who record video and audio as they navigate digital experiences. It is engineered for enterprise UX researchers and product designers.",
    "rating": 4.5,
    "reviewsCount": 1820,
    "pricing": "Paid",
    "websiteUrl": "https://usertesting.com",
    "affiliateUrl": "https://usertesting.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "maze-co",
    "name": "Maze",
    "domain": "maze.co",
    "category": "forms-surveys",
    "tagline": "Rapid product discovery and prototype testing platform for designers",
    "description": "Maze turns Figma and Adobe XD prototypes into unmoderated user usability tests with quantitative metrics and heatmaps automatically. It serves product designers, UX researchers, and product managers.",
    "rating": 4.7,
    "reviewsCount": 890,
    "pricing": "Freemium",
    "websiteUrl": "https://maze.co",
    "affiliateUrl": "https://maze.co",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "useberry",
    "name": "Useberry",
    "domain": "useberry.com",
    "category": "forms-surveys",
    "tagline": "UI prototype testing and user feedback analytics platform",
    "description": "Useberry allows designers to test prototype user flows, collect screen heatmaps, and run preference surveys prior to code deployment. It is built for UX/UI designers and product strategy teams.",
    "rating": 4.8,
    "reviewsCount": 240,
    "pricing": "Freemium",
    "websiteUrl": "https://useberry.com",
    "affiliateUrl": "https://useberry.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "280K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "sprig",
    "name": "Sprig",
    "domain": "sprig.com",
    "category": "forms-surveys",
    "tagline": "AI-powered product experience platform for targeted in-app surveys and user research",
    "description": "Sprig uses AI to analyze in-app surveys, concept tests, and user session replays in real time. It is engineered for fast-moving product and UX research teams scaling digital software.",
    "rating": 4.7,
    "reviewsCount": 310,
    "pricing": "Freemium",
    "websiteUrl": "https://sprig.com",
    "affiliateUrl": "https://sprig.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "410K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "feedier",
    "name": "Feedier",
    "domain": "feedier.com",
    "category": "forms-surveys",
    "tagline": "Interactive customer feedback platform using gamified survey experiences",
    "description": "Feedier collects multi-channel feedback using gamified survey rewards and converts raw text responses into structured analytics. It serves customer experience managers and marketing directors.",
    "rating": 4.6,
    "reviewsCount": 160,
    "pricing": "Free Trial",
    "websiteUrl": "https://feedier.com",
    "affiliateUrl": "https://feedier.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "150K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "involve-me",
    "name": "involve.me",
    "domain": "involve.me",
    "category": "forms-surveys",
    "tagline": "No-code interactive funnel, quiz, and survey builder for marketing lead generation",
    "description": "involve.me builds interactive personality quizzes, price calculators, and lead capture surveys to increase digital marketing conversions. It is tailored for digital marketers and agency teams.",
    "rating": 4.7,
    "reviewsCount": 420,
    "pricing": "Freemium",
    "websiteUrl": "https://involve.me",
    "affiliateUrl": "https://involve.me",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "650K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "outgrow-co",
    "name": "Outgrow",
    "domain": "outgrow.co",
    "category": "forms-surveys",
    "tagline": "Interactive content platform for building calculators, viral quizzes, and forms",
    "description": "Outgrow enables marketers to acquire leads by building custom ROI calculators, interactive assessments, and viral recommendation quizzes. It is built for growth marketers and performance agencies.",
    "rating": 4.8,
    "reviewsCount": 720,
    "pricing": "Free Trial",
    "websiteUrl": "https://outgrow.co",
    "affiliateUrl": "https://outgrow.co",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "heyflow",
    "name": "Heyflow",
    "domain": "heyflow.app",
    "category": "forms-surveys",
    "tagline": "No-code interactive click-flow and lead generation form builder",
    "description": "Heyflow creates visually rich click-flows, lead qualification funnels, and interactive forms designed for paid ad campaigns. It is optimized for performance agencies and conversion marketers.",
    "rating": 4.8,
    "reviewsCount": 210,
    "pricing": "Free Trial",
    "websiteUrl": "https://heyflow.app",
    "affiliateUrl": "https://heyflow.app",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "340K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "opinion-stage",
    "name": "Opinion Stage",
    "domain": "opinionstage.com",
    "category": "forms-surveys",
    "tagline": "Interactive survey, poll, and quiz maker for websites and digital publishers",
    "description": "Opinion Stage helps publishers and brand marketers increase on-site engagement with interactive polls, lead generation quizzes, and visual surveys. It serves media sites and content creators.",
    "rating": 4.6,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://opinionstage.com",
    "affiliateUrl": "https://opinionstage.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "580K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "survey-planet",
    "name": "SurveyPlanet",
    "domain": "surveyplanet.com",
    "category": "forms-surveys",
    "tagline": "Simple online survey maker with clean templates and unlimited free responses",
    "description": "SurveyPlanet provides simple online survey creation with responsive themes, multi-language support, and clean visual reports. It serves educators, students, and small business owners.",
    "rating": 4.5,
    "reviewsCount": 540,
    "pricing": "Freemium",
    "websiteUrl": "https://surveyplanet.com",
    "affiliateUrl": "https://surveyplanet.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "920K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "sogosurvey-kapture",
    "name": "Kapture CX (formerly SoGoSurvey)",
    "domain": "kapturecx.com",
    "category": "forms-surveys",
    "tagline": "Enterprise survey software for employee engagement and customer feedback",
    "description": "Kapture CX delivers automated survey distribution, advanced analytics, and secure data handling for workforce and customer sentiment. It serves enterprise HR divisions and CX teams.",
    "rating": 4.4,
    "reviewsCount": 310,
    "pricing": "Free Trial",
    "websiteUrl": "https://kapturecx.com",
    "affiliateUrl": "https://kapturecx.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "290K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "pointerpro-suvbiz",
    "name": "Pointerpro (formerly Survey Anyplace)",
    "domain": "pointerpro.com",
    "category": "forms-surveys",
    "tagline": "Software to create interactive assessments that automatically generate personalized PDF reports",
    "description": "Pointerpro turns online assessment survey answers into customized PDF reports delivered to respondents instantly. It is built for professional advisors, consultants, and trainers.",
    "rating": 4.6,
    "reviewsCount": 180,
    "pricing": "Free Trial",
    "websiteUrl": "https://pointerpro.com",
    "affiliateUrl": "https://pointerpro.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "180K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "kwanko-questionpro",
    "name": "QuestionPro",
    "domain": "questionpro.com",
    "category": "forms-surveys",
    "tagline": "Online survey software for research, customer experience, and employee feedback",
    "description": "QuestionPro provides full-suite survey creation, conjoint analysis tools, workforce sentiment tracking, and research panels. It is designed for academic researchers, enterprise CX leads, and pollsters.",
    "rating": 4.5,
    "reviewsCount": 1100,
    "pricing": "Freemium",
    "websiteUrl": "https://questionpro.com",
    "affiliateUrl": "https://questionpro.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.4M",
    "isFreeTier": true,
    "isOpenSource": false
  }
];

const saasDataPath = path.join(__dirname, '..', 'src', 'data', 'saasData.jsx');
let content = fs.readFileSync(saasDataPath, 'utf8');

const match = content.match(/export const staticSaasTools = (\[[\s\S]*?\n\]);/);
if (!match) {
  console.error('Could not find staticSaasTools in saasData.jsx');
  process.exit(1);
}

let existingTools = JSON.parse(match[1]);

const existingIds = new Set(existingTools.map(t => t.id.toLowerCase()));
const existingNames = new Set(existingTools.map(t => t.name.toLowerCase()));

let addedCount = 0;
let skippedCount = 0;

newTools.forEach(tool => {
  const normId = tool.id.toLowerCase();
  const normName = tool.name.toLowerCase();

  if (!existingIds.has(normId) && !existingNames.has(normName)) {
    existingTools.push(tool);
    existingIds.add(normId);
    existingNames.add(normName);
    addedCount++;
  } else {
    // Enrich existing tool without creating a duplicate
    const idx = existingTools.findIndex(t => t.id.toLowerCase() === normId || t.name.toLowerCase() === normName);
    if (idx !== -1) {
      existingTools[idx] = { ...existingTools[idx], category: tool.category, tagline: tool.tagline || existingTools[idx].tagline };
    }
    skippedCount++;
  }
});

const updatedArrayStr = JSON.stringify(existingTools, null, 2);
content = content.replace(/export const staticSaasTools = \[[\s\S]*?\n\];/, `export const staticSaasTools = ${updatedArrayStr};`);

fs.writeFileSync(saasDataPath, content, 'utf8');
console.log(`Ingestion Complete! Added: ${addedCount} brand new tools | Deduplicated: ${skippedCount} existing tools | Total static tools: ${existingTools.length}`);
