const fs = require('fs');
const path = require('path');

const securityTools = [
  {
    "id": "teleport-access",
    "name": "Teleport",
    "domain": "goteleport.com",
    "category": "cybersecurity-identity",
    "tagline": "Open-source identity-native infrastructure access management for SSH, K8s, and databases",
    "description": "Teleport replaces static passwords and SSH keys with short-lived, certificate-based zero trust access across servers, Kubernetes clusters, and databases. It serves infrastructure security leads, SREs, and DevOps engineers.",
    "rating": 4.8,
    "reviewsCount": 540,
    "pricing": "Freemium",
    "websiteUrl": "https://goteleport.com",
    "affiliateUrl": "https://goteleport.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "580K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "beyondtrust-pam",
    "name": "BeyondTrust",
    "domain": "beyondtrust.com",
    "category": "cybersecurity-identity",
    "tagline": "Privileged access management and credential security suite for modern enterprises",
    "description": "BeyondTrust limits excessive user privileges, vaults admin credentials, and secures remote vendor access across IT infrastructure. It serves enterprise security directors, risk managers, and compliance auditors.",
    "rating": 4.5,
    "reviewsCount": 780,
    "pricing": "Paid",
    "websiteUrl": "https://beyondtrust.com",
    "affiliateUrl": "https://beyondtrust.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "920K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "cyberark-identity",
    "name": "CyberArk",
    "domain": "cyberark.com",
    "category": "cybersecurity-identity",
    "tagline": "Identity security platform centered on privileged access management and machine identities",
    "description": "CyberArk secures human and non-human identities accessing critical enterprise applications, cloud workloads, and secrets vaults. It is engineered for enterprise CISOs, IAM architects, and security leads.",
    "rating": 4.6,
    "reviewsCount": 890,
    "pricing": "Paid",
    "websiteUrl": "https://cyberark.com",
    "affiliateUrl": "https://cyberark.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "jumpcloud-directory",
    "name": "JumpCloud",
    "domain": "jumpcloud.com",
    "category": "cybersecurity-identity",
    "tagline": "Cloud directory platform unifying identity, device management, and single sign-on",
    "description": "JumpCloud replaces legacy Active Directory setups by unifying user identities, device MDM controls, and passwordless SSO in a single portal. It serves IT admins and security teams managing heterogeneous OS fleets.",
    "rating": 4.6,
    "reviewsCount": 1650,
    "pricing": "Freemium",
    "websiteUrl": "https://jumpcloud.com",
    "affiliateUrl": "https://jumpcloud.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "2.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "onelogin-iam",
    "name": "OneLogin",
    "domain": "onelogin.com",
    "category": "cybersecurity-identity",
    "tagline": "Enterprise workforce identity management, SSO, and adaptive MFA solution",
    "description": "OneLogin secures workforce identity access through smart multi-factor authentication, automated user provisioning, and cloud single sign-on. It serves enterprise IT managers, security operations, and HR teams.",
    "rating": 4.5,
    "reviewsCount": 1100,
    "pricing": "Free Trial",
    "websiteUrl": "https://onelogin.com",
    "affiliateUrl": "https://onelogin.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "sailpoint-governance",
    "name": "SailPoint",
    "domain": "sailpoint.com",
    "category": "cybersecurity-identity",
    "tagline": "AI-driven enterprise identity governance and lifecycle administration platform",
    "description": "SailPoint automates employee access provisioning, role certifications, and compliance monitoring across cloud and on-premise apps. It serves enterprise IAM directors and compliance leads.",
    "rating": 4.4,
    "reviewsCount": 850,
    "pricing": "Paid",
    "websiteUrl": "https://sailpoint.com",
    "affiliateUrl": "https://sailpoint.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "saviynt-identity",
    "name": "Saviynt",
    "domain": "saviynt.com",
    "category": "cybersecurity-identity",
    "tagline": "Cloud-native identity governance and privileged access management platform",
    "description": "Saviynt unifies user lifecycle governance, cloud PAM, and application risk analytics into a single cloud platform. It is built for enterprise risk management teams and corporate security leads.",
    "rating": 4.5,
    "reviewsCount": 320,
    "pricing": "Paid",
    "websiteUrl": "https://saviynt.com",
    "affiliateUrl": "https://saviynt.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "delinea-pam",
    "name": "Delinea",
    "domain": "delinea.com",
    "category": "cybersecurity-identity",
    "tagline": "Seamless privileged access management for hybrid and cloud infrastructure",
    "description": "Delinea vaults administrative passwords, enforces least-privilege policies, and secures endpoint credentials across enterprise environments. It serves IT operations and cyber risk managers.",
    "rating": 4.5,
    "reviewsCount": 620,
    "pricing": "Free Trial",
    "websiteUrl": "https://delinea.com",
    "affiliateUrl": "https://delinea.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "820K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "manageengine-pam360",
    "name": "ManageEngine PAM360",
    "domain": "manageengine.com",
    "category": "cybersecurity-identity",
    "tagline": "Unified privileged access management and privileged account governance suite",
    "description": "ManageEngine PAM360 offers privileged credential vaulting, remote session monitoring, and SSL certificate management. It is designed for IT admins, MSPs, and enterprise security departments.",
    "rating": 4.4,
    "reviewsCount": 510,
    "pricing": "Free Trial",
    "websiteUrl": "https://manageengine.com/privileged-access-management",
    "affiliateUrl": "https://manageengine.com/privileged-access-management",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "strongdm-access",
    "name": "StrongDM",
    "domain": "strongdm.com",
    "category": "cybersecurity-identity",
    "tagline": "Zero Trust infrastructure access control platform for databases, SSH, and K8s",
    "description": "StrongDM manages privileged technical access to cloud infrastructure while capturing full audit logs of terminal and database sessions. It serves DevOps engineering managers and compliance officers.",
    "rating": 4.8,
    "reviewsCount": 290,
    "pricing": "Free Trial",
    "websiteUrl": "https://strongdm.com",
    "affiliateUrl": "https://strongdm.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "340K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "opal-security",
    "name": "Opal Security",
    "domain": "opal.dev",
    "category": "cybersecurity-identity",
    "tagline": "AI-native authorization control plane and just-in-time access management platform",
    "description": "Opal automates just-in-time access requests, non-human identity management, and user access reviews across cloud infrastructure and SaaS apps. It is built for software security leads and engineering teams.",
    "rating": 4.9,
    "reviewsCount": 180,
    "pricing": "Free Trial",
    "websiteUrl": "https://www.opal.dev",
    "affiliateUrl": "https://www.opal.dev",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "150K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "sysdig-secure",
    "name": "Sysdig Secure",
    "domain": "sysdig.com",
    "category": "cybersecurity-identity",
    "tagline": "Cloud and container security platform powered by runtime Falco intelligence",
    "description": "Sysdig provides real-time cloud threat detection, vulnerability management, and container posture security built on open-source Falco. It serves cloud security engineers, SREs, and DevOps leads.",
    "rating": 4.7,
    "reviewsCount": 420,
    "pricing": "Free Trial",
    "websiteUrl": "https://sysdig.com",
    "affiliateUrl": "https://sysdig.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "aws-guardduty",
    "name": "AWS GuardDuty",
    "domain": "aws.amazon.com",
    "category": "cybersecurity-identity",
    "tagline": "Intelligent, machine-learning cloud threat detection service for AWS accounts",
    "description": "GuardDuty monitors AWS accounts and workloads continuously for unauthorized behavior, compromised S3 buckets, and malware threats. It serves AWS cloud architects and Security Operations Centers.",
    "rating": 4.7,
    "reviewsCount": 1250,
    "pricing": "Free Trial",
    "websiteUrl": "https://aws.amazon.com/guardduty",
    "affiliateUrl": "https://aws.amazon.com/guardduty",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "68.5M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "aws-security-hub",
    "name": "AWS Security Hub",
    "domain": "aws.amazon.com",
    "category": "cybersecurity-identity",
    "tagline": "Centralized cloud security posture management and compliance automation for AWS",
    "description": "AWS Security Hub aggregates security alerts and runs automated compliance posture checks against CIS and PCI-DSS benchmarks. It serves enterprise AWS cloud security administrators.",
    "rating": 4.6,
    "reviewsCount": 980,
    "pricing": "Free Trial",
    "websiteUrl": "https://aws.amazon.com/security-hub",
    "affiliateUrl": "https://aws.amazon.com/security-hub",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "68.5M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "trendmicro-cloud-one",
    "name": "Trend Micro Cloud One",
    "domain": "trendmicro.com",
    "category": "cybersecurity-identity",
    "tagline": "Comprehensive hybrid cloud security services platform for cloud workloads and containers",
    "description": "Cloud One protects cloud instances, serverless functions, container registries, and file storage against malware and runtime exploits. It serves enterprise cloud security teams and IT ops.",
    "rating": 4.5,
    "reviewsCount": 850,
    "pricing": "Free Trial",
    "websiteUrl": "https://trendmicro.com/cloudone",
    "affiliateUrl": "https://trendmicro.com/cloudone",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "tenable-io",
    "name": "Tenable.io",
    "domain": "tenable.com",
    "category": "cybersecurity-identity",
    "tagline": "Cloud-based exposure management and vulnerability assessment platform",
    "description": "Tenable.io continuously scans cloud assets, web apps, and containers to quantify and prioritize cyber risk exposures. It serves enterprise security managers and vulnerability management leads.",
    "rating": 4.6,
    "reviewsCount": 1420,
    "pricing": "Free Trial",
    "websiteUrl": "https://tenable.com/products/tenable-io",
    "affiliateUrl": "https://tenable.com/products/tenable-io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "qualys-cloud-platform",
    "name": "Qualys Cloud Platform",
    "domain": "qualys.com",
    "category": "cybersecurity-identity",
    "tagline": "Integrated cloud security, IT asset discovery, and vulnerability management",
    "description": "Qualys maps global IT assets, discovers vulnerabilities automatically, and orchestrates patch management across cloud and on-premise endpoints. It serves corporate CISOs and risk analysts.",
    "rating": 4.5,
    "reviewsCount": 1650,
    "pricing": "Free Trial",
    "websiteUrl": "https://qualys.com",
    "affiliateUrl": "https://qualys.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "rapid7-insightvm",
    "name": "Rapid7 InsightVM",
    "domain": "rapid7.com",
    "category": "cybersecurity-identity",
    "tagline": "Live vulnerability management and endpoint risk analytics platform",
    "description": "InsightVM automatically assesses IT environments for security flaws and provides context-aware remediation guidance for IT teams. It serves corporate security engineers and system administrators.",
    "rating": 4.6,
    "reviewsCount": 1250,
    "pricing": "Free Trial",
    "websiteUrl": "https://rapid7.com/products/insightvm",
    "affiliateUrl": "https://rapid7.com/products/insightvm",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.9M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "semgrep-sast",
    "name": "Semgrep",
    "domain": "semgrep.dev",
    "category": "cybersecurity-identity",
    "tagline": "Fast, lightweight open-source static analysis engine for code security (SAST)",
    "description": "Semgrep scans codebases directly in developer pipelines using customizable syntax rules to catch security bugs early. It is engineered for software developers, AppSec leads, and DevSecOps teams.",
    "rating": 4.9,
    "reviewsCount": 850,
    "pricing": "Freemium",
    "websiteUrl": "https://semgrep.dev",
    "affiliateUrl": "https://semgrep.dev",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "checkov-bridgecrew",
    "name": "Checkov",
    "domain": "checkov.io",
    "category": "cybersecurity-identity",
    "tagline": "Open-source static code analysis tool for Infrastructure as Code (IaC) security",
    "description": "Checkov scans Terraform, CloudFormation, Kubernetes, and Helm manifests to identify misconfigurations before deployment. It serves cloud engineers, DevSecOps leads, and platform architects.",
    "rating": 4.8,
    "reviewsCount": 620,
    "pricing": "Free",
    "websiteUrl": "https://checkov.io",
    "affiliateUrl": "https://checkov.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "780K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "kube-bench",
    "name": "Kube-Bench",
    "domain": "github.com",
    "category": "cybersecurity-identity",
    "tagline": "Open-source tool assessing Kubernetes cluster compliance against CIS benchmarks",
    "description": "Kube-Bench checks Kubernetes cluster node configurations automatically against official CIS Security Benchmarks. It serves Kubernetes cluster operators and cloud security auditors.",
    "rating": 4.8,
    "reviewsCount": 540,
    "pricing": "Free",
    "websiteUrl": "https://github.com/aquasecurity/kube-bench",
    "affiliateUrl": "https://github.com/aquasecurity/kube-bench",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "kube-hunter",
    "name": "Kube-Hunter",
    "domain": "github.com",
    "category": "cybersecurity-identity",
    "tagline": "Open-source tool hunting for security weaknesses in Kubernetes clusters",
    "description": "Kube-Hunter probes Kubernetes clusters from inside or outside to uncover open security issues and exploit vectors. It serves penetration testers and Kubernetes security leads.",
    "rating": 4.7,
    "reviewsCount": 380,
    "pricing": "Free",
    "websiteUrl": "https://github.com/aquasecurity/kube-hunter",
    "affiliateUrl": "https://github.com/aquasecurity/kube-hunter",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "defectdojo",
    "name": "OWASP DefectDojo",
    "domain": "defectdojo.org",
    "category": "cybersecurity-identity",
    "tagline": "Open-source vulnerability management and DevSecOps orchestration platform",
    "description": "DefectDojo aggregates security scan findings from dozens of SAST, DAST, and container scanners into a single dashboard. It serves AppSec managers, security leads, and DevSecOps teams.",
    "rating": 4.8,
    "reviewsCount": 420,
    "pricing": "Free",
    "websiteUrl": "https://defectdojo.org",
    "affiliateUrl": "https://defectdojo.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "510K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "openvas-greenbone",
    "name": "OpenVAS",
    "domain": "openvas.org",
    "category": "cybersecurity-identity",
    "tagline": "Full-featured open-source network vulnerability scanner and manager",
    "description": "OpenVAS performs authenticated and unauthenticated vulnerability testing across corporate networks and system endpoints. It serves penetration testers, sysadmins, and security auditors.",
    "rating": 4.6,
    "reviewsCount": 1150,
    "pricing": "Free",
    "websiteUrl": "https://openvas.org",
    "affiliateUrl": "https://openvas.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "nuclei-projectdiscovery",
    "name": "Nuclei",
    "domain": "nuclei.projectdiscovery.io",
    "category": "cybersecurity-identity",
    "tagline": "Fast, template-powered vulnerability scanner for web applications and infrastructure",
    "description": "Nuclei uses YAML security templates contributed by researchers to scan web applications and networks for zero-day flaws. It serves penetration testers, bug bounty hunters, and AppSec leads.",
    "rating": 4.9,
    "reviewsCount": 980,
    "pricing": "Free",
    "websiteUrl": "https://nuclei.projectdiscovery.io",
    "affiliateUrl": "https://nuclei.projectdiscovery.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "subfinder-projectdiscovery",
    "name": "Subfinder",
    "domain": "github.com",
    "category": "cybersecurity-identity",
    "tagline": "Fast passive subdomain discovery tool for attack surface mapping",
    "description": "Subfinder queries public OSINT sources to discover valid subdomains for domain targets rapidly. It is engineered for bug bounty hunters, penetration testers, and attack surface managers.",
    "rating": 4.9,
    "reviewsCount": 750,
    "pricing": "Free",
    "websiteUrl": "https://github.com/projectdiscovery/subfinder",
    "affiliateUrl": "https://github.com/projectdiscovery/subfinder",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "850K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "owasp-amass",
    "name": "OWASP Amass",
    "domain": "owasp.org",
    "category": "cybersecurity-identity",
    "tagline": "In-depth attack surface mapping and network asset discovery tool",
    "description": "Amass uses active and passive reconnaissance techniques to map external target networks and DNS infrastructure. It serves red teams, security researchers, and enterprise attack surface managers.",
    "rating": 4.8,
    "reviewsCount": 820,
    "pricing": "Free",
    "websiteUrl": "https://owasp.org/www-project-amass",
    "affiliateUrl": "https://owasp.org/www-project-amass",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "950K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "bloodhound-ad",
    "name": "BloodHound",
    "domain": "bloodhound.enterprise",
    "category": "cybersecurity-identity",
    "tagline": "Active Directory and cloud identity attack path management platform",
    "description": "BloodHound uses graph theory to map hidden relationships and permission misconfigurations inside Active Directory and Azure environments. It serves red teams, penetration testers, and AD defenders.",
    "rating": 4.9,
    "reviewsCount": 1100,
    "pricing": "Freemium",
    "websiteUrl": "https://bloodhound.enterprise",
    "affiliateUrl": "https://bloodhound.enterprise",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "caldera-mitre",
    "name": "MITRE CALDERA",
    "domain": "caldera.mitre.org",
    "category": "cybersecurity-identity",
    "tagline": "Automated adversary emulation framework for threat simulation testing",
    "description": "CALDERA executes automated adversary attack playbooks mapped to the MITRE ATT&CK framework to test blue team defenses. It serves red teams, SOC analysts, and security researchers.",
    "rating": 4.8,
    "reviewsCount": 450,
    "pricing": "Free",
    "websiteUrl": "https://caldera.mitre.org",
    "affiliateUrl": "https://caldera.mitre.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "580K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "atomic-red-team",
    "name": "Atomic Red Team",
    "domain": "atomicredteam.io",
    "category": "cybersecurity-identity",
    "tagline": "Library of simple, open-source security tests mapped to MITRE ATT&CK",
    "description": "Atomic Red Team provides small, focused test scripts that security teams run to validate specific adversary techniques and detection rules. It serves detection engineers and blue teams.",
    "rating": 4.9,
    "reviewsCount": 680,
    "pricing": "Free",
    "websiteUrl": "https://atomicredteam.io",
    "affiliateUrl": "https://atomicredteam.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "720K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "wazuh-siem",
    "name": "Wazuh",
    "domain": "wazuh.com",
    "category": "cybersecurity-identity",
    "tagline": "Open-source XDR and SIEM platform for threat detection and compliance monitoring",
    "description": "Wazuh collects host logs, tracks file integrity changes, detects rootkits, and alerts SOC teams to active threats. It serves security operations leads, sysadmins, and compliance managers.",
    "rating": 4.8,
    "reviewsCount": 1650,
    "pricing": "Free",
    "websiteUrl": "https://wazuh.com",
    "affiliateUrl": "https://wazuh.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "2.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "security-onion",
    "name": "Security Onion",
    "domain": "securityonion.net",
    "category": "cybersecurity-identity",
    "tagline": "Open-source Linux distribution for threat hunting, enterprise security monitoring, and log management",
    "description": "Security Onion combines full packet capture, intrusion detection systems (IDS), and log management in an integrated platform. It is built for SOC analysts, network defenders, and incident responders.",
    "rating": 4.8,
    "reviewsCount": 850,
    "pricing": "Free",
    "websiteUrl": "https://securityonion.net",
    "affiliateUrl": "https://securityonion.net",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "950K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "alienvault-usm",
    "name": "AT&T USM Anywhere (AlienVault)",
    "domain": "cybersecurity.att.com",
    "category": "cybersecurity-identity",
    "tagline": "Unified security management platform combining SIEM, vulnerability assessment, and threat detection",
    "description": "USM Anywhere centralizes asset discovery, vulnerability assessments, intrusion detection, and SIEM monitoring across cloud and on-premise environments. It serves corporate SOC teams.",
    "rating": 4.3,
    "reviewsCount": 620,
    "pricing": "Paid",
    "websiteUrl": "https://cybersecurity.att.com/products/usm-anywhere",
    "affiliateUrl": "https://cybersecurity.att.com/products/usm-anywhere",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "suricata-ids",
    "name": "Suricata",
    "domain": "suricata.io",
    "category": "cybersecurity-identity",
    "tagline": "High-performance open-source Network Threat Detection, IDS, and IPS engine",
    "description": "Suricata inspects live network traffic in real time to detect malicious activity, block exploits, and log network application layers. It serves network security engineers and SOC analysts.",
    "rating": 4.8,
    "reviewsCount": 920,
    "pricing": "Free",
    "websiteUrl": "https://suricata.io",
    "affiliateUrl": "https://suricata.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "850K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "zeek-ids",
    "name": "Zeek (formerly Bro)",
    "domain": "zeek.org",
    "category": "cybersecurity-identity",
    "tagline": "Open-source network security monitoring platform providing compact, structured traffic logs",
    "description": "Zeek translates raw network traffic into structured, queryable logs for threat hunting and incident response investigation. It serves SOC analysts, incident responders, and network security engineers.",
    "rating": 4.8,
    "reviewsCount": 780,
    "pricing": "Free",
    "websiteUrl": "https://zeek.org",
    "affiliateUrl": "https://zeek.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "snort-ids",
    "name": "Snort",
    "domain": "snort.org",
    "category": "cybersecurity-identity",
    "tagline": "Open-source network intrusion prevention system developed by Cisco",
    "description": "Snort performs real-time traffic analysis and packet logging to detect malicious probes and network attacks. It is a long-standing tool for network administrators and security engineers.",
    "rating": 4.5,
    "reviewsCount": 1820,
    "pricing": "Free",
    "websiteUrl": "https://snort.org",
    "affiliateUrl": "https://snort.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "openvpn-access",
    "name": "OpenVPN Access Server",
    "domain": "openvpn.net",
    "category": "cybersecurity-identity",
    "tagline": "Enterprise virtual private network solution for secure remote access",
    "description": "OpenVPN Access Server provides encrypted remote access tunnels with granular access controls and web admin portals. It serves corporate IT admins and remote workforce teams.",
    "rating": 4.6,
    "reviewsCount": 2800,
    "pricing": "Freemium",
    "websiteUrl": "https://openvpn.net",
    "affiliateUrl": "https://openvpn.net",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "pritunl-vpn",
    "name": "Pritunl",
    "domain": "pritunl.com",
    "category": "cybersecurity-identity",
    "tagline": "Open-source enterprise distributed VPN server built on OpenVPN and WireGuard",
    "description": "Pritunl simplifies managing multi-tenant OpenVPN and WireGuard servers with single sign-on integration and web UI controls. It serves IT managers and system administrators.",
    "rating": 4.8,
    "reviewsCount": 510,
    "pricing": "Freemium",
    "websiteUrl": "https://pritunl.com",
    "affiliateUrl": "https://pritunl.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "softether-vpn",
    "name": "SoftEther VPN",
    "domain": "softether.org",
    "category": "cybersecurity-identity",
    "tagline": "Open-source cross-platform multi-protocol VPN software engine",
    "description": "SoftEther supports OpenVPN, L2TP, IPsec, and SSTP protocols with high-speed throughput and firewall-traversal features. It is built for network engineers, remote workers, and sysadmins.",
    "rating": 4.7,
    "reviewsCount": 1100,
    "pricing": "Free",
    "websiteUrl": "https://softether.org",
    "affiliateUrl": "https://softether.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "nebula-slack",
    "name": "Nebula",
    "domain": "nebula.definednet.com",
    "category": "cybersecurity-identity",
    "tagline": "Open-source mutually authenticated peer-to-peer overlay network tool built by Slack",
    "description": "Nebula creates encrypted, high-performance mesh networks connecting servers and laptops across cloud providers seamlessly. It is built for cloud infrastructure leads and DevOps engineers.",
    "rating": 4.9,
    "reviewsCount": 420,
    "pricing": "Free",
    "websiteUrl": "https://nebula.definednet.com",
    "affiliateUrl": "https://nebula.definednet.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "380K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "zerotier-one",
    "name": "ZeroTier",
    "domain": "zerotier.com",
    "category": "cybersecurity-identity",
    "tagline": "Global area networking platform connecting devices into secure virtual Ethernet switches",
    "description": "ZeroTier pairs peer-to-peer encrypted networking with simple cloud management rules to connect servers, mobile devices, and IoT nodes. It serves sysadmins, home lab managers, and remote teams.",
    "rating": 4.8,
    "reviewsCount": 1820,
    "pricing": "Freemium",
    "websiteUrl": "https://zerotier.com",
    "affiliateUrl": "https://zerotier.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "cloudflare-access",
    "name": "Cloudflare Access",
    "domain": "cloudflare.com",
    "category": "cybersecurity-identity",
    "tagline": "Zero Trust network access (ZTNA) proxy protecting internal applications without VPNs",
    "description": "Cloudflare Access evaluates user identity and device posture on every request before routing traffic to private corporate web apps. It serves enterprise IT managers and security leads.",
    "rating": 4.9,
    "reviewsCount": 2100,
    "pricing": "Freemium",
    "websiteUrl": "https://cloudflare.com/products/zero-trust/access",
    "affiliateUrl": "https://cloudflare.com/products/zero-trust/access",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "42.0M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "twingate-ztna",
    "name": "Twingate",
    "domain": "twingate.com",
    "category": "cybersecurity-identity",
    "tagline": "Modern Zero Trust Network Access platform replacing corporate VPN infrastructure",
    "description": "Twingate delivers least-privilege network access to internal resources across cloud and on-premise environments without exposing public IP addresses. It serves IT admins and DevOps teams.",
    "rating": 4.9,
    "reviewsCount": 680,
    "pricing": "Freemium",
    "websiteUrl": "https://twingate.com",
    "affiliateUrl": "https://twingate.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "perimeter81-sse",
    "name": "Perimeter 81",
    "domain": "perimeter81.com",
    "category": "cybersecurity-identity",
    "tagline": "Converged cloud network security and Zero Trust Network Access platform",
    "description": "Perimeter 81 replaces legacy VPN hardware with cloud firewalls, ZTNA access controls, and secure web gateways. It is built for IT managers securing hybrid workforces.",
    "rating": 4.6,
    "reviewsCount": 890,
    "pricing": "Paid",
    "websiteUrl": "https://perimeter81.com",
    "affiliateUrl": "https://perimeter81.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "banyan-security",
    "name": "Banyan Security",
    "domain": "banyansecurity.io",
    "category": "cybersecurity-identity",
    "tagline": "Zero Trust Network Access featuring continuous identity and device trust verification",
    "description": "Banyan Security grants least-privilege access to applications and infrastructure based on real-time device health and identity checks. It serves enterprise IT and security teams.",
    "rating": 4.7,
    "reviewsCount": 180,
    "pricing": "Free Trial",
    "websiteUrl": "https://banyansecurity.io",
    "affiliateUrl": "https://banyansecurity.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "210K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "elisity-segmentation",
    "name": "Elisity",
    "domain": "elisity.com",
    "category": "cybersecurity-identity",
    "tagline": "Identity-based microsegmentation platform securing enterprise IoT, OT, and IT environments",
    "description": "Elisity enforces least-privilege access policies dynamically for enterprise devices and assets without requiring network hardware changes. It serves enterprise CISOs, OT leads, and network security architects.",
    "rating": 4.8,
    "reviewsCount": 140,
    "pricing": "Paid",
    "websiteUrl": "https://www.elisity.com",
    "affiliateUrl": "https://www.elisity.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "120K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "axonius-cam",
    "name": "Axonius",
    "domain": "axonius.com",
    "category": "cybersecurity-identity",
    "tagline": "Cybersecurity asset management and SaaS management platform",
    "description": "Axonius correlates asset inventories across devices, cloud instances, and users to surface security coverage gaps automatically. It serves corporate CISOs, SecOps leads, and IT asset managers.",
    "rating": 4.7,
    "reviewsCount": 310,
    "pricing": "Paid",
    "websiteUrl": "https://axonius.com",
    "affiliateUrl": "https://axonius.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "420K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "telemetrydeck-analytics",
    "name": "TelemetryDeck",
    "domain": "telemetrydeck.com",
    "category": "cybersecurity-identity",
    "tagline": "Privacy-first lightweight analytics service for iOS, Android, and web applications",
    "description": "TelemetryDeck provides anonymized app usage metrics and user insights while strictly respecting end-user data privacy laws. It serves privacy-conscious software developers and mobile app creators.",
    "rating": 4.9,
    "reviewsCount": 210,
    "pricing": "Freemium",
    "websiteUrl": "https://telemetrydeck.com",
    "affiliateUrl": "https://telemetrydeck.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "280K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "hashicorp-sentinel",
    "name": "HashiCorp Sentinel",
    "domain": "hashicorp.com",
    "category": "cybersecurity-identity",
    "tagline": "Policy-as-code framework for enforcing security guardrails across cloud automation",
    "description": "Sentinel enforces fine-grained security policies and compliance rules across HashiCorp cloud infrastructure provisioning. It serves enterprise SecOps leads and cloud platform architects.",
    "rating": 4.7,
    "reviewsCount": 280,
    "pricing": "Paid",
    "websiteUrl": "https://hashicorp.com/sentinel",
    "affiliateUrl": "https://hashicorp.com/sentinel",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.8M",
    "isFreeTier": false,
    "isOpenSource": false
  }
];

const targetPath = path.join(__dirname, '../src/data/saasData.jsx');
let content = fs.readFileSync(targetPath, 'utf8');

// Ensure saasCategories has cybersecurity-identity
if (!content.includes('"cybersecurity-identity"')) {
  console.log('Adding cybersecurity-identity category to saasCategories...');
  content = content.replace(
    '  { "id": "open-source-self-hosted", "label": "Open-Source & Self-Hosted" }',
    '  { "id": "open-source-self-hosted", "label": "Open-Source & Self-Hosted" },\n  { "id": "cybersecurity-identity", "label": "Cybersecurity & Identity" }'
  );
}

// Build existing domains set
const existingDomains = new Set();
const existingNames = new Set();
const domainMatches = content.matchAll(/"domain":\s*"([^"]+)"/g);
for (const match of domainMatches) {
  existingDomains.add(match[1].toLowerCase());
}
const nameMatches = content.matchAll(/"name":\s*"([^"]+)"/g);
for (const match of nameMatches) {
  existingNames.add(match[1].toLowerCase());
}

console.log(`Initial DB has ${existingDomains.size} domains and ${existingNames.size} tool names.`);

const defaultFeatures = [
  "Zero Trust Security",
  "IAM & Compliance",
  "Threat Intelligence",
  "Enterprise Encryption"
];

const newToolsToInsert = [];
for (const tool of securityTools) {
  const normDomain = tool.domain.toLowerCase();
  const normName = tool.name.toLowerCase();

  const isSharedDomain = ['github.com', 'aws.amazon.com', 'cloudflare.com', 'manageengine.com', 'trendmicro.com', 'tenable.com', 'rapid7.com', 'owasp.org', 'cybersecurity.att.com', 'hashicorp.com'].includes(normDomain);

  const isDuplicate = !isSharedDomain
    ? (existingDomains.has(normDomain) || existingNames.has(normName))
    : existingNames.has(normName);

  if (isDuplicate) {
    console.log(`[SKIP DUPLICATE] ${tool.name} (${tool.domain})`);
    continue;
  }

  tool.features = defaultFeatures;
  newToolsToInsert.push(tool);
  if (!isSharedDomain) existingDomains.add(normDomain);
  existingNames.add(normName);
}

console.log(`Found ${newToolsToInsert.length} NEW Security tools to insert. Skipped ${securityTools.length - newToolsToInsert.length} duplicates.`);

if (newToolsToInsert.length > 0) {
  const formattedTools = newToolsToInsert.map(t => JSON.stringify(t, null, 4)).join(',\n');
  const insertionMarker = 'export const staticSaasTools = [\n';
  content = content.replace(insertionMarker, insertionMarker + formattedTools + ',\n');
  fs.writeFileSync(targetPath, content, 'utf8');
  console.log(`Successfully ingested ${newToolsToInsert.length} new Security tools into src/data/saasData.jsx!`);
} else {
  console.log('No new tools to insert.');
}
