const fs = require('fs');
const path = require('path');

const newTools = [
  {
    "id": "vimeo",
    "name": "Vimeo",
    "domain": "vimeo.com",
    "category": "video-tools",
    "tagline": "Professional video hosting, collaboration, and high-quality streaming suite",
    "description": "Vimeo provides ad-free video hosting, customizable video players, team review tools, and live streaming capabilities. It serves creative filmmakers, corporate communications, and digital agencies.",
    "rating": 4.6,
    "reviewsCount": 3800,
    "pricing": "Freemium",
    "websiteUrl": "https://vimeo.com",
    "affiliateUrl": "https://vimeo.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "24.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "wistia",
    "name": "Wistia",
    "domain": "wistia.com",
    "category": "video-tools",
    "tagline": "Video marketing and hosting platform designed to generate B2B leads",
    "description": "Wistia provides customizable video players, interactive lead capture forms, video SEO tools, and detailed viewer heatmaps. It is engineered specifically for B2B marketing teams and content strategists.",
    "rating": 4.7,
    "reviewsCount": 1420,
    "pricing": "Freemium",
    "websiteUrl": "https://wistia.com",
    "affiliateUrl": "https://wistia.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "3.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "vidyard",
    "name": "Vidyard",
    "domain": "vidyard.com",
    "category": "video-tools",
    "tagline": "Video messaging and video hosting platform for B2B sales and prospecting",
    "description": "Vidyard enables sales reps to record screen walkthroughs, send personalized video emails, and track prospect view analytics directly inside CRMs. It serves SDRs, sales reps, and customer success teams.",
    "rating": 4.5,
    "reviewsCount": 1650,
    "pricing": "Freemium",
    "websiteUrl": "https://vidyard.com",
    "affiliateUrl": "https://vidyard.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "2.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "loom",
    "name": "Loom",
    "domain": "loom.com",
    "category": "video-tools",
    "tagline": "Async video messaging tool to capture screen and camera updates instantly",
    "description": "Loom records screen and camera video clips with instant cloud link generation for fast, meeting-free asynchronous communication. It is built for remote teams, product managers, and distributed workforces.",
    "rating": 4.8,
    "reviewsCount": 2100,
    "pricing": "Freemium",
    "websiteUrl": "https://loom.com",
    "affiliateUrl": "https://loom.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "18.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "descript",
    "name": "Descript",
    "domain": "descript.com",
    "category": "video-tools",
    "tagline": "AI-powered text-based video and audio editor that works like a doc",
    "description": "Descript transcribes video recordings automatically, allowing creators to edit video timelines by simply deleting or editing written text transcripts. It serves podcasters, YouTubers, and course creators.",
    "rating": 4.8,
    "reviewsCount": 1650,
    "pricing": "Freemium",
    "websiteUrl": "https://descript.com",
    "affiliateUrl": "https://descript.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "6.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "capcut",
    "name": "CapCut",
    "domain": "capcut.com",
    "category": "video-tools",
    "tagline": "All-in-one desktop and mobile video editor with trending effects and AI tools",
    "description": "CapCut delivers multi-track timeline editing, auto-captioning, background removal, and speed ramping for social media creators. It is designed for TikTokers, Instagram Reels creators, and digital editors.",
    "rating": 4.7,
    "reviewsCount": 8900,
    "pricing": "Freemium",
    "websiteUrl": "https://capcut.com",
    "affiliateUrl": "https://capcut.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "45.0M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "veed-io",
    "name": "VEED.IO",
    "domain": "veed.io",
    "category": "video-tools",
    "tagline": "Online video suite for auto-subtitling, screen recording, and social edits",
    "description": "VEED.IO provides browser-based video editing, screen recording, voiceover generation, and automatic subtitle translation. It serves social media managers, marketers, and video creators.",
    "rating": 4.6,
    "reviewsCount": 2400,
    "pricing": "Freemium",
    "websiteUrl": "https://veed.io",
    "affiliateUrl": "https://veed.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "12.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "obs-studio",
    "name": "OBS Studio",
    "domain": "obsproject.com",
    "category": "video-tools",
    "tagline": "Free, open-source video recording and live streaming software",
    "description": "OBS Studio offers high-performance real-time video capture, scene composition, audio mixing, and broadcast streaming. It is built for live streamers, gamers, and open-source video producers.",
    "rating": 4.8,
    "reviewsCount": 4500,
    "pricing": "Free",
    "websiteUrl": "https://obsproject.com",
    "affiliateUrl": "https://obsproject.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "14.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "camtasia",
    "name": "Camtasia",
    "domain": "techsmith.com/camtasia.html",
    "category": "video-tools",
    "tagline": "All-in-one screen recorder and timeline video editor for tutorial training",
    "description": "Camtasia combines multi-track screen recording with cursor effects, annotations, quizzes, and timeline editing. It is engineered for corporate trainers, educators, and instructional designers.",
    "rating": 4.6,
    "reviewsCount": 2100,
    "pricing": "Free Trial",
    "websiteUrl": "https://techsmith.com/camtasia.html",
    "affiliateUrl": "https://techsmith.com/camtasia.html",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "davinci-resolve",
    "name": "DaVinci Resolve",
    "domain": "blackmagicdesign.com/products/davinciresolve",
    "category": "video-tools",
    "tagline": "Professional video editing, advanced color grading, motion graphics, and audio post-production",
    "description": "DaVinci Resolve integrates non-linear video editing, industry-standard color correction, Fusion visual effects, and Fairlight audio tools. It is built for Hollywood filmmakers, post-production studios, and video editors.",
    "rating": 4.8,
    "reviewsCount": 3800,
    "pricing": "Freemium",
    "websiteUrl": "https://blackmagicdesign.com/products/davinciresolve",
    "affiliateUrl": "https://blackmagicdesign.com/products/davinciresolve",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "9.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "adobe-premiere-pro",
    "name": "Adobe Premiere Pro",
    "domain": "adobe.com/products/premiere.html",
    "category": "video-tools",
    "tagline": "Industry-leading timeline video editing software for film, TV, and web",
    "description": "Adobe Premiere Pro offers high-performance multi-cam editing, Lumetri color controls, speech-to-text editing, and Creative Cloud integrations. It serves professional video editors, agencies, and filmmakers.",
    "rating": 4.6,
    "reviewsCount": 5100,
    "pricing": "Paid",
    "websiteUrl": "https://adobe.com/products/premiere.html",
    "affiliateUrl": "https://adobe.com/products/premiere.html",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "38.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "clipchamp",
    "name": "Microsoft Clipchamp",
    "domain": "clipchamp.com",
    "category": "video-tools",
    "tagline": "User-friendly web and Windows video editor with stock templates and screen capture",
    "description": "Clipchamp provides simple timeline video trimming, text overlays, auto-captions, and screen recording directly in browser tabs. It is built for small business marketers, educators, and casual video creators.",
    "rating": 4.5,
    "reviewsCount": 1850,
    "pricing": "Freemium",
    "websiteUrl": "https://clipchamp.com",
    "affiliateUrl": "https://clipchamp.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "14.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "riverside-fm",
    "name": "Riverside.fm",
    "domain": "riverside.fm",
    "category": "video-tools",
    "tagline": "Local 4K video and audio studio recording platform for podcasts and interviews",
    "description": "Riverside records uncompressed 4K video and separate audio tracks locally on each participant's device to bypass web internet glitches. It serves podcasters, journalists, and remote video teams.",
    "rating": 4.8,
    "reviewsCount": 1250,
    "pricing": "Freemium",
    "websiteUrl": "https://riverside.fm",
    "affiliateUrl": "https://riverside.fm",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "4.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "screen-studio",
    "name": "Screen Studio",
    "domain": "screen.studio",
    "category": "video-tools",
    "tagline": "Cinematic screen recording app with automated smooth zooms and cursor effects",
    "description": "Screen Studio automatically applies smooth mouse tracking, background blurring, and dynamic zooms to desktop screen captures. It is engineered for Mac software developers, product managers, and creators.",
    "rating": 4.9,
    "reviewsCount": 890,
    "pricing": "Paid",
    "websiteUrl": "https://screen.studio",
    "affiliateUrl": "https://screen.studio",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "screenpal",
    "name": "ScreenPal (formerly Screencast-O-Matic)",
    "domain": "screenpal.com",
    "category": "video-tools",
    "tagline": "Easy screen recorder, video editor, and image capture tool for educators",
    "description": "ScreenPal provides intuitive screen capture, webcam recording, video trimming, and instant video hosting. It is popular among teachers, students, and corporate trainers.",
    "rating": 4.6,
    "reviewsCount": 1100,
    "pricing": "Freemium",
    "websiteUrl": "https://screenpal.com",
    "affiliateUrl": "https://screenpal.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.9M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "invideo",
    "name": "InVideo",
    "domain": "invideo.io",
    "category": "video-tools",
    "tagline": "AI prompt-to-video generator with scripted narration and stock media",
    "description": "InVideo turns written scripts and topic prompts into fully assembled video presentations with stock clips, AI voiceovers, and captions. It serves digital marketers, YouTube creators, and agencies.",
    "rating": 4.6,
    "reviewsCount": 2850,
    "pricing": "Freemium",
    "websiteUrl": "https://invideo.io",
    "affiliateUrl": "https://invideo.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "8.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "runway",
    "name": "Runway",
    "domain": "runwayml.com",
    "category": "video-tools",
    "tagline": "Generative AI video creation studio and advanced motion editing suite",
    "description": "Runway offers text-to-video, image-to-video, camera control, and generative visual effects for video projects. It is built for creative filmmakers, visual artists, and modern video editors.",
    "rating": 4.8,
    "reviewsCount": 2100,
    "pricing": "Freemium",
    "websiteUrl": "https://runwayml.com",
    "affiliateUrl": "https://runwayml.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "12.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "synthesia",
    "name": "Synthesia",
    "domain": "synthesia.io",
    "category": "video-tools",
    "tagline": "AI avatar video platform converting scripts into presenter-led videos",
    "description": "Synthesia generates studio-grade video content featuring photorealistic synthetic avatars speaking in 140+ languages. It serves corporate L&D teams, HR trainers, and customer education leads.",
    "rating": 4.7,
    "reviewsCount": 1850,
    "pricing": "Paid",
    "websiteUrl": "https://synthesia.io",
    "affiliateUrl": "https://synthesia.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "6.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "heygen",
    "name": "HeyGen",
    "domain": "heygen.com",
    "category": "video-tools",
    "tagline": "AI video generation, avatar creation, and automated video translation",
    "description": "HeyGen creates avatar-led video messages and translates spoken video dialogue with accurate lip-syncing across languages. It serves sales teams, marketing agencies, and global creators.",
    "rating": 4.8,
    "reviewsCount": 1620,
    "pricing": "Freemium",
    "websiteUrl": "https://heygen.com",
    "affiliateUrl": "https://heygen.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "11.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "vdocipher",
    "name": "VdoCipher",
    "domain": "vdocipher.com",
    "category": "video-tools",
    "tagline": "Secure DRM video hosting with dynamic watermarking to prevent piracy",
    "description": "VdoCipher provides Hollywood-grade DRM encryption and user-specific dynamic watermarking for premium video content. It is built for online course creators, edtech platforms, and media publishers.",
    "rating": 4.7,
    "reviewsCount": 380,
    "pricing": "Free Trial",
    "websiteUrl": "https://vdocipher.com",
    "affiliateUrl": "https://vdocipher.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "sprout-video",
    "name": "SproutVideo",
    "domain": "sproutvideo.com",
    "category": "video-tools",
    "tagline": "Secure business video hosting platform with analytics and lead capture",
    "description": "SproutVideo offers secure cloud video hosting, password-protected video shares, player customization, and detailed engagement metrics. It serves small businesses, agencies, and enterprise teams.",
    "rating": 4.6,
    "reviewsCount": 320,
    "pricing": "Free Trial",
    "websiteUrl": "https://sproutvideo.com",
    "affiliateUrl": "https://sproutvideo.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "jw-player",
    "name": "JW Player",
    "domain": "jwplayer.com",
    "category": "video-tools",
    "tagline": "Enterprise video streaming, HTML5 video player, and ad monetization engine",
    "description": "JW Player delivers scalable video streaming infrastructure, multi-device HTML5 playback, and programmatic ad insertion. It serves digital publishers, media companies, and broadcasting networks.",
    "rating": 4.4,
    "reviewsCount": 650,
    "pricing": "Paid",
    "websiteUrl": "https://jwplayer.com",
    "affiliateUrl": "https://jwplayer.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "dubb",
    "name": "Dubb",
    "domain": "dubb.com",
    "category": "video-tools",
    "tagline": "Interactive video sales operating system and video email marketing engine",
    "description": "Dubb combines screen recording with interactive call-to-action buttons, booking calendars, and automated video email campaigns. It is tailored for sales executives, realtors, and agencies.",
    "rating": 4.7,
    "reviewsCount": 510,
    "pricing": "Freemium",
    "websiteUrl": "https://dubb.com",
    "affiliateUrl": "https://dubb.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "520K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "mindstamp",
    "name": "Mindstamp",
    "domain": "mindstamp.com",
    "category": "video-tools",
    "tagline": "Interactive video platform for adding clickable buttons, quizzes, and hotspots",
    "description": "Mindstamp turns standard video files into interactive experiences by overlaying clickable links, branching paths, questions, and forms. It serves corporate trainers, marketers, and educators.",
    "rating": 4.8,
    "reviewsCount": 190,
    "pricing": "Free Trial",
    "websiteUrl": "https://mindstamp.com",
    "affiliateUrl": "https://mindstamp.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "210K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "h5p",
    "name": "H5P",
    "domain": "h5p.org",
    "category": "video-tools",
    "tagline": "Open-source interactive video, quiz, and HTML5 content creation framework",
    "description": "H5P empowers educators to add interactive questions, branching choices, and pop-up information directly onto video playback. It is engineered for instructional designers, LMS admins, and teachers.",
    "rating": 4.7,
    "reviewsCount": 420,
    "pricing": "Free",
    "websiteUrl": "https://h5p.org",
    "affiliateUrl": "https://h5p.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "opus-clip",
    "name": "OpusClip",
    "domain": "opus.pro",
    "category": "video-tools",
    "tagline": "AI video repurposing tool converting long videos into viral short-form clips",
    "description": "OpusClip analyzes long recordings to extract, reframe, caption, and score short vertical clips for TikTok, Shorts, and Reels. It serves podcasters, YouTubers, and social media managers.",
    "rating": 4.7,
    "reviewsCount": 1950,
    "pricing": "Freemium",
    "websiteUrl": "https://opus.pro",
    "affiliateUrl": "https://opus.pro",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "7.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "captions-app",
    "name": "Captions",
    "domain": "captions.ai",
    "category": "video-tools",
    "tagline": "AI video editing studio for animated subtitles, eye contact, and dubbing",
    "description": "Captions automates dynamic subtitle styling, AI lip-sync dubbing, noise cleanup, and eye contact alignment on mobile and desktop. It serves social influencers, educators, and video creators.",
    "rating": 4.8,
    "reviewsCount": 1410,
    "pricing": "Paid",
    "websiteUrl": "https://captions.ai",
    "affiliateUrl": "https://captions.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "submagic",
    "name": "Submagic",
    "domain": "submagic.co",
    "category": "video-tools",
    "tagline": "AI captions, b-roll insertion, and sound effects for short vertical videos",
    "description": "Submagic generates trending captions, auto-inserts stock B-roll clips, and adds sound effects to short-form social videos. It is built for TikTokers, Instagram Reels creators, and marketers.",
    "rating": 4.7,
    "reviewsCount": 820,
    "pricing": "Paid",
    "websiteUrl": "https://submagic.co",
    "affiliateUrl": "https://submagic.co",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "final-cut-pro",
    "name": "Final Cut Pro",
    "domain": "apple.com/final-cut-pro",
    "category": "video-tools",
    "tagline": "Apple's professional non-linear video editing software optimized for Mac",
    "description": "Final Cut Pro features a magnetic timeline, object tracking, Metal graphics acceleration, and optimized 8K video rendering. It is engineered exclusively for macOS video editors and content creators.",
    "rating": 4.7,
    "reviewsCount": 3200,
    "pricing": "Paid",
    "websiteUrl": "https://apple.com/final-cut-pro",
    "affiliateUrl": "https://apple.com/final-cut-pro",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "18.5M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "cyberlink-powerdirector",
    "name": "CyberLink PowerDirector",
    "domain": "cyberlink.com/products/powerdirector-video-editing-software",
    "category": "video-tools",
    "tagline": "Feature-packed consumer video editor with motion tracking and AI tools",
    "description": "PowerDirector offers multi-cam editing, screen recording, AI motion tracking, color grading, and speed controls. It serves prosumers, YouTube creators, and video enthusiasts.",
    "rating": 4.5,
    "reviewsCount": 2400,
    "pricing": "Free Trial",
    "websiteUrl": "https://cyberlink.com/products/powerdirector-video-editing-software",
    "affiliateUrl": "https://cyberlink.com/products/powerdirector-video-editing-software",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "5.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "filmora",
    "name": "Wondershare Filmora",
    "domain": "filmora.wondershare.com",
    "category": "video-tools",
    "tagline": "Intuitive video editor with built-in templates, effects, and AI tools",
    "description": "Filmora combines easy drag-and-drop timeline editing with AI smart cutout, green screen keying, and audio ducking. It is built for casual video creators, YouTubers, and small business owners.",
    "rating": 4.5,
    "reviewsCount": 4100,
    "pricing": "Freemium",
    "websiteUrl": "https://filmora.wondershare.com",
    "affiliateUrl": "https://filmora.wondershare.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "11.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "shotcut",
    "name": "Shotcut",
    "domain": "shotcut.org",
    "category": "video-tools",
    "tagline": "Free, open-source cross-platform video editing software",
    "description": "Shotcut delivers multi-format timeline video editing, audio mixing, filter effects, and native 4K support without subscription fees. It is built for open-source users and budget video editors.",
    "rating": 4.5,
    "reviewsCount": 1100,
    "pricing": "Free",
    "websiteUrl": "https://shotcut.org",
    "affiliateUrl": "https://shotcut.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "kdenlive",
    "name": "Kdenlive",
    "domain": "kdenlive.org",
    "category": "video-tools",
    "tagline": "Open-source non-linear video editor built on MLT framework and KDE",
    "description": "Kdenlive provides multi-track video editing, customizable interface layouts, keyframeable effects, and titling tools. It serves Linux and cross-platform video editors seeking open-source tools.",
    "rating": 4.6,
    "reviewsCount": 620,
    "pricing": "Free",
    "websiteUrl": "https://kdenlive.org",
    "affiliateUrl": "https://kdenlive.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "screencastify",
    "name": "Screencastify",
    "domain": "screencastify.com",
    "category": "video-tools",
    "tagline": "Chrome extension screen recorder and interactive video assessment tool for education",
    "description": "Screencastify allows teachers and students to record, edit, and embed interactive quiz questions directly onto browser recordings. It is built for K-12 educators and Google Classroom users.",
    "rating": 4.5,
    "reviewsCount": 1850,
    "pricing": "Freemium",
    "websiteUrl": "https://screencastify.com",
    "affiliateUrl": "https://screencastify.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "zight",
    "name": "Zight (formerly CloudApp)",
    "domain": "zight.com",
    "category": "video-tools",
    "tagline": "Instant screen recorder, GIF generator, and visual communication app",
    "description": "Zight captures quick video messages, animated GIFs, and annotated screenshots with auto-copied sharing links. It serves customer support teams, software engineers, and sales reps.",
    "rating": 4.6,
    "reviewsCount": 1100,
    "pricing": "Freemium",
    "websiteUrl": "https://zight.com",
    "affiliateUrl": "https://zight.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "claap",
    "name": "Claap",
    "domain": "claap.io",
    "category": "video-tools",
    "tagline": "Async video workspace, AI meeting recorder, and central video wiki",
    "description": "Claap records screen updates and meetings, auto-generating transcripts, summaries, and timestamped comment threads. It serves product designers, engineering leads, and remote teams.",
    "rating": 4.8,
    "reviewsCount": 190,
    "pricing": "Freemium",
    "websiteUrl": "https://claap.io",
    "affiliateUrl": "https://claap.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "210K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "snagit",
    "name": "TechSmith Snagit",
    "domain": "techsmith.com/screen-capture.html",
    "category": "video-tools",
    "tagline": "Screen capture and short video recording software for documentation",
    "description": "Snagit captures screenshots and short screen recordings, adding visual callouts and step annotations. It is built for technical writers, IT support desks, and trainers.",
    "rating": 4.7,
    "reviewsCount": 2400,
    "pricing": "Paid",
    "websiteUrl": "https://techsmith.com/screen-capture.html",
    "affiliateUrl": "https://techsmith.com/screen-capture.html",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "gumlet",
    "name": "Gumlet",
    "domain": "gumlet.com",
    "category": "video-tools",
    "tagline": "Secure video hosting, streaming infrastructure, and video analytics platform",
    "description": "Gumlet offers DRM-protected video hosting, adaptive bit-rate streaming, and granular viewer analytics. It serves online course creators, OTT platforms, and SaaS developers.",
    "rating": 4.8,
    "reviewsCount": 210,
    "pricing": "Freemium",
    "websiteUrl": "https://gumlet.com",
    "affiliateUrl": "https://gumlet.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "340K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "bunnet-stream",
    "name": "Bunny Stream",
    "domain": "bunny.net/stream",
    "category": "video-tools",
    "tagline": "Ultra-fast, affordable video hosting and edge delivery network",
    "description": "Bunny Stream handles video encoding, storage, global CDN streaming, and media player embedding at low cost. It is designed for developers, web masters, and online learning platforms.",
    "rating": 4.9,
    "reviewsCount": 650,
    "pricing": "Paid",
    "websiteUrl": "https://bunny.net/stream",
    "affiliateUrl": "https://bunny.net/stream",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "2.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "api-video",
    "name": "api.video",
    "domain": "api.video",
    "category": "video-tools",
    "tagline": "Developer API infrastructure for live streaming and video-on-demand integration",
    "description": "api.video provides REST APIs and SDKs to encode, host, stream, and play video directly within software applications. It serves software engineering teams and product developers.",
    "rating": 4.8,
    "reviewsCount": 140,
    "pricing": "Freemium",
    "websiteUrl": "https://api.video",
    "affiliateUrl": "https://api.video",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "180K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "mux",
    "name": "Mux",
    "domain": "mux.com",
    "category": "video-tools",
    "tagline": "Developer-first video API for live and on-demand video streaming",
    "description": "Mux gives developers API endpoints to ingest raw video, stream via adaptive HLS, and track real-time QoE metrics. It is engineered for software developers and video platform architects.",
    "rating": 4.8,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://mux.com",
    "affiliateUrl": "https://mux.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "850K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "cloudflare-stream",
    "name": "Cloudflare Stream",
    "domain": "cloudflare.com/products/cloudflare-stream",
    "category": "video-tools",
    "tagline": "Global video streaming, encoding, and storage platform powered by Cloudflare",
    "description": "Cloudflare Stream simplifies video delivery by combining encoding, global CDN distribution, and HTML5 players into a single API. It serves web developers and digital media platforms.",
    "rating": 4.7,
    "reviewsCount": 510,
    "pricing": "Paid",
    "websiteUrl": "https://cloudflare.com/products/cloudflare-stream",
    "affiliateUrl": "https://cloudflare.com/products/cloudflare-stream",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "42.0M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "vizard-ai",
    "name": "Vizard",
    "domain": "vizard.ai",
    "category": "video-tools",
    "tagline": "AI video clipper converting long recordings into social media shorts",
    "description": "Vizard splits webinars and podcasts into social-ready video clips with custom template layouts and subtitles. It serves remote teams, podcasters, and content marketers.",
    "rating": 4.6,
    "reviewsCount": 520,
    "pricing": "Freemium",
    "websiteUrl": "https://vizard.ai",
    "affiliateUrl": "https://vizard.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "klap-app",
    "name": "Klap",
    "domain": "klap.app",
    "category": "video-tools",
    "tagline": "Turn long YouTube videos into TikToks and Shorts automatically",
    "description": "Klap detects viral video moments, applies dynamic face reframing, and adds animated captions for short-form clips. It serves social media managers and video creators.",
    "rating": 4.7,
    "reviewsCount": 610,
    "pricing": "Freemium",
    "websiteUrl": "https://klap.app",
    "affiliateUrl": "https://klap.app",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "munch",
    "name": "Munch",
    "domain": "getmunch.com",
    "category": "video-tools",
    "tagline": "AI video repurposing platform guided by social marketing trend data",
    "description": "Munch extracts engaging snippets from long recordings based on social search trends and auto-crops for vertical feeds. It serves media buyers, agencies, and brand marketers.",
    "rating": 4.7,
    "reviewsCount": 780,
    "pricing": "Paid",
    "websiteUrl": "https://getmunch.com",
    "affiliateUrl": "https://getmunch.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "tella-tv",
    "name": "Tella",
    "domain": "tella.tv",
    "category": "video-tools",
    "tagline": "Browser-based video recorder and editor for product demos and courses",
    "description": "Tella captures screen and camera footage simultaneously, offering instant layout edits and web video link sharing. It is built for online course creators, founders, and educators.",
    "rating": 4.8,
    "reviewsCount": 310,
    "pricing": "Freemium",
    "websiteUrl": "https://tella.tv",
    "affiliateUrl": "https://tella.tv",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "jam-dev",
    "name": "Jam",
    "domain": "jam.dev",
    "category": "video-tools",
    "tagline": "One-click screen recording and automated bug reporting tool for developers",
    "description": "Jam logs video recordings alongside browser console logs, network requests, and device specs in a single shareable link. It serves QA testers, product managers, and software engineers.",
    "rating": 4.9,
    "reviewsCount": 580,
    "pricing": "Freemium",
    "websiteUrl": "https://jam.dev",
    "affiliateUrl": "https://jam.dev",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "820K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "clipdrop-uncrop",
    "name": "Clipdrop",
    "domain": "clipdrop.co",
    "category": "video-tools",
    "tagline": "AI visual editing ecosystem for image and video asset background editing",
    "description": "Clipdrop provides AI-powered background removal, lighting adjustments, and image/video asset enhancement. It is tailored for digital artists, e-commerce sellers, and video creators.",
    "rating": 4.7,
    "reviewsCount": 1250,
    "pricing": "Freemium",
    "websiteUrl": "https://clipdrop.co",
    "affiliateUrl": "https://clipdrop.co",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "playable",
    "name": "Playable",
    "domain": "playable.video",
    "category": "video-tools",
    "tagline": "Video email marketing platform that embeds autoplaying video into email campaigns",
    "description": "Playable enables marketers to stream high-quality, autoplaying video clips directly inside HTML email campaigns across all email clients. It serves e-commerce brands and email marketers.",
    "rating": 4.6,
    "reviewsCount": 180,
    "pricing": "Free Trial",
    "websiteUrl": "https://playable.video",
    "affiliateUrl": "https://playable.video",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "150K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "videask",
    "name": "Videoask by Typeform",
    "domain": "videoask.com",
    "category": "video-tools",
    "tagline": "Interactive video forms and asynchronous video conversation builder",
    "description": "Videoask creates face-to-face video funnels where respondents answer via video, audio, or multiple-choice buttons. It is designed for recruitment, lead qualification, and customer feedback.",
    "rating": 4.7,
    "reviewsCount": 620,
    "pricing": "Freemium",
    "websiteUrl": "https://videoask.com",
    "affiliateUrl": "https://videoask.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.8M",
    "isFreeTier": true,
    "isOpenSource": false
  }
];

const saasDataPath = path.join(__dirname, '..', 'src', 'data', 'saasData.jsx');
let content = fs.readFileSync(saasDataPath, 'utf8');

const match = content.match(/export const staticSaasTools = (\[[\s\S]*?\n\]);/);
if (!match) {
  console.error('Could not find staticSaasTools in saasData.jsx');
  process.exit(1);
}

let existingTools = JSON.parse(match[1]);

const existingIds = new Set(existingTools.map(t => t.id.toLowerCase()));
const existingNames = new Set(existingTools.map(t => t.name.toLowerCase()));

let addedCount = 0;
let skippedCount = 0;

newTools.forEach(tool => {
  const normId = tool.id.toLowerCase();
  const normName = tool.name.toLowerCase();

  if (!existingIds.has(normId) && !existingNames.has(normName)) {
    existingTools.push(tool);
    existingIds.add(normId);
    existingNames.add(normName);
    addedCount++;
  } else {
    // Enrich existing tool without creating a duplicate
    const idx = existingTools.findIndex(t => t.id.toLowerCase() === normId || t.name.toLowerCase() === normName);
    if (idx !== -1) {
      existingTools[idx] = { ...existingTools[idx], category: tool.category, tagline: tool.tagline || existingTools[idx].tagline };
    }
    skippedCount++;
  }
});

const updatedArrayStr = JSON.stringify(existingTools, null, 2);
content = content.replace(/export const staticSaasTools = \[[\s\S]*?\n\];/, `export const staticSaasTools = ${updatedArrayStr};`);

fs.writeFileSync(saasDataPath, content, 'utf8');
console.log(`Ingestion Complete! Added: ${addedCount} brand new tools | Deduplicated: ${skippedCount} existing tools | Total static tools: ${existingTools.length}`);
