const fs = require('fs');
const path = require('path');

const newTools = [
  {
    "id": "aws",
    "name": "Amazon Web Services (AWS)",
    "domain": "aws.amazon.com",
    "category": "hosting-cloud",
    "tagline": "Comprehensive enterprise cloud computing platform and infrastructure services",
    "description": "AWS provides a vast ecosystem of cloud infrastructure services including compute, storage, databases, machine learning, and networking. It is built for businesses of all sizes, from early-stage startups to Global 2000 enterprises.",
    "rating": 4.7,
    "reviewsCount": 8500,
    "pricing": "Freemium",
    "websiteUrl": "https://aws.amazon.com",
    "affiliateUrl": "https://aws.amazon.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "68.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "google-cloud",
    "name": "Google Cloud Platform (GCP)",
    "domain": "cloud.google.com",
    "category": "hosting-cloud",
    "tagline": "High-performance cloud infrastructure, data analytics, and AI services",
    "description": "Google Cloud offers scalable virtual machines, Kubernetes management, BigQuery analytics, and cutting-edge AI infrastructure. It is engineered for software developers, data engineering teams, and enterprise organizations.",
    "rating": 4.6,
    "reviewsCount": 5200,
    "pricing": "Freemium",
    "websiteUrl": "https://cloud.google.com",
    "affiliateUrl": "https://cloud.google.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "42.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "microsoft-azure",
    "name": "Microsoft Azure",
    "domain": "azure.microsoft.com",
    "category": "hosting-cloud",
    "tagline": "Enterprise cloud services, virtual computing, and hybrid cloud infrastructure",
    "description": "Azure delivers hybrid cloud computing, enterprise Active Directory management, serverless functions, and AI hosting seamlessly integrated with Microsoft systems. It serves enterprise IT managers, developers, and corporate operations.",
    "rating": 4.5,
    "reviewsCount": 6100,
    "pricing": "Freemium",
    "websiteUrl": "https://azure.microsoft.com",
    "affiliateUrl": "https://azure.microsoft.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "38.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "vercel",
    "name": "Vercel",
    "domain": "vercel.com",
    "category": "hosting-cloud",
    "tagline": "Frontend cloud platform for Next.js, web applications, and serverless deployment",
    "description": "Vercel streamlines web app deployment with instant global CDN edge distribution, automatic preview deployments, and serverless compute. It is built specifically for frontend developers, Next.js engineers, and modern digital agencies.",
    "rating": 4.9,
    "reviewsCount": 3400,
    "pricing": "Freemium",
    "websiteUrl": "https://vercel.com",
    "affiliateUrl": "https://vercel.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "18.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "netlify",
    "name": "Netlify",
    "domain": "netlify.com",
    "category": "hosting-cloud",
    "tagline": "Composable web platform for static sites, serverless functions, and headless apps",
    "description": "Netlify automates web hosting build pipelines, continuous integration, continuous delivery (CI/CD), and edge computing for jamstack frameworks. It is ideal for web developers, Jamstack agencies, and software startups.",
    "rating": 4.8,
    "reviewsCount": 2900,
    "pricing": "Freemium",
    "websiteUrl": "https://netlify.com",
    "affiliateUrl": "https://netlify.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "14.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "digitalocean",
    "name": "DigitalOcean",
    "domain": "digitalocean.com",
    "category": "hosting-cloud",
    "tagline": "Developer-friendly cloud hosting, cloud Droplets, and managed Kubernetes",
    "description": "DigitalOcean simplifies cloud hosting with low-cost Virtual Private Servers (Droplets), managed databases, and app platform deployments. It is designed for developers, startups, and growing SMB engineering teams.",
    "rating": 4.7,
    "reviewsCount": 3800,
    "pricing": "Free Trial",
    "websiteUrl": "https://digitalocean.com",
    "affiliateUrl": "https://digitalocean.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "11.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "cloudflare",
    "name": "Cloudflare",
    "domain": "cloudflare.com",
    "category": "hosting-cloud",
    "tagline": "Global CDN, DDoS protection, edge workers, and web security network",
    "description": "Cloudflare speeds up and secures web properties using global content delivery networks, DNS routing, and edge worker compute scripts. It serves website owners, SaaS developers, and enterprise security administrators.",
    "rating": 4.8,
    "reviewsCount": 4500,
    "pricing": "Freemium",
    "websiteUrl": "https://cloudflare.com",
    "affiliateUrl": "https://cloudflare.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "42.0M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "render",
    "name": "Render",
    "domain": "render.com",
    "category": "hosting-cloud",
    "tagline": "Unified cloud platform to build, deploy, and run static sites and web apps",
    "description": "Render provides effortless cloud hosting for web applications, Docker containers, background workers, and PostgreSQL databases with automatic SSL. It is built as a modern, developer-friendly alternative to Heroku.",
    "rating": 4.8,
    "reviewsCount": 1150,
    "pricing": "Freemium",
    "websiteUrl": "https://render.com",
    "affiliateUrl": "https://render.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "fly-io",
    "name": "Fly.io",
    "domain": "fly.io",
    "category": "hosting-cloud",
    "tagline": "Deploy full-stack applications and databases close to your users globally",
    "description": "Fly.io converts Docker containers into micro-VMs that run on physical hardware distributed across global edge locations. It serves backend developers and DevOps engineers requiring low-latency server execution.",
    "rating": 4.8,
    "reviewsCount": 850,
    "pricing": "Freemium",
    "websiteUrl": "https://fly.io",
    "affiliateUrl": "https://fly.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "railway",
    "name": "Railway",
    "domain": "railway.com",
    "category": "hosting-cloud",
    "tagline": "Instant infrastructure platform to deploy code, databases, and microservices",
    "description": "Railway connects directly to GitHub repositories to deploy applications, redis caches, and databases automatically with zero configuration. It is engineered for indie developers, startups, and software teams.",
    "rating": 4.9,
    "reviewsCount": 1420,
    "pricing": "Freemium",
    "websiteUrl": "https://railway.com",
    "affiliateUrl": "https://railway.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "3.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "supabase",
    "name": "Supabase",
    "domain": "supabase.com",
    "category": "hosting-cloud",
    "tagline": "The open-source Firebase alternative providing real-time Postgres backends",
    "description": "Supabase provides instant managed Postgres databases, authentication services, storage buckets, and auto-generated REST/GraphQL APIs. It is built for full-stack web and mobile application developers.",
    "rating": 4.9,
    "reviewsCount": 2100,
    "pricing": "Freemium",
    "websiteUrl": "https://supabase.com",
    "affiliateUrl": "https://supabase.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "5.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "neon-db",
    "name": "Neon",
    "domain": "neon.tech",
    "category": "hosting-cloud",
    "tagline": "Serverless open-source Postgres database with instant branching and scaling",
    "description": "Neon separates storage from compute to offer serverless Postgres databases that scale down to zero and allow code-like database branching. It is built for modern web developers and cloud architects.",
    "rating": 4.9,
    "reviewsCount": 980,
    "pricing": "Freemium",
    "websiteUrl": "https://neon.tech",
    "affiliateUrl": "https://neon.tech",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "planetscale",
    "name": "PlanetScale",
    "domain": "planetscale.com",
    "category": "hosting-cloud",
    "tagline": "Serverless MySQL platform built on Vitess with non-blocking schema migrations",
    "description": "PlanetScale delivers highly available serverless MySQL databases supporting database branching and zero-downtime schema deployments. It is designed for high-scale SaaS products and engineering teams.",
    "rating": 4.8,
    "reviewsCount": 1100,
    "pricing": "Paid",
    "websiteUrl": "https://planetscale.com",
    "affiliateUrl": "https://planetscale.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.9M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "linode-akamai",
    "name": "Akamai Cloud (Linode)",
    "domain": "linode.com",
    "category": "hosting-cloud",
    "tagline": "Reliable, high-performance cloud compute virtual machines and infrastructure",
    "description": "Linode provides simple Linux virtual machines, block storage, and Kubernetes infrastructure at transparent pricing. It is a trusted cloud platform for system administrators, developers, and SMBs.",
    "rating": 4.6,
    "reviewsCount": 2100,
    "pricing": "Free Trial",
    "websiteUrl": "https://linode.com",
    "affiliateUrl": "https://linode.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "5.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "hetzner",
    "name": "Hetzner Cloud",
    "domain": "hetzner.com",
    "category": "hosting-cloud",
    "tagline": "Ultra-affordable, high-performance European cloud servers and dedicated hosting",
    "description": "Hetzner offers high-spec dedicated root servers, NVMe cloud instances, and web hosting at low European price points. It is heavily favored by system engineers, DevOps specialists, and bootstrapped startups.",
    "rating": 4.8,
    "reviewsCount": 3200,
    "pricing": "Paid",
    "websiteUrl": "https://hetzner.com",
    "affiliateUrl": "https://hetzner.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "8.9M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "vultr",
    "name": "Vultr",
    "domain": "vultr.com",
    "category": "hosting-cloud",
    "tagline": "Global cloud compute, GPU server hosting, and bare metal infrastructure",
    "description": "Vultr deploys high-speed cloud compute, bare metal servers, and NVIDIA GPUs across 30+ worldwide data center locations. It serves web developers, AI infrastructure engineers, and enterprise workloads.",
    "rating": 4.6,
    "reviewsCount": 1820,
    "pricing": "Free Trial",
    "websiteUrl": "https://vultr.com",
    "affiliateUrl": "https://vultr.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "docker",
    "name": "Docker",
    "domain": "docker.com",
    "category": "hosting-cloud",
    "tagline": "Industry-standard containerization platform for software developers and DevOps",
    "description": "Docker packages applications and dependencies into isolated lightweight containers for consistent execution across environments. It is a fundamental tool for software engineers, DevOps teams, and CI/CD pipelines.",
    "rating": 4.8,
    "reviewsCount": 6200,
    "pricing": "Freemium",
    "websiteUrl": "https://docker.com",
    "affiliateUrl": "https://docker.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "24.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "kubernetes",
    "name": "Kubernetes",
    "domain": "kubernetes.io",
    "category": "hosting-cloud",
    "tagline": "Open-source container orchestration system for automating application deployment",
    "description": "Kubernetes automates deployment, scaling, and operational management of containerized application clusters across cloud environments. It serves enterprise DevOps engineers, site reliability engineers, and cloud architects.",
    "rating": 4.8,
    "reviewsCount": 4100,
    "pricing": "Free",
    "websiteUrl": "https://kubernetes.io",
    "affiliateUrl": "https://kubernetes.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "terraform",
    "name": "HashiCorp Terraform",
    "domain": "terraform.io",
    "category": "hosting-cloud",
    "tagline": "Open-source Infrastructure as Code (IaC) tool to provision cloud resources",
    "description": "Terraform defines cloud and on-premise infrastructure resources in human-readable declarative configuration files. It is an industry standard for cloud engineers and DevOps professionals managing multi-cloud infrastructure.",
    "rating": 4.8,
    "reviewsCount": 2900,
    "pricing": "Freemium",
    "websiteUrl": "https://terraform.io",
    "affiliateUrl": "https://terraform.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "pulumi",
    "name": "Pulumi",
    "domain": "pulumi.com",
    "category": "hosting-cloud",
    "tagline": "Infrastructure as Code using real programming languages like TypeScript and Python",
    "description": "Pulumi allows developers to provision cloud resources using familiar programming languages instead of custom domain-specific languages. It serves modern software engineers and cloud architects.",
    "rating": 4.8,
    "reviewsCount": 650,
    "pricing": "Freemium",
    "websiteUrl": "https://pulumi.com",
    "affiliateUrl": "https://pulumi.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "890K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "portainer",
    "name": "Portainer",
    "domain": "portainer.io",
    "category": "hosting-cloud",
    "tagline": "Lightweight management UI for Docker, Swarm, and Kubernetes environments",
    "description": "Portainer simplifies container management with an intuitive graphical dashboard for deploying and monitoring Docker containers. It is tailored for home lab managers, developers, and DevOps teams.",
    "rating": 4.8,
    "reviewsCount": 1250,
    "pricing": "Freemium",
    "websiteUrl": "https://portainer.io",
    "affiliateUrl": "https://portainer.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "coolify",
    "name": "Coolify",
    "domain": "coolify.io",
    "category": "hosting-cloud",
    "tagline": "Self-hosted, open-source Heroku and Netlify alternative for your servers",
    "description": "Coolify transforms any bare-metal Linux server or VPS into a self-hosted PaaS to deploy web apps, databases, and open-source services. It serves privacy-minded developers, self-hosters, and indie hackers.",
    "rating": 4.9,
    "reviewsCount": 1100,
    "pricing": "Free",
    "websiteUrl": "https://coolify.io",
    "affiliateUrl": "https://coolify.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "dokku",
    "name": "Dokku",
    "domain": "dokku.com",
    "category": "hosting-cloud",
    "tagline": "Docker-powered mini-Heroku platform for self-hosting on personal servers",
    "description": "Dokku is an ultra-lightweight PaaS that allows developers to push applications to their own VPS via simple Git commands. It is designed for developers seeking low-cost, self-hosted app deployments.",
    "rating": 4.7,
    "reviewsCount": 540,
    "pricing": "Free",
    "websiteUrl": "https://dokku.com",
    "affiliateUrl": "https://dokku.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "320K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "mongodb-atlas",
    "name": "MongoDB Atlas",
    "domain": "mongodb.com/atlas",
    "category": "hosting-cloud",
    "tagline": "Fully managed multi-cloud developer document database platform",
    "description": "MongoDB Atlas provides automated, scalable document database hosting across AWS, GCP, and Azure with vector search support. It serves full-stack web developers and enterprise data architects.",
    "rating": 4.7,
    "reviewsCount": 3100,
    "pricing": "Freemium",
    "websiteUrl": "https://mongodb.com/atlas",
    "affiliateUrl": "https://mongodb.com/atlas",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "12.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "redis-cloud",
    "name": "Redis Cloud",
    "domain": "redis.io",
    "category": "hosting-cloud",
    "tagline": "High-performance managed in-memory data store, cache, and vector database",
    "description": "Redis Cloud offers ultra-low latency in-memory data caching, session storage, and vector searching for real-time web applications. It serves backend developers and high-throughput application teams.",
    "rating": 4.8,
    "reviewsCount": 2400,
    "pricing": "Freemium",
    "websiteUrl": "https://redis.io",
    "affiliateUrl": "https://redis.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "6.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "upstash",
    "name": "Upstash",
    "domain": "upstash.com",
    "category": "hosting-cloud",
    "tagline": "Serverless database platform for Redis, Kafka, and Vector search",
    "description": "Upstash provides serverless Redis, Kafka, and Vector databases with per-request pricing and HTTP REST APIs for edge runtime frameworks. It is tailored for Next.js, Vercel, and serverless developers.",
    "rating": 4.9,
    "reviewsCount": 620,
    "pricing": "Freemium",
    "websiteUrl": "https://upstash.com",
    "affiliateUrl": "https://upstash.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "850K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "cockroachdb",
    "name": "CockroachDB",
    "domain": "cockroachlabs.com",
    "category": "hosting-cloud",
    "tagline": "Cloud-native distributed SQL database with multi-region resilience",
    "description": "CockroachDB is a cloud-native distributed SQL database that delivers transactional consistency and survivor-level fault tolerance across regions. It serves enterprise architects and SaaS engineering teams.",
    "rating": 4.7,
    "reviewsCount": 890,
    "pricing": "Freemium",
    "websiteUrl": "https://cockroachlabs.com",
    "affiliateUrl": "https://cockroachlabs.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "turso",
    "name": "Turso",
    "domain": "turso.tech",
    "category": "hosting-cloud",
    "tagline": "In-memory, edge-replicated serverless database powered by libSQL",
    "description": "Turso provides edge-hosted SQLite-compatible databases that replicate data instantly near application end users. It is designed for web developers building low-latency, distributed edge apps.",
    "rating": 4.8,
    "reviewsCount": 420,
    "pricing": "Freemium",
    "websiteUrl": "https://turso.tech",
    "affiliateUrl": "https://turso.tech",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "pinecone",
    "name": "Pinecone",
    "domain": "pinecone.io",
    "category": "hosting-cloud",
    "tagline": "Fully managed vector database for high-performance AI applications and RAG",
    "description": "Pinecone provides ultra-fast vector index storage and semantic search capabilities for building LLM applications and retrieval-augmented generation (RAG) pipelines. It serves AI developers and machine learning engineers.",
    "rating": 4.8,
    "reviewsCount": 1150,
    "pricing": "Freemium",
    "websiteUrl": "https://pinecone.io",
    "affiliateUrl": "https://pinecone.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "qdrant",
    "name": "Qdrant",
    "domain": "qdrant.tech",
    "category": "hosting-cloud",
    "tagline": "Open-source vector database and similarity search engine for AI stack",
    "description": "Qdrant provides a vector similarity search engine with extended payload filtering built in Rust. It serves machine learning engineers and developers building production AI retrieval models.",
    "rating": 4.9,
    "reviewsCount": 480,
    "pricing": "Freemium",
    "websiteUrl": "https://qdrant.tech",
    "affiliateUrl": "https://qdrant.tech",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "github-actions",
    "name": "GitHub Actions",
    "domain": "github.com/features/actions",
    "category": "hosting-cloud",
    "tagline": "Automate software workflows, CI/CD pipelines, and deployments natively in GitHub",
    "description": "GitHub Actions automates code testing, container building, and cloud deployments directly from repository event triggers. It is used daily by millions of software developers and open-source projects.",
    "rating": 4.8,
    "reviewsCount": 4200,
    "pricing": "Freemium",
    "websiteUrl": "https://github.com/features/actions",
    "affiliateUrl": "https://github.com/features/actions",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "85.0M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "gitlab-ci",
    "name": "GitLab CI/CD",
    "domain": "about.gitlab.com",
    "category": "hosting-cloud",
    "tagline": "Integrated DevOps platform for code repositories, CI pipelines, and security",
    "description": "GitLab provides a complete DevSecOps environment covering code version control, automated testing, container registries, and deployment monitoring. It serves enterprise engineering teams.",
    "rating": 4.6,
    "reviewsCount": 3100,
    "pricing": "Freemium",
    "websiteUrl": "https://about.gitlab.com",
    "affiliateUrl": "https://about.gitlab.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "18.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "circleci",
    "name": "CircleCI",
    "domain": "circleci.com",
    "category": "hosting-cloud",
    "tagline": "Continuous integration and delivery platform for fast software development",
    "description": "CircleCI automates code building, testing, and deployment pipelines at enterprise scale with custom orb integrations. It is engineered for engineering teams scaling DevOps automation.",
    "rating": 4.5,
    "reviewsCount": 1820,
    "pricing": "Freemium",
    "websiteUrl": "https://circleci.com",
    "affiliateUrl": "https://circleci.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "sentry",
    "name": "Sentry",
    "domain": "sentry.io",
    "category": "hosting-cloud",
    "tagline": "Code-level application performance monitoring and real-time error tracking",
    "description": "Sentry pinpoints production software crashes, memory leaks, and slow database queries across frontend and backend codebases. It is built for software engineers and site reliability teams.",
    "rating": 4.8,
    "reviewsCount": 2400,
    "pricing": "Freemium",
    "websiteUrl": "https://sentry.io",
    "affiliateUrl": "https://sentry.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "6.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "datadog",
    "name": "Datadog",
    "domain": "datadoghq.com",
    "category": "hosting-cloud",
    "tagline": "Cloud-scale monitoring, log management, and application performance analytics",
    "description": "Datadog integrates cloud server metrics, application traces, logs, and network security data into unified enterprise dashboards. It is built for site reliability engineers and enterprise IT ops.",
    "rating": 4.6,
    "reviewsCount": 2900,
    "pricing": "Free Trial",
    "websiteUrl": "https://datadoghq.com",
    "affiliateUrl": "https://datadoghq.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "9.5M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "new-relic",
    "name": "New Relic",
    "domain": "newrelic.com",
    "category": "hosting-cloud",
    "tagline": "All-in-one observability platform for cloud infrastructure and app health",
    "description": "New Relic tracks metrics, events, traces, and logs across cloud systems to pinpoint performance bottlenecks. It serves enterprise engineering teams and DevOps organizations.",
    "rating": 4.5,
    "reviewsCount": 2100,
    "pricing": "Freemium",
    "websiteUrl": "https://newrelic.com",
    "affiliateUrl": "https://newrelic.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "5.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "grafana",
    "name": "Grafana",
    "domain": "grafana.com",
    "category": "hosting-cloud",
    "tagline": "Open-source operational dashboards and metric visualization platform",
    "description": "Grafana visualizes timeseries data from Prometheus, InfluxDB, and cloud providers in customizable, real-time dashboards. It is an industry staple for system administrators and DevOps engineers.",
    "rating": 4.9,
    "reviewsCount": 3800,
    "pricing": "Freemium",
    "websiteUrl": "https://grafana.com",
    "affiliateUrl": "https://grafana.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "4.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "prometheus",
    "name": "Prometheus",
    "domain": "prometheus.io",
    "category": "hosting-cloud",
    "tagline": "Open-source timeseries monitoring system and alerting toolkit",
    "description": "Prometheus collects and stores real-time metrics in a timeseries database with a powerful PromQL query engine. It serves cloud-native architects monitoring Kubernetes cluster infrastructure.",
    "rating": 4.8,
    "reviewsCount": 1950,
    "pricing": "Free",
    "websiteUrl": "https://prometheus.io",
    "affiliateUrl": "https://prometheus.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.6M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "better-stack",
    "name": "Better Stack",
    "domain": "betterstack.com",
    "category": "hosting-cloud",
    "tagline": "Uptime monitoring, incident management, and structured log management",
    "description": "Better Stack combines real-time website status monitoring, incident call routing, and SQL-searchable log management in an elegant interface. It serves modern developers and IT operations teams.",
    "rating": 4.9,
    "reviewsCount": 850,
    "pricing": "Freemium",
    "websiteUrl": "https://betterstack.com",
    "affiliateUrl": "https://betterstack.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.9M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "pagerduty",
    "name": "PagerDuty",
    "domain": "pagerduty.com",
    "category": "hosting-cloud",
    "tagline": "Enterprise incident response, on-call scheduling, and operations management",
    "description": "PagerDuty routes critical system alerts to on-call engineers to minimize downtime during IT outages. It is engineered for enterprise site reliability teams and IT operations departments.",
    "rating": 4.6,
    "reviewsCount": 2400,
    "pricing": "Free Trial",
    "websiteUrl": "https://pagerduty.com",
    "affiliateUrl": "https://pagerduty.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "cpanel",
    "name": "cPanel & WHM",
    "domain": "cpanel.net",
    "category": "hosting-cloud",
    "tagline": "Industry-standard web hosting control panel and server management dashboard",
    "description": "cPanel simplifies server administration, domain management, email creation, and MySQL database setup via a visual web interface. It is deployed across millions of web hosting providers worldwide.",
    "rating": 4.3,
    "reviewsCount": 3100,
    "pricing": "Paid",
    "websiteUrl": "https://cpanel.net",
    "affiliateUrl": "https://cpanel.net",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.5M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "plesk",
    "name": "Plesk",
    "domain": "plesk.com",
    "category": "hosting-cloud",
    "tagline": "Web hosting automation, server control panel, and WordPress management tool",
    "description": "Plesk provides a visual server management platform supporting multi-tenant hosting, security patching, and automated WordPress management. It is designed for web hosts, digital agencies, and developers.",
    "rating": 4.4,
    "reviewsCount": 1650,
    "pricing": "Paid",
    "websiteUrl": "https://plesk.com",
    "affiliateUrl": "https://plesk.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "kinsta",
    "name": "Kinsta",
    "domain": "kinsta.com",
    "category": "hosting-cloud",
    "tagline": "Premium managed WordPress hosting built on Google Cloud Platform",
    "description": "Kinsta delivers high-speed managed WordPress hosting, application hosting, and database hosting backed by Google's C2 infrastructure. It is built for high-traffic websites, agencies, and e-commerce stores.",
    "rating": 4.8,
    "reviewsCount": 1420,
    "pricing": "Paid",
    "websiteUrl": "https://kinsta.com",
    "affiliateUrl": "https://kinsta.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.9M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "wp-engine",
    "name": "WP Engine",
    "domain": "wpengine.com",
    "category": "hosting-cloud",
    "tagline": "Enterprise managed WordPress hosting platform and developer tools",
    "description": "WP Engine provides managed WordPress infrastructure, staging environments, global CDN performance, and enterprise security. It serves digital agencies, enterprise brands, and high-traffic publishers.",
    "rating": 4.6,
    "reviewsCount": 2800,
    "pricing": "Paid",
    "websiteUrl": "https://wpengine.com",
    "affiliateUrl": "https://wpengine.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "hostinger",
    "name": "Hostinger",
    "domain": "hostinger.com",
    "category": "hosting-cloud",
    "tagline": "Affordable web hosting, VPS, and managed WordPress hosting platform",
    "description": "Hostinger provides budget-friendly shared hosting, cloud servers, custom control panels, and automated website building. It is built for small business owners, bloggers, and web developers.",
    "rating": 4.6,
    "reviewsCount": 9500,
    "pricing": "Paid",
    "websiteUrl": "https://hostinger.com",
    "affiliateUrl": "https://hostinger.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "22.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "siteground",
    "name": "SiteGround",
    "domain": "siteground.com",
    "category": "hosting-cloud",
    "tagline": "High-performance web hosting with Google Cloud infrastructure and speed tools",
    "description": "SiteGround offers managed web hosting with custom caching plugins, automated backups, and daily security monitoring. It serves small business sites, WordPress developers, and online merchants.",
    "rating": 4.7,
    "reviewsCount": 4200,
    "pricing": "Paid",
    "websiteUrl": "https://siteground.com",
    "affiliateUrl": "https://siteground.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "8.5M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "fastly",
    "name": "Fastly",
    "domain": "fastly.com",
    "category": "hosting-cloud",
    "tagline": "Programmable edge cloud, real-time CDN, and edge security platform",
    "description": "Fastly provides edge computing, real-time cache purging, and web application firewall security for high-traffic platforms. It is built for enterprise engineering teams and digital publishers.",
    "rating": 4.6,
    "reviewsCount": 450,
    "pricing": "Free Trial",
    "websiteUrl": "https://fastly.com",
    "affiliateUrl": "https://fastly.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "backblaze-b2",
    "name": "Backblaze B2",
    "domain": "backblaze.com/b2",
    "category": "hosting-cloud",
    "tagline": "Low-cost S3-compatible cloud object storage for backups and media data",
    "description": "Backblaze B2 offers affordable cloud object storage with full Amazon S3 API compatibility at a fraction of standard cloud costs. It serves developers, IT backup managers, and media producers.",
    "rating": 4.8,
    "reviewsCount": 1820,
    "pricing": "Freemium",
    "websiteUrl": "https://backblaze.com/b2",
    "affiliateUrl": "https://backblaze.com/b2",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "wasabi",
    "name": "Wasabi Technologies",
    "domain": "wasabi.com",
    "category": "hosting-cloud",
    "tagline": "Hot cloud object storage with zero egress fees and S3 API compatibility",
    "description": "Wasabi provides fast S3-compatible cloud object storage with predictable pricing and no charges for API calls or data egress. It is designed for enterprise backup, media storage, and data archiving.",
    "rating": 4.7,
    "reviewsCount": 920,
    "pricing": "Free Trial",
    "websiteUrl": "https://wasabi.com",
    "affiliateUrl": "https://wasabi.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "ovhcloud",
    "name": "OVHcloud",
    "domain": "ovhcloud.com",
    "category": "hosting-cloud",
    "tagline": "European enterprise bare metal, public cloud infrastructure, and web hosting",
    "description": "OVHcloud delivers dedicated bare-metal servers, public cloud computing, and web hosting with built-in DDoS protection. It serves European enterprises, hosting resellers, and system engineers.",
    "rating": 4.3,
    "reviewsCount": 2400,
    "pricing": "Paid",
    "websiteUrl": "https://ovhcloud.com",
    "affiliateUrl": "https://ovhcloud.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "7.8M",
    "isFreeTier": false,
    "isOpenSource": false
  }
];

const saasDataPath = path.join(__dirname, '..', 'src', 'data', 'saasData.jsx');
let content = fs.readFileSync(saasDataPath, 'utf8');

const match = content.match(/export const staticSaasTools = (\[[\s\S]*?\n\]);/);
if (!match) {
  console.error('Could not find staticSaasTools in saasData.jsx');
  process.exit(1);
}

let existingTools = JSON.parse(match[1]);

const existingIds = new Set(existingTools.map(t => t.id.toLowerCase()));
const existingNames = new Set(existingTools.map(t => t.name.toLowerCase()));

let addedCount = 0;
let skippedCount = 0;

newTools.forEach(tool => {
  const normId = tool.id.toLowerCase();
  const normName = tool.name.toLowerCase();

  if (!existingIds.has(normId) && !existingNames.has(normName)) {
    existingTools.push(tool);
    existingIds.add(normId);
    existingNames.add(normName);
    addedCount++;
  } else {
    // Enrich existing tool without creating a duplicate
    const idx = existingTools.findIndex(t => t.id.toLowerCase() === normId || t.name.toLowerCase() === normName);
    if (idx !== -1) {
      existingTools[idx] = { ...existingTools[idx], category: tool.category, tagline: tool.tagline || existingTools[idx].tagline };
    }
    skippedCount++;
  }
});

const updatedArrayStr = JSON.stringify(existingTools, null, 2);
content = content.replace(/export const staticSaasTools = \[[\s\S]*?\n\];/, `export const staticSaasTools = ${updatedArrayStr};`);

fs.writeFileSync(saasDataPath, content, 'utf8');
console.log(`Ingestion Complete! Added: ${addedCount} brand new tools | Deduplicated: ${skippedCount} existing tools | Total static tools: ${existingTools.length}`);
