const fs = require('fs');
const path = require('path');

const devopsTools = [
  {
    "id": "opentofu",
    "name": "OpenTofu",
    "domain": "opentofu.org",
    "category": "devops-infrastructure",
    "tagline": "Open-source, community-driven Infrastructure as Code engine",
    "description": "OpenTofu is a community-governed, open-source fork of Terraform for declaring, provisioning, and managing cloud resources using declarative configurations. It serves cloud engineers, platform architects, and DevOps teams seeking an open-source IaC foundation.",
    "rating": 4.9,
    "reviewsCount": 1150,
    "pricing": "Free",
    "websiteUrl": "https://opentofu.org",
    "affiliateUrl": "https://opentofu.org",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.6M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "flux-cd",
    "name": "FluxCD",
    "domain": "fluxcd.io",
    "category": "devops-infrastructure",
    "tagline": "GitOps operator for keeping Kubernetes cluster states in sync",
    "description": "FluxCD continuously reconciles Kubernetes cluster states with code definitions stored in Git repositories and OCI image registries. It is built for cloud-native developers, platform engineers, and SREs implementing progressive delivery.",
    "rating": 4.8,
    "reviewsCount": 1250,
    "pricing": "Free",
    "websiteUrl": "https://fluxcd.io",
    "affiliateUrl": "https://fluxcd.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "keda-sh",
    "name": "KEDA",
    "domain": "keda.sh",
    "category": "devops-infrastructure",
    "tagline": "Kubernetes Event-driven Autoscaling component for dynamic pod scaling",
    "description": "KEDA drives Kubernetes pod autoscaling based on event metrics, message queue depths, or database state triggers down to zero pods. It serves backend cloud developers and event-driven microservices architects.",
    "rating": 4.9,
    "reviewsCount": 850,
    "pricing": "Free",
    "websiteUrl": "https://keda.sh",
    "affiliateUrl": "https://keda.sh",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "950K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "portainer",
    "name": "Portainer",
    "domain": "portainer.io",
    "category": "devops-infrastructure",
    "tagline": "Lightweight management UI for Docker, Swarm, and Kubernetes environments",
    "description": "Portainer simplifies containerized workload management with an intuitive graphical web interface for deploying and monitoring container clusters. It is tailored for home lab managers, developers, and DevOps operations.",
    "rating": 4.8,
    "reviewsCount": 1250,
    "pricing": "Freemium",
    "websiteUrl": "https://portainer.io",
    "affiliateUrl": "https://portainer.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "rancher-suse",
    "name": "Rancher",
    "domain": "rancher.com",
    "category": "devops-infrastructure",
    "tagline": "Complete enterprise multi-cluster Kubernetes management platform",
    "description": "Rancher centralizes operational security, access controls, and cluster management across multi-cloud and on-premise Kubernetes deployments. It serves enterprise platform engineering teams and system leads.",
    "rating": 4.7,
    "reviewsCount": 1820,
    "pricing": "Freemium",
    "websiteUrl": "https://rancher.com",
    "affiliateUrl": "https://rancher.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "2.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "linkerd",
    "name": "Linkerd",
    "domain": "linkerd.io",
    "category": "devops-infrastructure",
    "tagline": "Ultralight, security-first service mesh for Kubernetes",
    "description": "Linkerd adds zero-config mTLS encryption, latency tracking, and traffic routing to Kubernetes microservices without complex YAML setup. It is built for SREs, cluster operators, and cloud security engineers.",
    "rating": 4.8,
    "reviewsCount": 920,
    "pricing": "Freemium",
    "websiteUrl": "https://linkerd.io",
    "affiliateUrl": "https://linkerd.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "850K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "istio-mesh",
    "name": "Istio",
    "domain": "istio.io",
    "category": "devops-infrastructure",
    "tagline": "Open-source service mesh providing microservice traffic management and security",
    "description": "Istio manages microservice communication with advanced traffic routing, mutual TLS encryption, and deep telemetry collection. It is engineered for enterprise platform teams operating high-scale Kubernetes workloads.",
    "rating": 4.6,
    "reviewsCount": 2400,
    "pricing": "Free",
    "websiteUrl": "https://istio.io",
    "affiliateUrl": "https://istio.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "cilium-ebpf",
    "name": "Cilium",
    "domain": "cilium.io",
    "category": "devops-infrastructure",
    "tagline": "eBPF-powered CNI networking, observability, and security for cloud-native apps",
    "description": "Cilium provides high-performance Linux network routing, identity-based security policies, and deep L3-L7 observability powered by eBPF. It is built for cloud-native network engineers and platform leads.",
    "rating": 4.9,
    "reviewsCount": 1150,
    "pricing": "Free",
    "websiteUrl": "https://cilium.io",
    "affiliateUrl": "https://cilium.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "helm-sh",
    "name": "Helm",
    "domain": "helm.sh",
    "category": "devops-infrastructure",
    "tagline": "The Kubernetes package manager for defining and deploying applications",
    "description": "Helm uses chart templates to package, version, and manage complex Kubernetes application manifests as single repeatable units. It is an industry standard tool for Kubernetes developers and release engineers.",
    "rating": 4.8,
    "reviewsCount": 3800,
    "pricing": "Free",
    "websiteUrl": "https://helm.sh",
    "affiliateUrl": "https://helm.sh",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.5M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "terragrunt-iac",
    "name": "Terragrunt",
    "domain": "terragrunt.gruntwork.io",
    "category": "devops-infrastructure",
    "tagline": "Thin wrapper for IaC tools providing DRY code configurations and multi-module runs",
    "description": "Terragrunt eliminates code duplication across environment directories and orchestrates parallel execution across multiple IaC modules. It serves cloud infrastructure engineers and DevOps leads.",
    "rating": 4.8,
    "reviewsCount": 1100,
    "pricing": "Free",
    "websiteUrl": "https://terragrunt.gruntwork.io",
    "affiliateUrl": "https://terragrunt.gruntwork.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "atlantis-pr",
    "name": "Atlantis",
    "domain": "runatlantis.io",
    "category": "devops-infrastructure",
    "tagline": "Pull request automation for Infrastructure as Code workflows",
    "description": "Atlantis executes IaC plan and apply commands directly within code pull request comments to promote GitOps peer reviews. It serves DevOps engineers automating infrastructure deployment safety.",
    "rating": 4.9,
    "reviewsCount": 820,
    "pricing": "Free",
    "websiteUrl": "https://runatlantis.io",
    "affiliateUrl": "https://runatlantis.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "950K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "infracost-finops",
    "name": "Infracost",
    "domain": "infracost.io",
    "category": "devops-infrastructure",
    "tagline": "Real-time cloud cost estimates for Infrastructure as Code in code reviews",
    "description": "Infracost parses IaC code changes to display exact monthly cloud cost impacts directly inside pull request code reviews. It serves FinOps leads, DevOps engineers, and engineering managers.",
    "rating": 4.9,
    "reviewsCount": 650,
    "pricing": "Freemium",
    "websiteUrl": "https://infracost.io",
    "affiliateUrl": "https://infracost.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "780K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "kubecost-finops",
    "name": "Kubecost",
    "domain": "kubecost.com",
    "category": "devops-infrastructure",
    "tagline": "Real-time cost monitoring and capacity optimization for Kubernetes",
    "description": "Kubecost breaks down Kubernetes cloud spend by namespace, deployment, and service to optimize cluster resource efficiency. It is built for FinOps leads, platform engineers, and cloud architects.",
    "rating": 4.8,
    "reviewsCount": 720,
    "pricing": "Freemium",
    "websiteUrl": "https://kubecost.com",
    "affiliateUrl": "https://kubecost.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "localstack-aws",
    "name": "LocalStack",
    "domain": "localstack.cloud",
    "category": "devops-infrastructure",
    "tagline": "Fully functional local AWS cloud emulator for fast developer testing",
    "description": "LocalStack runs local mocks of AWS services like S3, Lambda, DynamoDB, and API Gateway on developer machines. It serves backend software developers and DevOps leads building cloud apps locally.",
    "rating": 4.8,
    "reviewsCount": 1650,
    "pricing": "Freemium",
    "websiteUrl": "https://localstack.cloud",
    "affiliateUrl": "https://localstack.cloud",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "2.9M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "minio-storage",
    "name": "MinIO",
    "domain": "min.io",
    "category": "devops-infrastructure",
    "tagline": "High-performance Kubernetes-native S3-compatible object storage",
    "description": "MinIO delivers enterprise S3-compatible cloud object storage for structured and unstructured data workloads on private infrastructure. It serves cloud infrastructure architects and DevOps leads.",
    "rating": 4.8,
    "reviewsCount": 1650,
    "pricing": "Freemium",
    "websiteUrl": "https://min.io",
    "affiliateUrl": "https://min.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "traefik-proxy",
    "name": "Traefik",
    "domain": "traefik.io",
    "category": "devops-infrastructure",
    "tagline": "Cloud-native edge router and ingress controller with automatic service discovery",
    "description": "Traefik routes web traffic to microservices dynamically while automating SSL certificate renewal and load balancing. It is built for DevOps engineers, Kubernetes admins, and container operators.",
    "rating": 4.8,
    "reviewsCount": 2100,
    "pricing": "Freemium",
    "websiteUrl": "https://traefik.io",
    "affiliateUrl": "https://traefik.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "kong-gateway",
    "name": "Kong Gateway",
    "domain": "konghq.com",
    "category": "devops-infrastructure",
    "tagline": "Cloud-native, high-performance API gateway and microservices control plane",
    "description": "Kong Gateway routes API traffic, enforces authentication, and applies rate-limiting plugins for microservice architectures. It serves enterprise software architects and cloud infrastructure teams.",
    "rating": 4.8,
    "reviewsCount": 2100,
    "pricing": "Freemium",
    "websiteUrl": "https://konghq.com",
    "affiliateUrl": "https://konghq.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "tyk-gateway",
    "name": "Tyk",
    "domain": "tyk.io",
    "category": "devops-infrastructure",
    "tagline": "Open-source enterprise API gateway and developer portal platform",
    "description": "Tyk provides API routing, quota controls, detailed analytics, and developer portal generation with zero third-party dependencies. It serves DevOps engineers and platform engineering leads.",
    "rating": 4.7,
    "reviewsCount": 850,
    "pricing": "Freemium",
    "websiteUrl": "https://tyk.io",
    "affiliateUrl": "https://tyk.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "emissary-ingress",
    "name": "Ambassador (Emissary-Ingress)",
    "domain": "getambassador.io",
    "category": "devops-infrastructure",
    "tagline": "Kubernetes-native API gateway and ingress controller powered by Envoy",
    "description": "Ambassador routes edge traffic, handles Canary releases, and manages gRPC/HTTP traffic natively inside Kubernetes clusters. It is built for Kubernetes developers and cloud infrastructure leads.",
    "rating": 4.7,
    "reviewsCount": 540,
    "pricing": "Freemium",
    "websiteUrl": "https://getambassador.io",
    "affiliateUrl": "https://getambassador.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "cloudflare-tunnels",
    "name": "Cloudflare Tunnel",
    "domain": "cloudflare.com",
    "category": "devops-infrastructure",
    "tagline": "Expose web servers securely to the internet without open inbound ports",
    "description": "Cloudflare Tunnel establishes encrypted outbound connections from private servers to Cloudflare's edge network without opening public ports. It serves sysadmins, developers, and security leads.",
    "rating": 4.9,
    "reviewsCount": 2800,
    "pricing": "Freemium",
    "websiteUrl": "https://cloudflare.com/products/tunnel",
    "affiliateUrl": "https://cloudflare.com/products/tunnel",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "42.0M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "tailscale-vpn",
    "name": "Tailscale",
    "domain": "tailscale.com",
    "category": "devops-infrastructure",
    "tagline": "Zero-config WireGuard mesh VPN for secure private network connectivity",
    "description": "Tailscale creates encrypted mesh networks connecting servers, containers, and developer laptops authenticated via team Identity Providers. It is engineered for IT teams and DevOps engineers.",
    "rating": 4.9,
    "reviewsCount": 1420,
    "pricing": "Freemium",
    "websiteUrl": "https://tailscale.com",
    "affiliateUrl": "https://tailscale.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "3.9M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "wireguard-protocol",
    "name": "WireGuard",
    "domain": "wireguard.com",
    "category": "devops-infrastructure",
    "tagline": "Extremely simple yet fast modern VPN protocol and software kernel module",
    "description": "WireGuard provides high-speed, state-of-the-art encrypted networking using modern cryptography running directly inside the OS kernel. It is a foundational protocol for network engineers and sysadmins.",
    "rating": 4.9,
    "reviewsCount": 3800,
    "pricing": "Free",
    "websiteUrl": "https://wireguard.com",
    "affiliateUrl": "https://wireguard.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "netmaker-ztna",
    "name": "Netmaker",
    "domain": "netmaker.io",
    "category": "devops-infrastructure",
    "tagline": "Automated WireGuard virtual networking engine for multi-cloud environments",
    "description": "Netmaker provisions fast, multi-cloud WireGuard mesh networks across distributed servers and cloud instances automatically. It serves DevOps engineers connecting private cloud networks.",
    "rating": 4.7,
    "reviewsCount": 190,
    "pricing": "Freemium",
    "websiteUrl": "https://netmaker.io",
    "affiliateUrl": "https://netmaker.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "150K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "headscale-mesh",
    "name": "Headscale",
    "domain": "github.com",
    "category": "devops-infrastructure",
    "tagline": "Open-source, self-hosted implementation of the Tailscale control server",
    "description": "Headscale allows self-hosters to operate private Tailscale mesh networks on their own servers with complete data autonomy. It is built for open-source advocates and home lab network leads.",
    "rating": 4.9,
    "reviewsCount": 650,
    "pricing": "Free",
    "websiteUrl": "https://github.com/juanfont/headscale",
    "affiliateUrl": "https://github.com/juanfont/headscale",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "820K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "pomerium-ztna",
    "name": "Pomerium",
    "domain": "pomerium.com",
    "category": "devops-infrastructure",
    "tagline": "Open-source identity-aware access proxy for zero-trust application access",
    "description": "Pomerium enforces identity-aware access rules on incoming HTTP/HTTPS requests to internal web applications in real time. It is built for DevOps engineers replacing legacy network perimeters.",
    "rating": 4.7,
    "reviewsCount": 210,
    "pricing": "Freemium",
    "websiteUrl": "https://pomerium.com",
    "affiliateUrl": "https://pomerium.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "140K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "authentik-sso",
    "name": "authentik",
    "domain": "goauthentik.io",
    "category": "devops-infrastructure",
    "tagline": "Open-source Identity Provider focused on flexible SSO and reverse proxy access",
    "description": "authentik provides self-hosted single sign-on, WebAuthn MFA, and OAuth2/SAML authentication across private web applications. It serves homelab sysadmins and corporate security leads.",
    "rating": 4.9,
    "reviewsCount": 620,
    "pricing": "Free",
    "websiteUrl": "https://goauthentik.io",
    "affiliateUrl": "https://goauthentik.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "850K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "keycloak-iam",
    "name": "Keycloak",
    "domain": "keycloak.org",
    "category": "devops-infrastructure",
    "tagline": "Open-source enterprise identity and access management system",
    "description": "Keycloak handles user authentication, single sign-on, social login brokers, and LDAP synchronization for web applications. It serves enterprise software architects and IT administrators.",
    "rating": 4.7,
    "reviewsCount": 980,
    "pricing": "Free",
    "websiteUrl": "https://keycloak.org",
    "affiliateUrl": "https://keycloak.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.5M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "boundary-hashicorp",
    "name": "HashiCorp Boundary",
    "domain": "boundaryproject.io",
    "category": "devops-infrastructure",
    "tagline": "Identity-based privileged infrastructure access management platform",
    "description": "Boundary grants dynamic access to target private hosts and databases based on user identity without exposing private networks. It serves enterprise DevOps leads and security administrators.",
    "rating": 4.6,
    "reviewsCount": 280,
    "pricing": "Freemium",
    "websiteUrl": "https://boundaryproject.io",
    "affiliateUrl": "https://boundaryproject.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "210K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "vault-hashicorp",
    "name": "HashiCorp Vault",
    "domain": "vaultproject.io",
    "category": "devops-infrastructure",
    "tagline": "Enterprise secret management, encryption, and privileged identity store",
    "description": "Vault secures, stores, and tightly controls access to tokens, passwords, certificates, and API encryption keys across cloud applications. It is an industry staple for DevSecOps and SRE teams.",
    "rating": 4.8,
    "reviewsCount": 3100,
    "pricing": "Freemium",
    "websiteUrl": "https://vaultproject.io",
    "affiliateUrl": "https://vaultproject.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "3.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "infisical-vault",
    "name": "Infisical",
    "domain": "infisical.com",
    "category": "devops-infrastructure",
    "tagline": "Open-source secret management platform for syncing environment variables and tokens",
    "description": "Infisical provides end-to-end encrypted secret storage with native CLI, SDK, and Kubernetes operator integrations. It serves software developers and cloud engineers seeking open-source Vault alternatives.",
    "rating": 4.9,
    "reviewsCount": 310,
    "pricing": "Freemium",
    "websiteUrl": "https://infisical.com",
    "affiliateUrl": "https://infisical.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "390K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "doppler-secrets",
    "name": "Doppler",
    "domain": "doppler.com",
    "category": "devops-infrastructure",
    "tagline": "Universal secret ops platform for centralizing API keys and configurations",
    "description": "Doppler synchronizes secrets and environment variables securely across local development, GitHub Actions, and cloud providers. It serves developers and DevOps engineers ending .env file sprawl.",
    "rating": 4.9,
    "reviewsCount": 420,
    "pricing": "Freemium",
    "websiteUrl": "https://doppler.com",
    "affiliateUrl": "https://doppler.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "external-dns",
    "name": "ExternalDNS",
    "domain": "kubernetes-sigs.github.io",
    "category": "devops-infrastructure",
    "tagline": "Configure external DNS providers dynamically via Kubernetes resources",
    "description": "ExternalDNS synchronizes exposed Kubernetes Services and Ingresses automatically with external DNS providers like Route53 and Cloudflare. It is built for Kubernetes cluster operators and DevOps leads.",
    "rating": 4.8,
    "reviewsCount": 540,
    "pricing": "Free",
    "websiteUrl": "https://kubernetes-sigs.github.io/external-dns",
    "affiliateUrl": "https://kubernetes-sigs.github.io/external-dns",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "cert-manager-k8s",
    "name": "cert-manager",
    "domain": "cert-manager.io",
    "category": "devops-infrastructure",
    "tagline": "Automated TLS certificate issuance and renewal operator for Kubernetes",
    "description": "cert-manager automates issuing and renewing TLS certificates from Let's Encrypt and private PKI authorities inside Kubernetes clusters. It is an essential component for cloud-native security leads.",
    "rating": 4.9,
    "reviewsCount": 1950,
    "pricing": "Free",
    "websiteUrl": "https://cert-manager.io",
    "affiliateUrl": "https://cert-manager.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "kyverno-policy",
    "name": "Kyverno",
    "domain": "kyverno.io",
    "category": "devops-infrastructure",
    "tagline": "Kubernetes-native policy engine for validation, mutation, and generation",
    "description": "Kyverno manages cluster policy enforcement as native Kubernetes resources without requiring custom OPA Rego coding skills. It serves Kubernetes security teams and platform engineers.",
    "rating": 4.9,
    "reviewsCount": 540,
    "pricing": "Free",
    "websiteUrl": "https://kyverno.io",
    "affiliateUrl": "https://kyverno.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "trivy-aquasec",
    "name": "Trivy",
    "domain": "trivy.dev",
    "category": "devops-infrastructure",
    "tagline": "Comprehensive security scanner for container images, file systems, and IaC",
    "description": "Trivy detects software vulnerabilities, misconfigurations, and leaked secrets across container images and code repositories. It serves DevSecOps teams, container developers, and security auditors.",
    "rating": 4.9,
    "reviewsCount": 1420,
    "pricing": "Free",
    "websiteUrl": "https://trivy.dev",
    "affiliateUrl": "https://trivy.dev",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "falco-runtime",
    "name": "Falco",
    "domain": "falco.org",
    "category": "devops-infrastructure",
    "tagline": "Cloud-native runtime security threat detection engine for Kubernetes",
    "description": "Falco uses Linux kernel system calls to detect unexpected application behavior, intrusion attempts, and privilege escalations in real time. It serves enterprise SOC teams and cloud-native SREs.",
    "rating": 4.8,
    "reviewsCount": 850,
    "pricing": "Free",
    "websiteUrl": "https://falco.org",
    "affiliateUrl": "https://falco.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "920K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "chainguard-images",
    "name": "Chainguard",
    "domain": "chainguard.dev",
    "category": "devops-infrastructure",
    "tagline": "Minimal, secure-by-default container images with zero known vulnerabilities",
    "description": "Chainguard provides distroless, hardened container base images built daily from source with full SBOM attestations. It serves enterprise software engineers and DevSecOps teams securing software supply chains.",
    "rating": 4.9,
    "reviewsCount": 310,
    "pricing": "Freemium",
    "websiteUrl": "https://chainguard.dev",
    "affiliateUrl": "https://chainguard.dev",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "slim-ai",
    "name": "Slim.ai",
    "domain": "slim.ai",
    "category": "devops-infrastructure",
    "tagline": "Automated container optimization, vulnerability reduction, and image minification",
    "description": "Slim.ai analyzes container composition to remove unnecessary packages, minifying container image sizes and reducing security attack surfaces. It serves cloud developers and DevOps leads.",
    "rating": 4.8,
    "reviewsCount": 190,
    "pricing": "Freemium",
    "websiteUrl": "https://slim.ai",
    "affiliateUrl": "https://slim.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "240K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "earthly-ci",
    "name": "Earthly",
    "domain": "earthly.dev",
    "category": "devops-infrastructure",
    "tagline": "Containerized, repeatable build automation framework blending Dockerfile and Makefile concepts",
    "description": "Earthly executes build pipelines inside isolated container sandboxes to guarantee identical execution on local dev laptops and CI servers. It serves software developers and CI/CD engineers.",
    "rating": 4.9,
    "reviewsCount": 420,
    "pricing": "Freemium",
    "websiteUrl": "https://earthly.dev",
    "affiliateUrl": "https://earthly.dev",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "woodpecker-ci",
    "name": "Woodpecker CI",
    "domain": "woodpecker-ci.org",
    "category": "devops-infrastructure",
    "tagline": "Simple, community-driven open-source continuous integration engine built on Docker",
    "description": "Woodpecker CI executes pipeline tasks inside isolated container runtimes configured via simple YAML files. It serves open-source maintainers, self-hosters, and indie software teams.",
    "rating": 4.8,
    "reviewsCount": 210,
    "pricing": "Free",
    "websiteUrl": "https://woodpecker-ci.org",
    "affiliateUrl": "https://woodpecker-ci.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "180K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "drone-ci-harness",
    "name": "Drone CI",
    "domain": "drone.io",
    "category": "devops-infrastructure",
    "tagline": "Container-native self-service continuous integration engine built on Docker",
    "description": "Drone executes every pipeline step inside isolated Docker containers using clean declarative YAML files. It is designed for software developers and DevOps teams wanting fast self-hosted CI.",
    "rating": 4.7,
    "reviewsCount": 920,
    "pricing": "Freemium",
    "websiteUrl": "https://drone.io",
    "affiliateUrl": "https://drone.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "buildkite-cicd",
    "name": "Buildkite",
    "domain": "buildkite.com",
    "category": "devops-infrastructure",
    "tagline": "Hybrid CI/CD platform combining cloud pipeline controls with self-hosted private runners",
    "description": "Buildkite separates pipeline orchestration from build execution, running agent workloads safely inside user private clouds. It serves security-conscious enterprise engineering teams and DevOps leads.",
    "rating": 4.8,
    "reviewsCount": 680,
    "pricing": "Freemium",
    "websiteUrl": "https://buildkite.com",
    "affiliateUrl": "https://buildkite.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "950K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "semaphore-ci",
    "name": "Semaphore",
    "domain": "semaphoreci.com",
    "category": "devops-infrastructure",
    "tagline": "High-speed hosted continuous integration and delivery platform for fast teams",
    "description": "Semaphore delivers lightning-fast CI/CD pipelines with out-of-the-box build caching, monorepo support, and auto-scaling build agents. It serves fast-moving software development teams.",
    "rating": 4.7,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://semaphoreci.com",
    "affiliateUrl": "https://semaphoreci.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "420K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "harness-delivery",
    "name": "Harness",
    "domain": "harness.io",
    "category": "devops-infrastructure",
    "tagline": "End-to-end AI-driven software delivery and developer platform",
    "description": "Harness automates code builds, continuous deployments, cloud cost management, and feature flag management. It is engineered for enterprise DevOps organizations scaling delivery platform operations.",
    "rating": 4.6,
    "reviewsCount": 850,
    "pricing": "Freemium",
    "websiteUrl": "https://harness.io",
    "affiliateUrl": "https://harness.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "octopus-deploy",
    "name": "Octopus Deploy",
    "domain": "octopus.com",
    "category": "devops-infrastructure",
    "tagline": "Automated deployment and release management platform for multi-cloud systems",
    "description": "Octopus Deploy handles complex continuous deployment pipelines, environment configuration variables, and release approvals. It serves enterprise DevOps teams, release engineers, and sysadmins.",
    "rating": 4.8,
    "reviewsCount": 1650,
    "pricing": "Freemium",
    "websiteUrl": "https://octopus.com",
    "affiliateUrl": "https://octopus.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "backstage-spotify",
    "name": "Backstage",
    "domain": "backstage.io",
    "category": "devops-infrastructure",
    "tagline": "Open-source internal developer portal platform created by Spotify",
    "description": "Backstage unifies microservice software catalogs, software templates, technical documentation, and CI tooling into a single portal. It is built for enterprise platform engineers scaling developer experience.",
    "rating": 4.8,
    "reviewsCount": 1450,
    "pricing": "Free",
    "websiteUrl": "https://backstage.io",
    "affiliateUrl": "https://backstage.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "port-devportal",
    "name": "Port",
    "domain": "getport.io",
    "category": "devops-infrastructure",
    "tagline": "No-code developer portal and internal developer platform for platform teams",
    "description": "Port consolidates cloud asset catalogs, developer self-service actions, and software scorecard standards without complex custom code. It is tailored for DevOps managers and platform engineering leads.",
    "rating": 4.9,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://getport.io",
    "affiliateUrl": "https://getport.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "580K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "cortex-devportal",
    "name": "Cortex",
    "domain": "cortex.io",
    "category": "devops-infrastructure",
    "tagline": "Internal developer portal for microservice governance and engineering scorecards",
    "description": "Cortex maps microservice ownership, enforces production readiness scorecards, and tracks security compliance across cloud infrastructure. It serves engineering leaders, CISOs, and platform leads.",
    "rating": 4.8,
    "reviewsCount": 310,
    "pricing": "Free Trial",
    "websiteUrl": "https://cortex.io",
    "affiliateUrl": "https://cortex.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "420K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "compass-atlassian",
    "name": "Compass (Atlassian)",
    "domain": "atlassian.com",
    "category": "devops-infrastructure",
    "tagline": "Developer portal connecting software architecture components and DevOps metrics",
    "description": "Compass tracks microservice component dependencies, team ownership, and deployment health metrics natively in Atlassian Jira environments. It is engineered for platform teams and software engineering leads.",
    "rating": 4.6,
    "reviewsCount": 520,
    "pricing": "Freemium",
    "websiteUrl": "https://atlassian.com/software/compass",
    "affiliateUrl": "https://atlassian.com/software/compass",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "18.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "headlamp-k8s",
    "name": "Headlamp",
    "domain": "headlamp.dev",
    "category": "devops-infrastructure",
    "tagline": "Extensible, open-source web UI dashboard for Kubernetes clusters",
    "description": "Headlamp provides a clean multi-cluster dashboard UI with custom plugin extension capabilities for Kubernetes operators. It is built for Kubernetes developers, cluster admins, and platform teams.",
    "rating": 4.8,
    "reviewsCount": 240,
    "pricing": "Free",
    "websiteUrl": "https://headlamp.dev",
    "affiliateUrl": "https://headlamp.dev",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "310K",
    "isFreeTier": true,
    "isOpenSource": true
  }
];

const targetPath = path.join(__dirname, '../src/data/saasData.jsx');
let content = fs.readFileSync(targetPath, 'utf8');

// Ensure saasCategories has devops-infrastructure
if (!content.includes('"devops-infrastructure"')) {
  console.log('Adding devops-infrastructure category to saasCategories...');
  content = content.replace(
    '  { "id": "nocode-databases", "label": "No-Code Databases & Workflows" }',
    '  { "id": "nocode-databases", "label": "No-Code Databases & Workflows" },\n  { "id": "devops-infrastructure", "label": "DevOps & Cloud Infrastructure" }'
  );
}

// Build existing domains set
const existingDomains = new Set();
const existingNames = new Set();
const domainMatches = content.matchAll(/"domain":\s*"([^"]+)"/g);
for (const match of domainMatches) {
  existingDomains.add(match[1].toLowerCase());
}
const nameMatches = content.matchAll(/"name":\s*"([^"]+)"/g);
for (const match of nameMatches) {
  existingNames.add(match[1].toLowerCase());
}

console.log(`Initial DB has ${existingDomains.size} domains and ${existingNames.size} tool names.`);

const defaultFeatures = [
  "High Availability & Scale",
  "Automated Workflows",
  "Security & Compliance",
  "Cloud Native Operations"
];

const newToolsToInsert = [];
for (const tool of devopsTools) {
  const normDomain = tool.domain.toLowerCase();
  const normName = tool.name.toLowerCase();

  if (existingDomains.has(normDomain) || existingNames.has(normName)) {
    console.log(`[SKIP DUPLICATE] ${tool.name} (${tool.domain})`);
    continue;
  }

  tool.features = defaultFeatures;
  newToolsToInsert.push(tool);
  existingDomains.add(normDomain);
  existingNames.add(normName);
}

console.log(`Found ${newToolsToInsert.length} NEW DevOps tools to insert. Skipped ${devopsTools.length - newToolsToInsert.length} duplicates.`);

if (newToolsToInsert.length > 0) {
  const formattedTools = newToolsToInsert.map(t => JSON.stringify(t, null, 4)).join(',\n');
  const insertionMarker = 'export const staticSaasTools = [\n';
  content = content.replace(insertionMarker, insertionMarker + formattedTools + ',\n');
  fs.writeFileSync(targetPath, content, 'utf8');
  console.log(`Successfully ingested ${newToolsToInsert.length} new DevOps tools into src/data/saasData.jsx!`);
} else {
  console.log('No new tools to insert.');
}
