const fs = require('fs');
const path = require('path');

const newTools = [
  {
    "id": "slack",
    "name": "Slack",
    "domain": "slack.com",
    "category": "collaboration-chat",
    "tagline": "Channel-based messaging platform unifying team chat, huddles, and workflow integrations",
    "description": "Slack organizes team discussions into structured channels alongside real-time voice huddles, screen sharing, and automated app integrations. It is designed for remote, hybrid, and fast-paced modern workforces.",
    "rating": 4.7,
    "reviewsCount": 4200,
    "pricing": "Freemium",
    "websiteUrl": "https://slack.com",
    "affiliateUrl": "https://slack.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "48.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "microsoft-teams",
    "name": "Microsoft Teams",
    "domain": "microsoft.com/en-us/microsoft-teams",
    "category": "collaboration-chat",
    "tagline": "Enterprise workspace combining persistent chat, HD video conferencing, and Office 365 co-editing",
    "description": "Microsoft Teams integrates team channels, high-capacity video meetings, phone calling, and live document collaboration into Microsoft 365. It is built for corporate teams and global enterprise environments.",
    "rating": 4.5,
    "reviewsCount": 5800,
    "pricing": "Freemium",
    "websiteUrl": "https://microsoft.com/en-us/microsoft-teams",
    "affiliateUrl": "https://microsoft.com/en-us/microsoft-teams",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "62.0M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "zoom-meetings",
    "name": "Zoom",
    "domain": "zoom.us",
    "category": "collaboration-chat",
    "tagline": "Reliable HD video conferencing, cloud phone system, team chat, and virtual event suite",
    "description": "Zoom delivers friction-free video calls, breakout rooms, screen sharing, and continuous team chat threads across web and mobile. It serves businesses, educators, and remote workers holding virtual meetings.",
    "rating": 4.6,
    "reviewsCount": 6500,
    "pricing": "Freemium",
    "websiteUrl": "https://zoom.us",
    "affiliateUrl": "https://zoom.us",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "110M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "google-meet",
    "name": "Google Meet",
    "domain": "meet.google.com",
    "category": "collaboration-chat",
    "tagline": "Secure browser-based video conferencing integrated natively into Google Workspace",
    "description": "Google Meet allows users to start or join encrypted video calls directly from Google Calendar, Gmail, or browser tabs without software downloads. It is built for Google Workspace users and distributed teams.",
    "rating": 4.6,
    "reviewsCount": 3800,
    "pricing": "Freemium",
    "websiteUrl": "https://meet.google.com",
    "affiliateUrl": "https://meet.google.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "45.0M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "loom",
    "name": "Loom",
    "domain": "loom.com",
    "category": "collaboration-chat",
    "tagline": "Async video messaging platform to record screen, camera, and voice updates fast",
    "description": "Loom allows workers to record quick screen capture videos with camera bubble overlays to share explanations asynchronously without booking meetings. It is tailored for remote teams and distributed product leads.",
    "rating": 4.8,
    "reviewsCount": 2100,
    "pricing": "Freemium",
    "websiteUrl": "https://loom.com",
    "affiliateUrl": "https://loom.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "18.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "discord",
    "name": "Discord",
    "domain": "discord.com",
    "category": "collaboration-chat",
    "tagline": "Voice, video, and text communication platform featuring always-on audio channels",
    "description": "Discord organizes digital communities and teams into dedicated text channels and low-latency drop-in voice rooms. It is popular among developers, gaming communities, and casual project teams.",
    "rating": 4.7,
    "reviewsCount": 4900,
    "pricing": "Freemium",
    "websiteUrl": "https://discord.com",
    "affiliateUrl": "https://discord.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "140M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "mattermost",
    "name": "Mattermost",
    "domain": "mattermost.com",
    "category": "collaboration-chat",
    "tagline": "Open-source, self-hostable secure team messaging and developer collaboration platform",
    "description": "Mattermost provides encrypted channel-based chat, audio calls, and incident management with full self-hosted data ownership. It is engineered for technical DevOps, defense, and security-sensitive organizations.",
    "rating": 4.6,
    "reviewsCount": 920,
    "pricing": "Freemium",
    "websiteUrl": "https://mattermost.com",
    "affiliateUrl": "https://mattermost.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "rocket-chat",
    "name": "Rocket.Chat",
    "domain": "rocket.chat",
    "category": "collaboration-chat",
    "tagline": "Open-source communications platform for team messaging and secure customer chat",
    "description": "Rocket.Chat enables self-hosted team messaging, matrix federation, direct file sharing, and omni-channel customer service chat. It serves government, healthcare, and enterprise security operations.",
    "rating": 4.5,
    "reviewsCount": 850,
    "pricing": "Freemium",
    "websiteUrl": "https://rocket.chat",
    "affiliateUrl": "https://rocket.chat",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "element-io",
    "name": "Element",
    "domain": "element.io",
    "category": "collaboration-chat",
    "tagline": "Decentralized, end-to-end encrypted messaging and collaboration built on Matrix",
    "description": "Element offers zero-knowledge encrypted group messaging, voice calls, and file transfers operating on the open Matrix protocol. It is built for privacy purists, web3 organizations, and sovereign networks.",
    "rating": 4.6,
    "reviewsCount": 420,
    "pricing": "Freemium",
    "websiteUrl": "https://element.io",
    "affiliateUrl": "https://element.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "890K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "cisco-webex",
    "name": "Cisco Webex",
    "domain": "webex.com",
    "category": "collaboration-chat",
    "tagline": "Enterprise video conferencing, cloud calling, and secure team collaboration suite",
    "description": "Webex delivers high-definition video meetings, noise removal, real-time speech translation, and hardware room integrations. It is engineered for large enterprises and global corporate environments.",
    "rating": 4.4,
    "reviewsCount": 3100,
    "pricing": "Freemium",
    "websiteUrl": "https://webex.com",
    "affiliateUrl": "https://webex.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "12.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "twist-app",
    "name": "Twist by Doist",
    "domain": "twist.com",
    "category": "collaboration-chat",
    "tagline": "Threaded, asynchronous team messaging software designed to prevent work burn-out",
    "description": "Twist replaces real-time chat chaos with structured, topic-focused discussion threads and silent notification defaults. It is built for remote teams prioritizing deep focus work and async communication.",
    "rating": 4.6,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://twist.com",
    "affiliateUrl": "https://twist.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "450K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "basecamp-campfire",
    "name": "Basecamp",
    "domain": "basecamp.com",
    "category": "collaboration-chat",
    "tagline": "Project management platform with built-in Campfire chat rooms and message boards",
    "description": "Basecamp organizes team work using message boards, task lists, schedule calendars, and Campfire real-time chat spaces. It serves small businesses, creative agencies, and remote teams.",
    "rating": 4.5,
    "reviewsCount": 2400,
    "pricing": "Paid",
    "websiteUrl": "https://basecamp.com",
    "affiliateUrl": "https://basecamp.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "around-co",
    "name": "Around by Miro",
    "domain": "around.co",
    "category": "collaboration-chat",
    "tagline": "Video call app designed for hybrid teams with minimal camera heads and AI framing",
    "description": "Around presents video call participants in small floating circles over desktop workspaces, reducing screen clutter during co-working. It is built for designers, developers, and agile product teams.",
    "rating": 4.7,
    "reviewsCount": 310,
    "pricing": "Freemium",
    "websiteUrl": "https://around.co",
    "affiliateUrl": "https://around.co",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "380K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "ringcentral-video",
    "name": "RingCentral",
    "domain": "ringcentral.com",
    "category": "collaboration-chat",
    "tagline": "Cloud phone system, team chat, and business video meetings in one workspace",
    "description": "RingCentral unifies corporate PBX VoIP calling, team messaging, and cloud video conferencing into an enterprise cloud platform. It serves business communication and phone center operations.",
    "rating": 4.4,
    "reviewsCount": 2800,
    "pricing": "Free Trial",
    "websiteUrl": "https://ringcentral.com",
    "affiliateUrl": "https://ringcentral.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "8.9M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "goto-meeting",
    "name": "GoTo Meeting",
    "domain": "goto.com/meeting",
    "category": "collaboration-chat",
    "tagline": "High-security corporate web conferencing and online meeting software",
    "description": "GoTo Meeting provides encrypted online video calls, meeting drawing tools, screen sharing, and transcription services. It is designed for mid-market business meetings and sales presentations.",
    "rating": 4.3,
    "reviewsCount": 2100,
    "pricing": "Free Trial",
    "websiteUrl": "https://goto.com/meeting",
    "affiliateUrl": "https://goto.com/meeting",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "5.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "zoho-cliq",
    "name": "Zoho Cliq",
    "domain": "zoho.com/cliq",
    "category": "collaboration-chat",
    "tagline": "Affordable team chat, voice channels, and video calling integrated with Zoho CRM",
    "description": "Zoho Cliq connects teams through channel messaging, direct audio/video calls, and automated workflow bots. It is optimized for businesses operating within the Zoho software ecosystem.",
    "rating": 4.5,
    "reviewsCount": 680,
    "pricing": "Freemium",
    "websiteUrl": "https://zoho.com/cliq",
    "affiliateUrl": "https://zoho.com/cliq",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "chanty",
    "name": "Chanty",
    "domain": "chanty.com",
    "category": "collaboration-chat",
    "tagline": "Simple AI-powered team chat app with built-in Kanban task management",
    "description": "Chanty combines team messaging channels, voice/video calling, and voice message notes with visual task assignment. It is designed for small teams and non-technical business units.",
    "rating": 4.6,
    "reviewsCount": 340,
    "pricing": "Freemium",
    "websiteUrl": "https://chanty.com",
    "affiliateUrl": "https://chanty.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "290K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "flock-chat",
    "name": "Flock",
    "domain": "flock.com",
    "category": "collaboration-chat",
    "tagline": "All-in-one team messenger, task manager, and video calling app",
    "description": "Flock brings team chat channels, direct messaging, interactive polls, shared to-do lists, and 1-on-1 video calls together. It is built for small business collaboration.",
    "rating": 4.4,
    "reviewsCount": 450,
    "pricing": "Freemium",
    "websiteUrl": "https://flock.com",
    "affiliateUrl": "https://flock.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "troop-messenger",
    "name": "Troop Messenger",
    "domain": "troopmessenger.com",
    "category": "collaboration-chat",
    "tagline": "Secure team chat and instant messaging application for business operations",
    "description": "Troop Messenger offers encrypted channel messaging, remote desktop control, screen sharing, and self-hosting options. It serves defense, enterprise, and office communication teams.",
    "rating": 4.6,
    "reviewsCount": 210,
    "pricing": "Free Trial",
    "websiteUrl": "https://troopmessenger.com",
    "affiliateUrl": "https://troopmessenger.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "180K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "pumble",
    "name": "Pumble",
    "domain": "pumble.com",
    "category": "collaboration-chat",
    "tagline": "Free team chat app with unlimited user history and channel communication",
    "description": "Pumble provides unlimited searchable message history, channel organization, and direct video calling without restrictive user limits. It is designed for startups and budget-conscious small teams.",
    "rating": 4.7,
    "reviewsCount": 280,
    "pricing": "Freemium",
    "websiteUrl": "https://pumble.com",
    "affiliateUrl": "https://pumble.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "850K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "gather-town",
    "name": "Gather",
    "domain": "gather.town",
    "category": "collaboration-chat",
    "tagline": "Virtual 2D office space platform for spontaneous team interactions and events",
    "description": "Gather creates 8-bit style virtual office environments where proximity video chat activates when avatars walk near each other. It is built for remote company culture, virtual conferences, and co-working.",
    "rating": 4.8,
    "reviewsCount": 610,
    "pricing": "Freemium",
    "websiteUrl": "https://gather.town",
    "affiliateUrl": "https://gather.town",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "3.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "whereby",
    "name": "Whereby",
    "domain": "whereby.com",
    "category": "collaboration-chat",
    "tagline": "No-download video calls and embeddable video meeting APIs for websites",
    "description": "Whereby provides instant link-based video meetings in browser tabs alongside embeddable video room SDKs for developers. It is built for telehealth, online tutoring, and remote teams.",
    "rating": 4.7,
    "reviewsCount": 540,
    "pricing": "Freemium",
    "websiteUrl": "https://whereby.com",
    "affiliateUrl": "https://whereby.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.9M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "screen-studio",
    "name": "Screen Studio",
    "domain": "screen.studio",
    "category": "collaboration-chat",
    "tagline": "Produce beautiful, auto-zoomed screen recordings and video demos on macOS",
    "description": "Screen Studio turns desktop screen recordings into professional video presentations with automated smooth zooms and cursor motion smoothing. It serves product managers, founders, and async communicators.",
    "rating": 4.9,
    "reviewsCount": 890,
    "pricing": "Paid",
    "websiteUrl": "https://screen.studio",
    "affiliateUrl": "https://screen.studio",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "tella-tv",
    "name": "Tella",
    "domain": "tella.tv",
    "category": "collaboration-chat",
    "tagline": "Browser-based screen recorder and video editor for async demos and courses",
    "description": "Tella records camera and screen footage simultaneously, allowing instant layout edits, custom backgrounds, and web video sharing. It is tailored for content creators, course instructors, and remote teams.",
    "rating": 4.8,
    "reviewsCount": 310,
    "pricing": "Freemium",
    "websiteUrl": "https://tella.tv",
    "affiliateUrl": "https://tella.tv",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "snagit-techsmith",
    "name": "Snagit",
    "domain": "techsmith.com/screen-capture.html",
    "category": "collaboration-chat",
    "tagline": "Screen capture and video recording software for documentation and visual updates",
    "description": "Snagit captures desktop screens and audio recordings, adding visual callouts, step graphics, and text edits for async documentation. It serves technical writers, trainers, and support teams.",
    "rating": 4.7,
    "reviewsCount": 2100,
    "pricing": "Free Trial",
    "websiteUrl": "https://techsmith.com/screen-capture.html",
    "affiliateUrl": "https://techsmith.com/screen-capture.html",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "vimeo-record",
    "name": "Vimeo Record",
    "domain": "vimeo.com/features/screen-recorder",
    "category": "collaboration-chat",
    "tagline": "Free screen and webcam recorder tool for instant async team messaging",
    "description": "Vimeo Record captures browser and desktop video messages, saving recordings directly into cloud video folders for team review. It serves creative agencies, design teams, and marketers.",
    "rating": 4.6,
    "reviewsCount": 1250,
    "pricing": "Freemium",
    "websiteUrl": "https://vimeo.com/features/screen-recorder",
    "affiliateUrl": "https://vimeo.com/features/screen-recorder",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "18.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "clipchamp-microsoft",
    "name": "Microsoft Clipchamp",
    "domain": "clipchamp.com",
    "category": "collaboration-chat",
    "tagline": "In-browser video editor and webcam recorder built into Windows 11",
    "description": "Clipchamp enables easy webcam recording, screen capture, text-to-speech voiceovers, and video editing directly in browser tabs. It is built for corporate teams and social video creators.",
    "rating": 4.5,
    "reviewsCount": 1850,
    "pricing": "Freemium",
    "websiteUrl": "https://clipchamp.com",
    "affiliateUrl": "https://clipchamp.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "14.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "claap-io",
    "name": "Claap",
    "domain": "claap.io",
    "category": "collaboration-chat",
    "tagline": "Async video workspace and AI meeting recorder for product teams",
    "description": "Claap combines screen recording video messages with AI meeting summaries, timestamped comments, and central video wikis. It serves product managers, design reviewers, and remote leads.",
    "rating": 4.8,
    "reviewsCount": 190,
    "pricing": "Freemium",
    "websiteUrl": "https://claap.io",
    "affiliateUrl": "https://claap.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "210K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "zight-cloudapp",
    "name": "Zight (formerly CloudApp)",
    "domain": "zight.com",
    "category": "collaboration-chat",
    "tagline": "Visual communication tool for instant screen recordings, GIFs, and screenshots",
    "description": "Zight creates shareable screen videos, annotated screenshots, and animated GIFs instantly saved to auto-copied web links. It is engineered for customer support agents, engineers, and sales reps.",
    "rating": 4.6,
    "reviewsCount": 1100,
    "pricing": "Freemium",
    "websiteUrl": "https://zight.com",
    "affiliateUrl": "https://zight.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "vidyard",
    "name": "Vidyard",
    "domain": "vidyard.com",
    "category": "collaboration-chat",
    "tagline": "Video messaging and screen recording platform built for B2B sales teams",
    "description": "Vidyard enables sales reps to send personal video messages, track viewer engagement, and record screen walkthroughs inside email sequences. It serves SDRs, sales reps, and customer success.",
    "rating": 4.5,
    "reviewsCount": 1650,
    "pricing": "Freemium",
    "websiteUrl": "https://vidyard.com",
    "affiliateUrl": "https://vidyard.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "pop-in-pronto",
    "name": "Pronto",
    "domain": "pronto.io",
    "category": "collaboration-chat",
    "tagline": "Real-time chat and video messaging platform for higher education and frontline teams",
    "description": "Pronto connects students, instructors, and frontline workers through real-time chat, video messaging, and live language translation. It serves educational campuses and distributed workforces.",
    "rating": 4.7,
    "reviewsCount": 320,
    "pricing": "Paid",
    "websiteUrl": "https://pronto.io",
    "affiliateUrl": "https://pronto.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "rock-so",
    "name": "Rock",
    "domain": "rock.so",
    "category": "collaboration-chat",
    "tagline": "All-in-one messaging app combining messaging, tasks, notes, and file drive",
    "description": "Rock unifies real-time messaging, task boards, note files, and Google Drive integrations inside project spaces. It is designed for remote teams collaborating with external clients and freelancers.",
    "rating": 4.7,
    "reviewsCount": 210,
    "pricing": "Freemium",
    "websiteUrl": "https://rock.so",
    "affiliateUrl": "https://rock.so",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "280K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "jam-dev",
    "name": "Jam",
    "domain": "jam.dev",
    "category": "collaboration-chat",
    "tagline": "One-click screen recording and automated bug reporting tool for developers",
    "description": "Jam logs screen video, console logs, network requests, and browser specs in one link for software engineers. It serves QA testers, product managers, and developers fixing web bugs faster.",
    "rating": 4.9,
    "reviewsCount": 580,
    "pricing": "Freemium",
    "websiteUrl": "https://jam.dev",
    "affiliateUrl": "https://jam.dev",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "820K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "otter-ai",
    "name": "Otter.ai",
    "domain": "otter.ai",
    "category": "collaboration-chat",
    "tagline": "AI meeting assistant for real-time transcription, automated notes, and action items",
    "description": "Otter.ai automatically joins Zoom, Google Meet, and Teams calls to transcribe discussions, extract action items, and generate summary slide captures. It is built for remote professionals and students.",
    "rating": 4.6,
    "reviewsCount": 3100,
    "pricing": "Freemium",
    "websiteUrl": "https://otter.ai",
    "affiliateUrl": "https://otter.ai",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "9.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "fireflies-ai",
    "name": "Fireflies.ai",
    "domain": "fireflies.ai",
    "category": "collaboration-chat",
    "tagline": "AI meeting recorder and conversation intelligence engine across call channels",
    "description": "Fireflies.ai records, transcribes, and searches call topics across web conferencing applications automatically. It is built for sales development teams, recruiters, and corporate managers.",
    "rating": 4.7,
    "reviewsCount": 1820,
    "pricing": "Freemium",
    "websiteUrl": "https://fireflies.ai",
    "affiliateUrl": "https://fireflies.ai",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "4.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "fathom-video",
    "name": "Fathom",
    "domain": "fathom.video",
    "category": "collaboration-chat",
    "tagline": "Free AI meeting recorder that transcribes, highlights, and summarizes video calls",
    "description": "Fathom transcribes Zoom, Teams, and Google Meet calls, generating AI meeting summaries and syncing notes straight into CRMs. It is completely free for individual team members.",
    "rating": 4.9,
    "reviewsCount": 1420,
    "pricing": "Freemium",
    "websiteUrl": "https://fathom.video",
    "affiliateUrl": "https://fathom.video",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "3.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "tl-dv",
    "name": "tl;dv",
    "domain": "tldv.io",
    "category": "collaboration-chat",
    "tagline": "AI meeting recorder for Google Meet and Zoom with automatic clip generation",
    "description": "tl;dv transcribes meetings in 40+ languages, generates topic summaries, and allows users to make shareable video clips of key call moments. It is built for remote sales and product teams.",
    "rating": 4.8,
    "reviewsCount": 950,
    "pricing": "Freemium",
    "websiteUrl": "https://tldv.io",
    "affiliateUrl": "https://tldv.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "avoma",
    "name": "Avoma",
    "domain": "avoma.com",
    "category": "collaboration-chat",
    "tagline": "AI meeting lifecycle assistant and conversation intelligence platform",
    "description": "Avoma automates pre-meeting agendas, AI transcription, conversation insights, and CRM updates across sales calls. It is designed for revenue teams, customer success, and managers.",
    "rating": 4.6,
    "reviewsCount": 480,
    "pricing": "Freemium",
    "websiteUrl": "https://avoma.com",
    "affiliateUrl": "https://avoma.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "supernormal",
    "name": "Supernormal",
    "domain": "supernormal.com",
    "category": "collaboration-chat",
    "tagline": "AI note-taker that automatically captures formatted meeting notes and action items",
    "description": "Supernormal transcribes and formats meeting notes into customized bulleted summaries for Google Meet, Teams, and Zoom. It serves executives, project managers, and remote workers.",
    "rating": 4.7,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://supernormal.com",
    "affiliateUrl": "https://supernormal.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "850K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "grain-com",
    "name": "Grain",
    "domain": "grain.com",
    "category": "collaboration-chat",
    "tagline": "AI automated meeting recording, transcription, and customer insight clipping",
    "description": "Grain records customer interviews and sales calls, summarizing takeaways and generating shareable video highlight reels. It serves UX researchers, product managers, and sales reps.",
    "rating": 4.7,
    "reviewsCount": 510,
    "pricing": "Freemium",
    "websiteUrl": "https://grain.com",
    "affiliateUrl": "https://grain.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "920K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "bluedot-ai",
    "name": "Bluedot",
    "domain": "bluedot.ai",
    "category": "collaboration-chat",
    "tagline": "Chrome extension AI meeting recorder for Google Meet with zero bot joiners",
    "description": "Bluedot records and transcribes Google Meet calls directly in browser without sending visible bot accounts into the meeting room. It is built for privacy-conscious consultants and sales reps.",
    "rating": 4.8,
    "reviewsCount": 160,
    "pricing": "Freemium",
    "websiteUrl": "https://bluedot.ai",
    "affiliateUrl": "https://bluedot.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "240K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "krisp-call",
    "name": "Krisp Call",
    "domain": "krispcall.com",
    "category": "collaboration-chat",
    "tagline": "Virtual cloud phone system for remote business team calling and SMS",
    "description": "KrispCall provides international virtual phone numbers, call forwarding, shared contact centers, and team voicemail boxes. It serves remote support teams, sales reps, and call centers.",
    "rating": 4.5,
    "reviewsCount": 290,
    "pricing": "Paid",
    "websiteUrl": "https://krispcall.com",
    "affiliateUrl": "https://krispcall.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "380K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "openphone",
    "name": "OpenPhone",
    "domain": "openphone.com",
    "category": "collaboration-chat",
    "tagline": "Modern collaborative business phone app for startups and small teams",
    "description": "OpenPhone provides virtual business phone numbers with shared team inboxes, automated text messaging, and call recording capabilities. It is designed for growing startups, agencies, and small businesses.",
    "rating": 4.7,
    "reviewsCount": 1150,
    "pricing": "Free Trial",
    "websiteUrl": "https://openphone.com",
    "affiliateUrl": "https://openphone.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "2.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "dialpad-meetings",
    "name": "Dialpad",
    "domain": "dialpad.com",
    "category": "collaboration-chat",
    "tagline": "AI-powered workspace for business phone, team messaging, and video calls",
    "description": "Dialpad offers HD video meetings, business VoIP calling, real-time call transcription, and live sentiment analysis powered by AI. It serves modern sales teams, customer support, and enterprises.",
    "rating": 4.5,
    "reviewsCount": 2100,
    "pricing": "Free Trial",
    "websiteUrl": "https://dialpad.com",
    "affiliateUrl": "https://dialpad.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "clickmeeting",
    "name": "ClickMeeting",
    "domain": "clickmeeting.com",
    "category": "collaboration-chat",
    "tagline": "Webinar, online training, and large-scale video conferencing platform",
    "description": "ClickMeeting enables hosting online webinars, screen sharing demonstrations, interactive polls, and virtual team meetings. It is engineered for online educators, trainers, and marketing teams.",
    "rating": 4.4,
    "reviewsCount": 820,
    "pricing": "Free Trial",
    "websiteUrl": "https://clickmeeting.com",
    "affiliateUrl": "https://clickmeeting.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "livestorm",
    "name": "Livestorm",
    "domain": "livestorm.co",
    "category": "collaboration-chat",
    "tagline": "Browser-based video engagement platform for webinars and virtual meetings",
    "description": "Livestorm provides online webinar hosting, registration page building, automated email reminders, and in-depth attendee analytics. It serves marketing agencies, sales teams, and educators.",
    "rating": 4.6,
    "reviewsCount": 1100,
    "pricing": "Freemium",
    "websiteUrl": "https://livestorm.co",
    "affiliateUrl": "https://livestorm.co",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "demio-webinar",
    "name": "Demio",
    "domain": "demio.com",
    "category": "collaboration-chat",
    "tagline": "Hassle-free webinar software built for marketing and audience engagement",
    "description": "Demio delivers interactive live, automated, and hybrid webinar events with custom registration landing pages and real-time chat. It is engineered for SaaS marketers and digital educators.",
    "rating": 4.7,
    "reviewsCount": 520,
    "pricing": "Free Trial",
    "websiteUrl": "https://demio.com",
    "affiliateUrl": "https://demio.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "950K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "bigbluebutton",
    "name": "BigBlueButton",
    "domain": "bigbluebutton.org",
    "category": "collaboration-chat",
    "tagline": "Open-source web conferencing system built specifically for online learning",
    "description": "BigBlueButton features real-time multi-user whiteboards, breakout rooms, poll creation, and document sharing tailored for virtual classrooms. It serves schools, universities, and online teachers.",
    "rating": 4.5,
    "reviewsCount": 650,
    "pricing": "Free",
    "websiteUrl": "https://bigbluebutton.org",
    "affiliateUrl": "https://bigbluebutton.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "jitsi-meet",
    "name": "Jitsi Meet",
    "domain": "jitsi.org",
    "category": "collaboration-chat",
    "tagline": "100% free open-source encrypted video conferencing with zero registration required",
    "description": "Jitsi Meet allows users to spin up instant, encrypted video calls in browser without creating user accounts or installing apps. It is engineered for privacy purists, open-source communities, and developers.",
    "rating": 4.6,
    "reviewsCount": 1400,
    "pricing": "Free",
    "websiteUrl": "https://jitsi.org",
    "affiliateUrl": "https://jitsi.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "slido",
    "name": "Slido",
    "domain": "slido.com",
    "category": "collaboration-chat",
    "tagline": "Audience interaction platform for live Q&A, polls, and quiz participation",
    "description": "Slido engages meeting attendees and webinar participants with real-time live polling, word cloud generations, and upvoted Q&A sessions. It serves corporate leaders, event hosts, and educators.",
    "rating": 4.7,
    "reviewsCount": 2400,
    "pricing": "Freemium",
    "websiteUrl": "https://slido.com",
    "affiliateUrl": "https://slido.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "6.8M",
    "isFreeTier": true,
    "isOpenSource": false
  }
];

const saasDataPath = path.join(__dirname, '..', 'src', 'data', 'saasData.jsx');
let content = fs.readFileSync(saasDataPath, 'utf8');

const match = content.match(/export const staticSaasTools = (\[[\s\S]*?\n\]);/);
if (!match) {
  console.error('Could not find staticSaasTools in saasData.jsx');
  process.exit(1);
}

let existingTools = JSON.parse(match[1]);

const existingIds = new Set(existingTools.map(t => t.id.toLowerCase()));
const existingNames = new Set(existingTools.map(t => t.name.toLowerCase()));

let addedCount = 0;
let skippedCount = 0;

newTools.forEach(tool => {
  const normId = tool.id.toLowerCase();
  const normName = tool.name.toLowerCase();

  if (!existingIds.has(normId) && !existingNames.has(normName)) {
    existingTools.push(tool);
    existingIds.add(normId);
    existingNames.add(normName);
    addedCount++;
  } else {
    // Enrich existing tool without creating a duplicate
    const idx = existingTools.findIndex(t => t.id.toLowerCase() === normId || t.name.toLowerCase() === normName);
    if (idx !== -1) {
      existingTools[idx] = { ...existingTools[idx], category: tool.category, tagline: tool.tagline || existingTools[idx].tagline };
    }
    skippedCount++;
  }
});

const updatedArrayStr = JSON.stringify(existingTools, null, 2);
content = content.replace(/export const staticSaasTools = \[[\s\S]*?\n\];/, `export const staticSaasTools = ${updatedArrayStr};`);

fs.writeFileSync(saasDataPath, content, 'utf8');
console.log(`Ingestion Complete! Added: ${addedCount} brand new tools | Deduplicated: ${skippedCount} existing tools | Total static tools: ${existingTools.length}`);
