const fs = require('fs');
const path = require('path');

const newTools = [
  {
    "id": "github-copilot",
    "name": "GitHub Copilot",
    "domain": "github.com/features/copilot",
    "category": "developer-tools",
    "tagline": "AI pair programmer providing real-time code completions and chat assistance",
    "description": "GitHub Copilot suggests code snippets, refactors functions, and answers technical queries directly inside your IDE. It is built for software developers, engineers, and teams accelerating daily code output.",
    "rating": 4.8,
    "reviewsCount": 4200,
    "pricing": "Paid",
    "websiteUrl": "https://github.com/features/copilot",
    "affiliateUrl": "https://github.com/features/copilot",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "85.0M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "cursor",
    "name": "Cursor",
    "domain": "cursor.com",
    "category": "developer-tools",
    "tagline": "AI-first code editor engineered for fast codebase editing and multi-file changes",
    "description": "Cursor is a VS Code fork built from the ground up for AI-assisted editing, predictive edits, and intelligent codebase chat. It serves software engineers and product developers seeking seamless AI integration.",
    "rating": 4.9,
    "reviewsCount": 1850,
    "pricing": "Freemium",
    "websiteUrl": "https://cursor.com",
    "affiliateUrl": "https://cursor.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "12.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "postman",
    "name": "Postman",
    "domain": "postman.com",
    "category": "developer-tools",
    "tagline": "Complete API platform for building, testing, and documenting APIs",
    "description": "Postman simplifies API development by enabling engineers to execute requests, mock servers, and run automated API test suites. It is designed for backend developers, QA engineers, and API architects.",
    "rating": 4.7,
    "reviewsCount": 5400,
    "pricing": "Freemium",
    "websiteUrl": "https://postman.com",
    "affiliateUrl": "https://postman.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "28.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "visual-studio-code",
    "name": "Visual Studio Code",
    "domain": "code.visualstudio.com",
    "category": "developer-tools",
    "tagline": "Free, open-source source code editor with rich extension ecosystem",
    "description": "VS Code provides lightweight code editing, integrated debugging, Git controls, and thousands of extensions. It is the world's most popular code editor for web, cloud, and mobile developers.",
    "rating": 4.9,
    "reviewsCount": 8900,
    "pricing": "Free",
    "websiteUrl": "https://code.visualstudio.com",
    "affiliateUrl": "https://code.visualstudio.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "42.0M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "insomnia",
    "name": "Insomnia",
    "domain": "insomnia.rest",
    "category": "developer-tools",
    "tagline": "Open-source API client for REST, GraphQL, gRPC, and OpenAPI design",
    "description": "Insomnia streamlines API debugging with clean request management, environment variables, and OpenAPI schema generation. It serves backend engineers, full-stack developers, and API teams.",
    "rating": 4.7,
    "reviewsCount": 1150,
    "pricing": "Freemium",
    "websiteUrl": "https://insomnia.rest",
    "affiliateUrl": "https://insomnia.rest",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "hoppscotch",
    "name": "Hoppscotch",
    "domain": "hoppscotch.io",
    "category": "developer-tools",
    "tagline": "Open-source, lightweight web-first API development ecosystem",
    "description": "Hoppscotch offers a fast, browser-based API testing client supporting REST, GraphQL, and WebSockets without installation bloat. It is built for web developers and open-source advocates.",
    "rating": 4.8,
    "reviewsCount": 920,
    "pricing": "Free",
    "websiteUrl": "https://hoppscotch.io",
    "affiliateUrl": "https://hoppscotch.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "tabnine",
    "name": "Tabnine",
    "domain": "tabnine.com",
    "category": "developer-tools",
    "tagline": "Context-aware, privacy-focused AI code completion engine for teams",
    "description": "Tabnine provides localized AI code completions and chat that respect data privacy and offer self-hosted deployment options. It serves security-conscious enterprise engineering teams and developers.",
    "rating": 4.5,
    "reviewsCount": 1650,
    "pricing": "Freemium",
    "websiteUrl": "https://tabnine.com",
    "affiliateUrl": "https://tabnine.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "codeium",
    "name": "Codeium (Windsurf)",
    "domain": "codeium.com",
    "category": "developer-tools",
    "tagline": "Ultra-fast AI code acceleration engine and Windsurf editor platform",
    "description": "Codeium delivers free, high-speed multi-language code completions and agentic editing capabilities across all major IDEs. It is tailored for individual programmers, students, and professional developers.",
    "rating": 4.8,
    "reviewsCount": 1420,
    "pricing": "Freemium",
    "websiteUrl": "https://codeium.com",
    "affiliateUrl": "https://codeium.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "4.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "jetbrains-intellij-idea",
    "name": "IntelliJ IDEA",
    "domain": "jetbrains.com/idea",
    "category": "developer-tools",
    "tagline": "The premier Java and Kotlin IDE with deep static code analysis",
    "description": "IntelliJ IDEA provides intelligent refactoring, smart code completion, and enterprise framework support for JVM languages. It is the industry standard for Java developers, Kotlin engineers, and enterprise software teams.",
    "rating": 4.8,
    "reviewsCount": 3800,
    "pricing": "Freemium",
    "websiteUrl": "https://jetbrains.com/idea",
    "affiliateUrl": "https://jetbrains.com/idea",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "18.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "pycharm",
    "name": "PyCharm",
    "domain": "jetbrains.com/pycharm",
    "category": "developer-tools",
    "tagline": "Dedicated Python IDE for professional developers and data scientists",
    "description": "PyCharm offers automated refactoring, code inspection, Django framework tools, and integrated Jupyter notebooks. It is engineered for Python developers, backend engineers, and machine learning researchers.",
    "rating": 4.7,
    "reviewsCount": 2900,
    "pricing": "Freemium",
    "websiteUrl": "https://jetbrains.com/pycharm",
    "affiliateUrl": "https://jetbrains.com/pycharm",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "12.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "webstorm",
    "name": "WebStorm",
    "domain": "jetbrains.com/webstorm",
    "category": "developer-tools",
    "tagline": "The smartest JavaScript and TypeScript IDE for modern web development",
    "description": "WebStorm provides advanced auto-imports, refactoring, integrated testing, and debugging for React, Vue, Angular, and Node.js. It serves professional frontend and full-stack web developers.",
    "rating": 4.7,
    "reviewsCount": 2100,
    "pricing": "Paid",
    "websiteUrl": "https://jetbrains.com/webstorm",
    "affiliateUrl": "https://jetbrains.com/webstorm",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "8.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "neovim",
    "name": "Neovim",
    "domain": "neovim.io",
    "category": "developer-tools",
    "tagline": "Hyperextensible, Vim-based text editor built for extreme terminal speed",
    "description": "Neovim refactors classic Vim with Lua scripting, asynchronous plugin execution, and native Language Server Protocol (LSP) integration. It is favored by command-line power users, systems engineers, and Linux enthusiasts.",
    "rating": 4.9,
    "reviewsCount": 2400,
    "pricing": "Free",
    "websiteUrl": "https://neovim.io",
    "affiliateUrl": "https://neovim.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "zed-editor",
    "name": "Zed",
    "domain": "zed.dev",
    "category": "developer-tools",
    "tagline": "High-performance, GPU-accelerated code editor written in Rust",
    "description": "Zed delivers blazingly fast text rendering, real-time multiplayer code collaboration, and native AI assist tools in a lightweight footprint. It serves performance-focused software engineers and open-source developers.",
    "rating": 4.8,
    "reviewsCount": 850,
    "pricing": "Free",
    "websiteUrl": "https://zed.dev",
    "affiliateUrl": "https://zed.dev",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "2.4M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "sublime-text",
    "name": "Sublime Text",
    "domain": "sublimetext.com",
    "category": "developer-tools",
    "tagline": "Sophisticated text editor for code, markup, and prose with instant startup",
    "description": "Sublime Text offers ultra-fast file navigation, GPU rendering, multiple selections, and lightweight resource utilization. It is designed for developers wanting a fast, uncluttered text editing environment.",
    "rating": 4.6,
    "reviewsCount": 3100,
    "pricing": "Free Trial",
    "websiteUrl": "https://sublimetext.com",
    "affiliateUrl": "https://sublimetext.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "bruno-api",
    "name": "Bruno",
    "domain": "usebruno.com",
    "category": "developer-tools",
    "tagline": "Fast, privacy-first, open-source offline API client storing requests as files",
    "description": "Bruno stores API collection files directly inside Git repositories using plain text markup without forced cloud sync. It is built for developers who want offline, version-controlled API testing.",
    "rating": 4.9,
    "reviewsCount": 620,
    "pricing": "Freemium",
    "websiteUrl": "https://usebruno.com",
    "affiliateUrl": "https://usebruno.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "curl",
    "name": "cURL",
    "domain": "curl.se",
    "category": "developer-tools",
    "tagline": "The universal command-line tool for transferring data with URL syntax",
    "description": "cURL is the foundational open-source command-line tool used to test endpoints, fetch files, and send HTTP requests across network protocols. It is used daily by virtually every software engineer worldwide.",
    "rating": 4.9,
    "reviewsCount": 4800,
    "pricing": "Free",
    "websiteUrl": "https://curl.se",
    "affiliateUrl": "https://curl.se",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.5M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "tableplus",
    "name": "TablePlus",
    "domain": "tableplus.com",
    "category": "developer-tools",
    "tagline": "Modern, native, and elegant database GUI client for relational databases",
    "description": "TablePlus offers a fast, multi-tab database management interface for PostgreSQL, MySQL, SQLite, Redis, and MongoDB. It serves backend engineers, DBA managers, and full-stack developers.",
    "rating": 4.8,
    "reviewsCount": 1450,
    "pricing": "Freemium",
    "websiteUrl": "https://tableplus.com",
    "affiliateUrl": "https://tableplus.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.9M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "dbeaver",
    "name": "DBeaver",
    "domain": "dbeaver.io",
    "category": "developer-tools",
    "tagline": "Free multi-platform database tool for developers, SQL programmers, and analysts",
    "description": "DBeaver provides an open-source universal database GUI supporting over 100 database engines with ER diagram drafting and SQL editing. It is built for database admins and backend software leads.",
    "rating": 4.7,
    "reviewsCount": 2100,
    "pricing": "Freemium",
    "websiteUrl": "https://dbeaver.io",
    "affiliateUrl": "https://dbeaver.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "gitkraken",
    "name": "GitKraken Client",
    "domain": "gitkraken.com",
    "category": "developer-tools",
    "tagline": "Intuitive GUI Git client with commit graphs, conflict resolution, and workspace boards",
    "description": "GitKraken visualizes Git branching structures, simplifies merge conflict resolution, and integrates with GitHub, GitLab, and Bitbucket. It serves software teams navigating complex version control trees.",
    "rating": 4.6,
    "reviewsCount": 1820,
    "pricing": "Freemium",
    "websiteUrl": "https://gitkraken.com",
    "affiliateUrl": "https://gitkraken.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "sourcetree",
    "name": "Sourcetree",
    "domain": "sourcetreeapp.com",
    "category": "developer-tools",
    "tagline": "Free visual Git desktop client for Windows and Mac",
    "description": "Sourcetree simplifies Git interactions through a clean desktop interface for reviewing commits, managing branches, and staging hunks. It is tailored for developers and designers learning version control.",
    "rating": 4.4,
    "reviewsCount": 1950,
    "pricing": "Free",
    "websiteUrl": "https://sourcetreeapp.com",
    "affiliateUrl": "https://sourcetreeapp.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "ngrok",
    "name": "ngrok",
    "domain": "ngrok.com",
    "category": "developer-tools",
    "tagline": "Instant, secure ingress tunnels to expose local dev servers to the internet",
    "description": "ngrok connects local development environments to public URLs for webhook testing, mobile API debugging, and client demos. It is an essential utility for web and mobile software developers.",
    "rating": 4.8,
    "reviewsCount": 2400,
    "pricing": "Freemium",
    "websiteUrl": "https://ngrok.com",
    "affiliateUrl": "https://ngrok.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "5.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "warp-terminal",
    "name": "Warp",
    "domain": "warp.dev",
    "category": "developer-tools",
    "tagline": "Modern, Rust-based terminal equipped with AI command search and block editing",
    "description": "Warp reinforces command-line usage with IDE-style text selection, AI command completion, and shareable terminal workflows. It is built for developers and DevOps engineers using command-line tools.",
    "rating": 4.9,
    "reviewsCount": 980,
    "pricing": "Freemium",
    "websiteUrl": "https://warp.dev",
    "affiliateUrl": "https://warp.dev",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "3.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "iterm2",
    "name": "iTerm2",
    "domain": "iterm2.com",
    "category": "developer-tools",
    "tagline": "High-performance terminal emulator alternative for macOS power users",
    "description": "iTerm2 adds split panes, inline image rendering, autocomplete, and deep customization options to the standard Mac command line. It is a staple tool for macOS software developers.",
    "rating": 4.8,
    "reviewsCount": 3100,
    "pricing": "Free",
    "websiteUrl": "https://iterm2.com",
    "affiliateUrl": "https://iterm2.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.9M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "raycast",
    "name": "Raycast",
    "domain": "raycast.com",
    "category": "developer-tools",
    "tagline": "Extensible macOS command bar launcher with developer script integrations",
    "description": "Raycast speeds up developer workflows with quick API lookup tools, window management, GitHub issue controls, and AI prompt shortcuts. It serves Mac developers, engineers, and digital power users.",
    "rating": 4.9,
    "reviewsCount": 1100,
    "pricing": "Freemium",
    "websiteUrl": "https://raycast.com",
    "affiliateUrl": "https://raycast.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.9M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "cyberduck",
    "name": "Cyberduck",
    "domain": "cyberduck.io",
    "category": "developer-tools",
    "tagline": "Open-source cloud storage browser supporting FTP, SFTP, S3, and WebDAV",
    "description": "Cyberduck provides a simple desktop GUI to manage remote server files, AWS S3 buckets, and cloud storage protocols. It is designed for system administrators, web developers, and site managers.",
    "rating": 4.6,
    "reviewsCount": 1250,
    "pricing": "Free",
    "websiteUrl": "https://cyberduck.io",
    "affiliateUrl": "https://cyberduck.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "filezilla",
    "name": "FileZilla",
    "domain": "filezilla-project.org",
    "category": "developer-tools",
    "tagline": "Free, open-source FTP, FTPS, and SFTP cross-platform file transfer client",
    "description": "FileZilla facilitates fast batch file uploads and directory synchronization between desktop computers and remote servers. It is used widely by web developers and server administrators.",
    "rating": 4.5,
    "reviewsCount": 3800,
    "pricing": "Free",
    "websiteUrl": "https://filezilla-project.org",
    "affiliateUrl": "https://filezilla-project.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "6.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "sourgraph",
    "name": "Sourcegraph (Cody)",
    "domain": "sourcegraph.com",
    "category": "developer-tools",
    "tagline": "Code intelligence, universal code search, and Cody AI assistant for enterprises",
    "description": "Sourcegraph provides cross-repository code search, dependency mapping, and context-aware Cody AI coding assistance. It is engineered for large engineering teams maintaining massive codebases.",
    "rating": 4.7,
    "reviewsCount": 540,
    "pricing": "Freemium",
    "websiteUrl": "https://sourcegraph.com",
    "affiliateUrl": "https://sourcegraph.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.6M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "replit",
    "name": "Replit",
    "domain": "replit.com",
    "category": "developer-tools",
    "tagline": "Browser-based collaborative IDE, environment runtime, and instant app deployment",
    "description": "Replit allows developers to write, run, and host code in over 50 languages directly inside web browser tabs with built-in AI tools. It serves software learners, educators, and rapid prototypers.",
    "rating": 4.6,
    "reviewsCount": 2400,
    "pricing": "Freemium",
    "websiteUrl": "https://replit.com",
    "affiliateUrl": "https://replit.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "14.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "codesandbox",
    "name": "CodeSandbox",
    "domain": "codesandbox.io",
    "category": "developer-tools",
    "tagline": "Instant cloud development environments and collaborative web coding sandbox",
    "description": "CodeSandbox provisions instant cloud environments for web application development, live prototyping, and team code reviews. It is built for frontend engineers, web developers, and UI designers.",
    "rating": 4.7,
    "reviewsCount": 1100,
    "pricing": "Freemium",
    "websiteUrl": "https://codesandbox.io",
    "affiliateUrl": "https://codesandbox.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "stackblitz",
    "name": "StackBlitz",
    "domain": "stackblitz.com",
    "category": "developer-tools",
    "tagline": "Ultra-fast online WebContainers IDE running Node.js natively inside web browsers",
    "description": "StackBlitz leverages WebContainers to run full-stack Node.js environments locally inside browser engines without cloud latency. It is ideal for open-source documentation demos and web developers.",
    "rating": 4.8,
    "reviewsCount": 850,
    "pricing": "Freemium",
    "websiteUrl": "https://stackblitz.com",
    "affiliateUrl": "https://stackblitz.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "gitpod",
    "name": "Gitpod",
    "domain": "gitpod.io",
    "category": "developer-tools",
    "tagline": "Automated, standardized cloud development environments configured as code",
    "description": "Gitpod spins up ephemeral pre-configured development environments in the cloud directly from GitHub, GitLab, or Bitbucket PRs. It serves software teams looking to eliminate manual local dev environment setup.",
    "rating": 4.6,
    "reviewsCount": 680,
    "pricing": "Freemium",
    "websiteUrl": "https://gitpod.io",
    "affiliateUrl": "https://gitpod.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "regex101",
    "name": "Regex101",
    "domain": "regex101.com",
    "category": "developer-tools",
    "tagline": "Interactive regular expression tester, debugger, and pattern explainer",
    "description": "Regex101 provides real-time regex testing, syntax highlighting, detailed match explanations, and code generation across PCRE, Python, and JavaScript. It is an indispensable web utility for developers.",
    "rating": 4.9,
    "reviewsCount": 2800,
    "pricing": "Free",
    "websiteUrl": "https://regex101.com",
    "affiliateUrl": "https://regex101.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "8.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "jsoncrack",
    "name": "JSON Crack",
    "domain": "jsoncrack.com",
    "category": "developer-tools",
    "tagline": "Seamlessly visualize complex JSON data structures into interactive graphs",
    "description": "JSON Crack converts dense, raw JSON payloads into clear visual node graphs for easier data exploration and debugging. It is engineered for frontend developers, API engineers, and data analysts.",
    "rating": 4.9,
    "reviewsCount": 420,
    "pricing": "Freemium",
    "websiteUrl": "https://jsoncrack.com",
    "affiliateUrl": "https://jsoncrack.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "bundlephobia",
    "name": "Bundlephobia",
    "domain": "bundlephobia.com",
    "category": "developer-tools",
    "tagline": "Find the performance cost of adding an npm package to your JavaScript bundle",
    "description": "Bundlephobia calculates the download size, gzipped footprint, and execution impact of npm packages prior to installation. It serves frontend performance engineers and web developers.",
    "rating": 4.9,
    "reviewsCount": 310,
    "pricing": "Free",
    "websiteUrl": "https://bundlephobia.com",
    "affiliateUrl": "https://bundlephobia.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "transform-tools",
    "name": "Transform",
    "domain": "transform.tools",
    "category": "developer-tools",
    "tagline": "All-in-one web utility converting code types like JSON to TypeScript or HTML to JSX",
    "description": "Transform provides instant client-side code conversions including JSON to TypeScript interfaces, SVG to JSX components, and CSS to Tailwind. It is built for frontend and full-stack developers.",
    "rating": 4.9,
    "reviewsCount": 240,
    "pricing": "Free",
    "websiteUrl": "https://transform.tools",
    "affiliateUrl": "https://transform.tools",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "dev-toys",
    "name": "DevToys",
    "domain": "devtoys.app",
    "category": "developer-tools",
    "tagline": "A Swiss Army knife offline utility app for developers on Windows and Mac",
    "description": "DevToys bundles offline developer utilities like JWT decoders, Base64 encoders, JSON formatters, and hash generators in a clean GUI. It serves software developers working with daily data conversions.",
    "rating": 4.9,
    "reviewsCount": 510,
    "pricing": "Free",
    "websiteUrl": "https://devtoys.app",
    "affiliateUrl": "https://devtoys.app",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "380K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "local-can",
    "name": "LocalCan",
    "domain": "localcan.com",
    "category": "developer-tools",
    "tagline": "Dev-friendly LocalXpose and ngrok alternative with custom local domains and SSL",
    "description": "LocalCan creates local .local domain names with automatic SSL certificates and public tunnels for web application testing. It is built for macOS web developers testing webhooks and APIs.",
    "rating": 4.8,
    "reviewsCount": 180,
    "pricing": "Paid",
    "websiteUrl": "https://localcan.com",
    "affiliateUrl": "https://localcan.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "150K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "proxyman",
    "name": "Proxyman",
    "domain": "proxyman.io",
    "category": "developer-tools",
    "tagline": "Native, modern web debugging proxy for macOS, iOS, and Android development",
    "description": "Proxyman captures, inspects, and mocks HTTP/HTTPS network requests between applications and servers effortlessly. It is designed for mobile app developers, web engineers, and QA leads.",
    "rating": 4.9,
    "reviewsCount": 780,
    "pricing": "Freemium",
    "websiteUrl": "https://proxyman.io",
    "affiliateUrl": "https://proxyman.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "820K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "charles-proxy",
    "name": "Charles Proxy",
    "domain": "charlesproxy.com",
    "category": "developer-tools",
    "tagline": "Cross-platform HTTP proxy, reverse proxy, and network debugging application",
    "description": "Charles Proxy records HTTP/HTTPS traffic, allowing engineers to view headers, throttle network speeds, and rewrite API responses. It is a long-standing tool for mobile and web software developers.",
    "rating": 4.5,
    "reviewsCount": 1100,
    "pricing": "Free Trial",
    "websiteUrl": "https://charlesproxy.com",
    "affiliateUrl": "https://charlesproxy.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "950K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "orbstack",
    "name": "OrbStack",
    "domain": "orbstack.dev",
    "category": "developer-tools",
    "tagline": "Fast, lightweight Docker desktop and Linux machine runner built for Mac",
    "description": "OrbStack replaces heavy Docker Desktop installations on macOS with low CPU usage, instant startup times, and minimal battery consumption. It is engineered for Mac software developers.",
    "rating": 4.9,
    "reviewsCount": 920,
    "pricing": "Freemium",
    "websiteUrl": "https://orbstack.dev",
    "affiliateUrl": "https://orbstack.dev",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "dbgate",
    "name": "DbGate",
    "domain": "dbgate.org",
    "category": "developer-tools",
    "tagline": "Smart open-source database client for MySQL, PostgreSQL, SQL Server, and MongoDB",
    "description": "DbGate provides a cross-platform database manager with schema editing, data comparison, and visual query building. It serves software developers working across multiple SQL and NoSQL engines.",
    "rating": 4.8,
    "reviewsCount": 310,
    "pricing": "Free",
    "websiteUrl": "https://dbgate.org",
    "affiliateUrl": "https://dbgate.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "280K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "pgadmin",
    "name": "pgAdmin",
    "domain": "pgadmin.org",
    "category": "developer-tools",
    "tagline": "The most popular open-source administration and development platform for PostgreSQL",
    "description": "pgAdmin offers visual query execution plans, server monitoring, ER diagrams, and administrative management for PostgreSQL databases. It is built for Postgres database administrators and backend engineers.",
    "rating": 4.5,
    "reviewsCount": 1820,
    "pricing": "Free",
    "websiteUrl": "https://pgadmin.org",
    "affiliateUrl": "https://pgadmin.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.1M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "phpmyadmin",
    "name": "phpMyAdmin",
    "domain": "phpmyadmin.net",
    "category": "developer-tools",
    "tagline": "Classic web-based open-source administration tool for MySQL and MariaDB",
    "description": "phpMyAdmin handles MySQL database operations over web interfaces, supporting SQL execution, table exports, and privilege management. It is deployed across web hosting environments worldwide.",
    "rating": 4.4,
    "reviewsCount": 2900,
    "pricing": "Free",
    "websiteUrl": "https://phpmyadmin.net",
    "affiliateUrl": "https://phpmyadmin.net",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "mitmproxy",
    "name": "mitmproxy",
    "domain": "mitmproxy.org",
    "category": "developer-tools",
    "tagline": "Free, open-source interactive HTTPS intercepting proxy for command line",
    "description": "mitmproxy allows engineers to inspect, modify, and replay HTTP/HTTPS traffic through a terminal interface or Python scripts. It is engineered for security researchers and backend developers.",
    "rating": 4.8,
    "reviewsCount": 650,
    "pricing": "Free",
    "websiteUrl": "https://mitmproxy.org",
    "affiliateUrl": "https://mitmproxy.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "ghostty-terminal",
    "name": "Ghostty",
    "domain": "ghostty.org",
    "category": "developer-tools",
    "tagline": "Fast, native, GPU-accelerated terminal emulator designed for high stability",
    "description": "Ghostty provides GPU-accelerated terminal execution using Zig to deliver minimal input latency and native platform feel. It is built for CLI power users, systems engineers, and developers.",
    "rating": 4.9,
    "reviewsCount": 380,
    "pricing": "Free",
    "websiteUrl": "https://ghostty.org",
    "affiliateUrl": "https://ghostty.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "410K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "docfx-docs",
    "name": "DocFX",
    "domain": "dotnet.github.io/docfx",
    "category": "developer-tools",
    "tagline": "Open-source static documentation generator for .NET and API references",
    "description": "DocFX extracts source code comments to build structured static API documentation sites for C# and .NET projects. It serves open-source library authors and enterprise .NET developers.",
    "rating": 4.6,
    "reviewsCount": 190,
    "pricing": "Free",
    "websiteUrl": "https://dotnet.github.io/docfx",
    "affiliateUrl": "https://dotnet.github.io/docfx",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "240K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "swagger-io",
    "name": "Swagger (SmartBear)",
    "domain": "swagger.io",
    "category": "developer-tools",
    "tagline": "OpenAPI specification tools for API design, documentation, and testing",
    "description": "Swagger provides UI generation, schema editing, and code generation based on the open-source OpenAPI specification. It is an industry standard for API documentation and backend design.",
    "rating": 4.6,
    "reviewsCount": 2400,
    "pricing": "Freemium",
    "websiteUrl": "https://swagger.io",
    "affiliateUrl": "https://swagger.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "5.8M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "redocly",
    "name": "Redocly",
    "domain": "redocly.com",
    "category": "developer-tools",
    "tagline": "Modern OpenAPI documentation generator, linter, and developer portal framework",
    "description": "Redocly turns OpenAPI contracts into beautiful, interactive three-panel API documentation web portals. It serves API product teams, enterprise engineering leads, and technical writers.",
    "rating": 4.8,
    "reviewsCount": 210,
    "pricing": "Freemium",
    "websiteUrl": "https://redocly.com",
    "affiliateUrl": "https://redocly.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "380K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "mermaid-js",
    "name": "Mermaid.js",
    "domain": "mermaid.js.org",
    "category": "developer-tools",
    "tagline": "JavaScript-based diagramming and charting tool that renders Markdown text definitions",
    "description": "Mermaid.js converts simple text code definitions into dynamic architecture diagrams, sequence flows, and Gantt charts. It is built for technical writers, software architects, and documentation maintainers.",
    "rating": 4.9,
    "reviewsCount": 1100,
    "pricing": "Free",
    "websiteUrl": "https://mermaid.js.org",
    "affiliateUrl": "https://mermaid.js.org",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.9M",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "excalidraw",
    "name": "Excalidraw",
    "domain": "excalidraw.com",
    "category": "developer-tools",
    "tagline": "Virtual hand-drawn style whiteboard for software architecture sketching and wireframing",
    "description": "Excalidraw provides a lightweight online drawing canvas with hand-drawn visual aesthetics for sketching system architectures and diagrams. It is designed for software developers, engineers, and product designers.",
    "rating": 4.9,
    "reviewsCount": 1820,
    "pricing": "Free",
    "websiteUrl": "https://excalidraw.com",
    "affiliateUrl": "https://excalidraw.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "4.8M",
    "isFreeTier": true,
    "isOpenSource": true
  }
];

const saasDataPath = path.join(__dirname, '..', 'src', 'data', 'saasData.jsx');
let content = fs.readFileSync(saasDataPath, 'utf8');

const match = content.match(/export const staticSaasTools = (\[[\s\S]*?\n\]);/);
if (!match) {
  console.error('Could not find staticSaasTools in saasData.jsx');
  process.exit(1);
}

let existingTools = JSON.parse(match[1]);

const existingIds = new Set(existingTools.map(t => t.id.toLowerCase()));
const existingNames = new Set(existingTools.map(t => t.name.toLowerCase()));

let addedCount = 0;
let skippedCount = 0;

newTools.forEach(tool => {
  const normId = tool.id.toLowerCase();
  const normName = tool.name.toLowerCase();

  if (!existingIds.has(normId) && !existingNames.has(normName)) {
    existingTools.push(tool);
    existingIds.add(normId);
    existingNames.add(normName);
    addedCount++;
  } else {
    // Enrich existing tool without creating a duplicate
    const idx = existingTools.findIndex(t => t.id.toLowerCase() === normId || t.name.toLowerCase() === normName);
    if (idx !== -1) {
      existingTools[idx] = { ...existingTools[idx], category: tool.category, tagline: tool.tagline || existingTools[idx].tagline };
    }
    skippedCount++;
  }
});

const updatedArrayStr = JSON.stringify(existingTools, null, 2);
content = content.replace(/export const staticSaasTools = \[[\s\S]*?\n\];/, `export const staticSaasTools = ${updatedArrayStr};`);

fs.writeFileSync(saasDataPath, content, 'utf8');
console.log(`Ingestion Complete! Added: ${addedCount} brand new tools | Deduplicated: ${skippedCount} existing tools | Total static tools: ${existingTools.length}`);
