const fs = require('fs');
const path = require('path');

const newTools = [
  {
    "id": "stripe",
    "name": "Stripe",
    "domain": "stripe.com",
    "category": "finance-payments",
    "tagline": "Financial infrastructure platform for internet commerce and global payments",
    "description": "Stripe provides developer-first payment APIs, fraud prevention, subscription billing, and merchant processing infrastructure. It is designed for software developers, online stores, and global SaaS platforms.",
    "rating": 4.8,
    "reviewsCount": 4200,
    "pricing": "Freemium",
    "websiteUrl": "https://stripe.com",
    "affiliateUrl": "https://stripe.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "28.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "paypal",
    "name": "PayPal",
    "domain": "paypal.com",
    "category": "finance-payments",
    "tagline": "Global digital wallet, merchant payment processor, and checkout platform",
    "description": "PayPal allows businesses to accept credit card payments, digital wallet transfers, and buy-now-pay-later options globally. It is built for e-commerce merchants, freelancers, and digital storefronts.",
    "rating": 4.5,
    "reviewsCount": 8500,
    "pricing": "Freemium",
    "websiteUrl": "https://paypal.com",
    "affiliateUrl": "https://paypal.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "180M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "square",
    "name": "Square",
    "domain": "squareup.com",
    "category": "finance-payments",
    "tagline": "Integrated point-of-sale, omnichannel payment processing, and merchant tools",
    "description": "Square combines hardware card readers with online checkout APIs, customer invoicing, and business banking. It serves brick-and-mortar retailers, restaurants, and hybrid e-commerce merchants.",
    "rating": 4.7,
    "reviewsCount": 3800,
    "pricing": "Freemium",
    "websiteUrl": "https://squareup.com",
    "affiliateUrl": "https://squareup.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "14.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "paddle",
    "name": "Paddle",
    "domain": "paddle.com",
    "category": "finance-payments",
    "tagline": "Complete Merchant of Record platform for digital software and SaaS sales",
    "description": "Paddle acts as a Merchant of Record, handling global sales tax, local payment methods, subscription billing, and compliance automatically. It is engineered specifically for software creators and SaaS founders.",
    "rating": 4.7,
    "reviewsCount": 920,
    "pricing": "Paid",
    "websiteUrl": "https://paddle.com",
    "affiliateUrl": "https://paddle.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "2.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "adyen",
    "name": "Adyen",
    "domain": "adyen.com",
    "category": "finance-payments",
    "tagline": "Enterprise end-to-end payment platform for global omnichannel businesses",
    "description": "Adyen provides direct merchant acquiring, risk management, and unified payment processing across online, mobile, and in-store channels. It is engineered for enterprise retailers and global platforms.",
    "rating": 4.6,
    "reviewsCount": 1150,
    "pricing": "Paid",
    "websiteUrl": "https://adyen.com",
    "affiliateUrl": "https://adyen.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "4.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "chargebee",
    "name": "Chargebee",
    "domain": "chargebee.com",
    "category": "finance-payments",
    "tagline": "Subscription management, recurring billing, and revenue operations platform",
    "description": "Chargebee automates complex subscription lifecycles, proration, dunning recovery, and revenue recognition across multiple gateways. It is built for growing SaaS and subscription eCommerce brands.",
    "rating": 4.7,
    "reviewsCount": 850,
    "pricing": "Freemium",
    "websiteUrl": "https://chargebee.com",
    "affiliateUrl": "https://chargebee.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "checkout-com",
    "name": "Checkout.com",
    "domain": "checkout.com",
    "category": "finance-payments",
    "tagline": "High-performance global payment processing for enterprise digital commerce",
    "description": "Checkout.com offers direct acquiring, flexible payment APIs, and real-time fraud monitoring to boost approval rates globally. It serves enterprise digital businesses, marketplaces, and fintech platforms.",
    "rating": 4.6,
    "reviewsCount": 680,
    "pricing": "Paid",
    "websiteUrl": "https://checkout.com",
    "affiliateUrl": "https://checkout.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.9M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "airwallex",
    "name": "Airwallex",
    "domain": "airwallex.com",
    "category": "finance-payments",
    "tagline": "Global financial accounts, cross-border payments, and merchant card processing",
    "description": "Airwallex provides multi-currency business accounts, FX transfers, corporate cards, and payment gateway APIs to eliminate international conversion markup fees. It is built for cross-border e-commerce brands.",
    "rating": 4.7,
    "reviewsCount": 1100,
    "pricing": "Freemium",
    "websiteUrl": "https://airwallex.com",
    "affiliateUrl": "https://airwallex.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "braintree",
    "name": "Braintree by PayPal",
    "domain": "braintreepayments.com",
    "category": "finance-payments",
    "tagline": "Developer-friendly payment gateway supporting credit cards, PayPal, and Venmo",
    "description": "Braintree delivers custom checkout integrations accepting credit cards, digital wallets, Apple Pay, and Venmo through a single SDK. It serves fast-scaling web applications and mobile apps.",
    "rating": 4.5,
    "reviewsCount": 1420,
    "pricing": "Paid",
    "websiteUrl": "https://braintreepayments.com",
    "affiliateUrl": "https://braintreepayments.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "recurly",
    "name": "Recurly",
    "domain": "recurly.com",
    "category": "finance-payments",
    "tagline": "Subscription management platform focused on churn reduction and retention",
    "description": "Recurly uses machine learning to recover failed recurring transactions, manage subscriber plans, and streamline multi-gateway routing. It is optimized for subscription businesses maximizing subscriber LTV.",
    "rating": 4.5,
    "reviewsCount": 420,
    "pricing": "Paid",
    "websiteUrl": "https://recurly.com",
    "affiliateUrl": "https://recurly.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "authorize-net",
    "name": "Authorize.net",
    "domain": "authorize.net",
    "category": "finance-payments",
    "tagline": "Established payment gateway service providing secure online credit card processing",
    "description": "Authorize.net connects merchant accounts with secure web payment processing, recurring billing, and virtual terminal management. It is designed for small to mid-sized businesses seeking traditional gateway stability.",
    "rating": 4.3,
    "reviewsCount": 1850,
    "pricing": "Paid",
    "websiteUrl": "https://authorize.net",
    "affiliateUrl": "https://authorize.net",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "helcim",
    "name": "Helcim",
    "domain": "helcim.com",
    "category": "finance-payments",
    "tagline": "Transparent interchange-plus payment processing with zero monthly subscription fees",
    "description": "Helcim offers transparent merchant processing, virtual terminals, hosted checkouts, and invoicing with automatic volume discounts. It serves growing small businesses wanting low credit card processing rates.",
    "rating": 4.8,
    "reviewsCount": 650,
    "pricing": "Freemium",
    "websiteUrl": "https://helcim.com",
    "affiliateUrl": "https://helcim.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "820K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "quickbooks-payments",
    "name": "QuickBooks Payments",
    "domain": "quickbooks.intuit.com/payments",
    "category": "finance-payments",
    "tagline": "Integrated credit card and ACH payment processing for QuickBooks accounting",
    "description": "QuickBooks Payments lets customers pay invoice links directly via credit card or ACH, reconciling transactions instantly inside accounting records. It is tailored for small businesses using QuickBooks.",
    "rating": 4.5,
    "reviewsCount": 3100,
    "pricing": "Paid",
    "websiteUrl": "https://quickbooks.intuit.com/payments",
    "affiliateUrl": "https://quickbooks.intuit.com/payments",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "18.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "wave-invoicing",
    "name": "Wave Invoicing & Payments",
    "domain": "waveapps.com/invoicing",
    "category": "finance-payments",
    "tagline": "Free online invoicing software with built-in credit card and bank payment processing",
    "description": "Wave provides free online invoice creation combined with transparent pay-per-use online credit card and ACH processing. It is built for solopreneurs, freelancers, and micro-businesses.",
    "rating": 4.4,
    "reviewsCount": 1650,
    "pricing": "Freemium",
    "websiteUrl": "https://waveapps.com/invoicing",
    "affiliateUrl": "https://waveapps.com/invoicing",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "zoho-billing",
    "name": "Zoho Billing (formerly Zoho Subscriptions)",
    "domain": "zoho.com/billing",
    "category": "finance-payments",
    "tagline": "End-to-end recurring billing, usage-based metering, and invoicing software",
    "description": "Zoho Billing handles complex recurring subscriptions, usage pricing, tax compliance, and automated customer invoicing. It is built for growing SaaS platforms, services, and digital merchants.",
    "rating": 4.6,
    "reviewsCount": 980,
    "pricing": "Freemium",
    "websiteUrl": "https://zoho.com/billing",
    "affiliateUrl": "https://zoho.com/billing",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "freshbooks-payments",
    "name": "FreshBooks Payments",
    "domain": "freshbooks.com/payments",
    "category": "finance-payments",
    "tagline": "Seamless client online payment acceptance and automated invoice tracking",
    "description": "FreshBooks Payments allows service professionals to accept online credit cards directly on sent invoices and set up recurring billing. It is built for freelancers, agencies, and consultants.",
    "rating": 4.5,
    "reviewsCount": 1420,
    "pricing": "Paid",
    "websiteUrl": "https://freshbooks.com/payments",
    "affiliateUrl": "https://freshbooks.com/payments",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "bill-com",
    "name": "BILL (formerly Bill.com)",
    "domain": "bill.com",
    "category": "finance-payments",
    "tagline": "Automated accounts payable and accounts receivable payment software",
    "description": "BILL streamlines business-to-business payments, digitizing vendor bill approvals, digital ACH transfers, and customer invoicing. It serves small-to-midsize businesses modernizing cash flow operations.",
    "rating": 4.4,
    "reviewsCount": 1280,
    "pricing": "Free Trial",
    "websiteUrl": "https://bill.com",
    "affiliateUrl": "https://bill.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "6.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "melio",
    "name": "Melio",
    "domain": "meliopayments.com",
    "category": "finance-payments",
    "tagline": "Simple B2B payables and receivables platform for small business owners",
    "description": "Melio enables small businesses to pay vendor bills via bank transfer or credit card and receive customer payments online easily. It is designed for small business owners optimizing cash flow.",
    "rating": 4.6,
    "reviewsCount": 820,
    "pricing": "Freemium",
    "websiteUrl": "https://meliopayments.com",
    "affiliateUrl": "https://meliopayments.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "recharge",
    "name": "Recharge",
    "domain": "rechargepayments.com",
    "category": "finance-payments",
    "tagline": "Subscription billing and customer retention engine for Shopify e-commerce",
    "description": "Recharge empowers e-commerce brands to offer physical product subscriptions, recurring order bundles, and customer portal management. It is engineered specifically for Shopify merchants.",
    "rating": 4.6,
    "reviewsCount": 1250,
    "pricing": "Freemium",
    "websiteUrl": "https://rechargepayments.com",
    "affiliateUrl": "https://rechargepayments.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.9M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "stax-payments",
    "name": "Stax Payments",
    "domain": "staxpayments.com",
    "category": "finance-payments",
    "tagline": "Subscription-style subscription merchant processing with zero markup on interchange",
    "description": "Stax offers flat monthly subscription merchant fees that grant direct access to wholesale interchange rates without percentage markups. It is built for high-volume mid-market businesses.",
    "rating": 4.4,
    "reviewsCount": 510,
    "pricing": "Paid",
    "websiteUrl": "https://staxpayments.com",
    "affiliateUrl": "https://staxpayments.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "410K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "invoice-ninja",
    "name": "Invoice Ninja",
    "domain": "invoiceninja.com",
    "category": "finance-payments",
    "tagline": "Open-source invoicing, expense tracking, and client payment portal",
    "description": "Invoice Ninja allows freelancers and businesses to send custom invoices, track time, and accept payments via 50+ payment gateways. It offers both hosted cloud and self-hostable open-source deployment.",
    "rating": 4.7,
    "reviewsCount": 540,
    "pricing": "Freemium",
    "websiteUrl": "https://invoiceninja.com",
    "affiliateUrl": "https://invoiceninja.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "510K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "klarna",
    "name": "Klarna",
    "domain": "klarna.com",
    "category": "finance-payments",
    "tagline": "Global Buy Now Pay Later (BNPL) and flexible consumer payment gateway",
    "description": "Klarna embeds flexible payment options like installment plans and pay-in-30-days directly into e-commerce checkout flows. It is built for online retailers seeking higher cart conversion rates.",
    "rating": 4.5,
    "reviewsCount": 6200,
    "pricing": "Paid",
    "websiteUrl": "https://klarna.com",
    "affiliateUrl": "https://klarna.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "38.0M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "affirm",
    "name": "Affirm",
    "domain": "affirm.com",
    "category": "finance-payments",
    "tagline": "Transparent consumer financing and Buy Now Pay Later checkout integration",
    "description": "Affirm enables retail shoppers to pay over time with fixed monthly payments and zero hidden fees. It serves major e-commerce brands and digital storefronts looking to boost average order value.",
    "rating": 4.6,
    "reviewsCount": 4100,
    "pricing": "Paid",
    "websiteUrl": "https://affirm.com",
    "affiliateUrl": "https://affirm.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "12.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "afterpay",
    "name": "Afterpay",
    "domain": "afterpay.com",
    "category": "finance-payments",
    "tagline": "Four-installment interest-free retail checkout and merchant payment service",
    "description": "Afterpay splits consumer purchase costs into four interest-free payments while paying merchants upfront. It is tailored for e-commerce fashion, lifestyle, and consumer goods retailers.",
    "rating": 4.6,
    "reviewsCount": 4800,
    "pricing": "Paid",
    "websiteUrl": "https://afterpay.com",
    "affiliateUrl": "https://afterpay.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "15.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "mollie",
    "name": "Mollie",
    "domain": "mollie.com",
    "category": "finance-payments",
    "tagline": "Effortless European payment gateway supporting local payment methods",
    "description": "Mollie simplifies accepting iDEAL, SEPA, Klarna, and major credit cards through clean developer APIs and plugins. It is built for European e-commerce stores and fast-growing web platforms.",
    "rating": 4.7,
    "reviewsCount": 1650,
    "pricing": "Freemium",
    "websiteUrl": "https://mollie.com",
    "affiliateUrl": "https://mollie.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "worldpay",
    "name": "Worldpay",
    "domain": "worldpay.com",
    "category": "finance-payments",
    "tagline": "Global merchant acquiring, omni-channel payment processing, and POS services",
    "description": "Worldpay delivers global card acquiring, point-of-sale hardware, and web gateway processing across 135+ currencies. It serves mid-market to enterprise businesses across retail, travel, and hospitality.",
    "rating": 4.1,
    "reviewsCount": 2400,
    "pricing": "Paid",
    "websiteUrl": "https://worldpay.com",
    "affiliateUrl": "https://worldpay.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.5M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "maxio",
    "name": "Maxio (formerly Chargify & SaaSOptics)",
    "domain": "maxio.com",
    "category": "finance-payments",
    "tagline": "Financial operations, complex B2B subscription billing, and revenue analytics",
    "description": "Maxio manages intricate B2B SaaS subscription models, custom enterprise contracts, ASC 606 revenue recognition, and financial reporting. It serves finance-led B2B SaaS leadership teams.",
    "rating": 4.5,
    "reviewsCount": 380,
    "pricing": "Paid",
    "websiteUrl": "https://maxio.com",
    "affiliateUrl": "https://maxio.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "290K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "metronome",
    "name": "Metronome",
    "domain": "metronome.com",
    "category": "finance-payments",
    "tagline": "Flexible usage-based billing platform designed for API and AI-first SaaS",
    "description": "Metronome processes real-time usage metrics to calculate dynamic consumption pricing, credits, and custom enterprise billing. It is engineered for AI, cloud infrastructure, and developer-tool companies.",
    "rating": 4.8,
    "reviewsCount": 110,
    "pricing": "Paid",
    "websiteUrl": "https://metronome.com",
    "affiliateUrl": "https://metronome.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "120K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "orb-billing",
    "name": "Orb",
    "domain": "withorb.com",
    "category": "finance-payments",
    "tagline": "Modern usage-based billing and rating engine for complex software pricing",
    "description": "Orb ingests high-volume usage event streams to power flexible usage-based models, hybrid plans, and automated customer invoices. It serves modern AI companies and software engineering organizations.",
    "rating": 4.8,
    "reviewsCount": 140,
    "pricing": "Paid",
    "websiteUrl": "https://withorb.com",
    "affiliateUrl": "https://withorb.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "150K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "lago-billing",
    "name": "Lago",
    "domain": "getlago.com",
    "category": "finance-payments",
    "tagline": "Open-source metering, usage-based billing, and subscription architecture",
    "description": "Lago provides open-source metering infrastructure to construct custom usage-based pricing, hybrid plans, and invoicing logic. It is built for developers who require self-hosted billing control.",
    "rating": 4.7,
    "reviewsCount": 210,
    "pricing": "Freemium",
    "websiteUrl": "https://getlago.com",
    "affiliateUrl": "https://getlago.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "180K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "zuora",
    "name": "Zuora",
    "domain": "zuora.com",
    "category": "finance-payments",
    "tagline": "Enterprise monetisation, subscription management, and quote-to-revenue engine",
    "description": "Zuora orchestrates complex enterprise subscription product catalogs, multi-entity billing, and global revenue recognition. It is built for large, global enterprise subscription corporations.",
    "rating": 4.3,
    "reviewsCount": 890,
    "pricing": "Paid",
    "websiteUrl": "https://zuora.com",
    "affiliateUrl": "https://zuora.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "fast-spring",
    "name": "FastSpring",
    "domain": "fastspring.com",
    "category": "finance-payments",
    "tagline": "Full-service Merchant of Record platform for digital goods, software, and SaaS",
    "description": "FastSpring manages global checkout, international tax remittance, fraud prevention, and recurring billing as a Merchant of Record. It serves global digital software sellers and video game publishers.",
    "rating": 4.5,
    "reviewsCount": 480,
    "pricing": "Paid",
    "websiteUrl": "https://fastspring.com",
    "affiliateUrl": "https://fastspring.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "850K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "2checkout-verifone",
    "name": "2Checkout (Verifone)",
    "domain": "2checkout.com",
    "category": "finance-payments",
    "tagline": "All-in-one global monetization platform for software and digital services",
    "description": "2Checkout facilitates cross-border digital commerce, subscription management, global tax compliance, and local payment acceptance. It is built for software vendors expanding into global markets.",
    "rating": 4.2,
    "reviewsCount": 820,
    "pricing": "Paid",
    "websiteUrl": "https://2checkout.com",
    "affiliateUrl": "https://2checkout.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "gocardless",
    "name": "GoCardless",
    "domain": "gocardless.com",
    "category": "finance-payments",
    "tagline": "Direct bank debit and account-to-account recurring payment collection platform",
    "description": "GoCardless automates recurring bank debit payments (ACH, SEPA, Bacs) directly from customer bank accounts with lower transaction fees. It is ideal for subscription businesses, utilities, and B2B invoicing.",
    "rating": 4.6,
    "reviewsCount": 1450,
    "pricing": "Freemium",
    "websiteUrl": "https://gocardless.com",
    "affiliateUrl": "https://gocardless.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "payoneer",
    "name": "Payoneer",
    "domain": "payoneer.com",
    "category": "finance-payments",
    "tagline": "Cross-border payment platform for freelancers, marketplaces, and global SMBs",
    "description": "Payoneer provides receiving bank accounts in foreign currencies, marketplace payout integrations, and international business debit cards. It serves global freelancers, agencies, and cross-border sellers.",
    "rating": 4.4,
    "reviewsCount": 6100,
    "pricing": "Freemium",
    "websiteUrl": "https://payoneer.com",
    "affiliateUrl": "https://payoneer.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "11.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "wise-business",
    "name": "Wise Business",
    "domain": "wise.com/business",
    "category": "finance-payments",
    "tagline": "Low-cost international multi-currency business accounts and transfer engine",
    "description": "Wise Business provides mid-market exchange rate transfers, local account details in 9+ currencies, and batch international payroll processing. It is built for companies conducting international trade.",
    "rating": 4.8,
    "reviewsCount": 5400,
    "pricing": "Freemium",
    "websiteUrl": "https://wise.com/business",
    "affiliateUrl": "https://wise.com/business",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "32.0M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "tipalti",
    "name": "Tipalti",
    "domain": "tipalti.com",
    "category": "finance-payments",
    "tagline": "Global payables, partner payouts, and supplier invoice automation platform",
    "description": "Tipalti automates complex mass payouts to global suppliers, affiliates, and contractors across 196 countries while enforcing tax compliance. It serves digital marketplaces, ad networks, and enterprise accounts.",
    "rating": 4.6,
    "reviewsCount": 420,
    "pricing": "Paid",
    "websiteUrl": "https://tipalti.com",
    "affiliateUrl": "https://tipalti.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "payment-depot",
    "name": "Payment Depot",
    "domain": "paymentdepot.com",
    "category": "finance-payments",
    "tagline": "Wholesale interchange-plus credit card processing for established merchants",
    "description": "Payment Depot passes through direct interchange cost rates paired with transparent membership pricing instead of taking percentage markups. It serves established merchants processing high card volumes.",
    "rating": 4.6,
    "reviewsCount": 380,
    "pricing": "Paid",
    "websiteUrl": "https://paymentdepot.com",
    "affiliateUrl": "https://paymentdepot.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "210K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "plaid",
    "name": "Plaid",
    "domain": "plaid.com",
    "category": "finance-payments",
    "tagline": "Secure financial data network connecting apps to user bank accounts",
    "description": "Plaid enables applications to verify bank account details, authenticate instant ACH transfers, and check real-time account balances. It is engineered for developers building fintech and payment apps.",
    "rating": 4.7,
    "reviewsCount": 980,
    "pricing": "Freemium",
    "websiteUrl": "https://plaid.com",
    "affiliateUrl": "https://plaid.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "finix",
    "name": "Finix",
    "domain": "finix.com",
    "category": "finance-payments",
    "tagline": "Full-stack payment facilitation infrastructure for software platforms",
    "description": "Finix empowers SaaS platforms to become payment facilitators (PayFacs), monetizing platform transactions and configuring custom checkout flows. It is tailored for vertical SaaS applications.",
    "rating": 4.8,
    "reviewsCount": 110,
    "pricing": "Paid",
    "websiteUrl": "https://finix.com",
    "affiliateUrl": "https://finix.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "140K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "chargeflow",
    "name": "Chargeflow",
    "domain": "chargeflow.io",
    "category": "finance-payments",
    "tagline": "Automated AI chargeback representation and dispute recovery for e-commerce",
    "description": "Chargeflow uses artificial intelligence to gather transaction evidence and resolve credit card chargeback disputes automatically. It is built for Shopify and digital e-commerce merchants.",
    "rating": 4.8,
    "reviewsCount": 310,
    "pricing": "Paid",
    "websiteUrl": "https://chargeflow.io",
    "affiliateUrl": "https://chargeflow.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "350K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "quaderno-tax",
    "name": "Quaderno",
    "domain": "quaderno.io",
    "category": "finance-payments",
    "tagline": "Automated international tax, VAT, and GST calculation and billing engine",
    "description": "Quaderno calculates international digital sales taxes in real time, issues tax-compliant invoices, and compiles global filing reports. It serves e-commerce, SaaS, and digital product sellers globally.",
    "rating": 4.6,
    "reviewsCount": 180,
    "pricing": "Paid",
    "websiteUrl": "https://quaderno.io",
    "affiliateUrl": "https://quaderno.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "160K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "taxjar-payments",
    "name": "TaxJar by Stripe",
    "domain": "taxjar.com",
    "category": "finance-payments",
    "tagline": "Automated sales tax calculation, nexus tracking, and filing platform",
    "description": "TaxJar automates state sales tax calculations across e-commerce checkouts, tracks economic nexus, and manages automated tax filings. It is designed for e-commerce merchants and digital sellers.",
    "rating": 4.5,
    "reviewsCount": 620,
    "pricing": "Paid",
    "websiteUrl": "https://taxjar.com",
    "affiliateUrl": "https://taxjar.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "950K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "invoicely",
    "name": "Invoicely",
    "domain": "invoicely.com",
    "category": "finance-payments",
    "tagline": "Free multi-currency online invoicing and payment processing software",
    "description": "Invoicely enables instant multi-currency invoice creation, billable time logging, and online customer credit card acceptance. It is designed for small business owners and independent freelancers.",
    "rating": 4.4,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://invoicely.com",
    "affiliateUrl": "https://invoicely.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "420K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "invoice-simple",
    "name": "Invoice Simple",
    "domain": "invoicesimple.com",
    "category": "finance-payments",
    "tagline": "Fast mobile-first invoice generator app for trade contractors and field services",
    "description": "Invoice Simple provides mobile estimate creation and invoice billing allowing trade contractors to accept payments on site. It is tailored for field service professionals and local trade businesses.",
    "rating": 4.6,
    "reviewsCount": 890,
    "pricing": "Freemium",
    "websiteUrl": "https://invoicesimple.com",
    "affiliateUrl": "https://invoicesimple.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "hiveage",
    "name": "Hiveage",
    "domain": "hiveage.com",
    "category": "finance-payments",
    "tagline": "Cloud-based online invoicing and subscription billing software for small business",
    "description": "Hiveage provides custom online invoice generation, recurring billing, team time tracking, and multi-gateway payment collection. It serves small service businesses and independent agencies.",
    "rating": 4.4,
    "reviewsCount": 160,
    "pricing": "Freemium",
    "websiteUrl": "https://hiveage.com",
    "affiliateUrl": "https://hiveage.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "140K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "polar-sh",
    "name": "Polar",
    "domain": "polar.sh",
    "category": "finance-payments",
    "tagline": "Open-source Merchant of Record platform for open-source developers and SaaS",
    "description": "Polar offers an open-source Merchant of Record platform that monetizes digital software downloads, SaaS subscriptions, and GitHub sponsorships cleanly. It is engineered for open-source developers.",
    "rating": 4.8,
    "reviewsCount": 180,
    "pricing": "Freemium",
    "websiteUrl": "https://polar.sh",
    "affiliateUrl": "https://polar.sh",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "320K",
    "isFreeTier": true,
    "isOpenSource": true
  },
  {
    "id": "solvimon",
    "name": "Solvimon",
    "domain": "solvimon.com",
    "category": "finance-payments",
    "tagline": "PSP-agnostic hybrid usage and seat billing engine for AI-native SaaS",
    "description": "Solvimon provides a headless subscription billing platform supporting hybrid seat, credit, and usage pricing alongside PSP independence. It serves AI-native companies, global SaaS startups, and multi-entity operations.",
    "rating": 4.9,
    "reviewsCount": 95,
    "pricing": "Freemium",
    "websiteUrl": "https://solvimon.com",
    "affiliateUrl": "https://solvimon.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "85K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "splitwise",
    "name": "Splitwise",
    "domain": "splitwise.com",
    "category": "finance-payments",
    "tagline": "Social expense sharing, shared bill tracking, and group debt settlement app",
    "description": "Splitwise tracks shared household bills, travel expenses, and group tabs, calculating net balances and facilitating settlements. It is designed for roommates, group trips, and shared cost tracking.",
    "rating": 4.8,
    "reviewsCount": 4200,
    "pricing": "Freemium",
    "websiteUrl": "https://splitwise.com",
    "affiliateUrl": "https://splitwise.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "12.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "tricount",
    "name": "Tricount",
    "domain": "tricount.com",
    "category": "finance-payments",
    "tagline": "Simple mobile app to track group expenses and calculate trip balances",
    "description": "Tricount organizes shared group costs on mobile devices, providing instant balance calculations for group trips and events. It serves friends, group travelers, and housemates managing shared budgets.",
    "rating": 4.7,
    "reviewsCount": 2800,
    "pricing": "Freemium",
    "websiteUrl": "https://tricount.com",
    "affiliateUrl": "https://tricount.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.9M",
    "isFreeTier": true,
    "isOpenSource": false
  }
];

const saasDataPath = path.join(__dirname, '..', 'src', 'data', 'saasData.jsx');
let content = fs.readFileSync(saasDataPath, 'utf8');

const match = content.match(/export const staticSaasTools = (\[[\s\S]*?\n\]);/);
if (!match) {
  console.error('Could not find staticSaasTools in saasData.jsx');
  process.exit(1);
}

let existingTools = JSON.parse(match[1]);

const existingIds = new Set(existingTools.map(t => t.id.toLowerCase()));
const existingNames = new Set(existingTools.map(t => t.name.toLowerCase()));

let addedCount = 0;
let skippedCount = 0;

newTools.forEach(tool => {
  const normId = tool.id.toLowerCase();
  const normName = tool.name.toLowerCase();

  if (!existingIds.has(normId) && !existingNames.has(normName)) {
    existingTools.push(tool);
    existingIds.add(normId);
    existingNames.add(normName);
    addedCount++;
  } else {
    // Enrich existing tool without creating a duplicate
    const idx = existingTools.findIndex(t => t.id.toLowerCase() === normId || t.name.toLowerCase() === normName);
    if (idx !== -1) {
      existingTools[idx] = { ...existingTools[idx], category: tool.category, tagline: tool.tagline || existingTools[idx].tagline };
    }
    skippedCount++;
  }
});

const updatedArrayStr = JSON.stringify(existingTools, null, 2);
content = content.replace(/export const staticSaasTools = \[[\s\S]*?\n\];/, `export const staticSaasTools = ${updatedArrayStr};`);

fs.writeFileSync(saasDataPath, content, 'utf8');
console.log(`Ingestion Complete! Added: ${addedCount} brand new tools | Deduplicated: ${skippedCount} existing tools | Total static tools: ${existingTools.length}`);
