const fs = require('fs');
const path = require('path');

const newTools = [
  {
    "id": "apollo-io",
    "name": "Apollo.io",
    "domain": "apollo.io",
    "category": "lead-generation",
    "tagline": "All-in-one B2B lead database, buyer intent, and sales engagement engine",
    "description": "Apollo provides access to over 275 million B2B contacts alongside built-in email sequencing, phone dialers, and buyer intent filters. It is designed for SDRs, founders, and sales teams looking to source contacts and execute cold outreach in one platform.",
    "rating": 4.7,
    "reviewsCount": 9400,
    "pricing": "Freemium",
    "websiteUrl": "https://apollo.io",
    "affiliateUrl": "https://apollo.io",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "18.5M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "zoominfo",
    "name": "ZoomInfo",
    "domain": "zoominfo.com",
    "category": "lead-generation",
    "tagline": "Enterprise B2B contact database, corporate intelligence, and buyer intent platform",
    "description": "ZoomInfo delivers enterprise-grade contact records, verified direct dials, org charts, and real-time company purchasing intent signals. It is engineered for high-volume revenue operations and sales development teams.",
    "rating": 4.4,
    "reviewsCount": 8200,
    "pricing": "Paid",
    "websiteUrl": "https://zoominfo.com",
    "affiliateUrl": "https://zoominfo.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "12.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "clay",
    "name": "Clay",
    "domain": "clay.com",
    "category": "lead-generation",
    "tagline": "AI sales prospecting, waterfall enrichment, and automated outbound workflows",
    "description": "Clay cascades data across 75+ enrichment providers to locate verified emails, phone numbers, and company insights automatically. It is built for growth marketers and revenue operations specialists scaling hyper-personalized outreach.",
    "rating": 4.9,
    "reviewsCount": 1150,
    "pricing": "Freemium",
    "websiteUrl": "https://clay.com",
    "affiliateUrl": "https://clay.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "2.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "linkedin-sales-navigator",
    "name": "LinkedIn Sales Navigator",
    "domain": "linkedin.com/sales",
    "category": "lead-generation",
    "tagline": "Advanced social selling search, account tracking, and decision-maker discovery",
    "description": "LinkedIn Sales Navigator leverages live network data to help sales reps discover target decision-makers, track lead changes, and send InMails. It is designed for B2B sales professionals conducting targeted account prospecting.",
    "rating": 4.6,
    "reviewsCount": 3800,
    "pricing": "Free Trial",
    "websiteUrl": "https://linkedin.com/sales",
    "affiliateUrl": "https://linkedin.com/sales",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "42.0M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "cognism",
    "name": "Cognism",
    "domain": "cognism.com",
    "category": "lead-generation",
    "tagline": "Compliance-first B2B intelligence engine with verified mobile direct dials",
    "description": "Cognism offers phone-verified direct dials and global email contacts with strict GDPR and CCPA compliance controls. It is tailored for revenue teams targeting decision-makers across Europe and international markets.",
    "rating": 4.6,
    "reviewsCount": 850,
    "pricing": "Paid",
    "websiteUrl": "https://cognism.com",
    "affiliateUrl": "https://cognism.com",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "1.6M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "lusha",
    "name": "Lusha",
    "domain": "lusha.com",
    "category": "lead-generation",
    "tagline": "B2B contact finder browser extension for direct phone numbers and emails",
    "description": "Lusha delivers verified business emails and direct mobile numbers while reps browse LinkedIn profiles or company websites. It serves SDRs, recruiters, and account executives making direct cold calls.",
    "rating": 4.5,
    "reviewsCount": 1850,
    "pricing": "Freemium",
    "websiteUrl": "https://lusha.com",
    "affiliateUrl": "https://lusha.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "hunter-io",
    "name": "Hunter.io",
    "domain": "hunter.io",
    "category": "lead-generation",
    "tagline": "Fast professional email finder, domain search, and email deliverability verifier",
    "description": "Hunter locates professional contact email structures from company domain names and validates deliverability instantly. It is built for agencies, freelancers, and sales reps verifying outbound contact lists.",
    "rating": 4.6,
    "reviewsCount": 2400,
    "pricing": "Freemium",
    "websiteUrl": "https://hunter.io",
    "affiliateUrl": "https://hunter.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "5.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "clearbit",
    "name": "Clearbit (Breeze)",
    "domain": "clearbit.com",
    "category": "lead-generation",
    "tagline": "Real-time B2B data enrichment, lead scoring, and firmographic intelligence",
    "description": "Clearbit automatically enriches incoming CRM leads and anonymous website traffic with 100+ firmographic and technographic data points. It is engineered for marketing operations and sales strategy divisions.",
    "rating": 4.5,
    "reviewsCount": 1100,
    "pricing": "Paid",
    "websiteUrl": "https://clearbit.com",
    "affiliateUrl": "https://clearbit.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "seamless-ai",
    "name": "Seamless.AI",
    "domain": "seamless.ai",
    "category": "lead-generation",
    "tagline": "Real-time AI search engine for verified B2B emails and phone numbers",
    "description": "Seamless.AI uses real-time web scraping algorithms to research and verify direct phone numbers and emails for target decision-makers. It serves outbound sales teams looking for fresh contact information.",
    "rating": 4.4,
    "reviewsCount": 2900,
    "pricing": "Freemium",
    "websiteUrl": "https://seamless.ai",
    "affiliateUrl": "https://seamless.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "4.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "leadfeeder",
    "name": "Leadfeeder",
    "domain": "leadfeeder.com",
    "category": "lead-generation",
    "tagline": "Identify anonymous B2B website visitors and track buyer intent signals",
    "description": "Leadfeeder reveals the identities of companies visiting your website, tracking pageview activity and connecting accounts to contact details. It is designed for inbound sales and account-based marketing (ABM) teams.",
    "rating": 4.4,
    "reviewsCount": 920,
    "pricing": "Freemium",
    "websiteUrl": "https://leadfeeder.com",
    "affiliateUrl": "https://leadfeeder.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.9M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "uplead",
    "name": "UpLead",
    "domain": "uplead.com",
    "category": "lead-generation",
    "tagline": "B2B prospecting database featuring 95%+ real-time email verification accuracy",
    "description": "UpLead provides high-accuracy B2B prospect lists backed by real-time email verification right before credit deduction. It is built for sales development teams prioritizing low bounce rates.",
    "rating": 4.7,
    "reviewsCount": 740,
    "pricing": "Freemium",
    "websiteUrl": "https://uplead.com",
    "affiliateUrl": "https://uplead.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "950K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "snov-io",
    "name": "Snov.io",
    "domain": "snov.io",
    "category": "lead-generation",
    "tagline": "All-in-one cold outreach platform with email finder, verifier, and CRM",
    "description": "Snov.io combines email address searching, deliverability verification, automated drip sequences, and email warm-up utilities. It serves budget-conscious startups, freelancers, and small sales teams.",
    "rating": 4.6,
    "reviewsCount": 1650,
    "pricing": "Freemium",
    "websiteUrl": "https://snov.io",
    "affiliateUrl": "https://snov.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "rocketreach",
    "name": "RocketReach",
    "domain": "rocketreach.co",
    "category": "lead-generation",
    "tagline": "Uncover verified contact details and social links for professionals worldwide",
    "description": "RocketReach searches a database of over 700 million professionals to locate personal and work emails plus direct phone lines. It is tailored for recruiters, corporate sales, and market researchers.",
    "rating": 4.5,
    "reviewsCount": 1120,
    "pricing": "Freemium",
    "websiteUrl": "https://rocketreach.co",
    "affiliateUrl": "https://rocketreach.co",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "6.8M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "instantly-ai",
    "name": "Instantly",
    "domain": "instantly.ai",
    "category": "lead-generation",
    "tagline": "Scale cold email outreach with unlimited inbox warming and lead management",
    "description": "Instantly offers unlimited sending accounts, automated inbox warm-up, and lead campaign management to maximize cold email deliverability. It serves lead generation agencies and sales teams sending high-volume cold emails.",
    "rating": 4.9,
    "reviewsCount": 1820,
    "pricing": "Free Trial",
    "websiteUrl": "https://instantly.ai",
    "affiliateUrl": "https://instantly.ai",
    "badge": "Verified Tool",
    "featured": true,
    "monthlyVisits": "5.4M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "smartlead-ai",
    "name": "Smartlead",
    "domain": "smartlead.ai",
    "category": "lead-generation",
    "tagline": "Cold email infrastructure for lead generation agencies and multi-domain outreach",
    "description": "Smartlead provides automated mailbox warm-up, dynamic IP rotation, centralized master inboxes, and campaign automation. It is engineered for outbound agencies managing dozens of client sending domains.",
    "rating": 4.8,
    "reviewsCount": 910,
    "pricing": "Free Trial",
    "websiteUrl": "https://smartlead.ai",
    "affiliateUrl": "https://smartlead.ai",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "lemlist",
    "name": "lemlist",
    "domain": "lemlist.com",
    "category": "lead-generation",
    "tagline": "Personalized cold email, liquid syntax, and LinkedIn multichannel outreach",
    "description": "lemlist allows outbound teams to customize campaign emails using dynamic image personalization, video landing pages, and LinkedIn steps. It serves growth marketers and SDRs focusing on high response rates.",
    "rating": 4.6,
    "reviewsCount": 1350,
    "pricing": "Free Trial",
    "websiteUrl": "https://lemlist.com",
    "affiliateUrl": "https://lemlist.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "leadiq",
    "name": "LeadIQ",
    "domain": "leadiq.com",
    "category": "lead-generation",
    "tagline": "Capture LinkedIn prospect data and sync directly to CRMs with AI messaging",
    "description": "LeadIQ captures direct contact records, verifies emails, and drafts AI-generated outreach copy directly inside LinkedIn workflows. It is built for SDRs syncing prospect data straight into Salesforce or HubSpot.",
    "rating": 4.5,
    "reviewsCount": 680,
    "pricing": "Freemium",
    "websiteUrl": "https://leadiq.com",
    "affiliateUrl": "https://leadiq.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "kaspr",
    "name": "Kaspr",
    "domain": "kaspr.io",
    "category": "lead-generation",
    "tagline": "Get instant B2B phone numbers and work emails while browsing LinkedIn",
    "description": "Kaspr provides a Chrome extension that surfaces direct phone numbers and verified emails on LinkedIn profiles and group lists. It is tailored for European and global SDRs focusing on phone prospecting.",
    "rating": 4.6,
    "reviewsCount": 820,
    "pricing": "Freemium",
    "websiteUrl": "https://kaspr.io",
    "affiliateUrl": "https://kaspr.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.4M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "phantombuster",
    "name": "PhantomBuster",
    "domain": "phantombuster.com",
    "category": "lead-generation",
    "tagline": "No-code web scraping, social media automation, and list building growth tool",
    "description": "PhantomBuster automates data extraction and actions across LinkedIn, Twitter, and web directories using cloud scripts. It serves growth hackers and recruiters automating prospect scraping.",
    "rating": 4.5,
    "reviewsCount": 610,
    "pricing": "Free Trial",
    "websiteUrl": "https://phantombuster.com",
    "affiliateUrl": "https://phantombuster.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "evaboot",
    "name": "Evaboot",
    "domain": "evaboot.com",
    "category": "lead-generation",
    "tagline": "Export, clean, and locate emails from LinkedIn Sales Navigator searches in one click",
    "description": "Evaboot extracts search results from LinkedIn Sales Navigator, cleans up lead names, and verifies work email addresses automatically. It is built for SDRs and agencies scraping structured LinkedIn leads.",
    "rating": 4.8,
    "reviewsCount": 420,
    "pricing": "Freemium",
    "websiteUrl": "https://evaboot.com",
    "affiliateUrl": "https://evaboot.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "620K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "getprospect",
    "name": "GetProspect",
    "domain": "getprospect.com",
    "category": "lead-generation",
    "tagline": "B2B email finder extension and verified lead database for outbound sales",
    "description": "GetProspect finds professional email addresses based on company names, domain lists, or LinkedIn search exports. It is built for budget-conscious sales reps and growth agencies.",
    "rating": 4.5,
    "reviewsCount": 480,
    "pricing": "Freemium",
    "websiteUrl": "https://getprospect.com",
    "affiliateUrl": "https://getprospect.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "850K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "skrapp-io",
    "name": "Skrapp.io",
    "domain": "skrapp.io",
    "category": "lead-generation",
    "tagline": "B2B email lookup tool and domain search platform for outbound prospecting",
    "description": "Skrapp finds verified professional emails from company websites and LinkedIn profiles using waterfall enrichment. It serves SDRs, recruiters, and marketers needing fast email lookup.",
    "rating": 4.4,
    "reviewsCount": 540,
    "pricing": "Freemium",
    "websiteUrl": "https://skrapp.io",
    "affiliateUrl": "https://skrapp.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "920K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "findymail",
    "name": "Findymail",
    "domain": "findymail.com",
    "category": "lead-generation",
    "tagline": "Automated B2B email finder and scraper with zero bounce deliverability guarantee",
    "description": "Findymail scrapes and verifies hard-to-find professional email addresses directly from Sales Navigator and Apollo lists. It is engineered for outbound teams protecting domain reputation.",
    "rating": 4.8,
    "reviewsCount": 310,
    "pricing": "Paid",
    "websiteUrl": "https://findymail.com",
    "affiliateUrl": "https://findymail.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "410K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "neverbounce",
    "name": "NeverBounce",
    "domain": "neverbounce.com",
    "category": "lead-generation",
    "tagline": "Real-time email verification, bulk list cleaning, and bounce protection",
    "description": "NeverBounce scrubs invalid, disposable, and catch-all email addresses from prospect lists in bulk before campaign launch. It is designed for email marketers and outbound sales teams.",
    "rating": 4.6,
    "reviewsCount": 1450,
    "pricing": "Freemium",
    "websiteUrl": "https://neverbounce.com",
    "affiliateUrl": "https://neverbounce.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "zero-bounce",
    "name": "ZeroBounce",
    "domain": "zerobounce.net",
    "category": "lead-generation",
    "tagline": "Enterprise email validation, inbox placement testing, and spam trap detection",
    "description": "ZeroBounce validates email contact lists while identifying spam traps, abuse emails, and catch-all servers. It serves enterprise marketers and outbound agencies protecting domain deliverability.",
    "rating": 4.7,
    "reviewsCount": 1150,
    "pricing": "Freemium",
    "websiteUrl": "https://zerobounce.net",
    "affiliateUrl": "https://zerobounce.net",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.6M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "bounceless",
    "name": "BounceBan",
    "domain": "bounceban.com",
    "category": "lead-generation",
    "tagline": "The only email verifier specialized in verifying catch-all email addresses",
    "description": "BounceBan accurately verifies catch-all and accept-all email domains that standard verifiers fail to validate. It serves outbound teams looking to expand deliverable email lists safely.",
    "rating": 4.8,
    "reviewsCount": 290,
    "pricing": "Freemium",
    "websiteUrl": "https://bounceban.com",
    "affiliateUrl": "https://bounceban.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "380K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "ocean-io",
    "name": "Ocean.io",
    "domain": "ocean.io",
    "category": "lead-generation",
    "tagline": "AI account discovery and lookalike domain search for B2B sales teams",
    "description": "Ocean.io uses machine learning to scan target company website text and identify ideal lookalike client accounts. It is tailored for B2B sales teams running account-based prospecting campaigns.",
    "rating": 4.6,
    "reviewsCount": 180,
    "pricing": "Paid",
    "websiteUrl": "https://ocean.io",
    "affiliateUrl": "https://ocean.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "210K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "dealfront",
    "name": "Dealfront (Leadfeeder)",
    "domain": "dealfront.com",
    "category": "lead-generation",
    "tagline": "European B2B sales intelligence, website visitor tracking, and compliance data",
    "description": "Dealfront combines GDPR-compliant European company databases with real-time website visitor identification. It serves sales and marketing teams prospecting across Europe.",
    "rating": 4.5,
    "reviewsCount": 890,
    "pricing": "Paid",
    "websiteUrl": "https://dealfront.com",
    "affiliateUrl": "https://dealfront.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "rb2b",
    "name": "RB2B",
    "domain": "rb2b.com",
    "category": "lead-generation",
    "tagline": "Person-level US website visitor identification delivered directly to Slack",
    "description": "RB2B identifies specific individual US website visitors and pushes their LinkedIn profile data directly into team Slack channels. It is designed for US B2B SaaS teams capturing high-intent traffic.",
    "rating": 4.7,
    "reviewsCount": 240,
    "pricing": "Freemium",
    "websiteUrl": "https://rb2b.com",
    "affiliateUrl": "https://rb2b.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "albacross",
    "name": "Albacross",
    "domain": "albacross.com",
    "category": "lead-generation",
    "tagline": "B2B account intelligence, website visitor identification, and intent tracking",
    "description": "Albacross reveals corporate site traffic, enriches visiting accounts with firmographic data, and measures buyer intent. It serves B2B marketing teams running targeted ABM programs.",
    "rating": 4.5,
    "reviewsCount": 380,
    "pricing": "Free Trial",
    "websiteUrl": "https://albacross.com",
    "affiliateUrl": "https://albacross.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "340K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "snitcher",
    "name": "Snitcher",
    "domain": "snitcher.com",
    "category": "lead-generation",
    "tagline": "B2B lead generation engine tracking anonymous website visitors and intent",
    "description": "Snitcher identifies company IP addresses visiting web pages and scores their intent based on browsing depth. It is built for sales development reps following up with warm website leads.",
    "rating": 4.8,
    "reviewsCount": 210,
    "pricing": "Free Trial",
    "websiteUrl": "https://snitcher.com",
    "affiliateUrl": "https://snitcher.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "290K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "salesloft",
    "name": "Salesloft",
    "domain": "salesloft.com",
    "category": "lead-generation",
    "tagline": "AI-powered revenue orchestration, sales cadence, and deal tracking platform",
    "description": "Salesloft organizes multi-touch outreach cadences across email, phone, and LinkedIn while tracking deal health. It is engineered for mid-market and enterprise sales organizations.",
    "rating": 4.5,
    "reviewsCount": 3800,
    "pricing": "Paid",
    "websiteUrl": "https://salesloft.com",
    "affiliateUrl": "https://salesloft.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "6.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "outreach-io",
    "name": "Outreach",
    "domain": "outreach.io",
    "category": "lead-generation",
    "tagline": "Enterprise sales execution platform for prospecting, cadences, and pipeline intelligence",
    "description": "Outreach provides SDRs and AEs with automated multi-channel sequences, meeting scheduling, and AI pipeline forecasting. It serves enterprise revenue organizations scaling sales rep output.",
    "rating": 4.3,
    "reviewsCount": 3200,
    "pricing": "Paid",
    "websiteUrl": "https://outreach.io",
    "affiliateUrl": "https://outreach.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "5.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "mailshake",
    "name": "Mailshake",
    "domain": "mailshake.com",
    "category": "lead-generation",
    "tagline": "Sales engagement platform combining cold email, phone dialer, and social steps",
    "description": "Mailshake automates cold email campaigns, integrated VoIP calling, and LinkedIn tasks in a unified interface. It is tailored for sales teams, agencies, and founders generating outbound meetings.",
    "rating": 4.7,
    "reviewsCount": 650,
    "pricing": "Paid",
    "websiteUrl": "https://mailshake.com",
    "affiliateUrl": "https://mailshake.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "890K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "reply-io",
    "name": "Reply.io",
    "domain": "reply.io",
    "category": "lead-generation",
    "tagline": "AI sales engagement platform for multichannel outreach and lead discovery",
    "description": "Reply.io combines B2B prospect discovery with AI-generated multichannel email and LinkedIn messaging sequences. It is built for SDR teams and agencies automating outreach workflows.",
    "rating": 4.6,
    "reviewsCount": 1100,
    "pricing": "Freemium",
    "websiteUrl": "https://reply.io",
    "affiliateUrl": "https://reply.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "1.2M",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "klenty",
    "name": "Klenty",
    "domain": "klenty.com",
    "category": "lead-generation",
    "tagline": "Sales engagement platform built specifically to execute multi-channel outreach from CRMs",
    "description": "Klenty integrates directly into Salesforce, HubSpot, and Pipedrive to execute personalized email, call, and LinkedIn sequences. It serves sales reps automating follow-ups within CRM pipelines.",
    "rating": 4.6,
    "reviewsCount": 380,
    "pricing": "Free Trial",
    "websiteUrl": "https://klenty.com",
    "affiliateUrl": "https://klenty.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "580K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "quickmail",
    "name": "QuickMail",
    "domain": "quickmail.io",
    "category": "lead-generation",
    "tagline": "Cold email automation platform designed for high deliverability and agency scaling",
    "description": "QuickMail manages multi-inbox cold email campaigns with automated deliverability monitoring and inbox rotation. It is built for lead generation agencies and B2B sales teams.",
    "rating": 4.6,
    "reviewsCount": 320,
    "pricing": "Free Trial",
    "websiteUrl": "https://quickmail.io",
    "affiliateUrl": "https://quickmail.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "450K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "woodpecker-co",
    "name": "Woodpecker",
    "domain": "woodpecker.co",
    "category": "lead-generation",
    "tagline": "Cold email and follow-up automation software with deliverability protection",
    "description": "Woodpecker schedules human-like cold email sequences, automated follow-ups, and inbox warm-up routines. It serves B2B agencies and sales reps protecting sender domain reputation.",
    "rating": 4.5,
    "reviewsCount": 620,
    "pricing": "Free Trial",
    "websiteUrl": "https://woodpecker.co",
    "affiliateUrl": "https://woodpecker.co",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "820K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "optinmonster",
    "name": "OptinMonster",
    "domain": "optinmonster.com",
    "category": "lead-generation",
    "tagline": "Lead capture popup builder and website conversion rate optimization tool",
    "description": "OptinMonster converts website traffic into leads using Exit-Intent popups, slide-ins, and targeted lead forms. It is tailored for e-commerce marketers, bloggers, and digital agencies.",
    "rating": 4.5,
    "reviewsCount": 2100,
    "pricing": "Paid",
    "websiteUrl": "https://optinmonster.com",
    "affiliateUrl": "https://optinmonster.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "3.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "leadpages",
    "name": "Leadpages",
    "domain": "leadpages.com",
    "category": "lead-generation",
    "tagline": "Conversion-focused landing page builder and lead capture software",
    "description": "Leadpages builds high-converting landing pages, alert bars, and popups with built-in lead generation checkouts. It serves small business owners, consultants, and digital marketers.",
    "rating": 4.5,
    "reviewsCount": 1850,
    "pricing": "Free Trial",
    "websiteUrl": "https://leadpages.com",
    "affiliateUrl": "https://leadpages.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.8M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "unbounce",
    "name": "Unbounce",
    "domain": "unbounce.com",
    "category": "lead-generation",
    "tagline": "AI-powered landing page builder and smart traffic lead optimization tool",
    "description": "Unbounce generates personalized landing pages and uses Smart Traffic AI routing to increase PPC lead conversions. It is built for performance marketers and digital advertising agencies.",
    "rating": 4.4,
    "reviewsCount": 1620,
    "pricing": "Free Trial",
    "websiteUrl": "https://unbounce.com",
    "affiliateUrl": "https://unbounce.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "2.1M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "dripify",
    "name": "Dripify",
    "domain": "dripify.io",
    "category": "lead-generation",
    "tagline": "Multichannel LinkedIn automation and sales prospecting platform",
    "description": "Dripify executes automated LinkedIn connection requests, drip messages, and lead tracking on complete autopilot. It is designed for SDRs and recruiters seeking automated social selling.",
    "rating": 4.6,
    "reviewsCount": 580,
    "pricing": "Free Trial",
    "websiteUrl": "https://dripify.io",
    "affiliateUrl": "https://dripify.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "780K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "hey-reach",
    "name": "HeyReach",
    "domain": "heyreach.io",
    "category": "lead-generation",
    "tagline": "Scale LinkedIn outreach safely using multi-account rotation and agency controls",
    "description": "HeyReach rotates outreach campaigns across multiple team LinkedIn accounts to bypass weekly connection limits safely. It is engineered for lead generation agencies scaling LinkedIn campaigns.",
    "rating": 4.8,
    "reviewsCount": 210,
    "pricing": "Free Trial",
    "websiteUrl": "https://heyreach.io",
    "affiliateUrl": "https://heyreach.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "320K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "aeroleads",
    "name": "AeroLeads",
    "domain": "aeroleads.com",
    "category": "lead-generation",
    "tagline": "B2B contact finder tool for finding emails and business phone numbers",
    "description": "AeroLeads finds work emails and phone numbers from corporate websites and LinkedIn directories. It is built for sales reps, small business owners, and list builders.",
    "rating": 4.3,
    "reviewsCount": 380,
    "pricing": "Freemium",
    "websiteUrl": "https://aeroleads.com",
    "affiliateUrl": "https://aeroleads.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "480K",
    "isFreeTier": true,
    "isOpenSource": false
  },
  {
    "id": "leadfuze",
    "name": "LeadFuze",
    "domain": "leadfuze.com",
    "category": "lead-generation",
    "tagline": "Automated B2B lead generation engine with AI list-building bots",
    "description": "LeadFuze uses AI bots to automatically locate target prospects matching specific role criteria and sync them to CRMs. It serves outbound agencies and sales teams.",
    "rating": 4.5,
    "reviewsCount": 320,
    "pricing": "Free Trial",
    "websiteUrl": "https://leadfuze.com",
    "affiliateUrl": "https://leadfuze.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "290K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "adapt-io",
    "name": "Adapt.io",
    "domain": "adapt.io",
    "category": "lead-generation",
    "tagline": "B2B contact database, lead enrichment, and prospect list builder",
    "description": "Adapt.io provides access to millions of company contact profiles alongside CRM enrichment and API tools. It is built for sales development reps and marketing teams.",
    "rating": 4.4,
    "reviewsCount": 290,
    "pricing": "Free Trial",
    "websiteUrl": "https://adapt.io",
    "affiliateUrl": "https://adapt.io",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "350K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "salesgenie",
    "name": "Salesgenie",
    "domain": "salesgenie.com",
    "category": "lead-generation",
    "tagline": "Targeted B2B prospect lists, business contact data, and marketing campaigns",
    "description": "Salesgenie gives businesses access to verified corporate and consumer contact databases for targeted prospecting. It serves SMB sales reps and field marketing managers.",
    "rating": 4.3,
    "reviewsCount": 210,
    "pricing": "Free Trial",
    "websiteUrl": "https://salesgenie.com",
    "affiliateUrl": "https://salesgenie.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "280K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "pipedrive-leadbooster",
    "name": "LeadBooster by Pipedrive",
    "domain": "pipedrive.com/en/products/leadbooster",
    "category": "lead-generation",
    "tagline": "Inbound chatbot, web forms, prospector, and live chat toolkit for Pipedrive CRM",
    "description": "LeadBooster captures inbound site leads using conversational bots, web forms, and outbound B2B database prospecting. It is designed for Pipedrive users filling their sales pipeline.",
    "rating": 4.6,
    "reviewsCount": 1850,
    "pricing": "Paid",
    "websiteUrl": "https://pipedrive.com/en/products/leadbooster",
    "affiliateUrl": "https://pipedrive.com/en/products/leadbooster",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "11.2M",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "rollworks",
    "name": "RollWorks",
    "domain": "rollworks.com",
    "category": "lead-generation",
    "tagline": "Account-based marketing (ABM) platform for target account identification and ads",
    "description": "RollWorks identifies high-fit target accounts, runs targeted display ad campaigns, and tracks intent signals. It is built for mid-market B2B revenue teams executing ABM strategies.",
    "rating": 4.3,
    "reviewsCount": 520,
    "pricing": "Paid",
    "websiteUrl": "https://rollworks.com",
    "affiliateUrl": "https://rollworks.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "380K",
    "isFreeTier": false,
    "isOpenSource": false
  },
  {
    "id": "bombora",
    "name": "Bombora",
    "domain": "bombora.com",
    "category": "lead-generation",
    "tagline": "B2B intent data platform revealing company research activity across the web",
    "description": "Bombora measures target company content consumption to alert sales teams when accounts actively research solutions. It serves enterprise ABM leaders prioritizing ready-to-buy leads.",
    "rating": 4.5,
    "reviewsCount": 240,
    "pricing": "Paid",
    "websiteUrl": "https://bombora.com",
    "affiliateUrl": "https://bombora.com",
    "badge": "Verified Tool",
    "featured": false,
    "monthlyVisits": "310K",
    "isFreeTier": false,
    "isOpenSource": false
  }
];

const saasDataPath = path.join(__dirname, '..', 'src', 'data', 'saasData.jsx');
let content = fs.readFileSync(saasDataPath, 'utf8');

const match = content.match(/export const staticSaasTools = (\[[\s\S]*?\n\]);/);
if (!match) {
  console.error('Could not find staticSaasTools in saasData.jsx');
  process.exit(1);
}

let existingTools = JSON.parse(match[1]);

const existingIds = new Set(existingTools.map(t => t.id.toLowerCase()));
const existingNames = new Set(existingTools.map(t => t.name.toLowerCase()));

let addedCount = 0;
let skippedCount = 0;

newTools.forEach(tool => {
  const normId = tool.id.toLowerCase();
  const normName = tool.name.toLowerCase();

  if (!existingIds.has(normId) && !existingNames.has(normName)) {
    existingTools.push(tool);
    existingIds.add(normId);
    existingNames.add(normName);
    addedCount++;
  } else {
    // Enrich existing tool without creating a duplicate
    const idx = existingTools.findIndex(t => t.id.toLowerCase() === normId || t.name.toLowerCase() === normName);
    if (idx !== -1) {
      existingTools[idx] = { ...existingTools[idx], category: tool.category, tagline: tool.tagline || existingTools[idx].tagline };
    }
    skippedCount++;
  }
});

const updatedArrayStr = JSON.stringify(existingTools, null, 2);
content = content.replace(/export const staticSaasTools = \[[\s\S]*?\n\];/, `export const staticSaasTools = ${updatedArrayStr};`);

fs.writeFileSync(saasDataPath, content, 'utf8');
console.log(`Ingestion Complete! Added: ${addedCount} brand new tools | Deduplicated: ${skippedCount} existing tools | Total static tools: ${existingTools.length}`);
